- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
- WORKSPACE.bazel
Run `build-determinism` checks on `ubuntu-latest`.
Adding `git config http.postBuffer 524288000` in `before-script` to address the git issues:
```
Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
Error: fatal: the remote end hung up unexpectedly
Error: fatal: early EOF
Error: fatal: index-pack failed
```
> chore(IDX): bd on ubuntu-latest

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
Filter needs to be conditional.
> chore(IDX): cargo-filter update

- .github/workflows-source/ci-pr-only.yml
- .github/workflows/ci-pr-only-cov.yml
- .github/workflows/ci-pr-only.yml
- WORKSPACE.bazel
Conventional Commit In Pull Requests GitHub Action.
> feat(CI): PR title cov workflow

- .github/workflows/gitlab-push.yml
We push entire branch. Commits will get squashed in GitLab.
> fix(IDX): push to gitlab

- .github/workflows/gitlab-sync-branches.yml
Sync when there's no workflows in merge queue.
> chore(IDX): sync from gitlab

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
System wide config is in CI container image.
> chore(IDX): cleanup

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
- .github/workflows/gitlab-push.yml
- .github/workflows/gitlab-sync-branches.yml
- .github/workflows/schedule-daily.yml
- .github/workflows/tag-release.yml
Now that we are using dind runners we can upgrade gh actions.
> chore(IDX): upgrade gh actions

- .github/workflows-source/ci-main.yml
- .github/workflows-source/ci-pr-only.yml
- .github/workflows-source/schedule-hourly.yml
- .github/workflows/ci-main.yml
- .github/workflows/ci-pr-only.yml
- .github/workflows/release-testing.yml
- .github/workflows/schedule-hourly.yml
- .github/workflows/schedule-weekly.yml
Image `sha256:5bd0f059ad6e21966e9c644516b6ecd52d5ed44f1b18a76b91b59740a9d639a2` shouldn't have been changed.
Reverts dfinity/ic#236
> chore(IDX): revert PR236

- .github/workflows-source/ci-main.yml
- .github/workflows-source/ci-pr-only.yml
- .github/workflows-source/schedule-hourly.yml
- .github/workflows/ci-main.yml
- .github/workflows/ci-pr-only.yml
- .github/workflows/release-testing.yml
- .github/workflows/schedule-daily.yml
- .github/workflows/schedule-hourly.yml
- .github/workflows/schedule-weekly.yml
Switch to `dind-large` runner group.
> chore(IDX): dind large group

- .github/workflows/schedule-weekly.yml
Adding missing env vars. Run workflow in the PR when it's definition changes.
> fix(IDX): weekly workflow envs

- .github/workflows-source/schedule-hourly.yml
- .github/workflows/schedule-hourly.yml
Fixing bazel options for scheduled hourly workflow. Changes to run it in the PR when the definition changes.
> chore(IDX): config change for schedule-hourly

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
Once we switch everyone to GitHub we'll revert this change but before that it's beneficial to have it.
> chore(IDX): no execution_environment_test on darwin

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
> revert(IDX): no execution_environment_test on darwin

- rs/consensus/tests/framework/mod.rs
- rs/consensus/tests/integration.rs
Following [this conversation](https://github.com/dfinity/ic/pull/282#issuecomment-2196888292), the framework tests in consensus need to be more precise.
> chore(CON-1302): Make consensus framework tests more precise

- rs/boundary_node/certificate_issuance/certificate_issuer/src/check.rs
> fix(custom domains): ignore leading and trailing whitespaces when checking domain names

- .github/workflows/ci-main.yml
- .github/workflows/slack-workflow-queue.yml
Scheduled workflow on `ubuntu-latest` that sends slack notification to `eng-idx-alerts` if there are any workflows in wait queue.
> feat(IDX): wait queue notifications

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/9966743879
> chore: Update Base Image Refs [2024-07-17-0147]

- .github/workflows/slack-workflow-queue.yml
Run every 20 min until we start with new darwin runners (2-3 weeks).
> chore(IDX): changing schedule

- .github/workflows/ci-notify-slack.yml
- .github/workflows/team-channels.json
Adding SDK team. Handling missing team.
> fix(IDX): codeowners and notifications

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/10016528020
> chore: Update Base Image Refs [2024-07-20-0145]

- rs/registry/canister/src/mutations/node_management/common.rs
This optimizes get_key_family in the registry to avoid unnecessary iteration.
> fix(registry): Optimize get_key_family

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
- gitlab-ci/src/git_changes/git_changes_test.py
Reverts dfinity/ic#534
These tests are failing on master, need to look at them again before enabling them.
> revert: "fix(IDX): exclude certain tests from the merge train"

- rs/ethereum/cketh/mainnet/orchestrator_upgrade_2024_07_22.md
(XC-148): Proposal to upgrade the ledger suite orchestrator and all managed ledger suites to the latest release candidate `rc--2024-07-18_01-30--github` (`de29a1a55b589428d173b31cdb8cec0923245657`)
> chore(ckerc20): NNS proposal to upgrade ledger suite orchestrator

- .github/workflows/system-tests-k8s.yml
Adding a schedule for system tests on k8s.
> chore(IDX): k8s system tests schedule

- rs/boundary_node/ic_boundary/src/log.rs
`then_some` is eagerly evaluated. This is problematic on systems that don't have `systemd-journald` (e.g., container environments). Switching to `then` solves that as it is lazily evaluated.
> fix(ic-boundary): switch logging setup from eager to lazy eval

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/10190492912
> chore: Update Base Image Refs [2024-08-01-0150]

- testnet/mainnet_revisions.json
tdb26: https://dashboard.internetcomputer.org/proposal/131479
io67a: https://dashboard.internetcomputer.org/proposal/131481
> chore: Manually update `testnet/mainnet_revisions.json`

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/10258796973
> chore: Update Base Image Refs [2024-08-06-0146]

- rs/registry/admin/src/create_subnet.rs
This is a follow up to https://github.com/dfinity/ic/pull/441. After the [upgrade of registry canister](https://dashboard.internetcomputer.org/proposal/131397) to a version that includes the previous commit that removes the instructions limit from the subnet record, it's now safe to update `ic-admin` to use the same struct that does not include the fields anymore.
> chore: Remove copy of CreateSubnetPayload in ic-admin

- rs/async_utils/Cargo.toml
- rs/bitcoin/adapter/Cargo.toml
- rs/bitcoin/client/Cargo.toml
- rs/canister_client/Cargo.toml
- rs/config/Cargo.toml
- rs/replica/Cargo.toml
- rs/starter/Cargo.toml
This PR sorts the dependencies in `Cargo.toml` files.
> chore: sort dependencies in networking Cargo.toml files

- rs/crypto/Cargo.toml
- rs/test_utilities/in_memory_logger/Cargo.toml
This PR sorts the dependencies in `Cargo.toml` files.
> chore: sort dependencies in crypto Cargo.toml files

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/10400720724
> chore: Update Base Image Refs [2024-08-15-0808]

- rs/rosetta-api/ledger_canister_blocks_synchronizer/src/blocks.rs
This MR adds the following changes:
1. Add an index for searching block hashes
2. Add an index for searching transaction hashes
3. Add an index for block index on the account balance table
> chore(ICP-Rosetta): FI-1419: add indices

- packages/pocket-ic/src/common/rest.rs
- packages/pocket-ic/src/nonblocking.rs
- rs/pocket_ic_server/CHANGELOG.md
- rs/pocket_ic_server/src/state_api/routes.rs
- rs/pocket_ic_server/src/state_api/state.rs
- rs/rosetta-api/icp_ledger/rosetta-integration-tests/tests/tests.rs
This PR adds support for an artificial delay in auto progress mode of PocketIC specifying the minimum delay between consecutive rounds in auto progress mode.
> feat(PocketIC): artificial delay in auto progress mode of PocketIC

- rs/rosetta-api/icrc1/rosetta/runner/src/lib.rs
- rs/rosetta-api/icrc1/rosetta/src/main.rs
- rs/rosetta-api/icrc1/rosetta/tests/system_tests.rs
1. Add a check for the passed icrc1 symbol
> feat(ICP-Rosetta): FI-1408: add symbol check

- rs/state_manager/src/manifest/split/tests.rs
This commits modifies the unit tests for the splitting of the manifest for subnet splitting, by including a file related to canister snapshots, and verifying that it is correctly assigned.
> test: Add snapshots to subnet split manifest test

- rs/replicated_state/src/metadata_state.rs
Previously hidden by `queues::MemoryUsageStats`' custom `PartialEq` implementation (that ignored `transient_stream_responses_size_bytes`); and not triggered by the original `StreamHandler` tests (that cloned the state before any streams were populated); this suddenly started causing test failures with the combination of new `StreamHandler` test fixtures and `queues::QueueStats` that include `transient_stream_responses_size_bytes` in equality comparisons.
The issue is that `responses_size_bytes` is only supposed to have its zero values pruned after they have been applied to the corresponding canisters' `transient_stream_responses_size_bytes`. Simply wiping them clean when replacing the streams left canisters with outdated non-zero `transient_stream_responses_size_bytes` fields.
Instead, …
> fix: Fix bug in StreamsTesting fixture

- rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
- rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
- rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
The comments on the new topics and proposal types should be consistent with ICP dashboard and NNS Dapp.
Modify comments on the new topics and proposals.
> chore(nns): Make the comments on the topics and proposals consistent with NNS Dapp and ICP Dashboard

- rs/pocket_ic_server/src/state_api/state.rs
This PR makes PocketIC block during instance deletion until PocketIC is dropped and the state_dir written to disk. Before this PR, the instance deletion could return early (before the state_dir is written to disk) if the instance is busy.
> chore(PocketIC): block in instance deletion until PocketIC is dropped

- rs/messaging/src/routing/stream_handler/tests.rs
When tracking the `available_guaranteed_response_memory` GC-ed responses are ignored. Therefore when comparing this to the computed value and adjusting for this fact, only the right response will correctly compensate. Without this change all responses have the same size and so a test could pass but actually use the wrong message for memory checks.
> test: Make payload size unique for all messages in StreamHandler tests.

- .github/workflows/ci-notify-slack.yml
Works as expected now: https://github.com/dfinity/ic/actions/runs/10504957667/job/29101512776?pr=1063
> fix(IDX): syntax error

- rs/nns/governance/src/lib.rs
Closes [NNS1-3252](https://dfinity.atlassian.net/browse/NNS1-3252).
[NNS1-3252]: https://dfinity.atlassian.net/browse/NNS1-3252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(nns): Flip flag to enabled SetVisibility proposals.

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/10504152142
> chore: Update Base Image Refs [2024-08-22-0808]

- rs/consensus/src/dkg/payload_builder.rs
- rs/consensus/src/dkg/payload_validator.rs
- rs/consensus/src/dkg/utils.rs
We now also check that we don't have multiple dealings from the same dealer in the payload
> chore(consensus): add more checks to the dkg payload validator

- .github/workflows/schedule-daily.yml
Fixes changes introduced in a previous PR adding some FI tests to `schedule-daily.yml`.
> fix(ICP_ledger): Remove double if in schedule-daily.yml

- Cargo.lock
- rs/nns/handlers/root/impl/BUILD.bazel
- rs/nns/handlers/root/impl/Cargo.toml
Removing an unused dependency on governance in NNS root.
> chore(nns): Remove unused dependency

- .github/scripts/generate-ci.py
- .github/workflows-source/schedule-daily.yml
- .github/workflows/ci-generate-ci.yml
If only the workflows file is updated without `workflows-source` it can cause errors later on.
PR reference: https://github.com/dfinity/ic/pull/1097
> chore(IDX): Fix workflow daily

- rs/nns/governance/canister/canister.rs
The `_pb` methods are deprecated and we'd like to get rid of them. A clear and easier alternative already exists (methods without `_pb` suffix).
Panicking with a given probability before executing the methods.
> chore(nns): Introduce random panics in deprecated _pb methods

- rs/nns/test_utils/golden_nns_state/src/lib.rs
Most of the time is spent on downloading and decompressing the state. Caching it will make debugging faster.
When `USE_CACHED_STATE_DIR` is provided as an environment variable, the test will first check whether a `nns_state` directory already exists, and use it instead of downloading and decompressing again. If the directory does not exist, then download and decompress to the cached state directory. Note that there is no mechanism for cleaning the cache within the test itself, but can be done by simply cleaning the directoy.
> test(nns): Support caching of the golden NNS state when running the `upgrade_canisters_with_golden_nns_state` test

- .github/workflows/ci-main.yml
- .github/workflows/ci-pr-only-team-tags.yml
> chore(IDX): base branch restriction for PR labels

- .github/workflows/system-tests-k8s.yml
Bumping timeout to 6 hours. Setting parallel jobs to 7.
> chore(IDX): k8s system tests timeout/jobs

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/10611072561
> chore: Update Base Image Refs [2024-08-29-0808]

- rs/cycles_account_manager/src/lib.rs
- rs/execution_environment/src/canister_manager.rs
> chore: EXC-1692: Refactor canister snapshot charges

- ic-os/components/setupos-scripts/hardware.sh
The current node deployment path verification warning was causing confusion: https://matrix.to/#/!jUsknEqNdJobySpXuN:matrix.org/$3rwsIDadeI2ogmKw4nP8rriuevl83WlYd9sBX7dJqus?via=matrix.org&via=greensteps.cn&via=rudd-o.com
> chore: update node deployment path verification warning

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
Setting `CI_COMMIT_BRANCH` that is still used in some parts of our CI.
> fix(IDX): CI_COMMIT_BRANCH

- rs/registry/canister/src/invariants/endpoint.rs
- rs/registry/canister/src/mutations/prepare_canister_migration.rs
This PR enforces Node network address-related Registry invariant checks.
> feat(registry): Enforce Node network address-related Registry invariant checks

- rs/nns/governance/src/neuron/mod.rs
- rs/nns/governance/src/neuron_store.rs
- rs/nns/governance/src/neuron_store/neuron_store_tests.rs
Remove range_heap_neurons as it's not used anywhere
> chore(nns): remove unused method from NeuronStore

- rs/nns/cmc/src/exchange_rate_canister.rs
The function get_next_multiply_of is unnecessarily complex.
Refactor and add some reasoning as comments.
> chore(cmc): Simplify get_next_multiply_of

- rs/sns/governance/src/governance.rs
Avoid unnecessary neuron clone operations.
Move the filter originally after cloning all the neurons, into the process of finding the neurons to clone
Tests `test_disburse_maturity_*` in the same file already has decent coverage. This change is entirely a refactoring in terms of functionality.
> fix(sns): Avoid unnecessary neuron copies for those not ready to disburse yet

- .github/workflows-source/schedule-daily.yml
- .github/workflows/schedule-daily.yml
Removing as this is breaking on Linux machine runner: see [this](https://github.com/dfinity/ic/actions/runs/10712253519/job/29702343274) run.
> fix(IDX): daily schedule

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/10792107176
> chore: Update Base Image Refs [2024-09-10-1216]

- Cargo.lock
- rs/async_utils/src/lib.rs
- rs/http_endpoints/metrics/src/lib.rs
- rs/http_endpoints/public/src/lib.rs
- rs/replica/src/setup_ic_stack.rs
- rs/xnet/endpoint/BUILD.bazel
- rs/xnet/endpoint/Cargo.toml
- rs/xnet/endpoint/src/lib.rs
- rs/xnet/endpoint/src/tests.rs
Revert 5d25ae6b6c6daac78c580c5fba5a98927fc9408e because some flakiness on the xnet slo 120 test
> revert: 5d25ae6b6c6daac78c580c5fba5a98927fc9408e

- rs/nns/cmc/src/main.rs
The CMC state migration was done a long time ago. The migration code should be cleaned up to avoid confusion for the readers.
* Clean up the code path where the state version does not exist
* Add comments about adding migration code in the future
> chore(cmc): Clean up the CMC state migration code

- .github/workflows-source/schedule-hourly.yml
- .github/workflows/schedule-hourly.yml
Fixing broken schedule hourly workflow [see [here](https://github.com/dfinity/ic/actions/runs/10813330596/job/29997108624)].
> fix(schedule-hourly): env var

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/10826656444
> chore: Update Base Image Refs [2024-09-12-0807]

- ci/bazel-scripts/main.sh
If the branch is protected, automatically run on all targets.
> fix(IDX): update RUN_ON_DIFF_ONLY logic

- rs/replica/src/setup_ic_stack.rs
> feat(call-v3): [NET-1754] Enable synchronous call handler for all Application subnets

- ic-os/dev-tools/bare_metal_deployment/benchmark_driver.sh
- ic-os/dev-tools/bare_metal_deployment/deploy.py
- Switch file share mounting to http
- Fix bash expansion of lists
> fix: Nightly benchmarking followups

- ic-os/dev-tools/bare_metal_deployment/deploy.py
Previously, the deployment would continue even if media attachment failed, which could sometimes lead to false positives.
> fix: [NODE-1476] Add stronger failures to bare metal deployment

- rs/nervous_system/docs/proposal_verification.md
- testnet/tools/nns-tools/lib/proposals.sh
Instead of inlining such instructions.
(FWIW, Arshavir said he likes this idea.)
Make proposals shorter. Reduce repetition. Explain with more details. Embed videos that we recently made.
> feat(nervous-system-tools): Link to instructions on how to verify * nervous system proposals.

- rs/state_manager/src/lib.rs
We observed on some subnets with many canisters that they can slow down slightly (up to 20%) as more and more canisters receive messages, only for a replica restart to speed things up again.
This PR addresses this by cleaning up the memory layout of the canisters map during checkpointing, i.e. every 500 rounds. This data structure is iterated over often, and during message execution we remove and re-add element to this map, worsening the memory layout each time.
> perf: Defragment memory during checkpointing

- ci/bazel-scripts/main.sh
Don't use git revision with use of `CI_ALL_BAZEL_TARGETS`.
> fix(IDX): S3 upload

- rs/execution_environment/src/scheduler.rs
Addressing community comment: https://github.com/dfinity/ic/commit/a8464ac479913fe1b369228ad7c57f96f14c334e#r147358162
> chore: EXC-1737: Update comments

- rs/rosetta-api/BUILD.bazel
- rs/rosetta-api/tests/system_tests/test_cases/search_transactions.rs
This MR introduces the changes:
- Fix flakiness in system test of ICP Rosetta
> fix(ICP-Rosetta): fix flakyness

- Cargo.lock
- rs/bitcoin/kyt/BUILD.bazel
- rs/bitcoin/kyt/Cargo.toml
- rs/bitcoin/kyt/btc_kyt_canister.did
- rs/bitcoin/kyt/src/fetch.rs
- rs/bitcoin/kyt/src/fetch/tests.rs
- rs/bitcoin/kyt/src/lib.rs
- rs/bitcoin/kyt/src/main.rs
- rs/bitcoin/kyt/src/providers.rs
- rs/bitcoin/kyt/src/state.rs
- rs/bitcoin/kyt/src/types.rs
- rs/bitcoin/kyt/tests/tests.rs
XC-188: Initialize KYT canister with the bitcoin network type, and support fetching testnet transactions for testing purposes.
> feat(ckbtc): Initialize the new KYT canister with network type

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/11114269566
> chore: Update Base Image Refs [2024-09-30-2122]

- rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2024_09_27.md
- rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2024_09_27.md
- rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2024_09_27.md
Proposals to upgrade the ckBTC ledger suite (index, ledger and archive canisters) to `rc--2024-09-14_01-30` (commit `d4ee25b0865e89d3eaac13a60f0016d5e3296b31`)
> chore(ckbtc): Proposals to upgrade ckBTC ledger suite

- ic-os/boundary-guestos/context/Dockerfile
> Bump ic-gateway version

- rs/tests/dashboards/IC/execution-metrics.json
This PR updates "Execution Metrics" testnet grafana dashboards to be up-to-date with same dashboards in prod.
> chore: update testnet execution dashboards

- ic-os/boundary-guestos/context/Dockerfile
- ic-os/boundary-guestos/context/Dockerfile.base
In 24.04 it's shipped as a separate package
> fix(BOUN-1250): ubuntu: add systemd-resolved

- Cargo.lock
- rs/ledger_suite/icrc1/BUILD.bazel
- rs/ledger_suite/icrc1/Cargo.toml
- rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
- rs/ledger_suite/tests/sm-tests/src/lib.rs
Refactor the ICRC golden state test in preparation for adding upgrade and downgrade of the other ledger suite canisters (index, archives).
> refactor(ICRC_ledger): FI-1455: Refactor ICRC ledger golden state test

- .github/actions/bazel-test-all/action.yaml
- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
- ci/bazel-scripts/diff.sh
Fixes a small bug with identifying the diff files for `diff.sh`.
> fix(IDX): add branch head sha

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/11161752264
> chore: Update Base Image Refs [2024-10-03-1220]

- rs/ledger_suite/icp/BUILD.bazel
- rs/ledger_suite/icp/index/tests/tests.rs
- rs/ledger_suite/icp/test_utils/src/state_machine_helpers/index.rs
- rs/ledger_suite/icp/tests/golden_nns_state.rs
Add a check to verify that the blocks retrieved from the ledger and archives match the blocks retrieved from the index, for the ICP ledger suite golden state test.
> test(ICP_ledger): FI-1428: Add ledger, archive, and index block parity checks for ICP golden state test

- rs/ledger_suite/icrc1/ledger/README.adoc
This MR proposes the following changes:
1. Change the hardcoded IC_Version in the README to a git commit after the ledger suite resturucturing
> fix(Ledger-Suite): changed IC version

- rs/execution_environment/src/execution_environment.rs
- rs/execution_environment/src/lib.rs
- rs/execution_environment/src/scheduler.rs
- rs/execution_environment/src/scheduler/round_schedule.rs
- rs/execution_environment/src/scheduler/test_utilities.rs
- rs/execution_environment/src/scheduler/tests.rs
- rs/replicated_state/src/canister_state.rs
No functional changes, just moving functions in one place.
> chore: EXC-1749: Consolidate scheduling logic

- rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Fix the ICRC SNS golden state test that was broken in an earlier refactoring PR.
> test(ICRC_ledger): FI-1455: Fix ICRC SNS golden state test

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
Tested [here](https://github.com/dfinity/ic/actions/runs/11231306971/job/31220466089).
> fix(IDX): repository name

- .github/workflows-source/schedule-hourly.yml
- .github/workflows/schedule-hourly.yml
We want to leave FARM capacity occupied by hourly schedule to daily schedule.
> chore(IDX): no hourly at night

- Cargo.lock
- Cargo.toml
- rs/tests/Cargo.toml
- rs/tests/node/BUILD.bazel
- rs/tests/node/Cargo.toml
> chore: Remove unnecessary dependencies

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/11269871631
> chore: Update Base Image Refs [2024-10-10-0808]

- rs/tests/driver/src/driver/prometheus_vm.rs
Some folks have problems accessing the Grafana and P8s server in testnets via the registered domain name because by default only a AAAA record is registered. In some networks (in particular the DFINITY office) AAAA records don't work well. We therefor enable IPv4 support for PrometheusVms by default and when enabled register an A record for the prometheus and grafana server.
> test(IDX): enable IPv4 and A records for PrometheusVms

- .github/CODEOWNERS
- rs/tests/dashboards/IC/execution-metrics.json
This PR updates testnet 'Execution Metrics' dashboards to match the prod dashboards.
> chore: update testnet 'Execution Metrics' dashboards

- .github/workflows-source/ci-main.yml
- .github/workflows-source/ci-pr-only.yml
- .github/workflows/ci-main.yml
- .github/workflows/ci-pr-only.yml
- .github/workflows/container-autobuild.yml
- .github/workflows/container-base-images.yml
- .github/workflows/test-namespace-darwin.yaml
This updates and standardizes the concurrency logic across workflows, adding explanations where needed.
> chore(IDX): update concurrency logic

- .github/CODEOWNERS
Update CODEOWNERS for MODULE.bazel and sort alphabetically.
> chore(IDX): update codeowners for MODULE.bazel

- ic-os/components/hostos-scripts/build-bootstrap-config-image.sh
This BUILD_TAR_ONLY conditional is never used, and I don't suspect it will be used.
> chore: remove BUILD_TAR_ONLY conditional

- rs/replica/setup_ic_network/src/lib.rs
> chore: introduce a hashes-in-blocks feature flag

- .github/workflows-source/release-testing.yml
- .github/workflows-source/schedule-daily.yml
- .github/workflows/release-testing.yml
- .github/workflows/schedule-daily.yml
Missed these jobs during the upgrade here: https://github.com/dfinity/ic/pull/2041
> chore(IDX): upgrade python for dependency-scan jobs

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/11376758654
> chore: Update Base Image Refs [2024-10-17-0144]

- rs/nns/governance/src/governance.rs
- rs/nns/governance/tests/governance.rs
- rs/nns/integration_tests/src/governance_neurons.rs
- rs/nns/integration_tests/src/ledger.rs
- rs/nns/test_utils/src/state_test_helpers.rs
- rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
- rs/tests/src/rosetta_tests/tests/neuron_staking.rs
Created neurons should have a minimal dissolve delay.  This sets the minimum dissolve delay to 1 week and puts a ceiling on neuron creation.
> feat(nns): Neurons created with minimum dissolve delay

- rs/tests/testing_verification/testnets/small_high_perf.rs
This PR updates setup for `small_high_perf` testnet to remove unused resources.
> chore: update small_high_perf testnet setup

- rs/tests/BUILD.bazel
Fix for https://github.com/dfinity/ic/actions/runs/11435432121/job/31811296612?pr=2141
> fix(IDX): mark //rs/tests:dpkg_status_noble as linux only to fix build on mac

- Cargo.lock
- Cargo.toml
- rs/nervous_system/instruction_stats/BUILD.bazel
- rs/nervous_system/instruction_stats/Cargo.toml
- rs/nervous_system/instruction_stats/src/lib.rs
- rs/nervous_system/instruction_stats/src/tests.rs
In the next PR, this is used to come up with an enhanced `#[update]` attribute.
[👈 Previous PR] | [Next PR 👉]
[👈 Previous PR]: https://github.com/dfinity/ic/pull/1828
[Next PR 👉]: https://github.com/dfinity/ic/pull/1830
> feat: Instruction stats library.

- mainnet-canisters.json
How this PR was written:
```
bazel run //rs/nervous_system/tools/sync-with-released-nevous-system-wasms
```
(Per our standard procedure.)
Proposals:
* NNS:
* governance: https://dashboard.internetcomputer.org/proposal/133451
* genesis-token: https://dashboard.internetcomputer.org/proposal/133452
* registry: https://dashboard.internetcomputer.org/proposal/133453
* SNS:
* swap: https://dashboard.internetcomputer.org/proposal/133454
* governance: https://dashboard.internetcomputer.org/proposal/133455
> test(governance): Tell bazel about the governance WASMs that we just released.

- ic-os/guestos/context/packages.common
We plan to merge this just to generate a base image, then will revert until further testing has completed.
> feat: [NODE-1509] Update packages for 6.11 test

- ic-os/guestos/context/packages.common
Following https://github.com/dfinity/ic/pull/2164, we will revert until we have finished testing with the new kernel.
> feat: [NODE-1509] Revert "Update packages for 6.11 test"

- ic-os/guestos/context/Dockerfile.base
- ic-os/guestos/context/packages.common
> feat: Revert "feat: [NODE-1509] Use 6.11 kernel on 24.04 for GuestOS"

- rs/tests/httpbin-rs/src/main.rs
The http bin server takes a long time to shutdown at the end of a system-test.
At the end of a system-test the driver issues a DELETE /group/$testnet to Farm, Farm will then gracefully shutdown all VMs of the testnet (using virsh shutdown). 
The OS of the UVM running httpbin will then likely send a SIGINT to all its services including docker to give it time to gracefully shut down. However, the httpbin doesn't react to SIGINT, so the OS has to wait the default 90s before it kills the process.
> chore: Add graceful shutdown to bin test server

- cpp/prestorecon-cpp/prestorecon.cc
Calling selabel_open from each thread lead to bad performance, we can share a single selabel handle. Also log the elapsed time.
> fix: Improve prestorecon performance

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/11495091084
> chore: Update Base Image Refs [2024-10-24-0808]

- mainnet-canisters.json
Verify by running 
```
bazel run //rs/nervous_system/tools/sync-with-released-nevous-system-wasms --config=local
```
> chore(nervous-system): Update mainnet-canisters.json

- rs/ic_os/network/mac_address/src/mac_address.rs
The tool reports errors even when it successfully returns the mac. We shouldn't log those errors if we are able to extract the mac.
> fix: Fix confusing logging of ipmitool

- .github/workflows/rosetta-release.yml
- .github/workflows/schedule-weekly.yml
This value is not sensitive and can thus be retrieved from a var instead of a secret.
> chore(IDX): replace DOCKER_HUB_USER secret

- .github/workflows-source/schedule-daily.yml
- .github/workflows-source/schedule-hourly.yml
- .github/workflows/schedule-daily.yml
- .github/workflows/schedule-hourly.yml
It is good enough to run code coverage once a day.
> chore(IDX): code coverage daily

- .github/workflows/system-tests-k8s.yml
Based on resource utilization, we should be able to have more parallelism.
> chore(system-tests-k8s): double the job count

- rs/cross-chain/proposal-cli/templates/install.md
- rs/cross-chain/proposal-cli/templates/upgrade.md
Add the hash of the upgrade/install args to the summary generated by the `proposal-cli`.
> feat(proposal_cli): FI-1567: Add arguments hash to summary

- rs/bitcoin/ckbtc/mainnet/minter_upgrade_2024_10_28.md
XC-233: ckBTC minter: Proposal to change min withdrawal amount
> chore(ckbtc): Propose to reduce retrieve_btc_min_amount to 0.0005 btc

- rs/cross-chain/proposal-cli/src/candid/tests.rs
- rs/cross-chain/proposal-cli/src/canister/mod.rs
Add `proposal-cli` support for the cycles-ledger and exchange-rate-canister.
> feat(proposal-cli): Add support for the cycles-ledger and exchange-rate-canister

- rs/rust_canisters/canister_test/src/canister.rs
- rs/sns/integration_tests/src/proposals.rs
- rs/sns/test_utils/src/itest_helpers.rs
This test has been flaky, most recently reported by Bas. After switching to StateMachine it should be deterministic
> test(sns): migrate SNS integration test to StateMachine

- ic-os/boundary-guestos/context/docker-base.prod
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
Run URL: https://github.com/dfinity/ic/actions/runs/11718865209
> chore: Update Base Image Refs [2024-11-07-0808]

- rs/boundary_node/anonymization/client/src/lib.rs
This PR adds the client code for the canister. It will later be used by ic-boundary to interact with the canister.
> feat(BOUN-1236): add client code for canister

- rs/boundary_node/anonymization/backend/src/acl.rs
- rs/boundary_node/anonymization/backend/src/lib.rs
- rs/boundary_node/anonymization/backend/src/queue.rs
- rs/boundary_node/anonymization/backend/src/registry.rs
This change adds metrics and logging to the canister.
> feat(BOUN-1236): add metrics and logging to canister

- rs/nns/governance/src/neuron_store.rs
This fixes an inefficiency in how ballots are generated when neurons are in stable memory.
> fix(nns): Fix ballot generation inefficiency (for stable neurons)

- rs/config/src/embedders.rs
- rs/embedders/src/wasmtime_embedder/wasmtime_embedder_tests.rs
- rs/embedders/tests/spec_tests.rs
This PR enables the Wasm64 functionality for mainnet.
> feat: EXC: Enable Wasm64

- rs/sns/governance/canister/governance.did
- rs/sns/governance/canister/governance_test.did
- rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
- rs/sns/governance/protobuf_generator/src/lib.rs
- rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
This will be useful in the contingency that we need to reset them for some reason
> feat(sns): Add UpgradeStepsReset type to the upgrade journal

- rs/tests/ckbtc/BUILD.bazel
- rs/tests/ckbtc/ckbtc_minter_batching.rs
> fix(ckbtc): fix system test ckbtc_minter_batching

- rs/bitcoin/ckbtc/mainnet/minter_upgrade_2024_11_13.md
XC-233: ckBTC minter: Proposal to change min withdrawal amount
> chore(ckbtc): Propose to reduce retrieve_btc_min_amount for ckBTC minter

- rs/consensus/src/consensus/finalizer.rs
- rs/consensus/src/consensus/metrics.rs
- rs/consensus/src/consensus/payload.rs
- rs/consensus/src/consensus/payload_builder.rs
Add payload and payload section byte size histograms. And a batch delivery interval histogram.
> feat: Instrument payload size and batch delivery interval

- Cargo.Bazel.Fuzzing.json.lock
- Cargo.Bazel.Fuzzing.toml.lock
- Cargo.Bazel.json.lock
- Cargo.Bazel.toml.lock
- Cargo.toml
- MODULE.bazel
- bazel/external_crates.bzl
- rs/crypto/internal/crypto_service_provider/Cargo.toml
- rs/replica/BUILD.bazel
- rs/replica/Cargo.toml
- rs/replica/src/main.rs
- rs/tests/BUILD.bazel
- rs/tests/jaeger_activate.sh
manually tested with `ict test //rs/tests/networking:p2p_performance_test --keepalive`
> chore: upgrade opentelemetry and num_cpus crates

- rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
- rs/sns/governance/canister/governance.did
- rs/sns/governance/canister/governance_test.did
- rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
- rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
- rs/sns/governance/src/governance.rs
- rs/sns/governance/src/pb/conversions.rs
- rs/sns/governance/src/proposal.rs
- rs/sns/governance/src/types.rs
This PR adds a new proposal type called `AdvanceSnsTargetVersion`.
This is part of an upcoming [Effortless SNS Updates](https://forum.dfinity.org/t/effortless-sns-updates/35751) feature.
| [Next PR](https://github.com/dfinity/ic/pull/2704) >
> feat(sns): new proposal type AdvanceSnsTargetVersion

- rs/pocket_ic_server/src/state_api/state.rs
This PR ensures that the PocketIC server awaits the PocketIC HTTP gateway shutdown by shutting down the axum server handle in a drop handler invoked in the methods `ApiState::stop_http_gateway` and `ApiState::stop_all_http_gateways` after setting the `HttpGateway` struct to `None`.
In particular, the function `ApiState::stop_all_http_gateways` is awaited in the signal handler of the PocketIC server and thus all PocketIC HTTP gateways are shut down gracefully before the PocketIC main axum server is shut down and the main function exits (terminating the PocketIC server process).
> chore: await PocketIC HTTP gateway shutdown

- mainnet-canisters.json
This PR was created in the usual way, i.e.
```
bazel run //rs/nervous_system/tools/sync-with-released-nevous-system-wasms
```
> test(governance): Tell bazel about the Governance release we did on Monday (2024-11-18).

- Cargo.lock
- rs/rosetta-api/icrc1/BUILD.bazel
- rs/rosetta-api/icrc1/CHANGELOG.md
- rs/rosetta-api/icrc1/Cargo.toml
- rs/rosetta-api/icrc1/src/common/constants.rs
1. Add all changes necessarity for making a new release for ICRC Rosetta
> feat(ICRC-Rosetta): release changes for icrc rosetta

- rs/tests/ckbtc/ckbtc_minter_kyt.rs
Fix system test broken by #2674 since initially discarded UTXOs are re-evaluated and therefore also minted if the checks now go through on the second trial.
> test(ckbtc): fix system test `ckbtc_minter_kyt`

- rs/canister_sandbox/src/replica_controller/sandbox_process_eviction.rs
- rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
Problem:
The newest change to Sandbox caching keeps the idle candidates in the cache until we do not need to replace them with a cache for other candidates. This may create unnecessary overhead in the asynchronous thread which monitors the cache state.
Solution:
Remove candidates from the cache as soon as they become idle.
> feat: Evict sandbox cache of all idle candidates

- rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
In my testing, this takes the test time down from `192s` to `113s`, saving a full minute. 
(Repro: `bazel test //rs/nervous_system/integration_tests:integration_tests_test_tests/advance_sns_target_version --test_arg=test_advance_target_version_upgrades_all_canisters`)
I expected to save more than that actually. But reducing the 1000 in `let num_ticks = timeout_seconds.min(1000);` too much causes the tests to start failing for mysterious (to me) reasons.
> refactor(test): Reduce number of ticks used in tests

- rs/p2p/quic_transport/src/connection_manager.rs
I believe the custom handshake is not needed. 
Also this custom handshake is an artifact of the SEV attestation which was removed long time ago.
> fix: remove the app handshake

- rs/replicated_state/src/page_map/storage/tests.rs
The fuzzer exhausts disk space when run for long hours due to the removal of `TempDir` being unsound. The PR enforces the removal explicitly instead of relying on the `Drop` implementation. This codepath is used only in fuzzing.
> chore(fuzzing): enforce `TempDir` removal in `write_overlays_and_verify`

- MODULE.bazel
The [interface-spec](https://github.com/dfinity/interface-spec/) repo is archived and has been moved to dfinity/portal
> chore(ic): switch management canister did url to portal repo

- rs/orchestrator/src/orchestrator.rs
Update the onboarding log to emphasize onboarding is not yet complete
> chore(node): update onboarding log

- rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
- rs/nns/governance/canbench/canbench_results.yml
- rs/nns/governance/canister/governance.did
- rs/nns/governance/canister/governance_test.did
- rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
- rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
- rs/nns/governance/src/governance.rs
- rs/nns/governance/src/pb/conversions.rs
- rs/nns/governance/tests/governance.rs
Added RefreshVotingPower to ManageNeuron.
Closes https://dfinity.atlassian.net/browse/NNS1-3426
> feat(nns): Added dedicated API for refreshing voting power.

- rs/sns/governance/src/governance/advance_target_sns_version_tests.rs
This edge case is essential to test since I believe it caused a production incident before.
> test(sns): Upgrade archives and ledger, even when not all archives are at the same version

- .github/workflows/sync-public-with-private.yml
I have changes some things on the CLA, so this should work again. This is a double revert.
Restores: https://github.com/dfinity/ic/pull/2863
> revert: "revert: 'chore(IDX): replace PAT with GH App'"

- rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
use ic-boundary env file instead of systemd service
> fix: revive the nns recovery script

- .github/actions/bazel-test-all/action.yaml
- .github/workflows-source/ci-main.yml
- .github/workflows-source/ci-pr-only.yml
- .github/workflows-source/release-testing.yml
- .github/workflows-source/schedule-daily.yml
- .github/workflows-source/schedule-hourly.yml
- .github/workflows/ci-main.yml
- .github/workflows/ci-pr-only.yml
- .github/workflows/release-testing.yml
- .github/workflows/schedule-daily.yml
- .github/workflows/schedule-hourly.yml
- .github/workflows/schedule-rust-bench.yml
- ci/bazel-scripts/main.sh
- ci/scripts/lock-generate.sh
This was a leftover GITLAB CI var that we can remove.
> refactor(IDX): remove CI_PIPELINE_SOURCE

- rs/ledger_suite/tests/sm-tests/src/in_memory_ledger.rs
In addition to comparing the amounts, also check the expiration time when comparing allowances in the ledger and the `InMemoryLedger`.
> test(ICRC_Ledger): FI-1531: Also check expiration time when comparing allowances in InMemoryLedger

- rs/state_manager/src/lib.rs
In the state manager's commit_and_certify function, it now does the copy_state step before taking the write lock for the list of states.
Several API calls to the state manager rely on reading from the list of states, and they are blocked otherwise.
This fixes a regression introduced by commit
[e3ee007](https://github.com/dfinity/ic/commit/e3ee0072c1ea003c489b59fa10df2610c60fe2e6)
> perf: Copy outside write lock

- rs/nns/governance/canister/canister.rs
Instead of storing it in a global variable (technically, thread_local! + RefCell).
> refactor(nns): pass begin: Bound<NeuronId> to schedule_prune_some_following.

- .github/workflows/system-tests-k8s.yml
Disabling temporarily. Will enable again once Kubevirt is on 1.4.0 and VM manifests are adjusted.
> chore(IDX): disable system tests k8s

- rs/sns/governance/src/governance.rs
- rs/sns/governance/src/governance/assorted_governance_tests.rs
This PR makes timestamps that appear in logging and the upgrade journal human readable.
> feat(sns): Print human-readable timestamps when printing timestamps for humans

- .github/workflows/system-tests-k8s.yml
- rs/tests/driver/src/k8s/virtualmachine.rs
Adjusting VM manifests, required due to changes in newer kubevirt version. Enabling workflow on schedule and workflow dispatch events.
> chore(system-tests-k8s): kubevirt api changes

- rs/nns/cmc/src/main.rs
- rs/nns/integration_tests/src/cycles_minting_canister.rs
Prices recently increased, and users have started running into the previous limit.
This is a much simpler alternative to (and mutually exclusive with) https://github.com/dfinity/ic/pull/3087
> feat(cmc): Increase cycles_limit by 3x.

- .github/workflows/anonymization-backend-release.yml
- .github/workflows/rate-limits-backend-release.yml
Replaces the use of the `gh` cli tool with the release action.
> chore(BOUN-1308): use github release action

- mainnet-canisters.json
Verify with:
```
bazel run //rs/nervous_system/tools/sync-with-released-nervous-system-wasms --config=local
```
> chore(sns): Update mainnet-canisters.json

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
This works around some strange quirks of GHA. Before this, the condition always evaluated to true.
> fix(IDX): use correct if syntax for intel macos

- rs/nns/governance/src/voting.rs
Small change to clarify voting function.
> refactor(nns): Clarify voting code

- rs/messaging/src/state_machine.rs
Also, instrument timing out callbacks separately from timing out messages.
> fix: Correctly set `best_effort_message_memory_capacity`

- .github/repo_policies/BOT_APPROVED_FILES
Since we're sharing this as an example it's good to include wildcards. This also simplifies readability a little.
> chore(IDX): update BOT_APPROVED_FILES

- rs/nervous_system/integration_tests/src/lib.rs
- rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
- rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs
- rs/nns/governance/src/governance.rs
The objective is to speed the test up enough that it can be included in premaster again.
Cons: does this make the tests nondeterministic? I somewhat doubt it tbh
> test(sns): Speed up upgrade tests (and any other tests that involve archive)

- rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
The new approach is to submit all the requests, then await all the responses, when spamming archive.
On my machine, the total runtime of upgrade_everything_test goes from `109.0s`-`126.8s` to `64.3s`-`65.9s` after this change.
> test(sns): speed up integration tests that involve SNS archive even more

- rs/tests/consensus/tecdsa/tecdsa_signature_fails_without_cycles_test.rs
- rs/tests/consensus/tecdsa/tecdsa_signature_life_cycle_test.rs
- rs/tests/consensus/tecdsa/tecdsa_signature_timeout_test.rs
A temporary fix for a test failure introduced by #3282
> test: change error_code in tecdsa_signature_fails_without_cycles_test

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
If this works, we will do the same thing to other canisters that we (the Governance team) own. Automation will be implemented in other PRs.
[Remind the team to update unreleased_changelog.md][remind] (if it exists).
[remind]: https://github.com/dfinity/ic/pull/3342
[Automate proposal generation][propose].
[propose]: https://github.com/dfinity/ic/pull/3353
> docs(governance): Added unreleased_changelog.md and CHANGELOG.md to governance.

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- testnet/tools/nns-tools/add-release-to-changelog.sh
[prev]: https://github.com/dfinity/ic/pull/3332
> feat(governance-tools): Script that adds entry for new release to CHANGELOG after a proposal was successfully executed.

- rs/ethereum/cketh/mainnet/orchestrator_upgrade_2025_01_10.md
[(XC-270)](https://dfinity.atlassian.net/browse/XC-270) Proposal to upgrade all ledger suites managed by the ledger suite orchestrator to the latest version.
> chore(cketh/ckerc20): proposal to upgrade ledger suite orchestrator and managed canisters

- rs/nns/governance/src/governance.rs
- rs/nns/governance/src/governance/tla/disburse_to_neuron.rs
- rs/nns/governance/src/governance/tla/mod.rs
- rs/nns/governance/tests/governance.rs
- rs/nns/governance/tla/Claim_Neuron.tla
- rs/nns/governance/tla/Disburse_To_Neuron.tla
- rs/nns/governance/tla/Disburse_To_Neuron_Apalache.tla
Instrument the `disburse_to_neuron` function to check the test traces for compatibility with the TLA model.
> feat(IC-1579): TLA annotations for disburse_to_neuron

- rs/tests/cross_chain/ic_xc_cketh_test.rs
The P90 duration of the `//rs/tests/cross_chain:ic_xc_cketh_test` is 7 minutes which is longer than our maximum allowed of 5 minutes. This commit parallelizes the setup function to shave of ~45 seconds.
> test: parallelize the ic_xc_cketh_test setup function

- ci/tools/repro-check.sh
Should resolve this issue: https://forum.dfinity.org/t/proposal-to-elect-new-release-rc-2025-01-16-16-18/40172/10
> fix(ci): broaden `git_remote` match in repro-check script

- Cargo.lock
Restore Cargo.lock to what it was before #2386 / f53c9f3.
> chore: Restore Cargo.lock

- rs/tests/driver/src/k8s/virtualmachine.rs
Log serial console to dedicated container.
> chore(system-tests-k8s): console logs

- rs/bitcoin/ckbtc/mainnet/minter_upgrade_2025_01_24.md
Proposal to upgrade the ckBTC minter to include the latest code changes, notably: add metrics for the `update_latency` method and timestamps to the minter events.
> chore: proposal to upgrade ckBTC minter

- rs/tests/driver/src/driver/bootstrap.rs
- rs/tests/driver/src/k8s/config.rs
Log URL to navigate to node console logs.
> chore(system-tests-k8s): console logs url

- ci/src/artifacts/upload.bzl
- ci/src/artifacts/upload.sh
The proxy cache hasn't been used in a while.
> chore(idx): remove proxy cache url

- .github/workflows-source/ci-main.yml
- .github/workflows-source/ci-pr-only.yml
- .github/workflows-source/release-testing.yml
- .github/workflows-source/schedule-daily.yml
- .github/workflows-source/schedule-hourly.yml
- .github/workflows/ci-main.yml
- .github/workflows/ci-pr-only.yml
- .github/workflows/release-testing.yml
- .github/workflows/schedule-daily.yml
- .github/workflows/schedule-hourly.yml
- .github/workflows/system-tests-k8s.yml
This reverts commit 0468e6f90e52fab4be7b0bf722dacb520a589c55.
> revert: "chore(IDX): remove bazel-bep upload (#3615)"

- .github/workflows-source/ci-main.yml
- .github/workflows-source/ci-pr-only.yml
- .github/workflows-source/release-testing.yml
- .github/workflows-source/schedule-daily.yml
- .github/workflows-source/schedule-hourly.yml
- .github/workflows/ci-main.yml
- .github/workflows/ci-pr-only.yml
- .github/workflows/release-testing.yml
- .github/workflows/schedule-daily.yml
- .github/workflows/schedule-hourly.yml
- .github/workflows/system-tests-k8s.yml
> chore(IDX): remove bazel-bep upload

- rs/nns/governance/src/governance.rs
- rs/nns/governance/src/lib.rs
- rs/nns/governance/src/neuron/types.rs
- rs/nns/governance/src/neuron/types/tests.rs
- rs/nns/governance/tests/governance.rs
This feature ([private & public neurons][feat]) has completed its probation.
[feat]: https://dashboard.internetcomputer.org/proposal/130832
Closes [NNS1-3228] and [NNS1-3248].
[NNS1-3228]: https://dfinity.atlassian.net/browse/NNS1-3228
[NNS1-3248]: https://dfinity.atlassian.net/browse/NNS1-3248
> refactor(nns): Delete private neuron flags.

- bin/dotbootstrap.sh
The file seems to have been committed by mistake.
> chore(IDX): remove dotboostrap

- .github/workflows/team-channels.json
Team created a dedicated slack channel for PR notifications.
> chore(IDX): eng-consensus-prs

- rs/nervous_system/tools/release-runscript/src/main.rs
After this PR, the runscript acquires the latest commit and shows it to you, saving you from running the command yourself. 
[← Previous PR](https://github.com/dfinity/ic/pull/3712) | [Next PR →](https://github.com/dfinity/ic/pull/3714)
> feat(nns-tools): Release runscript automatically grabs the latest commit

- rs/nervous_system/tools/release-runscript/src/main.rs
Later, this will enable it to perform some of the steps of the release for you.
[← Previous PR](https://github.com/dfinity/ic/pull/3713) | [Next PR →](https://github.com/dfinity/ic/pull/3715)
> feat(nns-tools): Release runscript asks you which canisters to release

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
> docs(nns): Created entry in Governance's CHANGELOG for proposal 134777 (Jan 10).

- Cargo.lock
- rs/nervous_system/tools/release-runscript/BUILD.bazel
- rs/nervous_system/tools/release-runscript/Cargo.toml
- rs/nervous_system/tools/release-runscript/src/main.rs
This automates another step of the release process
[← Previous PR](https://github.com/dfinity/ic/pull/3714) | [Next PR →](https://github.com/dfinity/ic/pull/3716)
> feat(nns-tools): Release runscript generates proposal texts for you

- rs/nervous_system/tools/release-runscript/src/main.rs
The previous PR created the proposals texts for you. Now, they are submitted for you!
[← Previous PR](https://github.com/dfinity/ic/pull/3715) | [Next PR →](https://github.com/dfinity/ic/pull/3717)
> feat(nns-tools): Release runscript submits proposals for you

- Cargo.lock
- rs/nervous_system/tools/release-runscript/BUILD.bazel
- rs/nervous_system/tools/release-runscript/Cargo.toml
- rs/nervous_system/tools/release-runscript/src/main.rs
Well, it doesn't quite create them, but it opens the page for you and copies it to your clipboard. It's then up to you to post them and add in the proposal IDs.
[← Previous PR](https://github.com/dfinity/ic/pull/3716)
> feat(nns-tools): Release runscript generates forum posts

- ic-os/components/monitoring/metrics-proxy/guestos/metrics-proxy.yaml
- **Metrics Proxy Updates**:
- Add rule to keep `mr_blocks_proposed_total` metric.
- Add rule to keep `mr_blocks_not_proposed_total` metric.
> feat(metrics-proxy): add rules for `mr_blocks_proposed_total` and `mr_blocks_not_proposed_total`

- rs/nervous_system/tools/release-runscript/src/main.rs
Minor fixes:
1. When asking the user for whether they'd like to submit proposals, yes/no options are reversed
2. The comment for asking for neuron ids was misplaced
> fix(nns/sns): Minor fix for release script

- rs/nns/governance/src/governance.rs
- rs/nns/governance/src/neuron/types.rs
https://github.com/dfinity/ic/pull/2339
All changes here are comments.
> docs(nns): Follow up on PR 2339

- rs/bitcoin/adapter/src/get_successors_handler.rs
Before, the maximum number of queued up blocks that were tried to be downloaded was 100. The blocks are prioritized in a deterministic BFS fashion (closest 100 to the anchor are tried to be downloaded). Because testnet4 can have many (>100) forked blocks, this can lead to all closest 100 blocks to be outside of the main chain. When asked for these blocks, the peers simply timeout. This leads to the adapter not downloading anything, and getting stuck, as in the next iteration, the same 100 blocks will be retried.
After, the maximum number of blocks that are to be found in the BFS is increased to 1000. The testnet4 does not currently reach that many forked blocks, so this is a fine temporary fix. In the future, we ought to find a more robust way of dealing with forked blocks, (black-list …
> fix: increase the number of bitcoin in flight requests to 1000.

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
> revert: "chore(IDX): bazel-test-all ln1"

- rs/nervous_system/tools/release-runscript/src/main.rs
This much improves the error reporting if anything goes wrong, and makes the code more concise as we can use `?` instead of .unwrap()
[← Previous PR](https://github.com/dfinity/ic/pull/3792) | [Next PR →](https://github.com/dfinity/ic/pull/3794)
> refactor(nervous-system): use anyhow in release runscript

- rs/ledger_suite/icp/tests/golden_nns_state.rs
Fix the ICP ledger suite golden state test that broke due to a recent upgrade of the ledger canister.
> test(ICP_Ledger): Fix ICP ledger suite golden state test

- ic-os/components/early-boot/save-machine-id/save-machine-id.service
- ic-os/components/init/bootstrap-ic-node/bootstrap-ic-node.service
- ic-os/components/init/setup-encryption/setup-encryption.service
- ic-os/components/monitoring/node_exporter/setup-node_exporter-keys/setup-node_exporter-keys.service
- ic-os/components/upgrade/shared-resources/monitor-expand-shared-data/monitor-expand-shared-data.service
- ic-os/components/upgrade/shared-resources/upgrade-shared-data-store/upgrade-shared-data-store.service
NODE-1330
- [Update bootstrap-ic-node.service mount settings](https://github.com/dfinity/ic/pull/3798/commits/7c8658e7fcd0d4cde538e40f215a6ba433b0b86a)
- [Update mount settings](https://github.com/dfinity/ic/pull/3798/commits/c659aaf0ef1d10fb3d3e0345288cc992eb48b66a)
> chore(node): update mount settings

- rs/nns/governance/canister/canister.rs
This addresses follow up issues from [PR 2392].
[PR 2392]: https://github.com/dfinity/ic/pull/2392
All changes here are comments.
> docs(nns): Updated comment about following pruning batches.

- rs/nns/cmc/CHANGELOG.md
- rs/nns/cmc/unreleased_changelog.md
- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- rs/registry/canister/CHANGELOG.md
- rs/registry/canister/unreleased_changelog.md
- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
- rs/sns/root/CHANGELOG.md
- rs/sns/root/unreleased_changelog.md
- testnet/tools/nns-tools/add-release-to-changelog.sh
- [135205](https://dashboard.internetcomputer.org/proposal/135205)
- [135206](https://dashboard.internetcomputer.org/proposal/135206)
- [135207](https://dashboard.internetcomputer.org/proposal/135207)
- [135208](https://dashboard.internetcomputer.org/proposal/135208)
- [135209](https://dashboard.internetcomputer.org/proposal/135209)
> chore(nervous-system): Update changelog for release 2025-02-07

- .github/workflows-source/ci-main.yml
- .github/workflows-source/release-testing.yml
- .github/workflows-source/schedule-hourly.yml
- .github/workflows/ci-main.yml
- .github/workflows/release-testing.yml
- .github/workflows/schedule-hourly.yml
- .github/workflows/schedule-rust-bench.yml
The `RUSTFLAGS` don't seem to be used by anything.
> chore(IDX): remove RUSTFLAGS from workflows

- Cargo.lock
- rs/nns/test_utils/BUILD.bazel
- rs/nns/test_utils/Cargo.toml
Working towards retiring dfn_core
> chore(test-utils): Remove unused dependency

- ci/bazel-scripts/main.sh
https://github.com/dfinity/ic/pull/3899 broke intel darwin builds.
> fix(IDX): --repository_cache only for Linux

- ic-os/defs.bzl
- ic-os/guestos/defs.bzl
- ic-os/hostos/defs.bzl
- ic-os/setupos/defs.bzl
> refactor(node): standardize custom_partitions interface and improve documentation

- rs/consensus/dkg/src/lib.rs
- rs/consensus/dkg/src/payload_validator.rs
This helps to ensure that the logic remains consistent between both components.
> refactor: CON-1468 Extract common functionality of verifying NiDKG dealings

- Cargo.lock
- packages/ic-ed25519/BUILD.bazel
- packages/ic-ed25519/CHANGELOG.md
- packages/ic-ed25519/Cargo.toml
Update the changelog in preparation for releasing to crates.io
> chore(crypto): Update version of ic-ed25519 to 0.2

- rs/nns/handlers/root/CHANGELOG.md
- rs/nns/handlers/root/unreleased_changelog.md
- rs/nns/sns-wasm/CHANGELOG.md
- rs/nns/sns-wasm/unreleased_changelog.md
- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
- [135313](https://dashboard.internetcomputer.org/proposal/135313)
- [135314](https://dashboard.internetcomputer.org/proposal/135314)
- [135315](https://dashboard.internetcomputer.org/proposal/135315)
> chore(nervous-system): Update changelog for release 2025-02-14

- rs/ledger_suite/common/ledger_core/src/balances.rs
Update some comments regarding maximum values for tokens.
> chore(Ledger): Update some comments

- rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Update the SNS ledger suites in the ICRC golden state test.
> test(ICRC_Ledger): FI-1676: Update SNS ledger suites in ICRC golden state test

- rs/nns/cmc/src/lib.rs
- rs/nns/cmc/src/main.rs
- rs/nns/integration_tests/src/cycles_minting_canister.rs
The feature has been out since Feb 10 ([proposal 135205]), and there has been no sign of trouble.
[proposal 135205]: https://dashboard.internetcomputer.org/proposal/135205
Closes [NNS1-3566].
[NNS1-3566]: https://dfinity.atlassian.net/browse/NNS1-3566
> chore(cycles-minting): Deleted flag `IS_AUTOMATIC_REFUND_ENABLED`.

- .github/workflows-source/ci-main.yml
- .github/workflows-source/ci-pr-only.yml
- .github/workflows/ci-generate-ci.yml
- .github/workflows/ci-main.yml
- .github/workflows/ci-pr-only.yml
- .github/workflows/ci-pr-title-validation.yml
We want to set default permissions to read-only, so we need to explicitly set permissions in all of our worklfows.
> chore(IDX): set permissions by job

- bazel/conf/.bazelrc.build
- publish/binaries/BUILD.bazel
- testnet/BUILD.bazel
- testnet/README.md
- testnet/ansible.cfg
- testnet/host_inventory.py
- testnet/tools/BUILD.bazel
- testnet/tools/README.md
- testnet/tools/icos_collect_debug_info.py
- testnet/tools/icos_deploy.sh
- testnet/tools/icos_destroy.sh
- testnet/tools/ipv6-calc.py
Some teams still rely on those scripts
This reverts commit 5c2881a00b075f658d5e7249b6b6ef98088de44c.
> fix(IDX): Revert "chore(IDX): remove testnet directory (#4000)"

- rs/nervous_system/tools/release-runscript/src/main.rs
This is required because the changelog parts of the bash scripts look at the current text in the unreleased_changes.md files, not the text at the commit specified in the command
[Next PR →](https://github.com/dfinity/ic/pull/4004)
> feat(release-runscript): switch to commit being released when generating proposal texts

- rs/consensus/dkg/src/lib.rs
- rs/consensus/dkg/src/payload_validator.rs
Just some small refactors that I encountered DKG.
> refactor(Consensus): Small cleanups in the DKG crate

- .github/workflows/container-base-images.yml
- .github/workflows/update-mainnet-revisions.yaml
This PR moves any workflows that generate PRs to a new app and require using a new environment.
> feat(IDX): use new github app

- rs/consensus/src/idkg/pre_signer.rs
- rs/consensus/src/idkg/signer.rs
- rs/p2p/quic_transport/src/lib.rs
These logs can appear quite frequently during [membership changes](https://kibana.mainnet.dfinity.network/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:'2025-02-24T15:12:26.543Z',to:'2025-02-24T17:22:44.516Z'))&_a=(columns:!(MESSAGE),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'9a044220-7f73-4abe-bc4e-842056f2c703',key:ic_node,negate:!f,params:(query:rq2bj-ek3yy-mjj6s-zewtq-zzke4-u4zix-tz2xd-xigpz-s5hih-4wpmt-iqe),type:phrase),query:(match_phrase:(ic_node:rq2bj-ek3yy-mjj6s-zewtq-zzke4-u4zix-tz2xd-xigpz-s5hih-4wpmt-iqe)))),hideChart:!f,index:'9a044220-7f73-4abe-bc4e-842056f2c703',interval:auto,query:(language:kuery,query:'%22ConnectionLost%22%20or%20%22LocallyClosed%22%20or%20%22Exiting%20request%20handler%20event%20loop%20due%20t …
> chore: Reduce frequency of some logs

- rs/ethereum/cketh/mainnet/minter_upgrade_2025_02_25.md
Proposal to upgrade the ckETH minter to update the OFAC checklist.
> chore(cketh): proposal to upgrade ckETH minter

- .github/CODEOWNERS
- Cargo.lock
- rs/registry/node_provider_rewards/BUILD.bazel
- rs/registry/node_provider_rewards/Cargo.toml
- rs/registry/node_provider_rewards/src/lib.rs
- rs/registry/node_provider_rewards/src/logs.rs
This PR adds some unit tests for type3 and type1 nodes reward calculations in `calculate_rewards_v0`.
> test(registry/node_provider_rewards): Add unit tests for calculate_rewards_v0

- Cargo.lock
- rs/state_manager/BUILD.bazel
- rs/state_manager/Cargo.toml
- rs/state_manager/src/labeled_tree_visitor/tests.rs
- rs/state_manager/src/manifest/tests/compatibility.rs
- rs/state_manager/src/stream_encoding/tests.rs
- rs/state_manager/src/tree_diff.rs
- rs/state_manager/tests/state_manager.rs
> chore: refactor to use test_strategy in State Manager proptests

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- rs/nns/sns-wasm/CHANGELOG.md
- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
Update release changelogs for the proposals:
* http://dashboard.internetcomputer.org/proposal/135613
* http://dashboard.internetcomputer.org/proposal/135614
* http://dashboard.internetcomputer.org/proposal/135615
> chore(nns/sns): Update changelog for NNS/SNS releases

- Cargo.lock
- rs/tree_deserializer/BUILD.bazel
- rs/tree_deserializer/Cargo.toml
- rs/tree_deserializer/src/tests.rs
> chore: refactor to use test_strategy in Tree Deserializer proptests

- Cargo.lock
- rs/canonical_state/BUILD.bazel
- rs/canonical_state/Cargo.toml
- rs/canonical_state/tests/compatibility.rs
- rs/canonical_state/tests/size_limit_visitor.rs
- rs/canonical_state/tree_hash/BUILD.bazel
- rs/canonical_state/tree_hash/Cargo.toml
- rs/canonical_state/tree_hash/tests/hash_tree.rs
> chore: refactor to use test_strategy in Canonical State proptests

- Cargo.lock
- rs/state_machine_tests/BUILD.bazel
- rs/state_machine_tests/Cargo.toml
- rs/state_machine_tests/src/tests.rs
> chore: refactor to use test_strategy in State Machine Tests proptests

- Cargo.lock
- rs/state_layout/BUILD.bazel
- rs/state_layout/Cargo.toml
- rs/state_layout/src/state_layout/tests.rs
> chore: refactor to use test_strategy in State Layout proptests

- .github/workflows/update-mainnet-revisions.yaml
> fix(IDX): switch var names

- ci/bazel-scripts/main.sh
> chore(IDX): cleanup main.sh

- .rclone.conf
Since this PR: https://github.com/dfinity/ic/pull/4151 we do not need these env vars anymore.
> chore(IDX): remove references to old env vars

- rs/embedders/fuzz/src/ic_wasm.rs
The previous decoding have always been wrong or updated recently since we never checked the first byte for the operator before decoding the const value.
> fix(fuzzing): Update `get_persisted_global` to match proper encoding

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
Update changelog for proposals:
* http://dashboard.internetcomputer.org/proposal/135702
* http://dashboard.internetcomputer.org/proposal/135703
> chore(nns/sns): Update changelog after release

- rs/ledger_suite/icp/tests/tests.rs
The endpoint was not tested. Before migrating it to cdk it would be good to add a test that passes with dfn.
> test(ICP-Ledger): adding test fot transfer_fee_pb

- rs/execution_environment/src/hypervisor.rs
This TODO was handled in https://github.com/dfinity/ic/pull/3554.
> chore(EXC): Remove outdated TODO

- ic-os/hostos/context/Dockerfile.base
- ic-os/hostos/context/packages.common
These changes will only be used to create new base images, and will otherwise have no effect. Once they are pushed, https://github.com/dfinity/ic/pull/4321 will be used to integrate and test with.
> feat: [NODE-1574] Upgrade components to SEV-SNP compatible versions

- .github/workflows/system-tests-k8s.yml
From changes in https://github.com/dfinity/ic/pull/4280
> fix(IDX): adding missing step

- rs/consensus/src/consensus/validator.rs
Otherwise we might declare empty block proposals as invalid (instead of simply removing them) after an upgrade, if the data payload layout changed due to the upgrade.
> chore: Check block proposal version before integrity

- rs/utils/lru_cache/src/lib.rs
Add the `pop_lru` method to the actions tested in the LRU cache proptest.
> test(EXC): Add pop to lru cache proptest

- rs/tests/crypto/ic_crypto_csp_umask_test.rs
The test has to wait for at least a DKG interval before checking the metadata of the secret key store. It used to attempt to accomplish this by calling:
```rust
await_node_certified_height(&node, Height::from(SHORT_DKG_INTERVAL), ...);
```
where `SHORT_DKG_INTERVAL = 3`. However `await_node_certified_height` expects a target block height. So what would happen in practise is that when the node was already at certified height, say, 7. The test would "wait" until the height was 3 which would immediately be satisfied. This would mean the metadata of the secret key store was not updated yet.
This is fixed by calculating a proper target height and calling `await_node_certified_height` on that:
```rust
let node_certified_height = get_node_certified_height(&node, ...).get();
let …
```
> test(IDX): fix flaky ic_crypto_csp_umask_test

- rs/nns/integration_tests/src/wait_for_quiet.rs
The problem is that `voting_power_refreshed_timestamp_seconds` (a recently introduced field) was not set in a test neuron. As a result, the neuron's voting power started to be "slashed" due to Periodic Refresh of Following/Voting Power (a new feature, directly related to the new field). As a result, the tally did not "flip" from majority Yes to majority No. As a result, wait for quiet did not get triggered. Thus, the assert on original line 148 (correctly) started exploding.
Originally (immediately prior to this change), the exploding `assert!` left no bread crumbs. It is practically always wrong to not attach extra bread crumbs to an `assert!` (with `assert_eq!` this is much less of a problem, because it at least tells you the two sides of the `==`).
> test(nns): Fix wait_for_quiet test.

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
This PR updates the changelogs for NNS and SNS Governances after this week's release cycle.
> chore(nns/sns): Update changelogs for NNS and SNS Governances

- rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Fix the SNS ICRC ledger suite golden state test since the SNSs have been upgraded to a ledger where the blocks are migrated to stable structures.
> test(ICRC_Ledger): FI-1698: Fix SNS ICRC ledger suite golden state test

- rs/boundary_node/certificate_issuance/certificate_issuer/Cargo.toml
- rs/boundary_node/certificate_issuance/certificate_issuer/src/main.rs
* Trim the key that was read from the file
* If the file wasn't provided - try to read from `CLOUDFLARE_API_KEY` env var
> chore(BOUN-1331): certificate-issuer: rework cloudflare key reading

- .github/workflows-source/ci-main.yml
- .github/workflows-source/schedule-hourly.yml
- .github/workflows/ci-main.yml
- .github/workflows/schedule-hourly.yml
Putting bazel command in one line as recent changes have seem to broken [hourly schedule](https://github.com/dfinity/ic/actions/runs/14064520131/job/39383478480#step:4:279).
> fix(IDX): bazel command

- rs/state_manager/src/lib.rs
This PR adds some extra logs for uncommon paths during the end of state sync with the goal of understanding some test flakiness better.
> chore: Extra logs for the end of state sync

- ic-os/components/selinux/ic-node/ic-node.fc
- ic-os/components/selinux/ic-node/ic-node.te
> revert: "chore(EXC-1837): Remove execmem permissions"

- .github/actions/bazel/action.yaml
- .github/actions/bazel/bin/bazel
Reverts dfinity/ic#4550. Addressed in https://github.com/dfinity-ops/k8s/pull/1083
> revert: "fix(IDX): set expected names for bep and profile"

- rs/crypto/BUILD.bazel
- rs/crypto/Cargo.toml
- rs/crypto/benches/vetkd.rs
- rs/crypto/internal/crypto_lib/bls12_381/vetkd/benches/vetkd.rs
> feat(crypto): CRP-2733 add vetKD benchmarks

- rs/execution_environment/src/query_handler/query_context.rs
This PR adds logging for composite and expensive canister http transform functions.
> chore: log composite and expensive canister http transforms

- rs/nns/integration_tests/src/neuron_voting.rs
Similar fix as in: https://github.com/dfinity/ic/pull/4416
> fix(IDX): fix the neuron_voting test_voting_can_span_multiple_rounds

- rs/tests/nested/BUILD.bazel
[NODE-1579](https://dfinity.atlassian.net/browse/NODE-1579)
[NODE-1579]: https://dfinity.atlassian.net/browse/NODE-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: remove flaky nested tests from hourly pipeline

- Cargo.lock
- rs/rosetta-api/icrc1/BUILD.bazel
- rs/rosetta-api/icrc1/CHANGELOG.md
- rs/rosetta-api/icrc1/Cargo.toml
- rs/rosetta-api/icrc1/src/common/constants.rs
Release info for ICRC Rosetta 1.2.0
> feat(icrc-rosetta): add icrc rosetta release 1.2.0

- .github/workflows-source/ci-pr-only.yml
- .github/workflows/ci-pr-only.yml
Updating checkout to work with a PR from a forked repo.
> chore(IDX): lock generate checkout

- ic-os/README.adoc
- ic-os/hostos/README.adoc
Minor icos documentation cleanups
> docs(node): clean up icos documentation

- rs/tests/networking/canister_http_correctness_test.rs
This change removes the test `test_non_existing_transform_function` which seems to be identical to `test_non_existent_transform_function`.
> test(consensus): remove redundant system test for non existing transform function

- .github/workflows/schedule-rust-bench.yml
Adding information about dedicated machine for rust benchmarks (`fr1-spm15`).
> chore(IDX): rust bench runner info

- rs/nervous_system/agent/src/sns/governance.rs
- rs/nervous_system/integration_tests/BUILD.bazel
- rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
- rs/nervous_system/integration_tests/tests/set_following.rs
- rs/sns/governance/src/follower_index.rs
- rs/sns/governance/src/following.rs
- rs/sns/governance/src/governance.rs
- rs/sns/governance/src/topics.rs
- rs/sns/governance/unreleased_changelog.md
This PR implements a synchronization between the legacy and new topic following indices.
> feat(sns): Fine-grained unsetting of legacy proposal following while setting topic following

- rs/ic_os/config_types/src/lib.rs
vm_nr_of_vcpus was added to config_types, but it wasn't given a default value for backwards compatibility serialization.
> chore(node): fix config_types vm_nr_of_vcpus default

- rs/registry/transport/src/high_capacity.rs
- rs/registry/transport/src/high_capacity_tests.rs
- rs/registry/transport/src/lib.rs
These are not used yet, but will be in sequel PR(s).
Epic: [NNS1-3645]
[NNS1-3645]: https://dfinity.atlassian.net/browse/NNS1-3645
[Next PR 👉 ][next]
[next]: https://github.com/dfinity/ic/pull/4761
> feat(registry): Added some conversions to HighCapacity types.

- Cargo.lock
- Cargo.toml
- rs/registry/canister/chunkify/BUILD.bazel
- rs/registry/canister/chunkify/Cargo.toml
- rs/registry/canister/chunkify/src/lib.rs
- rs/registry/canister/chunkify/src/tests.rs
This is not used yet.
Epic: [NNS1-3645]
[NNS1-3645]: https://dfinity.atlassian.net/browse/NNS1-3645
[👈 Previous PR][prev] | [Next PR 👉][next]
[prev]: https://github.com/dfinity/ic/pull/4758
[next]: https://github.com/dfinity/ic/pull/4751
> feat(registry): Library for chunkifying whale registry mutations.

- Cargo.lock
- rs/ic_os/vsock/vsock_lib/BUILD.bazel
- rs/ic_os/vsock/vsock_lib/Cargo.toml
- rs/ic_os/vsock/vsock_lib/src/host/agent.rs
Builds atop and fixes https://github.com/dfinity/ic/pull/4805
> chore(node): unify downloading logic

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- [136285](https://dashboard.internetcomputer.org/proposal/136285)
> chore(nervous-system): Update changelog for release 2025-04-15

- ic-os/components/hostos-scripts/monitoring/custom-metrics.sh
> chore(node): Use get_config_value to read from config object

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- rs/node_rewards/canister/CHANGELOG.md
- rs/node_rewards/canister/unreleased_changelog.md
- rs/registry/canister/CHANGELOG.md
- rs/registry/canister/unreleased_changelog.md
- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
- [136370](https://dashboard.internetcomputer.org/proposal/136370)
- [136371](https://dashboard.internetcomputer.org/proposal/136371)
- [136372](https://dashboard.internetcomputer.org/proposal/136372)
- [136373](https://dashboard.internetcomputer.org/proposal/136373)
> chore(nervous-system): Update changelog for release 2025-04-25

- rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
In order to detect issues like voting rewards stalling (which is time dependent), we can advance the time enough to the future after an upgrade, to see if voting rewards and node rewards can be successfully distributed/minted, as a sanity check.
> test(nns): Check voting rewards and node rewards after an upgrade in golden state test

- rs/execution_environment/benches/run-benchmark.sh
- rs/execution_environment/benches/summarize-results.sh
1. Display top 10 improvements/regressions by time (currently, script displays top 5 ordered by percentage)
2. Other minor script changes.
> chore: EXC-2033: Summarize results by top time improvements

- ic-os/dev-tools/bare_metal_deployment/deploy.py
Fix bare metal deployment tempfile after: https://github.com/dfinity/ic/pull/4917
> fix(node): bare-metal-deploy tempfile

- rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
- rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
- rs/nervous_system/integration_tests/tests/sns_topics.rs
- rs/sns/governance/src/governance.rs
- rs/sns/governance/src/governance/assorted_governance_tests.rs
- rs/sns/governance/src/governance/proposal_topics_tests.rs
- rs/sns/governance/src/topics.rs
- rs/sns/governance/tests/governance.rs
- rs/sns/governance/unreleased_changelog.md
- rs/sns/integration_tests/src/proposals.rs
This PR makes the `DaoCommunitySettings` topic (and all proposal types that it contains) critical.
For context, please refer to https://forum.dfinity.org/t/make-sns-topic-dao-community-settings-critical/46689
> feat(sns): Make topic `DaoCommunitySettings` critical

- ic-os/components/setupos-scripts/setup-disk.sh
> fix(node): setup-disk.sh hardening

- rs/ledger_suite/icp/ledger/BUILD.bazel
- rs/ledger_suite/icp/ledger/src/main.rs
- rs/ledger_suite/icp/ledger/tests/tests.rs
Add logging of callers to the deprecated notify method.
> feat(ICP_Ledger): FI-1728: Add logging of callers to the deprecated notify method

- rs/ledger_suite/icrc1/ledger/tests/tests.rs
Re-enable the commented-out `test_icrc1_test_suite` test.
> test(ICRC_Ledger): FI-1732: Re-enable test_icrc1_test_suite test

- rs/tests/consensus/tecdsa/utils/src/lib.rs
Corrects a Jira ticket number for a TODO
> docs(crypto): CRP-2794 fix TODO item Jira ticket number

- rs/ic_os/config/src/deployment_json.rs
- rs/ic_os/config/src/main.rs
- rs/ic_os/dev_test_tools/setupos-image-config/src/bin/create.rs
- rs/ic_os/dev_test_tools/setupos-image-config/src/lib.rs
- rs/tests/driver/src/driver/bootstrap.rs
This will allow us to configure elasticsearch for a nested GuestOS through SetupOS
> feat: Pipe elasticsearch config through SetupOS

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- rs/nns/handlers/root/CHANGELOG.md
- rs/nns/handlers/root/unreleased_changelog.md
- rs/registry/canister/CHANGELOG.md
- rs/registry/canister/unreleased_changelog.md
- rs/sns/root/CHANGELOG.md
- rs/sns/root/unreleased_changelog.md
- [136693](https://dashboard.internetcomputer.org/proposal/136693)
- [136694](https://dashboard.internetcomputer.org/proposal/136694)
- [136695](https://dashboard.internetcomputer.org/proposal/136695)
- [136697](https://dashboard.internetcomputer.org/proposal/136697)
> chore(nervous-system): Update changelog for release 2025-05-21

- rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2025_05_22.md
- rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2025_05_22.md
- rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2025_05_22.md
- rs/ethereum/cketh/mainnet/orchestrator_upgrade_2025_05_22.md
[XC-373](https://dfinity.atlassian.net/browse/XC-373?atlOrigin=eyJpIjoiNTRlMGM1MTZjMzhkNGVlMmEyYTIyMzlkMGRjNWIxY2IiLCJwIjoiaiJ9): Proposal to upgrade all ledger suites to [ledger-suite-icrc-2025-05-22](https://github.com/dfinity/ic/releases/tag/ledger-suite-icrc-2025-05-22).
[XC-373]: https://dfinity.atlassian.net/browse/XC-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ckbtc/cketh/ckerc20): add proposals to upgrade all ledger suites to `ledger-suite-icrc-2025-05-22`

- .github/workflows-source/ci-pr-only.yml
- .github/workflows/ci-generate-ci.yml
- .github/workflows/ci-pr-only.yml
- .github/workflows/container-autobuild.yml
- .github/workflows/sync-public-with-private.yml
This updates our workflows to use a github app only used for the IC repos.
> chore(IDX): replace bot reference

- rs/ledger_suite/icp/ledger/canbench_results/canbench.yml
- rs/ledger_suite/icp/ledger/src/canbench/benches.rs
- rs/ledger_suite/icp/ledger/src/main.rs
Canbench benchmarks for `icrc2_approve` and `icrc2_transfer_from`.
> feat(ICP-Ledger): FI-1750: add approve and transfer from benchmarks

- rs/execution_environment/src/canister_manager.rs
- rs/execution_environment/src/canister_manager/tests.rs
This PR fixes the function `memory_usage_updates` in the management canister to return deallocated bytes back to subnet available memory.
> fix: return deallocated bytes to subnet available memory

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- rs/nns/gtc/CHANGELOG.md
- rs/nns/handlers/root/CHANGELOG.md
- rs/nns/sns-wasm/CHANGELOG.md
- rs/nns/sns-wasm/unreleased_changelog.md
- rs/node_rewards/canister/CHANGELOG.md
- rs/registry/canister/CHANGELOG.md
- rs/registry/canister/unreleased_changelog.md
- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
- rs/sns/root/CHANGELOG.md
Per 2025-06-06 upgrade proposals.
**Release Candidate**: [02571e8215fa3e77da791e693cc238b2de3beae9](https://github.com/dfinity/ic/tree/02571e8215fa3e77da791e693cc238b2de3beae9)
genesis-token: [136889](https://www.google.com/url?q=https://dashboard.internetcomputer.org/proposal/136889&sa=D&source=calendar&ust=1749651732997475&usg=AOvVaw2f-Dz0FE-tpC7tb6dwnawA)
governance: [136890](https://www.google.com/url?q=https://dashboard.internetcomputer.org/proposal/136890&sa=D&source=calendar&ust=1749651732997475&usg=AOvVaw1hZJp2vhPwI-5SeyinUbWr)
root: [136891](https://www.google.com/url?q=https://dashboard.internetcomputer.org/proposal/136891&sa=D&source=calendar&ust=1749651732997475&usg=AOvVaw1OcmDi6lichMsdpBhnYFua) 
sns-wasm: [136892](https://www.google.com/url?q=https://dashboard.internetcomputer …
> docs(governance-backend): Update Governance backend CHANGELOG files.

- rs/embedders/src/wasmtime_embedder/system_api.rs
`is_controller` is available in all system api contexts so a match on the `api_type` is unnecessary.
> refactor: Drop unnecessary match in is_controller

- rs/nns/governance/api/src/proposal_submission_helpers.rs
- rs/nns/governance/api/src/types.rs
- rs/nns/governance/canbench/canbench_results.yml
- rs/nns/governance/canister/governance.did
- rs/nns/governance/canister/governance_test.did
- rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
- rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
- rs/nns/governance/src/governance.rs
- rs/nns/governance/src/pb/conversions.rs
- rs/nns/governance/src/pb/mod.rs
- rs/nns/governance/tests/neurons.rs
- rs/nns/governance/unreleased_changelog.md
Closes [NNS1-3738].
[NNS1-3738]: https://dfinity.atlassian.net/browse/NNS1-3738
> feat(nns): Set following on multiple topics at once.

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- rs/registry/canister/CHANGELOG.md
- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
Proposals:
NNS:
* Governance: [Proposal 137080]
* Registry: [Proposal 137081]
SNS:
* Governance: [Proposal 137082]
[Proposal 137080]: https://dashboard.internetcomputer.org/proposal/137080
[Proposal 137081]: https://dashboard.internetcomputer.org/proposal/137081
[Proposal 137082]: https://dashboard.internetcomputer.org/proposal/137082
> docs(governance): Updated CHANGELOG files for canisters that we just proposed.

- rs/execution_environment/BUILD.bazel
- rs/execution_environment/tests/dts.rs
- rs/state_machine_tests/src/lib.rs
- rs/state_machine_tests/tests/multi_subnet.rs
- rs/universal_canister/lib/src/lib.rs
This PR refactors DTS tests to make the hard-coded constants better documented and easier to maintain.
> chore: refactor hard-coded constants in DTS tests

- toolchains/sysimage/build_container_filesystem_tar.py
One missing piece from https://github.com/dfinity/ic/pull/5604.
> fix: Don't map ID when extracting

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
This removes unused workflow IDs.
> chore: Clean up workflow IDs

- .github/workflows/ci-pr-only-nns-team-reminder.yml
Closes [NNS1-3859].
[NNS1-3859]: https://dfinity.atlassian.net/browse/NNS1-3859
> feat(governance-tools): Governance checklist.

- rs/rosetta-api/local/cluster/deploy.sh
Minor issue with cAdvisor initialization
> fix(rosetta): rosetta local cluster script

- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
- [137172](https://dashboard.internetcomputer.org/proposal/137172)
> chore(nervous-system): Update changelog for release 2025-06-27

- rs/embedders/src/wasmtime_embedder/signal_stack.rs
Fix the doc comment and remove some unneeded/commented out code.
> chore: Cleanup signal_stack module

- rs/tests/networking/canister_http_correctness_test.rs
This PR fixes the `invalid_ip` system test.
The test now explicitly checks for a timeout, rather than just assuming a `SysTransient` error.
> test(Consensus): Fix invalid ip test

- ic-os/components/early-boot/initramfs-tools/guestos/modules
- ic-os/components/early-boot/initramfs-tools/hostos/modules
- ic-os/guestos/context/docker-base.dev
- ic-os/guestos/context/docker-base.prod
- ic-os/hostos/context/docker-base.dev
- ic-os/hostos/context/docker-base.prod
- ic-os/setupos/context/docker-base.dev
- ic-os/setupos/context/docker-base.prod
- rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_kvm.xml
- rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_qemu.xml
- rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_sev.xml
- rs/ic_os/os_tools/guest_vm_runner/templates/guestos_vm_template.xml
Following https://github.com/dfinity/ic/pull/5635, will integrate the new components into the actual images built in https://github.com/dfinity/ic/pull/5714.
> feat: [NODE-1574] Upgrade images to SEV-SNP compatible base images

- rs/sns/governance/CHANGELOG.md
- rs/sns/governance/unreleased_changelog.md
- [137282](https://dashboard.internetcomputer.org/proposal/137282)
> chore(nervous-system): Update changelog for release 2025-07-09

- rs/nns/governance/src/proposals/fulfill_subnet_rental_request.rs
- rs/nns/governance/src/proposals/fulfill_subnet_rental_request/tests.rs
Working towards [NNS1-3925].
[NNS1-3925]: https://dfinity.atlassian.net/browse/NNS1-3925
[👈 Previous PR][prev] | [Next PR 👉][next]
[prev]: https://github.com/dfinity/ic/pull/5885
[next]: https://github.com/dfinity/ic/pull/5854
> test(nns-governance): Test for FulfillSubnetRentalRequest::validate.

- rs/nervous_system/tools/release-runscript/src/main.rs
This adds the proposal number as part of the links, so that they have a better chance of showing up in search in the forum.
> feat(nns-tools): improve the forum post links

- rs/nns/governance/CHANGELOG.md
- rs/nns/governance/unreleased_changelog.md
- rs/registry/canister/CHANGELOG.md
- rs/sns/root/CHANGELOG.md
- rs/sns/root/unreleased_changelog.md
* NNS Backend
* [Governance](https://www.google.com/url?q=https://dashboard.internetcomputer.org/proposal/137499&sa=D&source=calendar&ust=1753286013151817&usg=AOvVaw2HusYmpnLcstpgtfe_xwor)
* [Registry](https://www.google.com/url?q=https://dashboard.internetcomputer.org/proposal/137500&sa=D&source=calendar&ust=1753286013151817&usg=AOvVaw1d3pcAIKWpoJNBqWzp6Xrh)
* SNS Backend
* [Root](https://www.google.com/url?q=https://dashboard.internetcomputer.org/proposal/137501&sa=D&source=calendar&ust=1753286013151817&usg=AOvVaw1F6Sc6i0FcOQtnaDtXH530)
> docs(governance): Added entries to Governance backend CHANGELOGs for 2025-07-18.

- rs/tests/message_routing/common/common.rs
- rs/tests/message_routing/xnet/slo_test_lib/xnet_slo_test_lib.rs
This test flaked recently but the logging isn't really sufficient to debug this.
> chore(mr): Log ingress failure reasons in xnet SLO test

- rs/config/src/execution_environment.rs
- rs/rust_canisters/canister_creator/test/test.rs
This PR increase the subnet memory capacity from 1 TiB to 2 TiB and subnet memory threshold from 450 GiB to 750 GiB.
> feat: Increase subnet memory capacity to 2 TiB and subnet memory threshold to 750 GiB

- rs/tests/nested/src/lib.rs
- rs/tests/nested/src/util.rs
- rs/tests/system_tests.bzl
Fix bug with uses_setupos_img version breaking guestos_upgrade_smoke_test
> test(node): fix guestos_upgrade_smoke_test

- .github/workflows-source/ci-main.yml
- .github/workflows/ci-main.yml
No change, just caused some confusion for me when I was trying to make updates.
> fix(IDX): small workflow fix

- Cargo.lock
- rs/crypto/node_key_generation/BUILD.bazel
- rs/crypto/node_key_generation/Cargo.toml
- rs/crypto/node_key_validation/BUILD.bazel
- rs/crypto/node_key_validation/Cargo.toml
- rs/rust_canisters/canister_creator/BUILD.bazel
- rs/rust_canisters/canister_creator/Cargo.toml
Remove unused dependency on `ic-test-utilities` from a few crates.
> chore: FI-1814: Remove unused dependency on ic-test-utilities

- rs/cross-chain/proposal-cli/src/canister/mod.rs
- rs/cross-chain/proposal-cli/templates/install.md
- rs/cross-chain/proposal-cli/templates/upgrade.md
Add pointer to discussion thread on the forum for some canisters (ICP ledger suite, cycles ledger) in `proposal-cli`.
> feat(proposal-cli): FI-1791: Add pointer to forum discussion to select proposals in proposal-cli

- ic-os/components/misc/guestos-recovery/guestos-recovery-upgrader/guestos-recovery-upgrader.sh
Match guestos-recovery-upgrader to guestos-recovery-engine url construction
> refactor(node): guestos-recovery-upgrader url construction

- Cargo.Bazel.json.lock
- Cargo.toml
- bazel/external_crates.bzl
rust-ini 0.21.2 was yanked, preventing cargo build.
> fix: Downgrade yanked crate. 

- rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
- rs/nervous_system/integration_tests/tests/sns_extension_test.rs
- rs/sns/governance/src/extensions.rs
This PR ensures that TreasuryManager extension canisters are installed on the fiduciary subnet.
> feat(sns): Validate that treasury manager extension is on fiduciary subnet

- rs/registry/canister/CHANGELOG.md
- rs/registry/canister/unreleased_changelog.md
- [138164](https://dashboard.internetcomputer.org/proposal/138164)
> chore(nervous-system): Update changelog for release 2025-08-22

- .github/workflows/ci-notify-slack.yml
As an example, the escaping is fixed in this PR: https://github.com/dfinity/ic/pull/6445
> fix: EXC: Fix PR title sanitizer escaping

- Cargo.lock
- Cargo.toml
- ic-os/components/guestos/generate-ic-config/generate-ic-config.service
- rs/ic_os/config/BUILD.bazel
- rs/ic_os/config/Cargo.toml
- rs/ic_os/config/src/guestos/generate_ic_config.rs
- rs/orchestrator/Cargo.toml
NODE-1691
Use rust crates to replace external command execution and misc refactoring
> feat(node): generate-ic-config follow ups

- rs/execution_environment/tests/canister_snapshots.rs
This PR adds a test for uploading and loading a canister snapshot with invalid WASM.
> test: add test for uploading and loading a canister snapshot with invalid WASM

- rs/nervous_system/tools/release-runscript/src/main.rs
This adds the agreed upon tags to forum posts for SNS and NNS canisters.
See https://forum.dfinity.org/t/nns-proposal-discussions/34492 for more context
> feat(release-runscript): Add correct tags to forum posts

- rs/nns/governance/src/lib.rs
- rs/nns/governance/unreleased_changelog.md
Delete the flag, after probation ([NNS1-4115]).
[NNS1-4115]: https://dfinity.atlassian.net/browse/NNS1-4115
Closes [NNS1-3930].
[NNS1-3930]: https://dfinity.atlassian.net/browse/NNS1-3930
> feat(governance): Enable FulfillSubnetRentalRequest proposals.

- rs/crypto/benches/ni_dkg.rs
If the benchmark is not actually being run (for example because the user on the command line requested some subset of benchmarks be executed), creating the NIDKG test data is unnecessary work.
> perf(crypto): In NIDKG benchmarks avoid unnecessary setup

- rs/tests/nns/BUILD.bazel
Fix the path to the moved xrc_mock_canister.
> refactor: FI-1862: Fix xrc_mock_canister path

- rs/migration_canister/BUILD.bazel
- rs/migration_canister/src/canister_state.rs
- rs/migration_canister/src/external_interfaces/management.rs
- rs/migration_canister/src/external_interfaces/registry.rs
- rs/migration_canister/src/lib.rs
- rs/migration_canister/src/migration_canister.rs
- rs/migration_canister/src/processing.rs
- rs/migration_canister/src/tests.rs
- rs/migration_canister/tests/tests.rs
This PR implements the rest of the migration logic and adds additional public endpoints.
Testing further is blocked by https://github.com/dfinity/ic/pull/6872 and will come in a follow-up.
> feat: Migration Canister continued

- Cargo.lock
- rs/tests/nested/BUILD.bazel
- rs/tests/nested/Cargo.toml
- rs/tests/nested/guestos_upgrade.rs
- rs/tests/nested/hostos_upgrade.rs
- rs/tests/nested/recovery_upgrader_test.rs
- rs/tests/nested/src/lib.rs
- rs/tests/nested/src/util.rs
> refactor(node): Move nested tests into separate files

- Cargo.lock
- Cargo.toml
- rs/nervous_system/tools/neuron-subaccount/BUILD.bazel
- rs/nervous_system/tools/neuron-subaccount/Cargo.toml
- rs/nervous_system/tools/neuron-subaccount/src/main.rs
For mapping from principal + memo to subaccount & account (of the NNS Governance canister).
> feat(governance): Created neuron-subaccount tool.

- rs/nns/governance/src/lib.rs
- rs/nns/governance/src/proposals/fulfill_subnet_rental_request.rs
- rs/nns/governance/src/proposals/fulfill_subnet_rental_request/tests.rs
- rs/nns/governance/unreleased_changelog.md
When merge: after the Swiss subnet folks have their subnet. Nominally, that is supposed to happen in mid Sep. However, there is a non-negligible chance that things will be delayed. That event will "probably" have taken place by October.
In any case, in the meantime, this is ready for review.
Closes [NNS1-4115].
[NNS1-4115]: https://dfinity.atlassian.net/browse/NNS1-4115
> chore(governance): Delete the FulfillSubnetRentalRequest flag.

- rs/execution_environment/src/canister_manager/types.rs
Apply a suggestion on a previous PR: https://github.com/dfinity/ic/pull/6725#discussion_r2381147990
> chore: Improve error suggestion for CanisterMetadataSectionNotFound

- ic-os/components/setupos/check-hardware.sh
- ic-os/components/setupos/test-setupos.sh
> chore: use node reward type to determine node generation

- rs/nns/governance/src/lib.rs
This PR, adds a feature flag to enable neuron follow restrctions.
> feat(nns): neuron follow restrictions feature flag

- ic-os/components/setupos/check-ntp.sh
> chore(node): update chrony service logs
