WORKSPACE.bazel

This replaces the last (`new_`)`git_repository` usage with the recommended `http_archive`. This means that the client's Git is not used anymore and all dependencies listed in WORKSPACE are fetched natively by Bazel.

chore(IDX): remove usage of new_git_repository

---

.github/CODEOWNERS
.github/workflows/ci-notify-slack.yml

It seems that the action "ready for review" triggers before "review requested" so the payload doesn't always have the complete teams. This fix changes the trigger and will both trigger if a PR is directly opened as a non-draft and if additional reviewers are added later.

chore(IDX): update slack notification

---

.bazelrc
WORKSPACE.bazel

Without this it's impossible to run system-tests locally because the IC-OS images won't be uploaded to the bazel cache which means Farm / k8s won't be able to download them to boot VMs.

fix(IDX): do upload to the bazel-remote cache for systests

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Sacrificing DRY for clearer definition of 2 CI jobs and fixing conditional step.

chore(IDX): cargo-filter

---

.github/workflows/team-channels.json

This fixes a typo (missing 's') in the team-channels mapping file. This caused an issue when the `ic-owners-owners` team would be assigned for review.

fix(IDX): typo in teams mapping

---

rs/crypto/test_utils/tls/src/test_client.rs
rs/crypto/test_utils/tls/src/test_server.rs
rs/crypto/tests/tls_handshake.rs

Improves an error mapping in the TLS test client and server.
In particular, a `TlsConfigError::MalformedSelfCertificate` is used for something that actually isn't a malformed self certificate. This is fixed by letting let the `run` methods of the TLS test server and client return a new, more general error type.
This is a follow-up from [feat: remove the legacy TlsHandshake interface](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/19354).

refactor(crypto): CRP-2411 improve error mapping in TLS test client and server

---

ic-os/defs.bzl

This fixes the following error first observed in [this failing job](https://github.com/dfinity/ic/actions/runs/9396755633/job/25878546623?pr=180):
```
$ bazel build //ic-os/guestos/envs/prod:launch-remote-vm --config=check
INFO: Invocation ID: 713803fa-c204-4f6c-8638-523a043c58a4
INFO: Streaming build results to: https://dash.idx.dfinity.network/invocation/713803fa-c204-4f6c-8638-523a043c58a4
INFO: Build option --@rules_rust//rust/settings:pipelined_compilation has changed, discarding analysis cache.
ERROR: /ic/ic-os/guestos/envs/prod/BUILD.bazel:10:11: in genrule rule //ic-os/guestos/envs/prod:launch-remote-vm: non-test target '//ic-os/guestos/envs/prod:launch-remote-vm' depends on testonly target '//rs/ic_os/launch-single-vm:launch-single-vm' and doesn't have testonly attribute set …
```

fix(IDX): make launch-remote-vm testonly because it depends on a testonly target

---

.github/workflows/gitlab-push.yml

The `push_to_gitlab_improved` GitHub job is an improved version of `push_to_gitlab` which creates a (draft) MR for just the HEAD of the `mirroring` branch. `push_to_gitlab` actually creates a MR for the whole `mirroring` branch which sometimes contains commits of multiple PRs.
Once `push_to_gitlab_improved` is working as expected we'll remove the old `push_to_gitlab` and rename `push_to_gitlab_improved` to it.

chore(IDX): introduce the push_to_gitlab_improved job

---

.github/workflows/gitlab-push.yml

Specifying full refname.
```
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:
- Looking for a ref that matches 'mirroring-v2-marko-push-to-gitlab' on the remote side.
- Checking if the <src> being pushed ('refs/remotes/origin/marko-push-to-gitlab')
is a ref in "refs/{heads,tags}/". If so we add a corresponding
refs/{heads,tags}/ prefix on the remote side.
Neither worked, so we gave up. You must fully qualify the ref.
```

fix(IDX): gitlab push ref

---

.github/workflows-source/schedule-hourly.yml
.github/workflows/schedule-daily.yml
.github/workflows/schedule-hourly.yml
.github/workflows/schedule-weekly.yml

Relabeling `bazel-build-fuzzers-weekly` and `cut-release-candidate` to run on different runners.

chore(IDX): relabel CI jobs

---

.bazelrc

This removes a workaround that was necessary in the past to work around an issue in clippy. The issue is now fixed in clippy, and our clippy version is recent enough to include the fix.
See also:
* https://github.com/bazelbuild/rules_rust/pull/2277
* https://github.com/rust-lang/rust-clippy/pull/12203

chore(IDX): remove clippy sysroot workaround

---

.bazelrc
.gitignore
gitlab-ci/config/main.yml

This changes the default config to not general a build log. The build log is a very large file, and is not used much.
When debugging builds, the build log can simply be re-enabled. It does not seem to be generally useful to generate the build log or to store it.

chore(IDX): remove bazel-build-log.json

---

bazel/external_crates.bzl
gitlab-ci/src/ci-scripts/before-script.sh

`sudo podman` doesn't seem to get credentials. Adding them to `.docker/auth.json` for root which is the file that rootful podman uses as a fallback if it exists.
```
Error: initializing source docker://dfinity/boundaryos-base@sha256:8c218ad124309aa177c2f41c3766f87edca4485150c4ebe002de281a6932ae83: reading manifest sha256:8c218ad124309aa177c2f41c3766f87edca4485150c4ebe002de281a6932ae83 in docker.io/dfinity/boundaryos-base: toomanyrequests: You have reached your pull rate limit.
```

fix(IDX): docker.io auth

---

.github/workflows-source/ci-main.yml
.github/workflows-source/ci-pr-only.yml
.github/workflows/ci-generate-ci.yml
.github/workflows/ci-main.yml
.github/workflows/ci-notify-slack.yml
.github/workflows/ci-pr-only.yml

By using jq's `--arg` we make sure `jq` interprets the team as a whole string. Without thing, the `jq` filter can expand to e.g. `'.my-team'` which is not valid. For instance with `TEAM="ic-interface-owners"`:
```
jq: error: interface/0 is not defined at <top-level>, line 1:
.ic-interface-owners
```

fix(IDX): use jq arg in team lookup

---

.github/workflows-source/schedule-hourly.yml
.github/workflows/release-testing.yml
.github/workflows/schedule-hourly.yml
rs/tests/networking/BUILD.bazel

Bonding has been setup in ln1-idx1 which means [firewall_max_connections_test is succeeding now](https://dash.sf1-idx1.dfinity.network/invocation/6b696acb-71c4-4280-b435-7652307416e8?target=%2F%2Frs%2Ftests%2Fnetworking%3Afirewall_max_connections_test&targetStatus=5).

chore(IDX): enable the firewall_max_connections_test on GitHub again

---

.github/workflows-source/ci-main.yml
.github/workflows-source/schedule-daily.yml
.github/workflows-source/schedule-hourly.yml
.github/workflows/ci-main.yml
.github/workflows/release-testing.yml
.github/workflows/schedule-daily.yml
.github/workflows/schedule-hourly.yml
.github/workflows/team-channels.json

We previously used `--verbose failures` for debugging but it is not required anymore.
Also remove defaults that are already set by the bazel-test-all action: https://github.com/dfinity/ic/blob/master/.github/actions/bazel-test-all/action.yaml#L10-L15.

chore(IDX): Remove verbose failures

---

.github/workflows/team-channels.json
rs/tests/consensus/backup_manager_test.rs

This will ensure that we can backup blocks containing tSchnorr payloads.

test(schnorr): CON-1337 Add tSchnorr keys to backup manager test

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Disabling run diff targets logic as we sometimes have issues that block users.

chore(IDX): disable run on diff for bazel-build-all-config-check

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Temporarily setting `continue-on-error` to prevent a job from failing.

chore(IDX): darwin continue-on-error

---

Cargo.lock
Cargo.toml

This adds the `rs/validator/http_request_arbitrary` package to the top-level `Cargo.toml`. The package was missing from the cargo build, though it is already included in the Bazel build.

fix(IDX): add missing package to cargo workspace

---

rs/consensus/tests/framework/mod.rs
rs/registry/keys/src/lib.rs

There was a test in consensus `framework` left over, that was still not fully migrated to use `make_chain_key_signing_subnet_list`.
This MR migrates the test, (even though it seems we are not even using Threshold Sigs in these tests), and can then remove `make_ecdsa_signing_subnet_list_key` and its test altogether.

chore(CON13-02): Remove `make_ecdsa_signing_subnet_list_key` from the codebase

---

rs/types/types/src/consensus/idkg/schnorr.rs

Messages to be signed by tSchnorr may be up to 10 MiB in length, and we shouldn't print them in their entirety. This MR implements the `Debug` trait for `ThresholdSchnorrSigInputRef`, such that only the message length is printed.

chore(schnorr): CON-1349 Manually implement `Debug` for `ThresholdSchnorrSigInputRef` and omit full message

---

rs/recovery/src/file_sync_helper.rs
rs/recovery/src/ssh_helper.rs

During a recent recovery it became clear that the SSH timeout is too high. The execution of a recovery step got stuck while trying to download the certification pool of an unavailable node, with no way to skip it.

fix(recovery): CON-1344 Reduce SSH timeout and number of attempts in `ic-recovery`

---

rs/consensus/src/certification.rs
rs/consensus/src/certification/certifier.rs
rs/consensus/src/consensus/batch_delivery.rs
rs/consensus/src/consensus/finalizer.rs
rs/consensus/src/consensus/malicious_consensus.rs
rs/consensus/src/consensus/notary.rs
rs/consensus/src/consensus/random_tape_maker.rs
rs/consensus/src/consensus/share_aggregator.rs
rs/consensus/src/consensus/validator.rs
rs/consensus/src/dkg.rs
rs/consensus/src/dkg/payload_builder.rs
rs/consensus/src/dkg/payload_validator.rs
rs/consensus/src/dkg/test_utils.rs

This PR merges and organizes the imports of the consensus crate (except the ecdsa submodule, which we should do separately at some point).

refactor(consensus): Merge imports in consensus crate

---

rs/tests/src/orchestrator/upgrade_with_alternative_urls.rs

Previously we would wait until the node becomes unavailable, as a sign that it was upgrading. This is imprecise and sometimes flaky, see [here](https://dash.zh1-idx1.dfinity.network/invocation/997a197e-62ed-4aee-969c-3fa8a0f73de0?target=%2F%2Frs%2Ftests%2Fconsensus%2Forchestrator%3Aupgrade_with_alternative_urls&targetStatus=6#1). The logs reveal that the replica did in fact upgrade successfully, but I suspect the "unhealthy" status didn't persist long enough to be picked up by the test driver.
With this PR we instead wait until the node is running the expected replica version after the upgrade.

chore: Improve Upgrade with Alternative URLs test

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.json.lock
Cargo.lock
rs/rosetta-api/Cargo.toml
rs/rosetta-api/ledger_canister_blocks_synchronizer/BUILD.bazel
rs/rosetta-api/ledger_canister_blocks_synchronizer/Cargo.toml

This updates the cargo build to remove the `actix-web` & `serde_bytes` dependencies from the ledger canister blocks synchronizer, and to remove the `actix-web` custom features for the top-level `rosetta` package. This aligns the rosetta cargo build a bit more with the Bazel configuration.

fix(IDX): align rosetta deps

---

rs/consensus/utils/src/lib.rs

An off-by-one error in the notary bound leads the notary to stall one height too early. `ACCEPTABLE_NOTARIZATION_CUP_GAP` is inclusive, so this MR changes the notary to correctly notarize heights that are `ACCEPTABLE_NOTARIZATION_CUP_GAP` above the next CUP height. This is now also consistent with the validator.

fix(consensus): Fix off-by-one error in notary bound

---

rs/tests/src/tecdsa/tecdsa_add_nodes_test.rs

This test ensures that after adding nodes to a subnet with signing enabled, signing still works and the keys haven’t changed.
However, currently we only wait until the proposal to add the new nodes is executed, before immediately running the signature test.
This means that by the time we run the signature test, the membership of the subnet hasn't actually changed yet, as that only happens after a couple of DKG intervals.
With this PR, we instead wait until all keys were reshared as a result of the membership change before running the signature test.

chore(tests): CON-1351 Improve adding nodes test

---

.github/workflows-source/release-testing.yml
.github/workflows/release-testing.yml

This change updates the trigger for the release workflow so that it will be triggered once CI Main has completed on either a hotfix or rc branch but only if it was successful.

chore(IDX): trigger release workflow after main

---

rs/consensus/src/consensus/batch_delivery.rs
rs/consensus/src/ecdsa/payload_builder/resharing.rs
rs/consensus/src/ecdsa/payload_verifier.rs

We should be using the new type `ComputeInitialIDkgDealings` here. The reason why it works anyway is that both types are the same on the wire.

fix(schnorr): CON-1257 Remove leftover uses of `ComputeInitialEcdsaDealings`

---

.github/workflows-source/release-testing.yml
.github/workflows/release-testing.yml

The checkout step cannot get the correct context when triggered by workflow_run and switches to master. We must therefore explicitly specify which ref to checkout.

fix(IDX): update checkout ref

---

.github/workflows-source/release-testing.yml
.github/workflows/release-testing.yml

If we check out the ref instead of the branch we end up in a detached HEAD state.

fix(IDX): checkout correct branch

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Some dependency scanning alerts are hard-coded to the "ic" repo and fail when run on "ic-private". Since this is a blocker for migration, we need to disable them when run on "ic-private". The long-term correct solution would be to use a variable that references the repo it is being run from instead of hard-coding.

chore(IDX): only run certain python tests on security-hotfix

---

.github/workflows-source/schedule-daily.yml
.github/workflows/schedule-daily.yml

Adding missing `/cache` for bazel benchmarks. This got broken after our recent changes that added `options`.

fix(IDX): /cache for benchmarks

---

rs/canister_sandbox/src/replica_controller/launch_as_process.rs
rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs

This fixes two thread leaks per SandboxedExecutionController. Note that in production replica that fix has little impact because there is only one controller that has the same lifetime as the process itself.
However, in tests that create many instances of the controller, this considerably reduces the number of threads.
Kudos to mraszyk@ for reporting the issue and providing a way to reproduce the leak and verify the fix.
Fixes:
- the sandbox monitoring thread was not terminated properly. The fix introduces a channel to request termination when the controller is dropped.
- the background writing thread of the launcher service was not terminated properly.  The fix terminates the writing thread when the reading thread exits (similar to other places).

fix: RUN-1014: Free SandboxedExecutionController threads

---

.github/workflows-source/ci-pr-only.yml
.github/workflows/ci-pr-only.yml

Checkout by default only fetches the latest commit. In `dependencies-check` job, we require the git history to find the merge-base and flag dependencies accordingly. 
Fix tested [here](https://github.com/dfinity/ic/pull/357)

fix(dependency-mgmt): Set `fetch-depth` to 256 for `dependencies-check`

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
bazel/external_crates.bzl
rs/crypto/ed25519/BUILD.bazel
rs/crypto/ed25519/Cargo.toml
rs/crypto/ed25519/src/lib.rs
rs/crypto/internal/crypto_lib/basic_sig/ed25519/BUILD.bazel
rs/crypto/internal/crypto_lib/basic_sig/ed25519/Cargo.toml
rs/crypto/internal/crypto_lib/basic_sig/ed25519/src/api.rs
rs/rosetta-api/icrc1/rosetta/client/BUILD.bazel
rs/rosetta-api/icrc1/rosetta/client/Cargo.toml
rs/rosetta-api/icrc1/rosetta/client/src/lib.rs

Replaces the remaining usage of the unmaintained `ed25519-consensus` crate with `ic-crypto-ed25519` in the production code.
There were two usages of `ed25519-consensus` left in production code, both of which were about signature _verification_. The usage of `ic-crypto-ed25519` for signature verification is equivalent with `ed25519-consensus` because both crates perform signature verification according to the [ZIP215](https://zips.z.cash/zip-0215) rules.
Other usages of `ed25519-consensus` have been removed earlier in https://github.com/dfinity/ic/commit/cae2f79e404b1a94a4753073eb03033a8686d1b8 and https://github.com/dfinity/ic/commit/9f7ca0a7548d1550a46eff2dbc59d62dee2e8eba.

refactor(crypto): CRP-2536 replace ed25519-consensus with ic-crypto-ed25519 in prod

---

rs/canister_sandbox/src/protocol/sbxsvc.rs
rs/canister_sandbox/src/protocol/structs.rs
rs/cycles_account_manager/src/lib.rs
rs/embedders/src/lib.rs
rs/embedders/src/serialized_module.rs
rs/embedders/src/wasm_executor.rs
rs/interfaces/src/execution_environment.rs
rs/replicated_state/src/page_map.rs
rs/replicated_state/src/page_map/checkpoint.rs
rs/replicated_state/src/page_map/page_allocator.rs
rs/replicated_state/src/page_map/storage.rs
rs/system_api/src/lib.rs
rs/system_api/src/sandbox_safe_system_state.rs
rs/types/types/src/methods.rs

This is a mechanical change that adds `PartialEq` to all types that are used in the IPC between replica and sandbox.
The motivation for this change is to write tests that assert that all IPC types can correctly round-trip with bincode:
```
deserialize(serialize(x)) == x
```

chore: RUN-1015: Derive ParitalEq for all sandbox IPC types

---

rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/canister_settings.rs
rs/execution_environment/src/hypervisor/tests.rs

This follows up on `9c7d1c` to use the new error code that was introduced in the original fix, but couldn't be used immediately due to forward/backward compatibility in the replicated state.

fix: RUN-1001: Follow up on the reserved cycles limit fix

---

rs/tests/crypto/BUILD.bazel
rs/tests/gix/BUILD.bazel
rs/tests/nns/sns/BUILD.bazel
rs/tests/src/nns_dapp.rs
rs/tests/system_tests.bzl
rs/tests/testing_verification/BUILD.bazel
rs/tests/testing_verification/testnets/BUILD.bazel
rs/tests/testing_verification/testnets/src_testing.rs

This updates the system tests using the NNS dapp (and NNS dapp dependencies) not rely on any bazel-specific paths. Instead, the path to the canisters used by these tests is passed as environment variables (and adds supports for setting runtime environment variables in system tests).
This makes the tests less dependent on bazel-specific paths (`external/`, exact canister names, etc).

chore(IDX): make nns_dapp tests bazel-agnostic

---

buf.yaml
rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs

I made a typo in !20396, this MR fixes it. We can fix it now since the change hasn't been released yet.
Of course, it will fail the protobuf backwards compatibility checker, so it might require a force merge or similar workaround

chore(nervous_system): Principals proto typo fix: 7 -> 1

---

.github/workflows/container-base-images.yml
.github/workflows/slack-workflow-run.yml

Updating and enabling workflow to build and push images to GHCR. Test run: https://github.com/dfinity/ic/pull/387.

chore(IDX): updating base images workflow

---

testnet/tools/BUILD.bazel

Set testonly for icos_deploy to fix static testnet deployment tooling from bazel.

fix(node): fix testonly in icos_deploy bazel rules

---

buf.yaml

This MR restores buf.yaml, which was only partially disabled to temporarily remove its restrictions on backwards-incompatible changes

chore(idx): Restore buf.yaml

---

rs/nervous_system/integration_tests/BUILD.bazel

Specifically,
- //rs/nervous_system/integration_tests:integration_tests_test_tests/sns_ledger_upgrade
- //rs/nervous_system/integration_tests:integration_tests_test_tests/sns_release_qualification
The solution seems to be to simply give it more cores.

test(sns): SNS upgrade-related tests were flaking out.

---

rs/consensus/src/ecdsa/signer.rs
rs/consensus/src/ecdsa/test_utils.rs
rs/consensus/utils/src/lib.rs
rs/execution_environment/src/execution_environment.rs
rs/execution_environment/src/scheduler/threshold_signatures.rs
rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
rs/types/types/src/consensus/idkg/schnorr.rs

The threshold Schnorr request context contains the message to be signed, which may be up to 10Mib in size.  When iterating over open request contexts and building the signature inputs, this message is currently being cloned [here](https://sourcegraph.com/github.com/dfinity/ic/-/blob/rs/consensus/src/ecdsa/utils.rs?L292).
Although preliminary performance tests with a large number of maximum size tSchnorr request didn’t reveal any degradation in finalization rate, wrapping this message in an `Arc` reduced the average `on_state_change` duration by a factor of 2.

perf: CON-1360 Reduce cost of cloning tSchnorr inputs

---

.github/workflows-source/release-testing.yml
.github/workflows/release-testing.yml
gitlab-ci/src/dependencies/data_source/jira_finding_data_source.py

- dependency-scan-release-cut doesn't perform any actions on the Github but the token is loaded outside the instantiation which throws an [error](https://github.com/dfinity/ic/actions/runs/9966897303/job/27539714343#step:6:31). Hence, we export the token with default read perms to silence the error. 
- Remove `Finding` from warning logs.

fix(dependency-mgmt): Export `GITHUB_TOKEN` for `dependency-scan-release-cut` 

---

rs/ethereum/cketh/minter/tests/ckerc20.rs
rs/ethereum/cketh/test_utils/src/ckerc20.rs
rs/ethereum/ledger-suite-orchestrator/README.adoc
rs/ethereum/ledger-suite-orchestrator/ledger_suite_orchestrator.did
rs/ethereum/ledger-suite-orchestrator/src/candid/mod.rs
rs/ethereum/ledger-suite-orchestrator/src/scheduler/mod.rs
rs/ethereum/ledger-suite-orchestrator/src/scheduler/tests.rs
rs/ethereum/ledger-suite-orchestrator/src/state/test_fixtures.rs
rs/ethereum/ledger-suite-orchestrator/test_utils/src/arbitrary.rs
rs/ethereum/ledger-suite-orchestrator/test_utils/src/flow.rs
rs/ethereum/ledger-suite-orchestrator/test_utils/src/lib.rs
rs/ethereum/ledger-suite-orchestrator/tests/tests.rs
rs/tests/src/cross_chain/ic_xc_ledger_suite_orchestrator_test.rs

Follow-up on [MR-20019](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/20019) to simplify adding new ckERC20 tokens by changing the following fields in the ledger initialization arguments:
1. `minting_account` is removed
2. `fee_collector_account` is removed
3. `decimals` is no longer optional (the default value of `8` does not necessarily make sense depending on the underlying ERC-20 token).
4. `max_memo_length` is removed
5. `initial_balances` is removed
6. `feature_flags` is removed
7. `maximum_number_of_accounts` is removed
8. `accounts_overflow_trim_quantity` is removed
The ledger suite orchestrator provides meaningful default values for all removed fields. The same values were used in all the proposals that created ckERC20 tokens …

feat(ckerc20): Simplify adding new ckERC20 token (II)

---

hs/spec_compliance/src/IC/Test/Spec/HTTP.hs
packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/common/rest.rs
packages/pocket-ic/tests/test_canister.did
packages/pocket-ic/tests/test_canister.rs
packages/pocket-ic/tests/tests.rs
rs/https_outcalls/adapter/BUILD.bazel
rs/pocket_ic_server/BUILD.bazel
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/pocket_ic.rs
rs/pocket_ic_server/src/state_api/routes.rs
rs/pocket_ic_server/tests/spec_test.rs
rs/state_machine_tests/src/lib.rs

This MR contains a collection of preparatory steps for canister HTTP outcalls in PocketIC and unrelated little fixes in PocketIC:
- specification compliance tests for canister HTTP outcalls always use `https://` for invalid (in particular, non-localhost) domains (because the production canister HTTP outcalls adapter only allows `http://` for localhost domains)
- the PocketIC test canister contains (update/query) endpoints for testing canister HTTP outcalls in PocketIC
- the timestamps in PocketIC tests are set to timestamps after GENESIS (because every subnet's time is initialized to GENESIS and thus `StateMachine` produces a warning that time went back if timestamps in PocketIC tests are prior to GENESIS)
- update and fix the changelog (in particular, the function …

chore: collection of preparatory steps for canister HTTP outcalls in PocketIC and unrelated fixes

---

rs/crypto/ed25519/src/lib.rs

Previously ZIP215 batch verification of Ed25519 signatures used full size (253 bit) randomizers. However 128 bits is sufficient for security here, and is somewhat faster to execute.

perf(crypto): CRP-2542 Reduce the size of randomizers during Ed25519 batch verification

---

Cargo.lock
rs/nns/governance/BUILD.bazel
rs/nns/governance/Cargo.toml
rs/nns/governance/api/BUILD.bazel
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/src/pb/mod.rs

To improve build times, we want other parts of the build to not depend on the entire governance crate.  Additionally, we want to separate API types from internal governance types so that they can evolve independently.  This is a first mechanical step towards that end.
This MR creates type conversions from governance types to api types.  It does not yet use them, but allows Governance to start using them (in followup MRs) in the main canister file.

chore(nns): Add api <--> internal type conversions

---

rs/nns/governance/src/proposals/install_code.rs
rs/nns/integration_tests/src/canister_upgrade.rs

Previously, `install_code` proposal action is added without supporting upgrading root. This PR supports it.
We support creating a proposal with action `install_code` while specifying NNS Root as the target canister, and the proposal execution code will call the correct `upgrade_root` endpoint correctly (unlike upgrading other canisters which calls root). Note that `install` or `reinstall` modes aren't supported. It might not be obvious why `reinstall` isn't supported - HardResetRootToVersion supports "resetting" root, but the reset is implemented as an `uninstall_code` followed by `install_code` (with `Install` mode). This behavior seems to exceed what can be reasonably thought of as the `install_code` proposal action. Therefore, `HardResetRootToVersion` will remain as an NnsFunction and …

feat(nns): Support upgrading root canister through install_code

---

.github/workflows/slack-workflow-queue.yml

The `rust-benchmarks` jobs will have long wait times so it's best to exclude these from the queue time alert.

chore(IDX): exclude workflows with long wait times

---

rs/pocket_ic_server/BUILD.bazel
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/pocket_ic.rs
rs/pocket_ic_server/tests/test.rs

This MR makes PocketIC store the registry file on disk if a state_dir is specified for a PocketIC instance. This way, external users of PocketIC can retrieve the registry of a PocketIC instance and use it, e.g., when installing the NNS registry canister to initialize its state.

feat(PocketIC): store registry file in state_dir

---

packages/pocket-ic/src/lib.rs

This MR should mitigate test failures due to `Failed to start PocketIC service in time` by only starting the PocketIC server once per test suite (as opposed to once per each individual test and terminating the server early if another one is already running) and doubling the timeout for the PocketIC server to start from 5s to 10s.

chore: optimize starting PocketIC server in PocketIC library

---

rs/embedders/src/wasm_utils/instrumentation.rs
rs/embedders/src/wasmtime_embedder/host_memory.rs
rs/embedders/tests/wasmtime_embedder.rs

This MR caps the amount of Wasm64 heap a canister can request to 4 GiB (equal to the current Wasm32 heap size). In the future, this value will grow for Wasm64.

fix(RUN-1019): Cap Wasm64 heap memory size

---

buf.yaml
rs/nervous_system/proto/proto/ic_nervous_system/pb/v1/nervous_system.proto
rs/nervous_system/proto/src/gen/ic_nervous_system.pb.v1.rs
rs/nervous_system/proto/src/lib.rs
rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/pb/conversions.rs
rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
rs/sns/swap/src/types.rs

This allows us to keep the .did files clean, and keeps our .proto files organized, and lets us deduplicate some code

refactor(nervous_system): Move `Principals` message definition to nervous_system/proto

---

rs/consensus/src/consensus/validator.rs

In the validator tests, we pass around the subnet members explicitly to `get_block_maker_by_rank`. But this is redundant since we can get this information from `membership`.

chore(consensus): Compute subnet members from membership directly

---

rs/execution_environment/src/execution/update.rs
rs/execution_environment/src/execution_environment.rs
rs/execution_environment/src/scheduler.rs
rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
rs/replicated_state/src/canister_state.rs
rs/replicated_state/src/canister_state/execution_state.rs
rs/replicated_state/src/canister_state/system_state.rs
rs/system_api/src/lib.rs
rs/test_utilities/execution_environment/src/lib.rs
rs/types/types/src/messages.rs
rs/types/types/src/methods.rs

This PR starts the implementation of the OnLowWasmMemory hook. Here we are just adding a new type of SystemMehod/CanisterTask/ExecutionTask which is not called anywere.

feat: Add new type of task OnLowWasmMemory

---

bazel/conf/.bazelrc.build
bazel/conf/.bazelrc.internal

This moves some build filters & the verbose flag from the internal bazelrc to the base bazelrc, since they are not internal-only. This was overlooked in https://github.com/dfinity/ic/pull/459.

fix(IDX): move build filters

---

rs/nns/governance/api/src/pb.rs
rs/nns/governance/canister/canister.rs

As a further step in reducing direct dependencies on the nns governance crate, this reverses the direction of API dependencies so that the API crate defines the types that define the API, and other crates can then depend on the API crate instead of the governance canister crate and library

refactor(nns): Use governance_api instead of governance types in entrypoint in governance

---

rs/execution_environment/src/hypervisor/tests.rs
rs/execution_environment/src/scheduler/test_utilities.rs

This removes (via `cfg`) some code that isn't built on Apple Silicon. This fixes clippy hints for Apple Silicon.

fix(IDX): disable unused aarch64-darwin code

---

rs/bitcoin/ckbtc/minter/BUILD.bazel
rs/tests/boundary_nodes/BUILD.bazel
rs/tests/financial_integrations/BUILD.bazel
rs/tests/financial_integrations/ckbtc/BUILD.bazel
rs/tests/message_routing/BUILD.bazel
rs/tests/networking/BUILD.bazel
rs/tests/networking/canister_http/canister_http.rs
rs/tests/networking/canister_http_fault_tolerance_test.rs
rs/tests/src/boundary_nodes/boundary_nodes_integration.rs
rs/tests/src/certificate_orchestrator.rs
rs/tests/src/ckbtc/lib.rs
rs/tests/src/custom_domains_integration/setup.rs
rs/tests/src/icrc1_agent_test/mod.rs
rs/tests/src/message_routing/global_reboot_test.rs
rs/tests/src/message_routing/mod.rs
rs/tests/src/nns_dapp.rs
rs/tests/testing_verification/testnets/src_testing.rs

This updates tests to read the path of Wasm modules from environment variables, instead of hard coding Bazel-specific paths. This continues what was done for the NNS dapp here: https://github.com/dfinity/ic/pull/389

chore(IDX): set wasm paths via env

---

rs/universal_canister/impl/BUILD.bazel
scalability/BUILD.bazel

This PR cleans up Bazel files, removes duplicated comment and sorts required dependencies.

chore: cleanup Bazel files

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml
bazel/candid.bzl

As discussed in [this slack thread](https://dfinity.slack.com/archives/CL7Q2RXUM/p1721393630190629) the variable `CI_MERGE_REQUEST_TARGET_BRANCH_SHA` doesn't exist on GitHub which meant the `did_git_test` would always compare the compatibility of the Candid interface files of the PR with the PR itself, which would obviously always succeed.
We fix this by setting `CI_MERGE_REQUEST_TARGET_BRANCH_SHA` to `${{ github.event.pull_request.base.sha }}`.
Tested in https://github.com/dfinity/ic/pull/500 by applying this fix on a backwards incompatible change and observing that `//rs/sns/swap:sns-swap-canister_did_git_test` [fails](https://dash.zh1-idx1.dfinity.network/invocation/062e1d73-4bfd-43be-a98c-ad0415609d32?target=%2F%2Frs%2Fsns%2Fswap%3Asns-swap-canister_did_git_test&targetStatus=6) as …

fix(IDX): fix the did_git_test on GitHub

---

bazel/canisters.bzl
bazel/inject_version_into_wasm_tests/BUILD.bazel

This reduces the number of targets that `rust_canister` generates. In particular:
* The bin (transition base) `rust_binary` build is marked as `"manual"` so that the native build is not performed when e.g. running `bazel build //rs/...`
* A lot of intermediary targets (gzipping, metadata, shrinking) are removed and replaced with a single `finalize_wasm` pass, which helps decrease the total number of targets (less data duplicated, fewer cache downloads, etc)
This saves ~300 targets compared to previously (2305 -> 1991), including strictly unnecessary native builds of canisters.
The transition `whitelist` attribute is also replaced with `allowlist` (the former has been deprecated for a while).

chore(IDX): remove targets from rust_canister

---

rs/execution_environment/src/hypervisor/tests.rs

This is a follow up to https://github.com/dfinity/ic/pull/486 where one proptest import was missed. The import is not used on Apple Silicon.

fix(IDX): remove unused aarch64 import

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/src/storage/neurons/neurons_tests.rs
rs/nns/integration_tests/test_canisters/governance_mem_test_canister.rs

This just adds the ability to read the visibility of a neuron. There is not yet the ability to set it. Nor is this enforced.
This follows the plan described [here](https://forum.dfinity.org/t/request-for-comments-api-changes-for-public-private-neurons/33360).
Closes [NNS1-3072](https://dfinity.atlassian.net/browse/NNS1-3072).
[Next PR >>](https://github.com/dfinity/ic/pull/488)
[NNS1-3072]: https://dfinity.atlassian.net/browse/NNS1-3072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(nns): Added visibility field to neurons.

---

rs/config/src/http_handler.rs
rs/http_endpoints/public/src/lib.rs

For the new synchronous call endpoint we need to support concurrent HTTP requests in the order of thousands. We should therefore increase `SETTINGS_MAX_CONCURRENT_STREAMS` to 1000 to avoid intitating multiple TCP handshakes under load.

chore(http-endpoint): Increase `SETTINGS_MAX_CONCURRENT_STREAMS` to 1000

---

Cargo.toml
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/pocket_ic.rs
rs/pocket_ic_server/src/state_api/routes.rs
rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/test.rs

This MR makes the `CallRequest` operation of type V3 deterministic by not executing rounds on a background thread when computing that operation. This also enables parallel update calls of type V3 since no rounds are executed when submitting such update calls (via the `CallRequest` operation).

fix(PocketIC): make CallRequest of type V3 deterministic

---

rs/config/src/state_manager.rs

This PR reverts to the usage of memory-based allocator instead of file-backed allocators. This step enables a future optimization involving huge pages to speed up IO, which will come in the following release.

feat(RUN-1021): Revert to the memory allocator

---

rs/tests/testing_verification/testnets/BUILD.bazel

Creating a large testnet currently fails with 
```
Analyzing: target //rs/tests/testing_verification/testnets:large (0 packages loaded, 0 targets configured)
ERROR: /ic/rs/tests/testing_verification/testnets/BUILD.bazel:157:12: in run_system_test rule //rs/tests/testing_verification/testnets:large: label '//rs/rosetta-api/icrc1/ledger:ledger_canister' in $(location) expression is not a declared prerequisite of this rule
ERROR: /ic/rs/tests/testing_verification/testnets/BUILD.bazel:157:12: Analysis of target '//rs/tests/testing_verification/testnets:large' failed
ERROR: Analysis of target '//rs/tests/testing_verification/testnets:large' failed; build aborted:
```
This MR adds the ledger canister to the runtime depndencies.

fix: add missing large testnet runtime dependency

---

.github/CODEOWNERS
.gitlab/CODEOWNERS

This commit passes the code ownership of the state manager config file from networking to message routing.

chore: Code owners for state manager config

---

rs/protobuf/def/state/canister_snapshot_bits/v1/canister_snapshot_bits.proto
rs/protobuf/src/gen/state/state.canister_snapshot_bits.v1.rs
rs/state_layout/src/state_layout.rs
rs/state_layout/src/state_layout/tests.rs

This commit adds a `total_size` field to `CanisterSnapshotBits`, in accordance to the same field in `CanisterSnaphot`. This is in preparation for loading snapshots from disk during checkpointing, where this field is needed to construct a valid `CanisterSnapshot`.

fix: Add total_size to CanisterSnapshotBits

---

rs/consensus/src/idkg.rs
rs/interfaces/src/canister_http.rs
rs/types/types/src/consensus/idkg/schnorr.rs

1. Include tSchnorr pre-signatures
2. Update tEcdsa state machine to immediately start with `kappa_unmasked`
3. Clarify that "signature requests" are no longer matched with "available pre-signatures" to form "ongoing signatures" in the block payload. Instead, pre-signatures are delivered to the DSM and matched with signature requests as soon as they arrive.

chore: CON-1350 Update documentation to include tSchnorr

---

.github/workflows/test-namespace-darwin.yml
gitlab-ci/src/artifacts/upload.bash.template

This adds Apple Silicon (aarch64) builds for Darwin. This is a trial run with hardware from provider https://namespace.so.
This new check is not mandatory for PRs to be pass CI.

feat(IDX): Add Apple Silicon builds

---

rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/tests/governance.rs
rs/nns/sns-wasm/canister/sns-wasm.did
rs/sns/audit/src/lib.rs
rs/sns/init/src/lib.rs
rs/sns/integration_tests/src/initialization_flow.rs
rs/sns/swap/canister/swap.did
rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/src/types.rs
rs/sns/swap/tests/common/mod.rs
rs/sns/swap/tests/swap.rs

A `controller` field has been added to replace `hotkey_principal` (which is now deprecated and will hopefully be removed). New versions of the code populate both fields. New versions of the code only require at least one of the two fields to be populated.
This change is useful because the previous name for `controller`, `hotkey_principal`, is very confusing because it doesn't refer to the NNS neuron's hotkey, instead it refers to the NNS neuron's controller. (It is named that way because it becomes a hotkey on the SNS neuron that is allocated to that NNS neuron, but it does not represent a hotkey on the NNS neuron.)
A `hotkeys` field has been added.
This is useful because we want to transfer NF neurons' hotkeys from the NNS over to the SNS.
**None.** This MR merely extends various API …

refactor(nervous_system): Add `controller` and `hotkeys` fields to CfParticipant, CfNeuron, and CfInvestment

---

.github/workflows-source/ci-main.yml
.github/workflows-source/release-testing.yml
.github/workflows/ci-main.yml
.github/workflows/release-testing.yml
gitlab-ci/src/bazel-ci/main.sh
gitlab-ci/src/ci-scripts/build-ic.sh

This PR slightly changes the procedure of security hotfixes, where branches now only only need to follow the pattern `hotfix-*` instead of `hotfix-.*-rc--.*`. The reasons for this change are:
a) We have run into a lot of confusion in the past because of incorrect branch names
b) It lets us unify the hotfix process for both regular and ic-os (?) hotfixes
This change is backwards compatible, as branches with the `hotfix-.*-rc--.* ` will still behave the same.

refactor(IDX): simplify hotfix branch matching logic

---

.github/workflows/slack-workflow-run.yml

Small fix so that both successes and failures will be sent to #release-management-alerts

fix(IDX): update release testing channel

---

.github/workflows/test-namespace-darwin.yml

This ensures that we only run a single namespace-backed workflow at a time for any PR, branch or tag. This is similar to what we do with other runners and will help save some resources.

feat(IDX): limit namespace runs to 1

---

rs/cycles_account_manager/src/lib.rs
rs/execution_environment/tests/subnet_size_test.rs
rs/pocket_ic_server/src/pocket_ic.rs
rs/rosetta-api/icrc1/index-ng/tests/retrieve_blocks_from_ledger_interval.rs
rs/state_machine_tests/src/lib.rs
rs/tests/src/nns_tests/cycles_minting.rs
rs/tests/src/tecdsa/mod.rs

This PR removes an obsolete feature flag for scaling cycles cost depending on the subnet size.
The feature has been released a while ago and there is no need in such feature flag any more.
Before this change `state_machine_tests` framework had cost scaling disabled by default, therefore some tests with cycles cost assertions had to be updated.

chore: remove obsolete cost scaling feature flag

---

rs/tests/ict/cmd/testnetCreateCmd.go

Changed the file extension from `_log.txt` to `.log`. Most editors have highlighting for `.log` files making it easier to read the test output.

chore: change file extension for system test logs

---

.github/workflows/test-namespace-darwin.yml

This inlines the custom `namespace-profile-darwin-small` that we use for Darwin builds. Previously a `matrix` was used, though it was unnecessary since it only contained a single profile.

fix(IDX): inline namespace profile

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/src/pb/convert_struct_to_enum.rs
rs/nns/governance/src/pb/convert_struct_to_enum/manage_neuron.rs
rs/nns/governance/src/pb/convert_struct_to_enum/manage_neuron/configure.rs
rs/nns/governance/src/pb/mod.rs
rs/nns/governance/tests/governance.rs

Setting the visibility of known neurons is not allowed, [per the plan](https://forum.dfinity.org/t/request-for-comments-api-changes-for-public-private-neurons/33360#known-neurons-are-always-public-6).
As described [here](https://forum.dfinity.org/t/request-for-comments-api-changes-for-public-private-neurons/33360#reading-and-writing-visibility-4).
**Entrained change**: Added implementations of Command::from(struct) and Operation::from(struct). If desired, this could be split off pretty easily into another PR, because these changes are in their own commit (thanks to git rebase -i).
Closes [NNS1-3073](https://dfinity.atlassian.net/browse/NNS1-3073).
Closes [NNS1-3082](https://dfinity.atlassian.net/browse/NNS1-3082).
[<< Previous PR](https://github.com/dfinity/ic/pull/488)
[NNS1-3073]: …

feat(nns): Added setting neuron visibility.

---

publish/canisters/BUILD.bazel
rs/nervous_system/compressed_wasm_size_limits.bzl

The list of canisters that are being published/uploaded to github as artifacts include 
1. Officially released canisters that can be downloaded/verified by 3rd parties - https://github.com/dfinity/ic/blob/master/.github/workflows/tag-release.yml
2. Canisters required for dfx - https://github.com/dfinity/dfx-extensions/tree/main/extensions-utils/src/dependencies/download_wasms
3. Mainnet canisters - https://github.com/dfinity/ic/blob/master/mainnet-canisters.bzl

test: stop uploading test canister artifacts 

---

rs/sns/governance/src/proposal.rs

Currently there is no way to view the upgrade args from the NNS dapp. e.g. check [this sns proposal](https://nns.ic0.app/proposal/?u=jmod6-4iaaa-aaaaq-aadkq-cai&proposal=5):
We can't quite add a way to view them in a human-readable format, since they are encoded (so all we see is a `Vec<u8>`). And we don't normally put potentially-large blobs in the payload text rendering. However, we can at least show the hash. The encoded upgrade args are also available as part of the proposal payload returned by `get_proposal`.

feat(sns): Include hash of upgrade args in UpgradeSnsControlledCanister payload text rendering

---

.github/actions/bazel-test-all/action.yaml
.github/workflows/system-tests-k8s.yml

Adding `Sytem Tests K8s` workflow.

chore(IDX): k8s system tests workflow

---

.github/CODEOWNERS

`drun` is only used by the Languages team for testing. Moving the ownership to them so they can independently evolve it as they see fit.

chore: Move drun ownership to the languages team

---

packages/ic-signature-verification/CHANGELOG.md

Prepare ic-signature-verification's CHANGELOG for release of version 0.1.0 on crates.io.

chore(crypto): CRP-2551 adapt ic-signature-verification changelog

---

testnet/mainnet_revisions.json

The automation updating this file seems broken at the moment. We should still update it such that tests run against the correct mainnet version.
For currently deployed versions see https://grafana.mainnet.dfinity.network/d/release/release?orgId=1

chore: Manually update `testnet/mainnet_revisions.json`

---

rs/messaging/src/routing/stream_builder/tests.rs
rs/messaging/src/routing/stream_handler/tests.rs
rs/replicated_state/tests/canister_state.rs
rs/test_utilities/state/src/lib.rs

The function `register_callback()` takes a `CallbackId` as an argument. This suggests that this `CallbackId` is registered in the `CallContextManager` such that a response using this `CallbackId` can later be inducted successfully by passing this [sanity check](https://sourcegraph.com/github.com/dfinity/ic@rumenov/regtypes/-/blob/rs/replicated_state/src/canister_state/system_state/call_context_manager.rs?L599).
This is false. The `CallbackId` handed to `register_callback()` is used to construct an update call, but the origin of a call is irrelevant for the [sanity check](https://sourcegraph.com/github.com/dfinity/ic@rumenov/regtypes/-/blob/rs/replicated_state/src/canister_state/system_state/call_context_manager.rs?L599) because each message gets its own `CallbackId`. It is in general not …

refactor: Remove misleading `callback_id` from `register_callback()` test function

---

rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
rs/ethereum/evm-rpc-client/src/lib.rs
rs/ethereum/evm-rpc-client/src/types.rs

(XC-162): Continue the migration initiated in [MR-19972](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/19972) towards using the EVM-RPC canister to interact with the Ethereum JSON-RPC providers. This PR focuses specifically on the `eth_feeHistory` endpoint.

feat(ckerc20): Use EVM-RPC canister to call `eth_feeHistory`

---

testnet/env/shared-config.yml

Replace CH1 old prefix VLAN 66 subnet: `2607:f6f0:3004:1::/64` with the
new one: `2602:fb2b:120:10::/64`.
Add the new prefix along the old when possible.
This commit is related to FOPS-5186.

chore: Align CH1 IPv6 prefix

---

rs/nns/governance/BUILD.bazel
rs/nns/governance/api/BUILD.bazel
rs/nns/governance/protobuf_generator/src/main.rs
rs/nns/governance/tests/check_generated_files.rs

We separate the API types used in canister.rs from the internal types used in nns/governance.  This helps both with speeding up the builds (because we can remove dependencies on nns/governance) and with allowing independent evolution of the internal domain types and the API, which will allow us to make better APIs while still supporting older versions of the APIs.

refactor(nns): no longer generate api types from internal protos

---

rs/crypto/internal/crypto_service_provider/src/api/keygen.rs
rs/crypto/internal/crypto_service_provider/src/api/mod.rs
rs/crypto/internal/crypto_service_provider/src/lib.rs
rs/crypto/src/keygen/mod.rs
rs/crypto/src/keygen/tests.rs
rs/crypto/test_utils/csp/src/lib.rs

Refactors the code so that the crypto component bypasses the obsolete `CspPublicAndSecretKeyStoreChecker` and at the same time deletes it.

refactor(crypto): CRP-2453 remove CspPublicAndSecretKeyStoreChecker

---

rs/tests/src/orchestrator/subnet_recovery_app_subnet.rs

Increases the subnet size used in the large app subnet recovery test with tECDSA from 34 to 37.
One purpose of this test is to showcase how large app subnets with (all) chain keys enabled can be so that they can still be recovered. In local tests, the test succeeded around 50 times for 37 nodes, which seems sufficient for increasing the value permanently.

test(orchestrator): increase subnet size for sr_app_large_with_tecdsa_test to 37

---

rs/rosetta-api/ledger_canister_blocks_synchronizer/src/balance_book.rs
rs/rosetta-api/ledger_canister_blocks_synchronizer/tests/store_tests.rs
rs/rosetta-api/ledger_core/src/balances.rs

This modification is needed for the stable structure migration. StableBTreeMap is only able to return elements by value: https://docs.rs/ic-stable-structures/0.6.5/ic_stable_structures/btreemap/struct.BTreeMap.html#method.get

chore(ICP/ICRC-ledger): FI-1404: return value in BalanceStrore.get_balance

---

rs/messaging/src/scheduling/valid_set_rule.rs
rs/replicated_state/src/replicated_state.rs
rs/tests/src/execution/api_tests.rs
rs/types/types/src/messages/ingress_messages.rs

The error message for subnet methods that were not allowed through ingress was coupled with the error message of a method not found which can be misleading when an ingress message is not inducted. Additionally, improve the error message for `SubnetMethodNotAllowed` when parsing an ingress to mention directly that the message is not allowed through ingress instead of "can only be called by canisters". The two are not exactly equivalent, the example here being `fetch_canister_logs` which can only be called by non-replicated queries.

chore: Update error message for subnet methods that are not allowed through ingress messages

---

rs/execution_environment/src/query_handler/query_context.rs

This will help us identify more easily whether there are any legacy ICQC requests on system subnets in preparation of removing the feature eventually.

chore: Add logs to capture usages of legacy ICQC feature on system subnets

---

publish/binaries/BUILD.bazel

chore: revert "remove binaries which don't need to be released (e.g. stripped) and don't need to to uploaded to the CDN"

---

.github/workflows-source/ci-main.yml
.github/workflows-source/ci-pr-only.yml
.github/workflows/ci-main.yml
.github/workflows/ci-pr-only.yml
gitlab-ci/src/dependencies/job/bazel_rust_ic_scanner_merge_job.py
gitlab-ci/src/dependencies/job/bazel_rust_ic_scanner_periodic_job.py
gitlab-ci/src/dependencies/job/bazel_rust_ic_scanner_release_job.py
gitlab-ci/src/dependencies/job/bazel_trivy_container_ic_scanner_periodic_job.py
gitlab-ci/src/dependencies/job/npm_scanner_periodic_job.py
gitlab-ci/src/dependencies/model/ic.py
gitlab-ci/src/dependencies/scanner/dependency_scanner.py
gitlab-ci/src/dependencies/scanner/dependency_scanner_test.py
gitlab-ci/src/dependencies/scanner/manager/bazel_rust_dependency_manager.py
gitlab-ci/src/dependencies/scanner/manager/bazel_rust_dependency_manager_test.py
gitlab-ci/src/dependencies/scanner/manager/bazel_trivy_dependency_manager.py
gitlab-ci/src/dependencies/scanner/manager/dependency_manager.py
gitlab-ci/src/dependencies/scanner/manager/npm_dependency_manager.py

- Relative paths for `ic` / `ic-private` are removed. `ic.py` will provide the IC repo in use.
- Renabled dependency-mgmt tests
- Github actions URL needs are pulled from `ic.py` as well
- Set BRANCH_NAME to the right env_var

fix(dependency-mgmt): Adapt `ic` root directory checks

---

gitlab-ci/src/bazel-ci/main.sh

`gitlab-ci/src/bazel-ci/diff.sh` was invoked twice on GitHub: 
once (redundantly) in the code path for GitLab and 
once (correctly) in the code path for GitHub.
We fix this by dropping the code path for GitLab since we don't support it anymore.

fix(IDX): don't invoke gitlab-ci/src/bazel-ci/diff.sh twice

---

publish/canisters/BUILD.bazel

An artifact used by DRE qualification. Our team will look into removing this dependency ASAP. Until then this is needed.

chore: adding back xnet test canister

---

rs/nns/governance/canister/canister.rs

This removes two methods in governance that have long been deprecated and have not had any callers in the last year.

chore(nns): remove long deprecated unused method

---

.github/workflows/ci-pr-only-team-tags.yml

This fixes the label job in case the label had already been added, so that it does not cause CI to fail.

fix(ci): Fix team label job to not fail if label was already present

---

rs/nns/governance/src/governance.rs
rs/nns/governance/tests/governance.rs

Because this is new, and clients (e.g. nns-dapp) do not yet have the latest governance.did to fully deserialize these.
(Technically, clients can partially deserialize such proposals. Also, technically, clients could dynamically fetch the latest governance.did file, but this is a more advanced technique and not the typical way to do things.).
Closes [NNS1-3224](https://dfinity.atlassian.net/browse/NNS1-3224).
This will be reverted per [NNS1-3228](https://dfinity.atlassian.net/browse/NNS1-3228).
[NNS1-3228]: https://dfinity.atlassian.net/browse/NNS1-3228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NNS1-3224]: https://dfinity.atlassian.net/browse/NNS1-3224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

feat(nns): Disallow SetVisibility ManageNeuron proposals.

---

rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/canister.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/tests/governance.rs
rs/nns/integration_tests/src/governance_neurons.rs
rs/nns/test_utils/src/state_test_helpers.rs
rs/rosetta-api/src/request_handler/construction_payloads.rs
rs/tests/driver/src/canister_api.rs

[Per the plan](https://forum.dfinity.org/t/request-for-comments-api-changes-for-public-private-neurons/33360).
The upshot is that people can now read public neurons.
Fixed a bug from a [recent change of mine](https://github.com/dfinity/ic/pull/488) where neuron normalization was not applied 😬
Renamed list_neurons_by_principal to list_neurons in order to exactly match the Candid method name. Also, changed its &PrincipalId parameter to be of type PrincipalId, since that type is Copy.
Overhauled the implementation of (what is now called) Governance::list_neurons. This is the main thing I was touching anyway, but the change could have been smaller.
Added NeuronStore::can_principal_vote_on_proposals_that_target_neuron.
Refactored NeuronStore::get_full_neuron to use …

feat(nns): Added include_public_neurons_in_full_neurons to ListNeurons.

---

rs/nns/test_utils/src/state_test_helpers.rs

Deterministic Time Slicing, which allows large messages to execute across multiple rounds, was being tested in advance of releasing it as system settings.
Now that t[he system settings are being updated](https://github.com/dfinity/ic/pull/621), we no longer need special configuration to test this on system subnets.

chore(nns): Remove DTS config for NNS StateMachine tests (using defaults set at system level)

---

rs/nns/governance/tests/governance.rs
rs/sns/swap/canister/canister.rs
rs/sns/swap/canister/swap.did
rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/src/types.rs
rs/sns/swap/tests/swap.rs
rs/sns/test_utils/src/state_test_helpers.rs

The only principal that was allowed to call this method was NNS governance, but it no longer does that. It used to be the main thing that the OpenSnsTokenSwap proposal called, but that type of proposal can no longer be used.
Ofc, this is technically a backwards incompatible change, because we removed a method. However, it is safe, because previously, there was only one allowed caller, and that caller has stopped calling the removed method.

refactor(sns): Remove the open method from swap. [override-didc-check]

---

rs/sns/governance/src/types.rs
rs/sns/integration_tests/src/neuron.rs

This is needed as part of the NF neurons' hotkeys project, because we need to know that there is a safe number of hotkeys to set up on the SNS

fix(sns): NNS1-3206: Enforce a minimum on the maximum number of permissioned principals an SNS neuron is allowed to have

---

packages/pocket-ic/src/common/rest.rs
packages/pocket-ic/src/nonblocking.rs
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/main.rs
rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/test.rs

The MR makes it possible to specify the IP address at which the PocketIC server and HTTP gateway should listen. The default used to be `[::]`, but it shouldn't take a firewall rule to prevent connections to the PocketIC server from all network interfaces.

feat(PocketIC): specify IP address of PocketIC server and HTTP gateway

---

rs/execution_environment/tests/canister_logging.rs
rs/interfaces/src/messaging.rs

This is a follow-up to https://github.com/dfinity/ic/pull/540 that uses a single sentence for some error messages in `IngressInductionError`. Having two sentences seems somewhat redundant while a single sentence feels indeed a bit more readable.

chore: Use a single sentence for error messages in IngressInductionError

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

This workflow runs very frequently and takes up quite a lot of minutes (in total). Switch to self-hosted to save our minutes usage.

chore(IDX): switch python tests to self-hosted

---

rs/starter/src/lib.rs

Enable wasm64 in ic_starter, so people can start testing the feature with dfx

feat: RUN-1026: Enable wasm64 in ic_starter

---

rs/tests/consensus/BUILD.bazel

This will be picked up by the [system-test-benchmarks-nightly job](https://github.com/dfinity/ic/blob/master/.github/workflows-source/schedule-daily.yml#L154-L175)

test(consensus): [CON-1382] Run `consensus_performance_test` nightly

---

rs/embedders/src/wasmtime_embedder/system_api.rs
rs/embedders/tests/wasmtime_embedder.rs
rs/system_api/src/sandbox_safe_system_state.rs

Allow the canister to specify -1 (and other values >= u32::MAX) as a function index

chore: RUN-1025: Saturate function index in system api calls

---

rs/sns/governance/src/governance.rs
rs/sns/governance/src/types.rs

This PR simplifies the implementation of `claim_swap_neurons` in SnsGov by (1) retrofitting `NeuronRecipes` based on legacy struct `NeuronParameters` (if the new field was not set), and (2) processing the new neuron recipes in a uniformly.
< [Previous PR in this series](https://github.com/dfinity/ic/pull/596) |

chore(sns): Retrofit `NeuronRecipes` based on legacy struct `NeuronParameters`

---

rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/neuron_store/neuron_store_tests.rs

The number of hotkeys for each Neurons' Fund neuron must be limited due to SNS Governance constraints. This PR does the following two things:
1. Introduces a constant for the above-mentioned limit, `MAX_HOTKEYS_FROM_NEURONS_FUND_NEURON`, setting it to 4.
2. Implements a simple tactic for picking up to `MAX_HOTKEYS_FROM_NEURONS_FUND_NEURON` hotkeys out of all NNS neuron hotkeys.

feat(neurons-fund): Picking a finite number of NNS hotkeys for propagating to Neurons' Fund SNS neurons

---

rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/neuron.rs
rs/sns/governance/src/types.rs
rs/sns/governance/tests/governance.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/tests/swap.rs

Note that we transition to an entirely new type inside `ClaimSwapNeuronsRequest`, `NeuronRecipes` rather than `NeuronParameters`. However the types are generally very similar isomorphic. 
A `oneof` has been added to collect information that is unique to direct participants and neurons' fund participants.
They `hotkey` field has been replaced with `nns_neuron_controller`. This is convenient because otherwise the next change would have been confusing. The old field was named that way because it becomes a hotkey on the SNS neuron that is allocated to that NNS neuron, but it does not represent a hotkey on the NNS neuron.
A hotkeys field has been added.
This is useful because we want to transfer NF neurons' hotkeys from the NNS over to the SNS.
SNS Governance has been updated to support the …

refactor(sns): Add controller and hotkeys information to ClaimSwapNeuronsRequest, and use it in SNS Governance

---

.github/workflows-source/schedule-daily.yml
.github/workflows/schedule-daily.yml

Yesterday a 2nd `system_test_benchmarks` was added by https://github.com/dfinity/ic/pull/676 which [caused the error](https://github.com/dfinity/ic/actions/runs/10172391233/job/28134886611#step:5:30) that the `$GITHUB_ENV` was malformed. It apparently can't contain newlines so we turn those into spaces.
Tested it by running the "Schedule Daily" workflow on it here: https://github.com/dfinity/ic/actions/runs/10176317610/job/28145417148

fix(IDX): support multiple system_test_benchmarks in the system-tests-benchmarks-nightly job

---

rs/backup/src/backup_helper.rs
rs/backup/src/backup_manager.rs
rs/backup/src/notification_client.rs

Currently we check the disk usage every 5 minutes *and* every time we run ic-replay, and report a warning to slack when the remaining disk space is below a threshold.
With this change we will only send such a notification after we run ic-replay.
Also added a "storage type" label to the disk usage metrics so we know whether the metric is about the cold or hot storage (without having to look at the directory name)

chore(backup): [CON-1393] Check if the disk usage exceeds threshold only after running ic-replay

---

rs/starter/src/lib.rs

This will unblock the SDK team to work on integrating with the canister snapshots feature and testing it out.

chore: Enable canister snapshots in ic-starter

---

rs/types/types/src/batch/ingress.rs
rs/types/types/src/batch/self_validating.rs
rs/types/types/src/batch/xnet.rs
rs/types/types/src/consensus.rs
rs/types/types/src/consensus/catchup.rs
rs/types/types/src/consensus/dkg.rs

Also removed some unnecessary clones

chore(consensus): change the associated `Error` type of `TryFrom<pb>` from `String` to `ProxyDecodeError` for some consensus types

---

Cargo.lock
rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/neurons_fund.rs
rs/nns/governance/src/neurons_fund/neurons_fund_anonymization_tests.rs
rs/nns/governance/src/neurons_fund/neurons_fund_participation_constraints_tests.rs
rs/nns/governance/src/neurons_fund/neurons_fund_participation_tests.rs
rs/nns/governance/src/neurons_fund/polynomial_neurons_fund_participation_tests.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/tests/interleaving_tests.rs
rs/sns/governance/src/governance.rs
rs/sns/swap/BUILD.bazel
rs/sns/swap/Cargo.toml
rs/sns/swap/src/swap.rs
rs/sns/swap/tests/swap.rs

Neurons' Fund neuron information starts in NNS Governance, goes to Swap, then goes to SNS Governance. There were some places where we did not populate the hotkeys field, along this chain. This PR rectifies that, although it doesn't yet actually "complete" the chain as that is done in #629

chore(neurons_fund): Populate hotkeys when necessary in the NNS Governance → Swap → SNS Governance dataflow

---

Cargo.lock
rs/ic_os/launch-single-vm/src/main.rs
rs/tests/driver/BUILD.bazel
rs/tests/driver/Cargo.toml
rs/tests/driver/src/driver/bootstrap.rs
rs/tests/driver/src/driver/boundary_node.rs
rs/tests/driver/src/driver/nested.rs
rs/tests/driver/src/driver/resource.rs

[NODE-1399](https://dfinity.atlassian.net/browse/NODE-1399)
Update test driver to use zst ic-os images instead of gz images
[NODE-1399]: https://dfinity.atlassian.net/browse/NODE-1399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(NODE-1399): Update test driver to use zst images

---

rs/tests/driver/src/util.rs

We create the agent in the test driver [here](https://github.com/dfinity/ic/blob/3909a2cfe50518d54d217d4aa5918578591beb9c/rs/tests/driver/src/util.rs#L788) to run workloads in system tests. The agent can [by default only submit 50 requests concurrently](https://github.com/dfinity/agent-rs/blob/7e9489a65aba3e6993d8b96f6ef09e34a50837c1/ic-agent/src/agent/agent_config.rs#L20), which is a problem if we want to execute high RPS ingress message workloads against the synchronous call endpoint. It is a problem because in the worst case, we might have roughly the size of the ingress pool, ~10_000, requests concurrently to one replica, which all take 10s to resolve. In this scenario where each requests take 10s, the agent would only be able to send 50 requests every 10 seconds.
To prevent this …

test(test-driver): [NET-1738] Increase `max_concurrent_requests` in system test agent to 10_000

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron/types/tests.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/neuron_store/metrics.rs
rs/nns/governance/src/neuron_store/metrics/tests.rs
rs/nns/governance/tests/governance.rs

The problem is that there are (many) paths where normalization is not applied. This is a bug from a recent change that I did.
The solution (implemented here) is to make the Neuron::visibility field private, and add a (public) getter.
This obsoletes the previous solution: `fn normalized`. Thus, I deleted `normalized`.
This bug was discovered by strengthening an existing test (for public neuron metrics), which then started failing.

fix(nns): Fixed a bug where known neuron is not seen as public.

---

gitlab-ci/src/dependencies/model/ic.py
gitlab-ci/src/dependencies/scanner/dependency_scanner_test.py

Some failing tests for dependency-mgmt weren't captured #615 since there were only tested on `ic` CI jobs. This PR tries to address the missing changes in tests and was tested on [ic-private](https://github.com/dfinity/ic-private/pull/17)

fix(dependency-mgmt): fix `ic` root path in tests

---

gitlab-ci/tools/repro-check.sh

NODE-1401
We will update the upgrade gz image references in a later PR.

chore(NODE-1401): Update repro-check.sh SetupOS zst references

---

rs/config/src/execution_environment.rs
rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
rs/replicated_state/src/canister_snapshots.rs

This PR implements the limit on number of snapshots per canister as specified in the [interface spec PR](https://github.com/dfinity/interface-spec/pull/259/files#diff-b9a833d6114611a080aee4cd57618feb45aa044bcc11105d44b155b5bbde00ebR2477). The current limit is 1 snapshot per canister.

feat: Limit number of snapshots stored per canister

---

ic-os/defs.bzl

NODE-1401
Remove non-upgrade gz images from the build. Only merge after release proposals have been updated to link to zst images.

feat(NODE-1401): Remove non-upgrade gz images

---

rs/nns/governance/src/governance.rs
rs/nns/governance/tests/governance.rs

The `InstallCode` is to replace the `NnsCanisterUpgrade` and `NnsRootUpgrade` NNS functions. The large fields within them needs to be omitted in the same way as `ExecuteNnsFunction`
* Trigger `omit_large_fields` call `proposal_data_to_info` for multi queries
* Implement the omission logic to clear the wasm_module_and arg

feat(nns): Omit large fields for InstallCode

---

rs/rosetta-api/icrc1/ledger/sm-tests/BUILD.bazel
rs/rosetta-api/icrc1/ledger/sm-tests/src/in_memory_ledger.rs
rs/rosetta-api/icrc1/ledger/sm-tests/src/in_memory_ledger/tests.rs
rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs
rs/rosetta-api/icrc1/ledger/sm-tests/src/metrics.rs
rs/rosetta-api/icrc1/ledger/tests/tests.rs

Add an `InMemoryLedger` that creates an expected ICRC ledger state based on blocks retrieved from a deployed ICRC ledger and archive(s). Provide a `verify_ledger_state` helper function that takes a `StateMachine` and the ledger `CanisterId`, and retrieves the blocks from the ledger and its archive(s), reconstructs the expected ledger state wrt. account balances and allowances, and verifies that the balances and allowances on the deployed ledger matches those of the `InMemoryLedger`.

test(icrc_ledger): FI-1399: Add an InMemoryLedger for verifying ICRC ledger state

---

publish/canisters/BUILD.bazel

`bitcoin-mock-canister` is used in [snsdemo](https://github.com/dfinity/snsdemo/blob/3913867870d832d2884e32787054f7b902884379/bin/dfx-software-mock-bitcoin-install#L34) which creates the test environment for [NNS dapp](https://github.com/dfinity/nns-dapp/blob/71a89a811ba76f027633b770f2c6128895b2fc89/.github/actions/start_dfx_snapshot/action.yaml#L51).
It was removed in https://github.com/dfinity/ic/pull/533 after which the NNS dapp test environment stopped updating.
Add `bitcoin-mock-canister.wasm.gz` back to `CANISTERS` in `publish/canisters/BUILD.bazel`.
I'm not sure how to test this. I'm hoping the wasm will be published again after this PR is merged.

fix: Restore publishing bitcoin-mock-canister

---

.github/workflows/slack-workflow-queue.yml

This runs frequently that we should use our self-hosted runners to avoid using up minutes.

chore(IDX): switch queue check to self-hosted runner

---

.github/workflows/sync-public-with-private.yml

This runs frequently that we should use our self-hosted runners to avoid using up minutes.

chore(IDX): switch sync to self-hosted

---

.github/CODEOWNERS
.gitlab/CODEOWNERS

This reflects the recent merge of the teams.

chore: Replace team runtime with team execution in code owners

---

rs/prep/src/subnet_configuration/constants.rs

In the bigger effort of trying to unify configuration between subnets, we are working towards getting all subnets on the same DKG interval length of 499. Currently all subnets except the NNS use this configuration, and we plan to submit a proposal to have the NNS subnet use this configuration as well. Therefore, it makes sense that we update our default values for future subnet creations to also use this value of 499.

chore: update default dkg-interval-length to use 499 for all subnets

---

ic-os/components/upgrade/manageboot/guestos/manageboot.sh
ic-os/docs/Upgrades.adoc
ic-os/guestos/docs/Build.adoc
rs/ic_os/vsock/vsock_lib/src/host/agent.rs
rs/nns/integration_tests/src/upgrades_handler.rs
rs/nns/test_utils/src/registry.rs
rs/registry/admin/src/main.rs
rs/registry/canister/tests/hostos_version.rs
rs/registry/canister/tests/update_subnet_and_bless_replica_version.rs

NODE-1399
This PR should have no functional impact. It only updates some filenames to be agnostic to either gz or zst images, and it fixes some dummy links to be zst rather than gz.

chore(NODE-1399): Update gz references

---

Cargo.lock
Cargo.toml
rs/tests/networking/Cargo.toml

Rust-analyzer now also lints the networking system tests.

test: Include networking system tests as workspace member

---

rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/fs_ni_dkg/forward_secure.rs
rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/fs_ni_dkg/nizk_chunking.rs
rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/fs_ni_dkg/nizk_sharing.rs
rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/groth20_bls12_381/encryption.rs

If we decide to add parallel execution within the cryptography later this provides some guidepoints for doing so within NIDKG

chore(crypto): CRP-2547 Annotate where parallelism can be used in NIDKG

---

rs/tests/gix/BUILD.bazel
rs/tests/src/nns_dapp.rs
rs/tests/testing_verification/testnets/BUILD.bazel

The name of the env var pointing to the ICRC1 Ledger WASM is defined from [the key `ic-icrc1-ledger` here](https://github.com/dfinity/ic/blob/master/rs/tests/common.bzl#L243). So we have to use `IC_ICRC1_LEDGER_WASM_PATH` as the env var and not `ICRC1_LEDGER_WASM_PATH`.
It's also more consistent with [all other references to that canister](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/dfinity/ic%24+IC_ICRC1_LEDGER_WASM_PATH&patternType=keyword&sm=0).

fix(IDX): use correct env var to the icrc1-ledger WASM path

---

rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs

Tested manually using:
```bash
test_tmpdir="/tmp/$(whoami)/test_tmpdir"; echo "test_tmpdir=$test_tmpdir"; rm -rf "$test_tmpdir"; ict testnet create recovered_mainnet_nns --lifetime-mins 5 --set-required-host-features=dc=zh1 --verbose -- --test_tmpdir="$test_tmpdir"
```

fix(IDX): use the correct path to the XRC mock canister WASM

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
Cargo.toml
bazel/external_crates.bzl

Previously different versions of quinn were used for Bazel and for Cargo, perhaps by mistake.
This updates both quinn and quinn-udp to their latest crate release version.

chore: Update quinn to 0.11.3

---

rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/tests/governance.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/src/types.rs
rs/sns/swap/tests/swap.rs

#596 added `NeuronRecipes` in `ClaimSwapNeuronsRequest`, a replacement for `NeuronParameters`. This PR uses it in SNS Swap
| [Next PR](https://github.com/dfinity/ic/pull/705) >

refactor(sns): NNS1-3207: Use NeuronRecipes in SNS Swap

---

gitlab-ci/src/dependencies/job/npm_scanner_periodic_job.py

`oisy-wallet` supports only node v20 and [above](https://github.com/dfinity/oisy-wallet/blob/2c485e05bf1331da8290e70eedbf564b9f9923ca/package.json#L108)

chore(dependency-mgmt): Change `oisy-wallet` node version to 20

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
Cargo.toml
bazel/external_crates.bzl
rs/boundary_node/ic_boundary/Cargo.toml

Switching to our own fork of `cloudflare-rs` as it is not maintained and some APIs are broken due to deprecation of certain fields (`locked` and `multiple_railguns_allowed`).

fix: update cloudflare dependency [S3_UPLOAD]

---

rs/tests/BUILD.bazel

This ensures the system test images are not pulled on darwin, even if `//rs/tests/...` is built.
See also #772 which will add tests ensuring images don't get pulled on Darwin in the future.

fix(IDX): don't pull systest images on Darwin

---

rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/responses.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
rs/ethereum/cketh/minter/src/test_fixtures.rs
rs/ethereum/cketh/minter/tests/cketh.rs
rs/ethereum/cketh/test_utils/src/flow.rs
rs/ethereum/evm-rpc-client/src/lib.rs
rs/ethereum/evm-rpc-client/src/types.rs

([XC-165](https://dfinity.atlassian.net/browse/XC-165)): Continue the migration initiated in [MR-19972](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/19972) towards using the EVM-RPC canister to interact with the Ethereum JSON-RPC providers. This PR focuses specifically on the `eth_getTransactionReceipt` endpoint.
[XC-165]: https://dfinity.atlassian.net/browse/XC-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ckerc20): Use EVM-RPC canister to call `eth_getTransactionReceipt`

---

rs/ic_os/vsock/README.md
rs/ic_os/vsock/guest/src/main.rs
rs/ic_os/vsock/vsock_lib/src/host/agent.rs
rs/ic_os/vsock/vsock_lib/src/protocol/structures.rs
rs/ic_os/vsock/vsock_lib/src/protocol/utils.rs

NODE-1448
Set-node-id was a vsock command that was written but never used. This PR removes it from the codebase.

chore(NODE-1448): Remove obsolete set-node-id command

---

rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/proposals/create_service_nervous_system.rs
rs/nns/sns-wasm/canister/sns-wasm.did
rs/sns/init/proto/ic_sns_init/pb/v1/sns_init.proto
rs/sns/init/src/gen/ic_sns_init.pb.v1.rs
rs/sns/init/src/lib.rs

Since the NF participants cannot be specified upfront anymore, we remove `SnsInitPayload.neurons_fund_participants`.

chore(sns): Remove obsolete field `SnsInitPayload.neurons_fund_participants`

---

ic-os/components/upgrade/manageboot/guestos/manageboot.sh

The upgrade-install documentation incorrectly states that it "Installs a new system image into the spare partition and _changes bootloader to use it on next boot._"
It does not change the bootloader. upgrade-commit changes the bootloader

docs: fix upgrade-install documentation

---

Cargo.lock
rs/nervous_system/clients/src/canister_status.rs
rs/nervous_system/clients/src/management_canister_client/tests.rs
rs/nns/governance/BUILD.bazel
rs/nns/governance/Cargo.toml
rs/nns/governance/src/proposals/update_canister_settings.rs
rs/nns/handlers/root/impl/canister/canister.rs
rs/nns/handlers/root/impl/canister/root.did
rs/nns/handlers/root/impl/src/canister_management.rs
rs/nns/handlers/root/interface/src/client.rs
rs/nns/handlers/root/interface/src/lib.rs
rs/nns/integration_tests/src/update_canister_settings.rs
rs/sns/root/canister/root.did
rs/sns/swap/canister/canister.rs

The `UpdateCanisterSettings` proposal type was defined so that canisters controlled by NNS Root can have their settings changed. This PR implements the execution of the proposal.
* Define an NNS Root endpoint `update_canister_settings` and implement it by calling the management canister
* When the `UpdateCanisterSettings` proposal executes, call the `update_canister_settings` with the correct payload
* The `canister_status` client has its types updated to include new fields `wasm_memory_limit` and `log_visibility`
* Do not allow such proposals targeting NNS Root, since it needs another endpoint sent to Lifeline

feat(nns): Implement the execution of UpdateCanisterSettings proposals

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/proposals/install_code.rs
rs/nns/governance/src/proposals/stop_or_start_canister.rs
rs/nns/governance/src/proposals/update_canister_settings.rs

Context: https://forum.dfinity.org/t/refine-nns-proposals-topics/32125. Some NNS functions should be switched to new topics based on the new definition of the 3 related topics (2 new)
* Define a feature flag `enable_new_canister_management_topics`
* Move some existing logic behind `enable_new_canister_management_topics`
* Use new topics for some `ExecuteNnsFunction`s, conditioned on the flag

feat(nns): Switch NNS functions to new topics behind a feature flag

---

rs/execution_environment/tests/execution_test.rs
rs/replicated_state/src/canister_snapshots.rs
rs/replicated_state/src/replicated_state.rs
rs/state_machine_tests/src/lib.rs

This PR fixes a bug when calculating the subnet's available memory at the beginning of a round.
As a refresher, the general flow wrt available memory is the following:
1. At the beginning of every round, we calculate the subnet's available memory by subtracting all resources that take memory from the available capacity.
2. While executing messages in the round, we keep updating the available memory as needed depending on the type of message and the operations triggered by it.
With the new snapshot feature that's being developed, we want the snapshots to be considered against the subnet's capacity since they will be stored on disk and we need to ensure we have enough space available. We already [take into account the available memory](https://sourcegraph.com/github.com/dfinity/ic@c95b51dbc6 …

fix: [EXC-1673] Consider canister snapshots when calculating available subnet memory

---

rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/neurons_fund.rs

Since the maximum ingress message payload is 2 MB, we test that this limit is not exceeded with `MAX_NEURONS_FUND_PARTICIPANTS` participants.
Specifically, we need to know that Swap can observe that max number of NNS neuron portions each with the max allowed number of hotkeys. See `NeuronsFundSnapshot`

test(neurons-fund): Add tests for checking worst-case response size of `NnsGov.settle_neurons_fund_participation`

---

rs/embedders/src/wasmtime_embedder/system_api.rs
rs/execution_environment/src/hypervisor/tests.rs

Currently some System APIs smaller range of result than specified:
- ic0_canister_cycle_balance (returns i64 instead of u64)
- ic0_msg_cycles_available (returns i64 instead of u64)
- ic0_msg_cycles_refunded (returns i64 instead of u64)
- ic0_mint_cycles (returns i64 instead of u64)
- stable64_size (returns i64 instead of u64)
- stable_size (returns signed i32 instead of unsigned u32)
If the result doesn't fit into the narrow range, then the System APIs trap.
This PR fixes it and changes the System API return the correct range.
Regression tests are added for all System APIs except for `stable[64]_size()`
that can never return values that don't fit in `i32` (because the result is in Wasm pages).

fix: RUN-874: Fix the return type of some System APIs

---

rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
rs/ethereum/cketh/minter/src/withdraw.rs
rs/ethereum/cketh/test_utils/src/flow.rs
rs/ethereum/evm-rpc-client/src/lib.rs
rs/ethereum/evm-rpc-client/src/types.rs

([XC-164](https://dfinity.atlassian.net/browse/XC-164)): Continue the migration initiated in [MR-19972](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/19972) towards using the EVM-RPC canister to interact with the Ethereum JSON-RPC providers. This PR focuses specifically on the `eth_getTransactionCount` endpoint.
This endpoint needs to be handled slightly differently than the other ones because the same type `TransactionCount` is handled differently depending on the block height for which it was queried:
1. `Finalized`. In that case, equality between multiple `TransactionCount` for the same Ethereum address is expected.
2. `Latest`. In that case, equality between multiple `TransactionCount` for the same Ethereum address cannot be expected and so the minimum is taken.
[XC-164]: …

feat(ckerc20): Use EVM-RPC canister to call `eth_getTransactionCount`

---

Cargo.lock
rs/validator/ingress_message/BUILD.bazel
rs/validator/ingress_message/Cargo.toml
rs/validator/ingress_message/src/internal/mod.rs

This PR switches the ingress message validator crate from using `dfn_core::now()` (`dfn_core` is deprecated), to use the public Rust CDK instead.
`dfn_core` was written in way that would return some `Time` when compiled to native code which would allow the doc test to run successfully. In contrast, the CDK assumes that it compiles only to `Wasm` targets so we need to add some `cfg` directives to ensure the code can compile in either native or `Wasm` targets.

refactor: Use ic_cdk::api::time for ingress message validator crate

---

Cargo.lock
rs/rust_canisters/call_tree_test/BUILD.bazel
rs/rust_canisters/call_tree_test/Cargo.toml
rs/rust_canisters/call_tree_test/src/main.rs
rs/rust_canisters/downstream_calls_test/BUILD.bazel
rs/rust_canisters/downstream_calls_test/Cargo.toml
rs/rust_canisters/downstream_calls_test/src/main.rs
rs/rust_canisters/ecdsa/BUILD.bazel
rs/rust_canisters/ecdsa/Cargo.toml
rs/rust_canisters/ecdsa/src/main.rs
rs/rust_canisters/response_payload_test/BUILD.bazel
rs/rust_canisters/response_payload_test/Cargo.toml
rs/rust_canisters/response_payload_test/src/main.rs

This PR updates some of the test canisters included in `rust_canisters` to use the public CDK instead of the deprecated internal one (`dfn_core` and friends). The change is made for a set of canisters that were easy to port over. There are some more cases that are more nuanced and will happen in individual follow-ups.

refactor: Switch some test canisters in rust_canisters to use public CDK

---

rs/nns/governance/src/proposals/install_code.rs
rs/registry/admin/src/main.rs
rs/registry/admin/src/types.rs

The `InstallCode` and `StopOrStartCansiter` are 2 new proposal types to replace the `ExecuteNnsFunction` ones. Support creating them through ic-admin
Introduce a `no_use_legacy_execute_nns_function` option to use the new way of creating the proposals, and when it's true, create proposals using new format instead.

feat(ic-admin): Change IC Admin to support creating InstallCode and StopOrStartCansiter proposals

---

.github/workflows/system-tests-k8s.yml
rs/tests/system_tests.bzl

System-tests on k8s are already colocated so let's not run colocated system-tests in the `system-tests-k8s` workflow.
"System Tests K8s" workflow run:https://github.com/dfinity/ic/actions/runs/10290371878/job/28480183263.

fix(IDX): do not run colocated systests on k8s

---

Cargo.lock
rs/registry/admin/BUILD.bazel
rs/registry/admin/Cargo.toml
rs/registry/admin/src/main.rs
rs/registry/admin/src/types.rs

The `update_canister_settings` proposal type is added to NNS Governance (currently, for testing), and we should make it possible for someone to propose using ic-admin.
Define a subcommand to propose to update canister settings. For updating controllers, clap doesn't seem to support specifying a `Some(vec![])`, therefore another argument `--remove-all-controllers` is added for the case where `controllers` needs to be updated to be an empty list.
Tested end-to-end locally with different arguments

feat(ic-admin): Support sending update_canister_settings proposals through ic-admin

---

rs/types/types/src/consensus.rs
rs/types/types/src/exhaustive.rs

As far as I understand, currently we only have exhaustive tests for CUPs.
I'm adding similar tests for the other consensus artifacts

test(consensus): Add exhaustive serialization->deserialization test for `ConsensusMessage`

---

rs/http_endpoints/public/src/read_state/canister.rs
rs/http_endpoints/public/src/read_state/subnet.rs

`sparse_labeled_tree_from_paths` can be computationally intensive for certain inputs. To protect the tokio runtime we do the operation on the threadpool (as we already do for other things).

chore(http_endpoint): put compute intesive code in `/read_state` into `spawn_blocking` 

---

rs/nns/cmc/src/exchange_rate_canister.rs
rs/nns/cmc/src/lib.rs
rs/nns/cmc/src/main.rs

This PR initializes `average_icp_xdr_conversion_rate` with the same value that `icp_xdr_conversion_rate` is initialized with. This is convenient for testing, as e.g., the NNS Governance expects there to be some `average_icp_xdr_conversion_rate`, otherwise frequently printing errors to the log.

feat(cmc): Initialize `average_icp_xdr_conversion_rate`

---

gitlab-ci/container/build-image.sh

Fallback option if we cannot pull the ic-build image is to build the image locally. We were missing a tag after migrating to ghcr.io as a container registry. This PR adds it back.

fix: adding missing tag for build-image.sh

---

rs/https_outcalls/consensus/src/gossip.rs
rs/https_outcalls/consensus/src/pool_manager.rs

1. We modify the priority function so that we never fetch shares corresponding to more than `10` requests after the one we currently know.
2. We change the purging and the validation functions to only work on shares that belong to known and expected request ids.

chore(consensus): [Con-1227] defer shares handling created ahead

---

rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs

This fixes a discrepancy between the interface spec and the replica wrt the canister version stored in the `load_snaphot` history entry.
The change details of the history entry used to store the version of the canister after loading the snapshot (this already appears in the history entry anyway). However, it should contain the version of the canister at the time that the snapshot was taken -- this, along with the time taken and the snapshot id, fully describes the snapshot that was loaded back into the canister.

fix: Store the version of the snapshot that was loaded in canister history

---

rs/nns/constants/src/lib.rs
rs/nns/governance/src/proposals/install_code.rs
rs/nns/governance/src/proposals/mod.rs
rs/nns/governance/src/proposals/stop_or_start_canister.rs
rs/nns/governance/src/proposals/update_canister_settings.rs

Before this PR, the new proposal types only supports `ProtocolCanisterManagement` and returns error for other cansiters. 
Define mapping for SNS related canisters and the catch-all.

feat(nns): Add topic mapping for canister management topics

---

rs/nns/governance/src/storage.rs

This adds a very minimal validation to ensure reading data from stable storage after an upgrade won't panic.

chore(nns): Add post-upgrade validation for NP Rewards and audit events

---

rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/tests/fake.rs
rs/nns/governance/tests/governance.rs
rs/sns/init/src/lib.rs
rs/sns/integration_tests/src/payment_flow.rs
rs/sns/integration_tests/src/swap.rs
rs/sns/swap/canister/swap.did
rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/src/swap_builder.rs
rs/sns/swap/src/types.rs
rs/sns/swap/tests/swap.rs
rs/sns/test_utils/src/itest_helpers.rs

Since the NF participants cannot be specified upfront anymore, we remove `SwapInit.neurons_fund_participants`.

chore(sns): Obsolete `SwapInit.neurons_fund_participants`

---

rs/execution_environment/src/execution_environment.rs

The doc comment for `ExecutionEnvironment::execute_subnet_message` was incorrectly saying that we return instructions left but in reality we return instructions consumed by message execution (e.g. [for installing code](https://sourcegraph.com/github.com/dfinity/ic@af7db79a8e558715eef7a0a71f44db2da1c33da2/-/blob/rs/execution_environment/src/execution_environment.rs?L2996)).

fix(execution): Update doc comment

---

ic-os/components/monitoring/node_exporter/node_exporter
ic-os/components/prep/guestos/node_exporter/node_exporter.te

Recently the node exporter was upgraded from 1.2 to 1.8. With this change the `arp` and `netdev` collector switched to using `netlink` to collect metrics. The current selinux policy on the guestos does not allow the node exporter process to open netlink socket and therfore the the `arp` and `netdev` metrics are currently missing.
This MR disables the netlink metrics scarping by switching back to scaping `/proc/net/dev` as was done by default before version 1.4.

fix: disable node exporter netlink metrics collection

---

bazel/conf/.bazelrc.internal

Before this, build events were uploaded on every `build` & `test` locally. When developing, `build` commands are usually incremental & relatively fast, making the build event upload often take longer than the build itself.
This moves the build event related config to a new config which can be enabled with `--config=bes`, and makes the `--config=ci` inherit from it so that it's still enabled on CI.

chore(IDX): only upload build events on CI

---

rs/ethereum/cketh/minter/src/eth_rpc.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
rs/ethereum/cketh/minter/src/withdraw.rs
rs/ethereum/cketh/test_utils/src/flow.rs
rs/ethereum/evm-rpc-client/src/lib.rs
rs/ethereum/evm-rpc-client/src/types.rs

([XC-163](https://dfinity.atlassian.net/browse/XC-163)): Continue the migration initiated in [MR-19972](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/19972) towards using the EVM-RPC canister to interact with the Ethereum JSON-RPC providers. This PR focuses specifically on the `eth_sendRawTransaction` endpoint.
One notable change of behaviour is that when the EVM-RPC canister is used for `eth_sendRawTransaction`, all 3 providers (Ankr, Public Node and Llama Modes) will be queried in parallel, whereas the minter uses a minor optimization in querying all 3 providers sequentially until the first ok result, since the sent transaction is signed and cannot be altered.
[XC-163]: https://dfinity.atlassian.net/browse/XC-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …

feat(ckerc20): Use EVM-RPC canister to call `eth_sendRawTransaction`

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/mod.rs

This PR adds a (test-only) convenience feature to print a neuron's subaccount when `NnsGov.update_neuron` fails due to mismatched subaccount. This simplifies manual testing in which one typically does not have the neuron subaccount handy while trying to modify other, unrelated fields of the neuron.

test(nns): Make `NnsGov.update_neuron` fail more verbosely for attempted neuron subaccount updates

---

Cargo.lock
Cargo.toml
rs/nervous_system/temporary/BUILD.bazel
rs/nervous_system/temporary/Cargo.toml
rs/nervous_system/temporary/src/lib.rs
rs/nervous_system/temporary/tests/temporary.rs
rs/nns/governance/BUILD.bazel
rs/nns/governance/Cargo.toml
rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/merge_neurons.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/tests/merge_neurons.rs

This feature is currently disabled in release builds, and enabled in feature = "test" builds.
This also includes a tiny new library: ic_nervous_system_temporary. This just makes it easier to test flag-protected features. It makes it pretty easy to test the behavior both when the feature is enabled and when it is disabled without the need to test two different builds. This new library is in its own commit, which should make reviewing this PR easier.

feat(nns): Redact private neuron info fields.

---

rs/registry/canister/canister/canister.rs
rs/registry/canister/canister/registry.did
rs/registry/canister/src/mutations/do_revise_elected_replica_versions.rs

This PR effectively renames the (already unused) `Registry.update_elected_replica_versions` function into another (not yet used) `Registry.revise_elected_guestos_versions` function that follows the new naming convention for IC OS proposals (for details, see [NNS Gov proposal](https://dashboard.internetcomputer.org/proposal/129630) and [the forum discussion](https://forum.dfinity.org/t/bringing-clarity-to-icp-upgrade-proposals/29626)). 
Note that currently, the NNS Governance calls a yet another alias (`Registry.revise_elected_replica_versions`).
If and when the Registry is released with this API extension, it will enable switching NNS Governance to call the new function with a consistent name instead of the legacy one; after that, it will become possible to obsolete the legacy function …

feat(registry): Add consistently-named alias `Registry.revise_elected_guestos_versions` [override-didc-check]

---

rs/registry/canister/canister/canister.rs
rs/registry/canister/canister/registry.did

This PR removes the unused Registry function `bless_replica_version`, as it could only be used by NNS Governance which no longer uses it.

feat(registry): Remove unused function `Registry.bless_replica_version` [override-didc-check]

---

rs/registry/canister/canister/canister.rs
rs/registry/canister/canister/registry.did
rs/registry/canister/src/mutations/do_update_nodes_hostos_version.rs

This PR adds a new Registry function `Registry.deploy_hostos_to_some_nodes` that works exactly like the legacy `update_nodes_hostos_version` function but has a name that is consistent with the new IC OS proposal naming convention (for details, see [NNS Gov proposal](https://dashboard.internetcomputer.org/proposal/129630) and [the forum discussion](https://forum.dfinity.org/t/bringing-clarity-to-icp-upgrade-proposals/29626)).
If and when the Registry is released with this API extension, it will enable switching NNS Governance to call the new function with a consistent name instead of the legacy one; after that, it will become possible to obsolete the legacy function `update_nodes_hostos_version` for good.

feat(registry): Add consistently-named alias `Registry.deploy_hostos_to_some_nodes`

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml
.github/workflows/test-namespace-darwin.yml
gitlab-ci/config/main.yml
gitlab-ci/config/zz-generated-gitlab-ci.yaml
rs/execution_environment/BUILD.bazel

This moves some executions tests (known to be flaky on old Intel macs) to the namespace runners. The namespace workflow is also changed to not cancel current jobs on `master` so that we can check all commits built successfully on `master`. Finally the `test_macos_master` flag is renamed to `test_macos_slow`, which is more representative of what the tests are, and less tied to the environment (branch names, etc).

feat(IDX): run execution tests on namespace

---

bazel/conf/.bazelrc.build

This changes the bazel build on macOS CI to _not_ use `fastbuild`, i.e. changes the bazel build to build in release mode.
This means the published replica should be more performant, and this also reduces the size of some Bazel cache artifacts (librocksdb-sys went from 700MiB to 19MiB).

feat(idx): disable fastbuild on macos_ci

---

rs/registry/canister/canister/canister.rs
rs/registry/canister/canister/registry.did
rs/registry/canister/src/mutations/do_update_api_boundary_nodes_version.rs

This PR adds a new Registry function `Registry.deploy_guestos_to_some_api_boundary_nodes` that works exactly like the legacy `update_api_boundary_nodes_version` function but has a name that is consistent with the new IC OS proposal naming convention (for details, see [NNS Gov proposal](https://dashboard.internetcomputer.org/proposal/129630) and [the forum discussion](https://forum.dfinity.org/t/bringing-clarity-to-icp-upgrade-proposals/29626)).
If and when the Registry is released with this API extension, it will enable switching NNS Governance to call the new function with a consistent name instead of the legacy one; after that, it will become possible to obsolete the legacy function `update_api_boundary_nodes_version` for good.

feat(registry): Add consistently-named alias `Registry.deploy_guestos_to_some_api_boundary_nodes`

---

rs/tests/testing_verification/testnets/from_config.rs

This PR adds a simple comment documentation which is present in other testnets but was missing for this implementation

docs: `from_config.rs` testnet

---

rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
rs/replicated_state/src/canister_snapshots.rs
rs/replicated_state/src/canister_state.rs
rs/replicated_state/src/canister_state/system_state.rs
rs/state_layout/src/state_layout.rs
rs/state_layout/src/state_layout/tests.rs
rs/state_manager/src/checkpoint.rs
rs/state_manager/src/tip.rs

A new field is added in `SystemState` that captures the memory usage of all snapshots that belong to a canister. The field is updated whenever a snapshot is taken or deleted and it's persisted in the checkpoints as well.
The change is both backwards and forwards compatible as the new field will be initialized to 0 and will remain 0 while the feature is still disabled. Without any snapshots there's no functional difference as a memory usage of 0 would be additionally included in the canister's memory usage.

feat: EXC-1683: Include snapshot memory usage in canister's memory usage

---

rs/nns/governance/src/governance.rs

This PR makes legacy IC OS upgrade-related proposals obsolete, i.e., executing them will results in an error. This should be safe since in the past 4 months the teams responsible for these proposals have migrated their workflows to use the proposals as per the new IC OS convention. For details, see [NNS Gov proposal](https://dashboard.internetcomputer.org/proposal/129630) and [the forum discussion](https://forum.dfinity.org/t/bringing-clarity-to-icp-upgrade-proposals/29626).

feat(nns): Obsolete legacy IC OS proposals

---

rs/registry/canister/canister/canister.rs
rs/registry/canister/canister/registry.did
rs/registry/canister/src/mutations/do_update_api_boundary_nodes_version.rs

This PR renames `UpdateNodesHost`**`O`**`sVersionPayload` as `UpdateNodesHostosVersionPayload` to precisely follow the in-code capitalization convention for GuestOS. This is technically a breaking change, but it's safe to merge as the Registry has not been upgraded since the new type name was introduced in the [previous PR](https://github.com/dfinity/ic/pull/864).

feat(registry): Fix (undeployed) Registry API type name [override-didc-check]

---

rs/registry/canister/canister/canister.rs
rs/registry/canister/canister/registry.did

This PR removes the unused Registry function `retire_replica_version`, as it could only be used by NNS Governance which no longer uses it.

feat(registry): Remove unused function `Registry.retire_replica_version` [override-didc-check]

---

rs/config/src/subnet_config.rs
rs/execution_environment/benches/lib/src/common.rs
rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/canister_manager/tests.rs
rs/execution_environment/src/execution_environment.rs
rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
rs/execution_environment/src/lib.rs
rs/execution_environment/src/scheduler/test_utilities.rs
rs/execution_environment/src/scheduler/tests.rs
rs/test_utilities/execution_environment/src/lib.rs

This PR updates the canister manager to charge canisters that are executing `take_canister_snapshot` or `load_canister_snapshot`.
Closes EXC-1567

feat: EXC-1567: Add charging for take and load canister snapshot

---

bin/bazel-pin.sh
gitlab-ci/src/ci-scripts/lock-generate.sh

This consolidates the `lock-generate` and `bazel-pin` scripts, making the former use the latter instead of duplicating the logic.
The `bazel-pin` script is also updated to have more flexible argument handling, and is updated to support a `--force` argument. Unless `--force` is provided, the `bazel-pin` script will try to infer if a repin is indeed necessary, and if not, will not try to repin.
The `lock-generate` script is update to remove references to GitLab.

chore(IDX): consolidate lock-generate and bazel-pin

---

rs/nns/governance/src/proposals/install_code.rs
rs/nns/governance/src/proposals/stop_or_start_canister.rs
rs/nns/governance/src/proposals/update_canister_settings.rs
rs/nns/handlers/lifeline/impl/lifeline.did
rs/nns/handlers/lifeline/impl/lifeline.mo
rs/nns/integration_tests/src/update_canister_settings.rs

The `update_canister_settings` proposal type should work on cansiters controlled by root (already implemented) as well as root itself (this PR)
Only a controller of a canister can change its settings. lifeline is the controller of root. Therefore, execution of update settings proposals that target root are implemented by calling a (new) method of lifeline. Whereas, for all other NNS canisters, update settings proposals are implemented via a call to root.
* Add an endpoint on the lifeline (update_root_settings)
* Call `Lifeline::update_root_settings` from Governance for proposal execution
* Minor changes
* Fix the error messages for some times
* Fix the lifeline.did which was out-dated

feat(nns): Implement proposal execution for updating settings for root

---

rs/rosetta-api/icrc1/rosetta/src/main.rs

This MR introduces the following changes:
- Expose the ICRC Rosetta metadata at startup

feat(ICRC-Rosetta): FI-1407: expose metadata

---

packages/icrc-ledger-types/src/icrc21/lib.rs
rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs

This MR introduces the following changes:
1. Change the error message of ICRC-21 when a method is provided that is not supported

fix(ICRC-21): FI-1424: method not supported error message

---

publish/canisters/BUILD.bazel
rs/nns/governance/BUILD.bazel
rs/registry/canister/BUILD.bazel

The dfx-extensions [PR](https://github.com/dfinity/dfx-extensions/pull/106) keeping the canister WASM gzipped has been released in v0.4.1 and dfx v0.22.0 now uses a higher dfx-extensions v0.4.3 so we can safely switch back to optimizing NNS canister builds for performance (instructions) again, effectively reverting this [commit](https://github.com/dfinity/ic/commit/b32f4a47d41e1c84a2b2a7f9f65c6239ee73e8b1).

chore: optimize NNS canister builds again

---

WORKSPACE.bazel

This removes the custom `darwin_puller` that we set on `container_pull`, which was used to make the container pulls fail on Darwin.
The non-existent label caused issues with `bazel query` so they are removed. If the (now removed) check seems necessary in the future we'll figure out a better way to implement it.

fix(IDX): remove darwin container check

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/api/src/proposal_helpers.rs
rs/nns/governance/canister/canister.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/src/pb/mod.rs
rs/nns/integration_tests/BUILD.bazel
rs/nns/integration_tests/src/create_service_nervous_system.rs
rs/nns/integration_tests/src/cycles_minting_canister_with_exchange_rate_canister.rs
rs/nns/integration_tests/src/governance_time_warp.rs
rs/nns/integration_tests/src/known_neurons.rs
rs/nns/integration_tests/src/node_assignment.rs
rs/nns/integration_tests/src/node_operator_handler.rs
rs/nns/integration_tests/src/node_provider_remuneration.rs
rs/nns/integration_tests/src/rewards.rs
rs/nns/integration_tests/src/stop_or_start_canister.rs
rs/nns/integration_tests/src/subnet_rental_canister.rs
rs/nns/integration_tests/src/uninstall_canister_by_proposal.rs
rs/nns/integration_tests/src/update_canister_settings.rs
rs/nns/integration_tests/src/wait_for_quiet.rs
rs/nns/test_utils/src/neuron_helpers.rs
rs/nns/test_utils/src/state_test_helpers.rs
rs/registry/admin/src/main.rs
rs/registry/admin/src/types.rs
rs/sns/integration_tests/src/initialization_flow.rs
rs/tests/src/rosetta_tests/governance_client.rs
rs/tests/src/rosetta_tests/tests/neuron_voting.rs

The `InstallCode` proposal contains unbounded blobs, and when reading such proposals from NNS Governance, there is no need to return the blobs themselves, but the hashes should be enough. The proposal summary should already explain how the proposal can be verified against the hashes.
* Introduce a new set of API types for the proposal for input (when proposals are made), different from the ones in the output (`get_proposal_info`, `list_proposals` and `get_pending_proposals`)
* For the API output types, replace `wasm_module` and `arg` with `wasm_module_hash` and `arg_hash`
* When converting from the internal type to the API output type, calculate the hashes
Among all the possible requests sent to NNS Governance, the canister should behave in the exact same way as before:
* For everything …

feat(nns): Change InstallCode proposal to always return wasm_module_hash and arg_hash

---

rs/tests/consensus/consensus_performance.rs
rs/tests/consensus/tecdsa/tecdsa_performance_test.rs
rs/tests/consensus/utils/src/lib.rs
rs/tests/driver/src/driver/simulate_network.rs
rs/tests/execution/fill_execution_rounds_workload.rs
rs/tests/networking/p2p_performance.rs
rs/tests/src/networking/p2p_performance_workload.rs

This MR refactors the `simulate_network` module to support more functionality, and refactors all system tests in the `consensus` directory to use this module.
The previous implementation of setting simulated latencies in the consensus system tests were faulty due to the transmission control buffers overflowing, leading to packets being dropped. This is now fixed.
As a consequence, the [SUCCESS_THRESHOLD](https://github.com/dfinity/ic/blob/d253a7a508d37d8922ea7968e98f52e8c139edf8/rs/tests/consensus/consensus_performance.rs#L89) in `consensus_performance.rs` can be removed as all requests now succeed.

test(network-simulation): Increase transmission control buffers

---

rs/rosetta-api/icp_ledger/ledger.did
rs/rosetta-api/icp_ledger/ledger/src/lib.rs
rs/rosetta-api/icp_ledger/ledger/tests/tests.rs
rs/rosetta-api/icp_ledger/src/lib.rs
rs/rosetta-api/icp_ledger/tests/golden_nns_state.rs
rs/rosetta-api/icp_ledger/tests/tests.rs
rs/rosetta-api/icrc1/index-ng/tests/tests.rs
rs/rosetta-api/icrc1/ledger/ledger.did
rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs
rs/rosetta-api/icrc1/ledger/src/lib.rs

1. Remove the maximum number of accounts from the upgrade arguments
This change is done, to close a possible vulnerability where the maximum number of accounts is set to 0 or a very small number.

chore(ICP-Ledger): FI-1426: remove maximum number of accounts

---

rs/artifact_pool/src/inmemory_pool.rs
rs/artifact_pool/src/lmdb_pool.rs
rs/artifact_pool/src/test_utils.rs
rs/consensus/src/consensus/purger.rs
rs/interfaces/src/consensus_pool.rs

Equivocation proofs are not needed at `h <= finalized_height`. Purging them more aggressively gives us a better upper bound for the artifact counts.

feat(consensus): [CON-1396] Purge equivocation proofs below and at finalized height

---

rs/ic_os/dflate/BUILD.bazel
rs/ic_os/dflate/src/lib.rs

NODE-1454
The following optimizations were done:
- Use a BufReader and remove unnecessary seeking
- Use a pre-allocated buffer instead of allocating a new buffer for every 512 bytes read
- Modify `is_empty` implementation so Rust generates more efficient assembly
I also added a test which passes both before and after the optimizations.
The optimizations make dflate on average ~2.5x faster in our build invocations, saving ~20seconds when building` //ic-os/guestos/envs/dev`
[NODE-1454]: https://dfinity.atlassian.net/browse/NODE-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

perf: Optimize the implementation of dflate and add a test

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs

We previously auto-generated these, but the auto-generated added a lot of cruft because the files were not meant to be hand-edited. Now that we're hand-editing them, we can simplify some of that.
This PR does **not** actually change any of the types in a practical sense, it just reorganizes how they refer to the types of their fields

refactor(nns): Cleanup NNS Governance API type definitions

---

rs/consensus/src/consensus/bounds.rs

With https://github.com/dfinity/ic/pull/927 implemented, we can place a fairly good bound on equivocation proofs.

feat(consensus): [CON-1324] Implement artifact pool bounds for equivocation proofs

---

rs/replicated_state/src/canister_state.rs
rs/replicated_state/src/canister_state/queues.rs
rs/replicated_state/src/canister_state/queues/tests.rs
rs/replicated_state/tests/replicated_state.rs
rs/test_utilities/state/src/lib.rs

* Make it obvious (via naming and documentation) that the strategies only populate output queues.
* Adjust the ratio of messages to queues, to make it more likely (with best-effort messages) for all messages in some queues to expire.
* Use `prop_assert!()` instead of plain `assert!()`.

test: Clean up `CanisterQueues` proptests

---

rs/orchestrator/src/upgrade.rs

This warning was previously logged whenever a node joins an ECDSA/Schnorr subnet, or a node that isn't part of an ECDSA/Schnorr subnet restarts, as these nodes never persisted a metric file beforehand. We can make it less noisy and more meaningful by only logging a warning if the file exists and then cannot be opened or read.

chore: CON-1356 Make `Cannot report master public key changed metric` warning less noisy

---

.github/workflows/team-channels.json

Add Slack channel for "languages" team as used for PR notifications of `drun`, see https://github.com/dfinity/ic/pull/565.

chore(IDX): Add `languages` team channel

---

rs/artifact_pool/Cargo.toml

Currently, `nix` build fails on MacOS saying that the `rocksdb` dependency is missing. (We still use `nix` for Motoko's CI.) 
I believe, the reason is that `macos` is not a target family but only a target OS. This change resolves this problem.

fix(IDX): Fix `nix` MacOs build for `rocksdb` dependency

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
bazel/external_crates.bzl
packages/ic-signature-verification/Cargo.toml

Changes `ic-signature-verification`'s dependency on `ic-verify-bls-signature` so that the `rand` feature is no longer used. For this, an upgrade from version `0.2` to `0.6` is needed/performed. This is done so that the `ic-signature-verification` crate can be used in WASM environments.
Finishes addressing CRP-2575 after https://github.com/dfinity/verify-bls-signatures/pull/11.

feat(crypto): CRP-2575: remove ic-signature-verification's dependency on rand

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/tests/governance.rs

As usual for new features, this is disabled in production.
In the future, [this feature will be enabled](https://dfinity.atlassian.net/browse/NNS1-3252). After a probation period, the [flag will be deleted](https://dfinity.atlassian.net/browse/NNS1-3228).
Unblocks [NNS1-3225](https://dfinity.atlassian.net/browse/NNS1-3225).
[NNS1-3225]: https://dfinity.atlassian.net/browse/NNS1-3225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(nns): Flag for SetVisibility Proposals.

---

rs/ic_os/inject_files/BUILD.bazel
rs/ic_os/partition_tools/src/ext.rs

NODE-1454
This change improves the build time of `//ic-os/guestos/envs/dev` by 30s.
Previously we used Tokio's `io::copy` which has very bad performance because (unlike the sync version in stdlib) it reads the file to a user space buffer before copying it to the target. `fs::copy` performs much better but doesn't allow seeking.
I considered a few approaches and decided to use `fs::copy` on the fast path and keep `io::copy` when necessary. Alternative approaches could be using sync IO in our build tools (I believe we don't gain anything from Tokio here but I'd need to verify this claim) or trying to fix Tokio's `io::copy`.

perf: Optimize the inject_files tool

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/canister.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/governance/tests/node_provider_rewards.rs
rs/nns/governance/src/node_provider_rewards.rs
rs/nns/integration_tests/src/node_provider_remuneration.rs
rs/nns/test_utils/src/state_test_helpers.rs

This adds a simple endpoint to load previous node provider rewards.
Followup work to add a filter will happen.  For now, it includes up to the most recent 5 results.

feat(nns): Add endpoint to get historical node provider rewards

---

publish/canisters/BUILD.bazel

This PR mitigates the recent growth of the compressed WASM size of the NNS Governance canister by bumping the size limit from 1.3 to 1.4 MB.

chore: Bump governance-canister / governance-canister_test compressed WASM size limit from 1.3 to 1.4 MB

---

Cargo.lock
packages/ic-signature-verification/CHANGELOG.md
packages/ic-signature-verification/Cargo.toml

Bumps `ic-signature-verification`'s version to 0.2.0 and updates the changelog.

chore(crypto): CRP-2575: bump ic-signature-verification version to 0.2

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Because RC branches can also be manually triggered we want to still run the Darwin tests on all other trigger types. They still won't be triggered on merge trains as we have that logic excluded at the job level.

fix(IDX): update darwin trigger logic

---

Cargo.lock
rs/replicated_state/BUILD.bazel
rs/replicated_state/Cargo.toml
rs/replicated_state/src/canister_state/queues/tests.rs

There is no change in functionality. The benefit of using `#[strategy]` annotations is that the code is formatted as expected, unlike the code within the `proptest! {...}` macro.

chore: Convert proptests to test strategy

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/canister.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/node_provider_rewards.rs
rs/nns/governance/src/node_provider_rewards.rs
rs/nns/integration_tests/src/node_provider_remuneration.rs
rs/nns/test_utils/src/state_test_helpers.rs

Add simple date filtering to list_node_provider_rewards to allow selecting individual reward events.
Also increases rewards limit to 24, as each reward event is about 18kb, so 24 is still only 432kb which gives a lot of room for increasing reward data sizes in the future.

feat(nns): Add date filtering to list_node_provider_rewards

---

rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/test.rs

This PR fixes PocketIC HTTP gateway to handle (/api/v2 and /api/v3) requests with IP address hosts.
Implementation-wise, this PR moves the HTTP request's domain resolution from an axum middleware (applied to all requests) to the fallback handler (applied only to requests that do not target /api/v2 or /api/v3).

fix(PocketIC): HTTP gateway can handle requests with IP address hosts

---

.github/workflows-source/schedule-daily.yml
.github/workflows/schedule-daily.yml
bazel/conf/.bazelrc.build
rs/rosetta-api/icp_ledger/BUILD.bazel
rs/rosetta-api/icrc1/BUILD.bazel

Add the golden state upgrade and downgrade tests for the ICP and ICRC ledgers to the nightly pipeline.

test(ICP_ledger): FI-1388: Add golden state tests to nightly

---

rs/nervous_system/common/src/lib.rs
rs/nervous_system/integration_tests/tests/constraints_dependencies.rs
rs/sns/init/src/lib.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/tests/swap.rs

This PR implements a more liberal enforcement for the max number of SNS neurons. Currently, we enforce that the worst case is passable (by validating the SNS init config at proposal submission time), while this rejects some viable swap scenarios, including those that occurred in production in the past. With this change, we can enforce the limits much later, so the overly strict SNS init validation could be lifted (this will be a follow-up PR).
For more details, see [this forum thread](https://forum.dfinity.org/t/swaps-to-allow-at-most-100k-sns-neurons-for-direct-participants).

feat(sns): Reject new participants if the maximum number of required SNS neurons has been reached

---

rs/nns/init/src/lib.rs

This commit modifies the `set_up_env_vars_for_all_canisters` function in `lib.rs` to search for NNS canister wasms in the specified directory. It checks for both `.wasm` and `.wasm.gz` files and sets up environment variables accordingly. If a file is not found, it fails with an assertion error, as usual.

feat(nns-init): Add support for gzipped NNS canister wasms

---

rs/nns/constants/src/lib.rs
rs/nns/sns-wasm/canister/canister.rs

This allows the constant to be used in other tests and canisters
[Next PR →](https://github.com/dfinity/ic/pull/1054)

chore(sns): Move DEFAULT_SNS_FRAMEWORK_CANISTER_WASM_MEMORY_LIMIT constant to ic-nns-common

---

rs/nns/governance/canister/canister.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did

This removes a no longer relevant field from the response (use_registry_derived_rewards) that is only useful as part of the proposal to reward node providers (which is also no longer used).
It also adds all the new fields to the response that are already available and are helpful to clients in using this data.
The two types in the PR are compatible from a candid API perspective, so migrating from one to the other is equivalent to removing an unneeded field and adding the new fields.

feat(nns): add additional fields to get_monthly_node_provider_rewards

---

rs/rosetta-api/icp_ledger/tests/upgrade_downgrade.rs

We upgraded ledger without upgrading archive so the test fails again when trying to update mainnet-canisters.bzl. We should re-enable the test once they have been upgraded to the same versions
[Next PR](https://github.com/dfinity/ic/pull/1001) (not relevant to FI team)

chore: Ignore should_spawn_a_new_archive_with_icp_transfers

---

rs/bitcoin/ckbtc/minter/src/metrics.rs
rs/ethereum/cketh/minter/src/main.rs
rs/ethereum/ledger-suite-orchestrator/src/main.rs

([XC-175](https://dfinity.atlassian.net/browse/XC-175)): Add a new metric `X_heap_memory_bytes` to track the heap memory used by a canister, where `X` is one of the following 3 canisters owned by the cross-chain team:
1. ckBTC minter
2. ckETH minter
3. ckERC20 ledger suite orchestrator
This complements the already existing metric `X_stable_memory_bytes`, that tracks the amount of stable memory used by those canisters.
[XC-175]: https://dfinity.atlassian.net/browse/XC-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add a metric to track the total memory usage of XC-canisters

---

.github/workflows/rosetta-release.yml

Seems to be that some dependencies are required to correctly run bazel, so we need to run the CI job inside our own image.

fix(IDX): run rosetta-release on build-ic container

---

rs/nns/governance/src/governance.rs
rs/registry/admin/src/main.rs
rs/tests/driver/src/nns.rs

This PR is the penultimate step towards consistency w.r.t. [this table](https://forum.dfinity.org/t/bringing-clarity-to-icp-upgrade-proposls/29626#summary-of-the-planned-changes-6). In particular, it changes the Registry functions that are called for the following NNS proposals:
* `ReviseElectedGuestosVersions`
* `revise_elected_replica_versions` → `revise_elected_guestos_versions`
* `ReviseElectedHostosVersions`
* `update_elected_hostos_versions` → `revise_elected_hostos_versions`
* `DeployHostosToSomeNodes`
* `update_nodes_hostos_version` → `deploy_hostos_to_some_nodes`
* `DeployGuestosToSomeApiBoundaryNodes`
* `update_api_boundary_nodes_version` → `deploy_guestos_to_some_api_boundary_nodes`
Additionally, this PR adjusts ic-admin and some system tests to form the respective new …

feat(nns): Call new IC OS upgrade-related Registry functions instead of deprecated ones

---

rs/nns/canister_ids.json
testnet/tools/nns-tools/lib/canister_wasms.sh

Add metadata regarding the ICP index canister to the `rs/nns/canister_ids.json` and `testnet/tools/nns-tools/lib/canister_wasms.sh` files, so that the `testnet/tools/nns-tools/test-canister-upgrade.sh` script can be used to upgrade the ICP index canister on the dynamic testnet with golden state.

test(ICP_index): FI-1445: Add ICP index canister to canister_ids.json and canister_wasms.sh

---

Cargo.lock
rs/sns/init/src/lib.rs
rs/sns/integration_tests/src/root.rs
rs/sns/root/BUILD.bazel
rs/sns/root/Cargo.toml
rs/sns/root/canister/canister.rs
rs/sns/root/canister/root.did
rs/sns/root/proto/ic_sns_root/pb/v1/root.proto
rs/sns/root/src/gen/ic_sns_root.pb.v1.rs
rs/sns/root/src/lib.rs

See the description of [NNS1-3202](https://dfinity.atlassian.net/browse/NNS1-3202).
The objective is to set SNS Framework canisters' memory limits to be explicitly 4GiB, rather than None, which will unblock the ongoing effort to change the default when it is not explicitly set.
Changing the memory limits of swap and root will need to be done separately, as they cannot be changed by root
[NNS1-3202]: https://dfinity.atlassian.net/browse/NNS1-3202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(nns): Automatically set SNS Governance, Ledger, Index, Archive canisters memory limits once

---

rs/cross-chain/proposal-cli/src/ic_admin/mod.rs
rs/cross-chain/proposal-cli/src/main.rs

(XC-173): Improve the generated `ic-admin` command introduced in #1007 by using relative paths to reference the files associated with the submission of a proposal (wasm, binary arguments and summary). This is needed because typically the proposal will be submitted from a different machine than where those files were generated.

fix(proposal-cli): use relative paths for generated `ic-admin` command

---

rs/tests/src/orchestrator/upgrade_downgrade.rs

In this test we send ingress messages to make sure that we can store and read messages after an upgrade. At the same time we send a workload of ECDSA/Schnorr messages to test the compatibility.
Because the Schnorr messages have a size of ~2MB, they sometimes block other ingress messages from being included, meaning they will expire and cause flakiness of the test.
As this isn't a performance test, reducing Schnorr messages to have a more reasonable size shouldn't be an issue.

fix(tests): Reduce Schnorr Message Size in upgrade_downgrade Tests

---

rs/registry/admin/src/main.rs

change-subnet-membership should be used instead of separate remove-node and add-node commands.
The `change-subnet-membership` command provides atomic node and removal, so both operations can be performed in a single proposal.
Also, prominently show suggestions to use the DRE tool for submitting this type of proposal, since the DRE tool calculates and optimizes subnet decentralization instead of blindly adding or removing nodes.

chore(ic-admin): Remove deprecated commands for subnet node add and remove

---

rs/replicated_state/src/canister_state/queues/tests.rs

The new `CanisterQueues` implementation expects unique `CallbackIds` for all inbound responses (and refuses to decode the proto otherwise). Tweak the `CanisterQueues` fixtures to generate inbound responses and outbound requests (in case they generate reject responses in the test) with unique `CallbackIds`.

test: Forward compatibility for `queues_compatibility_test`

---

rs/cross-chain/proposal-cli/src/canister/mod.rs

Remove the `rs/rosetta-api/icrc1/index-ng` directory from the list of directories from which commits are listed in generating the change log for canister upgrade proposals for the ICP index canister.

fix(proposal-cli): FI-1451: Remove rs/rosetta-api/icrc1/index-ng from git log for ICP index canister

---

rs/cross-chain/proposal-cli/src/git/mod.rs

Wrap the `git log --format` parameters in quotes for the `summary.md` file, so that the command can be copy & pasted and run from the summary.

fix(proposal-cli): FI-1452: Wrap git log format parameters in quotes for the summary.md file

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/src/pb/mod.rs
rs/nns/governance/src/pb/tests.rs
rs/nns/governance/src/proposals/install_code.rs
rs/nns/governance/tests/governance.rs
rs/nns/integration_tests/src/canister_upgrade.rs
rs/registry/admin/src/main.rs

The predecessor of `InstallCode` - the NnsCanisterUpgrade function has `Vec<u8>` as the type of [the arg](https://github.com/dfinity/ic/blob/2a2b74684b55c40d514c2e80165432e906dddbf5/rs/nervous_system/root/src/change_canister.rs#L49). We should keep this consistency.
* Only hashes the arg if it's not empty, and returns empty string if the arg is empty. It would be more difficult to understand if we return `sha256([])` instead
* Disallow `None` when submitting the proposal. Since `ic0.install_code` accepts `vec nat8`, we don't want to allow 2 ways (`Some(vec![])`, or `None`) to represent the same thing.
* Send `vec![]` when creating the proposal in ic-admin
* A minor change to stop truncating `wasm_module` and `arg` within the governance crate, since the API type conversion already avoid …

feat(nns): Use `Some(vec![])` to represent empty args and disallow `None`

---

Cargo.lock
rs/nns/governance/api/BUILD.bazel
rs/nns/governance/api/Cargo.toml
rs/nns/governance/api/src/proposal_helpers.rs
rs/registry/admin/src/main.rs

Currently, the ic-admin prints the entire WASM when submitting the `InstallCode` proposal. We want to only print hashes.
When printing `InstallCode` proposals, we convert it into the "response" API type which contains only hashes.
Ideally, we'd like to implement custom `Debug` trait. However, currently it's impossible to do so while the proposal API type is still `prost:message` which already derives `Debug` trait.

feat(ic-admin): Print hashes rather than entire blobs when submitting InstallCode proposals

---

rs/nns/governance/src/lib.rs
rs/nns/governance/src/proposals/install_code.rs
rs/nns/governance/src/proposals/stop_or_start_canister.rs
rs/nns/governance/src/proposals/update_canister_settings.rs

The canister management topic split, as well as the new `UpdateCanisterSettings` proposal type is hidden behind the flag `enable_new_canister_management_topics` while they were under development. We want to enable them as the development is complete.
Flip the `enable_new_canister_management_topics` to true

feat(nns): Enable new canister management topics

---

Cargo.lock
rs/nns/governance/api/src/lib.rs
rs/nns/governance/api/src/test_api.rs
rs/nns/governance/canister/canister.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/integration_tests/src/governance_time_warp.rs
rs/nns/integration_tests/src/wait_for_quiet.rs
rs/nns/test_utils/BUILD.bazel
rs/nns/test_utils/Cargo.toml
rs/nns/test_utils/src/itest_helpers.rs

Create a copy of TimeWarp in the api crate, so that we can remove another dependency on the nns governance crate.

refactor(nns): Put TimeWarp in API crate to remove dependency

---

rs/sns/cli/src/deploy.rs
rs/sns/cli/src/init_config_file.rs
rs/sns/cli/src/init_config_file/friendly.rs
rs/sns/cli/src/lib.rs
rs/sns/cli/src/main.rs
rs/sns/cli/src/neuron_id_to_candid_subaccount.rs
rs/sns/cli/src/prepare_canisters.rs
rs/sns/cli/src/propose.rs

It is generally not a very good practice to perform an `.unwrap()` that might plausibly fail, outside of tests. Instead, it is better to return an error. Even in the `main` function, you can return a `Result` instead of using `.unwrap()` or `exit(1)` (and returning an `Err` from the main function will automatically set a non-zero exit code). Using `exit(1)` is particularly dangerous as you may forget to call it, or forget to use `eprintln!` instead of `println!`, in both cases doing something somewhat unexpected that the compiler will not warn you about.
Convert all the sns-cli endpoints to return an `anyhow::Result` instead of `()`. This enables them to return errors instead of panicking.
Using anyhow makes some of our code a bit more concise as well. For example, compare the original: …

refactor(sns-cli): Use anyhow

---

Cargo.lock
Cargo.toml
rs/nervous_system/agent/BUILD.bazel
rs/nervous_system/agent/Cargo.toml
rs/nervous_system/agent/src/lib.rs
rs/nervous_system/agent/src/nns/mod.rs
rs/nervous_system/agent/src/nns/sns_wasm.rs
rs/nervous_system/tools/sync-with-released-nevous-system-wasms/BUILD.bazel
rs/nervous_system/tools/sync-with-released-nevous-system-wasms/Cargo.toml
rs/nervous_system/tools/sync-with-released-nevous-system-wasms/src/main.rs

I thought it would make sense to have a crate where we would put various helper functions for interaction with SNSes and the NNS. Right now, the only rust helper functions I'm aware of are in some in `//rs/nervous_system/tools/sync-with-released-nevous-system-wasms` for interacting with SNS-W, so I moved just those for now. There are also some that were developed for use in system tests, but they are not trivial to extract so I haven't yet. 
[Next PR →](https://github.com/dfinity/ic/pull/1091)

refactor(nervous_system): create ic-nervous-system-agent crate for interacting with the NNS and SNSes

---

rs/bitcoin/ckbtc/mainnet/minter_upgrade_2024_08_23.md

XC-177: NNS proposals to upgrade the ckBTC minter to the latest version to fix a security issue in previous versions of ic-cdk.

chore: NNS proposal to upgrade ckBTC minter

---

rs/cross-chain/proposal-cli/templates/install.md
rs/cross-chain/proposal-cli/templates/submit_with_ic_admin.shx
rs/cross-chain/proposal-cli/templates/upgrade.md

(XC-173): Small improvement upon #1007 in the generated submission script `submit.sh` that also ensures there is no remaining `TODO` in the summary file before calling `ic-admin`.

feat(proposal-cli): Detect TODOs in summary file

---

rs/http_endpoints/public/src/call/ingress_watcher.rs

Currently, an [error](https://github.com/dfinity/ic/blob/26d5f9d0bdca0a817c236134dc9c7317b32c69a5/rs/http_endpoints/public/src/call/ingress_watcher.rs#L250) is logged if the ingress watcher is cancelled, but in production the cancellation token is never used (since a [fresh](https://github.com/dfinity/ic/blob/26d5f9d0bdca0a817c236134dc9c7317b32c69a5/rs/http_endpoints/public/src/lib.rs#L344) one is created when starting the ingress watcher and it is not stored anywhere to be cancelled later), but the cancellation token is cancelled upon [drop](https://github.com/dfinity/ic/blob/26d5f9d0bdca0a817c236134dc9c7317b32c69a5/rs/state_machine_tests/src/lib.rs#L1486) in StateMachine tests resulting in errors being logged. Hence, this PR updates the log level of ingress watcher cancellation from …

chore: update ingress watcher cancellation log level

---

rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2024_08_23.md
rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2024_08_23.md
rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2024_08_26.md
rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2024_08_23.md
rs/cross-chain/proposal-cli/src/canister/mod.rs

([XC-148](https://dfinity.atlassian.net/browse/XC-148)): NNS proposals to upgrade the ckBTC ledger suite (ledger, index and archive canisters) to `3d0b3f10417fc6708e8b5d844a0bac5e86f3e17d` to add support for the [ICRC-21: Canister Call Consent Messages](https://github.com/dfinity/wg-identity-authentication/blob/fd846030109710cab67d9381485a73db424f2b07/topics/ICRC-21/icrc_21_consent_msg.md) standard. 
[XC-148]: https://dfinity.atlassian.net/browse/XC-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ckbtc): NNS proposals to upgrade ckBTC ledger suite to add support for ICRC-21

---

.github/workflows/test-namespace-darwin.yaml

We need to add a trigger on merge queue to make this a required check.

chore(IDX): trigger Apple Silicon jobs on merge queue

---

.github/workflows/test-namespace-darwin.yaml

This ports the `dev-gh-*` trick (allowing developers to trigger CI jobs on `push:` outside of `master`) to the Apple Silicon/namespace build.

feat(IDX): use dev-gh- for aarch64 darwin

---

rs/nns/sns-wasm/tests/add_wasm.rs

This PR ensures that we don't fail the smoke test in the precondition of `test_metadata_migration` as soon as the Root WASM metadata changes.

test(nns): Make `test_metadata_migration` less fragile

---

testnet/tools/nns-tools/lib/canister_wasms.sh
testnet/tools/nns-tools/lib/proposals.sh
testnet/tools/nns-tools/submit-mainnet-publish-sns-wasm-proposal.sh

Fixing some minor problems with the NNS/SNS release scripts:
* `assert_that_a_prebuilt_sns_wasm_is_available` should be called when publishing SNS canisters, not for upgrading NNS canisters.
* Fix the `HUMANIZED_CANISTER_TYPE` regex capture as the title is changed
* Add regex capture for `PROPOSAL_ID` after sending an SNS publish proposal

fix(release): Fix some minor issues with NNS release scripts

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml
.github/workflows/test-namespace-darwin.yaml

Now that we are using two macos runners (old intel for releases and newer apple silicon for CI runs) it's helpful to standardize their names. Eventually we'd like to move completely to Apple Silicon runners and can then remove the specification once old Intel runners are deprecated.

chore(IDX): rename macos runners for clarity

---

rs/replicated_state/src/canister_state/system_state.rs
rs/state_manager/src/checkpoint.rs

[MR-572] Bump `state_manager_checkpoint_soft_invariant_broken` critical error counter if `SystemState::check_invariants()` fails during checkpoint loading.
[MR-572]: https://dfinity.atlassian.net/browse/MR-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [MR-572] Check `SystemState` invariants on checkpoint loading

---

.github/workflows/team-channels.json

Most members of the NNS team do not consider these notifications to be valuable. For those who actually do want to see these notifications, that is what the #eng-nns-prs channel is for.

chore(nns): Send automatic GitHub Pull Request notifications to #eng-nns-prs.

---

rs/nns/integration_tests/BUILD.bazel

This PR makes the comment above `upgrade_canisters_with_golden_nns_state` less misleading.

chore: Edit comment for upgrade_canisters_with_golden_nns_state

---

rs/sns/governance/canister/canister.rs
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/types.rs
rs/sns/governance/tests/governance.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/tests/swap.rs

We deprecated the `NeuronParameters` struct and the field it was used in, but still have code in SNS governance for handling that field. It can safely be removed now that swap is upgraded.
Remove support for it in SNS Governance
[Previous PR](https://github.com/dfinity/ic/pull/870)

refactor(nervous_system): Remove support for NeuronParameters

---

Cargo.lock
rs/sns/init/src/lib.rs
rs/sns/integration_tests/src/root.rs
rs/sns/root/BUILD.bazel
rs/sns/root/Cargo.toml
rs/sns/root/canister/canister.rs
rs/sns/root/canister/root.did
rs/sns/root/proto/ic_sns_root/pb/v1/root.proto
rs/sns/root/src/gen/ic_sns_root.pb.v1.rs
rs/sns/root/src/lib.rs

This reverts commit 0aa15a5bec268e817c45b369bd7c33c708ce8710. (except it doesn't undo the changes to Cargo.lock)
Now that the change with the migration has been released, the code is no longer necessary and can be deleted

chore(sns): Remove migration code for setting SNS memory limits

---

Cargo.lock
Cargo.toml
rs/registry/canister/BUILD.bazel
rs/registry/canister/Cargo.toml
rs/registry/canister/src/get_node_providers_monthly_xdr_rewards.rs
rs/registry/canister/src/mutations/node_management/common.rs
rs/registry/node_provider_rewards/BUILD.bazel
rs/registry/node_provider_rewards/Cargo.toml
rs/registry/node_provider_rewards/src/lib.rs

This allows the sharing of the reward calculation function with other tools, so that new tools can be made available to assist node providers.

refactor(registry): Extract calculation function for node provider rewards

---

rs/nns/governance/src/governance.rs

This PR moves the obsolete NNS function `UpdateAllowedPrincipals` to the list of obsolete functions.

chore(nns): Remove obsolete proposal type `UpdateAllowedPrincipals` from NNS Governance

---

rs/tests/driver/src/util.rs

We see some nightly benchmarks failing due to the test agent being unable to make TCP handshakes due to hitting the replica firewall limit. This change makes the test agent to submit requests with H/2 to multiplex the requests, meaning 1 TCP connection is enough per replica.

fix: Make the transport implementation used by the test agent to use HTTP/2

---

rs/state_machine_tests/src/lib.rs

This PR makes the http endpoints in StateMachine test registry distinct so that they satisfy the corresponding registry variant.

chore: make http endpoints in SM test registry distinct

---

rs/pocket_ic_server/tests/test.rs

This PR attempts to fix PocketIC test flakiness (bazel target `//rs/pocket-ic-server:test`) due to PocketIC server not starting within 5 seconds by removing that requirement which is not needed in a bazel test which has its own timeout.

chore: attempt to fix PocketIC test flakiness

---

rs/embedders/src/wasm_utils/validation.rs
rs/embedders/tests/validation.rs
rs/interfaces/src/execution_environment/errors.rs
rs/types/wasm_types/src/errors.rs
rs/types/wasm_types/src/lib.rs

Add links to the Execution Errors reference page for all user errors
that can occur during smart contract validation.
Part of https://dfinity.atlassian.net/browse/RUN-931

feat(RUN-931): Add doc links to Validation Errors

---

.github/workflows-source/ci-main.yml
.github/workflows-source/ci-pr-only.yml
.github/workflows-source/release-testing.yml
.github/workflows-source/schedule-daily.yml
.github/workflows-source/schedule-hourly.yml
.github/workflows/ci-main.yml
.github/workflows/ci-pr-only.yml
.github/workflows/release-testing.yml
.github/workflows/schedule-daily.yml
.github/workflows/schedule-hourly.yml

This is a first step to security hardening our CI by only giving jobs access to the secrets they need instead of defaulting to all. Next steps will be:
- move to environment secrets
- reduce the need for credentials in CI

refactor(IDX): only give certain jobs access to secrets

---

WORKSPACE.bazel

This bumps `rules_haskell` to a version that officially supports Bazel versions past 6.5.0.

chore(IDX): bump rules_haskell

---

rs/consensus/src/certification/certifier.rs
rs/consensus/src/consensus/catchup_package_maker.rs
rs/consensus/src/consensus/random_beacon_maker.rs
rs/consensus/src/consensus/random_tape_maker.rs
rs/consensus/src/consensus/share_aggregator.rs
rs/consensus/src/consensus/validator.rs
rs/consensus/utils/src/lib.rs
rs/consensus/utils/src/membership.rs
rs/replay/src/validator.rs

NiDKG transcripts may be fairly large (0.4 ~ 0.9 MB on NNS). Currently they are cloned twice whenever we create/verify/aggregate a BLS signature share (once to check committee membership and once to get the DKG id). 
We don't actually need the full transcripts to perform these operations, and can avoid cloning them by extracting only the necessary transcript data (NiDkgId, committee, threshold).

chore: Avoid cloning NiDKG transcripts

---

rs/consensus/src/consensus/validator.rs
rs/consensus/src/idkg/payload_builder.rs
rs/consensus/src/idkg/payload_builder/errors.rs

Additionally remove two other lints that were ignored for no reason

chore: CON-1085 Remove allow `result_large_err` clippy lint

---

packages/pocket-ic/src/lib.rs
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/main.rs
rs/pocket_ic_server/tests/spec_test.rs
rs/pocket_ic_server/tests/test.rs

This PR drops the ready file from the PocketIC server.
Originally, the ready file was added to the PocketIC server for the sake of synchronization (or locking) - we want to have only one test in a cargo test suite start the PocketIC server and thus the individual tests need to agree who starts that server and what the port is:
- the port file is written atomically by the first test that manages to write that file atomically and that test starts the server and writes the port to the port file and afterwards creates the ready file;
- the other tests then poll for the ready file to exist and once it exists, they all know that they can read the port from the port file.
If the other tests attempted to read from the port file without knowing that it has been fully written, then we could get …

feat(PocketIC): drop ready file in PocketIC server

---

rs/nns/cmc/src/lib.rs
rs/nns/integration_tests/src/cycles_minting_canister.rs
rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
rs/nns/test_utils/src/common.rs
rs/nns/test_utils/src/state_test_helpers.rs
testnet/tools/nns-tools/README.md

The cycles ledger canister id constant is defined in a different way than other NNS canister ids.
Use the constant already defined in ic_nns_constants.

chore(cmc): Use the CYCLES_LEDGER_CANISTER_ID constant in ic_nns_constants

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/api/src/proposal_helpers.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/src/governance.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/tests/governance.rs

The API layer should disallow proposals with deprecated types to be created. It was already impossible to create `OpenSnsTokenSwap` or `SetSnsTokenSwapOpenTimeWindow` proposals, while `SetDefaultFollowees` is no longer needed as we are actually trying to reset the effect of the previous default following (https://forum.dfinity.org/t/periodic-confirmation-design/34215)
* Remove variants of the action types from the API request type of the proposal action
* Fail validation for `SetDefaultFolllowees`

chore(nns): Disallow deprecated proposal types at the API layer

---

rs/ethereum/cketh/minter/src/main.rs

Ensure that the HTTP response containing the ckETH minter logs (e.g. https://sv3dd-oaaaa-aaaar-qacoa-cai.raw.icp0.io/logs?sort=desc) is at most 2MB. Otherwise, the logs cannot be retrieved as `Response size exceeds limit`. This is due to a recent change (proposal [122354](https://dashboard.internetcomputer.org/proposal/122354)) in the fiduciary subnet (`pzp6e-ekpqk-3c5x7-2h6so-njoeq-mt45d-h3h6c-q3mxf-vpeq5-fk5o7-yae`), where the various limits used (including the maximum response limit) were re-aligned to that of other subnets (excluding the NNS).

fix(cketh): Trim logs to 2 MB

---

WORKSPACE.bazel

The image doesn't seem to be used. It was once introduced for integration tests and then left unused after test refactorings.

chore(IDX): remove nns-dapp-specs image

---

rs/nns/governance/canister/canister.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/migrations.rs
rs/nns/governance/src/proposal_data_neurons_fund_migration.rs
rs/nns/integration_tests/src/hotkeys_migration_test.rs

We have switched from the `hotkey_principal` field to a field named `nns_neuron_controller` in the type `NeuronsFundNeuronPortion`. This is because the type `nns_neuron_controller` more clearly explains the semantics of the type than `hotkey_principal`. However, already-existing `ProposalData`s indirectly contain `NeuronsFundNeuronPortion`s which have `None` for the new field.
I've implemented a migration for the `NeuronsFundNeuronPortion`s that are transitively stored in `ProposalData` to use this new field. The migration lives in `pre_upgrade` and iterates over the stored `ProposalData`s, and sets their `neurons_fund_data` field to a value that contains the migrated state. 
< [Previous PR](https://github.com/dfinity/ic/pull/1171) |

chore(nns): NeuronsFundAuditInfo migration

---

toolchains/sysimage/build_ext4_image.py

NODE-1454
We'd previously run `rm` for each nested file in directories. When a directory contains many files, this gets slow. By running `rm` only once, we can save 10-20s per build.
The output should still be the same, I verified it by taking the checksum of the generated images.

perf: Optimize strip_files function

---

rs/drun/src/main.rs

Enable the canister snapshot feature in `drun` for Motoko tests.

chore(drun): Enable canister snapshots

---

rs/embedders/src/wasmtime_embedder/system_api.rs
rs/execution_environment/src/execution/response/tests.rs
rs/execution_environment/src/query_handler/query_cache/tests.rs
rs/system_api/src/lib.rs
rs/system_api/src/request_in_prep.rs

Add links to the execution errors reference page for the contract violation errors. The errors related to the performance counter API and best-effort messaging aren't handled because they haven't been added to the reference page yet.

feat(RUN-931): Add Doc Links to Contract Violation Errors

---

.github/workflows-source/ci-main.yml
.github/workflows-source/schedule-daily.yml
.github/workflows-source/schedule-hourly.yml
.github/workflows/ci-main.yml
.github/workflows/schedule-daily.yml
.github/workflows/schedule-hourly.yml
gitlab-ci/src/bazel-ci/main.sh

As a follow-up from https://github.com/dfinity/ic/pull/1244 we can remove AWS creds where they are not needed.

chore(IDX): remove AWS creds where not needed

---

bin/afl_wrapper.sh

On latest master, some fuzzers have trouble coming up within the 5s timeout. This PR bumps the default maximum timeout from 5s to 20s. Note, the timeout for the fuzzer is still auto calculated but 20s is the ceiling.

chore(fuzzing): increase maximum timeout for AFL fuzzers from 5s to 20s

---

ic-os/components/misc/fetch-property.sh
ic-os/components/setupos.bzl

https://github.com/dfinity/ic/pull/1202 missed an import in `fetch-property.sh`, which fails when deploying HostOS. This was picked up by nightly bare metal testing.

fix: Fix missing log function

---

rs/tests/src/rosetta_tests/setup.rs

This changes the rosetta image lookup logic slightly to avoid a double slash in the path name. While this should not cause issues in general (on most OSs `/foo//bar` is similar to `/foo/bar`) it's a bit confusing.

fix(IDX): remove double '/' in rosetta img path

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
bazel/external_crates.bzl
packages/ic-signature-verification/Cargo.toml
rs/pocket_ic_server/Cargo.toml

The external ic-certification package was used by multiple dependencies, but with slightly different versions. This PR makes sure only one version is used. To help solve the problem, the ic-http-proxy dependency is also pinned to a more recent version.
Note that the external ic-certification is a different package than the one internal in rs/certification subdir.

fix: use only one version of ic-certification

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
Cargo.toml
bazel/external_crates.bzl

Resolves [GHSA-vr26-jcq5-fjj8](https://github.com/quinn-rs/quinn/security/advisories/GHSA-vr26-jcq5-fjj8).

chore: update quinn 

---

rs/nns/gtc/src/lib.rs
rs/nns/gtc/tests/test.rs
rs/nns/test_utils/BUILD.bazel
rs/nns/test_utils/src/common.rs
rs/nns/test_utils/src/gtc_helpers.rs
rs/nns/test_utils/src/lib.rs

This PR factors out test-only code from the GTC production crate into rs/nns/test_utils

chore: Move GenesisTokenCanisterInitPayloadBuilder to rs/nns/test_utils

---

requirements.in

By removing the specific pins from the version (changing `==` to `>=`) we allow for newer versions to get pulled in if they are available. However, after running `bazel run //:python-requirements.update` it appears that they are already at their most recent version (or restricted by other dependencies).

chore(IDX): unpin python dependencies

---

rs/tests/driver/src/driver/prometheus_vm.rs
rs/tests/driver/src/driver/resource.rs

This keeps the UVM and PrometheusVM images in sync with [the latest Farm commit](https://github.com/dfinity-lab/farm/commit/efdb2b6e273eb5933ceea68d1b0322e809f27776).

chore: upgrade to latest Universal- and Prometheus-VM images

---

rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
rs/protobuf/def/state/canister_snapshot_bits/v1/canister_snapshot_bits.proto
rs/protobuf/src/gen/state/state.canister_snapshot_bits.v1.rs
rs/replicated_state/src/canister_snapshots.rs
rs/replicated_state/src/canister_state/execution_state.rs
rs/state_layout/src/state_layout.rs
rs/state_layout/src/state_layout/tests.rs
rs/state_manager/src/checkpoint.rs
rs/state_manager/src/tip.rs

Currently, the canister snapshots do not cover the state of Wasm global variables, such that in realistic canister programs with mutable global variables, the state is not properly recovered when a snapshot is loaded.
This fix adds the Wasm globals to the snapshot state, similar to the execution state. (Side note: All Wasm variables are exported by the Wasm instrumentation.)

fix(execution): Canister snapshots should include Wasm globals

---

rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/execution_environment.rs
rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs

This PR fixes the logic of computing the subnet's available memory after some snapshot operations. More specifically, there were some cases where the accounting was incorrect:
1. When a snapshot creation would fail, we wouldn't add back the available memory deducted previously.
2. When deleting a snapshot (through `delete_canister_snapshot`) or replacing an existing snapshot, we wouldn't add back the memory taken by this snapshot.
These bugs were low impact as the calculation of available memory happens fresh at the beginning of every execution round, i.e. the above would only temporarily make the available memory look less than it should be within the same execution round that the snapshot operation happened. However, for the sake of correctness, it's best to fix these cases.
The changes …

fix(snapshots): Compute the correct subnet available memory after snapshot operations

---

.github/workflows-source/ci-pr-only.yml
.github/workflows/ci-pr-only.yml
ci/bazel-scripts/main.sh
ci/scripts/run-build-ic.sh

To remove complex CI logic. we will remove the flag `S3_UPLOAD`, since it is interchangeable with `RUN_ALL_BAZEL_TARGETS` (both run all targets and upload to s3). Added a deprecation message as well.

refactor(IDX): update custom ci logic

---

testnet/tools/nns-tools/lib/proposals.sh

As pointed out by Georgi, [proposals to add new SNS versions use `wasm` instead of `wasm_module`](https://github.com/dfinity/ic/blob/c5545625c47f52d03fe022befe0bf85d24683ebd/rs/nns/sns-wasm/canister/sns-wasm.did#L1-L2), but the template for the proposals to add SNS versions refers to a `wasm_module` field

fix(nns-tools): typo correction: wasm_module -> wasm

---

testnet/tools/nns-tools/README.md
testnet/tools/nns-tools/lib/proposals.sh
testnet/tools/nns-tools/list-new-commits.sh

1. README:
1. Refactored instructions for how to do upgrade test. One additional piece of information: it takes about 5 minutes to run. (If it takes much longer, operator should start start suspecting that something is wrong, and begin investigating.)
2. `pkcs11-tool --login --test` (not just `--list-slots`) is a stronger way to test HSM key, because it prompts for PIN, not just that you can talk to the hardware.
3. Removed some recently obsolete information.
2. Generating NNS proposal text: corrections in the section about argument verification.

docs(nns): Small corrections in nns-tools.

---

rs/tests/run-p8s.nix

This upgrades nixpkgs used in the `run-p8s.sh` script to the same [version as used by the prometheus-vm](https://github.com/dfinity-lab/farm/blob/master/nix/sources.json#L9).

chore: upgrade nixpkgs in run-p8s.nix to match the version used in the prometheus-vm

---

rs/query_stats/src/payload_builder.rs

The log message "Current stats are uninitalized. This warning should go away after some minutes" appears often in PocketIC logs. After some debugging, it turned out that this is because the PocketIC instance is not processing any query calls, but the log message indicates that it should just go away without hinting at what needs to happen. Hence, this PR extends the log message to be less confusing in PocketIC (and also make sense in production).

chore: update query stats log message to be less confusing in PocketIC

---

rs/registry/canister/src/get_node_providers_monthly_xdr_rewards.rs
rs/registry/canister/src/invariants/endpoint.rs

There are 2 instances where clippy should complain when `dfn_core::println` is no longer used but it didn't get caught by CI. We need to figure why CI didn't catch it, but for now, we fix them first.

chore(registry): Remove dfn_core::println in 2 places where they are no longer used

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.json.lock
Cargo.toml
bazel/external_crates.bzl

Currently, the `slog` dependency has two enabled features `release_max_level_debug` and `release_max_level_trace` which are contradictory and `release_max_level_debug` takes [precedence](https://github.com/slog-rs/slog/blob/master/src/lib.rs#L4039). Hence, this PR removes `release_max_level_debug` so that `release_max_level_trace` is effective.

fix(deps): drop release_max_level_debug from slog features

---

rs/config/src/embedders.rs
rs/embedders/src/wasm_executor.rs
rs/embedders/src/wasmtime_embedder.rs
rs/embedders/src/wasmtime_embedder/wasmtime_embedder_tests.rs
rs/embedders/tests/wasmtime_random_memory_writes.rs
rs/system_api/src/lib.rs
rs/system_api/tests/common/mod.rs
rs/system_api/tests/system_api.rs
rs/test_utilities/embedders/src/lib.rs

Add a feature flag to enable canister backtraces. Follow up PRs will use this flag and actually collect the backtraces.

feat(EXC-1715): Canister Backtrace Flag

---

testnet/tools/nns-tools/is-commit-released.sh

Simply pass it
1. canister name
2. (query) commit ID
It then asks the canister what commit it's on, and then asks git whether the query commit is an ancestor of the commit the canister is running.
This only works for NNS. In the case of SNS, this could answer a couple variations of the same request:
1. If an SNS had the most recent available version, would the query commit be included?
2. Which SNSs do not yet have the query commit?
Perhaps, we can (in a future iteration), we can make this even easier by making canister name optional. If omitted, this script could scan all NNS canisters, and print the status of each.
I would also like it if you could pass a PR number, and have it figure out the merge commit. One way to do this:
```
git log --grep ' (#1234)$' --pretty=format:"%H" master …
```

feat(nns): Added is-commit-released.sh to nns-tools.

---

ic-os/setupos/data/deployment.json.template
rs/ic_os/setupos-inject-configuration/src/main.rs
rs/ic_os/utils/src/deployment.rs
rs/tests/driver/src/driver/bootstrap.rs

NODE-1463
cpu deployment field has been implicitly used by setupos-inject-config and now it is now explicitly defined in deployment.json. Tests added for backwards compatibility (and once we have the HostOS upgrade to/from version handles, we can be super-duper confident in the backwards compatibility!)
This explicit definition will help with the larger config revamp, as in the new redesign, the cpu mode is explicitly defined in the new IcConfig object
Hourly pipeline succeeded: https://github.com/dfinity/ic/actions/runs/10599061627

feat(NODE-1463): Add cpu field to deployment.json

---

testnet/tools/nns-tools/lib/proposals.sh

It was an intentional change to use `arg_hash` instead of `arg_hex` for verifying `InstallCode` proposal. Previous change was accidentally reverted and now we revert back.

release(nns): Change to nns release script to verify arg_hash

---

rs/nervous_system/common/src/lib.rs
rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/neurons_fund.rs
rs/nns/governance/src/neurons_fund/neurons_fund_anonymization_tests.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/tests/interleaving_tests.rs
rs/sns/audit/src/lib.rs
rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/src/types.rs
rs/sns/swap/tests/common/mod.rs
rs/sns/swap/tests/swap.rs

We deprecated all fields named hotkey_principal, but still set them (even in cases where the field is optional)
Remove it when possible. However It is difficult to remove occurrences of `hotkey_principal` fields with type `String` (rather than `Option<String>). For these cases, we don’t need to fully remove the field, let’s just set it to String::new() at all sites where it is set, and make sure we don’t use that value anywhere.
[← Previous PR](https://github.com/dfinity/ic/pull/1286)

refactor(nervous_system): Remove most usages of hotkey_principal

---

rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
rs/sns/swap/protobuf_generator/src/lib.rs
rs/sns/swap/src/clients.rs
rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/src/types.rs
rs/sns/swap/tests/common/doubles.rs
rs/sns/swap/tests/swap.rs

This will allow us to remove the `NeuronParameters` field from Governance. This extra rigamarole is required because the field is not optional, so we need to make sure the callee is not expecting it before the caller stops providing it in the request.
Once #1297 is released, this PR should be reverted. With that in mind, I've implemented it optimizing for revert-ability. This means avoiding doing refactors that would potentially be painful to revert, if the code continued to change between now and then.
[Next PR →](https://github.com/dfinity/ic/pull/1297)

chore(sns): Duplicate ClaimSwapNeuronsRequest into Swap, so the version in SNS Governance can be changed independently

---

.github/workflows-source/schedule-hourly.yml
.github/workflows/schedule-hourly.yml

Only run `//rs/...` targets to omit `//publish/..` targets. `//rs/...` covers all system tests that have hourly system test tag.

fix(IDX): hourly schedule BAZEL_TARGET

---

rs/replicated_state/src/canister_state/queues.rs
rs/replicated_state/src/canister_state/queues/input_schedule.rs
rs/replicated_state/src/canister_state/queues/message_pool.rs
rs/replicated_state/src/canister_state/queues/queue.rs

Have it compare everything except message payloads.

refactor: Redo the ValidateEq annotations for CanisterQueues

---

rs/tests/driver/src/driver/farm.rs
rs/tests/driver/src/driver/group.rs
rs/tests/driver/src/driver/test_env_api.rs
rs/tests/driver/src/driver/test_setup.rs
rs/tests/ict/cmd/testnetCreateCmd.go
rs/tests/src/mainnet_tests/mainnet_api.rs

This adds support for deploying eternally-lived testnets using the system-testing framework, i.e. testnets that don't automatically get garbage collected.
Static testnets are EOL, no longer owned and maintained by anyone and currently broken. However there are still two static testnets left:
* `exchanges`: used by the FI team and external parties like Coinbase to test the Rosetta API.
* `bitcoin`: used to test bitcoin support. This is a static testnet since it needs to stay alive since it contains a big state that takes a long time (>1d) to setup.
This means the FI team and the Bitcoin team won't be able to test their code. So we need a replacement. The way forward for testnets is to use system-test-based testnets that are deployed via Farm (or via k8s in the future).
However …

feat(IDX): support eternal system-test-based testnets

---

.github/workflows/test-namespace-darwin.yaml

We can remove this as `nsc` is now installed by default on the runners.

chore(IDX): remove install nsc step

---

rs/replicated_state/src/canister_state/queues/message_pool.rs
rs/replicated_state/src/canister_state/queues/message_pool/tests.rs

[MR-550]: There's a cleaner way of representing "timed out" or "shed" reject responses, so there is need anymore for `ResponsePlaceholder`.
[MR-550]: https://dfinity.atlassian.net/browse/MR-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [MR-550] Drop `ResponsePlaceholder`

---

rs/replicated_state/src/canister_state/queues/input_schedule.rs

Trying too hard to avoid panics resulted in a panic.
One of the invariants of `InputSchedule` is that the queues and the `scheduled_senders` map stay in sync: a canister is in one of the queues iff it's in `scheduled_senders`. The code originally had an `assert` around `scheduled_senders.remove()`, which I accidentally turned into a `debug_assert`. Meaning that the code would run perfectly fine when tested; but would break in release mode.
Also, the underlying assumption for making this a soft invariant was that worst-case we would end up with a canister that was never scheduled or scheduled too often; maybe with a replica diverging after starting from a checkpoint.
In reality, because we rely on different sources for `has_input()` and `pop_input()`, something that only works if …

fix: Fix brown paper bag bug in `InputSchedule`

---

rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/tests/governance.rs

The field is deprecated and no longer supported. This change is safe because neuron_parameters was already not supported by `Governance`, this just removes the field entirely from the request it expects. 
[← Previous PR](https://github.com/dfinity/ic/pull/1295)

chore(sns): Remove neuron_parameters from ClaimSwapNeuronsRequest on SNS Governance's side

---

rs/registry/admin/src/main.rs

Now that we have a few proposals using `InstallCode` proposal type already, we can change ic-admin to use them by default.
* Switch the default by defining an opposite enum
* Remove the legacy option for stopping/starting since those proposals are rare.

chore(ic-admin): Use InstallCode by default for canister upgrades, and always use explicit action types for stopping/starting

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/proposals/create_service_nervous_system.rs
rs/nns/governance/tests/governance.rs
rs/sns/cli/src/lib.rs

This PR refactors the code in NNS Governance responsible for executing `CreateServiceNervousSystem` proposals s.t. it no longer requires the internal type `ExecutedCreateServiceNervousSystemProposal`. This type was intended to be internal but has become public for CLI tools to validate instances of this proposal type, which adds an undesirable crate-level dependency between, e.g., `//rs/nns/governance` and `//rs/sns/init`.

refactor(nns): Eliminate `ExecutedCreateServiceNervousSystemProposal`

---

rs/nervous_system/integration_tests/tests/constraints_dependencies.rs
rs/sns/init/src/lib.rs

This PR lifts an overly strict requirement due to which some SNS configurations were deemed invalid if it was possible to exceed the 100K SNS neurons limit for swap participants in the worst case. 
[Recently](https://github.com/dfinity/ic/pull/924), the maximum number of swap participants has started to be enforced during swap participation, so checking the condition upfront is no longer needed for security, and so we lift it to allow for more SNS configurations.

feat(sns): Postpone enforcing the 100K SNS neuron limit till swap begins

---

rs/nervous_system/common/src/ledger.rs
rs/nervous_system/common/src/tests.rs
rs/nns/governance/src/governance.rs

The logic and documentation around NNS neuron subaccount addresses are confusing.
* Update the link to dfinity_wallet to ic-js.
* Refactor the calculation logic for different neuron subaccounts to using the same function.
* Move the pointer to the ic-js link to a new test for the staking account.

refactor(nns): Some refactoring on how neuron subaccount addresses are calculated

---

rs/tests/consensus/utils/src/performance.rs

I'm using `replica_http_ingress_watcher_wait_for_certification_duration_seconds` metrics to compute, essentially doing the following query:
```
avg(delta(replica_http_ingress_watcher_wait_for_certification_duration_seconds_sum[15m]) / delta(replica_http_ingress_watcher_wait_for_certification_duration_seconds_count[15m]))
```
```
2024-09-05 15:44:34.488 INFO[uvms_logs_stream:StdOut] [uvm=test-driver] TEST_LOG: Task setup               PASSED  in 132.36s   -- Exited with code 0.
2024-09-05 15:44:34.488 INFO[uvms_logs_stream:StdOut] [uvm=test-driver] TEST_LOG: Task test_small_messages PASSED  in 103.57s
2024-09-05 15:44:34.488 INFO[uvms_logs_stream:StdOut] [uvm=test-driver] TEST_LOG:      Success rate: 100.0%
2024-09-05 15:44:34.488 INFO[uvms_logs_stream:StdOut] [uvm=test-driver] TEST_LOG: …
```

test(consensus): Output e2e latency in the consensus performance test

---

rs/execution_environment/src/metrics.rs
rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/scheduler_metrics.rs
rs/execution_environment/tests/canister_logging.rs

This PR improve canister log memory usage metric by using better buckets.
Originally this metric was using memory buckets for WASM memory which is too big (order of GB) when canister log current limit is 4 KiB.
EXC-1722

chore: improve canister log memory usage metric buckets

---

rs/nervous_system/clients/src/management_canister_client/tests.rs

The test is flaky (`bazel test --runs_per_test=1000 //rs/nervous_system/clients:clients_test --test_arg=test_limit_outstanding_calls` fails ~0.5% of the time). The test is depending on the thread waking up at the exact time, and that is probably not very accurate. Increasing the scale of the sleep duration seems to solve it (running 1000 times without failures)

fix(nns): Fix a flaky test by increasing the sleep duration

---

rs/state_manager/tests/state_manager.rs

This seems to be the state manager test that takes the longest, but it doesn't need to be this aggressive.

test: Less aggressive LSMT proptest

---

.github/workflows/release-testing.yml
.github/workflows/system-tests-k8s.yml
rs/tests/testing_verification/BUILD.bazel

We still rely on AWS in system tests on k8s. Adding it back for now. Removing nightly test on scheduled nightly to focus on system tests that are part of PR and hourly schedule.

fix(system-tests-k8s): aws variable

---

rs/tests/financial_integrations/rosetta/BUILD.bazel
rs/tests/src/rosetta_tests/tests/derive.rs
rs/tests/src/rosetta_tests/tests/list_known_neurons.rs
rs/tests/src/rosetta_tests/tests/list_neurons.rs
rs/tests/src/rosetta_tests/tests/make_transaction.rs
rs/tests/src/rosetta_tests/tests/network.rs
rs/tests/src/rosetta_tests/tests/neuron_disburse.rs
rs/tests/src/rosetta_tests/tests/neuron_dissolve.rs
rs/tests/src/rosetta_tests/tests/neuron_follow.rs
rs/tests/src/rosetta_tests/tests/neuron_hotkey.rs
rs/tests/src/rosetta_tests/tests/neuron_info.rs
rs/tests/src/rosetta_tests/tests/neuron_maturity.rs
rs/tests/src/rosetta_tests/tests/neuron_spawn.rs
rs/tests/src/rosetta_tests/tests/neuron_staking.rs
rs/tests/src/rosetta_tests/tests/neuron_voting.rs

Making UVM name shorter to overcome the issue of names being too long on k8s system tests where UVM name is concatenated from system test name and UVM name.
```
Invalid value: \"rosetta-neuron-hotkey-test-head-nns-szkv7-1-rosetta-neuron-hotkey\": must be no more than 63 characters", reason: "Invalid", code: 422
```

chore(system-tests-k8s): shorter VM name

---

rs/recovery/src/file_sync_helper.rs
rs/tests/consensus/BUILD.bazel
rs/tests/consensus/backup_manager_test.rs

The following changes have been made:
1. Increased the timeout for downloading binaries from 15s to 60s. Some binaries are quite large and under bad networking conditions 15s might not be enough. This should help with some test flakiness we've observed lately.
2. Removed the logic of downloading mainnet binaries from the `backup_manager_test` system test. The backup script [has its own logic](https://sourcegraph.com/github.com/dfinity/ic/-/blob/rs/backup/src/backup_helper.rs?L162-174) of downloading binaries when they are missing (together with some retry logic), so doing it explicitly in the system test is unnecessary and it's actually important to test that this functionality of the backup script works.
3. We are now passing `Logger` to `FileDownloader` utility, so we get some …

chore(ic-backup): Increase timeout for downloading binaries from 15s to 60s

---

rs/nns/governance/canister/canister.rs

We'd like to deprecate protobuf methods in the NNS Governance by ramping up the random failure gradually. Increase the failure rate from 10% to 30%.

chore(nns): Increase random error for protobuf methods to 30%

---

rs/nervous_system/neurons_fund/src/lib.rs
rs/nervous_system/neurons_fund/src/polynomial_matching_function_tests.rs
rs/nns/governance/src/governance/test_data.rs
rs/nns/governance/src/neurons_fund.rs
rs/nns/governance/src/neurons_fund/neurons_fund_anonymization_tests.rs
rs/nns/governance/tests/fixtures/mod.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/tests/interleaving_tests.rs
rs/sns/swap/tests/swap.rs

There are many logs that are helpful in mainnet that are creating too much noise in tests, causing in some cases the testing infrastructure to get overwhelmed and hang during cleanup.  
Additionally, removing the extra logs reduces the test run time from ~40s to  ~5s.

chore(nns): reduce logging in tests 

---

rs/ethereum/cketh/minter/src/eth_rpc.rs
rs/ethereum/cketh/minter/src/state.rs

([XC-190](https://dfinity.atlassian.net/browse/XC-190)): The error message in case the response size estimate of an HTTP outcall changed with release `35bfcad` (proposal [132222](https://dashboard.internetcomputer.org/proposal/132222)). This is used as an indicator in case the minter needs to retry an HTTPs outcalls but with a bigger estimate. Due to this change, this indicator was no longer working, which is fixed by this PR.
[XC-190]: https://dfinity.atlassian.net/browse/XC-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(cketh): Retry HTTPs outcalls

---

rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/test.rs

This PR supports IP addresses in frontend URLs to PocketIC HTTP gateway. They are being used in dfx by default and thus this PR makes sure that PocketIC is backward-compatible for dfx users.

fix(PocketIC): support IP addresses in frontend URLs to PocketIC HTTP gateway

---

rs/execution_environment/src/scheduler/scheduler_metrics.rs

Add a few more buckets for the "executable canisters" histogram to get better insights on subnets with high compute demand.

chore: Update granularity of executable canisters histogram

---

ic-os/components/hostos-scripts/misc/fetch-mgmt-mac.sh

This commit broke nested tests/hourly pipeline: https://github.com/dfinity/ic/commit/cb9249d5d22c84ad494a0b85a08c491b80137632
This PR fixes that. Tested on nested registration test
[NODE-1465](https://dfinity.atlassian.net/browse/NODE-1465)
[NODE-1465]: https://dfinity.atlassian.net/browse/NODE-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(NODE-1465): Update fetch-mgmt-mac

---

rs/boundary_node/ic_boundary/src/metrics.rs

**Rationale**:
With the introduction of the `/api/v3/call` (synchronous call), response latency between `ic-boundary` and `replica` can reach up to 10 seconds. To accurately capture and export Prometheus latency metrics, we need to extend the bucket range to accommodate this increased latency.

chore(boundary): increase the number of duration buckets in metrics

---

packages/pocket-ic/src/lib.rs

This PR drops the PocketIC library timeout of 10s when starting the PocketIC server. Given that other parts of a test might be slow, too, it is not clear why we'd impose a timeout on starting the PocketIC server. Moreover, we have seen this timeout causing flakiness in tests regularly.

fix(PocketIC): drop PocketIC library timeout

---

packages/icrc-ledger-types/src/icrc21/lib.rs
rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs

1. If no subaccount is set, display the effective subaccount when the anonymous principal is making the icrc21 call.

fix(ICRC-1 Ledger): add effective subaccount to ICRC-21

---

rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/test.rs

This PR adds a new endpoint `/_/dashboard` of the PocketIC HTTP gateway returning the dashboard of the underlying PocketIC instance or replica.
This way, the URL of the PocketIC HTTP gateway can be used to access the dashboard and no separate URL of the PocketIC instance (having a non-empty URL path of the form `/instances/<instance_id>`) or replica is needed.
On the other hand, the path `/_/dashboard` becomes reserved and cannot be used for frontend canister assets (note that paths with prefixes `/api/v2` and `/api/v3` are already reserved and thus this PR does not make a qualitative difference here).

feat(PocketIC): dashboard endpoint in PocketIC HTTP gateway

---

rs/pocket_ic_server/src/state_api/state.rs

This PR changes the log level of HTTP gateway termination from info to debug so that it doesn't appear in the console by default (analogously to the server termination which has been switched from into to debug in the past).

chore(PocketIC): make HTTP gateway termination into debug log

---

rs/ethereum/ledger-suite-orchestrator/src/scheduler/test_fixtures.rs
rs/ethereum/ledger-suite-orchestrator/src/state/mod.rs
rs/ethereum/ledger-suite-orchestrator/src/state/tests.rs

(XC-189): Fix a bug introduced in #1312 where a field stored in stable memory was renamed. The rename is kept transparent using `#[serde(rename)]` and test that ensures that changes in stable memory are backwards-compatible were fixed as well.

fix(ckerc20): bug in renaming field

---

rs/config/src/subnet_config.rs

Reducing the slice limit for `install_code` messages is now possible after the [update ](https://dashboard.internetcomputer.org/proposal/131699)to the DKG interval on the NNS subnet. Given the 1T limit for `install_code` messages on system subnets, a slice limit of 5B would mean at most 200 slices in the worst case, which is acceptable given the current DKG interval of 500 rounds.
This change brings even closer the configuration for normal messages (using a 2B slice limit) and `install_code` messages.

feat: Reduce slice limit for install_code messages in system subnets

---

rs/registry/admin/src/main.rs

Some users already use the `--use-explicit-action-type` when using ic-admin to create canister upgrade proposals. Avoid breaking them for now. 
The option isn't technically used. Ideally we want to have a boolean option default to true but can be set to false, but there seems to be no convenient way to do so with clap.

chore(ic-admin): Keep `--use-explicit-action-type` in ic-admin

---

rs/registry/canister/canister/canister.rs

In a nut shell, this adds a local `main` function that does the "real work" (including error handling). Whereas, operations that are common to all cases (error, or ok) are done directly in the body of get_changes_since.
These changes were originally part of #1206, but were spun out.
I recommend viewing this using side by side diff is recommended; unified is not so helpful. Also, I recommend enabling disregard whitespace changes.

refactor(registry): Refactor get_changes_since.

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/proposals/install_code.rs
rs/nns/governance/src/proposals/stop_or_start_canister.rs
rs/nns/governance/src/proposals/update_canister_settings.rs

The flag `enable_new_canister_management_topics` is already true on the mainnet. Clean up the code paths after replacing the function call with `true`.

chore(nns): Remove the flag to enable new topics

---

rs/execution_environment/benches/lib/src/common.rs
rs/execution_environment/benches/system_api/diff-old-vs-new.sh
rs/execution_environment/benches/system_api/execute_inspect_message.rs
rs/execution_environment/benches/system_api/execute_update.rs

Minor fixes around System API benchmarks:
* Updated repository
* Renamed some benchmarks
* Enabled best effort responses
* Updated `debug_print` expected instructions

chore: RUN-988: Fix System API benchmarks

---

rs/ethereum/cketh/minter/src/eth_rpc_client/providers.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
rs/ethereum/cketh/minter/tests/ckerc20.rs
rs/ethereum/cketh/minter/tests/cketh.rs
rs/ethereum/cketh/test_utils/src/flow.rs
rs/ethereum/cketh/test_utils/src/mock.rs
rs/ethereum/evm-rpc-client/src/tests.rs

Follow-up on #1412 to replace POKT network provider with [BlockPI](https://blockpi.io/).

fix(cketh): Replace provider POKT Network

---

Cargo.toml
rs/rosetta-api/Cargo.toml

This MR introduces the following chnages:
1. Move ICP Rosetta dependencies to the workspace file.

chore(ICP-Rosetta): move dependencies to workspace

---

rs/ethereum/cketh/minter/src/eth_rpc_client/providers.rs

This PR removes the `RpcService::Chain` variant (reflected in the EVM RPC Candid interface) due to ambiguity about which RPC provider is used to make the request.
Another option could be to always use a specific service such as [Public Node](https://www.publicnode.com/) for these RPC requests, although this would remain ambiguous and is only valid for some inputs compared to specifying, for instance, `#EthMainnet(#PublicNode)`. The current behavior is to use the RPC provider with the largest `provider_id` matching the provided `chain_id`.
Merges into the `evm-rpc-canister` branch.

candid(evm-rpc)!: remove `RpcService::Chain` variant

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/proposals/install_code.rs
rs/nns/governance/src/proposals/update_canister_settings.rs

All the proposal types that might be needed for recovering NNS Governance from excessive memory usage, should be allowed when memory usage is high.
* The `InstallCode` replaces `NnsCanisterUpgrade`, therefore it should be allowed.
* The `UpdateCanisterSettings` might be able to change canister settings such as `memory_allocation` and `wasm_memory_limit`
* The NNS Root is the controller of the NNS Governance, so hard-resetting root should be allowed, similar to `NnsRootUpgrade`
* For `InstallCode` and `UpdateCanisterSettings`, only the protocol canisters are allowed

feat(nns): Allow more proposal types when resources are low

---

ic-os/components/conformance_tests/defs.bzl
ic-os/defs.bzl

The current state triggers a rebuild of local base images, which are normally tagged as `manual`.

fix: Exempt local base targets from component tests

---

rs/replicated_state/BUILD.bazel
rs/replicated_state/Cargo.toml
rs/replicated_state/src/canister_state/queues.rs
rs/replicated_state/src/canister_state/queues/tests.rs

What we're actually interested in is that after a garbage collection, a `CanisterQueues` encodes to zero bytes. So check that instead of comparing with default.

fix: CanisterQueues: Check for zero-length encoding after GC

---

.github/scripts/determine-initial-guest-os-versions.py
.github/workflows-source/release-testing.yml
.github/workflows/release-testing.yml

This PR adds a backup option in case there are no viable subnet Git revisions or the rollout dashboard is down. Before this PR the job would fail and say that the matrix was invalid which results in a failed release cut as we can see [here](https://dfinity.slack.com/archives/C024WJPPX5W/p1726110654204759). 
There are some occasions when we expect this situation with the current code base:
1. There was no successful cuts for at least a week.
2. We didn't release because of the holidays (Like we do for Christmas) 
3. We had an urgent fix that was rolled out in a day and no new rollouts were dispatched when the release-testing flow was issued.
4. Rollout dashboard is malfunctioning.
Yet another set of concerns need resolving.  The prior version selection algorithm (in the case of using the …

fix: adding backup if there are no active rollouts from the rollout dashboard

---

.github/workflows-source/schedule-daily.yml
.github/workflows/schedule-daily.yml

Bump the FI nightly tests timeout to 12h. This matches the current longest timeout in the workflow (the rust benchmarks), and the actual duration is still below that of the benchmarks.

chore(ICRC_ledger): FI-1488: Bump FI nightly timeout

---

rs/messaging/src/message_routing.rs
rs/messaging/src/routing/stream_builder.rs
rs/messaging/src/routing/stream_builder/tests.rs
rs/messaging/src/routing/stream_handler.rs
rs/messaging/src/routing/stream_handler/tests.rs
rs/replicated_state/src/canister_state/queues.rs
rs/replicated_state/src/canister_state/queues/queue.rs
rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
rs/replicated_state/src/canister_state/tests.rs
rs/replicated_state/src/replicated_state.rs
rs/replicated_state/tests/replicated_state.rs

[MR-523]: The management canister does not make outgoing canister calls (not as itself, at least; it does do so on behalf of canisters, but those responses are routed back directly to the canisters themselves, not into the subnet input queues).
Return an error when a `Response` is about to be enqueued into the subnet input queues.
[MR-523]: https://dfinity.atlassian.net/browse/MR-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [MR-523] Don't allow responses in subnet input queues

---

bazel/conf/.bazelrc.build

The previous pattern did not match targets directly in the ic-os directory, only in its subdirectories.

fix: Enable sandboxless build strategy for all ic-os builds

---

rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/scheduler_metrics.rs

This PR introduces a scheduler metric to count the number of canisters actually executed in the past round.
This differs from the `scheduler_executable_canisters_per_round` metric, which shows the number of canisters that are eligible for execution (but may not be executed due to constraints such as round limits).

chore: add metric for executed canisters per round

---

Cargo.lock
rs/nervous_system/canisters/BUILD.bazel
rs/nervous_system/canisters/Cargo.toml
rs/nervous_system/canisters/src/ledger.rs
rs/nervous_system/common/BUILD.bazel
rs/nervous_system/common/Cargo.toml
rs/nervous_system/integration_tests/Cargo.toml
rs/nns/test_utils/src/sns_wasm.rs
rs/rust_canisters/dfn_candid/BUILD.bazel

In order to prepare to switch from dfn_core to ic_cdk, we need to use candid compatible methods.  This step temporarily makes more use of dfn_candid to allow us to migrate from dfn_protobuf.  It will be followed up by using the Runtime trait, and then a switch from DfnRuntime to CdkRuntime.

refactor(nervous_system): Use candid methods in ledger canister client

---

ci/src/dependencies/scanner/dependency_scanner_test.py
ci/src/dependencies/scanner/manager/bazel_rust_dependency_manager_test.py
ci/src/dependencies/scanner/manager/npm_dependency_manager_test.py

An old test code got pulled in the recent changes. This causes the dependency management [tests](https://github.com/dfinity/ic-private/actions/runs/10874044541/job/30170884228?pr=30) to fail on `ic-private`

fix(dependency-mgmt): Change root path for leftover tests in dependency-mgmt

---

packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/pocket_ic.rs

This PR fixes `dfx_test_key1` tECDSA and tSchnorr key names to `dfx_test_key`. The typo resulted from the same typo in developer docs (fix [PR](https://github.com/dfinity/portal/pull/3476)).

fix(PocketIC): dfx_test_key

---

.github/workflows-source/ci-main.yml
.github/workflows-source/release-testing.yml
.github/workflows-source/schedule-daily.yml
.github/workflows-source/schedule-hourly.yml
.github/workflows/ci-main.yml
.github/workflows/release-testing.yml
.github/workflows/schedule-daily.yml
.github/workflows/schedule-hourly.yml
.github/workflows/system-tests-k8s.yml
ci/bazel-scripts/main.sh
ci/scripts/run-build-ic.sh

I'm not sure why this issue didn't show up in a different way sooner, but the `${{ github.ref_protected }}` does not work as expected and usually defaults to `false`. This fix removes this env var and manually checks if the branch is in the list of branches we protect.

fix(IDX): fix ci logic related to branch protection rules

---

Cargo.lock
rs/embedders/benches/embedders_bench/Cargo.toml
rs/embedders/benches/embedders_bench/src/lib.rs
rs/embedders/benches/heap.rs
rs/test_utilities/execution_environment/src/lib.rs

This PR changes the wasm heap memory throughput benchmarks to allow them to run in Wasm64 mode.

chore: RUN-1035: Adapt wasm heap memory throughput benchmarks to run in Wasm64 mode

---

rs/rosetta-api/icp_ledger/README.md
rs/rosetta-api/icp_ledger/ledger/BUILD.bazel
rs/rosetta-api/icp_ledger/ledger/dfx.json
rs/rosetta-api/icp_ledger/ledger/scripts/dfx_deploy.sh

Adding a simple bazel target to make it easier building and deploying the icp ledger to a local ic replica using a single command.
The script run by the target also does any necessary cleanup required between deploying a new version of the canister when an older one is currently running there.

feat(icp-ledger): add bazel target for local replica testing

---

rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/tests/degraded_mode.rs
rs/nns/governance/tests/governance.rs
rs/nns/integration_tests/src/canister_upgrade.rs
rs/nns/integration_tests/src/copy_inactive_neurons_to_stable_memory.rs
rs/nns/integration_tests/src/governance_mem_test.rs
rs/nns/integration_tests/src/lifeline.rs
rs/nns/integration_tests/src/neuron_following.rs
rs/nns/integration_tests/src/reinstall_and_upgrade.rs
rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
rs/nns/test_utils/src/governance.rs
rs/nns/test_utils/src/neuron_helpers.rs
rs/tests/src/ledger_tests/transaction_ledger_correctness.rs

`InstallCode` has already been used for upgrading several NNS canisters. Now we don't need `NnsCanisterUpgrade` or `NnsRootUpgrade`.
* Make `NnsCanisterUpgrade` and `NnsRootUpgrade` obsolete by disabling proposal creation
* Switch existing tests using those proposal types to `InstallCode`

feat(nns): Disable NnsCanisterUpgrade and NnsRootUpgrade in favor of InstallCode

---

Cargo.lock
rs/nervous_system/canisters/BUILD.bazel
rs/nervous_system/canisters/Cargo.toml
rs/nervous_system/canisters/src/ledger.rs
rs/nervous_system/runtime/src/lib.rs
rs/nns/governance/canister/canister.rs
rs/rust_canisters/dfn_candid/BUILD.bazel
rs/sns/governance/canister/canister.rs
rs/sns/swap/canister/canister.rs
rs/sns/swap/src/types.rs

This migrates the ledger canister client to use the Runtime trait instead of directly calling out to dfn_core.
This is the second step in the series to migrate nns governance to ic_cdk from dfn_core

refactor(nervous_system): use Runtime trait for Ledger

---

Cargo.lock
rs/nervous_system/agent/BUILD.bazel
rs/nervous_system/agent/Cargo.toml
rs/nervous_system/agent/src/lib.rs
rs/nervous_system/agent/src/nns/sns_wasm.rs
rs/nervous_system/agent/src/sns/governance.rs
rs/nervous_system/clients/src/request.rs

The ic-nervous-system-agent library is hardcoded to only work with ic_agent. However, we may want to use its functions in a context where we don't have ic_agent. 
Create a `CallCanisters` trait that represents an object with the capability to call a canister. Implement that trait for `Agent`. In the future, implementations can also be created for other types. This is easy to do now, since rust now finally supports async traits without hacks. 
The trait has a `call` function, and different implementations support different errors. This is useful because different ways of calling canisters have different plausible errors (e.g. you are not going to get a boundary node error when a canister calls another, but you might when an external user calls a canister).
This also means that …

refactor(nervous-system): Make ic-nervous-system-agent generic over how it calls canisters

---

WORKSPACE.bazel
bazel/focal.lock.json
bazel/focal.yaml
rs/rosetta-api/BUILD.bazel
rs/rosetta-api/README.adoc
rs/rosetta-api/icrc1/rosetta/BUILD.bazel
rs/tests/BUILD.bazel
rs/tests/consensus/subnet_recovery/BUILD.bazel
rs/tests/consensus/subnet_recovery/orchestrator_universal_vm_activation.sh
rs/tests/httpbin-rs/BUILD.bazel
rs/tests/networking/canister_http/BUILD.bazel
rs/tests/networking/canister_http/canister_http.rs
rs/tests/src/btc_integration/btc_activate.sh
rs/tests/src/custom_domains_integration/activate.sh
rs/tests/src/jaeger/jaeger_activate.sh
rs/tests/src/rosetta_tests/setup.rs
rs/tests/system_tests.bzl
rs/tests/testing_verification/colocate_test.rs

This replaces the now-deprecated
[rules_docker](https://github.com/bazelbuild/rules_docker) with [rules_oci](https://github.com/bazel-contrib/rules_oci). This will allow us to upgrade our Bazel version (done separately).
There are a couple of notable changes. Overall, `rules_oci` is less just-add-water, and some of the `rules_docker` features were split into more rule sets (distroless, aspect).
* `rules_oci` does not expose `tarball`s by default, so a new `oci_tar` macro is introduced to expose `tarball`s.
* The `ubuntu_test_runtime_image` is now based on an Ubuntu snapshot and includes its own lockfile (see `bazel/focal.yaml`). This makes the image build more reproducible, and means the image can now also be built on CI (previously had to be built & uploaded separately).
* Images can now …

chore(IDX): replace rules_docker with rules_oci

---

rs/types/base_types/src/canister_id.rs
rs/types/base_types/src/canister_id/tests.rs

CanisterId::try_from(principal_id) never actually returns Err, even though not all principal IDs are canister IDs.
This new method does what CanisterId::try_from(principal_id) should have done.
We should look at all callers of `CanisterId::try_from(principal_id)` (including try_into) and figure out what they should call instead:
* `CanisterId::unchecked_from_principal`: This is for callers who assume that `try_from` always returns `Ok` even if the input is invalid. E.g. they immediately do `.unwrap()`, and assume that it never panics.
* `CanisterId::try_from_principal_id`: This is for callers who do NOT make that assumption. That is, they are prepared for Err to be returned. In some cases, they would even prefer that Err be returned, even though so far, `try_from` does not do that.
A …

refactor: CanisterId::try_from_principal_id.

---

rs/tests/ict/cmd/testnetCreateCmd.go
rs/tests/testing_verification/testnets/BUILD.bazel

Addressing the issue of being unable to pass additional args to bazel test from ict. Previously command like:
```bash
ict testnet create --from-ic-config-path /home/nikola/Downloads/test.json --lifetime-mins 10 -- --test_tmpdir=test_tmpdir/
```
Would result in an error:
```bash
There was an error while executing CLI: Cannot provide both `--from-ic-config-path` and a name for testnet configuration: --test_tmpdir=test_tmpdir/
```
Its been addressed here, and this allows us to pass normally additional arguments:
```bash
ict testnet create --from-ic-config-path /home/nikola/Downloads/test.json --lifetime-mins 10 -- --test_tmpdir=/home/nikola/Downloads/output
Raw Bazel command to be invoked:
$ bazel test //rs/tests/testing_verification/testnets:from_config --config=systest …
```

fix: ict `from_config` testnet not accepting additional bazel arguments

---

rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
rs/nns/constants/src/lib.rs
rs/nns/governance/tests/governance.rs
rs/nns/sns-wasm/canister/canister.rs
rs/nns/sns-wasm/src/canister_api.rs
rs/nns/sns-wasm/src/sns_wasm.rs

The wasm_memory_limit setting is useful because, when you canister reaches the limit, it prevents update calls but allows pre_upgrade to run. This can be used to make our canisters more resilient to a situation where they run out of memory, because it is unlikely that more memory will be consumed in the absence of update calls, but they can still be upgraded and keep their state because pre_upgrade is still able to runs.
Governance does not need to be changed because we get no advantage from having governance be at 3.5GB at this time.

feat(sns): Only set the `wasm_memory_limit` for SNS Governance when deploying an SNS

---

rs/starter/src/main.rs

This PR fixes a registry canister invariant violation in the local replica registry created by `ic-starter`: currently the public and xnet endpoints could be the same which violates an invariant and prevents the local replica registry from being synced into the registry canister; this PR ensure that the public and xnet endpoints are always distinct in the local replica registry.

fix(starter): registry invariants

---

rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/canister_control.rs
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/proposal.rs
rs/sns/governance/tests/fixtures/environment_fixture.rs
rs/sns/governance/tests/fixtures/mod.rs
rs/sns/governance/tests/governance.rs

#1427 made this change for the root canisters of new SNSes. This PR ensures that all root canisters have the expected settings by migrating existing SNSes. 
The change changes their settings to set wasm_memory_limit to 3GiB. This should be safe – no root canister uses anything close to 3GiB.

chore(sns): Migrate SNS Root's wasm_memory_limit

---

rs/execution_environment/src/execution/response.rs

This assert checks that there are no cases where the cycles balance of a canister can be reduced during execution. However, since this assert [was introduced about 2 years ago](https://github.com/dfinity/ic/commit/1d4692fd686a31a7f396f2d949d67edcaedcbfea), new legitimate cases have been added, like when the storage reservation mechanism kicks in or the canister calls `cycles_burn` API, that can reduce the canister's cycle balance. The assert is therefore deprecated and should be removed.
It replicates the [change](https://github.com/dfinity/ic/commit/5d1beaca74d0bf2ad2e8a37809e1e3ffa5ee9a32) that has already been patched on all IC subnets as part of the security hotfix that was performed over the last couple of days.

fix: Remove deprecated assert

---

rs/nervous_system/string/src/lib.rs
rs/nervous_system/string/src/tests.rs
rs/sns/governance/token_valuation/src/lib.rs

While trying to use `clamp_debug_len` to reduce log spam, I noticed that the argument was being moved.
The solution is to pass the argument by reference.

chore: Pass argument to clamp_debug_len by reference

---

Cargo.lock
rs/cross-chain/proposal-cli/BUILD.bazel
rs/cross-chain/proposal-cli/Cargo.toml
rs/cross-chain/proposal-cli/src/candid/mod.rs
rs/cross-chain/proposal-cli/src/git/mod.rs
rs/cross-chain/proposal-cli/src/ic_admin/mod.rs
rs/cross-chain/proposal-cli/src/ic_admin/tests.rs
rs/cross-chain/proposal-cli/src/proposal/mod.rs
rs/cross-chain/proposal-cli/templates/submit_with_ic_admin.shx

Automatically compute the SHA256 of install or upgrade arguments since as of #1154 `ic-admin` requires `arg-sha256` to be present when `arg` is present.

feat(proposal-cli): Automatically compute SHA256 of arguments

---

rs/replicated_state/src/canister_state/queues.rs
rs/replicated_state/src/canister_state/system_state.rs
rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
rs/replicated_state/src/canister_state/tests.rs

A best-effort response may be inducted after the matching call context has already expired; the reject response has been executed; and the call context was dropped. Because of this (and as opposed to guaranteed responses, where a duplicate or non-matching callback implies malicious behavior or a bug) best-effort responses that are either duplicates or don't match an existing callback should be silently dropped.

feat: [MR-607] Ignore non-matching best-effort responses

---

Cargo.lock
rs/sns/root/BUILD.bazel
rs/sns/root/Cargo.toml
rs/sns/root/canister/canister.rs
rs/sns/root/src/lib.rs

All the non-governance and non-root SNS canisters should have their `wasm_memory_limit` set to 3GiB via a root migration. (#1521 took care of this for root via a governance migration.) 
Once this PR is merged and released, all SNS canisters will have the same `wasm_memory_limit` - 4GiB for SNS Governance, 3GiB for all other canisters. I've already verified with the FI team that 3GiB is safe to use with all 3 FI canisters.
Closes [NNS1-3301](https://dfinity.atlassian.net/browse/NNS1-3301)
[NNS1-3301]: https://dfinity.atlassian.net/browse/NNS1-3301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(sns): migrate wasm_memory_limit in non-governance non-root canisters

---

rs/nns/governance/canister/canister.rs

Further increase the probability that deprecated methods will panic.

feat(nns): Further increase panic probability for deprecated pb methods

---

rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/tests/degraded_mode.rs
rs/nns/governance/tests/governance.rs
rs/nns/integration_tests/src/canister_upgrade.rs
rs/nns/integration_tests/src/copy_inactive_neurons_to_stable_memory.rs
rs/nns/integration_tests/src/governance_mem_test.rs
rs/nns/integration_tests/src/lifeline.rs
rs/nns/integration_tests/src/neuron_following.rs
rs/nns/integration_tests/src/reinstall_and_upgrade.rs
rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
rs/nns/test_utils/src/governance.rs
rs/nns/test_utils/src/neuron_helpers.rs
rs/tests/src/ledger_tests/transaction_ledger_correctness.rs

This PR also has an additional commit that re-re-reverts the changes in the original PR (#1496) that caused the tests to start failing. Those changes wll be re-applied after we address the remaining parties that are affected.

revert(nns): Re-apply changes from #1496 except for the ones that caused the tests to fail

---

.github/workflows/ci-generate-ci.yml

This changes the `ci-generate-ci` workflow triggers to also run on `dev-gh-*` branches. This helps test out new CI configuration without having to create a (draft) PR.

fix(IDX): Generate CI config on dev-gh branches

---

Cargo.lock
rs/registry/canister/BUILD.bazel
rs/registry/canister/Cargo.toml
rs/registry/canister/canister/canister.rs
rs/registry/canister/src/invariants/checks.rs

On local testing, I noticed some logging from the registry canister with pages and pages of comma separated numbers.
For one of these I tracked down that it was added in https://github.com/dfinity/ic/commit/b8f696f07c129c905e4affb54bf0f85acf763926 so I asked ([slack](https://dfinity.slack.com/archives/C0175CHJ0P6/p1726644247928809)) the author if we need these logs. He suggested to log the first 80 bytes.
Since the `clamp_debug_len` function we use preserves an equal amount of text from the start and end, I thought a max length of 800 would work: 5 characters per byte (3 digits, a comma and a space) means 80 bytes is 400 characters.
But after trying this, I realized that the list of numbers is not right at the start of the output. I determined experimentally that a max length of 1300 …

chore: Clamp some spammy registry logs

---

Cargo.lock
rs/consensus/src/consensus/block_maker.rs
rs/consensus/src/consensus/validator.rs
rs/consensus/utils/BUILD.bazel
rs/consensus/utils/Cargo.toml
rs/consensus/utils/src/lib.rs

The functions doesn't need to be shared across crates.
Also, removed unneeded dependencies

chore(consensus): move `get_block_maker_delay` function from `consensus_utils` crate to `consensus` crate

---

rs/tests/consensus/consensus_performance.rs
rs/tests/consensus/utils/src/performance.rs

I think it's a useful metrics to keep track of.
Also, added a small test case where we send very few, very small messages.
```
2024-09-18 14:55:22.612 INFO[uvms_logs_stream:StdOut] [uvm=test-driver] TEST_LOG: ===== Summary for //rs/tests/consensus:consensus_performance_colocate =====
2024-09-18 14:55:22.612 INFO[uvms_logs_stream:StdOut] [uvm=test-driver] TEST_LOG: Task setup                   PASSED  in 126.30s   -- Exited with code 0.
2024-09-18 14:55:22.612 INFO[uvms_logs_stream:StdOut] [uvm=test-driver] TEST_LOG: Task test_few_small_messages PASSED  in  98.22s
2024-09-18 14:55:22.612 INFO[uvms_logs_stream:StdOut] [uvm=test-driver] TEST_LOG:      Success rate: 100.0%
2024-09-18 14:55:22.616 INFO[setup:rs/tests/testing_verification/colocate_test.rs:321:0] Test execution finished with …
```

test(consensus): Print the `consensus_time_to_receive_block` metric at the end of `consensus_performance_test`

---

ci/bazel-scripts/main.sh

This adds some processing to bazel's stderr when running on CI. In particular, the BuildBuddy link is now repeated more often (every 20 lines), the output is colored (both on GHA & BuildBuddy) and a GitHub annotation is created (visible on job summary page once job ends).

feat(IDX): Improve CI Bazel logs

---

rs/artifact_pool/src/consensus_pool.rs

Thanks to @kpop-dfinity for catching this.

fix(consensus): Include equivocation proofs in artifacts returned by get_all_validated 

---

rs/nns/governance/benches/scale.rs
rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/test_utils.rs
rs/nns/governance/tests/degraded_mode.rs
rs/nns/governance/tests/fake.rs
rs/nns/governance/tests/fixtures/environment_fixture.rs
rs/nns/governance/tests/fixtures/mod.rs
rs/nns/governance/tests/governance.rs

Small refactor to make an interface more correct (it does not mutate the struct state).  
Next: https://github.com/dfinity/ic/pull/1565

refactor(nns): remove unnecessary mut from call_canister_method signature

---

Cargo.lock
rs/nns/test_utils/golden_nns_state/BUILD.bazel
rs/nns/test_utils/golden_nns_state/Cargo.toml
rs/nns/test_utils/golden_nns_state/src/lib.rs

Expand the canister ID ranges for the `StateMachine` app subnet in the golden state tests for the NNS, SNS, and fiduciary subnets to cover all possible canister IDs. This is to avoid scenarios where the tests may fail in case there are some messages to canisters on other subnets that cannot be routed.

test(ICRC_ledger): FI-1492: Set subnet configs in golden state tests to cover all canister IDs

---

rs/tests/message_routing/xnet/xnet_slo_3_subnets_hotfix_test.rs

After setting the XNet tests to non flaky I saw some timeouts of the test below, suggesting that the test setup can be slow in certain scenarios. This PR bumps the timeouts.

test: Bump XNet hotfix test timeout

---

.github/actions/bazel-test-all/action.yaml
ci/bazel-scripts/main.sh

This streamlines the output as shown on CI in two ways:
* The bazel-exporter output is hidden (unless it errors out) which allows the reader to focus on the output of the main command,
* `set -x` is removed which allows the reader to focus on the output of the main command,
* The BuildBuddy URL is repeated at the end of the build.
NOTE: the previous implementation used process substitution, which might break under some circumstances (when bash doesn't wait for `awk` to finish). Instead, simple piping is used (and stderr & stdout are merged & passed to `awk`).

fix(IDX): Bazel build output and bes link

---

rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
rs/replicated_state/src/canister_state/system_state/call_context_manager/tests.rs

[MR-612] Implement a priority queue of best-effort callback expiration times in `CallContextManager`; a function that returns newly expired callbacks; and persistence for this queue.
[MR-612]: https://dfinity.atlassian.net/browse/MR-612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [MR-612] Callback expiration priority queue

---

rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/scheduler_metrics.rs

This PR improves the tracking of executed canisters during a round by refining the counting logic and switching the associated metric to a histogram.
- The previous implementation used a variable called `executed_canisters`, which represented the number of canisters initially planned for execution. However, not all planned canisters were necessarily executed due to round instruction limit. This has been renamed to `active_canisters` to clarify its meaning. The function now also returns the IDs of the canisters that were actually executed before any instruction limits were reached.
- The metric `scheduler_executed_canisters_per_round` is switched from a gauge to a histogram. Gauges led to data loss as scraping occurred every 10-20 seconds, missing changes between scrapes. A histogram …

fix: fix a metric for counting actually executed canisters per round

---

rs/config/src/execution_environment.rs
rs/execution_environment/src/query_handler.rs
rs/starter/src/lib.rs

This PR makes `allowed_viewers` feature flag configurable in execution config and enables it in `ic-starter` for DFX.
So the feature is enabled in DFX for implementation and testing, but is still disabled in prod.

chore: make allowed viewers feature flag configurable and enable it for ic-starter

---

Cargo.lock
rs/nervous_system/agent/BUILD.bazel
rs/nervous_system/agent/Cargo.toml
rs/nervous_system/agent/src/agent_impl.rs
rs/nervous_system/agent/src/lib.rs
rs/nervous_system/agent/src/pocketic_impl.rs

This will allow us to use ic-nervous-system-agent helper functions from within tests built on pocket-ic. This PR synergizes with #1589, which starts to use ic-nervous-system-agent types from within ic-nervous-system-integration-tests

refactor(nervous-system-agent): Add pocket-ic support to ic-nervous-system-agent

---

rs/embedders/src/wasm_utils/instrumentation.rs
rs/embedders/src/wasm_utils/validation.rs
rs/embedders/tests/validation.rs
rs/embedders/tests/wasmtime_embedder.rs
rs/types/wasm_types/src/errors.rs

In this PR we add an additional validation step for the initial size for Wasm64 memories. The size of initial wasm heap memory should not be more than the protocol allows.

feat: RUN-1036: Validate initial wasm memory size for Wasm64

---

rs/p2p/artifact_downloader/src/fetch_stripped_artifact/assembler.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/download.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/metrics.rs

Sample of metrics fetched in a middle of `consensus_performance_test`:
```
ic_stripped_consensus_artifact_downloader_ingress_messages_in_a_block_count_bucket{source="ingress_pool",le="0"} 131
ic_stripped_consensus_artifact_downloader_ingress_messages_in_a_block_count_bucket{source="ingress_pool",le="1"} 140
ic_stripped_consensus_artifact_downloader_ingress_messages_in_a_block_count_bucket{source="ingress_pool",le="2"} 140
ic_stripped_consensus_artifact_downloader_ingress_messages_in_a_block_count_bucket{source="ingress_pool",le="5"} 140
ic_stripped_consensus_artifact_downloader_ingress_messages_in_a_block_count_bucket{source="ingress_pool",le="10"} 140
ic_stripped_consensus_artifact_downloader_ingress_messages_in_a_block_count_bucket{source="ingress_pool",le="20"} 140 …
```

feat: [CON-1373] Introduce metrics to the block stripper/assembler

---

rs/nns/integration_tests/src/reset_root.rs

This PR refactors NNS integration tests to retrieve the module hash of a canister via its canister status instead of via a dedicated function `StateMachine::module_hash` since that dedicated function is not available in PocketIC and thus it'd introduce unnecessary complications to migration of NNS integration tests to PocketIC.

chore: refactor state_machine.module_hash in NNS integration tests

---

rs/nns/test_utils/golden_nns_state/src/lib.rs

Setting `subnet_config.scheduler_config.max_instructions_per_slice = MAX_INSTRUCTIONS_PER_SLICE` is not necessary as this is now the default for both system and application subnets.

chore: drop unnecessary config override

---

Cargo.lock
rs/cross-chain/proposal-cli/BUILD.bazel
rs/cross-chain/proposal-cli/Cargo.toml
rs/cross-chain/proposal-cli/src/dashboard/mod.rs
rs/cross-chain/proposal-cli/src/git/mod.rs
rs/cross-chain/proposal-cli/src/main.rs

Allows to batch upgrade or install proposals. This is for example useful, when multiple canisters such as a ledger suite (ledger, index, archive) need to be upgraded together from one version to the next.

feat(proposal-cli): Batching

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
Cargo.toml
bazel/external_crates.bzl
packages/pocket-ic/BUILD.bazel
packages/pocket-ic/Cargo.toml
packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs

This PR makes the PocketIC library reuse the `ReadStateResponse` and `SubnetMetrics` type from `ic-transport-types` instead of redefining it from scratch (incl. custom deserializer).

chore(PocketIC): use ReadStateResponse and SubnetMetrics type from ic-transport-types

---

rs/consensus/src/consensus/validator.rs

This will be helpful in case we get paged, and need to find out who produced the equivocating block.

chore(consensus): Add info log when producing equivocation

---

.github/workflows-source/ci-main.yml
.github/workflows-source/release-testing.yml
.github/workflows-source/schedule-daily.yml
.github/workflows-source/schedule-hourly.yml
.github/workflows/ci-main.yml
.github/workflows/release-testing.yml
.github/workflows/schedule-daily.yml
.github/workflows/schedule-hourly.yml
.github/workflows/system-tests-k8s.yml

Uploading `profile.json` and BEP files only make sense if file is complete (CI job can get interrupted).

chore(IDX): upload bazel-bep on failure or success

---

ic-os/components/BUILD.bazel

This was removed early in the build refactor because there was no good integration point. Bring it back now that things are in a better state.

feat: Bring back ic.json5 validation test

---

rs/nns/governance/canister/canister.rs

Lower the probability of deprecated *_pb methods panicking to give integrators more time to migrate.

feat(nns): Lower probability of panicking deprecated methods

---

rs/registry/admin/src/main.rs

Currently, ic-admin has two code paths for `ProposeToChangeNnsCanister`, depending on `use_legacy_execute_nns_function`. The correspondence between the `arg` and `arg_sha256` CLI arguments is checked only in the legacy flow. The PR fixes that shortcoming.

feat(ic-admin): Check the correspondence between `arg` and `arg_sha256` before submitting install code requests

---

testnet/tools/nns-tools/lib/proposals.sh

Previously, the release tsar would manually fill out the "Features, Fixes, and Optimizations" section, but this doesn't seem to add much value, because what they more or less do is copy a subset of commit messages from the "New Commits" section. This would only be valuable if the release tsar does some additional interpretation of the commit messages to make it more understandable to a broader audience, but this rarely happens.
At the same time, manually populating this section takes time, and takes up space (which could be considered "spam" or "noise").
Therefore, the NNS team decided (by unanimous consent!) to get rid of this section entirely.
In short, this streamlines the process, and makes proposal summaries more concise.
One recent change that makes us revisit this now: Conventional …

feat(nervous-system-tools): No TODOs in generated proposal summary.

---

rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/test_utilities.rs
rs/execution_environment/src/scheduler/tests.rs
rs/execution_environment/tests/dts.rs

While in general it's safe to modify the state of aborted canisters, there are a few exceptions. Unlike normal canisters, aborted canisters have already taken messages from the input queues and stored them in their task queues. Therefore, subnet messages that would pause canister execution or alter  the task queue are not allowed for now.

feat: EXC-1737: Execute subnet messages on aborted canisters

---

rs/state_manager/src/lib.rs

This is a follow-up to commit a438bb7. The idea of the previous commit was to defragment the memory layout of the list of canisters. This fix makes sure we actually defragment the correct state, namely the one that has been fragmented in earlier rounds. The previous PR was perfectly safe, but did not provide the desired performance benefit.

fix: Defragment correct state

---

rs/sns/init/src/lib.rs

[Next PR →](https://github.com/dfinity/ic/pull/1606)
ic-sns-init has :init and :init--test-feature targets, which makes our dependency situation very hairy due to the viral nature of test features. It should be removed, but first ic-sns-init needs to not have any differential behavior between the test and normal configurations.
Remove the code that ran when cfg(feature = "test") was true. This was code that set up ledger with a principal with a ton of tokens.
This was probably needed at first, but is no longer, because the test configuration of the SNS Gov canister has a `mint_tokens` API that can be used instead. If this breaks anyone, I will help them switch over to the new API. I think the `nns_dapp` has already switched to the new API.

refactor(sns): Remove different sns init behavior when cfg(feature = "test")

---

publish/binaries/BUILD.bazel
rs/nervous_system/integration_tests/BUILD.bazel
rs/nns/governance/BUILD.bazel
rs/nns/governance/api/BUILD.bazel
rs/nns/governance/init/BUILD.bazel
rs/nns/gtc/BUILD.bazel
rs/nns/integration_tests/BUILD.bazel
rs/nns/sns-wasm/BUILD.bazel
rs/nns/test_utils/BUILD.bazel
rs/registry/admin/BUILD.bazel
rs/sns/cli/BUILD.bazel
rs/sns/governance/BUILD.bazel
rs/sns/governance/canister/canister.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/tests/fixtures/mod.rs
rs/sns/init/BUILD.bazel
rs/sns/integration_tests/BUILD.bazel
rs/sns/swap/BUILD.bazel
rs/sns/test_utils/BUILD.bazel

[← Previous PR](https://github.com/dfinity/ic/pull/1609)
There are two reasons to have a --test_feature target:
1. The crate itself has different functionality when cfg(feature = "test") is true
2. The crate is a library that depends on crate that has a --test_feature target, and needs to give the choice to its consumer whether the dependency has --test_feature enabled.
The second rule is "viral" which has lead to a massive outbreak of crates with a `--test_feature` target. In fact most of our crates that had a --test_feature target were in the second category.
The root cause of most of these was that SNS Governance's library had a `--test_feature` target. This PR:
1. Moves the logic for determining whether we are in "test mode" to the canister crate (from the library crate)
2. Remove's …

refactor(nervous-system): Remove ic-sns-governance and ic-sns-init's test_feature configurations

---

Cargo.lock
rs/nervous_system/integration_tests/BUILD.bazel
rs/nervous_system/integration_tests/Cargo.toml
rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/sns_ledger_upgrade.rs
rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
rs/nervous_system/integration_tests/tests/sns_release_qualification.rs

Unlike `DeployedSns`, the `Sns` type has no optional fields. This means we can remove the repetitive unwrapping in every test that deploys an SNS. The `Sns` type also has some utility functions on it that can be used in the integration tests once #1590 is merged

refactor(nervous-system): Use `Sns` type in integration tests rather than `DeployedSns`

---

testnet/tools/nns-tools/lib/proposals.sh

Previously it failed silently if there was any error, and in my case there was an error since I don't have didc on my PATH. This happened when submitting [a CMC upgrade](https://dashboard.internetcomputer.org/proposal/133088). This PR makes the error terminate the proposal submission

fix(nns-tools): fail proposal creation if not able to put candid args in file

---

ic-os/components/misc/fetch-property.sh
ic-os/components/setupos-scripts/check-network.sh

[NODE-1483](https://dfinity.atlassian.net/browse/NODE-1483)
Two bugs exist in assemble_nns_nodes_list and fetch_property. In assemble_nns_nodes_list, fetch-property is called without passing a metric value, which causes the call to fail to populate NNS_URL_STRING.
Then, when query_nns_nodes was called, the for loop was never entered and no failure was caught. 
This PR updates fetch-property to make the metric field optional if metrics.sh does not exist and it also refactors query_nns_nodes to fail if NNS_URL_LIST is empty.
I tested this change on bare metal 👍 
[NODE-1483]: https://dfinity.atlassian.net/browse/NODE-1483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(NODE-1483): query_nns_nodes bug

---

rs/bitcoin/adapter/src/get_successors_handler.rs

The check is not giving us much so I would prefer to remove it.
In the stady case the check has no effect since all anchors that are passed as part of the request will be pass the checkpoint.
The check make sense only when the canister is syncing. But even in this case the check doesn't by us much because:
1. it will reject only 1-2 requests because syncing the headers will take just a few seconds.
2. the check is not really preventing forks from happening because we can have a fork pass the checkpoint as well.

chore: remove the is_beyond_last_checkpoint check when serving requests

---

bazel/candid.bzl

This fixes bash errors when OVERRIDE_DIDC_CHECK is unset, by defaulting it to the empty string. This is standard best practice with bash variable and fixes test failures in some environments.

fix(IDX): allow empty OVERRIDE_DIDC_CHECK

---

rs/rosetta-api/BUILD.bazel
rs/rosetta-api/icp_ledger/index/BUILD.bazel
rs/rosetta-api/icp_ledger/ledger/BUILD.bazel

To unblock developers, (temporarily) mark the following FI tests as flaky:
- `//rs/rosetta-api/icp_ledger/ledger:ledger_canister_test`
- `//rs/rosetta-api/icp_ledger/index:ic_icp_index_test`
- `//rs/rosetta-api:icp_rosetta_system_tests_tests/system_tests/system_tests`

chore(FI): FI-1505: Mark some FI tests as flaky

---

rs/config/src/subnet_config.rs
rs/execution_environment/src/execution/response/tests.rs
rs/execution_environment/src/execution_environment/tests/canister_task.rs
rs/execution_environment/src/hypervisor/tests.rs
rs/execution_environment/src/query_handler/tests.rs
rs/execution_environment/tests/canister_logging.rs
rs/execution_environment/tests/execution_test.rs
rs/execution_environment/tests/in_replicated_execution.rs

This PR increases the `install_code` message limit for application subnets from 200B to 300B. This setting matches the one for verified application subnets and brings the gap closer between the two types.

feat: Increase install_code limit for application subnets

---

BUILD.bazel
WORKSPACE.bazel
bazel/pocket-ic-tests.bzl
rs/bitcoin/ckbtc/kyt/BUILD.bazel
rs/bitcoin/kyt/BUILD.bazel

This adds a build setting & related transition that allows for the pocket-ic version of tests to be overriden. By default `//:pocket-ic-server` points to the pocket-ic server from the source tree. This can be overriden by using `pocket_ic_mainnet_test` or by using the `//:pocket-ic-mainnet` target.

feat(IDX): allow tests to depend on mainnet pocket-ic

---

Cargo.lock
rs/nervous_system/agent/BUILD.bazel
rs/nervous_system/agent/Cargo.toml
rs/nervous_system/agent/src/nns/sns_wasm.rs
rs/nervous_system/agent/src/sns/governance.rs
rs/nervous_system/agent/src/sns/mod.rs
rs/nervous_system/agent/src/sns/root.rs
rs/nervous_system/tools/sync-with-released-nevous-system-wasms/src/main.rs
rs/sns/cli/src/health.rs
rs/sns/cli/src/lib.rs
rs/sns/cli/src/list.rs
rs/sns/cli/src/main.rs
rs/sns/cli/src/utils.rs
rs/sns/governance/src/request_impls.rs
rs/sns/root/src/lib.rs
rs/sns/root/src/request_impls.rs
rs/sns/root/src/types.rs

This adds a `health` command to the sns cli. You can run it like so from the monorepo:
```
$ bazel run :sns --config=local -- health
```
The output at the time of this writing is this:
Checking SNS's health...
| Name                    | Memory | Cycles                                                                      | Upgrades Remaining |
|-------------------------|--------|-----------------------------------------------------------------------------|--------------------|
| BOOM DAO                | 👍      | ❌ index: (9.49 TC)                                                          | 5                  |
| CYCLES-TRANSFER-STATION | 👍      | 👍                                                                           | 5                  |
| Catalyze                | 👍      | ❌ root: …

feat(sns-cli): Add `sns health` command

---

rs/tests/message_routing/BUILD.bazel
rs/tests/src/message_routing/rejoin_test.rs
rs/tests/src/message_routing/rejoin_test_large_state.rs

This PR fixes the flakiness of some state sync tests by retrying interacting with recently installed subnets instead of just failing.

test: Fix state sync tests flakiness

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml
ci/src/dependencies/job/bazel_rust_ic_scanner_release_job.py
ci/src/dependencies/model/ic.py

Python tests are not correctly running on ic-private, so pass in REPO_NAME as env var.

fix(IDX): fix python tests

---

Cargo.lock
rs/consensus/BUILD.bazel
rs/consensus/Cargo.toml
rs/consensus/src/consensus/block_maker.rs
rs/phantom_newtype/src/amountof.rs

Since we're using saturating arithmetic in many places (including `Time`), it might be good to have a blanket implementation for the phantom types.

chore: Implement saturating sub for AmountOf

---

.github/workflows-source/ci-pr-only.yml
.github/workflows-source/release-testing.yml
.github/workflows-source/schedule-daily.yml
.github/workflows/ci-pr-only.yml
.github/workflows/release-testing.yml
.github/workflows/schedule-daily.yml
ci/src/dependencies/scanner/dependency_scanner_test.py
ci/src/dependencies/scanner/manager/bazel_rust_dependency_manager_test.py

- Add REPO_NAME env var to all dependency-mgmt workflows. 
- Hopefully the last regression fix of tests between ic and ic-private.
-  Failures - https://github.com/dfinity/ic-private/actions/runs/11055160435/job/30713697688
-  Fix testing - https://github.com/dfinity/ic-private/pull/36
-  Test is green - https://github.com/dfinity/ic-private/actions/runs/11102905495/job/30843736486

chore(dependency-mgmt): Add REPO_NAME env var to dependency-mgmt CI jobs

---

.github/workflows-source/release-testing.yml
.github/workflows/release-testing.yml

This PR aims to fix the issues that have been occurring in the CI with issue in race conditions in uploading the same file from different matrix jobs.

fix: fixing bazel bep name generation for qualification

---

testnet/tools/lib.sh
testnet/tools/nns-tools/list-new-commits.sh

Overall, tries to make list-new-commits.sh more ergonomic.
Boring is defined as having one of the following Conventional Commits prefixes:
- chore
- refactor
- test
Colorizes.
When commit ID is not supplied, warns that one is chosen automatically. (When I originally sent this out for review, commit ID was required, but feedback said this is too inconvenient. So, I switched to printing a warning.)
Factored out common code from two loops (one for NNS, the other for SNS).
Adds more print_* colors.
Instead of manually reviewing which canisters to upgrade, this could be used to make that choice for us (using the same criterion for using green to print the canister heading). This would help streamline our releases, and in particular, reduce the release tsar's workload.

feat(nervous-system): Filter out boring commits when listing new NNS and SNS commits.

---

rs/sns/audit/src/lib.rs

This PR makes the `bazel run //rs/sns/audit:sns-audit` command work for SNS projects that did not request any Neurons' Fund participation.

feat(sns-audit): Correctly validate swaps without Neurons' Fund participation

---

rs/interfaces/state_manager/mocks/src/lib.rs
rs/interfaces/state_manager/src/lib.rs
rs/state_manager/src/lib.rs
rs/test_utilities/src/state_manager.rs

Close [MR-615](https://dfinity.atlassian.net/browse/MR-615)
This PR (1) excludes checkpoint_heights from the result of list_state_heights and (2) removes it from the StateReader trait and make it an associated method.
[MR-615]: https://dfinity.atlassian.net/browse/MR-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [MR-615] Refactor list_state_heights and make it an associated method

---

rs/sns/governance/canister/canister.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/types.rs
rs/sns/governance/tests/fixtures/environment_fixture.rs

We remove an unused random method, and rename the other method to denote the insecurity of the random number generate.  It currently is not used in a way that needs to be secure, so no further work needs to be done.

refactor(sns): Rename random_u64 to insecure_random_u64 and remove random_bytes in SNS gov

---

Cargo.lock
rs/nns/governance/BUILD.bazel
rs/nns/governance/Cargo.toml
rs/nns/governance/benches/scale.rs
rs/nns/governance/canister/canister.rs
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/heap_governance_data.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/src/test_utils.rs
rs/nns/governance/tests/degraded_mode.rs
rs/nns/governance/tests/fake.rs
rs/nns/governance/tests/fixtures/environment_fixture.rs
rs/nns/governance/tests/fixtures/mod.rs
rs/nns/governance/tests/governance.rs
rs/nns/integration_tests/src/node_provider_remuneration.rs
rs/sns/governance/canister/canister.rs

In NNS Governance.
This is done by reseeding every hour. The seed is sourced from the raw_rand method of the management canister, and because of this, these seeds are "as secure as it gets". This is a compromise between speed and security that DFINITY's security team is ok with.
Currently, there is no need for secure RNs. However, that could come up in the future, and when it does, it would be too easy for us to overlook (without this change).

feat(nns): More secure random numbers.

---

ci/src/dependencies/scanner/manager/npm_dependency_manager_test.py

In #1746 all tests should have been fixed. 
Looks like I missed a single file when applying the patch from `ic-private` to `ic`.
Reference PR - https://github.com/dfinity/ic/pull/1746/files
IC Private PR - https://github.com/dfinity/ic-private/pull/36/files

fix(dependency-mgmt): Apply ic-private patch to a leftover test

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

We don't have intel runner configured for `ic-private` so just skip the job instead of letting it hang.

chore(IDX): update intel job logic

---

.github/workflows-source/schedule-daily.yml
.github/workflows/schedule-daily.yml

Adjust the bazel target for the FI nightly test to match the renamed directory structure.

chore(ICP_ledger): FI-1514: Adjust bazel target for FI nightly

---

rs/tla_instrumentation/tla_instrumentation/src/tla_state.rs

As experienced by Andy, the existing error message isn't super helpful.

chore: Improve the error message when merging conflicting TLA locals

---

rs/execution_environment/src/execution/response.rs
rs/execution_environment/src/execution/response/tests.rs
rs/replicated_state/src/canister_state/system_state.rs

This fixes an edge case where in a cleanup callback that has produced some cycles balance change and when there's an accumulated ingress induction debit (due to ingress messages inducted while the cleanup callback was running DTS), the canister's balance might end up with an amount that wouldn't respect the canister's freezing threshold.
Typically, for other message executions, the DTS execution would fail if there were concurrent cycles changes that could not be applied. The cleanup callback is a bit different and failing it is not a good option; canisters depend on it running successfully to perform critical tasks (such as releasing locks or reverting state changes in case something goes wrong). Therefore, we should ensure that the cleanup callback can still complete successfully.
The …

fix: Cap ingress induction debit for cleanup callback

---

rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/round_schedule.rs
rs/execution_environment/src/scheduler/tests.rs

The idle canisters in front of the round schedule should be marked as fully executed, as they were scheduled first in the round.
This helps to rotate the round schedule faster.

feat: EXC-1751: Charge idle canisters for full execution

---

rs/protobuf/def/state/queues/v1/queues.proto
rs/protobuf/src/gen/state/state.queues.v1.rs
rs/protobuf/src/gen/types/state.queues.v1.rs
rs/replicated_state/src/canister_state/queues/message_pool.rs
rs/replicated_state/src/canister_state/queues/queue.rs
rs/replicated_state/src/canister_state/queues/tests.rs

[MR-616]: Instead of using enum references, as initially planned, we use plain numeric references but look them up in the pool plus a couple of compact reject response maps. So the `CanisterQueue::QueueItem` proto is no longer necessary.
As a first step, add and populate a new, simpler representation of canister queues (using plain integers). In a second step (and after a replica release) we can then drop the old representation and the `CanisterQueue::QueueItem` message.
[MR-616]: https://dfinity.atlassian.net/browse/MR-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [MR-616] Drop `CanisterQueue::QueueItem` proto, part 1

---

.github/workflows/ci-pr-only-team-tags.yml

The "Tag Team Reviewers" workflow was [failing](https://github.com/dfinity/ic-private/actions/runs/11152689696/job/30998779522?pr=39) in the private repo with:
```
+ gh pr edit 39 --add-label @ic-message-routing-owners
GraphQL: Resource not accessible by integration (repository.pullRequest.projectCards.nodes)
```
According to https://github.com/cli/cli/issues/6274 this will be fixed by adding the `repository-projects: read` permission.
Tested in: https://github.com/dfinity/ic-private/pull/41.

fix(IDX): fix the "Tag Team Reviewers" workflow when run in the private repo

---

rs/config/src/subnet_config.rs

Internal metrics show that spawning of sandbox process is closer to 2ms on average so updating the relevant overhead to align better with the actual pressure on the system.

fix: Tweak instruction overhead per canister

---

.github/workflows-source/release-testing.yml
.github/workflows/release-testing.yml

It's unclear why we set it in the first place, but it falsely shows the release pipeline as green.

fix(IDX): remove continue-on-error

---

ic-os/boundary-guestos/context/Dockerfile
ic-os/guestos/context/Dockerfile
ic-os/hostos/context/Dockerfile
ic-os/setupos/context/Dockerfile

- Don't enable template units (these will fail without the instance variable)
- Remove unnecessary check whether the definition contains an [Install] directive

fix: Small change in how we enable systemd services

---

rs/types/types/src/exhaustive.rs

This was introduced along with `SysUnknown`, for backwards compatibility. Now that `SysUnknown` is supported by mainnet replicas, the filter can be dropped.

chore: [MR-610] Revert custom `impl ExhaustiveSet for RejectCode`

---

rs/state_machine_tests/src/lib.rs

This PR ensures that `StateMachine` registry contains no special ipv6 addresses by setting its first byte to `0xe0`. This guarantees that the ipv6 address satisfies the registry canister [check](https://github.com/dfinity/ic/blob/4a1c62f4c9ede0e888002931bdadbfd74878238f/rs/registry/canister/src/invariants/endpoint.rs#L124).

fix: ensure that StateMachine registry contains no special ipv6 addresses

---

rs/tests/dashboards/IC/execution-metrics.json

This PR updates "Execution Metrics" testnet grafana dashboards to be up-to-date with same dashboards in prod.
Specifically this adds a section with dashboards for counting canisters (total, non-idle, executed).

chore: update execution metrics dashboards for testnets

---

rs/ethereum/cketh/playground/README.adoc

This MR proposes the following changes:
1. Fix the git hash and subdirectory path of the icrc1 ledger of the README for ckETH

fix(ckETH): update readme

---

.github/scripts/determine-initial-guest-os-versions.py
.github/scripts/generate-ci.py
bazel/candid_integration_tests/candid_integration_tests.py
bazel/inject_version_into_wasm_tests/inspect_stamped_trivial_wasm.py
ci/src/git_changes/git_changes.py
ci/src/git_changes/git_changes_test.py
ic-os/components/conformance_tests/check_file_references.py
ic-os/components/upgrade/shared-resources/monitor-expand-shared-data/monitor-expand-shared-data.py
ic-os/dev-tools/bare_metal_deployment/deploy.py
ic-os/dev-tools/power-metric-verification/parse_voltage_readings.py
pre-commit/ruff-format.sh
pre-commit/ruff-lint.sh
rs/boundary_node/certificate_issuance/certificate_orchestrator/public_suffix_list_shrink.py
rs/coverage.py
rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/scripts/cost_estimator.py
rs/ethereum/cketh/minter/scripts/ofaq_blocklist.py
rs/tests/proptests/proptest-regression-parser.py
rs/workload_generator/plot.py
testnet/ansible/inventory/inventory.py
testnet/host_inventory.py
testnet/tools/icos_collect_debug_info.py
toolchains/sysimage/build_container_base_image.py
toolchains/sysimage/build_container_filesystem_tar.py
toolchains/sysimage/build_ext4_image.py
toolchains/sysimage/build_fat32_image.py
toolchains/sysimage/build_lvm_image.py
toolchains/sysimage/build_vfat_image.py
toolchains/sysimage/container_utils.py

1. `//pre-commit:ruff-lint` will check both linting rules and formatting
2. `//pre-commit:ruff-format` will fix both linting rule fixes and formatting. 
The formatting rules are default for now.

chore(ic): Update python formatting rules for the monorepo

---

ic-os/components/boundary-guestos/opt/ic/bin/firewall-counter-check.sh
ic-os/components/early-boot/setup-hostname/hostos/setup-hostname.sh
ic-os/components/hostos-scripts/generate-guestos-config/dev-generate-guestos-config.sh
ic-os/components/hostos-scripts/generate-guestos-config/generate-guestos-config.sh
ic-os/components/hostos-scripts/guestos/start-guestos.sh
ic-os/components/hostos-scripts/guestos/stop-guestos.sh
ic-os/components/hostos-scripts/misc/detect-first-boot.sh
ic-os/components/hostos-scripts/misc/fetch-mgmt-mac.sh
ic-os/components/hostos-scripts/monitoring/monitor-guestos.sh
ic-os/components/init/bootstrap-ic-node/guestos/bootstrap-ic-node.sh
ic-os/components/monitoring/ipv4-connectivity-check/ipv4-connectivity-check.sh
ic-os/components/setupos-scripts/check-hardware.sh
ic-os/components/setupos-scripts/check-network.sh
ic-os/components/setupos-scripts/check-setupos-age.sh
ic-os/components/setupos-scripts/config.sh
ic-os/components/setupos-scripts/functions.sh
ic-os/components/setupos-scripts/install-guestos.sh
ic-os/components/setupos-scripts/install-hostos.sh
ic-os/components/setupos-scripts/setup-disk.sh
ic-os/components/setupos-scripts/setup-hostos-config.sh
ic-os/components/setupos-scripts/setupos.sh
ic-os/components/upgrade/manageboot/manageboot.sh

Easier to review by commits:
- [Remove variation in generate-guestos-config scripts except for what's necessary](https://github.com/dfinity/ic/pull/1857/commits/5593cce57e3925795468631852421f3f0b778051)
- [Add -e to log_and_halt_installation_on_error echo](https://github.com/dfinity/ic/pull/1857/commits/5a66aa42e72d52c4720701bef23c5ee955bd564e)
- [Organize sourcing in bash scripts](https://github.com/dfinity/ic/pull/1857/commits/7e6e3b8866af1c77feaac07945d7d5c635ee68b6)
- [Log domain in check-network.sh error](https://github.com/dfinity/ic/pull/1857/commits/c9d4e99ed428c93d5538fb5cfc043cfc6dcac3a2)

chore: assorted ic-os bash script clean-ups and tweaks

---

ic-os/components/hostos-scripts/verbose-logging/verbose-logging.service

When the verbose flag is not enabled, verbose-logging.sh exits immediately, but the service file was set to restart causing it to restart over and over again. After several rapid restarts, systemd marks the service as failed to prevent a restart loop.
This changes the service to only restart on failure

fix: verbose logging service file failure

---

rs/consensus/tests/integration.rs

The integration test mistakenly used the `absent_notary_share` modifier, instead of the equivocation flag.

fix(consensus): Use correct malicious flags in equivocation integration test

---

rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/advance_target_version.rs
rs/sns/governance/canister/canister.rs
rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/proposal.rs
rs/sns/governance/src/request_impls.rs
rs/sns/governance/src/sns_upgrade.rs
rs/sns/governance/tests/fixtures/environment_fixture.rs
rs/sns/governance/tests/fixtures/mod.rs
rs/sns/governance/tests/governance.rs

This PR implements part of periodic task type A, which fetches the remaining upgrade steps from SNS-W.
This PR does not implement the part of periodic task type A that refreshes deployed_version when an upgrade triggered by a change to target_version is in progress.
This PR also implements a SnsGov.get_upgrade_journal endpoint, which will be used in the future to get all the info needed to audit SNS Upgrades, but for now will just be used to see the cached_upgrade_steps
Remaining work: Add a pocketic test
| [Next PR](https://github.com/dfinity/ic/pull/1854) >

feat(sns): Add periodic task for caching the upgrade steps

---

WORKSPACE.bazel
bazel/rules_haskell.patch

This patches our rules_haskell version to increase the timeout for the `make install` command installing GHC. The default of 10 minutes seems to be too short in some scenarios, though this has to be confirmed after the workaround has been in use for a couple of days. We will also need to investigate ways to avoid burning 10+minutes installing GHC.
See also: https://github.com/tweag/rules_haskell/issues/2254

fix(IDX): work around GHC install timeouts

---

rs/tests/driver/src/driver/nested.rs

We already write the addresses to a log file but not to the console. We should improve discoverability of this information by printing it to the console (IP addresses of other nodes are logged to the console during the test run).

test: Log GuestOS and HostOS IP address in nested tests

---

Cargo.lock
rs/nervous_system/agent/src/pocketic_impl.rs
rs/nervous_system/integration_tests/BUILD.bazel
rs/nervous_system/integration_tests/Cargo.toml
rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/advance_target_version.rs
rs/nervous_system/integration_tests/tests/sns_ledger_upgrade.rs
rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
rs/registry/admin/tests/integration_tests.rs

`block_on` in general is a bad practice imo - it constantly causes issues because it doesn't compose. A function called with block_on (or an async context) cannot call another function with block_on. This is not symmetrical with async - a sync function can call an async function using block_on, but an async function cannot call a sync function that uses block_on.
This is revelant to the the tests in ic-nervous-system-integration-tests because PocketIc in blocking mode (the default) uses block_on. This excludes the possibility of using it in an async context. 
For a concrete example, we can’t currently use sns-audit in integration tests since it must work with ic-agent (which is async). This means that any functions called from sns-audit must work in an async context. It would be very nice …

refactor(nervous-system): make the ic-nervous-system-integration-tests tests async

---

rs/tests/boundary_nodes/BUILD.bazel
rs/tests/consensus/BUILD.bazel
rs/tests/consensus/orchestrator/BUILD.bazel
rs/tests/consensus/subnet_recovery/BUILD.bazel
rs/tests/consensus/tecdsa/BUILD.bazel
rs/tests/consensus/upgrade/BUILD.bazel
rs/tests/financial_integrations/BUILD.bazel
rs/tests/message_routing/BUILD.bazel
rs/tests/message_routing/xnet/BUILD.bazel
rs/tests/nested/BUILD.bazel
rs/tests/networking/BUILD.bazel
rs/tests/testing_verification/BUILD.bazel

Farm is overloaded whenever the bazel-system-test-nightly workflow is running. It looks like this is causing this workflow to [fail often](https://github.com/dfinity/ic/actions/workflows/schedule-daily.yml?query=branch%3Amaster).
We have many system-tests that are configured to run both on hourly and nightly. To reduce load we remove the system-tests from nightly that are also configured to run hourly.
Additionally there were a number of nightly-only system-tests that use the `system_test_nns` macro which caused two variants of the test to run on nightly: one using the mainnet NNS and one using the HEAD NNS. This PR turns the latter tests into manual. We recognise this reduces test coverage so component teams have to review carefully if this trade-off is acceptable.

test(IDX): reduce nightly system-test load

---

ci/tools/repro-check.sh

Fix tabbing in error log (see hashes):
And remove success message that runs for unsuccessful runs

chore: correct tabbing on repro-check.sh error log

---

testnet/tools/lib.sh
testnet/tools/nns-tools/list-new-commits.sh
testnet/tools/nns-tools/submit-mainnet-nns-upgrade-proposal.sh

Instead of hiding uninteresting commits, simply color codes interesting versus non-interesting, as shown below:

feat(release-scripts): Output all commits to be released with colors

---

testnet/tools/nns-tools/lib/proposals.sh

This implements what I said in [this forum post]. Specifically, where I said
[this forum post]: https://forum.dfinity.org/t/nns-updates-2024-10-04/35846/8?u=daniel-wong
> I can re-introduce instructions into future proposal summaries.
Multiple people (in DFINITY and outside) complained about the removal of instructions, so I'm putting them back.
This partially reverts [pull request 1657]. Basically, this change just gets rid of the deletions in that PR.
[pull request 1657]: https://github.com/dfinity/ic/pull/1657
Minor change: link to separate detailed instructions is now locked to the same commit as the proposal itself.
Example output files are attached below. I plugged those files into a Markdown viewer, and it seemed alright to me. …

feat(nervous-system-tools): Reintroduce verification instructions.

---

rs/sns/governance/src/governance.rs

These were added for debugging and they were accidentally committed in #1788. This PR removes them

chore(sns): Remove accidentally-committed logs

---

rs/ethereum/ledger-suite-orchestrator/test_utils/src/flow.rs
rs/ledger_suite/tests/sm-tests/src/lib.rs
rs/ledger_suite/tests/sm-tests/src/metrics.rs
rs/nns/integration_tests/src/cycles_minting_canister_with_exchange_rate_canister.rs
rs/rosetta-api/tvl/sm-tests/src/lib.rs
rs/rosetta-api/tvl/tests/tests.rs

This PR removes `run_until_completion` from canister StateMachine tests since it is not required in the existing tests (this draft [PR](https://github.com/dfinity/ic/pull/1900) asserting that `run_until_completion` is a no-op is an empirical evidence of this claim). The motivation for removing `run_until_completion` from canister StateMachine tests is that this function is not supported in PocketIC and thus a blocker for migrating StateMachine tests to PocketIC.

chore: drop run_until_completion from canister tests

---

rs/pocket_ic_server/BUILD.bazel
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/Cargo.toml
rs/pocket_ic_server/src/state_api/routes.rs
rs/pocket_ic_server/tests/test.rs

This PR exposes the PocketIC topology at a new endpoint `/instances/<instance_id>/_/topology` so that the PocketIC topology can be retrieved via a PocketIC HTTP gateway that routes all requests starting with `/_/` to the PocketIC server directly, but could not route `/read/topology` to `/instances/<instance_id>/read/topology`.

feat(PocketIC): topology endpoint at /_/topology

---

.github/actions/bazel-test-all/action.yaml
.github/workflows-source/ci-main.yml
.github/workflows-source/release-testing.yml
.github/workflows/ci-main.yml
.github/workflows/release-testing.yml

Reduce complexity by removing `BAZEL_EXTRA_ARGS_RULES`. We also change the default of `BAZEL_EXTRA_ARGS`, so that we only explicitly mark tests with `--keep_going`.

refactor(IDX): remove BAZEL_EXTRA_ARGS_RULES

---

rs/tests/consensus/BUILD.bazel

Data shows this is the most frequent test on the critical path, hence moving it to hourly makes sense.

chore(IDX): tag backup_manager_test with system_test_hourly

---

rs/replica/src/setup_ic_stack.rs

Reverting https://github.com/dfinity/ic/pull/1924 since we need the feature builds for other purposes this week.
This PR enables the sync endpoint on all subnets except for the NNS subnet.

chore: enable sync v3 calls on all subnets except NNS subnet

---

ic-os/components/early-boot/setup-hostname/hostos/setup-hostname.sh
ic-os/docs/Configuration.adoc
ic-os/docs/README.adoc
rs/ic_os/network/src/interfaces.rs
rs/ic_os/network/src/mac_address.rs

A few minor refactoring changes pulled out of the new [icos config integration](https://github.com/dfinity/ic/pull/1563/files):
- [Update has_ipv6_connectivity ipv6_prefix_length reference](https://github.com/dfinity/ic/commit/403dfd2399cf10b1fa5dd96e5e6ff76506e8d6c0)
- [Remove unused hostname field from setup-hostname.sh](https://github.com/dfinity/ic/commit/12a9ea1938b9a3455743ae12865018185506a390)
- [Remove references to deleted ConfigStore-SetupOSHostOS documentation](https://github.com/dfinity/ic/commit/40030e65e5ef69c3b24b32a470d2117625ace345)
- [Add comment to get_ipmi_mac](https://github.com/dfinity/ic/pull/1937/commits/afbe77d9e5066cf5071420f072073d35d20bdd44)

refactor: miscellaneous icos refactoring and clean-up

---

rs/config/src/subnet_config.rs
rs/execution_environment/src/canister_manager/tests.rs
rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
rs/execution_environment/src/hypervisor/tests.rs
rs/test_utilities/execution_environment/src/lib.rs

This enables the storage reservation mechanism on verified application subnets. The storage reservation mechanism has been enabled for a while on application subnets and so it's time that this is enabled for verified application subnets as well. This helps bring closer the configuration between application and verified application subnets.

feat: EXC-1659: Enable storage reservation mechanism on verified application subnets

---

ic-os/components/ic/generate-replica-config.sh

This code is never triggered. A hostname is required for build-bootstrap-config-image.sh to succeed, which is what is used to generate the GuestOS config.

refactor: remove dead code in generate-replica-config.sh

---

rs/tests/driver/src/k8s/virtualmachine.rs

The rosetta system-tests need [ports 8100-8111](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/dfinity/ic%24+file:rs/tests/src/rosetta+PORT.*8&patternType=regexp&sm=0) open on the UVM running rosetta. So this PR opens them up on the k8s-based UVM.

fix(IDX): open up more rosetta ports in the k8s-based UVM to fix the rosetta systests

---

rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did

NNS Candid files used to be generated from proto files. Because of this the structurally identical `ProposalId` and `NeuronId` types go conflated into just `NeuronId`.
Now we no longer generate the Candid files from the proto files so we can fix the types.
1. Add `ProposalId` type in `governance.did` and `governance_test.did`.
2. Use `ProposalId` type where appropriate.
Not tested but the existing interface test should pass.

chore: Stop using NeuronId for proposal IDs

---

rs/ledger_suite/icp/ledger/BUILD.bazel
rs/ledger_suite/icp/ledger/Cargo.toml
rs/ledger_suite/icp/ledger/ledger_canisters.bzl
rs/ledger_suite/icp/ledger/src/main.rs
rs/ledger_suite/icp/ledger/tests/tests.rs
rs/ledger_suite/icp/src/lib.rs

- Introduced the `allowance` endpoint to the ICP ledger canister that fetches an allowance given `AccountIdentifier`s. It's only available in test wasm and not exposed through the candid interface.
- Refactored Bazel configuration by moving shared canister setup to `ledger_canisters.bzl`
- Added tests to make sure the new endpoint works if and only if it's running from a test wasm.

feat(ICP-Ledger): FI-1508 add test icp allowance getter endpoint

---

bazel/BUILD.bazel
bazel/conf/.bazelrc.build
ci/bazel-scripts/main.sh
ci/container/build-ic.sh
ic-os/components/BUILD.bazel
ic-os/components/setupos-scripts/check-setupos-age.sh
ic-os/components/setupos.bzl
ic-os/setupos/context/Dockerfile
ic-os/setupos/context/Dockerfile.base

Previously, we computed the build time when building the SetupOS base image. We're trying to move away from base images and want to be able to build the entire OS directly from source, therefore a new solution is required for reproducibility which does not take the current time into account. The new approach uses the commit timestamp.
In order to allow better caching of non-release builds, a new build flag `release_build` is introduced. Non-release builds use a constant commit time.
This approach assumes/requires that commits are fairly regular. We currently check that the build time (or commit time after this change) is not older than 6 weeks.

chore: Change how the build time is calculated

---

.github/workflows-source/ci-main.yml
.github/workflows-source/ci-pr-only.yml
.github/workflows-source/release-testing.yml
.github/workflows/ci-main.yml
.github/workflows/ci-pr-only.yml
.github/workflows/container-autobuild.yml
.github/workflows/container-base-images.yml
.github/workflows/release-testing.yml

This simplifies the concurrency logic. The fallback to `github.run_id` is not really needed - the only scenarios where this would happen is for scheduled jobs or manually triggered jobs and concurrency rules shouldn't be necessary there.

chore(IDX): update concurrency logic

---

.gitignore

Exclude bazel's `profile.json` from version control. The profiling dump is generated by bazel when profiling is explicitly enabled in `.bazelrc` or on-demand. We enable it when improving the build system from time to time.

chore: add bazel profile.json to .gitignore

---

.github/workflows-source/ci-main.yml
.github/workflows-source/ci-pr-only.yml
.github/workflows-source/release-testing.yml
.github/workflows/ci-main.yml
.github/workflows/ci-pr-only.yml
.github/workflows/container-autobuild.yml
.github/workflows/container-base-images.yml
.github/workflows/release-testing.yml

This didn't work as expected so I'll revert this and look at it again.
This reverts commit ab3378422a388faacafe9106071355a52c7c0f71.

revert(IDX): "chore(IDX): update concurrency logic (#1958)"

---

rs/nns/governance/src/lib.rs
rs/nns/governance/src/neuron_store.rs

Not that justification is needed for more stats, but there was already an analogous metric for stable memory.
Added headings to the `encode_metrics` function, because it's very long.
Moved a couple of metrics around so that they are under the right heading.
It would probably be easier to step through the commits in this PR. Otherwise, if you view all the changes at once, they will be all mixed together, and probably more confusing than just stepping through the commits.

feat(nns): Heap neuron count metric.

---

rs/bitcoin/kyt/btc_kyt_canister.did
rs/bitcoin/kyt/src/dashboard/tests.rs
rs/bitcoin/kyt/src/fetch.rs
rs/bitcoin/kyt/src/fetch/tests.rs
rs/bitcoin/kyt/src/lib.rs
rs/bitcoin/kyt/src/main.rs
rs/bitcoin/kyt/src/state.rs
rs/bitcoin/kyt/src/state/tests.rs
rs/bitcoin/kyt/src/types.rs
rs/bitcoin/kyt/tests/tests.rs

Instead of storing full transaction data in the state, we keep only relevant bits such as output addresses, and the previous output of inputs.
Also `InvalidTransaction` error is changed to `InvalidTransactionId`, and most `HttpGetTxError` are treated as retriable except `ResponseTooLarge`.

refactor(ckbtc): Do not store full transaction data in state

---

rs/state_machine_tests/src/lib.rs

This PR fixes the seed when deriving threshold keys in StateMachine tests so that the keys are stable.

chore: use fixed seed for threshold keys in SM tests

---

bazel/conf/.bazelrc.build

Previously we disabled the lockfile on `build` commands. However `bazel query` commands will also try to generate a lockfile, so instead we disable the lockfile on `common`, which is inherited by all bazel commands, not just build commands.

fix(IDX): disable lockfile for all bazel commands

---

ci/bazel-scripts/main.sh

This replaces the previous GitHub notice/annotation with a GitHub step summary, which supports Markdown and hence links. This makes it easier to find and open BuildBuddy links.

feat(IDX): show buildbuddy link as step summary

---

rs/tests/nested/BUILD.bazel

The nested tests are very unstable and cause the "Schedule Hourly" workflow to fail often. So let's disable them to give us time to debug why they fail in the context of: https://dfinity.atlassian.net/browse/NODE-1500

fix(NODE-1500): disable unstable //rs/tests/nested/... tests

---

packages/pocket-ic/src/lib.rs

This PR adds a version compatibility check into the PocketIC library so that users get a clear error message if they use an incompatible PocketIC server.

chore(PocketIC): version compatibility check in PocketIC library

---

rs/sns/integration_tests/src/lib.rs
rs/sns/integration_tests/src/timers.rs
rs/sns/swap/canister/canister.rs
rs/sns/swap/canister/swap.did
rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
rs/sns/swap/src/swap.rs
rs/sns/swap/tests/swap.rs

Now that the Swap canister's periodic tasks are migrated from heartbeats to timers, a theoretical risk can arise if a panic occurs during one of the timers' setup process. This could occur, e.g., if the Swap runs out of cycles during that code's execution. To be able to recover from such a situation, the NNS could already pass two proposals (one to publish a new Swap WASM, potentially identical to the one already installed, thereby creating a new step in the upgrade order; another one for triggering the Swap upgrade). However, it would be better if the SNS could recover itself. To that end, we add a new function for resetting Swap's timers, only callable by the SNS Governance. A follow-up PR will add an SNS proposal for calling this new function. 
< [Previous …

feat(sns): Add Swap.reset_timers

---

rs/tests/boundary_nodes/integration_test_common/src/lib.rs
rs/tests/boundary_nodes/performance_test_common/src/lib.rs

This PR addresses the [changed behavior of `hyper-util`](https://github.com/hyperium/hyper-util/commit/2639193e9134a235db42cca16c8cff7f21f61661) of using the port number if a non-zero number is specified instead of inferring it from the URL.

fix: set ports to 0 in BN system tests

---

rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/providers.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
rs/ethereum/cketh/minter/tests/cketh.rs
rs/ethereum/cketh/test_utils/src/flow.rs
rs/ethereum/cketh/test_utils/src/lib.rs
rs/ethereum/cketh/test_utils/src/mock.rs

Use a 3-out-of 4 consensus strategy when querying the EVM RPC canister to avoid a provider being able to block the ckETH minter.

feat(cketh): threshold consensus strategy for HTTPs outcalls

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/lib.rs
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/state_api/routes.rs
rs/pocket_ic_server/tests/test.rs

This PR adds support for loading subnet state from a state dir for every subnet kind and subnet id.
The motivation for this PR is a planned migration of StateMachine tests to PocketIC.

feat(PocketIC): support for loading subnet state from state dir for every subnet

---

rs/pocket_ic_server/src/pocket_ic.rs

Because the PocketIC operation to fetch topology is also expected to be called by IC agents that don't expect to retry the operation if the PocketIC instance is busy, we need to retry in PocketIC.

fix(PocketIC): retry topology operation if the instance is busy

---

rs/rosetta-api/icp/tests/system_tests/common/system_test_environment.rs

In an attempt to fix some flakiness, advance the time of `tick()` to give the governance canister some time to initialize, before making the `PocketIC` instance live for the rest of the test.

test(icp_rosetta): FI-1526: Give governance canister some time to initialize

---

.github/workflows/slack-workflow-run.yml

In an effort to reduce the noise on our slack channels, this changes the logic to stop posting success messages to slack, since they are not actionable. However, I needed to update the logic a little to get it to work and keep it clear.

chore(IDX): dont post success messages to slack

---

MODULE.bazel
WORKSPACE.bazel

This removes a couple of Bazel dependencies that were duplicated between the WORKSPACE and the MODULE bazel files. These slipped through during rebase. There was also a bit of copypasta in a comment.

fix(IDX): Clean up WORKSPACE

---

packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs
packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/tests/test.rs

This PR makes the PocketIC library build on Windows by using the test driver's process ID instead of its parent process ID.

chore(PocketIC): use test driver's pid instead of parent pid

---

rs/nervous_system/integration_tests/tests/advance_target_version.rs

This PR changes the get_upgrade_journal test to simulate upgrades to root rather than Ledger. Root is a better candidate for testing against at this stage of the development of the effortless SNS upgrades feature, because it can be updated by Governance directly rather than needing to go through root like every other canister (except swap). Of course, it will need to be tested against all canisters eventually, but for now root seems like a good choice

refactor(tests): Attempt to upgrade root in test_get_upgrade_journal

---

rs/sns/swap/src/swap.rs

This is to aid debugging in situations such as this one: https://forum.dfinity.org/t/dapp-canisters-control-not-returned/36125/5

chore(sns): Add swap logs when changing controllership

---

ic-os/components/ic/setup-permissions/setup-permissions.sh

Reverts dfinity/ic#1906
If the commands aren't ran recursively, it seems that everything under `/var/lib/ic/backup/` will be owned by user `ic-http-adapter` and group `backup` instead after an upgrade. This means the replica can no longer write backup files.

revert: "perf: NODE-1499 Don't recursively fix permissions of the `backup` directory after reboots"

---

MODULE.bazel
WORKSPACE.bazel

This bumps `rules_distroless` to a version contained in the [bazel central registry](https://registry.bazel.build/modules/rules_distroless) and ports them from our WORKSPACE to our MODULE.
This involves a slight change in the API (was `deb_index`, now `apt.install`) but overall very small change.

feat(IDX): port rules_distroless to MODULE.bazel

---

.github/CODEOWNERS
rs/tests/dashboards/IC/bitcoin.json

This PR updates Bitcoin grafana testnet dashboard to match prod dashboard.
It also adds execution team as a co-owner of this dashboard.

chore: update bitcoin testnet dashboard to match prod

---

WORKSPACE.bazel

The motoko base archive is not being used in the Bazel build.

fix(IDX): remove unused motoko base

---

Cargo.toml

This removes the `feature` (without `s`) specified for the `cloudflare` crate. `feature` is not a valid key. The `rustls-tls` feature does not seem to be necessary.

fix(IDX): remove unused Cargo.toml cloudflare key

---

WORKSPACE.bazel
rs/embedders/BUILD.bazel
rs/embedders/tests/spec_tests.rs

This changes the embedders spec tests to use environment variables (set in `BUILD.bazel`) to specify the path to the wasm spec files.
This ensures that the tests do not depend on Bazel paths like `external/` and (more theoretically than practically) will make the tests run only if a file specifically depended on changes.

feat(IDX): use env vars for embedders test deps

---

.github/workflows/slack-workflow-run.yml

Now that we are only notified of failures, we can add `Schedule Hourly` as well.

chore(IDX): notify for schedule hourly

---

packages/pocket-ic/BUILD.bazel

This PR increases the PocketIC library test resources to address its timeouts:
- the size of the test is now medium;
- the CPU count of the test is 8.

chore(PocketIC): increase PocketIC library test resources

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

We see occasional timeouts for `bazel-test-macos-intel` so bump by 10 min.

chore(IDX): bump timeout for macos tests

---

ic-os/components/ic/generate-replica-config.sh
ic-os/components/ic/ic.json5.template
rs/orchestrator/src/firewall.rs
rs/tests/driver/src/util.rs

move default query_stats_aggregation field from generate-replica-config.sh to ic.json.template (where hard-coded values should be)

refactor: remove default query_stats_aggregation field

---

rs/nns/test_utils/src/registry.rs
rs/orchestrator/src/firewall.rs
rs/orchestrator/src/registration.rs
rs/prep/src/node.rs
rs/protobuf/def/registry/node/v1/node.proto
rs/protobuf/src/gen/registry/registry.node.v1.rs
rs/protobuf/src/registry/node.rs
rs/registry/canister/api/src/lib.rs
rs/registry/canister/canister/registry.did
rs/registry/canister/src/invariants/endpoint.rs
rs/registry/canister/src/invariants/firewall.rs
rs/registry/canister/src/mutations/node_management/do_add_node.rs
rs/registry/canister/tests/add_node.rs
rs/registry/helpers/src/firewall.rs
rs/state_machine_tests/src/lib.rs

This adds support for node_reward_type to NodeRecord and to AddNodePayload.
It adds it as a string to AddNodePayload, but as an enum with validation to NodeRecord.

feat(registry): Add node_reward_type to NodeRecord

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/neuron_store/benches.rs
rs/nns/governance/src/storage/neurons.rs
rs/nns/governance/src/storage/neurons/neurons_tests.rs

When scanning neurons in the main StableBTreeMap, instead of doing a separate traversal of the auxiliary StableBTreeMaps for EACH neuron in the result set, ranges of each auxiliary StableBTreeMap are used (and scanned in parallel).
This gets around a 40% performance improvement.
This method, while not currently extensively used, will be used more after the migration of neurons to stable storage.
Benchmark results before the change:
```
// Output from benchmark test
Benchmark: range_neurons_performance
total:
instructions: 47.07 M (improved by 41.47%)
heap_increase: 0 pages (no change)
stable_memory_increase: 0 pages (no change)
```
```
range_neurons_performance:
total:
instructions: 80415437
heap_increase: 0
stable_memory_increase: 0
scopes: {}
```
After the change (what's in PR):
``` …
```

refactor(nns): Improve range neurons performance for stable store

---

rs/consensus/src/consensus/batch_delivery.rs
rs/consensus/src/consensus/finalizer.rs
rs/consensus/src/dkg.rs
rs/consensus/src/dkg/payload_builder.rs
rs/protobuf/def/types/v1/dkg.proto
rs/protobuf/src/gen/types/types.v1.rs
rs/types/types/src/consensus/dkg.rs

This field is not only used to store NiDKG transcripts for *new* subnets that are being created, but also existing subnets that are being recovered. In the future it will additionally be used to hold transcripts for subnets requesting a vet Key resharing.

chore: CON-1415 Rename `transcripts_for_new_subnets_with_callback_ids`

---

mainnet-canisters.json
rs/ledger_suite/icp/ledger/tests/tests.rs
rs/ledger_suite/icrc1/ledger/tests/tests.rs
rs/ledger_suite/tests/sm-tests/src/lib.rs

This PR updates the pinned versions of mainnet NNS and SNS canisters after the last release cycle.
Swap: https://dashboard.internetcomputer.org/proposal/133383
SNS Governance: https://dashboard.internetcomputer.org/proposal/133384
SNS-W: https://dashboard.internetcomputer.org/proposal/133387
NNS Root: https://dashboard.internetcomputer.org/proposal/133386
NNS Governance: https://dashboard.internetcomputer.org/proposal/133385
Cycles Minting Canister: https://dashboard.internetcomputer.org/proposal/133311

chore: Update mainnet-canisters.json

---

rs/tests/consensus/subnet_recovery/BUILD.bazel
rs/tests/message_routing/xnet/BUILD.bazel

The release-testing workflow is very expensive in terms of vCPUs needed for testnet VMs:
This actually prevents us from running concurrent release-testing workflows. To help reduce resources a bit we disable a few test variants that run the test against the HEAD NNS canisters, namely:
* `//rs/tests/consensus/subnet_recovery:sr_app_large_with_tecdsa_test_head_nns`
* `//rs/tests/message_routing/xnet:xnet_slo_120_subnets_staging_test_head_nns`
They will now only be tested using the mainnet NNS canisters.

test(IDX): skip some tests using the HEAD NNS canisters to save resources

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.toml
bazel/external_crates.bzl
rs/bitcoin/ckbtc/minter/Cargo.toml

It is fairly discouraged to pin to particular version.
> Multiple versions within the same compatibility range are not allowed and will result in a resolver error if it is constrained to two different versions within a compatibility range. For example, if there are two packages in the resolve graph with the following requirements:
https://doc.rust-lang.org/cargo/reference/resolver.html

chore: do not pin to crate versions

---

rs/limits/src/lib.rs
rs/prep/src/subnet_configuration.rs

This constant is used only in system tests. In production the initial notary delay will be updated to the new value for the NNS subnet in few weeks. Let's start running our tests with the new value before that.

chore: remove the INITIAL_NOTARY_DELAY_NNS_SUBNET constant

---

Cargo.lock
mainnet-canisters.json
rs/sns/integration_tests/BUILD.bazel
rs/sns/integration_tests/Cargo.toml
rs/sns/integration_tests/src/golden_state_swap_upgrade_twice.rs
rs/sns/integration_tests/src/lib.rs
rs/sns/swap/canister/canister.rs
rs/sns/swap/src/swap.rs

The PR adds a simple data migration for old Swap canisters that still don't have the fields direct_participation_icp_e8s, neurons_fund_participation_icp_e8s. Additionally, we add golden upgrade tests to check that this migration works as expected in production.

feat(sns): Data migration that retrofits Swap.{direct_participation_icp_e8s, neurons_fund_participation_icp_e8s} + golden upgrade tests 

---

packages/pocket-ic/tests/tests.rs

This PR optimizes the network bandwidth in PocketIC tests by reducing the size of an overly large update call from 16MB to a bit over 2MiB which already exceeds the limit.

chore(PocketIC): reduce PocketIC test network bandwidth

---

rs/pocket_ic_server/src/state_api/routes.rs
rs/pocket_ic_server/src/state_api/state.rs

Pruning OpOut values in the PocketIC state graph could lead to test timeouts because a different operation might depend on the pruned OpOut:
- instance 0 starts op_id OP from state label SL
- instance 0 times out op_id OP from state label SL
- instance 1 starts op_id OP from state label SL
- library polls for the result of op_id OP from state label SL (instance 0) and gets NOT FOUND
- instance 1 finishes op_id OP from state label SL and writes result to graph
- instance 0 finishes op_id OP from state label SL and writes result to graph (computations are deterministic and thus the same result is written)
- instance 1 prunes the result of op_id OP from state label SL in the graph (because instance 1 finished the operation quickly)
- library polls for the result of op_id OP from state label …

fix(PocketIC): do not prune OpOut in graph

---

rs/pocket_ic_server/BUILD.bazel

This ensures that the pocket IC server tests don't rely on implicit bazel dependencies (`external/foo`) and simplifies some labels (to use local targets without the workspace root).

fix(IDX): clean up pocket_ic_server bazel deps

---

rs/pocket_ic_server/tests/test.rs

This PR retries calls to the `/api/v3/.../call` endpoint in PocketIC tests until `CallResponse::Response` is produced. At the moment, the test fails if a (single) call to that endpoint does not produce `CallResponse::Response` which makes the test flaky.

chore(PocketIC): retry /api/v3 calls in PocketIC tests

---

.github/workflows-source/ci-main.yml
.github/workflows-source/ci-pr-only.yml
.github/workflows/ci-main.yml
.github/workflows/ci-pr-only.yml

Permissions are set to `read-all` by default, so this is unnecessary and only causes confusion.

chore(IDX): remove read-all permissions

---

rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/scheduler_metrics.rs
rs/execution_environment/src/scheduler/tests.rs
rs/tests/dashboards/IC/execution-metrics.json

Change the per-message metrics to not count messages that fail to prepay for execution. Instead add a separate counter which increments each time a scheduled messages fails to actually execute anything.
Fixes EXC-1755.

fix(EXC-1755): Fail prepay metric

---

rs/ethereum/cketh/minter/BUILD.bazel

The `principal_to_bytes` test uses the deprecated
[closure](https://github.com/google/closure-library) framework. The `rules_closure` are causing flakiness in our Bazel build.
Because the `principal_to_bytes` code is rarely (if ever) changed we temporarily disable the tests, until a better solution is found.

chore(IDX): disable closure tests

---

rs/cross-chain/proposal-cli/src/candid/tests.rs
rs/cross-chain/proposal-cli/src/canister/mod.rs
rs/cross-chain/proposal-cli/src/git/mod.rs
rs/cross-chain/proposal-cli/src/main.rs
rs/cross-chain/proposal-cli/src/proposal/mod.rs
rs/cross-chain/proposal-cli/templates/install.md
rs/cross-chain/proposal-cli/templates/upgrade.md

Add support to the `proposal-cli` CLI tool for canisters outside the IC repository, such as the EVM RPC canister.

feat(proposal-cli): Support canisters outside the IC repository

---

rs/sns/integration_tests/BUILD.bazel

test(sns): Run `golden_state_swap_upgrade_twice` on nightly CI pipelines

---

rs/tests/src/message_routing/compatibility.rs

For some reason the replica upgrades got very slow over the last week, which is making a lot more messages fail in the XNet compatibility test. Bump the threshold up until we can figure out what's causing the upgrade slowdown.

chore(MR): bump the XNet compatibility test failure threshold

---

bazel/conf/.bazelrc.internal

Use `--build_event_binary_file=bazel-bep.pb --profile=profile.json` in CI only. Users that are manually running `bazel test --config=systest //<whatever>` implicitly end up having these files generated and that is not needed.

chore(IDX): bazelrc update

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
WORKSPACE.bazel
bazel/external_crates.bzl
rs/ethereum/cketh/test_utils/Cargo.toml
rs/ethereum/cketh/test_utils/src/evm_rpc_provider.rs
rs/ethereum/evm-rpc-client/Cargo.toml

Update the EVM RPC client to use [v2.2.0](https://github.com/internet-computer-protocol/evm-rpc-canister/releases/tag/v2.2.0).

feat(cketh): use EVM RPC canister v2.2.0

---

rs/recovery/src/app_subnet_recovery.rs
rs/recovery/src/cli.rs
rs/recovery/src/error.rs
rs/recovery/src/lib.rs
rs/recovery/src/nns_recovery_failover_nodes.rs
rs/recovery/src/nns_recovery_same_nodes.rs
rs/recovery/src/recovery_state.rs

Added a suggestion for errors during creation of the recovery directory folders. 
I also tried to make the fatal recovery errors more readable. Comparison:
**Before**:
**After**:

chore(recovery): Improve error messages 

---

rs/tests/boundary_nodes/BUILD.bazel
rs/tests/driver/src/driver/asset_canister.rs

This updates some boundary node tests to use an asset canister provided through environment variable. This avoids the tests relying on bazel implementation details (`external/`).

fix(IDX): specify asset canister path via env

---

ci/scripts/bazel-coverage.sh

Excluding problematic target (see https://github.com/dfinity/ic/pull/2103) to not degrade success rate of hourly workflow.

chore(IDX): exclude problematic target

---

ic-os/components/selinux/node_exporter/node_exporter.te

Give prometheus `node_exporter` more read access to device info:
* Allow reading udev state data from /run/udev/data
* Allow reading /proc/pressure
* Allow reading under mount points with mnt_t
(NODE-1498)

fix(NODE-1498): allow read access to more hardware info for node_exporter

---

ic-os/components/hostos-scripts/generate-guestos-config/dev-generate-guestos-config.sh

In this commit (https://github.com/dfinity/ic/pull/1970) we updated the nns_urls references but missed dev-generate-guestos-config, causing test bare-metal-deployments to fail

fix: nns_urls reference in dev-generate-guestos-config

---

ic-os/components/ic/setup-permissions/setup-permissions.sh

During recoveries, we are logged in as admin and operate in a working directory (by default we pick `/var/lib/ic/data/recovery`). Right now we need to create that manually with sudo mkdir & chown before starting the recovery tool.
Having an existing directory at `/var/lib/ic/data/recovery` with `admin` permissions helps simplify recovery, because the operator doesn't need to remember to create the directory beforehand.

fix(recovery): Set up empty recovery directory in guestOS

---

Cargo.lock
packages/pocket-ic/Cargo.toml
packages/pocket-ic/src/lib.rs
packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/main.rs
rs/pocket_ic_server/tests/test.rs

This PR makes canister tests using the PocketIC library run seamlessly on Windows:
- this PR removes the CLI option `--pid` of the PocketIC server and makes the CLI option `--port-file` behave like `--pid`: only one PocketIC server process listens at a port and writes that port to the specified port file. This change was necessary because the (implicit) port file created using `--pid` in a WSL temporary directory cannot be read from a native Windows `cargo test` invokation;
- this PR disables doc tests of the PocketIC library since they fail on both Linux and Windows at the moment.
This PR has been tested manually by running `cargo test -p pocket-ic` on a Windows laptop. It is not possible to have a CI test on a Windows runner because they only support WSLv1, but WSLv2 is required (see …

feat(PocketIC): make PocketIC library run on Windows seamlessly

---

Cargo.lock
packages/pocket-ic/BUILD.bazel
packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/Cargo.toml
packages/pocket-ic/HOWTO.md
packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/management_canister.rs
packages/pocket-ic/src/nonblocking.rs
packages/pocket-ic/tests/tests.rs

This PR introduces a PocketIC library module containing management canister types to avoid a dependency on the Rust CDK. This is useful to allow canister developers bump their Rust CDK version independently of their PocketIC library version. The names of the management canister types follow the names in the management canister candid interface.

feat(PocketIC): management canister types module

---

rs/tests/message_routing/BUILD.bazel

The `global_reboot_test` has a P90 of 5m and 5s so it has to move off of PRs and into long_tests. See the 
[GitHub IC Bazel PR+MG Stats](https://superset.idx.dfinity.network/superset/dashboard/7/) dashboard:

test(IDX): move the global_reboot_test to long_tests

---

rs/ethereum/cketh/minter/cketh_minter.did
rs/ethereum/cketh/minter/src/endpoints.rs
rs/ethereum/cketh/minter/src/main.rs
rs/ethereum/cketh/minter/tests/ckerc20.rs
rs/ethereum/cketh/minter/tests/cketh.rs

For debugging purposes and transparency reasons, returns the canister ID of the EVM RPC canister used to interact with Ethereum as part of `MinterInfo`, in case the minter does not issue the HTTPs outcalls itself.

feat(cketh): add EVM RPC canister ID to the minter info endpoint

---

Cargo.lock
rs/https_outcalls/adapter/BUILD.bazel
rs/https_outcalls/adapter/Cargo.toml
rs/https_outcalls/adapter/src/rpc_server.rs
rs/https_outcalls/adapter/tests/server_test.rs

This reverts commit c831d22abbf10bd37c15669b4c77579f40106e3d.
Manually triggered tests are failing after this feature, and were not caught on CI. Reverting for now to not block other PRs.

revert: "feat(https-outcalls): Enable H/2 support for outcalls (#2142)"

---

ic-os/components/init/bootstrap-ic-node/bootstrap-ic-node.sh

With the switch from the HTTP- to the ALPN-ACME challenge, we need to cleanup the pre-existing certificates.

fix: add a temporary measure to remove existing API BN certs

---

README.adoc
ci/tools/repro-check.sh

- Introduce `--guestos`, `--hostos`, and `--setupos` flags to allow selective verification of specific OS components.
- By default, the script verifies all components (GuestOS, HostOS, SetupOS), maintaining the original behavior.
- Adjusted download and verification logic to check only the selected OS components based on the provided flags.
- Updated the `print_usage` instructions to reflect the new flag options.
- Updated `README.adoc` to clarify the verification process for `IC-OS Version Elect` proposals and add instructions for verifying HostOS and SetupOS images.
- Adjusted RAM check logic in `repro-check.sh` to ensure accurate reporting of system memory.

feat(repro-check): add support for component-specific verification flags

---

rs/pocket_ic_server/src/state_api/routes.rs
rs/pocket_ic_server/src/state_api/state.rs

This PR
- prevents deadlocks when acquiring locks in conflicting orders in `ApiState` by having a single lock for instances;
- makes sure locks are not leaked in the public API of `ApiState`;
- makes sure that no read lock to instances needs to be acquired while another read lock to instances is being held.
In particular, the last point prevents deadlocks of the following form:
- a read lock RL1 to instances is acquired;
- a write lock WL1 to instances is requested (at this point, `tokio::sync::RwLock` blocks every subsequent read lock request until this write lock can be acquired, at least until RL1 is released);
- a read lock RL2 to instances is requested (blocks due to WL1 being requested already) and RL1 is not released until RL2 is acquired => deadlock.

fix(PocketIC): fix deadlock

---

rs/sns/integration_tests/src/golden_state_swap_upgrade_twice.rs
rs/sns/swap/src/swap.rs

This PR ensures that very old swaps that were finalized manually (as opposed to automatically) do not require periodic tasks.
Regression testing included.

feat(sns): Make very old swaps not require periodic tasks

---

WORKSPACE.bazel
bazel/rules_rust.patch

This is a patch for `rules_rust` to work around some build determinism issues in the `proc-macro2` Bazel build.
For more information, see:
* https://github.com/dtolnay/proc-macro2/issues/473
* https://github.com/bazelbuild/rules_rust/issues/2952

fix(IDX): work around proc-macro2 non-determinism

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
bazel/external_crates.bzl
rs/pocket_ic_server/Cargo.toml

This removes the old axum dep from the workspace

chore: upgrade aide

---

rs/ethereum/cketh/minter/DepositHelperWithSubaccount.sol

([XC-218](https://dfinity.atlassian.net/browse/XC-218)): Add a new Solidity helper smart contract for both ETH and ERC-20 deposits to support subaccounts. The contract is deployed on Sepolia at [`0x11d7c426EEdC044b21066d2BE9480D4b99E7cC1a`](https://sepolia.etherscan.io/address/0x11d7c426eedc044b21066d2be9480d4b99e7cc1a).
Examples of events:
1. [Example](https://sepolia.etherscan.io/tx/0x12213b78a743d45a868f0eca5da62a28ed8e6578cd63b1986a23f63e6089a5c3#eventlog) of ReceivedEth event with subaccount. 
2. [Example](https://sepolia.etherscan.io/tx/0x54b59e673d03d2313f77fbe3837e599cf47d51de007e08a18494189a2243f5dd#eventlog) of ReceivedErc20 with subaccount
[XC-218]: https://dfinity.atlassian.net/browse/XC-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

feat(cketh/ckerc20): add helper smart contract supporting Subaccounts

---

rs/execution_environment/benches/scheduler.rs
rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/round_schedule.rs
rs/execution_environment/src/scheduler/tests.rs

This change applies charges for each fully executed canister. The total amount of points charged is evenly distributed across canisters, but it is not included in the compute capacity used to calculate long/new execution cores.
This PR is a cherry-pick of previously reverted https://github.com/dfinity/ic/pull/1782

feat: EXC-1735: Charge active canisters for full execution

---

rs/config/src/embedders.rs

This reverts commit 75c57bc48ef317ce5ded8c68bdb0296d63fd6008.
As canister executions increase, it's essential to maintain more spawned sandboxes to accelerate sandbox executions. While the original change reduced memory usage to switch to the memory-based allocator, production metrics indicate minimal risk.

revert: "feat(RUN-1013): Adjust max number of cached sandboxes"

---

rs/tests/consensus/BUILD.bazel

`//rs/tests/consensus:dual_workload_test` is currently our most flaky test on PRs. What all flakes have in common is that the testnet is deployed in `se1` while the driver is running in `zh1` causing cross Atlantic traffic. What we then see is that some calls the `http://[$ip]:8080/api/v3/canister/$id/call` time out.
We can potentially fix this by running the test in colocated mode such that the driver and testnet are located on the same host or DC.

test(IDX): run //rs/tests/consensus:dual_workload_test in colocated mode to reduce flakiness

---

Cargo.lock
rs/tests/httpbin-rs/src/main.rs
rs/tests/networking/BUILD.bazel
rs/tests/networking/Cargo.toml
rs/tests/networking/canister_http_correctness_test.rs

This PR:
- Refactors all https correctness tests to give diagnostics on what failed for each test case.
- Removes an unsafe unwrap of host name in teh http bin server, used for testing. The host name header is not used in http/2, causing the server to crash, which failed the system tests when we enable http/2 for outcalls

chore: Fix http server used by system tests

---

rs/orchestrator/src/firewall.rs
rs/tests/driver/src/util.rs

`nns_url` was updated to `nns_urls` in ic.json.template here: https://github.com/dfinity/ic/pull/1970
But these two references were missed.

fix: update ic.json5 nns_urls references

---

rs/recovery/src/app_subnet_recovery.rs
rs/recovery/src/file_sync_helper.rs
rs/recovery/subnet_splitting/src/subnet_splitting.rs

To avoid confusion during recovery, we now print the expected key format.

fix(recovery): [CON-1405] Print example of expected ssh key format during recovery

---

rs/nns/handlers/root/impl/tests/test_change_canister_controllers.rs
rs/nns/handlers/root/impl/tests/test_open_calls_tracking.rs
rs/nns/integration_tests/src/canister_playground.rs
rs/nns/integration_tests/src/cycles_minting_canister.rs
rs/nns/integration_tests/src/governance_upgrade.rs
rs/nns/integration_tests/src/lifeline.rs
rs/nns/integration_tests/src/node_provider_remuneration.rs
rs/nns/integration_tests/src/reset_root.rs
rs/nns/sns-wasm/tests/common/mod.rs
rs/nns/sns-wasm/tests/deploy_new_sns.rs
rs/nns/sns-wasm/tests/upgrade_sns_instance.rs
rs/nns/test_utils/src/sns_wasm.rs
rs/nns/test_utils/src/state_test_helpers.rs
rs/sns/integration_tests/src/root.rs

This removes  simplifies the usage of a method to no longer require witnesses (but instead always just use candid encoders/decoders), as there are no instances of using it in any other way.  Moves us closer to removing dependency on dfn_candid.

refactor(nns): Remove dfn_candid from test_utils, simplify method

---

Cargo.lock
rs/https_outcalls/adapter/BUILD.bazel
rs/https_outcalls/adapter/Cargo.toml
rs/https_outcalls/adapter/src/rpc_server.rs
rs/https_outcalls/adapter/tests/server_test.rs

This reverts commit 4e666d720a90d3b9f08d7f72d771bcb5f0c43afd.
We initially reverted the http2 outcalls as `canister_http_correctness_test` was failing on the hourly system test. The problem was due to a bug in the test server, and was fixed in https://github.com/dfinity/ic/pull/2190. We can therefor re-enable the http/2 functionality for HTTPS outcalls.

feat(https-outcalls): re-enable H/2 support for outcalls

---

rs/nervous_system/proto/proto/ic_nervous_system/pb/v1/nervous_system.proto
rs/nervous_system/proto/src/gen/ic_nervous_system.pb.v1.rs
rs/sns/integration_tests/src/golden_state_swap_upgrade_twice.rs
rs/sns/integration_tests/src/timers.rs
rs/sns/swap/canister/canister.rs
rs/sns/swap/canister/swap.did
rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs

This PR moves some timer-related API types into the `ic_nervous_system` crate, as three different SNS canisters would benefit from using the same types to reset their timers and read timer-related metadata. As the first step, only Swap is adjusted to refer to the common types in this PR. To make the timer-related APIs uniform, we add `Swap.get_timers`, despite this information also being available via `Swap.get_state`.
| [Next PR](https://github.com/dfinity/ic/pull/2211) >

feat(sns): Refactor API types related to managing timers

---

rs/ethereum/cketh/minter/DepositHelperWithSubaccount.sol
rs/ethereum/cketh/minter/cketh_minter.did
rs/ethereum/cketh/minter/src/dashboard/tests.rs
rs/ethereum/cketh/minter/src/deposit.rs
rs/ethereum/cketh/minter/src/endpoints.rs
rs/ethereum/cketh/minter/src/eth_logs/mod.rs
rs/ethereum/cketh/minter/src/eth_logs/tests.rs
rs/ethereum/cketh/minter/src/main.rs
rs/ethereum/cketh/minter/src/memo/tests.rs
rs/ethereum/cketh/minter/src/state/audit/tests.rs
rs/ethereum/cketh/minter/src/state/tests.rs
rs/ethereum/cketh/minter/src/tests.rs
rs/ethereum/cketh/minter/tests/ckerc20.rs
rs/ethereum/cketh/test_utils/src/ckerc20.rs
rs/ethereum/cketh/test_utils/src/flow.rs

Parse deposit events originating from the smart contract introduced in #2143, which additionally contain an optional ledger subaccount. The events from that smart contract are not yet scraped, which will be done in a follow-up PR.

feat(cketh/ckerc20): Deposit events with subaccounts

---

ic-os/setupos/config/config.ini

For manual testnet deployments from setupos, use the current zh2 test machine prefixes as defaults to make it easier.

fix(setupos): update default ipv6 prefix and gw for setupos testnets

---

ci/container/build-ic.sh

This will avoid https://dfinity.atlassian.net/browse/NODE-1510 when reproducing builds, until we have a better solution to avoid caching this commit time.

fix: [NODE-1510] Clean cache in repro script

---

ic-os/dev-tools/bare_metal_deployment/deploy.py

deploy.py incorrectly determines the number of times to call iterate_func. The for loop assumes iterate_func will take 5 seconds, but the connectivity check actually fails faster than 5 seconds, causing the whole loop to typically run for just ~15 minutes.
Summary of changes:
* Change the success-check loop to run for the desired wait time
* I also *lowered* the DEFAULT_SETUPOS_WAIT_TIME_MINS to 20 minutes. 
* SetupOS is pretty reliably installing in less than 15 minutes. I only hit this issue by chance, which is why we didn’t see it until now. So I figured we could lower the labeled wait time from 25 to 20 minutes
* Remove unused parse_from_rows function

fix: bare_metal_deployment timeout

---

rs/types/types/src/lib.rs
rs/types/types/src/state_sync.rs

`cargo check` intermittently fails to build with `strum::EnumIter` as a derive macro, switch to `strum_derive::EnumIter`.

chore: Fix intermittent `cargo check` errors

---

rs/boundary_node/ic_boundary/README.md

The README was outdated and included some options that have been removed. Now,

chore: update ic-boundary README

---

ci/src/artifacts/upload.bash.template

Disabling verbose logs as we don't have any issues with deterministic builds where logs benefit the root cause analysis.

chore(IDX): disable verbose rclone logs

---

rs/consensus/src/consensus.rs

The combination of 3 seconds refresh period and [LOOK_AHEAD](https://sourcegraph.com/github.com/dfinity/ic/-/blob/rs/consensus/src/idkg.rs?L236) being set to 10 heights, means that a node which is lagging behind the other nodes, will catch up at the rate at most `LOOK_AHEAD / REFRESH_PERIOD = 10 / 3 = 3.(3)` blocks per second. Since the notary delay is now set to `0.3s`, some subnets achieve up to `2.5` blocks per second finalization rate, which is not that far away from the maximum achievable catch up rate.
Reducing the refresh period to `1s` means that in theory we could catch up 10 blocks per second.
Note that computing the bouncer function is very fast- 0.0002s on average according to `consensus_bouncer_update_duration` metric.

feat(consensus): reduce consensus bouncer function refresh period from 3 seconds to 1 second.

---

rs/registry/transport/src/lib.rs

When the error field is populated, deserialize_get_changes_since_response now returns Err.
Whereas, before, the only time it returned Err is when deserialization itself failed, not when the message is properly encoded, but bears information about an error (such as authorization fail).

fix(registry): Do not ignore the error field in get_changes_since response.

---

Cargo.lock
rs/canister_sandbox/BUILD.bazel
rs/canister_sandbox/Cargo.toml
rs/canister_sandbox/src/replica_controller/sandbox_process_eviction.rs
rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
rs/config/src/embedders.rs
rs/pocket_ic_server/src/pocket_ic.rs

This allows to increase the number of sandbox processes without risking the OOM as the total RSS size of sandboxes is still limited.
This PR also increases the number of sandbox processes to 5k.

feat: EXC-1758: Evict sandboxes based on their RSS

---

rs/ledger_suite/icp/index/BUILD.bazel
rs/ledger_suite/icp/ledger/BUILD.bazel

Set a limit on the number of threads used to run a couple of flaky ICP ledger and index tests.

test(ICP_ledger): FI-1506: Thread limit in flaky ICP ledger and index tests

---

rs/tests/testing_verification/spec_compliance/spec_compliance.rs
rs/tests/testing_verification/spec_compliance_application_subnet_test.rs
rs/tests/testing_verification/spec_compliance_group_01_application_subnet_test.rs
rs/tests/testing_verification/spec_compliance_group_01_system_subnet_test.rs
rs/tests/testing_verification/spec_compliance_group_02_system_subnet_test.rs
rs/tests/testing_verification/spec_compliance_system_subnet_test.rs

This shaves of about 30 seconds from the `//rs/tests/testing_verification:spec_compliance_...` system-tests by deploying the Boundary Node, httpbin UVM and IC concurrently instead of in sequence.
spec_compliance test run: https://github.com/dfinity/ic/actions/runs/11498495840.

test(IDX): parallelise the spec_compliance setup functions

---

MODULE.bazel

In the past, there were some official docker images (for `static-file-server` and `jaeger`) that we could not pull using `rules_oci`.
The issue seems to have been fixed in Bazel 7.
See: https://github.com/bazel-contrib/rules_oci/issues/695

fix(IDX): use official docker images

---

rs/config/src/execution_environment.rs
rs/execution_environment/tests/canister_logging.rs

This PR enables `allowed_viewers` for canister log visibility.
EXC-1697

feat: enable allowed_viewers feature for canister log visibility

---

rs/sns/governance/src/governance.rs

This PR adds a lock around checking the upgrade status and refreshing the cached upgrade steps. This ensures that they do not interleave with one another (or themselves).
This is useful because it simplifies our reasoning about any logic that may be impacted by such an interleaving.
This implementation is not ideal, because we attempt to acquire the lock unconditionally, which means that in cases where the lock was acquired it's impossible to say why. And in the unlikely even that the lock is not released, it would be useful to know what actual work necessitated it be acquired. #2124 builds upon this PR to create a more robust locking mechanism.

feat(sns): Add simple global lock for the periodic task that relates to upgrades

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tla/mod.rs
rs/nns/governance/src/governance/tla/store.rs
rs/nns/governance/tests/governance.rs
rs/tla_instrumentation/tla_instrumentation/src/lib.rs
rs/tla_instrumentation/tla_instrumentation/tests/multiple_calls.rs
rs/tla_instrumentation/tla_instrumentation/tests/structs.rs
rs/tla_instrumentation/tla_instrumentation_proc_macros/src/lib.rs

Switch to a `LocalKey`-based approach for Rust-based tests, and add an annotation (proc macro) that scopes the `LocalKey` to the test. 
Previously, we used only a global `RwLock`, which would cause traces of one test to be picked up by other tests. In contract, a `LocalKey` is task-local, eliminating the interference. We still use the `RwLock` as a fallback to store traces if the `LocalKey` is not present (i.e., no scope has been opened). This means that, first, tests that aren't annotated still collect the traces, but they aren't checked, which is a bit wasteful but should be OK as these aren't extremely heavy operations. Second, and more importantly, this means that the instrumentation will still work in canister-based tests, allowing a separate query method to pick the traces up from …

test(IC-1579): Isolate TLA tests in Rust-based (non-canister) tests

---

.bazelrc
hs/spec_compliance/bin/ic-ref-test.hs
hs/spec_compliance/src/IC/Management.hs
hs/spec_compliance/src/IC/Test/Agent.hs
hs/spec_compliance/src/IC/Test/Agent/SafeCalls.hs
hs/spec_compliance/src/IC/Test/Agent/UnsafeCalls.hs
hs/spec_compliance/src/IC/Test/Spec.hs
hs/spec_compliance/src/IC/Test/Spec/CanisterHistory.hs
hs/spec_compliance/src/IC/Test/Spec/Timer.hs
hs/spec_compliance/src/IC/Test/Spec/Utils.hs
rs/pocket_ic_server/tests/spec_test.rs

This PR uses the WASM chunk store to deploy the universal canister in spec compliance tests so that the universal canister WASM blob is not sent raw every time we deploy the universal canister. This optimization is supposed to save ingress message bandwidth and thereby optimize the spec compliance test runtime.

chore: use WASM chunk store in spec compliance tests

---

rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron/types/tests.rs
rs/nns/governance/tests/governance.rs

What we should have done was call Neuron::visibility. That's how it works now. Whereas, previously, similar (but not actually equivalent) code existed in a couple other places. Those have now been replaced with a call to Neuron::visibility, ensuring consistent behavior in our conversions.

fix(nns): Neuron conversion did not transcribe visibility correctly.

---

rs/nervous_system/proto/proto/ic_nervous_system/pb/v1/nervous_system.proto
rs/nervous_system/proto/src/gen/ic_nervous_system.pb.v1.rs
rs/sns/root/proto/ic_sns_root/pb/v1/root.proto
rs/sns/root/src/gen/ic_sns_root.pb.v1.rs

This PR adds some information about the applicability of `Timers` message in nervous_system.proto. 
Additionally, some typos are fixed in other proto comments.

docs(nervous-system): Add a comment for the `Timers` message in nervous_system.proto

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

This fixes a bug introduced in https://github.com/dfinity/ic/pull/2245. It defines the `RUN_ON_DIFF_ONLY ` env var on the workflow level such that the `Set BAZEL_EXTRA_ARGS` step has access to it.

fix(IDX): define RUN_ON_DIFF_ONLY on the workflow level

---

rs/tests/nested/BUILD.bazel

Since https://github.com/dfinity/ic/pull/2218, nested tests are back to running at a reasonable speed and passing tests.

fix: [NODE-1500] Re-enable nested tests

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Disabling bazel diff logic. https://github.com/dfinity/ic/pull/2266 introduced a bug and allowed the logic to work in this CI job.

fix(IDX): no diff with build-all-config-check

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Limiting diff logic only to `bazel-test-all` and `build-ic` since this is still problematic in PR runs.

fix(IDX): diff only bazel-test-all/build-ic

---

rs/bitcoin/adapter/src/lib.rs
rs/bitcoin/adapter/src/router.rs

Before https://github.com/dfinity/ic/pull/2178, make_idle was called at server startup if there have been no relevant transactions. 
After https://github.com/dfinity/ic/pull/2178, make_idle is not called anymore, meaning that the blockchain_manager and the connection_manager will stay in a "non idle" state forever for subnets that don't run the bitcoin adapter.

fix: call make_idle if the adapter is idle initially

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
MODULE.bazel
bazel/external_crates.bzl

This includes a patch that fixes rebuild issues in `rustix`. Without the patch the `rustix` crate creates a (seemingly non-deterministic) `.rmeta` file that causes cache misses in our bazel build.
For more info see: https://github.com/bytecodealliance/rustix/issues/1199
Some dependencies are also updated to match the `cargo` version and ensure we only depend on one `rustix` version -- more importantly, that we don't depend on `rustix v0.37.X` for which the patch doesn't work.

fix(IDX): work around spurious rebuilds in rustix

---

MODULE.bazel

Reverts dfinity/ic#2230 to mitigate the failures we're observing ([example](https://github.com/dfinity/ic/actions/runs/11553630505/job/32155209271)).

revert: "fix(IDX): use official docker images"

---

rs/ethereum/cketh/docs/proposals.adoc
rs/ethereum/cketh/mainnet/orchestrator_upgrade_2024_10_25.md

Proposal to upgrade all ledger suites managed by the ledger suite orchestrator to the latest version.

chore(cketh/ckERC20): proposal to upgrade ledger suite orchestrator and managed canisters

---

rs/bitcoin/adapter/src/lib.rs
rs/bitcoin/adapter/src/router.rs

the "idle" method was fairly complex, and it had a few bugs:
- if it was called before any transactions happened, it would not return immediately, instead it would wait for "idle_sec" (because the last_time defaults to now()).
- If the last transaction time happened more than "idle_sec" ago, it would panic because the u64 subtraction would underflow.
It was used to notify the main loop that it needs to break. This can now be a simple check after each iteration. 
These are both very niche cases and almost impossible to happen, from the way the method is used; but leaving it increases the risk of misusing the method in the future.

fix: remove the idle future

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
Cargo.toml
bazel/external_crates.bzl
rs/https_outcalls/adapter/src/rpc_server.rs
rs/https_outcalls/adapter/tests/server_test.rs
rs/tests/networking/canister_http_correctness_test.rs

After enabling h/2 with outcalls we had a regression where responses to https outcalls with headers greated than 16KB would fail. In https://github.com/hyperium/hyper-util/pull/154#issue-2614460610 hyper-util exposes a method to increase the header response limit.
This PR increases the limit to 52KiB, above 48KiB in the spec, to not block this weeks release in case the spec-compliance tests have any headers hardcoded that can break the test. We can reduce this limit  closer to 48KiB in the future.

fix(https-outcalls): Increase allowed header size limit for HTTP/2 requests

---

rs/validator/http_request_test_utils/src/lib.rs
rs/validator/ingress_message/tests/validate_request.rs
rs/validator/src/ingress_validation.rs

Adapts ingress message validation such that the ingress_expiry check is skipped for anonymous queries and anonymous read_state requests.
Implements the interface specification changes from https://github.com/dfinity/interface-spec/pull/343.

feat(crypto): CRP-2593 skip ingress_expiry check for anonymous queries and read_state requests

---

rs/tests/research/spec_compliance/spec_compliance.rs

https://github.com/dfinity/ic/pull/2251 optimised ic-ref-test such that instead of uploading the WASM of the universal canister for every test it's only uploaded once to the WASM chunk store and then installed from there.
This should reduce the load on the IC and so we should be able to support a higher level of parallelism. So like #2251 we bump the number of ic-ref-test jobs from 16 to 64.
The following are [the results](https://dash.zh1-idx1.dfinity.network/invocation/ccf672c1-5f7b-40da-bc73-8d1b4a511b47?targetFilter=%2F%2Frs%2Ftests%2Fresearch%3Aspec_compliance_#targets) where I list [the P90 from last week onwards](https://superset.idx.dfinity.network/explore/?form_data_key=8dXXZ6F633bRVs9tnki-0djzUkDwtjFAjeYJ_7nQBtbbdsmDpSSC1k0-0wG-V8s5&dashboard_page_id=jkkuHpdTs&slice_id=60) and …

test(IDX): increase the number of ic-ref-test jobs in the spec_compliance tests

---

Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock

The cargo build and the bazel fuzzing builds both use typenum v1.17.0.
The v1.16.0 version used in the main build includes `carg:rustc-env` stdout lines that include the build directory. Stdout is recorded by rules_rust and make the `typenum` build artifacts depend on the actual build directory.
This was fixed in https://github.com/paholg/typenum/commit/bbac3bf45621b3f35ddd1f312be9a92193470738#diff-aab2aa4b42e7b86d709397b51cfee282c98274effe7e541ed42603b96fe38136L7

fix(IDX): bump to typenum v1.17.0 in Bazel

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
bazel/external_crates.bzl

The previous `thiserror` version included dep-info files in the bazel build output, which included the (changing) build directory and threw off Bazel.
This was fixed in https://github.com/dtolnay/thiserror/pull/325

fix(IDX): bump to thiserror v1.0.65 in Bazel

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.json.lock
WORKSPACE.bazel

This ensures we're keeping up with potential changes in `rules_rust` and benefit from improvements.

chore(IDX): bump rules_rust to 0.53.0

---

rs/consensus/src/idkg/payload_builder.rs
rs/consensus/src/idkg/payload_builder/pre_signatures.rs
rs/consensus/src/idkg/payload_builder/signatures.rs
rs/consensus/src/idkg/payload_verifier.rs
rs/consensus/src/idkg/signer.rs
rs/consensus/src/idkg/test_utils.rs
rs/consensus/src/idkg/utils.rs
rs/consensus/utils/src/lib.rs
rs/execution_environment/src/scheduler/threshold_signatures.rs
rs/protobuf/def/registry/crypto/v1/crypto.proto
rs/protobuf/src/gen/crypto/registry.crypto.v1.rs
rs/protobuf/src/gen/registry/registry.crypto.v1.rs
rs/protobuf/src/gen/state/registry.crypto.v1.rs
rs/protobuf/src/gen/types/registry.crypto.v1.rs
rs/registry/canister/canister/registry.did
rs/registry/canister/tests/common/test_helpers.rs
rs/state_machine_tests/src/lib.rs
rs/test_utilities/execution_environment/src/lib.rs
rs/tests/consensus/tecdsa/tecdsa_signature_fails_without_cycles_test.rs
rs/tests/consensus/tecdsa/tecdsa_signature_life_cycle_test.rs
rs/tests/consensus/tecdsa/utils/src/lib.rs
rs/types/management_canister_types/src/lib.rs

Adds a variant for vetKD in the `MasterPublicKeyId` in the
1. registry protobuf definitions,
where it is used in the `KeyConfig` (which is used in the `ChainKeyConfig`, which is used in the `SubnetRecord`).
2. management canister types,
where it is used in the `ComputeInitialIDkgDealingsArgs` (which will be generalized in a later step, e.g., to `ReshareChainKeyArgs`).
3. registry canister API (registry.did),
where it is used in the `KeyConfig` (which is used in the `KeyConfigRequest`, which is used in the `InitialChainKeyConfig`, which is used in `CreateSubnetPayload` and `RecoverSubnetPayload`), and in the `UpdateSubnetPayload`'s `chain_key_signing_enable`/`chain_key_signing_disable`.
This is the very first step for the vetKeys feature.
As discussed with the Consensus team, various …

feat(crypto): CRP-2609 Introduce master key ID variant for vetKD

---

rs/nns/sns-wasm/src/sns_wasm.rs
rs/nns/sns-wasm/tests/deploy_new_sns.rs

This PR implements the first step towards making Swap a proper SNS canister. To that end, SNS-W now adds SNS Root as a controller of a newly created Swap canister, in addition to NNS Root. (In the future, only SNS Root would need to be its controller.)
| [Next PR](https://github.com/dfinity/ic/pull/2300) >

feat(sns): Make SNS-W create new Swaps with SNS Root as a controller (in addition to NNS Root)
