ic-os/components/setupos-scripts/check-network.sh

Successfully filters out `::1` and `fe80...`, and lets `...fe80...` and `...::1...` through.
```
% cat demo
inet6 ::1/128 scope host
valid_lft forever preferred_lft forever
inet6 fe80:a424:8eec:696f:de9a:532b:bbad:f0d7/64 scope link
valid_lft forever preferred_lft forever
inet6 a550:fe80:8eec:696f:de9a:532b:bbad:f0d7/64 scope global
valid_lft forever preferred_lft forever
inet6 a550:a424:8eec:696f:de9a:532b::1/64 scope global
valid_lft forever preferred_lft forever
```
```
% cat demo | awk '(/inet6/) && (!/\sfe80|\s::1/) { print $2 }'
a550:fe80:8eec:696f:de9a:532b:bbad:f0d7/64
a550:a424:8eec:696f:de9a:532b::1/64
```

fix: Make regex for special address ranges more strict

---

rs/bitcoin/kyt/btc_kyt_canister.did
rs/bitcoin/kyt/src/dashboard.rs
rs/bitcoin/kyt/src/dashboard/tests.rs
rs/bitcoin/kyt/src/fetch.rs
rs/bitcoin/kyt/src/fetch/tests.rs
rs/bitcoin/kyt/src/lib.rs
rs/bitcoin/kyt/src/main.rs
rs/bitcoin/kyt/src/state.rs
rs/bitcoin/kyt/src/types.rs
rs/bitcoin/kyt/templates/dashboard.html
rs/bitcoin/kyt/tests/tests.rs

Support KytMode in the initialization and upgrade parameters  to the new KYT canister.
This simplifies work involved in testing with this canister, because the previous KYT canister had this feature and existing ckbtc minter tests are making use of it.

feat(ckbtc): Support KytMode in new KYT canister

---

rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/proposal.rs
rs/sns/governance/src/sns_upgrade.rs
rs/sns/governance/tests/governance.rs

The idea is for the upgrade journal to have all the information necessary to understand when and why the SNS got to its current version. This PR adds the journal to the API (but doesn't yet populate the journal, generally).
A follow-up PR will use the new endpoint in tests, and populate it in more places. As a proof of concept, I've made refreshing the upgrade steps add an entry to the journal, although the purpose of this PR is just to implement the API.

feat(sns): Add the upgrade_journal to the get_upgrade_journal SNS-Gov endpoint

---

rs/nns/sns-wasm/src/sns_wasm.rs
rs/nns/sns-wasm/tests/deploy_new_sns.rs

This PR prepares the SNS-W canister to an upcoming replica change (https://github.com/dfinity/ic/pull/2308).
The previous value for `INITIAL_CANISTER_CREATION_CYCLES` was 1T.
With that amount, I experimentally observed the following error during SNS deployment, more specifically, when the SNS Root was being installed:
```
Error installing Root WASM: 
Failed to install WASM on canister 7tjcv-pp777-77776-qaaaa-cai: 
error code 2: 
Canister installation failed with 
`Canister 7tjcv-pp777-77776-qaaaa-cai is out of cycles: 
please top up the canister with at least 46_167_036_896 additional cycles`.
```
Thus, setting `INITIAL_CANISTER_CREATION_CYCLES` to 2T would suffice to cover the increased deployment costs. 
However, another fee increase planned in two weeks from now will be …

chore(sns): Set `INITIAL_CANISTER_CREATION_CYCLES` to 3T

---

Cargo.lock
rs/consensus/src/consensus/bounds.rs
rs/consensus/src/consensus/notary.rs
rs/consensus/src/consensus/priority.rs
rs/consensus/utils/BUILD.bazel
rs/consensus/utils/Cargo.toml
rs/consensus/utils/src/lib.rs

These functions are only used by the notary

chore(consensus): move notary related functions from `consensus_utils` crate to `notary.rs` in `consensus` crate

---

rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/tests.rs

When a canister execution consumes no instructions, it's likely due to insufficient cycle balance. The overhead of checking a balance is negligible compared to the overhead of actual canister execution.
This change allows executions to fail due to insufficient cycle balance without additional overhead, hence not impacting round capacity.

feat: EXC-1764: Skip per-canister overhead if no instructions used

---

ic-os/boundary-guestos/context/Dockerfile
ic-os/components/boundary-guestos/opt/ic/bin/setup-ic-gateway.sh

* Update `ic-gateway` to v0.1.58 with new shedding & timeouts
* Enable shedding based on Clickhouse statistics (target latency set to roughly x2 of 95% percentile)

feat(BOUN-1215) fix(BOUN-1282): update ic-gateway, enable shedding

---

rs/consensus/src/consensus/block_maker.rs
rs/consensus/utils/src/membership.rs

At the moment we trigger the delay a tad too often, thus we increase the threshold of maximum allowed non-rank-0 notarized blocks from 5 to 10. The metrics show that the delay will be still occasionally triggered, but significantly less frequently than now.

feat(consensus): adjust dynamic block maker delay

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/lib.rs

This allows an override that explicitly unmutes the server, which is needed when debugging canbench tests.
See: https://github.com/dfinity/canbench/pull/73/files

feat(pocket-ic): POCKET_IC_MUTE_SERVER only mutes output when set to non-empty string

---

ic-os/components/hostos-scripts/build-bootstrap-config-image.sh
ic-os/components/init/bootstrap-ic-node/bootstrap-ic-node.sh
rs/ic_os/dev_test_tools/launch-single-vm/src/main.rs
rs/prep/src/bin/prep.rs
rs/prep/src/internet_computer.rs
rs/prep/src/node.rs
rs/prep/src/prep_state_directory.rs
rs/registry/regedit/src/tests.rs
rs/replica_tests/src/lib.rs
rs/starter/src/main.rs
rs/tests/driver/src/driver/bootstrap.rs
rs/tests/driver/src/driver/ic.rs
rs/tests/driver/src/driver/prometheus_vm.rs
rs/tests/driver/src/driver/resource.rs
rs/tests/driver/src/driver/test_env_api.rs
rs/tests/testing_verification/testnets/BUILD.bazel
rs/tests/testing_verification/testnets/small_with_api_bn.rs

This PR adds the API BNs to the system test infrastructure such that one can spin up an IC with API boundary nodes. To this end, `ic-prep` has been extended (e.g., domain name in the node structs and the notion of API boundary nodes). In addition, the test driver has been extended to allow the addition of API boundary nodes. Finally, a small testnet with API BNs has been added to serve as an example.
In follow-up MRs, we can move some of the system tests (e.g., the API BN decentralization test).

chore(system-tests): adding API BNs to ic-prep and creating a testnet with API BNs

---

rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2024_10_28.md
rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2024_10_28.md
rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2024_10_28.md

Proposals to upgrade the ckBTC ledger suite (index, ledger and archive canisters) to `release-2024-10-17_03-07-base` (commit `e54d3fa34ded227c885d04e64505fa4b5d564743`)

chore(ckbtc): Upgrade ckBTC ledger suite

---

rs/consensus/src/consensus/block_maker.rs
rs/limits/src/lib.rs

The current value is constant and a bit too high. It should depend on the size of the subnet, because on a subnet with fewer nodes it should take less time to broadcast a block than on a subnet with many nodes. For example, on an app subnet it should take around 3x less time than on an nns subnet.
The unit delay setting in the subnet record encapsulates quite well what we need, thus instead of having the constant, we use the unit delay. This effectively means that when a subnet struggles to produce rank-0 blocks at acceptable (at the moment 66%) rate we double the time we allot to a rank-0 block maker for a creation and distribution of a block.

chore(consensus): adjust dynamic block maker delay

---

Cargo.lock
rs/bitcoin/kyt/BUILD.bazel
rs/bitcoin/kyt/Cargo.toml
rs/bitcoin/kyt/btc_kyt_canister.did
rs/bitcoin/kyt/src/dashboard/tests.rs
rs/bitcoin/kyt/src/fetch.rs
rs/bitcoin/kyt/src/fetch/tests.rs
rs/bitcoin/kyt/src/lib.rs
rs/bitcoin/kyt/src/main.rs
rs/bitcoin/kyt/src/providers.rs
rs/bitcoin/kyt/src/providers/tests.rs
rs/bitcoin/kyt/src/state.rs
rs/bitcoin/kyt/src/types.rs
rs/bitcoin/kyt/templates/dashboard.html

Support bitcoin regtest network for local testing by adding an option to specify bitcoind JSON RPC URL.
However, because bitcoind only supports HTTP protocol, one needs to find a workaround because by default canister HTTPs outcall will not work with plain HTTP. This can be achieved with one of the following methods:
1. Compile and use pocket-ic-server after enabling the "http" feature in the ic-https-outcalls-adapter crate, or
2. Set up reverse HTTPS proxy to connect to bitcoind.
The first approach has been tested manually and the second approach will be used in a followup PR that adapts ckbtc system tests after the new KYT canister is enabled.

feat(ckbtc): Support regtest network in new KYT canister

---

hs/spec_compliance/src/IC/Test/Spec.hs
hs/spec_compliance/src/IC/Test/Spec/CanisterVersion.hs
hs/spec_compliance/src/IC/Test/Spec/Utils.hs
rs/tests/research/BUILD.bazel
rs/universal_canister/impl/BUILD.bazel
rs/universal_canister/impl/Cargo.toml
rs/universal_canister/impl/src/main.rs

This PR speeds up spec compliance tests by
- deleting universal canister at the end of simple tests using only one canister;
- using a universal canister without heartbeats in all tests.
This prevents the following tests:
- test that heartbeat is executed (tested sufficiently in canister tests relying on heartbeat functionality and in execution environment tests);
- test that replying in heartbeats traps (tested sufficiently in system API tests);
- check canister version in heartbeat (only mild test coverage reduction as there is still an analogous test for global timer which is a system task, too).

chore: run spec compliance tests without heartbeat

---

rs/tests/dashboards/IC/execution-metrics.json

Problem:
Dashboard that is recently added to k8s repo, is not shown when running testnet.
Solution:
Add it in `/rs/tests/dashboards`.

chore: Add sandbox cache hit dashboard to testnet grafana

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/tests/governance.rs

This occurs when a neuron is modified in the following ways:
1. vote (directly, not indirectly)
2. change follow
This will be used to reduce the voting power in ballots when a neuron has not refreshed for a long time.
Closes https://dfinity.atlassian.net/browse/NNS1-3405.
[👈 Previous PR][prev] | [Next PR 👉][next]
[prev]: https://github.com/dfinity/ic/pull/2268
[next]: https://github.com/dfinity/ic/pull/2338

feat(nns): Refresh voting power.

---

Cargo.lock
Cargo.toml
rs/nervous_system/linear_map/BUILD.bazel
rs/nervous_system/linear_map/Cargo.toml
rs/nervous_system/linear_map/src/lib.rs
rs/nervous_system/linear_map/tests/tests.rs
rs/sns/governance/BUILD.bazel
rs/sns/governance/Cargo.toml
rs/sns/governance/src/reward.rs

This was spun out of sns governance so that it can be used elsewhere (in another PR that I'm working on).
(No ticket.)
[👈 Previous PR][prev] | [Next PR 👉][next]
[prev]: https://github.com/dfinity/ic/pull/2320
[next]: https://github.com/dfinity/ic/pull/2339

feat: Linear map.

---

rs/nervous_system/integration_tests/tests/advance_target_version.rs

This method is nicer because it gives better error messages when things go wrong, and is potentially faster and less fragile than what we were doing before.
[Next PR →](https://github.com/dfinity/ic/pull/2378)

test(sns): Refactor to use `await_with_timeout` method 

---

rs/nervous_system/agent/src/sns/governance.rs
rs/nervous_system/agent/src/sns/index.rs
rs/nervous_system/agent/src/sns/ledger.rs
rs/nervous_system/agent/src/sns/root.rs
rs/nervous_system/agent/src/sns/swap.rs

They are just wrappers for `Principald`s, which are `Copy`, and it's more convenient not to have to write `.clone()`
[← Prevous PR](https://github.com/dfinity/ic/pull/2377) | [Next PR →](https://github.com/dfinity/ic/pull/2321)

refactor(sns): Add `Copy` implementation to ic-nervous-system-agent SNS canister wrappers

---

rs/sns/cli/src/init_config_file/friendly.rs
rs/sns/cli/src/init_config_file/friendly/friendly_tests.rs
rs/sns/cli/test_sns_init_v2.yaml
testnet/tools/nns-tools/sns_default_test_init_params_v2.yml

Currently, `Distribution.InitialBalances.governance` is being mapped to `initialTokenDistribution.treasuryDistribution.total`. 
With this change, `Distribution.InitialBalances.governance` will be renamed to `Distribution.InitialBalances.treasury`.

feat(sns-cli): Rename `Distribution.InitialBalances.governance` as `Distribution.InitialBalances.treasury`.

---

packages/pocket-ic/tests/slow.rs
rs/state_machine_tests/src/lib.rs

In production, canister sandboxing is always enabled. Moreover, without canister sandboxing, the error message for instruction limit exceeded reports a limit of 0 instructions for single message execution which is confusing.

fix: always enable canister sandboxing in SM tests

---

packages/pocket-ic/Cargo.toml
packages/pocket-ic/src/lib.rs

This PR fixes and reenables doc tests of the PocketIC library.

fix(PocketIC): doc tests

---

rs/pocket_ic_server/src/pocket_ic.rs

This PR reshares code of the status HTTP handler from `ic-boundary`. That code used to be copied because `ic-boundary` used to depend on an incompatible axum version.

chore: reshare status handle from ic-boundary

---

rs/pocket_ic_server/src/pocket_ic.rs
rs/pocket_ic_server/src/state_api/state.rs

This PR removes an unused operation `InstallCanisterAsController` from the PocketIC server.

chore: drop unused operation in PocketIC server

---

Cargo.lock
packages/pocket-ic/BUILD.bazel
packages/pocket-ic/Cargo.toml
packages/pocket-ic/src/nonblocking.rs

This PR drops a dependency on `ic-agent` in the PocketIC library so that this library can be used in `ic-agent`.

chore: drop dependency on ic-agent in PocketIC library

---

packages/pocket-ic/src/common/rest.rs
packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs
rs/pocket_ic_server/src/pocket_ic.rs

This PR allows specifying multiple bitcoin nodes in PocketIC instance configuration which is required by DFX.

feat: allow specifying multiple bitcoin nodes in PocketIC instance configuration

---

publish/binaries/BUILD.bazel

The target sns-test-feature is not used anymore and is thus removed from the Bazel configurations.

chore: Remove obsolete publish target sns-test-feature

---

rs/ethereum/cketh/minter/DepositHelperWithSubaccount.sol
rs/ethereum/cketh/minter/cketh_minter.did
rs/ethereum/cketh/minter/src/deposit.rs
rs/ethereum/cketh/minter/src/eth_logs/mod.rs
rs/ethereum/cketh/minter/src/eth_logs/parser.rs
rs/ethereum/cketh/minter/src/eth_logs/scraping.rs
rs/ethereum/cketh/minter/src/eth_logs/tests.rs
rs/ethereum/cketh/minter/src/eth_rpc.rs
rs/ethereum/cketh/minter/src/guard/tests.rs
rs/ethereum/cketh/minter/src/lifecycle/init.rs
rs/ethereum/cketh/minter/src/lifecycle/tests.rs
rs/ethereum/cketh/minter/src/lifecycle/upgrade.rs
rs/ethereum/cketh/minter/src/state.rs
rs/ethereum/cketh/minter/src/state/tests.rs
rs/ethereum/cketh/minter/src/test_fixtures.rs

Support deposit of ETH or ERC-20 with subaccounts by scraping the logs of a new smart contract, currently deployed only on Sepolia at [0x2D39863d30716aaf2B7fFFd85Dd03Dda2BFC2E38](https://sepolia.etherscan.io/address/0x2d39863d30716aaf2b7fffd85dd03dda2bfc2e38). The smart contract offers 2 methods:
1. `depositEth`
2. `depositErc20`
that when successful emit the same type of event `ReceivedEthOrErc20`, which allows to retrieve the logs of that smart contract in a single request.

feat(cketh/ckerc20): Deposit with subaccounts

---

rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs

This was accidentally included in #2169 as pointed out by @aterga. This PR just removes it.

fix(sns): Remove accidentally-included timer type definitions

---

testnet/tools/nns-tools/lib/proposals.sh

This PR fixes a typo in the verification instructions of the Swap upgrade proposal generation script.

fix: typo in `generate_swap_canister_upgrade_proposal_text`

---

rs/nns/governance/init/src/lib.rs
rs/nns/governance/tests/neurons.csv
rs/nns/integration_tests/src/neurons.csv

This PR fixes the NNS init .csv parser to enable it to recognize `dissolve_delay_s` and `maturity_e8s_equivalent` values for initial neurons again.

fix: Make NNS init .csv parser recognize `dissolve_delay_s` and `maturity_e8s_equivalent` values again

---

hs/spec_compliance/src/IC/Test/Agent.hs
hs/spec_compliance/src/IC/Test/Spec.hs
rs/tests/research/BUILD.bazel
rs/tests/research/Cargo.toml
rs/tests/research/spec_compliance/spec_compliance.rs
rs/tests/research/spec_compliance_application_subnet_test.rs
rs/tests/research/spec_compliance_group_01_application_subnet_test.rs
rs/tests/research/spec_compliance_group_01_system_subnet_test.rs
rs/tests/research/spec_compliance_group_02_application_subnet_test.rs
rs/tests/research/spec_compliance_group_02_system_subnet_test.rs
rs/tests/research/spec_compliance_group_03_system_subnet_test.rs
rs/tests/research/spec_compliance_system_subnet_test.rs

This PR splits and optimizes the spec compliance tests:
- avoid artificial delays
- reuse the same universal canister in selected tests that do not update the universal canister's state
- decreases the number of jobs from 64 to 32 (reducing flakiness)
- no httpbin webserver is started if not needed
- a new group of test cases is introduced as a separate system test
All spec compliance tests are labeled as pre-master since they finish well below 5mins:
```
//rs/tests/research:spec_compliance_application_subnet_test              PASSED in 226.4s
//rs/tests/research:spec_compliance_group_01_application_subnet_test     PASSED in 232.9s
//rs/tests/research:spec_compliance_group_01_system_subnet_test          PASSED in 238.6s
//rs/tests/research:spec_compliance_group_02_application_subnet_test …
```

chore: split and optimize spec compliance tests

---

rs/bitcoin/kyt/BUILD.bazel
rs/bitcoin/kyt/src/dashboard/tests.rs
rs/bitcoin/kyt/src/fetch.rs
rs/bitcoin/kyt/src/fetch/tests.rs
rs/bitcoin/kyt/src/lib.rs
rs/bitcoin/kyt/src/main.rs
rs/bitcoin/kyt/src/state.rs

Refactor the ic-btc-kyt crate to only keep necessary functions in the library and move the rest to build together with the Wasm binary.
This is a necessary move in order to resolve a bizarre problem with CI when ic-btc-kyt is made a dependency of ic-ckbtc-minter. More specifically, our CI job "Bazel Build All Config Check" (which is essentially running clippy) would fail unless askama template is moved out of the ic-btc-kyt lib. Refactoring this crate avoids the problem.

refactor(ckbtc): refactor the ic-btc-kyt crate

---

rs/bitcoin/ckbtc/minter/src/metrics.rs
rs/ethereum/cketh/minter/src/main.rs
rs/ethereum/ledger-suite-orchestrator/src/main.rs

Rename the following metrics published by canisters owned by the cross-chain team:
1. `canister_stable_memory_bytes` -> `stable_memory_bytes`
2. `canister_ heap_memory_bytes` -> `heap_memory_bytes`

refactor(cross-chain): rename metrics related to memory

---

rs/execution_environment/tests/execution_test.rs
rs/replicated_state/src/canister_snapshots.rs

Eliminate code duplication by replacing `CanisterSnapshots::delete_snapshots` functionality with `CanisterSnapshots::remove`.

fix: EXC-1775: Replace `delete_snapshots` functionality with `remove`

---

.github/workflows-source/ci-main.yml
.github/workflows-source/ci-pr-only.yml
.github/workflows/ci-main.yml
.github/workflows/ci-pr-only.yml

Moving `bazel-test-coverage` to the PR workflow to avoid confusion as to why it's skipped on ci-main and release workflows.

chore(IDX): move bazel-test-coverage to pr workflow

---

hs/spec_compliance/src/IC/Test/Agent.hs
rs/tests/research/spec_compliance/spec_compliance.rs

This PR sets the read state retry delay in spec compliance tests to match the Rust agent's [initial retry delay](https://github.com/dfinity/agent-rs/blob/705f23f83dc1360d2de62fbf62a56757d6ba26cf/ic-agent/src/agent/mod.rs#L622) of 500 ms. Retry delays shorter than a round duration are not useful and only create network traffic.

chore: increase read state retry delay in spec compliance tests

---

.github/actions/bazel-test-all/action.yaml
.github/workflows-source/ci-main.yml
.github/workflows-source/ci-pr-only.yml
.github/workflows-source/release-testing.yml
.github/workflows-source/schedule-daily.yml
.github/workflows-source/schedule-hourly.yml
.github/workflows/ci-main.yml
.github/workflows/ci-pr-only.yml
.github/workflows/release-testing.yml
.github/workflows/schedule-daily.yml
.github/workflows/schedule-hourly.yml
.github/workflows/system-tests-k8s.yml

This PR moves the node name to the step summary as part of the `bazel-test-all` action instead of `before-script`. I then removed `before-script` completely as it's not needed.

refactor(IDX): move node-name to step summary

---

ic-os/components/ic/ic.json5.template
rs/orchestrator/testdata/nftables_boundary_node.conf.golden

Since we switched from the HTTP- to the ALPN-ACME-challenge, we don't need to have port 80 open anymore on the API boundary nodes.

chore(api-boundary-node): close port 80 on the API BNs

---

rs/nns/governance/api/BUILD.bazel

Remove a library we no longer need.

chore(nns): remove governance api--test-feature bazel target

---

rs/crypto/tests/canister_threshold_schnorr_verify_combined_sig.rs

The test generates BIP340 signatures, sometimes with and sometimes without using the Taproot option. However the validation check was never updated to handle Taproot. We got "lucky" in CI in 1803, and the test just happened to succeed at every point.

fix(crypto): Fix a flaky test introduced by PR 1803

---

testnet/tools/nns-tools/lib/proposals.sh

This PR fixes a typo in the previous fix attempt for the verification instructions of the Swap upgrade proposal generation script.
Previous attempt: https://github.com/dfinity/ic/pull/2380

fix: typo in generate_swap_canister_upgrade_proposal_text (attempt 2)

---

rs/nervous_system/integration_tests/tests/advance_target_version.rs
rs/sns/governance/canister/canister.rs
rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/types.rs

This PR populates the upgrade journal when new events occur. The upgrade journal was first introduced in #2169
[← Previous PR](https://github.com/dfinity/ic/pull/2378) | [Next PR →](https://github.com/dfinity/ic/pull/2034)

feat(sns): Populate upgrade journal

---

rs/nervous_system/integration_tests/tests/sns_ledger_upgrade.rs
rs/nervous_system/integration_tests/tests/sns_release_qualification.rs

These SNS qualification tests were disabled last week due to the mainnet SNS-W canister not providing enough cycles upfront while deploying an SNS. With https://dashboard.internetcomputer.org/proposal/133906 being adopted, we now have the adjusted SNS-W canister on mainnet, so the previously disabled qualification tests can now be enabled again.

test(sns): Re-enable SNS qualification tests after the next SNS-W release

---

rs/boundary_node/rate_limits/canister/add_config.rs
rs/boundary_node/rate_limits/canister/canister.rs
rs/boundary_node/rate_limits/canister/state.rs

This `post_upgrade` hook serves the following purposes:
- Allows changing the authorized principal during canister upgrade phase (upgrades will be done via nns proposals)
- Resets periodic timer task of polling API boundary nodes, otherwise this task remains stopped after upgrade

feat(boundary): add rate-limit canister post_upgrade

---

rs/rosetta-api/scripts/run_upgrade_test.sh

Assume yes, i.e., do not wait for user input when installing dependencies using `apt install` in the ICP ledger qualification script.

test(ICP_ledger): FI-1568: Assume yes for apt install in ICP ledger suite qualification script

---

packages/pocket-ic/BUILD.bazel
packages/pocket-ic/test_canister/canister.did
packages/pocket-ic/test_canister/src/canister.rs
packages/pocket-ic/tests/slow.rs
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/main.rs
rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/test.rs

This PR contains the following changes:
- the log levels for PocketIC server logs are configurable via a new CLI option `--log-levels`;
- auto progress mode produces a debug log when starting and stopping;
- PocketIC library tests are simplified by using the test canister and optimized by better controlling the number of executed instructions.

feat(PocketIC): configurable server log levels and optimized tests

---

rs/embedders/tests/stable_grow.rs

This reduces the overall test time from ~40s down to ~3s.

chore: EXC: Reduce stable grow test cases to 10

---

Cargo.lock
rs/nns/governance/BUILD.bazel
rs/nns/governance/Cargo.toml
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron/types/tests.rs
rs/nns/governance/src/neuron_store/metrics.rs
rs/nns/governance/src/neuron_store/metrics/tests.rs
rs/nns/governance/tests/governance.rs

Add deciding_voting_power method to Neuron.
Renames the voting_power method of Neuron to potential_voting_power.
Added a flag that controls whether deciding_voting_power applies adjustment. Per usual, adjustment is off in vanilla builds, but on when feature = "test".
Voting rewards uses this new method. As long as the the new behavior is not enabled (via the flag), this should result in no behavior change, and even initially, when the feature is enabled, since no neuron can be too unrefreshed, even then, there would be no immediate behavior change.
Closes https://dfinity.atlassian.net/browse/NNS1-3406, …

feat(nns): Make distinction between potential and deciding voting power.

---

rs/pocket_ic_server/tests/test.rs

This PR fixes PocketIC test [flakiness](https://dash.zh1-idx1.dfinity.network/invocation/3afbf11a-8204-4602-86f5-22bfe8452b55?target=%2F%2Frs%2Fpocket_ic_server%3Atest&targetStatus=6#@228) due to auto progress logs.

fix: test flakiness due to auto progress logs

---

rs/execution_environment/src/scheduler/round_schedule.rs

This change is functionally equivalent but necessary for the upcoming priority-based eviction.

chore: EXC-1754: Apply priority credit at the end of the round

---

rs/cross-chain/proposal-cli/src/candid/mod.rs
rs/cross-chain/proposal-cli/src/candid/tests.rs
rs/cross-chain/proposal-cli/src/main.rs
rs/cross-chain/proposal-cli/src/proposal/mod.rs

To avoid potential confusion for reviewers of proposals generated using the `proposal-cli` before they are submitted, do not write the `args.hex` file to disk.

feat(proposal_cli): FI-1571: Do not write the args.hex file from proposal-cli

---

rs/sns/governance/src/governance.rs
rs/sns/governance/src/proposal.rs

The way this function was implemented was super confusing to me. This PR refactors it and renames it to `check_no_other_upgrades_in_progress`. 
This PR also makes it fail if `pending_upgrade` is set to `Some(_)`. A for this behavior has been added.
[Next PR →](https://github.com/dfinity/ic/pull/2034)

refactor(sns): err_if_another_upgrade_is_in_progress refactor

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron/types/tests.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/tests/governance.rs

This will be used in the calculation of voting rewards. Whereas, before, the total voting power in ballots (i.e. "deciding" voting power) was used as the baseline to determine each neuron's share of the reward purse. With the distinction between potential voting power vs. deciding voting power (implemented in an earlier PR in this series), if we continued to do it the old way, the pie would be sliced into a smaller number of pieces. When this new field is used, the pie will continue to be sliced into the same number of pieces today. This way, neurons that stay refreshed will keep getting the same amount of rewards (not …

feat(nns): Added total_potential_voting_power to proposals.

---

rs/nns/governance/src/lib.rs
rs/nns/governance/src/test_utils.rs

This PR adds a new feature flag that will be used to keep stable neurons support behind a feature flag until it is completed and the migration is ready to proceed.
Next PR: https://github.com/dfinity/ic/pull/2473

chore(nns): add feature flag for stable following index

---

rs/ethereum/cketh/minter/cketh_minter.did
rs/ethereum/cketh/minter/src/dashboard.rs
rs/ethereum/cketh/minter/src/dashboard/tests.rs
rs/ethereum/cketh/minter/src/deposit.rs
rs/ethereum/cketh/minter/src/endpoints.rs
rs/ethereum/cketh/minter/src/eth_logs/scraping.rs
rs/ethereum/cketh/minter/src/eth_logs/tests.rs
rs/ethereum/cketh/minter/src/lifecycle/init.rs
rs/ethereum/cketh/minter/src/lifecycle/tests.rs
rs/ethereum/cketh/minter/src/main.rs
rs/ethereum/cketh/minter/src/state.rs
rs/ethereum/cketh/minter/src/state/audit.rs
rs/ethereum/cketh/minter/src/state/eth_logs_scraping/mod.rs
rs/ethereum/cketh/minter/src/state/tests.rs
rs/ethereum/cketh/minter/templates/dashboard.html
rs/ethereum/cketh/minter/tests/ckerc20.rs
rs/ethereum/cketh/minter/tests/cketh.rs

Follow-up on #2324 and #2369 to consolidate log scrapings done by the ckETH minter.
Information related to the state of the scraping of the new deposit with subaccount helper smart contract:
1. Last scraped block number to `MinterInfo`.
2. State of scraping (address and last scraped block number) to the minter dashboard.
3. Metric for the last scraped block number.
Refactor `State` to have a container (`LogScrapings`) to aggregate all log scrapings. This allows to:
1. Automatically display the state of a new log scraping to the minter dashboard. Information related to helper smart contracts was moved to its own section.
2. Automatically add a metric for the last scraped block number.
3. Recall to add an event that is registered during `pre-upgrade` to save the last scraped block number to …

feat(cketh/ckerc20): consolidate log scrapings

---

rs/ethereum/cketh/minter/tests/cketh.rs
rs/execution_environment/src/execution_environment/tests/canister_task.rs
rs/execution_environment/tests/canister_logging.rs
rs/execution_environment/tests/dts.rs
rs/ledger_suite/icp/index/tests/tests.rs
rs/ledger_suite/icp/ledger/tests/tests.rs
rs/ledger_suite/tests/sm-tests/src/lib.rs
rs/state_machine_tests/src/lib.rs

This PR avoids querying the time of next round in tests by advancing time so that time does not grow implicitly when executing a round. The motivation for this change is to clean up the StateMachine test API.

chore: do not use time of next round in tests

---

rs/tests/driver/src/util.rs
rs/tests/research/spec_compliance/spec_compliance.rs

This optimises the setup function of the spec_compliance system-tests by concurrently installing the NNS and starting the Boundary Node. This shaves off a minute from the setup and brings the total test time under 5 minutes.
Additionally the steps on the critical path of the setup function are now measured and logged so that we can monitor what takes up the time.

chore(IDX): optimise the setup of the spec_compliance systests

---

rs/pocket_ic_server/tests/spec_test.rs

I noticed the `//rs/pocket_ic_server:spec_test` being a bit unstable after https://github.com/dfinity/ic/pull/2331 which I suspect comes from the high degree of parallelism. So let's halve this from 64 to 32 threads.

chore(IDX): lower parallelism of ic-ref-test in //rs/pocket_ic_server:spec_test

---

rs/sns/integration_tests/src/golden_state_swap_upgrade_twice.rs
rs/sns/swap/canister/canister.rs
rs/sns/swap/src/swap.rs

This PR removes the data migration from Swap's post-upgrade, namely, the code that defined `direct_participation_icp_e8s` and `neurons_fund_participation_icp_e8s` based on priorly available data. This migration has been applied to all Swaps existing in production, see https://forum.dfinity.org/t/proposal-to-upgrade-the-oldest-swap-canisters/36318#p-143615-planned-upgrade-order-of-existing-swap-canisters-4

chore(sns): Remove completed data migration from Swap

---

ic-os/dev-tools/bare_metal_deployment/tools.bzl
requirements.in
requirements.txt

This python library has not been used in our repo since https://github.com/dfinity/ic/commit/d85f6e23095da708a0e606bde09e08d793e17054.

fix(IDX): remove unused icmplib py dep

---

rs/sns/governance/canister/canister.rs
rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/governance/tests/fail_stuck_upgrade_in_progress_tests.rs

As of this PR, UpgradeInProgress is used in the API, while PendingVersion is used internally. This will allow us to evolve them separately.
This is not actually a breaking change as far as proto is concerned

refactor(sns): Separate UpgradeInProgress and PendingVersion

---

Cargo.lock
rs/boundary_node/anonymization/backend/Cargo.toml
rs/boundary_node/anonymization/backend/src/lib.rs
rs/boundary_node/anonymization/backend/src/registry.rs

This PR makes the canister periodically poll the registry to list the principles of known API Boundary Nodes. These are then used in ACLs to only allow access to the canister by those principals (will be added in a follow-up PR).

feat(BOUN-1236): add registry scraping for acls

---

rs/boundary_node/anonymization/backend/src/acl.rs
rs/boundary_node/anonymization/backend/src/lib.rs
rs/boundary_node/anonymization/backend/src/queue.rs

This change adds initial empty implementations for the canister methods and also adds authorization to the canister endpoints. A follow-up will add the relevant logic to the canister method implementations.

feat(BOUN-1236): add skeleton service methods and wrap with authorization

---

rs/boundary_node/anonymization/backend/src/lib.rs
rs/boundary_node/anonymization/backend/src/queue.rs

This change adds the core logic of the `register`, `query` and `submit` canister methods. Additionally, it adds a cron job in the canister to elect a new leader.

feat(BOUN-1236): add core logic impl to canister, add leader election cron

---

Cargo.lock
rs/boundary_node/anonymization/client/src/lib.rs

This change adds a `Tracker` implementation for the client of the canister. This allows one to instantiate a tracker that will follow the current secret value from the canister, as well as participate in leader duties for secret generation (i.e if you as a client have been chosen as a leader, you will be required to generate the salt and encrypt it for other peers).

feat(BOUN-1236): implement secret tracking

---

.github/workflows/container-mirror-images.json
ic-os/bootloader/build-bootloader-tree.sh
ic-os/bootloader/grub.cfg

This reverts commit c582bfe2cc97e2dc2d49a55d050dd452dda9dbfc because it breaks the hourly `//rs/tests/nested:...` system-tests since the `host-1` VM gets stuck on grub:
https://farm.dfinity.systems/group/registration--1731006619504/vm/host-1/console/
This is likely caused by [using](https://github.com/dfinity/ic/commit/c582bfe2cc97e2dc2d49a55d050dd452dda9dbfc#diff-6580a63795796c85f6d7ac9b194b7543ce61bed207dad770e648fa53bef72ad1R1) `$fw_path` in `grub.cfg`.
Schedule Hourly on this branch: https://github.com/dfinity/ic/actions/runs/11739921391

fix: revert "feat: [NODE-1521] Move bootloader off dockerhub (#2475)"

---

rs/boundary_node/anonymization/client/src/lib.rs

This is a fairly minimal change that adds throttling and logging to the canister methods in the client. Note we use `#[allow(clippy::disallowed_types)]` to not warn on using `tokio::sync::Mutex` as it's in the disallowed types list in `clippy.toml`. The reason we _do_ need to use the tokio mutex here is because it is being used in the throttling code and it needs to hold on to the lock until the throttling finishes (i.e it's not a quick lock/unlock, but rather can take a while).

feat(BOUN-1236): add logging and throttling to canister methods

---

ic-os/components/selinux/ic-node/ic-node.te
ic-os/components/selinux/misc-fixes/misc-fixes.te

- Allow `nftables` (`nft`) to read from `/dev/urandom`
- Allow `systemd-journald` to access procfs symlinks of the canister sandbox process (it is already allowed to access the actual process to log its errors, etc.)

fix(NODE-1522): fix permissions for nftables and systemd-journald

---

rs/canister_sandbox/src/replica_controller/process_exe_and_args.rs
rs/execution_environment/fuzz/BUILD.bazel
rs/execution_environment/fuzz/fuzz_targets/execute_subnet_message_update_settings.rs
rs/execution_environment/fuzz/fuzz_targets/execute_system_api_call.rs
rs/execution_environment/fuzz/src/lib.rs

- Add a new helper lib for fuzzers to invoke canister sandbox `//rs/execution_environment/fuzz:fuzzer_sandbox`
- Adapt existing fuzzers to use the `fuzzer_sandbox`

chore(fuzzing): enable canister sandboxing for fuzzers

---

testnet/tools/nns-tools/submit-mainnet-nns-upgrade-proposal.sh

This PR removes the `--use-explicit-action-type` option from the ic-admin command in submit-mainnet-nns-upgrade-proposal.sh as it has been deprecated.

fix(release-scripts): Remove deprecated `--use-explicit-action-type` from ic-admin command in submit-mainnet-nns-upgrade-proposal.sh

---

rs/tests/dashboards/IC/bitcoin.json

This PR updates 'Bitcoin' grafana dashboards for farm testnets to match prod.
Changes:
- allows to see metrics for bitcoin related canisters deployed on farm testnets
- improves readability of heatmap charts

chore: update bitcoin dashboards for farm testnets to match prod

---

rs/execution_environment/src/scheduler/test_utilities.rs
rs/execution_environment/tests/history.rs
rs/messaging/src/scheduling/valid_set_rule.rs
rs/messaging/src/scheduling/valid_set_rule/test.rs
rs/replicated_state/src/replicated_state.rs
rs/test_utilities/execution_environment/src/lib.rs

There is no need for it, an immutable reference will do.

refactor: Do not clone in `ReplicatedState::get_ingress_status()`

---

rs/tests/dashboards/IC/bitcoin.json

This PR adds insert rate charts to 'Bitcoin' dashboards on testnets to match prod.

feat: add insert rate charts to bitcoin dashboards on testnets 

---

rs/bitcoin/ckbtc/minter/ckbtc_minter.did
rs/bitcoin/ckbtc/minter/src/dashboard.rs
rs/bitcoin/ckbtc/minter/src/lib.rs
rs/bitcoin/ckbtc/minter/src/main.rs
rs/bitcoin/ckbtc/minter/src/metrics.rs
rs/bitcoin/ckbtc/minter/src/state.rs
rs/bitcoin/ckbtc/minter/src/updates/retrieve_btc.rs
rs/bitcoin/ckbtc/minter/tests/tests.rs

The `retrieve_btc_min_amount` setting was both used as a configuration and as a dynamically calculated value based on recent fees. This led to a problem that changing this setting through canister upgrades would be ineffective because it would be overwritten by the calculated value.
The fix is to introduce another `fee_based_retrieve_btc_min_amount` in the state to hold the calculated value, and let `retrieve_btc_min_amount` always retain its initial setting.

fix(ckbtc): Fix a problem with retrieve_btc_min_amount setting

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/common/rest.rs
packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/src/pocket_ic.rs

This PR adds the function `Topology::get_subnet` to the PocketIC library to get the subnet to which a canister belongs independently of whether the canister exists. Such a function is needed to migrate StateMachine tests to PocketIC since StateMachine test API exposes subnet IDs publicly independently of whether canisters are already deployed.

feat: add function Topology::get_subnet to PocketIC library

---

bazel/conf/.bazelrc.build
rs/execution_environment/fuzz/fuzz_targets/execute_subnet_message_update_settings.rs
rs/execution_environment/fuzz/fuzz_targets/execute_system_api_call.rs

This PR introduces a new `--config=sandbox_fuzzing` bazel flag to capture unique runtime env vars for fuzzers using canister sandboxing.
All env_vars will be now added in the `.bazelrc.build` file and sandbox fuzzers can be invoked with `--config=sandbox_fuzzing`.

feat(fuzzing): Introduce `--config=sandbox_fuzzing` bazel flag

---

rs/nns/governance/src/lib.rs

More precisely, midnight UTC.
The value used to be Nov 5 (one second after midnight). Thus, this value has been decreased by a couple of months or so.
Originally, I set it to Nov 5, because I figured that would be the earliest feasible date we could release the `Neuron.voting_power_refreshed_timestamp_seconds field`. But then, it was decided that legacy neurons should be "pre-aged" by a couple of months.
IIUC, the rationale for pre-aging is that it has been known for a long time that this feature would be implemented. Also, many neurons probably haven't taken any actions that would refresh voting power in a long time. Therefore, we want them to start losing voting power sooner than 6 months (but still leave plenty of time for them to act to maintain full potential voting power).
This is …

feat(nns): Changed the default "voting power refreshed" timestamp to Sep 1.

---

BUILD.bazel
ic-os/components/BUILD.bazel

This way the commit timestamp is regenerated whenever a new branch is checked out.

fix: Depend on .git/index in commit_timestamp_txt

---

publish/canisters/BUILD.bazel

1. Remove the tests on _uncompressed_ wasm sizes to test instead the size of compressed wasms, since compressed wasms should always be used. This affects the following canisters:
1. `ic-ckbtc-minter`
2. `ledger-canister`
3. `ledger-canister_notify-method`
2. Add a bound for the compressed wasm size of the new Bitcoin KYT canister (`//rs/bitcoin/kyt:btc_kyt_canister`).
3. Tighten the bound on the wasm size limit of `ic-ledger-suite-orchestrator-canister.wasm.gz` that was increased by #2451.

test: update test regarding limit of wasm sizes

---

rs/boundary_node/rate_limits/canister/canister.rs
rs/boundary_node/rate_limits/canister/state.rs
rs/boundary_node/rate_limits/canister_client/src/main.rs
rs/boundary_node/rate_limits/integration_tests/src/pocket_ic_helpers.rs
rs/boundary_node/rate_limits/integration_tests/tests/rate_limit_canister_tests.rs
rs/tests/boundary_nodes/rate_limit_canister_test.rs

With this [inspect_message()](https://internetcomputer.org/docs/current/developer-docs/backend/rust/message-inspect)  hook, the canister rejects ingress messages in the pre-consensus phase if:
- Called method is neither one of the `update` canister methods nor `get_config` replicated query
- Method's authorization policy is not fulfilled

feat(boundary): add `inspect_message` hook to canister

---

rs/types/types/src/exhaustive.rs

Currently, NiDkg transcripts are stored in the summary using `pb::TaggedNiDkgTranscript`, which contains the `pb::NiDkgTranscript` and the NiDkg tag. The latter data is redundant, as the NiDkg tag is also already part of `pb::NiDkgTranscript`. Therefore we should be able to replace `pb::TaggedNiDkgTranscript` with `pb::NiDkgTranscript` entirely.
To do this, we first need to tell the `cup_compatibility_test` that the current replica version only creates instances of `pb::TaggedNiDkgTranscript`, where `tagged_transcript.tag == tagged_transcript.transcript.tag`. Otherwise, the test would continue to create instances where this isn't the case. These instances of `pb::TaggedNiDkgTranscript` would not be correctly deserialized as `pb::NiDkgTranscript` once we make the switch in a future …

test: CON-1434 Prepare `cup_compatibility_test` for removal of `pb::TaggedNiDkgTranscript`

---

rs/execution_environment/benches/lib/src/wat_builder.rs
rs/execution_environment/benches/wasm_instructions/helper.rs

This PR simplifies the instruction benchmarks for Wasm64.

chore: EXC: Minor change to instruction benchmarks

---

rs/boundary_node/certificate_issuance/certificate_orchestrator/interface.did
rs/boundary_node/certificate_issuance/certificate_orchestrator/src/main.rs
rs/boundary_node/certificate_issuance/certificate_orchestrator/src/registration.rs
rs/boundary_node/certificate_issuance/certificate_orchestrator/src/work.rs
rs/boundary_node/certificate_issuance/certificate_orchestrator_interface/src/lib.rs

This change adds two canister methods:
- list_registrations
- list_tasks
which allow to examine the queue contents and the existing registrations.

chore(BOUN): Add debugging endpoints to certificate-orchestrator

---

rs/bitcoin/adapter/src/connectionmanager.rs

Essentially all version messages are invalidated on the bitcoin Testnet. This could be due to a multitude of reasons.
Adding some additional logging will help us find the root cause.

chore: add additional logging in the case when the version message is not valid

---

Cargo.lock
packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/lib.rs
rs/pocket_ic_server/BUILD.bazel
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/Cargo.toml
rs/pocket_ic_server/src/main.rs

This PR releases PocketIC server v7 and PocketIC library v6.

chore: release PocketIC server v7 and PocketIC library v6

---

rs/ledger_suite/common/ledger_canister_core/src/runtime.rs
rs/ledger_suite/icp/archive/src/main.rs
rs/ledger_suite/icp/index/src/main.rs
rs/ledger_suite/icp/index/tests/tests.rs
rs/ledger_suite/icp/ledger/src/main.rs
rs/ledger_suite/icp/ledger/tests/tests.rs
rs/ledger_suite/icrc1/archive/src/main.rs
rs/ledger_suite/icrc1/index-ng/src/main.rs
rs/ledger_suite/icrc1/index-ng/tests/tests.rs
rs/ledger_suite/icrc1/index/src/lib.rs
rs/ledger_suite/icrc1/index/tests/tests.rs
rs/ledger_suite/icrc1/ledger/src/main.rs
rs/ledger_suite/icrc1/ledger/tests/tests.rs
rs/ledger_suite/tests/sm-tests/src/metrics.rs

Rename the heap- and stable memory-related metrics for the ICP and ICRC ledger suite canisters. This will facilitate the alerting, since a general alert for canisters can be used for all canisters exporting the same metrics under the same names.

refactor(ICP_ledger): FI-1570: Rename ledger suite memory-related metrics

---

rs/tests/dashboards/IC/bitcoin-adapter.json
rs/tests/dashboards/IC/https-outcalls.json

This PR adds bitcoin adapter and http outcalls dashboards to farm testnets grafana.

chore: add bitcoin-adapter & http-outcalls dashboards to testnets grafana

---

rs/execution_environment/src/execution_environment.rs
rs/execution_environment/src/scheduler/tests.rs

After commit 672551d (RUN-305), priority credit and long execution mode are now persisted, allowing us to maintain them across checkpoints.
This should ensure progress for long execution messages competing for execution resources.

feat: EXC-1787: Don't apply priority credit on abort

---

rs/bitcoin/kyt/src/fetch.rs
rs/bitcoin/kyt/src/fetch/tests.rs
rs/bitcoin/kyt/src/main.rs

Remove the `cycles_available` method from `FetchEnv` and make the return result of `check_fetched` slightly more accurate.

refactor(ckbtc): minor refactor of FetchEnv

---

ic-os/components/setupos-scripts/functions.sh

When we get installation screen recordings from node providers, the error log often comes so fast that the previous logs don't show up on the console for a single frame. Adding a sleep helps ensure that the logs show up on the console before the error log comes and wipes it.

chore: Add log_and_halt_installation_on_error sleep

---

rs/nervous_system/common/src/lib.rs
rs/nervous_system/common/src/tests.rs
rs/nervous_system/integration_tests/tests/advance_target_version.rs
rs/nns/sns-wasm/src/pb/mod.rs
rs/nns/sns-wasm/src/sns_wasm.rs
rs/sns/governance/canister/canister.rs
rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/governance/tests/fail_stuck_upgrade_in_progress_tests.rs
rs/sns/governance/src/sns_upgrade.rs
rs/sns/governance/src/types.rs
rs/sns/governance/src/upgrade_journal.rs

This PR adds a new periodic task (or rather, a new thing to be called from our existing periodic task) that will initiate an upgrade when one is necessary.
At the time of writing the proto backwards compatibility checker is complaining about this:
```
ic_sns_governance/pb/v1/governance.proto:1427:5:Field "4" with name "proposal_id" on message "PendingVersion" changed cardinality from "optional with implicit presence" to "optional with explicit presence".
```
Which I don't really think is a real issue, so I'm tagging the PR with CI_OVERRIDE_BUF_BREAKING
[← Previous PR](https://github.com/dfinity/ic/pull/2453)

feat(sns): Automatically trigger upgrades when target_version is ahead of the current version

---

rs/nns/governance/src/governance.rs

The number of neurons keeps growing. Some analysis showed that we would be able to increase the limit to 420K. However, given that we are actively working on moving all neurons to stable storage, we would like to increase the limit in a more conservative way. The 380K limit should give us ~18 weeks.

feat(nns): Increase the neurons limit to 380K

---

.github/CODEOWNERS

The cross-chain team should co-own (together with IDX) `/rs/tests/cross_chain/`, similarly to other system tests. Initially, those tests were in `/rs/tests/src/cross_chain/`, but were moved as part of the inlining in #1957 and the ownership of `/rs/tests/src/cross_chain/` was removed in #2260.

ci: Fix `CODEOWNERS` for cross-chain team

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/proposals/mod.rs
rs/nns/governance/tests/proposals.rs

Whereas, before, we did not have a distinction between **potential** voting power vs. **deciding** voting power. When neurons refresh themselves, there is no difference between these. Whereas, when a neuron does not refresh itself recently enough, the amount of voting power in its ballots (its "deciding" voting power) is less than its potential voting power.
Suppose there are two neurons:
* A has 100 potential voting power, and refreshed recently, and as a result, its deciding voting power is also 100.
* B has 1000 potential voting power, but has not refreshed in a long time, and as a result, it's deciding voting power is just 500.
Then, the total potential voting power is 1100. If both neurons vote, then A gets 100 / 1100 of the reward purse, while B gets only 500 / 1100 of the reward …

feat(nns): Voting rewards are now in proportion to total *potential* voting power.

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/proposals/mod.rs
rs/nns/governance/tests/proposals.rs

This used to be part of https://github.com/dfinity/ic/pull/2385, but I was asked to not spin out sum_weighted_voting_power from distribute_rewards.

refactor(nns): Spin out sum_weighted_voting_power.

---

testnet/tools/nns-tools/list-new-commits.sh

The problem is that 10 characters is no longer enough for short commit IDs.

fix(governance): Fix list-new-commits.sh

---

ic-os/components/guestos.bzl
ic-os/components/misc/guestos/hsm/pcscd
ic-os/components/misc/hsm/pcscd
ic-os/components/selinux/misc-fixes/misc-fixes.te

NODE-1526
After the Ubuntu 20.04 --> 24.04 upgrade, we started getting pcscd errors that broke HSM onboardings:
We learned that the upgraded pcscd switched from using D-bus to polkit. We tried [adding the necessary rules to polkit to fix the permission issue](https://support.nitrokey.com/t/unpriviledged-service-account/6369), but were unable to resolve it.
As a quick fix, by disabling polkit, HSM onboardings are fixed.
With fix, successfully deployed node to production using HSM!

fix(node): HSM onboarding

---

rs/execution_environment/src/scheduler/round_schedule.rs
rs/execution_environment/src/scheduler/tests.rs

The logic of penalizing canisters for full execution and distributing the priority across the subnet has been moved to the end of the round. This change is necessary for priority-based eviction.
Newly created canisters join the first execution round with an accumulated priority of zero, which breaks two existing tests, but is not a practical issue. To compensate for this, during the reset round, we set the accumulated priority to the canister's compute allocation instead of the default zero priority.
There are also a few minor optimizations.

feat: EXC-1787: Penalize canisters at the end of the round

---

rs/bitcoin/adapter/src/blockchainmanager.rs
rs/bitcoin/validation/BUILD.bazel
rs/bitcoin/validation/src/header.rs

The bitcoin adapter has been stuck on the testnet on height `3229631` since November 4th. The reason was that because of a u32 subtraction underflow (see changes), it thought that the next correct block was invalid (because of insufficient PoW), hence it was rejecting all headers messages coming from all the peers. 
The reason it was underflowing was that the timestamp of [block `3229631`](https://blockstream.info/testnet/block/000000000000005ca13d4fc8bebb498e46dd764ec5f727ffff7ac9c90da8ed28) is actually smaller than the timestamp of [block `3227616`](https://blockstream.info/testnet/block/00000000084e1bbf6a418ef356f62ad38fdab345afe69baead9146fc41c65141), even if `3227616` comes 2015 blocks before `3229631`. 
2015 blocks is on average 2 weeks worth of mining, so these two blocks having a …

fix: stop doing u32 subtraction in bitcoin headers validation

---

rs/orchestrator/src/orchestrator.rs

Node providers have mistaken the initial logging-nodeID-and-version message as a 'successful onboarding' message. It is not. This log helps better clarify that confusion.

chore(node): add HostOS console message clarifying onboarding success

---

rs/execution_environment/src/lib.rs
rs/execution_environment/src/query_handler.rs
rs/execution_environment/src/query_handler/query_context.rs
rs/execution_environment/src/query_handler/tests.rs
rs/test_utilities/execution_environment/src/lib.rs
rs/tests/execution/inter_canister_queries_tests/call_on_cleanup.rs
rs/tests/execution/inter_canister_queries_tests/inter_canister_queries.rs

The legacy code for ICQC (inter-canister query calls), aka predecessor of composite queries, is still enabled in system and verified application subnets. There's only one actual user of this legacy feature and it's Distrikt. The new team that took over is going to migrate off of this legacy feature but some extra time is required. When this is done we can completely remove this legacy feature.
On the IC side, given the recent load issues we experienced on mainnet, we would like to open up some of the (currently) unused verified application subnets. However, we wouldn't want to open the door to this legacy feature (only composite queries should be used). To satisfy all requirements, the proposed change in this PR is to restrict the legacy feature only on Distrikt's subnet until the team …

feat: Restrict legacy ICQC code to one subnet

---

rs/sns/integration_tests/src/upgrade_canister.rs
rs/sns/test_utils/src/itest_helpers.rs

This PR ports the old upgrade canister integration tests to state machines' framework that is expected to be less flaky than `local_test` framework.
| [Next PR](https://github.com/dfinity/ic/pull/2661) >

test(sns): Port old upgrade canister integration tests to state machines

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/voting.rs

This puts cast_vote_and_cascade_follow into governance, which will be necessary for the next step of making it async, and then finally adding break points to increase the voting capacity.
[Prev](https://github.com/dfinity/ic/pull/2528) | Next

refactor(nns): Move cast_vote_and_cascade_follow into Governance struct

---

Cargo.lock
rs/bitcoin/ckbtc/minter/BUILD.bazel
rs/bitcoin/ckbtc/minter/Cargo.toml
rs/bitcoin/ckbtc/minter/src/lib.rs
rs/bitcoin/ckbtc/minter/src/main.rs
rs/bitcoin/ckbtc/minter/src/tasks.rs
rs/bitcoin/ckbtc/minter/src/tasks/tests.rs
rs/bitcoin/ckbtc/minter/src/test_fixtures.rs
rs/bitcoin/ckbtc/minter/src/tests.rs
rs/bitcoin/ckbtc/minter/src/updates/retrieve_btc.rs
rs/bitcoin/ckbtc/minter/src/updates/update_balance.rs

The tasks `ProcessLogic` and `RefreshFeePercentiles` are executed on a timer at different frequencies. Since #2435, the second task is also guarded by a `TimerLogicGuard`, which is the same type of guard used by `ProcessLogic`, meaning it could be the case that a task of type `RefreshFeePercentiles` prevents a task of type `ProcessLogic` from being executed, which is particularly the case upon canister initialization or upgrade as all tasks are scheduled at the same time.
This is problematic because the re-scheduling of a task of type `ProcessLogic` only happened _after_ having tried to obtain a `TimerLogicGuard`, meaning that in case this failed, due to for example the running of a `RefreshFeePercentiles`, the task `ProcessLogic`  would not be rescheduled.
The fix simply consists of …

fix(ckbtc): ensure tasks are always rescheduled

---

rs/tests/driver/src/driver/test_env_api.rs
rs/tests/system_tests.bzl

This stops supplying the sha256 of ic-os images to system tests. The sha256 is already included in the CAS URLs.
This simplifies the runtime environment setup for the tests.

chore(IDX): Don't specify sha256 twice

---

rs/boundary_node/rate_limits/api/src/schema_versions/v1.rs
rs/boundary_node/rate_limits/canister_client/src/main.rs
rs/tests/boundary_nodes/rate_limit_canister_test.rs

This definition would allow to `rate-limit` on multiple request types:
```
pub struct RateLimitRule {
...
pub request_types: Option<Vec<RequestType>>,
...
}
```

chore(boundary): adapt rate-limit rule definition

---

rs/boundary_node/rate_limits/api/src/lib.rs
rs/boundary_node/rate_limits/canister/fetcher.rs
rs/boundary_node/rate_limits/canister/interface.did
rs/boundary_node/rate_limits/canister/types.rs

This `is_redacted` flag helps the `ic-boundary` service determine whether its call to the `rate-limit` canister succeeded with full reader privileges.

chore(boundary): add flag to canister response

---

rs/consensus/src/dkg.rs
rs/consensus/src/idkg/utils.rs

This PR changes changes how to handle protobuf conversion errors in `inspect_idkg_chain_key_initializations`.
Initially, we would return an error on some occasions, while on others, we would panic via `expect`.
We would also simply ignore the `ChainKeyInitialization`, if there was a `Transcript` variant.
Now, we will always return an Error, if something unexpected happens.

fix(CON-1332): Handle ChainKeyInitializations conversion errors

---

rs/consensus/src/idkg/payload_builder.rs
rs/consensus/src/idkg/signer.rs
rs/consensus/src/idkg/test_utils.rs
rs/consensus/src/idkg/utils.rs
rs/crypto/benches/tecdsa.rs
rs/crypto/benches/tschnorr.rs
rs/crypto/internal/crypto_lib/threshold_sig/canister_threshold_sig/src/lib.rs
rs/crypto/internal/crypto_service_provider/src/vault/api.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tecdsa/mod.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tecdsa/tests.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tschnorr/mod.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tschnorr/tests.rs
rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/mod.rs
rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_client.rs
rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_server.rs
rs/crypto/test_utils/canister_threshold_sigs/src/lib.rs
rs/crypto/test_utils/local_csp_vault/src/lib.rs
rs/crypto/tests/canister_threshold_ecdsa.rs
rs/crypto/tests/canister_threshold_idkg.rs
rs/crypto/utils/canister_threshold_sig/src/lib.rs
rs/execution_environment/src/execution_environment.rs
rs/types/types/src/consensus/idkg/ecdsa.rs
rs/types/types/src/consensus/idkg/schnorr.rs
rs/types/types/src/crypto.rs
rs/types/types/src/crypto/canister_threshold_sig.rs
rs/types/types/src/crypto/canister_threshold_sig/idkg/proto_conversions.rs
rs/types/types/src/crypto/canister_threshold_sig/idkg/tests/proto_conversions.rs
rs/types/types/src/crypto/canister_threshold_sig/tests.rs
rs/types/types/src/crypto/vetkd.rs
rs/types/types/src/crypto/vetkd/test.rs

Moves the `ExtendedDerivationPath` from `ic_types::crypto::canister_threshold_sig` up one level to `ic_types::crypto`, because with the vetKeys feature, the type will no longer be used just for canister threshold signatures.

refactor(crypto): CRP-2598 move ExtendedDerivationPath to ic_types::crypto

---

rs/tests/driver/src/driver/test_env_api.rs

The backoff used in the test driver is constant, not linear:
```
exponential: |.|..|....|.........|
linear:      |.|..|...|....|.....|
constant:    |.|.|.|.|.|.|.|.|.|.|
```

fix: use appropriate backoff term

---

rs/tests/driver/src/driver/bootstrap.rs
rs/tests/driver/src/driver/test_env_api.rs

This changes the test driver to look up setupos dependencies (image, binaries) from the environment (`ENV_DEPS__SETUPOS_...`) instead of making assumptions about the paths where Bazel put the artifacts.

fix(IDX): look up setupos dependencies from environment

---

rs/replicated_state/src/canister_state/system_state.rs
rs/system_api/src/sandbox_safe_system_state.rs

This PR cleans up code in `reserve_cycles` and fixing some typos in comments.

chore: fixing typos and cleanups

---

rs/sns/integration_tests/src/proposals.rs
rs/sns/integration_tests/src/upgrade_canister.rs
rs/sns/test_utils/src/itest_helpers.rs

This PR ports the old proposal integration tests to state machines' framework that is expected to be less flaky than `local_test` framework.
< [Previous PR](https://github.com/dfinity/ic/pull/2660) |

test(sns): Port old proposal integration tests to state machines

---

rs/state_manager/src/tree_hash.rs

This is a preparation step for [making request metadata non-optional](https://github.com/dfinity/ic/pull/2622). This will ensure further changes to the hashes affected by this change are due to something else (in a followup).

chore: Always use request metadata in backward compatibility test

---

rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs

Preemptively top up ledger suite canisters before running upgrade/downgrade tests on them, so that they do not run out of cycles during the test, which would cause the test to fail.

test(ICRC_Ledger): FI-1580: Preemptively top of canisters in golden state test

---

rs/nervous_system/agent/src/nns/sns_wasm.rs
rs/nervous_system/agent/src/sns/archive.rs
rs/nervous_system/agent/src/sns/governance.rs
rs/nervous_system/agent/src/sns/mod.rs
rs/nervous_system/agent/src/sns/root.rs
rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/sns_ledger_upgrade.rs
rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
rs/sns/root/src/request_impls.rs

Advantages of this change:
1. It's less code to implement in ic-nervous-system-agent than it was in pocket_ic_helpers.
2. It's also more compact to call - you can do `sns.governance.get_mode(&pocket_ic)` rather than `sns::governance::get_mode(&pocket_ic, sns.governance.canister_id)`. (Notice how the pocket_ic_helpers implementation required writing `governance` twice, as well as saying `.canister_id`.)
3. The new implementation is more general - the type argument means that you can call it with anything that implements CallCanisters. Currently this is pocket_ic as well as ic-agent. This means that the method can be used in CLI tooling as well as in tests - facilitating code reuse.
Some of the changes in this PR are due to ic-nervous-system-agent previously not having a concept of archive …

refactor(test): Move some helpers from `pocket_ic_helpers.rs` to `ic-nervous-system-agent`

---

rs/nns/governance/benches/scale.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/voting.rs
rs/nns/governance/tests/degraded_mode.rs
rs/nns/governance/tests/fake.rs
rs/nns/governance/tests/fixtures/mod.rs
rs/nns/governance/tests/governance.rs

This gets us closer into the position where we can scale the voting calculations across multiple messages.
[Prev](https://github.com/dfinity/ic/pull/2600) | [Next](https://github.com/dfinity/ic/pull/2697)

refactor(nns): Make cast_vote_and_cascade_follow async 

---

rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/neuron_store/neuron_store_tests.rs
rs/nns/integration_tests/src/governance_migrations.rs
rs/nns/integration_tests/src/governance_neurons.rs
rs/nns/test_utils/src/state_test_helpers.rs

This change has 2 purposes:
* While the target neuron location criteria doesn't change (inactive neuron -> stable), some neurons can become inactive due to the passage of time, this change migrates those neurons to stable storage in a timer
* In the future, when the stable storage for active neurons is enabled, this change will also move the active neurons to stable storage in a similar fashion
* Removing a state machine test regarding neuron indexes. It is not useful anymore because the migration is over.
* Adding a similar state machine test for the current use case
* Adding the capability for moving a batch of neurons from heap memory to stable storage
* Schedule a timer to execute the migration code

feat(nns): Move inactive neurons in the heap to stable storage through a timer

---

packages/pocket-ic/src/nonblocking.rs
packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/test.rs

This PR fixes two sources of panics in PocketIC HTTP gateway flows:
- calling `PocketIc::make_live` twice in a row should not panic, but return the same URL of the gateway;
- making a POST request to the `/http_gateway` endpoint on the server specifying a port that is already in use should not crash the server.

fix: avoid panics in PocketIC HTTP gateway flows

---

rs/pocket_ic_server/src/state_api/state.rs

This PR replaces Instant by SystemTime in PocketIC auto progress mode so that time advances properly also if the server's machine is hibernated and Instant does not advance.

chore: use SystemTime instead of Instant in PocketIC auto progress mode

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/lib.rs

This PR adds the function `PocketIcBuilder::with_bitcoind_addrs` to specify multiple addresses and ports at which `bitcoind` processes are listening. This function is necessary for PocketIC integration into dfx.

feat: support for multiple bitcoind addresses in PocketIC library

---

.github/workflows/container-mirror-images.json

This will be used by #2304 to setup a SSL reverse proxy to connect to a local bitcoind, because https-outcalls require https.

chore: Add nginx-proxy to mirror images

---

MODULE.bazel

This will be used by #2304 to setup a SSL reverse proxy to connect to a local bitcoind, because https-outcalls require https.

chore: Create oci tarball for nginx-proxy

---

rs/p2p/quic_transport/src/connection_manager.rs
rs/p2p/quic_transport/src/metrics.rs

200 ms way to aggressive given we have 5 seconds to timeout the connection due to inactivity. Also the expectation is that transport is used continuously, so there won't be any periods of more than 1 second of inactivity.

fix: increase the keep alive probes.

---

rs/nervous_system/agent/src/lib.rs
rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/advance_target_version.rs

The test is simple - we deploy an SNS, add upgrade steps for all 6 canisters, then advance the target version, then check that the SNS eventually gets to the desired version.
This tests that advance-target-version's upgrade logic is capable of working for all 6 canisters, at least in a normal happy scenario.

test(sns): Add test that all SNS canisters can be upgraded using the advance-target-version mechanism

---

rs/ic_os/config/src/generate_testnet_config.rs
rs/ic_os/config/src/lib.rs
rs/ic_os/config/src/main.rs
rs/ic_os/config/src/types.rs

Renaming use_nns_public_key and use_node_operator_private_key to because 'exists' variables add a layer of indirection from the truth (which is whether the keys actually exist) but 'use' emphasizes that we are using these variable as access controls.

refactor(node): rename use_nns_public_key and use_node_operator_private_key

---

ic-os/docs/Network-Configuration.adoc
rs/ic_os/network/mac_address/README.md
rs/ic_os/network/src/lib.rs
rs/ic_os/network/src/systemd.rs

NODE-1527
Remove bonding. It's added complexity that we don't need.
I successfully testing on bare metal and networking still works 👍 
zh2-dll01 on master:
On branch:
----
GuestOS `$ ip a` output is unchanged

chore(node): remove setupos/hostos network bonding and clean up docs

---

rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
rs/config/src/embedders.rs

Avoid RSS-based eviction if there is sufficient memory (250 GiB or more). RSS statistics are updated asynchronously, and by default, we assume a worst-case scenario of 50 MiB per sandbox. Consequently, RSS-based eviction can often be unnecessarily pessimistic, negatively impacting the sandbox cache hit ratio.

feat: EXC-1774: Evict sandboxes based on the available memory

---

rs/replicated_state/src/canister_state/queues.rs
rs/replicated_state/src/canister_state/system_state.rs
rs/replicated_state/src/canister_state/tests.rs
rs/replicated_state/tests/system_state.rs

`CanisterQueues` checks against duplicate responses for a given callback, but relies on `SystemState` to ensure that these are existent callbacks (other than the potential paused or aborted execution). `SystemState` already made this check this in `push_input()`. Also do the check in `induct_messages_to_self()`.

fix: Drop duplicate responses in `induct_messages_to_self`

---

rs/execution_environment/fuzz/BUILD.bazel
rs/execution_environment/fuzz/fuzz_targets/execute_system_api_call.rs
rs/state_machine_tests/src/lib.rs

Currently, the StateMachine sets `log_level: None` by default and switches it to `Warning` in `fn replica_logger`, which is counterintuitive. The PR addresses it by setting the value default to `Some(Level::Warning)` and if `None` is passed, `no_op_logger` is used.
This is required for fuzzing, since we maintain a StateMachine invocation in a global state and would need to reduce it's memory footprint as much as possible for fuzzing long hours.

chore(fuzzing): Allow `no_op_logger` in StateMachine

---

rs/ingress_manager/src/ingress_selector.rs

We can compute the number of ingress messages by calling `len` instead

chore(consensus): remove unnecessary variable in ingress selector

---

rs/replicated_state/src/replicated_state.rs
rs/replicated_state/tests/replicated_state.rs

Time out best-effort requests in subnet input queues and responses in subnet output queues.
The management canister does not make outgoing calls as itself, so there are no requests in subnet output queues or responses in subnet input queues. Meaning that there are also no `SubnetCallContextManager` callbacks to time out.
We already shed messages from subnet queues, so this is the last missing piece of the puzzle in terms of best-effort message shedding and expiration.

feat: [MR-627] Time out messages in subnet queues

---

rs/tests/driver/src/driver/test_env_api.rs

This ensures stderr is printed when building the uvm docker image (on errors). This makes debugging failures in the image build much easier.

fix(IDX): print stderr from uvm docker build

---

testnet/tools/nns-tools/README.md

In particular, the instructions are now more amenable to copy n' paste. At the top of each chunk of commands, there are some variables that the user (i.e. release tsar) fills in. Then, the rest of the commands in the chunk can be run **_without modification._**
Now that no manual work is needed to generate a complete proposal summary file, we could merge the steps where proposal texts are created vs. when they are submitted. Both could be done from a single script. All it would have to know is
1. What is the release candidate commit ID.
2. Which canisters.
3. The ID of the neuron that will submit the proposals.
This could further be merged with list-new-commits, but we would only want to do that if we trust list-new-commits to decide which canisters to release.
At this point, I would say …

docs(governance): More streamlined procedure for generating and submitting proposals.

---

rs/ethereum/cketh/minter/cketh_minter.did
rs/ethereum/cketh/minter/src/dashboard/tests.rs
rs/ethereum/cketh/minter/src/endpoints.rs
rs/ethereum/cketh/minter/src/main.rs
rs/ethereum/cketh/minter/src/state/eth_logs_scraping/mod.rs
rs/ethereum/cketh/minter/src/state/eth_logs_scraping/tests.rs
rs/ethereum/cketh/minter/templates/dashboard.html
rs/ethereum/cketh/minter/tests/ckerc20.rs
rs/ethereum/cketh/minter/tests/cketh.rs

The helper smart contract supporting subaccount is the new preferred way to do deposit, both of ETH and ERC-20. The 2 previous helper smart contracts are therefore deprecated. Concretely,
1. The status (active or deprecated) of a helper smart contract is added to the minter dashboard.
2. In case the address of the helper smart contract supporting subaccount is set, the minter endpoints to retrieve the state of a scraping (contract address and last scraped block number) for deposit of ETH and ERC-20 will be that of the new helper smart contract supporting subaccount. 
3. The field `last_deposit_with_subaccount_scraped_block_number` was removed. This is not a breaking change since it was never deployed in production.

refactor(cketh/ckerc20): mark older helper smart contracts as deprecated

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
Cargo.toml
bazel/external_crates.bzl
ic-os/boundary-guestos/context/Dockerfile
rs/boundary_node/ic_boundary/Cargo.toml

Also bump `rustls` minor as `ic-bn-lib` needs it.

chore: bump ic-bn-lib & ic-gateway

---

BUILD.bazel
ic-os/components/BUILD.bazel

This change will hopefully resolve the issues people were having with this target (the target was recomputed or not recomputed unexpectedly).

fix: Depend on //:bazel-timestamp instead of //:.git/index when calculating commit_timestamp_txt

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs
packages/pocket-ic/tests/tests.rs

This PR supports PocketIC handle creation for an existing PocketIC instance. This is necessary for using the PocketIC library in dfx since dfx creates a PocketIC instance in a separate process than the process making a request to the PocketIC instance.

feat: create PocketIC handle for existing PocketIC instance

---

bazel/upload_systest_dep.sh

This adds some pretty printing to the curl upload metrics:
```
Uploaded 376MiB in 1.804778s (209MiB/s)
```

chore(IDX): pretty print systest dep upload metrics

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/neuron_store/benches.rs

There was a recent regression on how we list neurons ready to unstake maturity or spawn. Adding benchmarks for those will help prevent them in the future (although, currently they are not enabled in CI yet).
Adding benchmarks for `list_ready_to_spawn_neuron_ids` and `list_neurons_ready_to_unstake_maturity`. Additional dimensions are: (1) whether the "active neuron in stable memory" is enabled (2) whether there are actually meaningful return value.
When running against changes in https://github.com/dfinity/ic/pull/2726 , we get the following results:
---------------------------------------------------
Benchmark: list_ready_to_spawn_neuron_ids_heap
total:
instructions: 455.22 K (improved by 86.76%)
heap_increase: 0 pages (no change)
stable_memory_increase: 0 pages (no change) …

perf(nns): Add benchmarks for periodic tasks

---

rs/tests/driver/src/driver/test_env_api.rs

This fixes a hostos image lookup function. The function previously tried to read the URL as a local (run)file.

fix(IDX): read hostos URL directly

---

rs/nns/governance/src/neuron_store.rs

Given the recent finalization rate drop while the NNS subnet had a sustained 2B instructions per round, and the migration can run every 5 seconds, we should lower the max instructions consumed by the task, just to be safe.

feat(nns): Adjust batch limit for moving neurons to stable memory

---

bazel/upload_systest_dep.sh

This defines all variables in `upload_systest_dep`. Two variables were not defined at the first use site due to a last minute refactoring.
This PR also enables `set -u` which will ensure that bash fails if a variable is used before being defined. This should have been enabled when the changes were first introduced; this was an oversight.

fix(IDX): Ensure upload_systest_dep variables are defined

---

rs/sns/governance/src/governance.rs
rs/sns/governance/src/governance/advance_target_sns_version_tests.rs
rs/sns/governance/src/proposal.rs
rs/sns/governance/src/proposal/advance_sns_target_version.rs

This PR slightly refactors the validation logic at `AdvanceTargetVersion.new_target` proposal submission time, and uses the same validation at execution times. The state of the SNS can change between those two time points, therefore re-validation is required.

feat(sns): Unify validation of `AdvanceTargetVersion.new_target` at proposal submission and execution times

---

rs/replicated_state/src/canister_state/queues.rs

Clarify which canister messages expire; that `try_push_deadline_expired_input()` only applies to best-effort callbacks; and that it's safe to only check for duplicates when enqueuing a reject response for a dropped outbpund request.

docs: Improve documentation around message and callback expiry

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/common/rest.rs
packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs

This PR adds the PocketIC library functions `PocketIc::update_call_with_effective_principal` and `PocketIc::query_call_with_effective_principal` for making generic calls (including management canister calls).

feat: PocketIC library functions for generic calls

---

.github/workflows-source/ci-pr-only.yml
.github/workflows/ci-pr-only.yml

This PR is a necessary step before making `CI PR Only` required / mandatory on PRs. 
Currently, when a workflow is marked as required for PR, it is also enforced on the merge queue as well which can block the queue. However, these jobs are only needed to gate the merge. Hence, we allow the workflow to run on `merge_group` but each individual job is not run by adding ` if: ${{ github.event_name != 'merge_group' }}`

chore(ci): Make `CI PR Only` mandatory for PRs

---

packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs

This PR makes the function `PocketIc::new_from_existing_instance` blocking since its implementation is already blocking and thus declaring it `async` is unnecessary and prevents its invocation in blocking code.

chore: make PocketIc::new_from_existing_instance blocking

---

.github/workflows/system-tests-k8s.yml

Run hourly system tests always (we want to run this after PR related tests but we don't care if that CI job fails).

chore(system-tests-k8s): always run hourly

---

rs/types/types/src/crypto/vetkd.rs
rs/types/types/src/crypto/vetkd/test.rs

Renames `VetKdArgs::encryption_key` to `VetKdArgs::encryption_public_key` to avoid confusions as to whether this is the private or the public part of an asymmetric encryption key pair and thus to make clear that this is not sensitive information.

refactor(crypto): CRP-2596 rename VetKdArgs::encryption_key to encryption_public_key

---

.devcontainer/devcontainer.json

Using the global search function in VScode is quite slow, as it indexes order of gigabytes worth of files from the bazel output directories. This PR excludes bazel directories from search to make the search times tolerable.

chore: speed up searching in VScode

---

.devcontainer/devcontainer.json

The extension `better-toml` is deprecated and the maintainer recommends to switch to `even-better-toml`. See README https://github.com/bungcip/better-toml/blob/master/README.md.
This PR replaces `better-toml` with `even-better-toml` ast the installed extension in our dev containers.

chore: Replace better-toml extenstion with even-better-toml

---

rs/sns/governance/src/governance.rs
rs/sns/governance/src/governance/advance_target_sns_version_tests.rs
rs/sns/governance/src/governance/assorted_governance_tests.rs
rs/sns/governance/src/governance/fail_stuck_upgrade_in_progress_tests.rs
rs/sns/governance/src/governance/test_helpers.rs

This PR contributes unit tests of the whole automatic-upgrade process (as triggered by target_version being set). It adds a test for Governance and Root.
Certain scenarios are much easier to test via unit testing. These tests lay the groundwork for a test I want to write which will exercise edge cases w.r.t. archive canisters, which are too hard to exercise in an integration test

test(sns): Add unit tests for automatic upgrades triggered when target version ahead of deployed version

---

rs/sns/cli/src/health.rs

Example output:
| Name                    | Memory              | Cycles                                                                                                                         | Upgrades Remaining |
|-------------------------|---------------------|--------------------------------------------------------------------------------------------------------------------------------|--------------------|
| BOOM DAO                | 👍                   | ❌ governance: (6.96 TC), index: (0.00 TC 🥶) | 24                 |
| CYCLES-TRANSFER-STATION | 👍                   | 👍                                                                             | 8                  |
| Catalyze                | 👍                   | ❌ governance: (9.76 TC), swap: (8.83 TC), archive: (9.30 TC) …

feat(sns): Add indication of whether a canister is frozen in `sns health`

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/governance/benches.rs

A last minute change to NeuronBuilder caused the benchmark to be incorrectly constructed.  This adds the field ` neuron.recent_ballots_next_entry_index = Some(0);` to the neurons so that the typical migration is not performed.

chore(nns): Fix benchmark test

---

rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/storage/neurons.rs
rs/nns/governance/src/storage/neurons/neurons_tests.rs

Instead, callers should use either NeruonSections::ALL or NeuronSections::NONE. It is very easy for a caller to think NeuronSections::default() is equivalent to ALL, when **_actually_**, it's equivalent to NONE. Whereas, it is basically impossible to misunderstand what ALL and NONE do.
Earlier, this PR tried to add support for sections to neuron range. But Max developed that independently/concurrently, and he was able to merge first. Therefore, the main change that I was originally trying to do has been removed from this PR. What remains is
1. Additional tests
2. `NeuronSections::ALL`, a constant that replaces `NeuronsSections::all` (an `fn`).
3. Added `NeuronSections::NONE`.
In terms of interface, the difference between what I did vs. what Max merged is that I figured that there should …

refactor(governance): NeuronSections no longer implements default.

---

rs/sns/governance/src/governance.rs
rs/sns/governance/src/governance/advance_target_sns_version_tests.rs
rs/sns/governance/src/governance/assorted_governance_tests.rs

In the very unlikely event of the time being close to u64::max, the upgrade lock would get permanently stuck. This PR changes it so that it is instead permanently un-stuck and adds a test for this edge case.

fix(sns): Don't permanently get the upgrade lock stuck in the event of overflow

---

rs/nervous_system/agent/src/agent_impl.rs
rs/nervous_system/agent/src/lib.rs
rs/nervous_system/agent/src/null_request.rs
rs/nervous_system/agent/src/pocketic_impl.rs
rs/nervous_system/agent/src/sns/governance.rs
rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/sns_lifecycle.rs

The `Request` trait in ic_nervous_system_clients is overly restrictive, as it assumes that all canister endpoints take exactly one argument. This is the case 99% of the time for our canisters, so it's nice to have, but for those cases where a canister endpoint takes 0 arguments, it's we need a more general option. This PR adds a trait that is flexible w.r.t. the number of argument, and makes use of it in ic_nervous_system_agent. There is also a blanket implementation, so anything that implements the old trait also implements the new trait.  
This adds a small amount of unfortunate complexity, but the benefit is large, because it means that we can now use CallCanisters for types which we could not implement `ic_nervous_system_clients::Request` for. I demonstrate this by adding a …

refactor(nervous_system_agent): Make CallCanisters implementation slightly more generic

---

rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron/types/tests.rs
rs/nns/governance/src/neuron_store.rs

The `list_ready_to_spawn_neuron_ids` implementation is unnecessarily complex.
* Refactor neuron spawn timestamp check logic into a `Neuron` method
* Add unit tests for `Neuron::ready_to_spawn`
* Add unit tests for `Neuron::ready_to_unstake_maturity` while we are at it

refactor(nns): Refactor neuron spawn timestamp check to Neuron::ready_to_spawn

---

rs/execution_environment/fuzz/fuzz_targets/execute_subnet_message_update_settings.rs

This is a regression from #2816 which broke `execute_subnet_message_update_settings`. The failure was caught on the hourly fuzzer [pipeline](https://github.com/dfinity/ic/actions/runs/12035541363) (CI for PRs don't run the fuzzers).

chore(fuzzing): set `with_precompiled_universal_canister` to `false` for `execute_subnet_message_update_settings`

---

rs/nns/governance/src/neuron_store.rs

An incorrect line made it into a previous PR, which caused a 43x performance regression in calculating ballots: 
Previous PR: https://github.com/dfinity/ic/pull/2470/files

fix(nns): Fix incorrectly modified line from NeuronSections PR

---

rs/nns/governance/BUILD.bazel
rs/nns/governance/canbench/canbench_results.yml

Avoid performance regressions by adding a test which will fail if the benchmark results change (currently, by 2%)
1. Run `bazel run //rs/nns/governance:governance-canbench_update` to update the results file
2. Add `add_test = True` for generating a test target to check if the results file is up to date
3. Add a comment about the new test target

perf(nns): Update canbench_results.yml for NNS Governance and turn on test

---

rs/recovery/src/file_sync_helper.rs
rs/recovery/src/steps.rs

We've recently set up the GuestOS so that the we always have a recovery directory in `var/lib/ic/data/ic_state`, which `ic-recovery` uses by default (see https://github.com/dfinity/ic/pull/2131). 
During clean-up, ic-recovery attempts to completely delete the directory, which results in a permission error. Instead, we should simply clear the directory's contents.

fix(recovery): Clear recovery directory instead of deleting it

---

rs/sns/governance/canister/canister.rs
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs

Needed for easy testing of the AdvanceSnsTargetVersion feature

feat(test): Add test-only endpoint to refresh cached upgrade steps

---

buf.yaml

The exception was added [here](https://github.com/dfinity/ic/pull/2622) to enable a specific change. After merging it, it should be removed.

chore: Removes an exception in buf.yaml

---

rs/replica/setup_ic_network/src/lib.rs

The feature has been already enabled for all subnets (for some subnets already over a month ago) except the NNS subnet and no issues have been observed.

feat: enable the hashes-in-blocks feature everywhere

---

rs/state_manager/src/lib.rs

When we create a checkpoint, we have two versions of `ReplicatedState`: one that we loaded from disk and one came from execution (updated to the new files). These two must be the same and we have a validation to raise a critical error if they diverge.
This change eliminates `checkpointed_state`, so we have only one.

feat: Unify checkpointed_state and state in commit_and_certify

---

rs/canister_sandbox/bin/test_controller.rs
rs/canister_sandbox/bin/test_sandbox.rs
rs/canister_sandbox/src/protocol/sbxsvc.rs
rs/canister_sandbox/src/sandbox_client_stub.rs
rs/canister_sandbox/src/sandbox_manager.rs
rs/canister_sandbox/src/sandbox_server.rs
rs/canister_sandbox/src/sandbox_service.rs

Now that we have a separate compilation sandbox, we can deprecate the IPC requests for compiling in the canister sandbox.

chore(EXC): Remove IPC calls for compliation in canister sandbox

---

rs/nns/governance/tests/governance.rs

The behavior was already implemented, but not intentionally. Therefore, this only adds asserts to verify that we (already) have the desired behavior.

test(nns): Daughter neurons should have fresh voting power.

---

.github/workflows/test-namespace-darwin.yaml

Namespace runners are not configured for our private repo, so these CI jobs get stuck otherwise.

chore(IDX): update darwin workflow

---

rs/tests/driver/src/driver/bootstrap.rs

This PR ensures that the root subnet is the first system subnet. Currently, it is not possible to use `use_specified_ids_allocation_range` with multiple system subnets since the specified ids allocation large is set for the first system subnet while the root subnet is the last system subnet.

fix: make sure the root subnet is the first system subnet

---

.github/workflows/tag-release.yml

After reviewing the code and testing this out in a separate repo, I've determined the token is not actually needed here - we already enable write permissions in this workflow.

chore(IDX): remove token from tag-release workflow

---

rs/nns/sns-wasm/src/sns_wasm.rs

#2837 made  `UpgradeSteps::add_wasm` return a result type, even though it cannot fail. This PR undoes that change. This results in a simplification of the other `add_wasm` function.

refactor(sns-w): `UpgradeSteps::add_wasm` is infallible and so should not return a Result

---

rs/sns/governance/src/cached_upgrade_steps.rs
rs/sns/governance/src/governance/advance_target_sns_version_tests.rs
rs/sns/governance/tests/governance.rs

An upgrade path with duplicate versions from SNS-W would almost certainly be erroneous, and likely to cause the SNS to enter an infinite upgrade loop, which could be unrecoverable. We also may make the assumption in various places that the upgrade steps will not have duplicates, so it's good to enforce that. 
[← Previous PR](https://github.com/dfinity/ic/pull/2836)

fix(sns): SNS Gov should not accept an upgrade path from SNS-W that contains duplicate versions

---

rs/sns/governance/src/governance.rs
rs/sns/governance/src/upgrade_journal.rs

This improves organization because now all the upgrade_journal logic is collected in the same file. This is just a move, no behavior was changed.

refactor(sns): Move get_upgrade_journal to upgrade_journal.rs

---

rs/sns/governance/src/governance.rs
rs/sns/governance/src/proposal/advance_sns_target_version.rs

The previous error messages could be misleading since they talked about there being "no upgrade steps remaining" (when really it is possible that the cache is just out of date), or overly expose implementation details. This PR enhances them slightly to be more informative.

fix(sns): Improve validate_new_target_version error messages

---

.vscode/settings.json
rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/advance_sns_target_version.rs
rs/sns/governance/canister/canister.rs
rs/sns/governance/src/cached_upgrade_steps.rs
rs/sns/governance/src/cached_upgrade_steps/tests.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/governance/advance_target_sns_version_tests.rs
rs/sns/governance/src/governance/assorted_governance_tests.rs
rs/sns/governance/src/proposal/advance_sns_target_version.rs
rs/sns/governance/src/sns_upgrade.rs
rs/sns/governance/tests/governance.rs

This PR refactors the SNS Governance to reset cached upgrade steps earlier, as soon as an inconsistency or missing data is detected. This simplifies the implementation of a few periodic functions since they can rely on the data being available.
The behavior is slightly affected, as the first upgrade journal entry for a newly deployed SNS is expected to be a cache _reset_ rather than a cache refresh.

refactor(sns): Reset cached upgrade steps upon detecting inconsistencies

---

.github/workflows/rosetta-release.yml

The wrong variable was being read in the ICRC Rosetta release workflow, leading to a docker release with a tag "v" being [created](https://hub.docker.com/layers/dfinity/ic-icrc-rosetta-api/v/images/sha256-d6c959f579d7827c53abd5c3d4d3a32c73046f312033a4146541b8e2e5256f26?context=explore). This PR proposes reading the `ICRC_ROSETTA_RELEASE_VERSION` variable in the case of ICRC Rosetta.

fix(ICRC_Rosetta): Set the ICRC Rosetta version correctly in the docker tag

---

ci/scripts/rust-benchmarks.sh
ic-os/components/monitoring/filebeat/filebeat.yml.template
rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs
rs/tests/consensus/utils/src/performance.rs
rs/tests/driver/src/driver/test_env_api.rs
testnet/env/shared-config.yml

This needs to be done due to the deprecation of the SF1 DC where the current elasticsearch clusters are. The new ES clusters will be brought up in a few weeks, in DM1 DC.

fix: Update Elasticsearch URLs and index patterns for testnet environment

---

bazel/conf/.bazelrc.build

Since we upload the systest dependencies separately, we don't need to ensure that bazel uploads built artifacts to the remote cache.

chore(IDX): don't force upload build results for systests

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/governance/merge_neurons.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron/types/tests.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/tests/fixtures/mod.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/tests/merge_neurons.rs
rs/nns/integration_tests/test_canisters/governance_mem_test_canister.rs

Closes https://dfinity.atlassian.net/browse/NNS1-3430

feat(nns): Added (potential|deciding)_voting_power fields to API.

---

Cargo.lock
rs/sns/governance/BUILD.bazel
rs/sns/governance/Cargo.toml
rs/sns/governance/src/proposal.rs
rs/sns/governance/src/proposal/advance_sns_target_version.rs

This PR improves the rendering of AdvanceSnsTargetVersion proposals by using a human-readable date-time format rather than raw Unix timestamps. Also, a potentially confusing remark is dropped from the disclaimer.

feat(sns): Use human readable date-time in AdvanceSnsTargetVersion proposal rendering

---

rs/ethereum/cketh/minter/cketh_minter.did
rs/ethereum/cketh/minter/src/endpoints.rs
rs/ethereum/cketh/minter/src/main.rs
rs/ethereum/cketh/minter/src/state/eth_logs_scraping/mod.rs
rs/ethereum/cketh/minter/src/state/eth_logs_scraping/tests.rs
rs/ethereum/cketh/minter/tests/ckerc20.rs
rs/ethereum/cketh/minter/tests/cketh.rs

Fix an undesired breaking changed introduced by #2747 :
1. The fields `eth_helper_contract_address` and `erc20_helper_contract_address` in `get_minter_info` were wrongly reused to point to the new helper smart contract [0x18901044688D3756C35Ed2b36D93e6a5B8e00E68](https://etherscan.io/address/0x18901044688D3756C35Ed2b36D93e6a5B8e00E68) that supports deposit with subaccounts and that was added as part of proposal [134264](https://dashboard.internetcomputer.org/proposal/134264).
2. This broke clients that relied on that information to make deposit of ETH or ERC-20 because the new helper smart contract has a different ABI. This is visible by such a [transaction](https://etherscan.io/tx/0x0968b25814221719bf966cf4bbd2de8290ed2ab42c049d451d64e46812d1574e), where the transaction tried to call the …

fix(cketh): Undo breaking change in `get_minter_info`

---

rs/sns/governance/src/lib.rs
rs/sns/governance/src/proposal.rs

If a governance error is too large (over 2 MiB), it cannot be sent back to the client, and the replica just drops the error with the following symptoms, e.g.: 
```
Canister violated contract: ic0.msg_reply_data_append:
application payload size (3043594) cannot be larger than 2097152.
Consider checking the response size and returning an error if it is too long.
See documentation:
http://internetcomputer.org/docs/current/references/execution-errors#msg_reply_data_append-payload-too-large
```
This PR bounds the maximum size of errors that can be produced upon `UpgradeSnsControlledCanister` proposal invalidation. In particular, SNS Governance no longer incorporates the entire (invalidated) WASM bytes string into validation errors. 
Additional measures are taken to bound the maximal byte size …

fix(sns): Avoid producing overly large errors upon `UpgradeSnsControlledCanister` proposal invalidation

---

rs/rosetta-api/icp/BUILD.bazel

On 2024-11-15 the `//rs/rosetta-api/icp:icp_rosetta_system_tests_tests` was marked as flaky in  https://github.com/dfinity/ic/pull/2615 and then became our most flaky test.
See: https://superset.idx.dfinity.network/explore/?slice_id=83
This is an experiment to see if lowering parallelism and increasing its CPU reservation lowers the flakiness of this test.

test(IDX): lower parallelism and reserve more CPUs for the //rs/rosetta-api/icp:icp_rosetta_system_tests_tests

---

rs/tests/consensus/orchestrator/node_reassignment_test.rs
rs/tests/consensus/utils/src/node.rs

In the `node_reassignment_test` we want to verify that a node's state is correctly delete during unassignment. In https://github.com/dfinity/ic/pull/2720 we therefore added an assertion checking that the state of unassigned nodes is empty. Technically, this check would also succeed if the state never existed in the first place.
For that reason, this PR adds an assertion to make sure that the state exists before unassignment, and no longer exists afterwards. Additionally, we extend the assertion to not only check the node state, but also the orchestrator's local CUP file.

test: CON-1440 Assert that a subnet state exists on the node before it is deleted

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/neuron_store.rs

As neurons will be moved to stable memory, listing neuron ids that are ready to spawn/unstake maturity will be more computationally intensive and we should optimize them.
1. Only read the main section of the neuron for those 2 situations
2. Update benchmark results
[Prev](https://github.com/dfinity/ic/pull/2812)

feat(nns): Improve listing neuron ids performance by reading the main section only

---

rs/tests/driver/src/driver/group.rs

https://github.com/dfinity/ic/pull/2855 changed the format of [systemd-journal-gatewayd's Range header](https://www.freedesktop.org/software/systemd/man/latest/systemd-journal-gatewayd.service.html#Range%20header) which broke fetching logs of UniversalVMs in system-tests. This PR fixes that.

fix(IDX): use correct Range header when fetching logs from gatewayd from UVMs

---

rs/nervous_system/string/src/lib.rs
rs/nervous_system/string/src/tests.rs

This PR fixes a potential panic in `clamp_string` that could occur due to string indices not being mapped 1:1 to Rust `char`s.

fix(nervous-system): Ensure clamp_string works on arbitrary unicode inputs

---

rs/boundary_node/anonymization/backend/src/lib.rs

This adds an `inspect_message` endpoint with authorization so that the canister can't be DDoSed.

fix(BOUN-1302): authorize to avoid cycle exhausion

---

rs/types/error_types/src/lib.rs

This PR adds a test that the reject code can be derived from the leading digit of an error code.

test: deriving reject code from error code

---

ci/scripts/rust-lint.sh

This defaults the working directory of the lint script to the root of the git repo, in case `CI_PROJECT_DIR` is not set.
Before this, the variable `CI_PROJECT_DIR` would be read, which is only set on CI. By adding a default, the script can be run locally.

fix(IDX): Add default directory for lint script

---

.github/workflows/rosetta-release.yml

Align the git tag set by the ICRC Rosetta release workflow to match the pattern used for previous releases, i.e., `rosetta-icrc-release-X.Y.Z`.

fix(ICRC_Rosetta): Align ICRC Rosetta release tag

---

bazel/upload_systest_dep.sh

In system-tests, the image upload sometimes fails. For example:
```
$ ict test //rs/tests/consensus/subnet_recovery:sr_app_same_nodes_test
Raw Bazel command to be invoked: 
$ bazel test //rs/tests/consensus/subnet_recovery:sr_app_same_nodes_test --config=systest --cache_test_results=no
INFO: Invocation ID: 075ad521-6af0-4c9b-a0d4-37b0024ff087
INFO: Streaming build results to: https://dash.idx.dfinity.network/invocation/075ad521-6af0-4c9b-a0d4-37b0024ff087
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed target //rs/tests/consensus/subnet_recovery:sr_app_same_nodes_test (0 packages loaded, 0 targets configured).
Found dep to upload ic-os/guestos/envs/dev/disk-img.tar.zst …
```

chore(IDX): in system-tests, show error when uploading the image fails & retry up to 3 times

---

ic-os/components/upgrade/shared-resources/upgrade-shared-data-store/upgrade-shared-data-store.service
ic-os/components/upgrade/shared-resources/upgrade-shared-data-store/upgrade-shared-data-store.sh

A bad check in `upgrade-shared-data-store.sh` was causing a `chown -R` to run across all of `/var/lib/ic/data`. This would then also create additional work for `setup-permissions.sh`.
With this fix, the broad `upgrade-shared-data-store.sh` should only run rarely. Though `setup-permissions.sh` will still scan parts of `/var/lib/ic/data`, it will need to change less permissions which should hopefully be an improvement as well.

fix: [NODE-1519] Fixup colliding permission services

---

ic-os/components/monitoring/fstrim/fstrim_tool.service
rs/ic_os/fstrim_tool/src/lib.rs
rs/ic_os/fstrim_tool/src/main.rs
rs/ic_os/fstrim_tool/src/tests.rs
rs/ic_os/fstrim_tool/tests/integration_tests.rs

NODE-1534
For unassigned nodes, issue NVMe `discard` commands via `fstrim` on the replica data partition

feat(NODE-1534): discard for data partition

---

rs/tests/message_routing/global_reboot_test.rs

The changes in https://github.com/dfinity/ic/pull/806 missed updating the arguments to the start function of the xnet canister in a system test. This PR fixes the issue.

fix: Update argument to start function of xnet canister in global reboot test

---

rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/tests/governance.rs

As we plan to move neurons to stable storage, the cost for scanning neurons to spawn will increase (80x). Therefore, to keep the average instruction count similar, we reduce its frequency (twice per second -> once every minute)
* Schedule a timer to run `maybe_spawn_neurons()` every minute
* Remove `spawn_neurons` from heartbeat
Verified that `bazel test //rs/nns/integration_tests:integration_tests_test_src/governance_neurons --test_filter=test_spawn_neuron` fails if the `spawn_neurons` is removed from heartbeat but not added to timer

feat(nns): Move spawn_neurons to a one-minute timer

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/neuron_store/benches.rs

Drawing maturity from neurons fund requires iterating through neurons, and that can be expensive when we move neurons to stable structures. Therefore we want a benchmark so that the future improvements can be measured and regressions can be prevented.

perf(nns): Add a benchmark for drawing neurons fund maturity

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/neurons_fund.rs
rs/nns/governance/src/storage/neurons.rs

Drawing/refunding neurons fund maturity iterates through many neurons and modify them, and can be more expensive when neurons are all moved to stable structures. Therefore we want to improve the performance by accessing the main section directly.
* Refactor the existing logic to modify maturity into `modify_neuron_maturity`
* Add the `StableNeuronStore::with_main_part_mut` for modifying the main neuron section directly
* Add the `self.use_stable_memory_for_all_neurons` to modify neuron maturity based on its location
* The benchmark `draw_maturity_from_neurons_fund_stable` improved by 81.8%

feat(nns): Improve drawing/refunding neurons fund maturity when neurons in stable memory feature is enabled

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
MODULE.bazel
bazel/external_crates.bzl

Bumping canbench and the pocket-ic-mainnet versions so that the performance tests based on canbench can be run successfully.

chore: Bump canbench and pocket ic mainnet version

---

rs/messaging/src/message_routing.rs

Export information about subnet type, size, features, initial notary delay, max block payload size when reading the registry at the top of the round.

feat: Add various subnet info metrics

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/governance.rs
rs/nns/governance/src/voting.rs

This removes a difficult edge case of trying to determine when to re-tally.  We know that any votes cast in cast_vote_and_cascade_follow are either when a proposal is created, or when register_vote is called, which makes sure the vote cast is cast while the proposal voting is still open.
This helps later when votes can be processed across multiple messages.

refactor(nns): Move recompute_tally to inside of cast_vote_and_cascade_follow

---

rs/tests/message_routing/common/common.rs

The `//rs/tests/message_routing/xnet:xnet_slo_3_subnets_test` is currently failing on master when starting canisters. This commit improves the error message we get in this case:
```
2024-12-05 09:42:53.985 INFO[test:StdErr] Starting canister_idx=0 on subnet_idx=1 failed because of: 
unexpected result: "rejected" - Some("Error from Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai: 
Canister called `ic0.trap` with message: failed to decode call arguments: 
Custom(Fail to decode argument 0 from table0 to record 
{\n  payload_size_bytes : nat64;\n  
network_topology : vec vec principal;\n  
canister_to_subnet_rate : nat64;\n}\n\nCaused by:\n    
Subtyping error: Type mismatch at external/crate_index__candid-0.10.10/src/de.rs:994)\n
Canister Backtrace:\nunknown function at index 683\n
unknown function at …
```

test(IDX): improve error message in xnet_slo_test

---

rs/tests/message_routing/common/common.rs

Encode the arguments to the start method as the newly defined StartArgs struct instead of a tuple.

fix: Fix XNet end-to-end tests

---

Cargo.lock
rs/nns/governance/api/BUILD.bazel
rs/nns/governance/api/Cargo.toml
rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/api/src/pb.rs
rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/canister/canister.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/data_migration.rs
rs/nns/governance/src/data_migration_tests.rs
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/governance/merge_neurons.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron/types/tests.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/neuron_store/neuron_store_tests.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/src/voting.rs
rs/nns/governance/tests/fixtures/mod.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/tests/merge_neurons.rs
rs/nns/integration_tests/src/network_economics.rs

With this in place, a future change will make it possible to change these values via ManageNetworkEconomics proposals.
Initially, the fields are set as follows:
1. start_reducing_voting_power_after_seconds = 0.5 years.
2. clear_following_after_seconds = 1/12 years.
(Nominally, 1 year = 365.25 days in NNS.)
[Next PR 👉][next]
[next]: https://github.com/dfinity/ic/pull/2997

feat(nns): Add voting_power_economics to NetworkEconomics.

---

rs/ledger_suite/icp/ledger/src/main.rs

Fix the comment of the ICP ledger heap memory bytes metric.

chore(ICP_Ledger): Fix ICP ledger heap memory bytes metric comment

---

rs/bitcoin/ckbtc/minter/src/lib.rs

Instead of using a built-in default value, use check_fee from state to compute min_withdrawal_amount.

fix(ckbtc): compute min_withdrawal_amount using check_fee from state

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/tests/governance.rs

In a previous change, we added VotingPowerEconomics to NetworkEconomics. But it wasn't possible to actually change VPE via proposal. This adds the ability to make such proposals.
Closes https://dfinity.atlassian.net/browse/NNS1-3437.
[prev]: https://github.com/dfinity/ic/pull/2580

feat(nns): Propose voting power economics.

---

Cargo.lock
rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/integration_tests/BUILD.bazel
rs/nns/integration_tests/Cargo.toml
rs/nns/integration_tests/src/neuron_following.rs

Originally, we decided to grandfather existing neurons so that they would be considered refreshed on Nov 15 (more precisely, [1731628801 seconds after UNIX epoch][used]), but later, we changed our minds, and said that the clock should start on Sep 1 (more precisely, 1725148800). We changed the value of the constant, but many neurons picked up the old value. This sets those neurons to the new value.
[used]: https://sourcegraph.com/github.com/dfinity/ic@1956e438af82a5b4aa9713bcbbe385684bf0704f/-/blob/rs/nns/governance/src/lib.rs?L189
Closes [NNS1-3488][closes].
[closes]: https://dfinity.atlassian.net/browse/NNS1-3488 …

fix(nns): Change the default voting power refreshed timestamp from Nov 15 to Sep 1.

---

rs/rust_canisters/xnet_test/src/main.rs

When `xnet_test_canister` was migrated from `dfn_core` to `ic_cdk`, it retained the code structure of the earlier, callback-based `fanout()` function. Which unfortunately meant that it was now awaiting the calls to each subnet separately. In `xnet_slo_120_subnets_staging_test`, this lead to extended ramp-up and and ramp-down periods, which caused the test to time out.
Instead, create futures for calls to all subnets first; and only then await them all.

fix: Await all calls at once in xnet_test_canister's fanout()

---

.github/CODEOWNERS
rs/rust_canisters/statesync_test/BUILD.bazel
rs/tests/common.bzl
rs/tests/message_routing/BUILD.bazel

This commit changes the naming scheme of the statsync test canister to be analogous to the xnet test canister.
This commit also moves the code ownership of that canister to the message routing team.

chore: Align test canister naming

---

rs/bitcoin/ckbtc/mainnet/canister_ids.json
rs/bitcoin/ckbtc/mainnet/dfx.json
rs/bitcoin/ckbtc/testnet/canister_ids.json
rs/bitcoin/ckbtc/testnet/dfx.json
rs/cross-chain/proposal-cli/BUILD.bazel
rs/cross-chain/proposal-cli/src/candid/tests.rs
rs/cross-chain/proposal-cli/src/canister/mod.rs

Add Bitcoin Checker canister to both mainnet and testnet configurations with newly created canister ids.
Add support for Bitcoin Checker canister to proposal-cli, and remove KYT canister from it.

chore(ckbtc): add Bitcoin Checker canister

---

rs/nns/governance/BUILD.bazel

Currently, the benchmarks in NNS Governance aren't very stable. Sometimes they go over 2% noise threshold, and currently the noise threshold is still hard-coded in canbench.
Disable the canbench test in the NNS Governance until we can either make the benchmarks more stable or increase the noise threshold.

chore(nns): Disable canbench test for NNS Governance

---

rs/nervous_system/integration_tests/BUILD.bazel
rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs
rs/nervous_system/integration_tests/tests/upgrade_everything_test.rs

The `//rs/nervous_system/integration_tests:integration_tests_test_tests/sns_release_qualification` is currently our most flaky test because the `test_upgrade_everything` test is often timing out.
To debug why this is happening we isolate this test to its own bazel target and add some logs to see where it's timing out.

test(NNS): isolate upgrade_everything_test to its own bazel target

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/api/src/proposal_submission_helpers.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/src/pb/conversions.rs

I did not know that I needed to do this in https://github.com/dfinity/ic/pull/2856.
I left comments behind to warn others about this landmine.

fix(nns): Copied RefreshVotingPower to ManageNeuronCommandRequest.

---

Cargo.lock
rs/sns/governance/BUILD.bazel
rs/sns/governance/Cargo.toml
rs/sns/governance/canbench/canbench_results.yml
rs/sns/governance/canbench/main.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/governance/benches.rs

This sets up canbench in the SNS with one simple example benchmark. Hopefully we can extend it in the future with benchmarks of our canister code, to identify performance regressions and bottlenecks.

perf(sns): Set up canbench

---

Cargo.lock
rs/nervous_system/long_message/src/lib.rs
rs/nervous_system/long_message/tests/test_canisters/long_message_canister.rs
rs/nervous_system/long_message/tests/test_message_breaks.rs
rs/nns/common/src/lib.rs
rs/nns/governance/BUILD.bazel
rs/nns/governance/Cargo.toml
rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/canister/canister.rs
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/neuron_store/benches.rs
rs/nns/governance/src/storage.rs
rs/nns/governance/src/test_utils.rs
rs/nns/governance/src/voting.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/tests/proposals.rs
rs/nns/integration_tests/src/neuron_voting.rs
rs/nns/integration_tests/src/voting_rewards.rs

This PR adds support for processing neuron following across multiple messages, so that any number of neurons can vote and have their votes processed, regardless of the size and complexity of the neuron following graph or the number of neurons.

feat(nns): Highly scalable voting

---

.github/workflows-source/schedule-daily.yml
.github/workflows/schedule-daily.yml
.github/workflows/slack-workflow-run.yml

Request from Crypto team to move alerts for `Schedule Rust Benchmarks` and `Bazel System Test Benchmarks` to dedicated slack channel.

chore(IDX): update slack alerts

---

rs/nervous_system/integration_tests/BUILD.bazel
rs/nervous_system/integration_tests/tests/advance_sns_target_version.rs
rs/nervous_system/integration_tests/tests/advance_target_version_upgrades_all_canisters_test.rs

The `//rs/nervous_system/integration_tests:integration_tests_test_tests/advance_sns_target_version` is currently the most flaky system-test. It flakes because the `advance_target_version_upgrades_all_canisters_test` is timing out. So this commit isolates this test into its own bazel target and adds some logging such that we know which part is timing out.

test(IDX): isolate the advance_target_version_upgrades_all_canisters_test

---

.github/CODEOWNERS

IDX used to co-own system-tests such that we could quickly make sweeping changes to all system-tests. However, system-tests have really stabilised and no longer receive sweeping changes frequently anymore. So to reduce code-review notifications for the IDX team, component teams will solely own their system-tests.

chore(IDX): IDX no longer co-owns system-tests

---

rs/nervous_system/integration_tests/BUILD.bazel

We got our first flakes for these tests ([example](https://dash.zh1-idx1.dfinity.network/invocation/af13b004-7600-4a70-bd98-3f4265e75bb4)) but because the rust test driver captures logs we can't see where they flaked.
So this commit disables capturing of logs for the `//rs/nervous_system/integration_tests:...` tests.

test(IDX): do not capture logs in //rs/nervous_system/integration_tests:... tests

---

rs/tests/consensus/tecdsa/BUILD.bazel

The P90 duration of `//rs/tests/consensus/tecdsa:tecdsa_key_rotation_test` is [5m 13s](https://superset.idx.dfinity.network/explore/?form_data_key=L-xruYuVU55b2GcEj-nkSn9Hi7_DgNzUqhqScHYiuV4rSfyPaw_ak0pkH5hnlDHw&dashboard_page_id=_HteHI2SXP&slice_id=48) which is longer than our maximum allowed 5 minutes.
This tests uses the setup function: `setup_without_ecdsa_on_nns()` which can take quite some time to finish. All the other system-tests, that use this setup function, have already been tagged as `long_test` such that they no longer run on PRs but just on pushes to master.
This commit does the same for `//rs/tests/consensus/tecdsa:tecdsa_key_rotation_test`.
Unfortunately, I don't see an easy way to optimise the setup. It just appears that creating 12 nodes takes quite some time. Especially …

test(IDX): tag tecdsa_key_rotation_test as a long_test

---

packages/pocket-ic/BUILD.bazel

The test `//packages/pocket-ic:test_tests/tests` has been timing out quite often on CI recently so this PR increases its size (and thus timeout) and cpu count.

chore: increase PocketIC test size and cpu

---

hs/spec_compliance/src/IC/Test/Agent.hs

This PR retries HTTP errors with status code 502 (bad gateway) in spec compliance tests: if the HTTP gateway is overloaded in PocketIC, then this error code is sometimes produced leading to spurious test failures.

fix: retry bad gateway errors in spec compliance tests

---

rs/registry/canister/src/mutations/do_update_subnet.rs

This PR fixes the validation of the SEV (AMD Secure Encrypted Virtualization) feature that prevented change-subnet proposals that attempted to set a (non-SEV-related) feature for the first time (i.e., when the subnet doesn't yet have any features).

fix(registry): Ensure subnet features can be changed for subnets without any features

---

rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs

This PR is an attempt to speed up the ensure_archive_canister_is_spawned_or_panic function used, e.g., in `//rs/nervous_system/integration_tests:integration_tests_test_tests/sns_ledger_upgrade`.

test(sns): Make ensure_archive_canister_is_spawned_or_panic faster

---

rs/tests/driver/src/driver/bootstrap.rs

node_reward_type is a required field in config.ini, so a default should be added to setupos-inject-config calls.

fix(node): add node-reward-type default to setupos-inject-config

---

testnet/tools/nns-tools/lib/proposals.sh

This helps engineers remember to add the summary to the proposal, until we have automation to do it for us.

chore(nns): Add TODO back to proposal texts to add human-readable summary before submitting

---

testnet/mainnet_revisions.json

The replica release `2d8611eb4efa8e69c4dd567546c1c353a545e0a6` was built with Ubuntu-24.04 which means that it expects a newer version of libc to be available in the environment where its binaries run. After deploying this release we had to downgrade to Ubuntu 20.04 again. This means that the binaries from the latest replica release don't work in our tests since the latest libc is not available there. This effects the `//rs/tests/consensus/backup:backup_manager_upgrade_test` for example. We therefor temporarily override the mainnet revision to the commit just before the Ubuntu 24.04 upgrade.

fix(IDX): override mainnet_revisions.json

---

bin/afl_wrapper.sh
rs/fuzzers/stable_structures/fuzz_targets/stable_structures_multiple_ops_persistent.rs

- When a crash occurs with AFL, the stacktrace of the crash is not preserved. Usually, it should be reproducible with the crash input (which is preserved). However, fuzzers with global state and OOM bugs are sometimes hard to recreate and it would be helpful to preserve the crash log. This PR achieves it by duplicating STDERR into a user controlled file. 
- Changes to the stable_structures fuzzer to sent panic info to STDERR.

feat(fuzzing): Duplicate STDERR to a separate file in AFL

---

rs/ledger_suite/icp/index/BUILD.bazel
rs/ledger_suite/icp/ledger/BUILD.bazel

[This earlier PR](https://github.com/dfinity/ic/pull/2208) limited the parallelism for the affected tests to 4 threads, but unfortunately that didn't seem to help. However, when combined with CPU reservations in [this PR](https://github.com/dfinity/ic/pull/2914) (for a somewhat related test), the flakiness of the latter test went down from 9% to 0.9%. Since both tests are similar (the tests in this PR use `StateMachine`, whereas the ones in the other use `PocketIC`, which in turn uses `StateMachine` under the hood), the hope is that increasing the CPU reservation would also reduce the flakiness of the ICP ledger and index tests covered by this PR.

test(ICP_Ledger): FI-1506: Increase CPU reservation for flaky ICP ledger and index tests

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron_store/benches.rs

Listing neurons could get more expensive when neurons are moved to stable structures. Adding a benchmark so that future improvements can be measured, and regressions can be detected.
* Some small refactoring on neuron building for benchmarks so that each benchmark can customize neuron builder before building it
* Add benchmarks for listing neurons fund neurons with and without the "neurons in stable memory" feature
[Next](https://github.com/dfinity/ic/pull/3020)

perf(nns): Add benchmark for listing neurons fund neurons

---

rs/sns/governance/BUILD.bazel
rs/sns/governance/canbench/canbench_results.yml
rs/sns/governance/src/governance.rs
rs/sns/governance/src/proposal.rs
rs/sns/governance/tests/fixtures/mod.rs
rs/sns/governance/tests/governance.rs

This PR enables SNS Governance to recover from a corrupted state in which a deployed version is not specified. The recovery is a best-effort attempt, currently done via calling SNS Root's `get_sns_canisters_summary` function.

feat(sns): Recover SNS from not knowing its deployed version

---

rs/nns/governance/src/neuron_store/metrics.rs

The purpose of loading the `known_neuron_data` section isn't very obvious. Adding a comment as well as using `..NeuronSections::NONE` for simplification.

chore(nns): Clarify the purpose of loading the known neuron section when calculating metrics

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/neuron_store/benches.rs
rs/nns/governance/src/neuron_store/metrics.rs
rs/nns/governance/src/neuron_store/metrics/tests.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/src/tests.rs
rs/nns/governance/tests/governance.rs

Most of the changes here are for breaking out voting power into deciding vs. potential, and copying those around, because of duplicate types.
Another metric in this PR: When the current prune following cycle began.
[Next PR 👉][next]
[next]: https://github.com/dfinity/ic/pull/3090

feat(nns): Periodic confirmation metrics.

---

Cargo.lock
rs/nervous_system/timestamp/BUILD.bazel
rs/nervous_system/timestamp/Cargo.toml
rs/nervous_system/timestamp/src/lib.rs
rs/nervous_system/timestamp/src/tests.rs
rs/sns/governance/BUILD.bazel
rs/sns/governance/Cargo.toml
rs/sns/governance/src/proposal.rs
rs/sns/governance/src/proposal/advance_sns_target_version.rs

This PR factors the human-readable timestamp formatter out into its own crate.

refactor(sns): Move human-readable timestamp formatter into its own crate

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/neuron_store/metrics.rs
rs/nns/governance/src/neuron_store/metrics/tests.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/tests/governance.rs

Here,
* stale = time since voting power was refreshed is between strictly 6 and 7 months (or whatever VotingPowerEconomics dictates).
* expired = time since voting power was refreshed is >= 7 months (again, per VotingPowerEconomics).
I think the main thing we really care about here is the number of such neurons in those two (sub)categories. However, it is not much harder to gather additional statistics (thanks to existing code for compiling statistics for arbitrary neuron (sub)categories). Therefore, a whole bunch of other stats about these two subcategories of neurons is also exported.
FWIW, if you strip away the highly repetitive code (and don't count test code), this change is actually pretty small.
This is part of the "periodic confirmation" feature that was recently approved in …

feat(nns): Count stale and expired voting power neurons.

---

rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/advance_sns_target_version.rs
rs/nervous_system/integration_tests/tests/advance_target_version_upgrades_all_canisters_test.rs

The issue is that there are some cases where we know that `await_with_timeout` will have to wait a certain minimum amount of time. By taking a range, we can have the caller pre-emptively tell us the minimum amount of time they think we'll have to wait. Then we can advance that amount of time straight away

refactor(tests): `await_with_timeout` should take a range, not just a timeout

---

rs/nervous_system/integration_tests/BUILD.bazel
rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/deploy_fresh_sns_test.rs
rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
rs/nervous_system/integration_tests/tests/sns_release_qualification_legacy.rs
rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs
rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils_legacy.rs

The upgrade tests are implemented by calling `test_sns_upgrade`. This PR changes that function to use the new mechanism rather than the old. I don't think it's necessary to retain test coverage for the old mechanism.
[NNS1-3441](https://dfinity.atlassian.net/browse/NNS1-3441)
[NNS1-3441]: https://dfinity.atlassian.net/browse/NNS1-3441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(sns): Migrate upgrade qualification tests to AdvanceSnsTargetVersion

---

MODULE.bazel
packages/pocket-ic/BUILD.bazel
rs/pocket_ic_server/BUILD.bazel

This PR uses mozilla root ca store in PocketIC tests on macOS to mitigate their flakiness caused by loading the system-wide root ca store on macOS.

chore: use mozilla root ca store in PocketIC tests on macOS

---

rs/ledger_suite/icp/index/BUILD.bazel

The `//rs/ledger_suite/icp/index:ic_icp_index_test` is a bit flaky (~2%) because it occasionally times out after 5 minutes. So we increase the timeout to `long` which is 15 minutes.
If it turns out the P90 duration of this test will go over 5 minutes we should look into optimising it or tagging it as a `long_test` to no longer run this on PRs but only on pushes to `master`.

test(IDX): increase timeout to 15m for the ic_icp_index_test

---

rs/ledger_suite/icp/ledger/BUILD.bazel

The `//rs/ledger_suite/icp/ledger:ledger_canister_test` is a bit flaky (~1.8%) because it occasionally times out after 5 minutes. So we increase the timeout to long which is 15 minutes.
If it turns out the P90 duration of this test will go over 5 minutes we should look into optimising it or tagging it as a long_test to no longer run this on PRs but only on pushes to master.

test(IDX): increase timeout to 15m for the ledger_canister_test

---

rs/nns/integration_tests/BUILD.bazel

The `//rs/nns/integration_tests:integration_tests_test_src/...` tests are slightly flaky (> 1%) because they sometimes time out after 5 minutes. So we increase the timeout to `long` which is 15 minutes.
If it turns out the P90 duration of these tests will go over 5 minutes we should look into optimising them or tagging them as `long_test` to no longer run them on PRs but only on pushes to `master`.

test(IDX): increae timeout of the NNS integration_tests_test

---

packages/pocket-ic/BUILD.bazel

A PocketIC library test timed out on a push to master after loading the root certificate store from a local file. Hence, this PR reduces parallelism in this test.

chore: reduce parallelism in PocketIC tests

---

.github/workflows/anonymization-backend-release.yml
rs/boundary_node/anonymization/backend/BUILD.bazel
rs/boundary_node/anonymization/backend/build.sh
rs/boundary_node/anonymization/backend/dfx.json

This adds a github workflow to manually trigger a build/release of the anonymization canister. We plan to add a similar workflow for another new rate-limiting canister.
I tested this on a small temporary repo but without the bazel portion, so am not entirely sure if this would require another runner or also installing ic-wasm? cc @basvandijk

feat(BOUN-1308): build and publish anonymization canister

---

rs/bitcoin/checker/src/providers.rs

Remove the redundant "Host" header to avoid errors in making https outcall via http/2.
This fixes problem accessing API providers blockstream.info and mempool.space.

fix(ckbtc): Drop Host header from https outcall request

---

.github/workflows/rate-limits-backend-release.yml

This is a similar PR to https://github.com/dfinity/ic/pull/3106, in this case building and publishing a release of the rate-limits canister used to adjust rate-limit rules for the API Boundary Nodes.

feat(BOUN-1308): add manually triggered ci workflow for rate-limits canister

---

rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
rs/nervous_system/integration_tests/tests/sns_release_qualification_legacy.rs

This was disabled until we updated SNS Gov on mainnet (as previously SNS Swap did not upgrade).
Closes [NNS1-3433](https://dfinity.atlassian.net/browse/NNS1-3433)
#2981 already did this for the legacy (UpgradeSnsToNextVersion) upgrade qualifications, this PR does it for AvanceSnsTargetVersion upgrade qualifications as well.
[NNS1-3433]: https://dfinity.atlassian.net/browse/NNS1-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Note: This PR also cleans up a comment in `sns_release_qualification_legacy.rs`

test(sns): Do release-qualification for swap upgrades

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/neuron_store.rs

Adds a benchmark for list_neurons

test(nns): Add a benchmark for list neurons

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/neuron_store/benches.rs

Neuron data validator goes through batches of neurons in order to make sure neurons and its indexes are in a consistent state, and such operations will get more expensive after neurons are migrated to stable structures. Adding benchmarks makes it easier to optimize the performance, and help prevent regressions.
Add benchmarks for neuron data validator for 2 cases - whether the neuron migration to stable structures is enabled or not.

perf(nns): Add benchmarks for neuron data validator

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/neuron_data_validation.rs
rs/nns/governance/src/neuron_store.rs

The method `with_active_neurons_iter` is much more expensive than reading `heap_neurons` directly. In the context of neuron data validation, it's unnecessary to use `with_active_neurons_iter` since it reads both heap and stable memories. In other words, it reads `heap_neurons` not for "active neurons" but really just the neurons in the heap.
Revert to using `heap_neurons_iter` and update benchmarks

perf(nns): Read heap neurons for cardinalities

---

rs/embedders/BUILD.bazel
rs/embedders/benches/compilation.rs
rs/embedders/benches/embedders_bench/src/lib.rs

This fixes heap, stable memory and compilation embedder benchmarks.

perf: EXC-1818: Fix embedder benches

---

rs/rosetta-api/icp/client/src/lib.rs
rs/rosetta-api/icp/src/convert.rs
rs/rosetta-api/icp/src/convert/state.rs
rs/rosetta-api/icp/src/ledger_client.rs
rs/rosetta-api/icp/src/ledger_client/handle_refresh_voting_power.rs
rs/rosetta-api/icp/src/models/operation.rs
rs/rosetta-api/icp/src/request.rs
rs/rosetta-api/icp/src/request_handler/construction_parse.rs
rs/rosetta-api/icp/src/request_handler/construction_payloads.rs
rs/rosetta-api/icp/src/request_handler/construction_preprocess.rs
rs/rosetta-api/icp/src/request_types.rs
rs/rosetta-api/icp/src/transaction_id.rs
rs/rosetta-api/icp/test_utils/src/lib.rs
rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
rs/tests/src/rosetta_tests/lib.rs

This MR proposes the following changes:
1. Add the refresh voting power functionality to ICP Rosetta
2. Add the refresh voting power functionality to the ICP Rosetta Client

feat(ICP-Rosetta): FI-1603: implement refresh voting power endpoint

---

rs/tests/nns/nns_cycles_minting_test.rs

This was just a matter of multiplying some numbers by 3, to match https://github.com/dfinity/ic/pull/3093.
This got broken by https://github.com/dfinity/ic/pull/3093, but we did not notice, because this test does not block merging (because it is slow).

fix(nns): //rs/tests/nns:nns_cycles_minting_test.

---

packages/icrc-ledger-agent/src/lib.rs
rs/ledger_suite/icrc1/ledger/src/main.rs
rs/ledger_suite/icrc1/ledger/tests/tests.rs
rs/tests/financial_integrations/icrc1_agent_test.rs

1. Use the icrc3 certificate endpoint for the ICRC1 Agent library.

fix(ICRC-Ledger): changed certificate version

---

rs/sns/cli/src/deploy.rs

Without doing this, the call to build_canister_payloads fails, since build_canister_payloads calls validate_post_execution. Even if it did not, the swap canister itself would reject the generated init arg: `Invalid init arg, reason: Mandatory fields must be specified: swap_due_timestamp_seconds, nns_proposal_id`

fix(sns): testflight should set post-execution variables

---

.github/workflows/anonymization-backend-release.yml
.github/workflows/rate-limits-backend-release.yml

This change applies @nmattia's suggestion about using a default shell. He also mentioned he believes that bash is the default but prior to this I had to set the shell to bash so I'm not confident if that is true.
It also downgrades the release action due to https://github.com/softprops/action-gh-release/issues/556

fix(BOUN-1308): use default shell and downgrade release action

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/neuron_data_validation.rs

Currently, the neuron data validation is reading all neuron sections for a batch of neurons, and the batching is by a fixed batch size. Those can be improved by: reading specific neuron sections for each task, and batch by instruction limit.
Implement the above-mentioned optimizations and update benchmarks.

perf(nns): Improve neuron validation batching

---

ic-os/components/setupos-scripts/setupos.service

Setting setupos.service to depend on systemd-networkd-wait-online.service prevents a timing issue where setupos.service runs before the networking has been set up.
If generate-network-config fails, setupos.service still runs. It just hangs for a minute after generate-network-config fails before starting setupos.service.

fix(node): setupos networking dependency

---

rs/ic_os/config/src/generate_testnet_config.rs
rs/ic_os/config/src/update_config.rs
rs/ic_os/config_types/src/lib.rs

A few small updates to update-config. Most notably: [Add node reward type update-config parsing](https://github.com/dfinity/ic/pull/3132/commits/f297cee67edf46f1975e1dd803116edf8838f3c0)

fix(node): Add node reward type update-config parsing

---

rs/ic_os/config/src/update_config.rs
rs/ic_os/dev_test_tools/setupos-inject-configuration/src/main.rs
rs/tests/driver/src/driver/bootstrap.rs
rs/tests/driver/src/driver/nested.rs

- Add a check in update-config preventing a "new" testnet config from being overwritten. This check fixes errors in the [config revamp](https://github.com/dfinity/ic/pull/1563) caused by update-config erroneously overriding development config fields. This change will have no impact on mainnet: cf825d2c08bc7b26a6dc2a1b16ea7e646f053482
- Allowing an empty hostname field in GuestOS fixes update-config errors in the nested tests. 
Example: https://github.com/dfinity/ic/actions/runs/12244488249
The hostname field will always be populated on mainnet, so this will only impact testing: 764230f49edaef0f9149bfd6fe0da1d6789e6774
- Switching nested testing to run with a "testnet" deployment environment (54cde2eeed7c7616b887e18aae3bb1b4820e7db7, 23d8824c61fc4e3f79d377e290f029df59568eaf) fixes issues …

fix(node): update-config in testnet environment

---

rs/ledger_suite/icp/tests/golden_nns_state.rs

Check the metrics to verify that the migration to stable structures was performed as expected in the ICP ledger golden state test.

test(ICP_Ledger): FI-1595: Check migration metrics in ICP golden state test

---

rs/pocket_ic_server/BUILD.bazel

This temporarily disables the `//rs/pocket_ic_server:test` on Apple Silicon because it occasionally runs into the following error:
```
---- test_http_gateway stdout ----
thread 'test_http_gateway' panicked at rs/pocket_ic_server/tests/test.rs:383:48:
called `Result::unwrap()` on an `Err` value: reqwest::Error {
kind: Request, url: "http://7tjcv-pp777-77776-qaaaa-cai.raw.localhost:49380/",
source: hyper_util::client::legacy::Error(
Connect,
ConnectError("tcp connect error", Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })
)
}
```

test(IDX): disable //rs/pocket_ic_server:test on Apple Silicon

---

Cargo.lock
rs/rosetta-api/icp/BUILD.bazel
rs/rosetta-api/icp/CHANGELOG.md
rs/rosetta-api/icp/Cargo.toml

This MR proposes the follwoing changes
1. Change ICP Rosetta to 2.1.1 for the upcoming release

chore(ICP-Rosetta): add release

---

rs/ledger_suite/icp/archive/src/main.rs
rs/ledger_suite/icp/index/src/main.rs
rs/ledger_suite/icp/ledger/src/main.rs
rs/ledger_suite/icp/ledger/tests/tests.rs
rs/ledger_suite/icp/src/lib.rs
rs/ledger_suite/icp/src/validate_endpoints.rs
rs/ledger_suite/icp/test_utils/src/pocket_ic_helpers/ledger.rs
rs/ledger_suite/icp/test_utils/src/state_machine_helpers/ledger.rs
rs/ledger_suite/icp/tests/tests.rs
rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/src/canister_access.rs
rs/rosetta-api/icp/tests/system_tests/common/utils.rs

Change the type of the `length` field in the ledger `GetBlocksArgs` struct from `usize` to `u64`. The field in the candid interface is of type `Nat64`, but if a value larger than what fit into a `u32` was passed in as the `length` in a `query_blocks` query, this would lead to a `Fail to decode argument 0 from table0 to record { start : nat64; length : nat64 }` error.

fix(ICP_Ledger): FI-1590: Change length type in GetBlocksArgs

---

mainnet-canisters.json

This PR bump the mainnet canister revisions file after the last Registry upgrade (https://dashboard.internetcomputer.org/proposal/134437).

chore(nns): Bump mainnet canister revisions after the last Registry upgrade

---

ic-os/components/selinux/ic-node/ic-node.te
ic-os/components/selinux/systemd-fixes/systemd-fixes.te

NODE-1522
- Silence libunwind-related SELinux denials (pipe access)
- allow fstrim_tool systemd service to perform NoNewPrivileges transition
Created from: https://github.com/dfinity/ic/pull/2990

fix(node): silence libunwind denials and allow systemd NoNewPrivileges for fstrim_tool

---

rs/pocket_ic_server/BUILD.bazel

Adding `requires-network` tag to overcome the issue of sporadic failures (seen [here](https://github.com/dfinity/ic/actions/runs/12320821672), attempt 1 & 2):
```
Failed to get result: reqwest::Error { kind: Request, url: "http://127.0.0.1:49325/instances", source: hyper_util::client::legacy::Error(Connect, ConnectError("tcp connect error", Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })) }
```

chore(pocket-ic): bazel test requires-network

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/voting.rs

In order to get approximately the same number of read/writes in stable for the VotingStateMachine, it is required to count accurately.  Canbench doesn't allow queries, which means the instruction_counter never gives a different result, which means the benchmark thinks it runs out of cycles on every iteration, and thus saves and restores the ProposalVotingStateMachine over and over, leading to an inaccurate benchmark compared to production.
This adds code to approximately simulate behavior in canbench-rs build.

fix(nns): Fix benchmark by simulating proper behavior in canbench-rs build

---

bazel/canbench.bzl
rs/nns/governance/BUILD.bazel
rs/nns/governance/canbench/canbench_results.yml

Compiler optimizations like loop unrolling can make benchmarks more sensitive to unrelated changes. In this PR we effectively disable such optimizations for benchmarks using `canbench`.

chore: Reduce optimization for NNS Governance rust_canbench

---

rs/sns/integration_tests/BUILD.bazel

The `//rs/sns/integration_tests:...` fail a lot on PRs and master so we set `flaky = True` so the test gets a chance to pass. If the flakiness turns out too high the NNS team should look into fixing it.

test: set flaky to True for //rs/sns/integration_tests

---

rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs

We prefer timer to heartbeat in general, and the neuron validation can be scheduled in a fixed interval. Therefore we should just move it to timer as a low hanging fruit.

feat(nns): Move neuron validation to timer

---

rs/tests/consensus/tecdsa/tecdsa_signature_timeout_test.rs

This test makes sure that signature requests fail after the configured timeout. It turns out that we occasionally manage to create signatures in less than 1 second, making this test flaky. This PR reduces the timeout to 1 millisecond instead.

fix(tests): Reduce timeout in `tecdsa_signature_timeout_test`

---

rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/test.rs

This PR adds a timeout when fetching the root key in PocketIC HTTP gateway. This way, passing an invalid backend URL would result into a comprehensible error message that fetching the root key from this URL timed out instead of the HTTP gateway creation timing out as a whole.

fix: add timeout when fetching root key in PocketIC HTTP gateway

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
Cargo.toml
bazel/external_crates.bzl
rs/execution_environment/BUILD.bazel
rs/execution_environment/Cargo.toml
rs/replicated_state/BUILD.bazel
rs/replicated_state/Cargo.toml

This PR removes an obsolete dependency on `ic-btc-test-utils` from replica.
EXC-1813

chore: remove obsolete ic-btc-test-utils dependency

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.json.lock
bazel/external_crates.bzl
bazel/libssh2-sys.patch

This adds a patch that prevents `libssh2-sys` from generating a `.pc` file. The pkg-config file includes absolute paths which makes it non-deterministic.
See: https://github.com/alexcrichton/ssh2-rs/issues/340

fix(IDX): work around libssh2-sys determinism issues

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Introducing `CI_MACOS_INTEL` label that allows users to run *Bazel Test macOS Intel* CI job within the PR, if they for some reason want to do so.

chore(CI): intel macos label

---

rs/nns/integration_tests/src/node_assignment.rs
rs/nns/integration_tests/src/node_operator_handler.rs

This attempts to fix a time discrepancy between system time and StateMachine time causing test flakiness when dealing with cryptographic keys in some tests using the Registry.

test(nns): Fix flakiness in two nns integration tests

---

rs/nervous_system/long_message/src/lib.rs

This cleans up a couple of comments that were no longer correct after behavioral changes were made.

chore(nervous-system): Fix comments to match code

---

mainnet-canisters.json
rs/ledger_suite/icp/ledger/tests/tests.rs
rs/ledger_suite/icp/tests/golden_nns_state.rs
rs/ledger_suite/icp/tests/upgrade_downgrade.rs
rs/ledger_suite/icrc1/ledger/tests/tests.rs
rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
rs/ledger_suite/icrc1/tests/upgrade_downgrade.rs
rs/ledger_suite/tests/sm-tests/src/lib.rs

Update the rest of the ledger suite canisters in `mainnet-canisters.json`, and fix the (upgrade) tests that broken as a consequence.

test(ICP_Ledger): FI-1616: Fix upgrade tests and update mainnet canisters

---

rs/sns/governance/src/governance.rs

These logs appear all the time when debugging SNS Governance, e.g:
```
2021-05-08 19:19:57.000000035 UTC: [Canister rrkah-fqaaa-aaaaa-aaaaq-cai] [Governance] Couldn't update maturity modulation. Error: Canister rkp4c-7iaaa-aaaaa-aaaca-cai not found
2021-05-08 19:19:58.000000035 UTC: [Canister 7tjcv-pp777-77776-qaaaa-cai] [Root Canister] start_canister call successful. Ok(())
2021-05-08 19:19:58.000000035 UTC: [Canister 7tjcv-pp777-77776-qaaaa-cai] change_canister: Canister change completed successfully.
2021-05-08 19:19:59.000000035 UTC: [Canister rrkah-fqaaa-aaaaa-aaaaq-cai] [Governance] Couldn't update maturity modulation. Error: Canister rkp4c-7iaaa-aaaaa-aaaca-cai not found
2021-05-08 19:20:01.000000035 UTC: [Canister rrkah-fqaaa-aaaaa-aaaaq-cai] [Governance] Couldn't update maturity …
```

fix(sns): Don't log when maturity modulation can't be refreshed

---

rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs

Otherwise it isn't much of a qualification test :D 
This PR also extends the test in a couple other ways to help ensure it only passes if the upgrades happened as expected

test(sns): AdvanceSnsTargetVersion qualification test should use master-branch canister versions

---

rs/tests/consensus/replica_determinism_test.rs

The test is flaky which may be caused by pooled agent sockets being broken during the node's restart.

test: Create a new agent after malicious node was restarted in `replica_determinism_test`

---

rs/bitcoin/checker/src/main.rs
rs/bitcoin/checker/tests/tests.rs

Make sure service fee is fully charged before checking the validity of txid.

fix(ckbtc): btc-checker charges service fee before checking txid

---

rs/tests/boundary_nodes/BUILD.bazel

Those tests were marked as flaky for compatibility reasons 10 months ago. I ran them all 10 times and they all succeeded (on the first try, of course):
```
x=0; while bazel test --config=systest //rs/tests/boundary_nodes/... --nocache_test_results --test_tag_filters="-system_test_hourly"; do echo "success $x" | tee -a successes; x=$(( $x + 1 )); done
```

chore(IDX): mark boundary node tests as not flaky

---

rs/bitcoin/checker/btc_checker_canister.did
rs/bitcoin/checker/src/main.rs
rs/bitcoin/checker/src/types.rs
rs/bitcoin/checker/tests/tests.rs

XC-259: Add a new public method `check_transaction_str` to Bitcoin Checker that takes transaction id as a text argument.

feat(ckbtc): add check_transaction_str to Bitcoin Checker

---

rs/ledger_suite/icrc1/index-ng/BUILD.bazel
rs/ledger_suite/icrc1/index-ng/tests/retrieve_blocks_from_ledger_interval.rs

This PR proposes two things to optimize the `//rs/ledger_suite/icrc1/index-ng:index_ng_test_..._tests/retrieve_blocks_from_ledger_interval` tests which has seen P90 durations of over 5min:
- Shorten the runtime of a couple of tests (from `10` to `4` cases for a `proptest`, and from `60s` to `10s` for a test checking the idle canister cycles consumption)
- Limit the parallelism and increase the allocated resources, since the runtime of the test was increasing with increasing values of `--runs_per_test`

test(ICRC_Index): FI-1617: Optimize retrieve_blocks_from_ledger_interval tests

---

Cargo.lock
rs/rust_canisters/xnet_test/BUILD.bazel
rs/rust_canisters/xnet_test/Cargo.toml
rs/rust_canisters/xnet_test/src/main.rs
rs/tests/message_routing/common/common.rs
rs/tests/message_routing/xnet/BUILD.bazel

* Install large numbers of canisters in batches, to prevent failures due to HTTP endpoint rate limits.
* Annotate blobs in types used by `xnet_test_canister` endpoints with `#{with(serde_bytes)]`, making them a lot cheaper to encode and decode.
* Add Prometheus/Grafana runtime dependencies to all XNet tests, to avoid mysterious failures when running `.with_prometheus()`.

test: Miscellaneous XNet test improvements

---

bazel/defs.bzl
rs/embedders/BUILD.bazel
rs/execution_environment/BUILD.bazel

Some benchmarks include assertions on the number of instructions executed, which can be broken when costs are adjusted. This change causes some benchmark targets to also generate corresponding test targets, ensuring their execution on each pipeline run.

test: EXC-1818: Test some bench targets

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
bazel/external_crates.bzl
rs/embedders/Cargo.toml
rs/embedders/README.adoc
rs/embedders/src/wasm_utils/validation.rs
rs/embedders/tests/spec_tests.rs

Release notes: https://github.com/bytecodealliance/wasmtime/releases/tag/v27.0.0
* enabled `gc-null` feature as the GC dependency
* minor changes in spec tests

chore: EXC-1818: Upgrade wasmtime to 27.0.0

---

rs/embedders/benches/embedders_bench/src/lib.rs
rs/test_utilities/execution_environment/src/lib.rs

Currently, all query benchmarks are near-instantaneous due to query caching. This PR disables caching to provide accurate benchmarks.

perf: EXC-1818: Fix embedders heap and stable memory query benches

---

rs/tests/consensus/liveness_test_common/src/lib.rs

It could happen that malicious nodes crash themselves by, for example, adding invalid artifacts to their own artifact pools and breaking some invariants resulting in a crash

test(consensus): fix liveness tests flakiness by only checking the health of honest nodes

---

ci/src/artifacts/BUILD.bazel
ci/src/artifacts/upload.bzl
ci/src/artifacts/upload.sh

This skips the template variable substition for the artifact uploader, using env vars instead. This simplifies the setup and allows the upload script to be called directly (provided the env is set correctly).

chore(IDX): don't use template for artifact upload

---

rs/nns/governance/src/governance.rs

This log pollutes test environments by logging the message a million times for no practical benefit. Most often it's just because we don't create the CMC in tests. Let's not log in that case.

chore(nns): Remove NNS maturity modulation log in some cases

---

rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/pocket_ic.rs
rs/pocket_ic_server/tests/test.rs

This PR allows canisters to be created via `provisional_create_canister_with_cycles` with the management canister ID as the effective canister ID. Although the same effect can be achieved by parsing the default effective canister ID from the topology and using it as the effective canister ID for `provisional_create_canister_with_cycles`, it is simpler to use the management canister ID `aaaaa-aa` instead, e.g., [juno-docker](https://github.com/junobuild/juno-docker) does it so.

fix: canister creation with aaaaa-aa as effective canister ID

---

rs/tests/boundary_nodes/BUILD.bazel
rs/tests/consensus/BUILD.bazel
rs/tests/consensus/orchestrator/BUILD.bazel
rs/tests/consensus/subnet_recovery/BUILD.bazel
rs/tests/consensus/tecdsa/BUILD.bazel
rs/tests/consensus/upgrade/BUILD.bazel
rs/tests/idx/BUILD.bazel
rs/tests/message_routing/BUILD.bazel
rs/tests/networking/BUILD.bazel
rs/tests/nns/BUILD.bazel

What
===
This moves all system-tests that only run hourly (tagged with `system_test_hourly`) to run on every push to `master` (tagged with `long_test`) except for the following hourly tests that are kept back (for now) because of the mentioned reason:
* `//rs/tests/boundary_nodes:bn_integration_on_playnet_test`: >1% flakiness rate
* `//rs/tests/consensus/subnet_recovery:sr_app_large_with_tecdsa_test`: >1% flakiness rate & >10 minutes
* `//rs/tests/consensus/subnet_recovery:sr_app_same_nodes_with_tecdsa_test`: >10 minutes
* `//rs/tests/consensus/upgrade:upgrade_downgrade_app_subnet_test`: >10 minutes
* `//rs/tests/consensus/upgrade:upgrade_downgrade_nns_subnet_test`: >10 minutes
* `//rs/tests/nested:registration`: >10 minutes
* `//rs/tests/nested:upgrade`: >1% flakiness rate & >10 minutes …

test(IDX): move most system_test_hourly to long_test

---

rs/bitcoin/ckbtc/minter/src/storage/tests.rs
rs/bitcoin/ckbtc/minter/src/test_fixtures.rs
rs/bitcoin/ckbtc/minter/src/tests.rs

[(XC-238)](https://dfinity.atlassian.net/browse/XC-238) Add property tests for the ckBTC event serialization/deserialization logic where events (both legacy and new) are arbitrarily generated from all possible event types. See [this comment](https://github.com/dfinity/ic/pull/3157#discussion_r1891578520).

chore(ckbtc): property tests for event serialization and deserialization

---

rs/tests/consensus/BUILD.bazel
rs/tests/consensus/consensus_performance.rs
rs/tests/consensus/utils/src/performance.rs

This will allow us, after adding enough instrumentation, to visualize traces like:
Maybe it will be helpful in identifying bottlenecks

test(consensus): add an option to start a Jaeger instance in consensus performance test

---

rs/ic_os/config/src/update_config.rs

[NODE-1541](https://dfinity.atlassian.net/browse/NODE-1541)
Handle the update-config case where reward.conf does not exist on the config partition.
[NODE-1541]: https://dfinity.atlassian.net/browse/NODE-1541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(node): fix update-config when reward.conf does not exist

---

rs/sns/governance/src/governance.rs
rs/sns/governance/src/governance/advance_target_sns_version_tests.rs
rs/sns/governance/src/governance/assorted_governance_tests.rs
rs/sns/governance/src/types.rs
rs/sns/integration_tests/src/neuron.rs
rs/sns/test_utils/src/itest_helpers.rs

For those who don't know, upgrade proposals (e.g. UpgradeSnsToNextVersion) block all other upgrade actions while they're adopted until they're done executing. If a proposal were to get stuck, this would be a major problem, since the SNS would be un-upgradable. This obviously is a pretty bad scenario, so this PR makes it so only upgrade proposals decided within the last day can block other upgrades.

fix(sns): Don't let very old upgrade proposals block future upgrades

---

rs/replica/setup_ic_network/src/lib.rs

There is a problem with the current implementation, we are thus disabling the feature while we fix the issue.

fix(consensus): disable hashes in blocks feature

---

rs/replicated_state/src/canister_state/queues.rs

This makes unmutated canister queues basically free to clone, which is important during certification and, more importantly, before and after every message execution (when the `SystemState` is cloned in order to allow for rollbacks). After the changes in #3241 and #3304, under heavy subnet load (millions of best-effort messages) this accounts for about half the message execution time; dropping to well under 10% with this change.

perf: Put canister queues behind `Arcs`

---

rs/nns/governance/src/governance.rs

This removes an edge case where a neuron can become locked when the ledger is unavailable during a neuron operation (such as during an upgrade).
If the neuron happens to spawn during a ledger upgrade, the neuron will become locked, and therefore stuck.

fix(nns): Revert spawn state when ledger unavailable and drop lock

---

rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs

Representing the canister global state with `thread_local!` avoids using unsafe blocks to access it. When using unsafe blocks to access it, one can easily write code with undefined behavior by retaining references across await boundary (more precisely, after an inter-canister call). 
The NNS Governance heavily depends on the accessing the global state as `static`, and there will be a lot of refactoring needed in order to get away with the current pattern. This PR is the first step towards getting rid of those bad access patterns - with this change, we can gradually migrate from using `governance()`/`governance_mut()` to using `GOVERNANCE.with()`. When all the usage of `governance()`/`governance_mut()` are replaced, we can delete them and declare victory.
Define the global state with …

refactor(nns): Switch NNS Governance global state from static to thread_local

---

rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/neuron_data_validation.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/neuron_store/benches.rs
rs/nns/governance/src/neuron_store/metrics.rs
rs/nns/governance/src/neuron_store/neuron_store_tests.rs

The previous set up for the feature flag `active_neurons_in_stable_memory` does not allow us to safely rollback if necessary, because the rolled back version would only look for active neurons in the heap memory, while some would still be in the stable memory until the timer picks them up (if the reverse migration is implemented).
Use `allow_active_neurons_in_stable_memory` for whether the canister allows active neurons to be in stable memory, by checking stable memory when iterating/finding active neurons.
Use `migrate_active_neurons_to_stable_memory` for whether the active neurons should be in stable memory, so that the migration task in the timer would move them accordingly.
With the new setup, we can:
1. Turn on `allow_active_neurons_in_stable_memory`. If any problems occur, we can …

feat(nns): Split the active_neurons_in_stable_memory into 2 flags

---

rs/tests/consensus/consensus_performance.rs

After the hashes-in-blocks feature has been turned off in https://github.com/dfinity/ic/commit/5716305a58110031dac133f7182b1e3efd50257e the consensus can no longer handle the load simulated in the test.
To make the test not fail we temporarily go back to the parameters from https://github.com/dfinity/ic/pull/3279

test(consensus): adjust the parameters of consensus performance tests

---

rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/tests/governance.rs

A neuron was locked, which logged `Inflight commands: { 17912780790050115461: NeuronInFlightCommand { timestamp: 1728911670, command: Some( Spawn( NeuronId { id: 17912780790050115461, }, ), ), }, }`
We identified the account as: https://dashboard.internetcomputer.org/account/9765cc69bd6580023bee8fa8280fb630977b9f850da49d73cddcb99512272abb  
And the neuron can be seen here: https://dashboard.internetcomputer.org/neuron/17912780790050115461
As can be seen, no ICP was minted, but the neuron's cached stake was set and maturity was cleared.  The fix is to mint the ICP and unlock the neuron.
Fix to prevent this from happening in the future is here: https://github.com/dfinity/ic/pull/3226

fix(nns): Fix for a particular locked neuron

---

rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/neuron_store/neuron_store_tests.rs

We are about to migrate neurons from heap memory to stable memory. If anything goes wrong, we'd like to reverse the migration by setting their target location from `Stable` to `Heap`. Previously the `adjust_neuron_storage` procedure only looks at the neurons in the heap, and therefore it can only move neurons from heap memory to stable memory if the target location is different from where they are. In order to make the reverse migration possible, we look at the neurons in the stable memory during `adjust_neuron_storage`.
Testing: ` //rs/nns/integration_tests:integration_tests_test_src/governance_migrations` still passes (which fails if `schedule_adjust_neurons_storage` is commented out)

feat(nns): Make neuron migration to stable memory reversible

---

rs/nns/governance/src/governance.rs
rs/nns/governance/tests/fake.rs
rs/nns/governance/tests/governance.rs

A previous pull request sets the maturity to the modulated amount, when it should be set to the original amount so that modulation is not applied more than once.

fix(nns): Fix maturity for neurons that temporarily fail to spawn

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/common/rest.rs
packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs
packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/pocket_ic.rs
rs/pocket_ic_server/src/state_api/routes.rs
rs/pocket_ic_server/src/state_api/state.rs
rs/state_machine_tests/src/lib.rs

This PR extends the PocketIC functionality of retrieving ingress status with an optional caller: if provided and if a corresponding read state request for the status of the same update call signed by that specified caller was rejected because the update call was submitted by a different caller, then an error is returned. To distinguish between the ingress status not being available and forbidden due to the new error condition introduced by this PR, a new enumeration `IngressStatusResult` is introduced in the PocketIC library.

feat(PocketIC): optionally check caller when retrieving ingress status

---

rs/consensus/src/consensus/validator.rs
rs/consensus/src/dkg/payload_validator.rs

With https://github.com/dfinity/ic/pull/3039 we will start to serialize maps of the form `(nidkg_tag, nidkg_transcript)` as a vector of `nidkg_transcript`s. This is fine since the NiDkg tag is also part of the NiDkg transcript. More generally, the change makes the assumption `nidkg_tag == nidkg_transcript.tag` explicit. 
As an extra pre-caution, this PR adds a log and metric to increase our confidence that this assumption already holds today (and thus that the change in https://github.com/dfinity/ic/pull/3039 is safe to roll out).

chore: CON-1434 Increment metric in case of `NiDkgTag` mismatches

---

.github/workflows/ci-pr-only-nns-team-reminder.yml
.github/workflows/governance_pull_request_template.yml

This happens via a new GitHub Action. What it does is
```
if review is not requested from nns-team {
return;
}
if already reminded {
return;
}
Add a review that reminds the author that they need to update unreleased_changelog.md.
```
Because the reminder is done as a code review, the author is FORCED to acknowledge the reminder.

feat(governance): Automatically remind governance team to update unreleased_changelog.md.

---

.github/CODEOWNERS

This PR updates the CODEOWNERS file to reflect the merge of the Networking team into the Consensus team.

chore: Update codeowners NET -> CON

---

rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/execution/install_code.rs

The field `threshold` in `InsufficientCyclesInMemoryGrow` error is not quite accurate. Some times it's not only the freezing threshold that might need to be taken into account (assuming the naming comes from that) but also other sources of consuming cycles, like for example the storage reservation cycles. Rename the field to `required` which also matches with the naming of other similar errors that deal with out of cycles cases.

refactor: Rename field in InsufficientCyclesInMemoryGrow error

---

ic-os/guestos/defs.bzl
rs/recovery/src/args_merger.rs
rs/recovery/src/cmd.rs
rs/recovery/src/lib.rs
rs/recovery/src/main.rs
rs/recovery/src/recovery_state.rs
rs/recovery/subnet_splitting/src/main.rs
rs/tests/consensus/subnet_recovery/common.rs
rs/tests/consensus/subnet_recovery/sr_nns_failover_nodes_test.rs
rs/tests/consensus/subnet_recovery/sr_nns_same_nodes_test.rs
rs/tests/consensus/subnet_splitting_test.rs

This PR adds `ic-admin` to the guest OS & adds a CLI argument to make the recovery tool use the local binaries from `/opt/ic/bin`.
With this, we can kick off a non-interactive, local subnet recovery via ssh, by calling the recovery tool with the right arguments. With this change, we should be able to create a system test for local recoveries.
To confirm that this works, I performed a non-interactive recovery on a testnet with the following arguments:
```
/opt/ic/bin/ic-recovery \
--nns-url http://[2602:fb2b:110:10:5025:8bff:fe14:daee]:8080 \
--test \
--skip-prompts \
--use-local-binaries \
app-subnet-recovery \
--subnet-id c3es6-ogziq-a5elm-47c4o-vkins-7kiu4-ekgun-oaeo2-ojd2m-j26wh-eae \
--pub-key "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFx8H9eVvkxl1n7crh/uUzqH03m8Qwlo2k5EE3MJa4Bs …
```

feat(recovery): [CON-1407] Add CLI option to use existing binaries for local recoveries

---

rs/nns/governance/unreleased_changelog.md
testnet/tools/nns-tools/lib/proposals.sh

If the canister does not yet have an unreleased_changelog.md file, the "Features & Fixes" section defaults to a TODO, forcing the release tsar to hand-craft that section.
If this works well, we will also do this for SNS later.
[prev]: https://github.com/dfinity/ic/pull/3332

feat(governance-tools): Use unreleased_changelog.md when generating proposals.

---

Cargo.lock
packages/icrc-ledger-types/CHANGELOG.md
packages/icrc-ledger-types/Cargo.toml

Bump the version of `icrc-ledger-types` to `0.1.7` in order to release the added rustdoc.

feat(icrc-ledger-types): FI-1624: Bump icrc-ledger-types version with the added rustdoc

---

hs/spec_compliance/src/IC/Test/Spec.hs
rs/system_api/src/sandbox_safe_system_state.rs

This PR fixes the reject code in synchronous rejects of mgmt canister calls to be derived from the given `UserError` instead of hard-coded to `CanisterError`.

fix: reject code in synchronous rejects

---

rs/execution_environment/tests/storage_reservation.rs

Reverts dfinity/ic#3360
Failures on master indicate a regression:
* https://github.com/dfinity/ic/actions/runs/12673499329/job/35320020267
* https://github.com/dfinity/ic/actions/runs/12673401969/job/35319700314

revert: "test: Add test for taking a snapshot that triggers storage reservation"

---

rs/registry/canister/src/mutations/node.rs
rs/registry/canister/src/mutations/node_management/do_remove_nodes.rs
rs/tests/nns/node_removal_from_registry_test.rs

Prevent that race conditions such as the one in the following proposal prevent proposal execution:
https://dashboard.internetcomputer.org/proposal/134665
It's impossible to completely prevent race conditions such as this one so we should handle them gracefully when possible.
- Extracted the node retrieval logic into a new function `get_node` that returns an `Option<NodeRecord>`.
- Simplified the `get_node_or_panic` function to leverage `get_node` for node retrieval.
- Updated the `do_remove_nodes` logic to skip nodes that aren't found in the registry, thus handling potential race conditions gracefully.
Also added several tests for the above

feat(NNS): allow execution of proposals that remove non-existing nodes

---

ic-os/components/ic/setup-permissions/erestorecon.sh
ic-os/components/ic/setup-permissions/setup-permissions.sh

This further increases the speed of the [reboot toy](https://github.com/dfinity/ic/blob/36e2b45d4712908b8ddca1c05b50b8fc1d6562d1/rs/tests/node/BUILD.bazel#L31) from 56.578s to 33.395s.

feat: [NODE-1499] Run chown/chmod in setup-permissions in parallel

---

ic-os/defs.bzl
ic-os/guestos/envs/local-base-dev/BUILD.bazel
ic-os/guestos/envs/local-base-prod/BUILD.bazel
ic-os/hostos/defs.bzl
ic-os/hostos/envs/local-base-dev/BUILD.bazel
ic-os/hostos/envs/local-base-prod/BUILD.bazel
ic-os/setupos/defs.bzl
ic-os/setupos/envs/local-base-dev/BUILD.bazel
ic-os/setupos/envs/local-base-prod/BUILD.bazel

This saves a couple gigabytes of cache space per build:
```
ubuntu@devenv-container:/ic$ bazel --noworkspace_rc --bazelrc=./bazel/conf/.bazelrc.build build --disk_cache=,out/disk-cache --config=systest //ic-os/setupos/envs/dev && du -sh ,out
...
Target //ic-os/setupos/envs/dev:dev up-to-date:
bazel-bin/ic-os/setupos/envs/dev/dev_pre_check_result.txt
bazel-bin/ic-os/setupos/envs/dev/disk-img.tar.zst
INFO: Elapsed time: 0.929s, Critical Path: 0.10s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
24G	,out
ubuntu@devenv-container:/ic$ bazel --noworkspace_rc --bazelrc=./bazel/conf/.bazelrc.build build --disk_cache=,out/disk-cache --config=systest //ic-os/setupos/envs/dev && du -sh ,out
...
Target //ic-os/setupos/envs/dev:dev up-to-date: …
```

chore(IDX): don't cache ic-os images

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/lib.rs
rs/nns/governance/unreleased_changelog.md

This is done by flipping a couple of flags.
This is the last step in the release of "periodic confirmation". There is still some post-launch follow up work.
All the usual consequences of this being a flag flip apply. In particular, if we need to roll back, it will be fairly easy and low risk.
This causes a performance regression for metrics. [A ticket][regression] has been opened to follow up on that. For now, this has been deemed acceptable, because metrics are calculated in the background, and is performed infrequently.
[regression]: https://dfinity.atlassian.net/browse/NNS1-3535
Closes [NNS1-3444].
[NNS1-3444]: …

feat(governance): Enable periodic confirmation.

---

ic-os/components/guestos.bzl
ic-os/components/hostos.bzl
ic-os/components/misc/log-config/log-config-guestos.service
ic-os/components/misc/log-config/log-config-hostos.service
ic-os/components/misc/log-config/log-config.sh
ic-os/guestos/defs.bzl
rs/ic_os/config/src/main.rs

Add the log-config service to GuestOS
This service was previously just on HostOS and would log config.ini and deployment.json. Now the service is on HostOS and GuestOS and logs the config object.

feat(node): Add log-config service to GuestOS

---

rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs

Adapt the ICRC golden state test to handle the case where some canisters have already been upgraded to the V4 version, and further no migration is expected to happen if they are upgraded to the same version again.

test(ICRC_Ledger): FI-1625: Adapt golden state test to V4 migration

---

rs/sns/governance/canister/canister.rs
rs/sns/governance/canister/tests.rs

I think this was a bug in the code previously. 
[here](https://github.com/dfinity/ic/blob/4b9b18fcada06a30f9d2286eddcacff6521ace47/rs/sns/governance/canister/canister.rs#L258-L270) is where we serialize Governance:
```rust
#[pre_upgrade]
fn canister_pre_upgrade() {
log!(INFO, "Executing pre upgrade");
let mut writer = BufferedStableMemWriter::new(STABLE_MEM_BUFFER_SIZE);
governance() 
.proto // This gets the `Governance` that's from `ic-sns-governance`
.encode(&mut writer)
.expect("Error. Couldn't serialize canister pre-upgrade.");
writer.flush(); // or `drop(writer)`
log!(INFO, "Completed pre upgrade");
}
```
And this is where we were deserializing it:
```rust
#[post_upgrade]
fn canister_post_upgrade() {
log!(INFO, "Executing post upgrade");
let reader = …
```

fix: SNS Gov canister should deserialize to proto Governance, not API Governance

---

testnet/tools/nns-tools/lib/proposals.sh

This fixes a problem where unreleased_changelog.md is not found if running from a different directory.

fix(proposal-tools): Fix code path to be absolute instead of relative

---

testnet/tools/nns-tools/add-release-to-changelog.sh
testnet/tools/nns-tools/lib/proposals.sh
testnet/tools/nns-tools/lib/util.sh

Add entry to SNS CHANGELOG.md files from unreleased_changelog.md, like how we do with NNS. This just involves making some (small?) changes to the add-release-to-changelog.sh script.
[prev]: https://github.com/dfinity/ic/pull/3388

feat(governance-tools): Populate "Features & Fixes" section of SNS proposals from unreleased_changelog.md.

---

rs/bitcoin/ckbtc/minter/src/guard.rs
rs/bitcoin/ckbtc/minter/src/lib.rs
rs/bitcoin/ckbtc/minter/src/main.rs
rs/bitcoin/ckbtc/minter/src/memo.rs
rs/bitcoin/ckbtc/minter/src/state/audit.rs
rs/bitcoin/ckbtc/minter/src/tasks.rs
rs/bitcoin/ckbtc/minter/src/tasks/tests.rs

XC-237
Since the ckBTC minter switched to using the checker canister, it no longer needs to distribute kyt fees, or reimburse failed kyt. These calls can be removed from the code, but we do still need to keep them for event and state handling during replay.

chore(ckbtc): remove distribute_kyt_fee and reimburse_failed_kyt

---

rs/canister_sandbox/BUILD.bazel
rs/canister_sandbox/bin/canister_sandbox.rs
rs/pocket_ic_server/BUILD.bazel
rs/pocket_ic_server/src/main.rs

This PR runs `install_backtrace_handler` if PocketIC is run as canister sandbox to match the dedicated binary's main function.

fix(PocketIC): run install_backtrace_handler if PocketIC is run as canister sandbox

---

Cargo.lock
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tla/common.rs
rs/nns/governance/src/governance/tla/disburse_neuron.rs
rs/nns/governance/src/governance/tla/mod.rs
rs/nns/governance/tests/fake.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/tla/Disburse_Neuron.tla
rs/nns/governance/tla/Disburse_Neuron_Apalache.tla
rs/nns/governance/tla/Spawn_Neurons.tla
rs/nns/governance/tla/Split_Neuron.tla
rs/tla_instrumentation/BUILD.bazel
rs/tla_instrumentation/tla_instrumentation/Cargo.toml
rs/tla_instrumentation/tla_instrumentation/tests/multiple_calls.rs
rs/tla_instrumentation/tla_instrumentation_proc_macros/src/lib.rs

Adds TLA instrumentation for `disburse_neuron`. Since this calls `transfer_funds` multiple times, we also need some additional functionality to disambiguate the different call sites. The disambiguation requires a small tweak to the existing models (of spawn, split, etc).
Moreover the disambiguation functionality (based on the `tla_function` macro) didn't play well with `async_trait`, so we add a special case to handle that.

feat(IC-1579): TLA instrumentation for `disburse_neuron`

---

rs/execution_environment/tests/storage_reservation.rs

This is a redo of #3360. Matching on the exact number of bytes requested can be flaky apparently so instead focus on matching only on the required amount of cycles in the error message which is the focus of the test anyway.

test: Add test for taking a snapshot that triggers storage reservation

---

Cargo.lock
rs/embedders/src/compilation_cache.rs
rs/embedders/src/serialized_module.rs
rs/execution_environment/src/hypervisor.rs
rs/execution_environment/src/query_handler/query_cache.rs
rs/execution_environment/src/query_handler/query_cache/tests.rs
rs/interfaces/src/execution_environment/errors.rs
rs/types/types/src/ingress.rs
rs/types/types/src/lib.rs
rs/types/wasm_types/src/lib.rs
rs/utils/lru_cache/BUILD.bazel
rs/utils/lru_cache/Cargo.toml
rs/utils/lru_cache/src/lib.rs

EXC-1795
Add the ability for the LRU cache to limit space used on disk as well as in memory and use this in the `CompilationCache` so that it doesn't grow to large.

feat(EXC-1795): Limit cache disk space

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/neuron_store/benches.rs

In the analysis of the safety of migrating neurons from heap to stable memory, one risk is that the `draw_maturity_from_neurons_fund`/`refund_maturity_to_neurons_fund` can take more instructions since reading from stable structures is more expensive. Therefore, the safety of such operations start to depend on how many neurons are involved in those operations. Adding a comment should help preventing any increase of this constant without considering its implications on the instructions cost.

chore(nns): Add a comment on MAX_NEURONS_FUND_PARTICIPANTS about its effect on instructions

---

Cargo.lock
Cargo.toml
rs/nervous_system/tools/release-runscript/BUILD.bazel
rs/nervous_system/tools/release-runscript/Cargo.toml
rs/nervous_system/tools/release-runscript/src/main.rs

This PR introduces a simple interactive "runscript" version of our NNS release runbook. 
A runscript is what I call a program that walks you through a procedure step-by-step, waiting for confirmation before showing the next step.
Runscripts have one big advantage over runbooks: They're easy to automate incrementally. Just replace "press enter to continue" with actual automation for specific step.
This first version is intentionally simple - it just shows the steps and waits for the user to press enter. But it provides a foundation we can build on to gradually automate pieces of the release process.

feat(sns): add release runscript to replace runbook in notion

---

rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml
rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml
rs/ledger_suite/icrc1/ledger/src/benches/benches_u256.rs
rs/ledger_suite/icrc1/ledger/src/benches/benches_u64.rs
rs/ledger_suite/icrc1/ledger/src/benches/mod.rs
rs/ledger_suite/icrc1/ledger/src/main.rs

Scopes for `icrc2_approve`, `icrc2_transfer_from` and `icrc3_get_blocks` were added. Scope `before_upgrade` was renamed to `icrc1_transfer`. Since we now test with more approvals, balances and blocks, the benchmark files need to be completely regenerated.

test(ICRC_Ledger): canbench benchmarks for icrc2_approve, icrc2_transfer_from and icrc3_get_blocks

---

rs/ledger_suite/icrc1/archive/BUILD.bazel
rs/ledger_suite/icrc1/archive/src/main.rs

Verify that the candid `Block` type returned by the ICRC ledger and archive canisters are the same.

test(ICRC_Ledger): FI-1043: Verify ICRC ledger and archive block equality

---

rs/ledger_suite/icrc1/index-ng/BUILD.bazel
rs/ledger_suite/icrc1/index-ng/src/main.rs

Verify that the candid `Block` type returned by the ICRC ledger and index canisters are the same.

test(ICRC_Index): FI-1042: Verify ICRC ledger and index block equality

---

rs/ledger_suite/icp/index/BUILD.bazel
rs/ledger_suite/icp/index/src/main.rs

Add a test that verifies the ICP ledger and index encoded block response type compatibility. Since the response types are not exactly the same, the best we can do is a Candid subtype check.

test(ICP_Ledger): FI-1036: Add ICP ledger and index encoded block response compatibility

---

rs/embedders/src/wasm_utils.rs
rs/execution_environment/tests/execution_test.rs

EXC-1834
Avoid triggering our critical error alert in the case where a module has empty data segments.

fix(EXC-1834): Ignore empty data segment pages

---

rs/embedders/src/wasm_executor.rs
rs/embedders/src/wasmtime_embedder.rs

EXC-1800
When using the on-disk compilation cache, switch to Wasmtime's new `deserialize_open_file` API which allows sandboxes to mmap the existing file so that canister code doesn't take up resident memory in the sandbox.

feat(EXC-1800): Use Wasmtime `deserialize_open_file`.

---

testnet/tools/nns-tools/add-release-to-changelog.sh

The main difference is that the wording of SNS proposal titles is different. With these changes, the script can also parse SNS proposal titles. Since the format of SNS titles is similar to those of NNS, this change is straightforward.
[prev]: https://github.com/dfinity/ic/pull/3332

feat(governance-tools): Support creating entries in SNS CHANGELOG.md files.

---

bazel/sanitizers_enabled_env/defs.bzl

This ensures that the repository rule get re-evaluated when the env var changes without having to specify it as a rule input.

chore(IDX): Use repository_ctx.getenv

---

testnet/tools/nns-tools/add-release-to-changelog.sh

Added a success message.
Added emojis.
Changed informational messages from purple to cyan. I think dark grey would be best, but we don't (yet) have a function for that; cyan seems like the next best thing.
Silence is a highly ambiguous way to communicate.
> Explicit is better than implicit.
> --Zen of Python

feat(governance-tools): Pretty add-release-to-changelog.sh output.

---

rs/consensus/benches/validate_payload.rs

Currently we only measure how much it takes to deserialize/serialize ingress payloads with 2000/4000/6000/8000 messages each of size 1KB. With the changes in this PR we will instead measure the following test cases:
1. 1000 messages, 4KB each
2. 2000 messages, 4KB each
3. 1 message, 4MB
4. 1 message, 8MB
which resembles more closely the current limits on the ingress payload, from both number of messages and message sizes extremes.
Also, in the deserialization benchmark we moved out the `clone()` as it affects the measurements significantly.

test(consensus): modify the test cases in ingress payload serialization/deserialization benchmarks

---

Cargo.lock
rs/ic_os/fstrim_tool/BUILD.bazel
rs/ic_os/fstrim_tool/Cargo.toml
rs/ic_os/fstrim_tool/src/lib.rs
rs/ic_os/fstrim_tool/src/metrics/mod.rs
rs/ic_os/fstrim_tool/src/metrics/tests.rs
rs/ic_os/fstrim_tool/src/tests.rs
rs/ic_os/fstrim_tool/tests/integration_tests.rs

NODE-1537
Node decommissioning stage 2 was rolled out in a hurry so that we could make the holiday-release cutoff: https://github.com/dfinity/ic/pull/2953 
These changes add the missing observability logic.
Main commits:
- [Add datadir metrics](https://github.com/dfinity/ic/pull/3322/commits/a1e6dbb99e60c8397d5ff9b7b8b1b839a5d0c0e2)
- [Update unit tests](https://github.com/dfinity/ic/pull/3322/commits/513ba80c20709d74fd7631fe3566ba6f92bd8679)
Screenshot of metrics:

feat(node): add fstrim datadir observability

---

Cargo.lock
rs/registry/canister/Cargo.toml

The following command currently failed to compile the registry canister if running from the /ic/rs/registery/canister sub-directory: 
cargo build --profile canister-release --target wasm32-unknown-unknown --bin registry-canister
The fix is to make sure the feature `getrandom/custom` is enabled.
Note that the above command would succeed if running from the top-level directory, but would produce incorrect wasm binary. This is because cargo would bring in global dependencies that enable both `getrandom/custom` and `getrandom/js` features, and the latter will lead to wasm binaries having unwanted imports (See #3309 for more details).
Since this problem does not affect bazel builds, this fix is only relevant to cargo.

fix: cargo build registry-canister for wasm32 target

---

rs/pocket_ic_server/src/pocket_ic.rs
rs/state_machine_tests/src/lib.rs

This PR safely drops every StateMachine in PocketIC to prevent its state directory from being deleted before every Arc to its state manager is dropped.

fix(PocketIC): safely drop StateMachine

---

rs/consensus/src/consensus/malicious_consensus.rs
rs/consensus/src/consensus/metrics.rs
rs/consensus/src/consensus/purger.rs
rs/ingress_manager/src/ingress_selector.rs
rs/interfaces/src/ingress_manager.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/download.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/stripper.rs
rs/protobuf/def/types/v1/consensus.proto
rs/protobuf/src/gen/types/types.v1.rs
rs/state_machine_tests/src/lib.rs
rs/types/types/src/batch/ingress.rs
rs/types/types/src/exhaustive.rs
rs/types/types/src/messages.rs

Currently the payload is one big bytes buffer which contains all ingress messages in a packed representation. This makes it a big hard to work with. 
In this PR we simplify the structure by replacing the buffer with a map from `IngressMessageId`s to a _serialized_ ingress messages.
The following two important properties are preserved:
1. The individual ingress messages deserialization is delayed until it's actually needed
2. We preserve the original byte representation of the ingress messages
I've ran multiple benchmarks and didn't notice a _big_ change:
1. `consensus-performance` system test showed the same throughput / block rates with both implementations
2. the [serialization/deserialization ](https://github.com/dfinity/ic/blob/master/rs/consensus/benches/validate_payload.rs#L374-L404) …

refactor(consensus): simplify `IngressPayload` implementation

---

rs/nns/governance/canister/canister.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/tests/governance.rs

This removes code that fixed a neuron that was locked as a result of a ledger upgrade happening during spawn.

chore(nns): Remove one-off fix for broken neuron after deployment

---

rs/execution_environment/src/execution/update.rs
rs/execution_environment/src/execution_environment/tests/canister_task.rs

Problem:
@mraszyk  noticed [here](https://github.com/dfinity/portal/pull/3761#issuecomment-2478612255) that property:
”If the canister gets frozen immediately after the function is scheduled for execution, the function will run once the canister's unfrozen if the canister's wasm memory remains above the threshold t.”
is missing.
Solution:
When execution of the hook is stopped because of the freezing canister, add the hook again to the task queue.

fix: [EXC-1831] Low Wasm memory hook will run once the canister's unfrozen if it was scheduled before freezing

---

rs/tests/ckbtc/BUILD.bazel
rs/tests/cross_chain/BUILD.bazel
rs/tests/message_routing/BUILD.bazel
rs/tests/networking/BUILD.bazel

Removing `k8s` tag from tests that are not functional on k8s. Tag will be added back again once the cause is identified and resolved. This change is **only relevant for having system tests functional on k8s** (this project is still in incubation phase).

chore(system-tests-k8s): untag broken k8s tests

---

Cargo.lock
rs/state_layout/src/state_layout.rs
rs/state_machine_tests/src/lib.rs
rs/state_manager/src/lib.rs
rs/state_tool/BUILD.bazel
rs/state_tool/Cargo.toml
rs/state_tool/src/commands.rs
rs/state_tool/src/commands/copy.rs
rs/state_tool/src/commands/import_state.rs
rs/state_tool/src/main.rs

This commit introduces the "copy" subcommand to the state-tool copying checkpoints from one place to another.
This command can both be used to backup a state as well as importing a state to an existing directory. It handles both the checkpoint files itself as well as the accompanying metadata such as manifests.
The new subcommand is more general than the existing "import" subcommand, as the old one only allows for imports and does not handle metadata. This commit does however not remove "import" in case somebody relies on it, and simplifies its internals a bit instead.

chore: state-tool copy commands

---

rs/bitcoin/replica_types/src/lib.rs
rs/types/types/src/batch.rs
rs/types/types/src/batch/ingress.rs
rs/types/types/src/batch/self_validating.rs
rs/types/types/src/batch/xnet.rs
rs/types/types/src/canister_http.rs
rs/types/types/src/consensus/dkg.rs
rs/types/types/src/consensus/payload.rs

This PR fixes two minor `BatchPayload` bugs:
1. The query stats payload was not considered when determining if a batch payload is empty.
2. The canister ID of `CanisterHttpResponse`s was not considered in `count_bytes`.
To prevent similar problems in the future, this PR changes implementations of `is_empty` and `count_bytes` to deconstruct `self` first, such that forgotten fields can be more easily spotted.

fix: Consider all fields in `is_empty` and `count_bytes` implementation for `BatchPayload`

---

rs/sns/cli/src/propose.rs
rs/sns/governance/src/types.rs

This is a little clearer I think since the type returns `Vec<NervousSystemFunction>`.

fix(sns): rename `proposal_types_disallowed_in_pre_initialization_swap` → `functions_disallowed_in_pre_initialization_swap`

---

.github/workflows/system-tests-k8s.yml

Updating `test_tag_filters` for CI job that cover tests that should be shorter then 5 minutes. Including tests that are longer then 5 minutes in CI job that covers hourly tests.

fix(system-tests-k8s): exclude long tests

---

rs/rosetta-api/icp/src/rosetta_server.rs

The `/ metrics` endpoint was returning a `text/html` type, which is rejected by metrics collectors like Prometheus.
I've verified that the new type is correctly collected by Prometheus.

fix(icp-rosetta): fix icp rosetta metrics reponse time

---

rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/scheduler_metrics.rs
rs/execution_environment/src/scheduler/tests.rs

The `scheduler_canister_age_rounds` metric tracks the difference between the current round and the round in which the canister last fully executed. By default, this last executed round is set to zero for newly created canisters. Consequently, the `canister_age` metric for these new canisters abruptly increases to the current round, which can be in the billions.
This PR addresses this issue by excluding canisters with a zero 'last executed round' from the `canister_age` metric observations.
Furthermore, this PR increases the upper bound of the metric's range to 5000 rounds.

fix: EXC-1765: Fix `canister_age` metric

---

ic-os/setupos/defs.bzl
rs/ic_os/config/src/generate_testnet_config.rs

NODE-1560
[wiki.internetcomputer.org](http://wiki.internetcomputer.org/) resolves to only an IPv4 address (107.161.28.131)
```
$ nslookup wiki.internetcomputer.org
Server:         127.0.0.53
Address:        127.0.0.53#53
Non-authoritative answer:
Name:   wiki.internetcomputer.org
Address: 107.161.28.131
```
This caused bare metal deployment tests to fail when only ipv6 info is provided. Changing to a more standard url fixes this.

fix(node): update development nns_url

---

packages/icrc-cbor/CHANGELOG.md

Adding the initial library version to be able to publish to crates.io.

feat: icrc-cbor: initial version of the library

---

packages/pocket-ic/HOWTO.md
rs/pocket_ic_server/tests/bitcoin_integration_tests.rs

This PR prevents spurious errors in PocketIC bitcoin integration tests
```
---- bitcoin_integration_test stdout ----
thread 'bitcoin_integration_test' panicked at rs/pocket_ic_server/tests/bitcoin_integration_tests.rs:145:10:
called `Result::unwrap()` on an `Err` value: JsonRpc(Transport(SocketError(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))
stack backtrace:
```
by retrying generating blocks until the bitcoind is up and running.

chore(PocketIC): retry in PocketIC bitcoin integration tests

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs
packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/CHANGELOG.md

This PR splits the function `PocketIc::ingress_status` taking an optional caller into a pair of functions:
- `PocketIc::ingress_status` taking no caller and returning a more precise return type;
- `PocketIc::ingress_status_as` taking a non-optional caller and returning the original return type.
This way, the use cases of just fetching the ingress status and also checking the caller are properly separated (no need to pass `None` in the former use case) and the return types are more precise.

feat(PocketIC): new library function PocketIc::ingress_status_as

---

rs/state_tool/src/commands/copy.rs
rs/state_tool/src/main.rs

Improves some of the error messages of the `state-tool copy` command. In particular it makes it more clear when the failure might have left the directory contents inconsistent.

chore: Improve some state tool error messages

---

rs/types/management_canister_types/src/lib.rs

Change variant names for the Wasm memory persistence to lower case in line with the IC specification, i.e. using `keep` and `replace` instead of `Keep` and `Replace`. The Wasm memory persistence option is used for Motoko's enhanced orthogonal persistence, which is currently still in beta testing. 
The following components need to be updated once these changes are released on IC mainnet and `dfx`:
* The Motoko compiler (https://github.com/dfinity/motoko/pull/4854)
* The Motoko playground (https://github.com/dfinity/motoko-playground/pull/275)
No change is needed for `dfx`.
For installed Motoko programs using enhanced orthogonal persistence, the change only affects the programmatic upgrades of Motoko actor class instances. Existing such programs would need to be recompiled with a new Motoko …

fix: Use lower case for Wasm persistence modes

---

rs/sns/integration_tests/src/upgrade_canister.rs

This PR aims to reduce flakiness in `//rs/sns/integration_tests/test_upgrade_canister_proposal_execution_fail` by bumping expected SNS dapp canister upgrade time from 30 to 60 seconds.

test(sns): Bump expected SNS dapp canister upgrade time from 30 to 60 seconds in testing

---

rs/sns/integration_tests/src/proposals.rs

The `//rs/sns/integration_tests:integration_test_src/proposals` is more than 4% flaky. Every time it fails it's because the                `assert!(age_seconds < 30.0, ...)` fails ([example](https://dash.zh1-idx1.dfinity.network/invocation/777191ad-ed01-4bcc-84a9-48d820d23fec?target=%2F%2Frs%2Fsns%2Fintegration_tests%3Aintegration_test_src%2Fproposals&targetStatus=11)). This commit attempts to fix it by bumping the expected maximum ballot age from 30 to 60 seconds.

test(sns): bump expected max ballot age to reduce flakiness in //rs/sns/integration_tests:integration_test_src/proposals

---

.github/workflows/system-tests-k8s.yml

I filter system tests that have `k8s` tag and are either `long_test` or `system_test_hourly`.

fix(system-tests-k8s): hourly targets

---

Cargo.lock
Cargo.toml
rs/nervous_system/candid_utils/BUILD.bazel
rs/nervous_system/candid_utils/Cargo.toml
rs/nervous_system/candid_utils/src/lib.rs
rs/nervous_system/candid_utils/src/validation.rs
rs/nervous_system/candid_utils/src/validation/tests.rs

This PR adds a new crate dedicated to Candid utilities that are likely to be useful in multiple places in the mono repo.
First, we add `candid_utils::validation::validate_upgrade_args`, which takes a full Candid service and checks if a given upgrade argument complies with it, using Candid subtyping. In particular, this function will soon be required in a tool for submitting upgrade proposals for SNS-controlled canisters.
| [Next PR](https://github.com/dfinity/ic/pull/3439) >

feat(nervous-system): Add crate candid-utils and add proper Candid service argument validation

---

.github/workflows/system-tests-k8s.yml

Use `--local_test_jobs` to limit parallelism only on test targets and not on build targets. Setting default `--local_test_jobs` to 10. This will be raised on a new cluster. On long term some queuing logic will have to be introduced in `setup` phase of system test driver.

chore(system-tests-k8s): use --local_test_jobs

---

rs/tests/driver/src/driver/bootstrap.rs
rs/tests/driver/src/driver/boundary_node.rs
rs/tests/driver/src/k8s/tnet.rs

Adding container disk logic for boundary node config disks. This was missed in https://github.com/dfinity/ic/pull/3481

fix(k8s-system-tests): containerDisk for boundary node

---

rs/rosetta-api/scripts/download_latest_icrc1_ledger.sh

Modify the helper script to download the latest ICRC ledger release, rather than the WASM built from the tip of the master branch.

feat(ICRC_Ledger): FI-1600: Download the latest ICRC ledger release instead of tip of master

---

rs/tests/crypto/canister_sig_verification_cache_test.rs

Try to keep the duration of the test always under 5 minutes.

test(crypto): lower `canister_sig_verification_cache_test` test params

---

rs/system_api/src/lib.rs
rs/system_api/tests/common/mod.rs
rs/system_api/tests/system_api.rs

This PR fixes some bugs in how the system API was reporting replicated vs non-replicated mode. Specifically, it was incorrectly reporting that `inspect_message`, a composite query `reply_callback` and `reject_callback` were running in replicated mode, although they are really running in non-replicated mode.

fix: Correct the value returned for replicated vs non replicated execution in system api

---

.github/workflows/system-tests-k8s.yml

* remove docker login
* run system tests 4 times during the night time
* also run longer system tests on manual dispatch
* set concurrency

chore(system-tests-k8s): misc changes

---

testnet/tools/nns-tools/add-release-to-changelog.sh

The most important thing is that the name of the canister is now printed where it says how long ago the proposal was executed.
Other than that removed some blank lines.

feat(governance-tools): Made the output from add-release-to-changelog a little better.

---

rs/consensus/dkg/src/dkg_key_manager.rs
rs/consensus/dkg/src/lib.rs
rs/consensus/dkg/src/payload_builder.rs
rs/consensus/dkg/src/payload_validator.rs
rs/consensus/src/cup_utils.rs
rs/consensus/utils/src/lib.rs
rs/replay/src/lib.rs
rs/test_utilities/consensus/src/lib.rs
rs/types/types/src/consensus/dkg.rs

This PR makes changes to DKG in order to prepare the implementation of CON-1413.
In particular, it makes two changes:
1. `Summary::current_transcript` now returns an `Option`, rather than panicking.
With the introduction of the `NiDkgTag::HighThresholdForKey(_)`, we can no longer enumerate all variants, and we should not assume that the `Summary` contains all the tags we assume. In fact, when generating a vetkey, we will end up in situations where `next_transcripts` contains tags that `current_transctips` doesn't have. This PR simply adds unwraps at all call sites, since the code should not panic, if called with `NiDkgTag::LowThreshold` or `NiDkgTag::HighThreshold`.
2.  Reimplement `into_next_transcripts` and move it into `dkg` crate
The current implementation is slightly wrong, since it …

refactor(consensus): Refactor code in NiDkg to prepare VetKD implementation

---

Cargo.lock
Cargo.toml
rs/tests/consensus/vetkd/BUILD.bazel
rs/tests/consensus/vetkd/Cargo.toml
rs/tests/consensus/vetkd/vetkd_key_life_cycle_test.rs

This PR sets up the integration tests for the consensus components of the vetkeys feature.
For now, it only has a system test that adds a vetkey and checks that the subnet makes progress.
This is to test, that code changes to be added later are not breaking the subnet, if a key gets added.
As more features are being implemented, we can expand the test to check more functionality and add more tests, for now it simply serves a smoke test.

test(Consensus): Add a stub test for vetkd

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/governance/benches.rs

Add a benchmark for listing proposals before doing any optimizations

perf(nns): Add a benchmark for listing proposals

---

rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs

The monitoring thread may collect information about each sandbox process for a few seconds. Consequently, metrics scraping might occur during this collection phase, leading to an underreporting of the number of sandboxes.
This PR addresses this issue by:
1. Collecting metrics into small vectors of `f64` values. This allows for more efficient and consistent data gathering.
2. Observing the metrics within a tight loop. This ensures that the latest and most accurate data is captured.
While this approach may not completely eliminate the possibility of an incomplete sandbox count, it should significantly reduce the likelihood of this occurring.

fix: EXC-1815: Fix sandbox processes metric

---

rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/providers.rs
rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
rs/ethereum/evm-rpc-client/src/lib.rs

([XC-272](https://dfinity.atlassian.net/browse/XC-272)) Replace rpc.sepolia.org by Ankr
Remove the rpc.sepolia.org RPC Sepolia provider, and replace it with Ankr. Ankr was originally removed due to a lack of IPv6 compatibility, but this seems to have been fixed in the meantime.
[XC-272]: https://dfinity.atlassian.net/browse/XC-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(cketh/ckerc20): Replace rpc.sepolia.org by Ankr

---

Cargo.lock
rs/execution_environment/BUILD.bazel
rs/execution_environment/Cargo.toml
rs/execution_environment/tests/storage_reservation.rs

EXC-1843
Adjust a test on reservation costs so that it doesn't rely on the exact cycles costs because these might change.

fix(EXC-1843): Make reservation test robust to costs

---

Cargo.lock
rs/p2p/artifact_downloader/BUILD.bazel
rs/p2p/artifact_downloader/Cargo.toml
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/assembler.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/download.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/metrics.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/stripper.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/test_utils.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/types.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/types/rpc.rs
rs/p2p/artifact_downloader/src/fetch_stripped_artifact/types/stripped.rs
rs/protobuf/def/types/v1/consensus.proto
rs/protobuf/src/gen/types/types.v1.rs
rs/types/types/src/batch/ingress.rs

Currently, with the feature flag enabled, when a node sends a block proposal to their peers it first removes all the ingress messages from the block's payload, leaving behind only the `IngressMessageId`s which identify the ingress messages. When a node receives such a "stripped" block proposal it _reconstructs_ the block by retrieving the referenced ingress messages from:
1. either their local ingress pools if there exists an ingress message with the given `IngressMessageId` there,
2. or by requesting the missing ingress messages from peers who are advertising the block.
The problem with the approach is that the `IngressMessageId`s do _not_ uniquely identify the the ingress messages and two ingresses with the same content _but_ with different signatures have the same id. We thus could end …

fix(consensus): fix the `hashes-in-blocks` feature implementation

---

rs/canister_sandbox/src/protocol/ctlsvc.rs
rs/canister_sandbox/src/protocol/structs.rs
rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
rs/canister_sandbox/src/sandbox_manager.rs
rs/embedders/src/wasm_executor.rs
rs/embedders/tests/wasmtime_embedder.rs
rs/execution_environment/src/execution/common.rs
rs/execution_environment/src/execution/install_code.rs
rs/execution_environment/src/execution/response.rs
rs/execution_environment/src/execution/update.rs
rs/execution_environment/src/hypervisor.rs
rs/execution_environment/src/scheduler/test_utilities.rs
rs/system_api/src/lib.rs
rs/system_api/src/sandbox_safe_system_state.rs
rs/system_api/tests/sandbox_safe_system_state.rs
rs/system_api/tests/system_api.rs

All the other structs that maintain modifications of different parts of the canister state use `*Modifications` in their name, so change `SystemStateChanges` to use it as well for consistency.

refactor: Rename SystemStateChanges to SystemStateModifications for consistency

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/pb/conversions.rs
rs/nns/governance/src/pb/mod.rs
rs/nns/governance/src/pb/tests.rs
rs/nns/governance/src/proposals/install_code.rs
rs/nns/governance/tests/degraded_mode.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/unreleased_changelog.md

Calculating hashes for wasm/arg actually takes quite a bit of instructions (80/byte), which makes it the dominant part of the list_proposals instructions. Such hashes can be calculated during write operations easily, since the data should be immutable.
* Add `wasm_module_hash` and `arg_hash` into `InstallCode` internal type
* Move hash calculation from read operation (internal -> response) to write operation (request -> internal)
* Add backfill for existing `Installcode` proposals
* Update benchmark results (96% improvement on list_proposals)

feat(nns): Avoid recomputing wasm/arg hashes during read operations

---

rs/http_endpoints/public/src/query.rs

This PR uses the user error description as the reject message for query calls to make the query call reject message matches the reject message for ingress message produced [here](https://github.com/dfinity/ic/blob/85af5fc7b9963f10bb6fd30d7929814501d783c7/rs/canonical_state/src/lazy_tree_conversion.rs#L517).
Using the `Display` implementation of `UserError` instead of the description [repeats](https://github.com/dfinity/ic/blob/85af5fc7b9963f10bb6fd30d7929814501d783c7/rs/types/error_types/src/lib.rs#L462) the error code in the reject message while the error code is also available as a [separate](https://github.com/dfinity/ic/blob/85af5fc7b9963f10bb6fd30d7929814501d783c7/rs/http_endpoints/public/src/query.rs#L235) field in the query call reject response.

fix: do not repeat error code in query call reject message

---

toolchains/sysimage/build_ext4_image.py

The resulting images are equivalent (verified with `rsync -avnc $DIR1/ $DIR2`).
`$ bazel build //ic-os/guestos/envs/dev:static-partition-root-unsigned.tzst`
Before: 26.593s  
After: 19.926s

perf: Move file system population to mkfs.ext4 invocation

---

rs/sns/governance/CHANGELOG.md
rs/sns/governance/src/types.rs
rs/sns/governance/unreleased_changelog.md

This PR makes the `SnsGov.list_proposals` query include the `chunked_canister_wasm` field for `UpgradeSnsControlledCanister` proposals. Previously, this field has been redacted from the response payload.

feat(sns): `SnsGov.list_proposals` includes `chunked_canister_wasm`

---

rs/registry/admin/src/main.rs

The interface is backwards compatible, just ic-admin will now default to the mainnet if no argument is provided.

fix(ic-admin): set default NNS URL to the mainnet one

---

packages/pocket-ic/BUILD.bazel
packages/pocket-ic/HOWTO.md
packages/pocket-ic/src/lib.rs
rs/pocket_ic_server/BUILD.bazel
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/main.rs
rs/pocket_ic_server/src/state_api/canister_id.rs
rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/bitcoin_integration_tests.rs
rs/pocket_ic_server/tests/test.rs

Reverting this [PR](https://github.com/dfinity/ic/pull/3280) since the flakiness [persists](https://github.com/dfinity/ic/actions/runs/12948633271/job/36117683459?pr=3595).

fix: Revert "fix: bind to [::1] per default instead of 127.0.0.1 in PocketIC (#3280)"

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs
packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/src/pocket_ic.rs
rs/pocket_ic_server/src/state_api/routes.rs
rs/state_machine_tests/src/lib.rs

This PR introduces a new PocketIC operation to set certified time so that query calls and read state requests are evaluated on a state with that (certified) time. Using this new operation to set time in the "live" mode also fixes test [flakiness](https://github.com/dfinity/ic/actions/runs/12909846684/job/35998504336).

feat(PocketIC): new PocketIC operation to set certified time

---

rs/replicated_state/src/canister_state/queues/tests.rs
rs/tests/message_routing/queues_compatibility_test.rs

Have `queues_compatibility_test` also persist and restore best-effort requests and responses.
Unfortunately, the mainnet version that we test against must also have the test module encoding and decoding the same messages (in this case `best_effort_test`) before the test can actually work. So we will require a second stage to actually enable the test once the mainnet version includes this newly added test module.

test(MR): [MR-638] Include best-effort messages in `queues_compatibility_test`, stage 1

---

Cargo.lock
publish/canisters/BUILD.bazel
rs/nns/cmc/BUILD.bazel
rs/nns/cmc/Cargo.toml
rs/nns/cmc/src/lib.rs
rs/nns/cmc/src/main.rs
rs/nns/integration_tests/BUILD.bazel
rs/nns/integration_tests/Cargo.toml
rs/nns/integration_tests/src/cycles_minting_canister.rs
rs/nns/test_utils/src/common.rs
rs/nns/test_utils/src/state_test_helpers.rs

This happens when the `memo` (or `icrc1_memo`) in an ICP transfer is not one of the special values that CMC recognizes as signaling the purpose of the transfer.
This behavior gets triggered when one of the `notify_*` methods gets called.
The new behavior is not actually active yet. To turn it on, we simply need to set `IS_AUTOMATIC_REFUND_ENABLED` to true. I have run the tests with this set to true locally, and they pass.
Avoids ICP getting stuck, which can result from people making mistakes when sending ICP to the CMC.
Added `issue_automatic_refund_if_memo_not_offerred`. As indicated by the name, this is the heart of the implementation of this new functionality. This is called from `fetch_transaction`. The call is guarded behind the aforementioned `IS_AUTOMATIC_REFUND_ENABLED` flag. …

feat(cycles-minting): Cycles Minting canister refunds automatically.

---

rs/rust_canisters/canister_test/src/canister.rs
rs/rust_canisters/tests/test/canister_management.rs
rs/tests/driver/src/util.rs
rs/tests/nns/nns_cycles_minting_multi_app_subnets_test.rs
rs/tests/nns/nns_cycles_minting_test.rs
rs/types/management_canister_types/src/lib.rs

`CanisterStatusResult` was used by NNS canisters but not anymore

chore: Remove deprecated CanisterStatusResult type

---

rs/http_endpoints/public/src/lib.rs

the redirect from `/` and `/_/` to the dashboard service, `/_/dashboard` should return `307`
We can use `307` instead of `302` as the endpoints `/` and `/_/` ony support the method `GET`, meaning that clients preserving the method for the redirect gives the same behavior as using `302`.

chore: change redirect code from 303 to 307

---

ic-os/components/boundary-guestos/opt/ic/bin/setup-ic-gateway.sh

Disable latency load shedding since it causes some false positives. Also remove deprecated config option.

fix: ic-gateway: remove load shedding

---

rs/http_endpoints/public/src/call/ingress_watcher.rs

This PR propagates panics from cancellations tasks.

chore: handle panics when joining on cancellations in ingress_watcher event loop

---

rs/http_endpoints/public/src/call/call_v3.rs
rs/http_endpoints/public/src/metrics.rs

The todo messages are completed in a PR that adds alerts/slack notifications.

chore: remove todo messages in call_v3.rs

---

ic-os/components/misc/config/setupos/config.sh
ic-os/components/setupos-scripts/check-network.sh

normalize config.sh get_config_value:
- If key not found or value is "null", returns empty string. Otherwise, returns value

chore(node): normalize config.sh to return empty string

---

rs/nervous_system/candid_utils/src/validation.rs
rs/nervous_system/candid_utils/src/validation/tests.rs

This PR makes the `validate_upgrade_args` function take `upgrade_args: Option<String>` rather than `upgrade_args: String`, making it simpler for the caller to decide if a given service expects no arguments.
Also, we add `encode_upgrade_args_unsafe` which can be used when a Candid service is not available, and thus the upgrade argument cannot be validated against an expected input type.

feat(candid-utils): Better validation for Candid services without arguments

---

rs/crypto/src/sign/threshold_sig/ni_dkg/transcript.rs
rs/crypto/src/sign/threshold_sig/store.rs
rs/crypto/src/sign/threshold_sig/store/tests.rs
rs/crypto/src/sign/threshold_sig/tests.rs

Stores the registry version in the threshold sig data store whenever an NI-DKG transcript is loaded. This will later be needed for implementing the VetKdProtocol.

feat(crypto): CRP-2670 store registry version in threshold sig data store

---

rs/nns/cmc/src/main.rs

This is per [feedback] from Andrew Lee.
[feedback]: https://github.com/dfinity/ic/pull/3484#discussion_r1929281626

docs(cmc): Fixed a comment in CMC automatic refund.

---

rs/nns/governance/src/neuron_store/metrics.rs
rs/nns/governance/src/neuron_store/metrics/tests.rs

The `neurons_fund_total_active_neurons` calculation was wrong when `allow_active_neurons_in_stable_memory = true` and `migrate_active_neurons_to_stable_memory = false` (the first phase of the migration). This was not detected in tests because the 2 flags always have the same value (both true or both false).
- Fix the metric calculation
- Add an inactive neuron into test, and test the metrics calculation under different combinations of the flag
- Documented that the previous calculation of `dissolved_neurons_count` and `neurons_with_less_than_6_months_dissolve_delay_count` are wrong when inactive neurons are in stable memory, and letting the tests reflect that

fix(nns): Fix neurons_fund_total_active_neurons metric

---

rs/nns/governance/src/lib.rs
rs/nns/governance/unreleased_changelog.md

Turn on 2 features:
- ALLOW_ACTIVE_NEURONS_IN_STABLE_MEMORY: this feature enables the canister to read active neurons in stable memory
- USE_STABLE_MEMORY_FOLLOWING_INDEX: this feature starts to let the canister use the neuron following index in the stable memory, instead of the one in the heap
Those will prepare us to turn on the active neurons migration into stable memory, in the next proposal.

feat: Turn on the features to allow active neurons in stable memory and use stable following index

---

rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/list_neurons.rs
rs/nns/governance/unreleased_changelog.md
rs/nns/integration_tests/src/governance_neurons.rs

The `include_empty_neurons_readable_by_caller` flag was default to true in order to retain the behavior before it was introduced. Now that it has been introduced for a while, changing its default to false will help preserving resources in the NNS Governance.
Details can be found at: https://forum.dfinity.org/t/listneurons-api-change-empty-neurons/40311

feat(nns): Change `include_empty_neurons_readable_by_caller` default to false

---

rs/nns/cmc/src/lib.rs
rs/nns/cmc/unreleased_changelog.md
rs/nns/integration_tests/src/cycles_minting_canister.rs

Implementation of this feature was done in an [earlier PR][impl], but was left disabled. For details of this feature, see the description of the aforementioned PR.
[impl]: https://github.com/dfinity/ic/pull/3484
Per the reminder bot, an entry has been added to unreleased_changes.md.

feat(cycles-minting-canister): Enabled automatic refunds.

---

rs/nns/common/src/lib.rs
rs/nns/test_utils/src/gtc_helpers.rs

This is a trivial inlining, since `NeuronId::from_subaccount` is only used in one place. Putting it together with production code creates confusion about how NNS neuron ids are created in production.

chore(nns): Refactor NeuronId::from_subaccount to test_utils since it's only used in tests

---

rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs

Based on the ledger version (used for stable structures migration), determine if a downgrade of the ledger to the mainnet version is expected to succeed or not.

test(ICRC_Ledger): FI-1655: Add check to see if downgrade to mainnet is expected to work

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Evaluate cache performance with new bazel remote configuration changes. See https://github.com/dfinity-ops/k8s/pull/730.

chore(IDX): bazel-test-all ln1

---

ic-os/components/hostos-scripts/guestos/guestos.service
ic-os/components/hostos-scripts/guestos/start-guestos.sh

[ICSUP-3863](https://dfinity.atlassian.net/browse/ICSUP-3863)
This fixes the "blank console" issue where, after completing a successful SetupOS installation, HostOS starts the guestos service, the console is cleared as QEMU is launched, and then node providers just see a blank console like:
This PR fixes this error so that now, the start-guestos script pipes failure logs from the `virsh start guestos` command to the console:
[ICSUP-3863]: https://dfinity.atlassian.net/browse/ICSUP-3863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Also adds an onboarding message for the success case:

feat(node): Log guestos.service console logs to tty1

---

rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs

Fix the SNS golden state upgrade and downgrade test due to the recent SNS ledger version bump.

test(ICRC_Ledger): Fix test failure due to SNS ledger version bump

---

rs/registry/admin-derive/src/lib.rs
rs/registry/admin/src/helpers.rs
rs/registry/admin/src/main.rs

- Extend `print_proposal` to include URL information in its output.
- Adjust related code to align with signature change.

feat(ic-admin): Show the proposal URL for --dry-run

---

rs/http_endpoints/public/src/common.rs

Removing TODO comment for NET-1667 which has previously been resolved as "won't do".

chore: remove last todo comment in HTTP-handler

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
Cargo.toml
bazel/external_crates.bzl
rs/sns/cli/BUILD.bazel
rs/sns/cli/Cargo.toml
rs/sns/cli/src/lib.rs
rs/sns/cli/src/utils.rs

This is needed for the DFX SNS extension to better integrate with DFX. The dependency is maintained by DFINITY, it is just not part of the monrepo (and not currently depended on by the monorepo, prior to this PR). 
dfx-core uses a newer version of ic-agent, which means we need to update ic-agent in the monorepo, and that means we need to update ic-http-gateway (which I do here).
SNS CLI commands after this PR have a slightly different command after this. You should pass `--network` to specify the network and `--identity` to specify the identity if you don't want to use the default one in DFX. The default network is the local one if none is specified, for compatibility with DFX.

chore: Add dfx-core dependency and use it in the SNS CLI to allow it to use the user's DFX identities

---

rs/nns/governance/canister/governance.did

Recently, we deleted a bunch of request and response types from NNS governance.proto. Although the types themselves are not necessary, the comments contained valuable information, which could (and should) have been copied to governance.did. This PR corrects that oversight.
Types deleted in recent PRs:
* [ListNeurons]
* [ManageNeuronResponse]
* [NeuronInfo]
[ListNeurons]: https://github.com/dfinity/ic/pull/3546
[ManageNeuronResponse]: https://github.com/dfinity/ic/pull/3573
[NeuronInfo]: https://github.com/dfinity/ic/pull/3639

docs(nns): Resurrect request and response comments.

---

rs/embedders/src/wasm_utils/validation.rs
rs/embedders/src/wasmtime_embedder/system_api.rs
rs/embedders/src/wasmtime_embedder/system_api_complexity.rs
rs/embedders/tests/wasmtime_embedder.rs
rs/execution_environment/src/query_handler/query_cache/tests.rs
rs/execution_environment/tests/hypervisor.rs
rs/interfaces/src/execution_environment.rs
rs/system_api/src/lib.rs
rs/system_api/src/sandbox_safe_system_state.rs
rs/system_api/tests/system_api.rs
rs/test_utilities/execution_environment/src/lib.rs
rs/universal_canister/impl/src/api.rs

This PR implements a new system API that enables canisters to learn which subnet they run on. The new functionality is composed of two functions: `ic0.subnet_self_size()` and `ic0.subnet_self_copy()`, described in this [Spec PR](https://github.com/dfinity/portal/pull/3790).

feat(EXC-1847): Support for `ic0.subnet_self()`

---

rs/execution_environment/fuzz/src/lib.rs

In the sandbox monitor function, the parent thread calls `std::thread::sleep(std::time::Duration::from_secs(1))` to allow the sandbox to spawn all its threads before tracing begins.
However, this approach is unreliable—the sleep duration is arbitrary, and attachment can occur at any point in execution. This led to `getrandom` failures in CI.
This PR removes the sleep timer and instead continuously fetches `tid`s as threads spawn, attaching to them dynamically. The trade-off is that it requires knowing the number of sandbox threads in advance.

chore(fuzzing): extend syscall whitelist in sandbox fuzzers

---

rs/tests/message_routing/rejoin_test_lib/rejoin_test_lib.rs

This commit fixes a condition that can lead to flakiness in the state sync system tests.
The test relies on a metric of the number of successful state syncs. However, there appears to be a race condition of when the changed metric can be observed. At the same time, in this test it only takes a very short amount of time between the end of state sync and the subnet being no longer stalled. This race condition confused the test.
Now, the test waits for the metric to increase instead of asserting on the first try.

chore: Reduce flakiness of state sync system tests

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

This simplifies the output base on our x86 darwin builders. Since only one job runs at a time, the output base does not need to include a unique ID.
This also removes `/private/var` which anyway points to `/var`.

chore(IDX): simplify x64-darwin output base

---

bazel/conf/.bazelrc.internal

This removes the `--bes_upload_mode` argument from the `--config=bes` since it was simply re-specifying the default value.

chore(IDX): simplify bes upload

---

bin/.gitignore
bin/ict

This simplifies the `ict` wrapper script. The script now relies on bazel to figure out if the `ict` tool needs to be rebuilt.
From basic testing, this seems fast enough for a good CLI experience and simplifies things a fair bit (avoid custom hashing & checksum file):
```sh
$ time ./bin/ict -v
ict version 0.1.2
real	0m0.345s
user	0m0.016s
sys	0m0.042s
```

chore(IDX): track ict changes with bazel

---

rs/canister_sandbox/src/sandbox_manager.rs
rs/embedders/src/wasm_executor.rs
rs/system_api/src/lib.rs
rs/system_api/tests/sandbox_safe_system_state.rs
rs/system_api/tests/system_api.rs

Currently, there are two similar functions in the `SystemApiImpl` to extract system state modifications. One of them `take_system_state_modifications` is used in the sandbox when preparing the state changes to be transmitted back to the replica. Then, the replica after deserializing the result that it receives from the sandbox calls `into_system_state_changes` on the reconstructed `system_api` to extract the changes again.
In a recent [PR](https://github.com/dfinity/ic/pull/363), `into_system_state_modifications` was changed (to make it more clear which changes are relevant per message type) but `take_system_state_modifications` wasn't. This works correctly because `into_system_state_modifications` is the last one that's called before applying the state changes back to the canister state. …

refactor: Consolidate how system state modifications are extracted from the System API

---

rs/nervous_system/agent/src/lib.rs
rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs

This PR introduces an NNS canister suite builder for PocketIc. 
This is important since we will soon need multiple different NNS configurations, and adding more arguments to the existing `install_nns_canisters` function doesn't work well with many parameters. In contrast, the builder can be extended with any number of parameters, without negatively affecting code readability.

test(nns/sns): Introduce NNS suite builder for PocketIc

---

rs/nervous_system/clients/src/canister_status.rs
rs/nns/handlers/root/impl/canister/root.did
rs/nns/handlers/root/unreleased_changelog.md
rs/sns/root/canister/root.did
rs/sns/root/unreleased_changelog.md

Currently, the management canister can return the LogVisibility::AllowedViewers variant for the canister status of a canister under NNS/SNS root control. Although it's currently impossible for NNS/SNS root to change the log visibility of any canister under their control into this variant, it's still possible for a canister with this variant to be brought under its control. When the `canister_status` is called in this case, the `canister_status` call made by root to the management canister will fail at decoding the response. This PR aims to improve that.
- Add the `allowed_viewers` variant into `LogVisibility` where it's part of the `canister_status` response (not when it's part of `update_settings`). Since the response from SNS/NNS root also uses this enum, this change also affects …

feat(nns/sns): Add allowed_viewers variant case into canister_status responses

---

rs/crypto/temp_crypto/src/lib.rs
rs/interfaces/src/crypto.rs

This will allow the implementation to be used via the `ConsensusCrypto` trait.

feat: Add `VetKdProtocol` to `Crypto` trait

---

rs/crypto/internal/crypto_service_provider/src/key_id/mod.rs
rs/crypto/internal/crypto_service_provider/src/key_id/tests.rs
rs/crypto/internal/crypto_service_provider/src/keygen/tests.rs
rs/crypto/internal/crypto_service_provider/src/signer/tests.rs
rs/crypto/internal/crypto_service_provider/src/tests.rs
rs/crypto/internal/crypto_service_provider/src/vault/api.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/basic_sig/mod.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/basic_sig/tests.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/multi_sig/mod.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/multi_sig/tests.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/public_and_secret_key_store/mod.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/public_and_secret_key_store/tests.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/secret_key_store/tests.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tls/mod.rs
rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tls/tests.rs
rs/crypto/internal/crypto_service_provider/src/vault/mod.rs
rs/crypto/internal/crypto_service_provider/src/vault/test_utils/ni_dkg.rs
rs/crypto/internal/crypto_service_provider/tests/remote_vault_basig_signature_delegation.rs
rs/crypto/internal/crypto_service_provider/tests/remote_vault_rpc_connection.rs
rs/crypto/src/sign/basic_sig.rs
rs/crypto/src/sign/basic_sig/tests.rs
rs/crypto/src/sign/multi_sig.rs
rs/crypto/src/tls/rustls/client_handshake.rs
rs/crypto/src/tls/rustls/server_handshake.rs

Makes some conversions to `KeyId` infallible. In particular:
* `impl<B: AsRef<[u8]>> TryFrom<(AlgorithmId, &B)> for KeyId`
* `impl TryFrom<&CspPublicKey> for KeyId`
* `impl TryFrom<&TlsPublicKeyCert> for KeyId`

feat(crypto): CRP-2687 make some conversions to KeyId infallible

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
Cargo.lock
Cargo.toml
bazel/cargo.config

Remove the (very old) reference to a custom version of jsonrpc in Cargo.toml and just use the latest version instead.

chore: remove reference to a custom jsonrpc version in Cargo.toml

---

Cargo.lock
rs/registry/canister/BUILD.bazel
rs/registry/canister/Cargo.toml
rs/registry/canister/canister/canister.rs
rs/registry/canister/src/lib.rs
rs/registry/canister/src/registry_lifecycle.rs
rs/registry/canister/src/storage.rs
rs/registry/canister/unreleased_changelog.md

Use MemoryManager instead of dfn_core's memory tools for saving and loading the protobuf on upgrades.
To allow moving registry records into stable memory, so that registry can scale, we first want to allow for multiple memory regions to be available so that different classes of objects can be stored.
Note, this was tested using the golden_state test and adding an additional check that registry state is still intact.

refactor(registry): Migrate Registry to use MemoryManager instead of raw stable memory

---

Cargo.lock
rs/nervous_system/tools/release-runscript/BUILD.bazel
rs/nervous_system/tools/release-runscript/Cargo.toml
rs/nervous_system/tools/release-runscript/src/main.rs

This will make it simpler to add automation for various steps in the future. It will also enable the person doing the release to start at any step (instead of needing to start at the beginning).
As a reminder, the runscript can be run with:
```
bazel run //rs/nervous_system/tools/release-runscript --config=lint
```
In this chain of PRs, I automate the first few steps of the release process in this script.
[Next PR →](https://github.com/dfinity/ic/pull/3713)

refactor(nns-tools): Turn release-runscript to clap-powered CLI

---

rs/nervous_system/clients/src/canister_status.rs
rs/nervous_system/clients/src/management_canister_client/tests.rs
rs/nns/handlers/root/impl/canister/root.did
rs/nns/handlers/root/interface/src/client.rs
rs/nns/handlers/root/unreleased_changelog.md
rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/unreleased_changelog.md
rs/sns/root/canister/root.did
rs/sns/root/unreleased_changelog.md
rs/sns/sns.bzl
rs/sns/swap/canister/swap.did
rs/sns/swap/canister/tests.rs
rs/sns/swap/unreleased_changelog.md

The `query_stats` field from the `canister_status` management canister API has been available for a while. Some NNS/SNS canisters expose methods to proxy the management canister method, and they haven't been updated to expose `query_stats` yet.
- Add `query_stats: QueryStatsFromManagementCanister` for the management canister call. No `opt` is needed since the management canister doesn't have `opt`.
- Add `query_stats: opt QueryStats` to the `CanisterStatusResult`/`CanisterStatusResultV2` structs, where each field in `QueryStats` is also `opt`. This is consistent with other NNS/SNS APIs where we use `opt` to allow removing such fields if needed.
Since every addition in `*.did` files changed by this PR is `opt`, decoding will always be successful no matter whether the sender/receiver of the …

feat(nns/sns): Add query stats to canister status

---

rs/nns/governance/src/governance.rs
rs/nns/governance/unreleased_changelog.md

The number of neurons keeps growing. Some analysis showed that we would be able to increase the limit to 500K (note that the maximum number changes over time because it takes into account the number of neurons that are already created). However, given that we are actively working on moving all neurons to stable storage, we would like to increase the limit in a more conservative way. The 400K limit should give us ~10 weeks.

feat(nns): Bump neurons limit

---

rs/nns/governance/unreleased_changelog.md
rs/registry/canister/src/mutations/node_management/do_add_node.rs
rs/registry/canister/src/mutations/node_management/do_remove_node_directly.rs
rs/registry/canister/unreleased_changelog.md

When a node is redeployed, but hasn't been removed from the registry before that, it is automatically replaced: the old node record is removed and the new one created.
Initially, this was only possible for unassigned nodes. Then, functionality was added such that this also worked for nodes assigned to a subnet.
This PR enables the same behavior for API boundary nodes. When a node that is currently active as API boundary node is redeployed, the old node record and the old API boundary node record are removed, and a new node record and a new API boundary node record are created.
We can't just use any node as API boundary node. The node needs to be configured with a domain name. This case will fail as we have an invariant in `invariants/api_boundary_node.rs` that ensures that each API …

chore: allow automatically replacing a node even if it is active as an API BN

---

testnet/tools/nns-tools/lib/proposals.sh

This forces the release tsar to review generated proposals before submitting them, because [validate_no_todos] stops proposals from being submitted if they contain "TODO".
[validate_no_todos]: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/dfinity/ic%24+f:nns-tools+%22validate_no_todos+%22&patternType=regexp&case=yes&sm=0
We could delete this later once we get used to and work work out all issues in this new process.

feat(governance-tools): Added TODOs to generated "Features & Fixtures" section.

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs

After changing the default value in a previous [PR](https://github.com/dfinity/ic/pull/3612), the comment on the field should also be updated.

chore(nns): Modify the comment on `include_empty_neurons_readable_by_caller`

---

rs/execution_environment/src/execution_environment/tests/canister_task.rs

This PR adds code coverage and tests the behavior of the low wasm memory hook in different situations depending on the used wasm memory before and after canister upgrade.

chore: [EXC-1880] Test hook behavior across upgrade

---

Cargo.lock
rs/bitcoin/adapter/BUILD.bazel
rs/bitcoin/adapter/Cargo.toml
rs/bitcoin/adapter/src/get_successors_handler.rs

Before, the total response of the `get_successors` rpc in the bitcoin adapter was 2MB, regardless of the bitcoin network. In the worst case, this lead to the response containing either :
- ~100 medium 20KB blocks, each with many small transactions, or
- 2 large 1MB blocks, each with really many small transactions
Both of those cases made serialization take really long, and the `get_successors` request would exceed the [50ms timeout in consensus](https://github.com/dfinity/ic/blob/b7a0b3d3b896cdaabc06c0ee6cd13cd54c939e67/rs/config/src/bitcoin_payload_builder_config.rs#L12).
After, the maximum response size is reduced to just 1MB for the testnet4 network. This speeds up the serialization, while not sacrificing the canister performance too much (on average, there will be 2x more requests to …

fix: reduce the bitcoin adapter maximum response size to 1MB for testnet4

---

rs/replicated_state/src/canister_state/queues.rs
rs/replicated_state/src/canister_state/queues/tests.rs
rs/replicated_state/src/canister_state/system_state.rs
rs/system_api/src/sandbox_safe_system_state.rs

This is a minor optimization that has `SystemStateModifications::apply_changes()` build a `BTreeSet<SubnetId>` instead of a `Vec<SubnetId>`, since the resulting collection is only ever used for looking up specific `SubnetIds`.

perf(MR): Look up `SubnetIds` from a `BTreeSet` instead of from a `Vec`

---

rs/nns/governance/src/lib.rs

This just adds a small comment.

docs(nns): Added a TODO with Jira ticket ID about the demise of refresh neuron flags.

---

Cargo.Bazel.Fuzzing.json.lock
Cargo.Bazel.Fuzzing.toml.lock
Cargo.Bazel.json.lock
Cargo.Bazel.toml.lock
bazel/external_crates.bzl

Bump the canbench to [0.1.9](https://github.com/dfinity/canbench/releases/tag/v0.1.9) so that custom noise threshold can be set.

chore: Bump canbench to 0.1.9

---

rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/execution_environment.rs

This PR extracts some memory related checks in a common function that can be used across both `take_canister_snapshot` and `load_canister_snapshot` for consistency.

refactor: Add memory usage checks when loading a snapshot for consistency

---

rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/api/src/pb.rs
rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/canister/canister.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/governance/tests/list_neurons.rs
rs/nns/governance/src/pb/mod.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/unreleased_changelog.md
rs/nns/integration_tests/src/governance_neurons.rs
rs/nns/integration_tests/src/neuron_voting.rs
rs/nns/test_utils/src/state_test_helpers.rs
rs/rosetta-api/icp/src/request_handler/construction_payloads.rs
rs/rosetta-api/icp/tests/system_tests/common/utils.rs
rs/tests/driver/src/canister_api.rs

This allows users who know the subaccounts of their neurons (i.e. they know the nonce and the principal used when the neurons are created) to specify which neurons they would like to list without needing to know the neuron ids (which are generated at random).
This adds a new API field to `list_neurons` called `neuron_subaccounts`, which works in the same way that `neuron_ids` works.  By specifying which subaccounts the user would like to list, they are able to retrieve neurons in the same way that they also can provide neuron ids.  Both of these are compatible, and in the case of overlaps, no duplicates are returned.

feat(nns): list_neurons supports querying by subaccount

---

rs/nervous_system/agent/src/management_canister/mod.rs
rs/nervous_system/agent/src/management_canister/requests.rs
rs/nervous_system/agent/src/pocketic_impl.rs
rs/nervous_system/agent/src/sns/governance.rs
rs/nervous_system/integration_tests/tests/upgrade_sns_controlled_canister_with_large_wasm.rs
rs/sns/cli/src/lib.rs
rs/sns/cli/src/main.rs
rs/sns/cli/src/upgrade_sns_controlled_canister.rs
rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs

This PR prepares for adding a new subcommand to sns-cli, so users who proposed to upgrade an SNS-controlled canister can easily request the unused cycles to be refunded to the original Cycles Ledger account that they used for uploading and storing the chunked Wasm in a store canister.
The corresponding integration test was updated to exercise the happy scenario.
For now, the subcommand does not refund cycles, but simply deletes the store canister. Refunding will be implemented in a follow-up PR.

feat(sns-cli): Cleanup store canister after upgrading an SNS-controlled canister

---

rs/nns/governance/src/neuron_store/metrics.rs

https://github.com/dfinity/ic/pull/3090
A couple of issues:
1. Moved comment.
2. Use < instead of checked_sub to detect when right operand is greater than left.

refactor(nns): Follow up on PR 3090

---

rs/sns/governance/src/types.rs
rs/sns/governance/src/types/tests.rs
rs/sns/governance/unreleased_changelog.md

This PR fixes a bug due to which the SNS ledger logo was being unset as a result of changes in unrelated SNS ledger metadata fields.

fix(sns): Correctly translate `ManageLedgerParameters` into `LedgerUpgradeArgs`

---

bazel/canbench.bzl
bazel/canbench.sh
rs/nns/governance/BUILD.bazel

NNS Governance benchmarks sometimes have variance slightly over 2%. Overall, the loss of productivity (in updating the results file and resolve conflicts) doesn't seem to be worth the benefit of keeping a tight threshold.

perf(nns): Set NNS Governance governance noise threshold to 5%

---

rs/nns/sns-wasm/unreleased_changelog.md
rs/sns/init/src/lib.rs
rs/sns/integration_tests/src/governance.rs

This PR ensures that logos are not serialized as part of the SNS initialization parameters, so that those parameters can better fit into the expected limits.

feat(sns): Do not store logos in SNS initialization parameters to save space

---

rs/nervous_system/tools/release-runscript/src/main.rs

It now opens the calendar page for you and copies the instructions for the trusted neurons to your clipboard.
[Next PR →](https://github.com/dfinity/ic/pull/3792)

feat(nervous-system): runscript partially automates scheduling the votes

---

rs/nervous_system/tools/release-runscript/src/main.rs

This was a common pattern so it's nice to have a function for it
[← Previous PR](https://github.com/dfinity/ic/pull/3793) | [Next PR →](https://github.com/dfinity/ic/pull/3796)

refactor(nervous-system): add "press enter to continue" helper

---

rs/nervous_system/tools/release-runscript/BUILD.bazel
rs/nervous_system/tools/release-runscript/src/commit_switcher.rs
rs/nervous_system/tools/release-runscript/src/main.rs
rs/nervous_system/tools/release-runscript/src/utils.rs

This improves code organization because now everything in main.rs is the essential logic (rather than helpers that you usually don't need to care about)
[← Previous PR](https://github.com/dfinity/ic/pull/3794) | [Next PR →](https://github.com/dfinity/ic/pull/3806)

refactor(nervous-system-runscript): move utilities to utils.rs

---

rs/bitcoin/adapter/src/connectionmanager.rs

Before this, only `getData` and `getHeaders` messages were recorded in the metrics.
With this change, all messages should be recorded.

fix: move metrics to all messages

---

rs/consensus/tests/framework/mod.rs
rs/messaging/src/message_routing/tests.rs
rs/registry/admin/src/types.rs
rs/registry/canister/src/mutations/do_update_subnet.rs
rs/registry/subnet_features/src/lib.rs
rs/tests/ckbtc/src/lib.rs

This PR adjusts ckBTC tests (and a test in message routing) to use the new chain key API, since the old one is now obsolete.
Additionally, the legacy code is further cleaned in in the Registry component (canister and ic-admin).

test(btc): Port ckBTC tests from legacy ECDSA to chain key Registry API

---

bazel/conf/.bazelrc.build
ci/container/build-ic.sh
ic-os/guestos/envs/prod/BUILD.bazel
ic-os/hostos/envs/prod/BUILD.bazel
ic-os/setupos/envs/prod/BUILD.bazel
publish/binaries/BUILD.bazel
publish/canisters/BUILD.bazel
publish/defs.bzl

This tries to improve the `build-ic.sh` script in a couple of ways:
* Push the checksum logic to bazel so that it can be used without `build-ic.sh` (e.g. for repro checks)
* Re-use bazel arguments in both build & `cquery` to ensure the same targets are actually used
* Discard environment validation (since the script is forcing use inside the container) and `exec` into container with script itself (ensures the whole script runs in the container and not just the build)
* Drop `*` from shasum output
* Use `tput` for terminal colors
* Use the built-in bazel `sha256` tool

chore(IDX): push checksum logic to Bazel

---

ic-os/defs.bzl

The `_pre_check` pre checks were used to ensure all inputs did exist before the action ran. Bazel does however ensure that the files exist, and it's not even guaranteed that Bazel will build the pre-check before the action that actually requires said inputs, making the check speedups unreliable.

chore(IDX): remove ic-os pre-check

---

rs/consensus/src/idkg/complaints.rs
rs/consensus/src/idkg/payload_builder.rs
rs/consensus/src/idkg/payload_builder/key_transcript.rs
rs/consensus/src/idkg/payload_builder/pre_signatures.rs
rs/consensus/src/idkg/payload_builder/resharing.rs
rs/consensus/src/idkg/payload_builder/signatures.rs
rs/consensus/src/idkg/payload_verifier.rs
rs/consensus/src/idkg/pre_signer.rs
rs/consensus/src/idkg/signer.rs
rs/consensus/src/idkg/test_utils.rs
rs/consensus/src/idkg/utils.rs

After the completed implementation of the VetKd protocol in the crypto component, this PR now calls the corresponding endpoints from within the consensus VetKd client.
This PR additionally extends unit tests to also be called for VetKd key IDs where it makes sense. Some unit tests related to IDKG internals and pre-signatures (as required by tSchnorr and tEcdsa) are not executed for VetKd.
Note that initially we intended to combine VetKd key shares using the `ThresholdSignatureBuilder` used in IDKG. Instead, this is now done by the VetKd batch payload builder.

feat: CON-1421 Call crypto in the VetKd client

---

ic-os/components/hostos-scripts/monitoring/custom-metrics.service
ic-os/components/hostos-scripts/monitoring/custom-metrics.sh
ic-os/components/hostos.bzl

NODE-1567
CPU microcode version now exported as a metric:

chore(node): export cpu microcode metrics

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml
ci/scripts/build-determinism.sh

This tries to simplify the `build-determinism.sh` to make it more robust and more readable. In particular:
* Avoid returning successfully (without checking checksums) if `bazel-targets` does not exist
* Remove outdated test ignores
* Unpack `build-ic.tar` in the GHA
* Simplify the GHA step
* Homogenize bash opts and avoid `set -x` for better readability

chore(IDX): simplify build-determinism.sh

---

rs/nervous_system/tools/release-runscript/BUILD.bazel
rs/nervous_system/tools/release-runscript/src/commit_switcher.rs
rs/nervous_system/tools/release-runscript/src/main.rs
rs/nervous_system/tools/release-runscript/src/utils.rs
testnet/tools/nns-tools/add-release-to-changelog.sh

This is the final step in the release process. Now everything is automated!
Here is an example of a PR it creates: #3807
To create the PR, we use `gh`, which we assert you have on your computer before the first step. (This ensures that you don't get to the last step and then hit an error which would be slightly annoying to recover from. Instead, you get the error right away, and it should be smooth sailing after that.)
The intention of this change is that you create the PR to update the changelog right when you create the proposals.
> Yes, we can optimistically assume that the proposal will pass. If it doesn't, we can revert the CHANGELOG.md. Branch predict FTW.
- @daniel-wong-dfinity-org 
A consequence of is that the changelog now shows the date of proposal submission, rather than …

feat(nervous-system): release runscript automatically creates changelog PRs

---

rs/nns/governance/src/governance.rs

Cleaning up the one-off migration code (the migration code is run after [this proposal](https://dashboard.internetcomputer.org/proposal/135063)). For new proposals, the hashes are computed when they are created.

chore(nns): Clean up the migration code to backfill InstallCode hashes

---

rs/bitcoin/ckbtc/minter/src/dashboard.rs
rs/bitcoin/ckbtc/minter/src/guard.rs
rs/bitcoin/ckbtc/minter/src/metrics.rs
rs/bitcoin/ckbtc/minter/src/state.rs
rs/bitcoin/ckbtc/minter/src/updates/retrieve_btc.rs
rs/bitcoin/ckbtc/minter/src/updates/update_balance.rs

XC-299: Change the reentrancy guards used in update_balance and retrieve_btc from user principals to accounts.
This allows more concurrency in update_balance or retrieve_btc calls.

feat(ckbtc): Place update_balance and retrieve_btc guards on user accounts

---

.github/workflows/team-channels.json

Change the Slack notification channel for the cross-chain team to a dedicated channel `eng-cross-chain-prs`

ci: change cross-chain team notification channel

---

rs/nns/governance/unreleased_changelog.md

2 changelog entries are already added to CHANGELOG.md. Removing them.

chore(nns): Remove changelog entries which are already copied to CHANGELOG.md

---

rs/nervous_system/tools/release-runscript/src/main.rs
rs/nervous_system/tools/release-runscript/src/utils.rs

Changes:
* CMC default upgrades args candid textual format shouldn't have single quotes around them
* Check both stdout and stderr for GH login message

fix(nns/sns): Minor fixes for release_runscript

---

rs/sns/governance/CHANGELOG.md

The endpoint mentioned in SNS Governance changelog was wrong, this PR corrects it. The [inflight publish proposal](https://dashboard.internetcomputer.org/proposal/135208) already has the correct text

chore(sns): Correct the changelog for SNS Governance

---

rs/nervous_system/tools/release-runscript/src/main.rs
rs/nervous_system/tools/release-runscript/src/utils.rs

When helping jason do the release, we discovered a couple small issues.
1. The script requires `code` and some bash scripts require `coreutils`, but it just fails in the middle instead of checking for you
2. It's too easy to accidentally forget a TODO in a proposal text. This leads to a panic later. It's better to just make you fix all of them before continuing.

fix(nervous-system): resolve issues in the release runscript discovered today

---

rs/nns/handlers/root/CHANGELOG.md
rs/nns/handlers/root/unreleased_changelog.md

The script that does this automatically seems to be broken for NNS root

chore(nns): update root changelog

---

testnet/tools/nns-tools/add-release-to-changelog.sh

It was looking for the timestamp under "proposal_creation_timestamp_seconds", but this only exists for SNS. On NNS the analogous field is "proposal_timestamp_seconds".

fix(nervous-system-tools): changelog script looks at correct field for NNS

---

testnet/tools/nns-tools/lib/functions.sh

The `CHANGELOG.md` and `unreleased_changelog.md` are located in `rs/nns/handlers/root`, and the `code_location_...` is used to figure out where the change logs are. Although one obvious solution is to move the change logs to `//rs/nns/handlers/root/impl/`, there doesn't seem to be a good reason that changes in `rs/nns/handlers/root/interface` should NOT be displayed in upgrade proposals.

chore(nns): Change NNS Root code location to one level up

---

rs/tests/dre/utils/steps/xnet.rs

Currently the versions running on mainnet don't support best-effort response message. Having the XNet step in the qualification test attempt sending them prevents the canisters from sending any message and will consequently fail the test.

fix: No best-effort messages in RC qualification test

---

rs/execution_environment/fuzz/src/lib.rs

This PR is to keep track of any missed syscalls in the existing whitelist and add them if necessary. The hourly fuzzing CI job is used as a testbed.
1. `set_robust_list` - [failures](https://github.com/dfinity/ic/actions/runs/13068049429/job/36463716667)
Update: Observed over a week and didn't see other failures.

chore(fuzzing): Add missing syscalls to the sandbox monitor whitelist

---

rs/tests/ict/cmd/helpers.go
rs/tests/ict/cmd/testCmd.go
rs/tests/ict/cmd/testnetCreateCmd.go

Wit this PR we add the possibility to override the branch from which the dashboards will be synced.
Usage:
```bash
ict testnet create small --lifetime-mins 60 --k8s-branch release-controller-new
ict test qualification --k8s-branch release-controller-new
```

feat: branch for syncing grafana dashboards

---

rs/execution_environment/src/canister_settings.rs

We have nowadays saturating arithmetic implemented for `AmountOf`s, so use this to simplify the code instead of having an `if-else` statement.

refactor: Use saturating subtraction for simplicity

---

rs/execution_environment/src/metrics.rs
rs/execution_environment/src/scheduler.rs
rs/execution_environment/src/scheduler/scheduler_metrics.rs
rs/messaging/tests/call_tree_tests.rs
rs/system_api/src/sandbox_safe_system_state.rs

Add an `execution_queues_best_effort_message_bytes` metric to track the size of the best-effort message memory pool. And break down the call tree metrics along a message class dimension.

feat(MR): Basic metrics for best-effort calls

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/src/lib.rs
rs/nns/governance/src/network_economics.rs
rs/nns/governance/src/network_economics_tests.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/unreleased_changelog.md

This way, people can specify just one the inner/nested subfield at a time.
Some code was moved from src/governance.rs (this file is pretty dang large) to a new file: network_economics.rs.
Close [NNS1-3499].
[NNS1-3499]: https://dfinity.atlassian.net/browse/NNS1-3499

feat(nns): Make NetworkEconomics inherit recursively.

---

rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
rs/execution_environment/src/execution_environment/tests/canister_task.rs
rs/replicated_state/src/canister_state/execution_state.rs

This PR updates the `sandboxed_execution_executed_message_slices_total` metric to track whether messages were executed on a Wasm32 or Wasm64 canister and validates the change with a test.

chore(EXC-1855): Adjust metric to track whether message is executed on Wasm32 or Wasm64 canisters

---

.github/workflows-source/ci-main.yml
.github/workflows-source/release-testing.yml
.github/workflows-source/schedule-daily.yml
.github/workflows-source/schedule-hourly.yml
.github/workflows/ci-main.yml
.github/workflows/release-testing.yml
.github/workflows/schedule-daily.yml
.github/workflows/schedule-hourly.yml
.github/workflows/schedule-rust-bench.yml
ci/bazel-scripts/main.sh

This specifies a default `--repository_cache` so that it doesn't have to be set for each job

chore(IDX): extract repository_cache

---

rs/tests/networking/BUILD.bazel

This colocates the test driver with the testnet it deploys for the following flaky system-tests:
* `//rs/tests/networking:network_reliability_test`: 10% flaky
* `//rs/tests/networking:query_workload_long_test` 11% flaky
* `//rs/tests/networking:update_workload_large_payload` 4% flaky
These test generate a workload from the test driver to their testnets so the idea is that if we colocate the driver with the testnet the network in between would be more reliable.
Hourly run: https://github.com/dfinity/ic/actions/runs/13263034379

test(IDX): colocate some flaky networking system-tests

---

rs/state_manager/tests/common/mod.rs

Tests regularly fail to wait for the checkpoint in the given time on CI. On local machine 5s fails 90% of the time with parallel runs, so it seems that the timeout is a bit short.

chore: Increase the wait for checkpoint timeout for the tests

---

.github/actions/bazel-test-all/action.yaml

Revering https://github.com/dfinity/ic/pull/3264 as [this issue](https://github.com/dfinity/ic/actions/runs/13267272609/job/37037785597) is seen in machines that I redeployed.

fix(IDX): chown /cache

---

rs/registry/canister/CHANGELOG.md
rs/registry/canister/src/common/test_helpers.rs
rs/registry/canister/src/mutations/node_management/do_remove_node_directly.rs

This update refines the logic within the `do_remove_node_directly` function to update the correct node operator ID record.
In the past the `caller_id` and the `node_operator_id` for the node were always the same. However, since #3285 the `caller_id` and the `node_operator_id` for the removed node may differ, and this introduces a bug in this edge case.
The wrong node operator record was retrieved (of the caller), but then written into the correct record id (of the removed node's node operator), resulting in lost data when using this new capability.
The bug resulted in a node reward discrepancy for a few operator records, identified in regular administrative checks and described [in the forum](https://forum.dfinity.org/t/issue-with-node-provider-rewards/41109/3) and mitigated with a few …

fix(registry): Update the correct node operator ID in node removal

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance_proto_builder.rs
rs/nns/governance/src/network_economics.rs
rs/nns/governance/src/network_economics_tests.rs
rs/nns/governance/tests/governance.rs
rs/nns/governance/unreleased_changelog.md

Closes [NNS1-3498].
[NNS1-3498]: https://dfinity.atlassian.net/browse/NNS1-3498

feat(nns): Validate manage network economics.

---

ci/bazel-scripts/main.sh

This removes the GHA step output `upload_artifacts` that doesn't seem to be used.

fix(IDX): remove unused step output

---

mainnet-canister-revisions.json
rs/registry/canister/src/mutations/node_management/do_add_node.rs
rs/registry/canister/src/mutations/node_management/do_remove_node_directly.rs
rs/registry/canister/unreleased_changelog.md

Direct node replacements of nodes that are active in a subnet may result in unexpected behavior and potential problems in the current Consensus code.
So to be on the safe side we need to disable the functionality on the Registry side until the rest of the core protocol can handle it safely.

fix(registry): disable replacement of nodes that are active in subnets

---

bazel/workspace_status.sh

This removes a couple of (volatile) variables set by the workspace status file. Those were not being used.

chore(IDX): simplify workspace_status

---

bazel/ic_version_or_git_sha.sh
bazel/workspace_status.sh
rs/tests/driver/src/driver/farm.rs
rs/tests/system_tests.bzl

This removes (more) unused status env vars, and removes the workaround used to clean up the volatile status by instead using stable status for farm metadata.
This means farm tests will be retriggered if the jobs are run under a new CI job name, which is actually already the case since ic-os images are not cached (we rely on `diff.sh` for skipping tests).

chore(IDX): clean up status

---

rs/nns/governance/protobuf_generator/src/lib.rs
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/tests/mod.rs

Obsolete NNS Functions are not handled very nicely - it just said "... is obsolete". When making `NnsCanisterUpgrade` obsolete previously, there were some confusions since the error message wasn't ideal. In addition, `is_obsolete` happened after `can_have_large_payload`, so obsolete functions might hit the `can_have_large_payload` first.
* Change `is_obsolete` to `check_obsolete` which returns an error message
* Move `can_have_large_payload` after `check_obsolete`
* `UpdateUnassignedNodesConfig` is obsolete but wasn't handled in `canister_and_function`. This PR fixes that.
* It doesn't really matter, since `is_obsolete` already returns true, so it's impossible for such proposals to be created, so `canister_and_function` won't be called with this nns function at the execution time.

feat(nns): Improve ExecuteNnsFunction proposal validation

---

rs/registry/admin/src/main.rs

`NnsCanisterUpgrade`/`NnsRootUpgrade` are obsolete. They were only used in `ic-admin` is the flag `use_legacy_execute_nns_function` is true (in case the replacement proposal type has some problems). This PR removes the legacy behavior.

chore(ic-admin): Stop supporting NnsCanisterUpgrade/NnsRootUpgrade in ic-admin

---

Cargo.lock
rs/sns/governance/BUILD.bazel
rs/sns/governance/Cargo.toml
rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
rs/sns/governance/api/src/topics.rs
rs/sns/governance/canister/canister.rs
rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance/assorted_governance_tests.rs
rs/sns/governance/src/lib.rs
rs/sns/governance/src/pb/conversions.rs
rs/sns/governance/src/proposal.rs
rs/sns/governance/src/topics.rs
rs/sns/governance/src/types.rs
rs/sns/governance/src/types/tests.rs
rs/sns/governance/unreleased_changelog.md
rs/sns/integration_tests/src/nervous_system_functions.rs
rs/sns/integration_tests/test_canisters/sns_governance_mem_test_canister.rs

This PR introduces the concept of topics to the SNS through the `list_topics` api. The intention is that UIs to the NNS can query `list_topics` and use the result to render a list of all available topics (as well as the functions within them).
When registering a GenericNervousSystemFunction, a topic can also be specified, and it will appear under that topic under the output of `list_topics`.
We want to implement following on topics at some point in the future, but that will be done in a separate PR.

feat: list topics

---

rs/execution_environment/src/execution_environment.rs
rs/execution_environment/src/query_handler/query_context.rs
rs/execution_environment/src/scheduler.rs

The function `RoundLimits::reached` checks specifically whether the instruction limit (only one part of `RoundLimits`) has been reached. Rename the function to `instructions_reached` and update the doc comment to reflect that better and avoid any misunderstandings that the function might be checking against all limits.

refactor: Rename reached to instructions_reached

---

rs/execution_environment/src/query_handler/query_context.rs

`Query` already exposes a function `source()` to retrieve the underlying source of the query, so rely on that to construct a `CallOrigin` in the query handler instead of trying to handle the different cases.

refactor: Simplify logic to get a CallOrigin from a Query

---

ci/bazel-scripts/main.sh

This uses actual regexes to avoid globbing-related issues when matching on branch names.

chore(IDX): use proper regex for branch matching

---

rs/execution_environment/tests/execution_test.rs

Failed memory growth operations finish in just a few milliseconds, so 10k seems like a safe assertion.

test: EXC-1878: Add failed stable memory grow tests

---

rs/execution_environment/src/execution/call_or_task.rs
rs/execution_environment/src/execution/common.rs
rs/execution_environment/src/execution/install_code.rs
rs/execution_environment/src/execution/response.rs
rs/execution_environment/src/execution_environment.rs

Small refactoring that moves the function closer to where it's used. The top level `execution_environment.rs` is quite big already, anything that does not need to be there, better not be there.

refactor: Move log_dirty_pages to the module where it's used

---

rs/sns/governance/src/governance/assorted_governance_tests.rs
rs/sns/governance/src/proposal.rs
rs/sns/governance/src/topics.rs
rs/sns/governance/unreleased_changelog.md

This ensures that all new custom functions will specify a topic.

feat(sns): Prevent submitting add_generic_nervous_system_function proposals without a topic

---

rs/bitcoin/checker/src/main.rs
rs/bitcoin/ckbtc/minter/src/main.rs
rs/ethereum/cketh/minter/src/main.rs
rs/ethereum/ledger-suite-orchestrator/src/main.rs
rs/ledger_suite/icp/src/lib.rs

We used to use `ic_cdk::api::data_certificate().is_none()` to detect whether a canister is running in replicated or query mode. Now the cdk has a function `in_replicated_execution`, so this PR switches all instances to this newer and more readable approach.

chore: use cdk::api::in_replicated_execution

---

rs/nns/governance/src/governance/tla/store.rs
rs/tla_instrumentation/tla_instrumentation/tests/multiple_calls.rs
rs/tla_instrumentation/tla_instrumentation/tests/structs.rs
rs/tla_instrumentation/tla_instrumentation_proc_macros/src/lib.rs

When the test feature was on, we have so far always recorded TLA traces in governance. But this can be problematic when a canister is built with this feature turned on, because the traces would be collected in the background. This is a problem for canisters with large states (since the traces keep multiple copies of the state in the Wasm heap), but even with moderate state sizes it would also effectively leak the canister memory over time, since the traces were never emptied.
Change the instrumentation infrastructure to not record any traces when both:
1. a `TLA_TRACES_LKEY` task-local (`LocalKey`) isn't set (this is meant to be used from pure Rust tests and is set by the `with_tla_trace_check` attribute macro)
2. `TLA_TRACES_MUTEX` isn't set (this is currently just disabled in …

feat(IC-1579): allow disabling the TLA instrumentation even with test feature

---

rs/consensus/dkg/src/payload_builder.rs
rs/consensus/src/cup_utils.rs

This function is called by the orchestrator to make the latest registry CUP every ~10 seconds. Instead of panicking when the NiDKG summary cannot be created, we should return an error and handle it in the caller.

fix: CON-1466 Don't panic in `get_dkg_summary_from_cup_contents`

---

ci/container/container-run.sh

Do not bind-mount `$HOME` as this is generally really not safe and clean. User has freedom to bind-mount specific home directories or entire home via `$HOME/.container-run.conf`. See below.
```bash
❯ cat ~/.container-run.conf
PODMAN_RUN_USR_ARGS=(
--mount type=bind,source=${HOME}/dev,target=/home/ubuntu/dev
--mount type=bind,source=${HOME}/.kube,target=/home/ubuntu/.kube
)
```
Having `$HOME` bind-mounted presented itself to be an issue with release verification of [this release](https://forum.dfinity.org/t/proposal-to-elect-new-release-rc-2025-02-13-03-06). Users tried to verified the build on AWS EC2 instance. It it yet not clear whether recent related code changes [here](https://github.com/dfinity/ic/pull/3752) are related.

chore(IDX): do not bind-mount home

---

.github/actions/bazel-test-all/action.yaml
ci/bazel-scripts/main.sh
ci/src/git_changes/git_changes.py

This stops uploading artifacts to S3 when a PR is targetting an `rc-*` branch.
We did this at some point as an experiment but we don't have a use case for this anymore.

chore(idx): don't upload artifacts on PRs to rc-*

---

rs/nns/cmc/CHANGELOG.md
rs/nns/governance/CHANGELOG.md
rs/nns/handlers/root/CHANGELOG.md
rs/nns/sns-wasm/CHANGELOG.md
rs/registry/canister/CHANGELOG.md
rs/sns/governance/CHANGELOG.md
rs/sns/root/CHANGELOG.md
rs/sns/swap/CHANGELOG.md
testnet/tools/nns-tools/add-release-to-changelog.sh

Before, it said `proposals` (notice trailing `s`) instead of `proposal`.
These URLs were generated by `add-release-to-changelog.sh`. That has also been fixed.
How `CHANGELOG.md` files were changed:
```bash
for f in $(find rs/{nns,sns,registry} -name 'CHANGELOG.md'); do 
sed -i '' 's!/proposals/!/proposal/!' $f
done
```
**Pro tip**: when you expect a single character to be added or deleted from a long string of non-space characters (e.g. a URL), try the following:
```
git diff --word-diff-regex=.
```

fix(governance-tools): Proposal URL was wrong.

---

rs/bitcoin/ckbtc/mainnet/minter_upgrade_2025_02_12.md

This was [the security fix](https://dashboard.internetcomputer.org/proposal/135282)  that has already been adopted by NNS.
Verification instructions:
```
git checkout ddf05d2c70905a99b54c63520b69deef6a4fcc48
"./ci/container/build-ic.sh" "--canisters"
sha256sum ./artifacts/canisters/ic-ckbtc-minter.wasm.gz
```

chore(ckbtc): proposal to upgrade ckbtc minter

---

rs/consensus/src/cup_utils.rs

This code is called by the orchestrator to create registry CUPs, so it shouldn't panic.

fix: CON-1313 Don't panic in `make_registry_cup`

---

rs/execution_environment/src/execution_environment/tests.rs
rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
rs/system_api/src/lib.rs

This change makes it more clear that whenever a refund needs to be computed when processing a result of a canister execution, the available cycles in the call context would need to be emptied. This is important to maintain spec compliance and disallow accepting cycles after the call has been replied to.
In the current version of the code, this was not happening in the call context manager and instead we kinda relied on some logic in the system API that would return 0 cycles can be accepted when the call was already responded (without looking anything up in the call context). This is a bit error prone as two different components are attempting to uphold a property. In fact, we had filed a bug ticket thinking that we are not properly maintaining spec compliance in this case. This was …

refactor(EXC-1905): Take cycles from call context when a refund is to be returned

---

rs/rosetta-api/icp/tests/integration_tests/BUILD.bazel

The ICP Rosetta integration tests continue to have a flakiness rate of around 2,32%. In the failure cases, it is usually [`test_rosetta_blocks_mode_enabled`](https://sourcegraph.com/github.com/dfinity/ic@edcb5ab41a0faa2801b93a9560b6f7f9a58b033d/-/blob/rs/rosetta-api/icp/tests/integration_tests/tests/tests.rs?L419-421) timing out after 5min. This PR proposes to bump the timeout in an attempt to address the flakiness.

test(ICP_Rosetta): FI-1678: Set timeout to long for Rosetta ICP integration tests

---

rs/nns/sns-wasm/src/sns_wasm.rs
rs/nns/sns-wasm/tests/deploy_new_sns.rs
rs/nns/sns-wasm/unreleased_changelog.md

This PR is the final change to make Swap a proper SNS canisters, which means that it must be controlled by, and only by the SNS itself, which this PR ensures.

feat(sns): No longer grant NNS Root control over Swap canisters of newly deployed SNSs

---

rs/sns/test_utils/src/itest_helpers.rs

Previously, symptoms were
```
... panicked at rs/sns/test_utils/src/itest_helpers.rs:685:10:
Couldn't send funds.: "CreatedInFuture { ledger_time: 1739549219813820649 }" 
```
**How we (attempt to) address this**: When a test sends a transfer request to ledger, do not set the creation time.
**Why this change is sound**: It was wrong to set the time in the first place, because the caller never specified the time.
**Verification**: I used `--runs_per_test=256` (and [all runs passed]).
[all runs passed]: https://dash.zh1-idx1.dfinity.network/invocation/c73aaa95-4d33-42d6-a41b-7626c95f63f2?target=%2F%2Frs%2Fsns%2Fintegration_tests%3Aintegration_test_src%2Fproposals&targetStatus=5#256
This was flaking out 2.3% of the time.

test(sns): Deflake `//rs/sns/integration_tests:integration_test_src/proposals`.

---

testnet/tools/nns-tools/add-release-to-changelog.sh

Both Max and jason were unable to run the changelog-related commands because their environment was defaulting to the macos `date` command rather than the gnu one, which is more full-featured. 
I think gdate will work for them though. It comes with coreutils which most people should have already probably (i think you need it to compile rust?). Also the release runscript will tell you to install coreutils if you haven't yet.

fix(nns-tools): Use gdate command instead of date

---

Cargo.lock
rs/nervous_system/tools/release-runscript/BUILD.bazel
rs/nervous_system/tools/release-runscript/Cargo.toml
rs/nervous_system/tools/release-runscript/src/commands.rs
rs/nervous_system/tools/release-runscript/src/main.rs

This prevents a situation where they then need to go annoyingly restart the whole process
Marked as draft for now to prevent accidental merging until the previous PR in this chain is merged.
[← Previous PR](https://github.com/dfinity/ic/pull/4004)

feat(release-runscript): Ask user if they want to retry if a script fails

---

ci/src/dependencies/job/npm_scanner_periodic_job.py

fix(dep-mgmt): Remove legacy node engine version

---

rs/embedders/src/lib.rs
rs/embedders/src/wasm_utils.rs
rs/embedders/src/wasm_utils/validation.rs
rs/embedders/tests/validation.rs
rs/execution_environment/src/hypervisor.rs

EXC-1930
There is currently a limit on Wasm code section sizes of 10 MiB. In order to see how often users are getting close to the limit, we add a histogram metric which tracks this value each time a Wasm is compiled.

feat(EXC-1930): Add a metric tracking Wasm code section sizes

---

rs/execution_environment/src/lib.rs
rs/execution_environment/src/query_handler.rs
rs/replica/src/setup_ic_stack.rs

In a previous [change](https://github.com/dfinity/ic/commit/3760f0a2898a1ff66a22b14a626666ce481be9f8), the older `AnonymousQueryService` was dropped in order to re-use the same `QueryService` for handling both regular queries and transform functions from https outcalls.
While this change is a step in a good direction as we don't have mostly duplicate code in `AnonymousQueryService`, it couples regular queries with transform function executions. To provide better quality of service, go back to using two instances of the same service. This way we can get the best of both worlds: code reusability as well as isolation between the two types of queries.

refactor: Use two instances of the query service for queries and https outcall transform functions

---

rs/embedders/src/wasm_utils/validation.rs
rs/embedders/tests/validation.rs
rs/execution_environment/src/hypervisor.rs

EXC-1943
Increase the size of allowed canister Wasm code section sizes from 10 MiB to 11 MiB.

feat(EXC-1943): Bump allowed code section size

---

bazel/conf/.bazelrc.build
rs/ic_os/fstrim_tool/tests/integration_tests.rs
rs/replica/tests/cli.rs

What this literally does is sets the `CLICOLOR_FORCE` environment variable to `true`. This causes terminal output to be colored, if the test follows [that convention]. In particular, the Rust `colored` library uses that convention. In particular, canbench uses `colored`. This makes the output of canbench easier for humans to consume (and we should really care about humans, such as ourselves).
[that convention]: http://bixense.com/clicolors/

test: Make tests not squelch color when being run by bazel.

---

rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/canister_manager/tests.rs
rs/execution_environment/src/execution_environment.rs
rs/execution_environment/src/execution_environment/tests.rs
rs/replicated_state/src/canister_state/system_state/task_queue.rs

This PR ensures that the condition for a low-wasm memory hook will be met after every mgmt canister call.
Since we already have tests that condition is checked after Updating settings and Installing code, we will only add tests that snapshot operations influence hook in the floow-up https://github.com/dfinity/ic/pull/4023/files.

fix: EXC-1889 Hook condition should be checked after every mgmt canister call

---

MODULE.bazel
rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
rs/nns/integration_tests/src/cycles_minting_canister.rs
rs/nns/test_utils/src/state_test_helpers.rs

This PR bumps the Cycles Ledger dependency to the latest version. This includes adapting to a breaking change (`max_transactions_per_request` was renamed into `max_blocks_per_request`).
| [Next PR](https://github.com/dfinity/ic/pull/3891) >

test(nervous-system): Bump Cycles Ledger dependency to the latest version

---

.gitignore
ci/src/artifacts/rclone_download.py
ci/src/artifacts/rclone_upload.py

This edits the `.gitignore` to only ignore `artifacts` in the top-level directory. Otherwise, directories like `ci/src/artifacts` are ignored by git.
This also formats some Python files that are now taken into account by the formatting checks (were previously git ignored).

chore(idx): don't gitignore ci/src/artifacts

---

.github/workflows-source/schedule-hourly.yml
.github/workflows/schedule-hourly.yml

The `--config=ci` argument was inlined but the action input `BAZEL_CI_CONFIG` was left behind.

fix(IDX): remove leftover BAZEL_CI_CONFIG

---

rs/registry/canister/src/mutations/node_management/do_add_node.rs

Similarly to the test changes in #3924 that we made for removing nodes, here is an equivalent one for adding nodes. The `rewardable_nodes` field in `NodeOperatorRecord` is extended with sample `btreemap` values to test that node allowance field value isn't lost in the node add operation.

test(registry): improve test for do_add_node - check rewardable_nodes

---

rs/memory_tracker/BUILD.bazel
rs/memory_tracker/Cargo.toml
rs/memory_tracker/benches/bit_vec.rs

Creating 768GiB worth of pages (192M bits) takes 2.9ms:
```
test bitvec_from_elem_false/bits:256GiB/ops:1 ... bench:      144149 ns/iter (+/- 1961)
test bitvec_from_elem_false/bits:512GiB/ops:1 ... bench:     1336148 ns/iter (+/- 50658)
test bitvec_from_elem_false/bits:768GiB/ops:1 ... bench:     2917326 ns/iter (+/- 22253)
```
There is a significant performance improvement for 1TiB worth of pages
(256M bits or 32MiB):
```
test bitvec_from_elem_false/bits:1008GiB/ops:1 ... bench:     4069684 ns/iter (+/- 17428)
test bitvec_from_elem_false/bits:1TiB/ops:1 ... bench:          11312 ns/iter (+/- 53)
test bitvec_from_elem_false/bits:2TiB/ops:1 ... bench:          12974 ns/iter (+/- 209)
```
The standard vector behaves similarly, so it's likely the underlying
memory allocator optimizations: …

perf: EXC-1942: Add `BitVec` create/grow benchmarks

---

rs/messaging/tests/memory_tests.rs
rs/replicated_state/src/replicated_state.rs
rs/replicated_state/tests/replicated_state.rs

Have `ReplicatedState` expose best-effort and total message memory usage, both directly and via the `MemoryTaken` struct.
Also extend `ReplicatedState` tests to cover best-effort message memory usage.

feat(MR): [MR-661] Expose best-effort memory usage

---

rs/execution_environment/src/canister_manager/tests.rs

This is the first part in a series of PRs that will convert canister manager tests to use the established `ExecutionTest` framework as this way the result is much more readable and concise.

refactor: Use ExecutionTest for canister manager tests (part 1)

---

Cargo.lock
rs/rosetta-api/icp/BUILD.bazel
rs/rosetta-api/icp/CHANGELOG.md
rs/rosetta-api/icp/Cargo.toml

This PR prepares the v2.1.2 release for ICP Rosetta, which fixes the incomplete request interface for refreshing voting power.

chore(icp-rosetta): add rosetta-icp release v2.1.2

---

rs/consensus/dkg/src/utils.rs

Since https://github.com/dfinity/ic/pull/3997 we use a dedicated AlgorithmID for vetKD. However, the PR missed to use this algorithm ID also in batch delivery, which led to the long running system test `//rs/tests/consensus/vetkd:vetkd_key_life_cycle_test` getting broken (see https://github.com/dfinity/ic/pull/4060). This PR fixes this by using `AlgorithmID::VetKD` also in batch delivery.

feat(crypto): CRP-2646 use AlgorithmID::VetKD in batch delivery for vetKD

---

rs/nns/governance/CHANGELOG.md
rs/nns/governance/unreleased_changelog.md
rs/nns/sns-wasm/CHANGELOG.md
rs/nns/sns-wasm/unreleased_changelog.md

Affected canister(s):
* Governance
* SNS-WASM
Also, we forgot to update the NNS Governance CHANGELOG during a [recent emergency upgrade]. This fixes that.
[recent emergency upgrade]: https://dashboard.internetcomputer.org/proposal/135265
No SNS WASMs are being published in this upgrade cycle.

docs(nns): Updated CHANGELOGs for NNS canister upgrade proposals that were just made.

---

rs/rosetta-api/icp/tests/integration_tests/BUILD.bazel

Revert the timeout bump for the ICP Rosetta integration tests.

test(ICP_Rosetta): FI-1646: Revert ICP Rosetta integration tests timeout bump

---

.gitattributes

It references `/hs/generated` which doesn't exist anymore.

fix(IDX): remove unused .gitattributes

---

cog.toml

It looks like it was used by `cog verify` in part of a (long gone) GitLab job.

fix(IDX): remove cog.toml

---

.github/actions/bazel-test-all/action.yaml

The find approach processes files individually, reducing the window for race conditions compared to the recursive chown. We try to mitigate the following issue until `/cache` has proper ownership set when we deploy new K8s node:
```
chown: cannot dereference '/cache/bazel/_bazel_buildifier/6222b2212f4432660c3f74d6b773699d/sandbox/sandbox_stash/CargoBuildScriptRun/36/execroot/_main/bazel-out/k8-opt/bin/external/crate_index__ring-0.16.20/_bs-': No such file or directory
```

chore(IDX): replace chown

---

rs/ledger_suite/icrc1/ledger/src/lib.rs
rs/ledger_suite/icrc1/ledger/tests/tests.rs
rs/ledger_suite/tests/sm-tests/src/lib.rs

Disallow setting the following metadata in the initialization and upgrade arguments of the ICRC ledger:
- `icrc1:symbol`
- `icrc1:name`
- `icrc1:decimals`
- `icrc1:fee`
- `icrc1:max_memo_length`
These fields are already set explicitly in the arguments, from there the ledger reads them and interprets them. Setting them in the vector of metadata is confusing, since they are then returned in the response to `icrc1_metadata` queries, but they have no effect on the operation of the ledger.

feat(ICRC_Ledger): FI-1664: Forbid setting interpreted ICRC ledger metadata

---

packages/pocket-ic/src/lib.rs

This PR makes the PocketIC library (Rust) start the PocketIC server in the background so that the server doesn't receive signals such as CTRL^C from the foreground terminal, resulting in data races between killing the canister sandbox processes and the PocketIC server itself.

chore(PocketIC): start PocketIC server in the background

---

rs/bitcoin/ckbtc/minter/src/dashboard.rs

Since we moved to testnet4, blockstream.info URLs stopped working.
Change it to use mempool.space instead.

fix(ckbtc): Use mempool.space in ckBTC dashboard URLs

---

packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/src/lib.rs
packages/pocket-ic/src/nonblocking.rs

This PR adds the function `PocketIcBuilder::with_server_binary` to provide a path to the PocketIC server binary used to start a server process if necessary. This is an alternative to use the environment variable `POCKET_IC_BIN` in contexts where setting that environment variable is infeasible or undesirable.

feat(PocketIC): new builder function PocketIcBuilder::with_server_binary

---

packages/ic-vetkd-utils/src/lib.rs
packages/ic-vetkd-utils/tests/tests.rs

Makes `ic-vetkd-utils::DerivedPublicKey` and its `DerivedPublicKey::deserialize` `pub`lic, so that public keys returned by the IC's management canister interface `vetkd_public_key` can easily be validated without having to resort to other libraries (e.g., `ic_bls12_381` or `ic_crypto_internal_bls12_381_vetkd`).

feat(crypto): CRP-2700 support public key validation in ic-vetkd-utils

---

rs/tests/nns/BUILD.bazel

The test runs comfortably in under 3 minutes.

chore(IDX): don't make nns_dapp_test as long_test

---

ci/container/build-ic.sh

This makes the build output easier to read and aligns the format with that of `ci/bazel-scripts/main.sh`.

chore(IDX): add colors to build-ic builds

---

rs/nns/governance/src/governance.rs
rs/nns/governance/src/governance/benches.rs
rs/nns/governance/src/governance/tests/mod.rs
rs/nns/governance/unreleased_changelog.md

`NnsCanisterUpgrade`/`NnsRootUpgrade` are no longer used on mainnet. All the tools/tests/benchmarks are also switched off from them. This PR makes the proposal validation fail for such proposals.
* Remove the obsolete NNS functions from `allowed_when_resources_are_low`/`can_have_large_payload`
* Add the obsolete NNS functions to the obsolete cases in `check_obsolete`/`canister_and_function`
* Switch benchmarks to use `HardResetNnsRootToVersion`

chore(nns): Disable NnsCanisterUpgrade/NnsRootUpgrade

---

bin/afl_wrapper.sh

Bumping `AFL_FORKSRV_INIT_TMOUT` from 0.1s to 1s since some fuzzers are [timing out](https://github.com/dfinity/ic/actions/runs/13502450001/job/37724002792#step:5:557) where the forkserver is bought up. This doesn't affect the individual run timeout which is specified via `-t` parameter

chore(fuzzing): bump `AFL_FORKSRV_INIT_TMOUT` to 1s

---

.github/workflows-source/ci-main.yml
.github/workflows-source/release-testing.yml
.github/workflows-source/schedule-daily.yml
.github/workflows-source/schedule-hourly.yml
.github/workflows/ci-main.yml
.github/workflows/release-testing.yml
.github/workflows/schedule-daily.yml
.github/workflows/schedule-hourly.yml

This removes `before-script` (the `NODE_NAME` can be found in the environment in the first step).

chore(IDX): remove before-script

---

.bazelrc
Cargo.lock
packages/pocket-ic/test_canister/src/canister.rs
packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/BUILD.bazel
rs/pocket_ic_server/Cargo.toml
rs/pocket_ic_server/src/state_api/state.rs
rs/pocket_ic_server/tests/test.rs

This PR makes the HTTP gateway router in PocketIC more consistent with ic-gateway.
See forum post: https://forum.dfinity.org/t/supported-http-methods-for-a-canister/41238

fix(PocketIC): make HTTP gateway router in PocketIC more consistent with ic-gateway

---

rs/bitcoin/ckbtc/mainnet/btc_checker_upgrade_2025_02_25.md

Update the Bitcoin checker canister to include the latest code changes, notably:
* Update the OFAC checklist.
* Add new `check_transaction_query` and `check_transaction_str` methods.

chore(ckbtc): Proposal to upgrade BTC checker

---

Cargo.lock
rs/rust_canisters/canister_test/BUILD.bazel
rs/rust_canisters/canister_test/Cargo.toml
rs/rust_canisters/canister_test/src/canister.rs

This [commit](https://github.com/dfinity/ic/commit/a944a8b331f1562508a5dde68f6eafcfbb54fe44) broke the xnet compatibility test by adding a new field to `CanisterStatusResultV2`. This is an artifact of depending on the private management types instead of using the public version of the types as client code is supposed to do. Replicas never attempt to decode this type, they only produce it so there's no real issue with the IC's compatibility.
The quick fix here is to make a temporary copy of the type without the new field until the change is rolled out and then drop the copy in favour of using the public types. Additionally, the [check](https://sourcegraph.com/github.com/dfinity/ic@6c12598a8e5ab3a1a241af5b51d5a27990b8177e/-/blob/rs/rust_canisters/canister_test/src/canister.rs?L810-L820) of …

fix: Compatibility xnet test

---

rs/https_outcalls/adapter/src/metrics.rs
rs/https_outcalls/adapter/src/rpc_server.rs
rs/https_outcalls/consensus/src/pool_manager.rs

The socks proxy dark launch works on ~1% of all requests. on 99% it results in generic Hyper error.
During system testing, it seemed like socks5h had more success.
I also have a suspicion that currently only URLs containing IPv4 work, but it's best to confirm that.
It's important due to privacy reasons not to log the whole URL itself. Instead we are only looking at its "format": IPv4, IPv6, domain name, or empty.

feat: use socks5h schema and log url format

---

rs/ledger_suite/icp/ledger/src/main.rs

Replacing `caller`, `print`, `time_nanos` and `trap_with` with their `ic_cdk` equivalents.

chore(ICP-ledger): replace dfn_core with ic_cdk in ledger main, part 1

---

Cargo.lock
packages/pocket-ic/BUILD.bazel
packages/pocket-ic/CHANGELOG.md
packages/pocket-ic/Cargo.toml
packages/pocket-ic/src/lib.rs
rs/pocket_ic_server/BUILD.bazel
rs/pocket_ic_server/CHANGELOG.md
rs/pocket_ic_server/Cargo.toml
rs/pocket_ic_server/src/main.rs

This PR releases PocketIC server v8 and library v7.

chore: release PocketIC server v8 and PocketIC library v7

---

Cargo.lock
rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
rs/execution_environment/BUILD.bazel
rs/execution_environment/Cargo.toml
rs/execution_environment/src/hypervisor.rs
rs/execution_environment/tests/hypervisor.rs

Currently, metrics are not reported for DTS executions, also when heap dirty pages exceed 1 GiB.
This PR moves `InstanceStats` metrics from the hypervisor down to the sandbox execution level. That's why all the prefixes changed from `hypervisor_` to `sandboxed_execution_`. The descriptions and properties are otherwise the same.
The Rust formatter was having trouble with long lines in the metrics, so those are also fixed and formatted now.
This fixes RUN-982

fix: EXC-1946: Fix `InstanceStats` metrics

---

.github/actions/bazel-test-all/action.yaml

Without escaped parentheses `find` doesn't have the intended effect.

fix(IDX): find condition grouping

---

.github/workflows/container-base-images.yml

It looks like it is required to explicitly set the token at this step after all.

fix(IDX): add token to step

---

rs/sns/governance/src/governance/assorted_governance_tests.rs
rs/sns/governance/src/types.rs
rs/sns/governance/unreleased_changelog.md

This PR ensures that the whole proposal payload doesn't get debug-printed into the error that SNS Governance needs to serialize and send back to the client upon proposal rejection.

fix(sns): Bound SNS Governance response size for proposal submission

---

testnet/tools/BUILD.bazel

This removes the `manual` tag from `icos_deploy` to make sure it gets built on CI, and also fixes its build.

fix(IDX): build icos_deploy by default

---

ci/src/artifacts/upload.sh

Multipart uploads seem to be flaky on Cloudflare so we re-disable them.

fix(IDX): disable multipart upload on cloudflare

---

rs/execution_environment/src/canister_manager/tests.rs

This is the second part of converting canister manager tests to use the `ExecutionTest` framework.

refactor: Convert more canister manager tests to use ExecutionTest

---

rs/cross-chain/proposal-cli/src/candid/tests.rs
rs/cross-chain/proposal-cli/src/canister/mod.rs
rs/ledger_suite/icp/BUILD.bazel
rs/ledger_suite/icp/canister_ids.json

Add `proposal-cli` support for the 4th ICP ledger archive canister.

chore(ICP_Ledger): FI-1684: Add proposal-cli support for 4th ICP archive

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

Currently, the `bazel test` command may not pull all the build checksums from the cache, meaning the build determinism may have nothing to compare.
As a (hopefully temporary) workaround, we skip the checks if the build didn't produce checksums.

fix(IDX): work around missing build checksums

---

rs/memory_tracker/src/tests.rs

Using static mut would become a hard error in future Rust version, so the memory tracker tests should avoid using it.
One quick idea was to move the static in the `thread_local` (as the tracker that's already a thread local) but that doesn't work and can lead to a segfault in tests. Each time we call `sigaction` in the tests, we're installing a new signal handler referencing the old one as fallback but if the signal handler is declared as `thread_local`, one thread does not see the signal handlers that were installed by others. This can lead to some of these missing from the chain of handlers we attempt to build (by installing a new and referencing the old one) and thus lead to a segfault in a test if we receive a signal that is expected to be handled by a missing handler.
Instead, it …

refactor(EXC-1841): Avoid using static mut references in memory tracker

---

rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
rs/sns/governance/api/src/topics.rs
rs/sns/governance/canister/governance.did
rs/sns/governance/canister/governance_test.did
rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
rs/sns/governance/src/governance.rs
rs/sns/governance/src/pb/conversions.rs
rs/sns/governance/src/proposal.rs
rs/sns/governance/src/proposal/set_custom_proposal_topics.rs
rs/sns/governance/src/topics.rs
rs/sns/governance/src/types.rs
rs/sns/governance/unreleased_changelog.md

This PR introduces a new type of SNS proposals, `SetCustomProposalTopics`, which can be used to batch-set topics for all custom proposals (or any non-empty subset thereof) at once.
| [Next PR](https://github.com/dfinity/ic/pull/4170) >

feat(sns): Introduce `SetCustomProposalTopics` proposal type

---

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
rs/nns/governance/api/src/proposal_submission_helpers.rs
rs/nns/governance/canister/governance.did
rs/nns/governance/canister/governance_test.did
rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
rs/nns/governance/src/governance.rs
rs/nns/governance/src/pb/conversions.rs

Similar to SNS, we'd like to support disbursing maturity instead of spawning neurons from it, since most of the time the users just want the minted ICP by converting the maturity.
* Define a new manage neuron command `DisburseMaturity` and corresponding response, in .proto, .rs and .did
* Add `#[serde(with = "serde_bytes")]` to the subaccount bytes in the API type

feat(nns): Define API for disburse maturity

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml
ci/bazel-scripts/main.sh

This adds a check to make sure that `bazel-out` exists before we scan it for checksums. If `bazel-out` (a symlink) doesn't exist, then we create an empty `SHA256SUMS`.

fix(IDX): check that bazel-out exists

---

rs/nns/governance/canbench/canbench_results.yml
rs/nns/governance/src/governance.rs
rs/nns/governance/src/neuron/types.rs
rs/nns/governance/src/neuron_store.rs
rs/nns/governance/src/neuron_store/benches.rs

When trying to unstake maturity, not only the listing steps are computationally intensive, the actual unstaking is too, because it calls `with_neuron_mut` in a loop. We should cap the number of neurons to unstake in a single message, and this benchmark prepares for the improvement.
* Refactor the `Governance::unstake_maturity_of_dissolved_neurons` to `NeuronStore::unstake_maturity_of_dissolved_neurons` since only neuron store is involved for this operation.
* Change benchmark from `list_neurons_ready_to_unstake_maturity` to `unstake_maturity_of_dissolved_neurons`
* Add bench scopes for listing and unstaking, since the former is linear to # of neurons and the latter depends on the available number of neurons to unstake maturity (and those 2 numbers don't have a reasonable ratio that we can …

perf(nns): Change from benchmarking listing neurons for unstake maturity to benchmarking the entire unstake maturity operation

---

packages/pocket-ic/tests/tests.rs
rs/config/src/execution_environment.rs
rs/execution_environment/src/canister_manager.rs
rs/execution_environment/src/canister_manager/tests.rs
rs/execution_environment/src/execution_environment.rs
rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
rs/test_utilities/execution_environment/src/lib.rs

This increases the maximum allowed snapshots per canister from 1 to 10. It should allow people to take multiple snapshots at different times and be able to restore their canister to different versions if desired.
The maximum number is moved to the execution config to make it possible to write the test in execution_environment in a more robust way that does not depend on the hardcoded value. In the future, if we need to change the number it should really be one line change.

feat: Increase max snapshots allowed per canister

---

ci/bazel-scripts/main.sh

This stores the bazel exit code and ensures the `main.sh` script can finish instead of directly exiting on error.

fix(IDX): don't shortcut main.sh on failure

---

rs/nns/integration_tests/src/neuron_following.rs

This disables a test that is currently failing due to a timing issue. The test will be re-enabled by the NNS team once fixed.

chore(IDX): disable failing NNS test

---

.github/actions/bazel-test-all/action.yaml
.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

The encryption step fails because `gpg` is missing from the machines. Before https://github.com/dfinity/ic/pull/4171 this was a silent failure, but is now explicit. So we disable it.

fix(IDX): don't try to upload bep on macOS intel

---

rs/tests/testnets/BUILD.bazel
rs/tests/testnets/Cargo.toml
rs/tests/testnets/single_app_small_node.rs

The new testnet configuration is similar to `single_app_large_node` but the single node is allocated significantly less resources (16 vCPUs, 64GiB of RAM, and 100 GiB disk) than the current config. While `single_app_large_node` is for performance testing, `single_app_small_node` is created for security to look into interaction between host and replica. With each node occupying less resource, we can afford frequent teardown without affecting the overall load.

feat(testing): Add new testnet `single_app_small_node`

---

.github/workflows-source/ci-main.yml
.github/workflows/ci-main.yml

This stores the `BAZEL_EXTRA_ARGS` as a step output instead of an environment variable, so that it does not unnecessarily pollute the environment.

chore(IDX): don't export BAZEL_EXTRA_ARGS

---

packages/pocket-ic/HOWTO.md
packages/pocket-ic/tests/tests.rs
rs/pocket_ic_server/tests/test.rs

This PR updates the PocketIC docs on the "live" mode to address the confusion reported in this [forum post](https://forum.dfinity.org/t/pocket-ic-7-0-issue-with-http-outcalls-in-live-mode/39110).

chore(PocketIC): update PocketIC docs on live mode

---

rs/nns/governance/init/src/lib.rs
rs/nns/integration_tests/src/neuron_following.rs

The later you run these tests, the more that voting power gets reduced.
The clock in the test is set to the current real time, but the timestamps in the test are hard-coded; in particular, `voting_power_refreshed_timestamp_seconds` in Neuron was set to [the default value]. Thus, starting on Mar 2 (in the real world), the test starts seeing that neurons have not refreshed in a "long time" (where "long time" is defined by [this parameter]). Thus, voting power reduction started to kick in, leading to the observed exercised voting power being less and less. Whereas, the expected amount of exercised voting power is some hard-coded value. Thus, the `assert` condition stopped being met.
[the default value]: https://sourcegraph.com/github.com/dfinity/ic@9d4240be28224b578e58f3c1f3734a6729905226/-/b …

test(nns): Fix tests that see less and less voting power.

---

.github/CODEOWNERS

Perhaps it was just renamed to `monitoring/tracing`. As it is, it doesn't exist.

chore: removes an entry that doesn't exist from CODEOWNERS

---

.github/actions/bazel-test-all/action.yaml

After https://github.com/dfinity/ic/pull/4171 the `SSH_AUTH_SOCK` was not exported anymore in the step that needed it. The changes here ensure the socket is still set in the actual bazel test step.

fix(IDX): export SSH_AUTH_SOCK in bazel-test-all
