.github/workflows/update-mainnet-revisions.yaml
I thought this wasn't required because we already have the token set in the checkout step, but apparently it fails if it is not set again.
=> fix(IDX): set GH token

ci/bazel-scripts/main.sh
This ensures that, even if no bazel targets are built, the `SHA256SUMS` file gets created.
=> fix(IDX): create empty SHA256SUMS even if no build

rs/execution_environment/fuzz/src/lib.rs
Corresponding [failure](https://github.com/dfinity/ic/actions/runs/13637443383/job/38119562486#step:4:1199) observed on the hourly pipeline
=> chore(fuzzing): Add `fcntl` to the sandbox monitor whitelist

rs/state_machine_tests/src/lib.rs
This PR increases state hash timeout in SM tests from 10s to 5min to avoid test [flakiness](https://dash.zh1-idx1.dfinity.network/invocation/47b7b0bd-80d9-4e50-8a6e-3353db2d5142?target=%2F%2Frs%2Fpocket_ic_server%3Atest&targetStatus=6#@110) of the form:
```
thread 'tokio-runtime-worker' panicked at rs/state_machine_tests/src/lib.rs:2637:9:
State hash computation took too long (10.009051501s)
```
=> chore: increase state hash timeout in SM tests

rs/nns/governance/src/benches_util.rs, rs/nns/governance/src/governance/benches.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron_store/benches.rs
We have some analysis based on the benchmarks to make sure certain computation does not exceed the instruction limit in production. Those analyses are based on extrapolations given the size used in the benchmark and the production size limit (e.g. neurons limit). Such analyses were not enforced through tests. For example, if certain operation gets more expensive in a PR, people might update the bench results without realizing that the change will cause problems in the production.
After the benchmarks are run, do extrapolation and assertion using the same analysis previously only expressed through comments (if at all).
=> perf(nns): Assert the instructions of certain periodic tasks are not too high

ci/bazel-scripts/main.sh
This adds a log line showing the build command being run. Previously, the last log line was `setting default repository cache`, which made the logs somewhat confusing (because the build command can take some time to show some output).
=> chore(IDX): show build command in main.sh

rs/nns/governance/src/governance.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/benches.rs, rs/nns/governance/src/neuron_store/neuron_store_tests.rs, rs/nns/governance/unreleased_changelog.md
The instructions used by unstaking maturity will become larger after migrating neurons to stable memory. Therefore we should bound the number of neurons to process within the same message. Note that the remaining neurons will continue to be processed at the next timer invocation.
=> feat(nns): Limit the number of neurons to unstake maturity in a single message

rs/embedders/benches/compilation.rs
EXC-1982
Add a "benchmark" in our compilation time bench suite that reports the compilation cost of each Wasm and the expected compilation time based on that cost. This will allow us to see how accurate the compilation costs are.
The benchmark test cases previously had hard-coded compilation costs which would need to be updated if the compilation costs changed. These are no longer needed now that we have a simple way to display the compilation costs along with the compilation time benchmark results.
=> test(EXC-1982): Benchmark compilation cost

mainnet-canister-revisions.json, rs/nervous_system/integration_tests/tests/sns_release_qualification.rs, rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs, rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils_legacy.rs, rs/nervous_system/integration_tests/tests/upgrade_everything_test.rs, rs/nervous_system/integration_tests/tests/upgrade_existing_sns_test.rs
This PR adjusts the SNS qualification tests that used to trigger SNS framework upgrades via proposal. 
The reason is adjustment is needed is that these tests use the mainnet WASMs, and those have recently changed (https://dashboard.internetcomputer.org/proposal/135615). In particular, the new behavior if to have automatic target version advancement from the moment an SNS is deployed. Whereas, tests assumed the old behavior (i.e. new SNS does NOT upgrade automatically, unless someone passes a special proposal).
=> test(sns): Release qualification tests should take automatic target version advancement into account

Cargo.lock, rs/nns/test_utils/golden_nns_state/BUILD.bazel, rs/nns/test_utils/golden_nns_state/Cargo.toml, rs/nns/test_utils/golden_nns_state/src/lib.rs, rs/nns/test_utils/prepare_golden_state/BUILD.bazel, rs/nns/test_utils/prepare_golden_state/Cargo.toml, rs/nns/test_utils/prepare_golden_state/src/lib.rs, rs/nns/test_utils/prepare_golden_state/src/watch_and_prepare.rs
Currently, if we have to run tests against golden NNS/SNS state many times, each iteration will download and untar the state before doing anything meaningful. However, if we use a separate binary to watch and prepare for the next iteration, the download/untar time can be hidden behind any time needed for the user to analyze and decide what to do with the next iteration.
* Refactor the download/untar operations to a library
* Use the library to implement a binary to watch a directory and untar if the state directory is taken (by the `StateMachine`)
=> test(nns): Use a separate binary to prepare golden state to speed up experimentation

rs/nns/test_utils/src/common.rs
Move the build_*_wasm functions into the same order that is in nns/constants/src/lib.rs, so that it is easier to find out if a given function exists, and to keep the file organized.
=> refactor(tests): Reorganize build_*_wasm functions

rs/tests/kubeconfig.bzl, rs/tests/system_tests.bzl
This ensures that -- by default -- system tests are not with run the `local` strategy. When run `local`ly, system tests don't seem to get cached across server restarts.
The `select()` which was evaluated as a boolean was truthy meaning the `local` tag was always added. Instead, the `local` strategy is specified as a CLI arg in the k8s CI job.
=> fix(IDX): don't run system tests with 'local' by default

pre-commit/check-incompatibilities.sh
This tweaks the buf incompatibility checks to use temporary dirs instead of creating temporary files in the source tree.
=> chore(IDX): don't create buf bins in PWD

rs/nns/governance/canister/canister.rs, rs/nns/governance/unreleased_changelog.md
The failure rate was 0.7: https://github.com/dfinity/ic/pull/1659 before we were notified about integrators needing more time to migrate. Now that they have migrated, ramping back to 0.7 again.
=> feat(nns): Increase the _pb method failure rate to 0.7 again

Cargo.lock, rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs, rs/sns/governance/canister/governance.did, rs/sns/governance/canister/governance_test.did, rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto, rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs, rs/sns/governance/src/governance.rs, rs/sns/governance/src/governance/assorted_governance_tests.rs, rs/sns/governance/src/governance/proposal_topics_tests.rs, rs/sns/governance/src/pb/conversions.rs, rs/sns/governance/src/proposal.rs, rs/sns/governance/src/topics.rs, rs/sns/governance/src/types.rs, rs/sns/governance/unreleased_changelog.md
This PR enables clients to reuse the existing calls they make to obtain the information about which topic this proposal corresponds to (at the time of proposal submission).
=> feat(sns): Add field `topic` to `ProposalData`

rs/nns/governance/src/governance.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/neuron_store_tests.rs, rs/nns/governance/tests/governance.rs, rs/nns/governance/unreleased_changelog.md
Currently, the execution of `ApproveGenesisKyc` proposals don't have a bound. However unlikely, it's possible for such proposals to get through. It's not a big issue now since changing neurons have lower instruction cost. However, after neurons are migrated to stable memory, this can become a problem.
Apply a limit of 1000 for the maximum number of neurons to set `kyc_verified`. This should be safe as `with_neuron_mut` should take ~5M instructions at maximum. Also, we don't expect a single kyc to apply to 1000 neurons.
=> fix(nns): Avoid applying approve_genesis_kyc for more than 1000 neurons

ic-os/components/hostos-scripts/monitoring/monitor-power.sh
The output of the IPMI tool changed. Now, both the IPMI timestamp and the Sampling period are on the same line. With that the script was actually extracting the date. The affected nodes were encountering the following issue:
```
ts=2025-03-06T12:12:11.776Z caller=textfile.go:245 level=error collector=textfile msg="failed to collect textfile data" file=power_metrics.prom err="failed to parse textfile data from \"/run/node_exporter/collector_textfile/power_metrics.prom\": text format parsing error in line 11: expected float as value, got \"03/06/25\""
```
=> fix: extracting of sampling period for power measurements

rs/boundary_node/ic_boundary/src/check/test.rs, rs/boundary_node/ic_boundary/src/cli.rs, rs/boundary_node/ic_boundary/src/core.rs, rs/boundary_node/ic_boundary/src/routes.rs, rs/boundary_node/ic_boundary/src/routes/test.rs, rs/boundary_node/ic_boundary/src/snapshot/test.rs, rs/boundary_node/ic_boundary/src/test_utils.rs, rs/pocket_ic_server/src/pocket_ic.rs
This adds two parameters:
* `health_nodes_per_subnet_alive_threshold`: fraction of nodes to be healthy in the subnet to consider the subnet alive (defaults to 0.6666)
* `health_subnets_alive_threshold`: fraction of healthy subnets visible to consider ourselves healthy (defaults to 0.51)
Previously we were considering ourselves healthy when we had 1 or more nodes alive total.
=> feat(BOUN-1364): ic-boundary: make self-health-checking more smart

rs/embedders/src/wasm_utils/validation.rs, rs/embedders/src/wasmtime_embedder/system_api.rs, rs/embedders/src/wasmtime_embedder/system_api_complexity.rs, rs/embedders/tests/wasmtime_embedder.rs, rs/execution_environment/src/query_handler/query_cache/tests.rs, rs/execution_environment/tests/execution_test.rs, rs/interfaces/src/execution_environment.rs, rs/system_api/src/lib.rs, rs/system_api/src/sandbox_safe_system_state.rs, rs/system_api/tests/system_api.rs, rs/test_utilities/embedders/src/lib.rs, rs/universal_canister/impl/src/api.rs, rs/universal_canister/impl/src/lib.rs, rs/universal_canister/impl/src/main.rs, rs/universal_canister/lib/src/lib.rs
This PR implements a new system API `ic0.canister_liquid_cycle_balance128` returning the current amount of cycles that is available for spending in calls and execution without getting frozen. This way, canisters can bound the amount of cycles attached to a call to prevent spurious traps when calling `ic0.call_cycles_add` or `ic0.call_cycles_add128`.
=> feat: new system API to retrieve liquid cycle balance of a canister

rs/boundary_node/ic_boundary/src/routes.rs, rs/boundary_node/ic_boundary/src/routes/test.rs
Small fix to previous PR that makes sure we do not crash when there are no subnets in the registry or there are subnets with zero nodes (probably a real case when the new subnet is added)
=> fix(BOUN-1364): handle empty subnets and no subnets

rs/sns/cli/src/health.rs
This PR adds a new column to indicate the status of automatic SNS target version advancement for each SNS.
=> feat(sns_cli): Add Auto upgrades status to `sns health`

rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/src/lib.rs, rs/nns/governance/unreleased_changelog.md, rs/nns/integration_tests/src/governance_migrations.rs
Re-enable neuron migration to stable memory after several improvements were made:
* Compared to the last time it was enabled, several improvements were made:
* Distribute rewards is moved to timer, and has a mechanism to distribute in batches in multiple messages.
* Unstaking maturity task has a limit of 100 neurons per message, which prevents it from exceeding instruction limit.
* The execution of `ApproveGenesisKyc` proposals have a limit of 1000 neurons, above which the proposal will fail.
* More benchmarks were added.
* Set `MIGRATE_ACTIVE_NEURONS_TO_STABLE_MEMORY` to true, which will cause active neurons to be continously moved from heap memory to stable memory in timers.
* Update benchmarks:
* The regression of `range_neurons_performance` is expected, since the benchmark loops …
=> feat(nns): Re-enable neuron migration

.github/actions/bazel-test-all/action.yaml, .github/workflows-source/ci-main.yml, .github/workflows-source/schedule-hourly.yml, .github/workflows/ci-main.yml, .github/workflows/schedule-hourly.yml, .github/workflows/system-tests-k8s.yml, ci/bazel-scripts/main.sh
This avois having the credentials set in the environment for the whole run and instead only have it accessed by the action that needs it.
=> chore(IDX): move cloud creds to action input

rs/nns/governance/src/lib.rs, rs/nns/governance/src/timer_tasks/mod.rs, rs/nns/governance/src/timer_tasks/seeding.rs, rs/nns/governance/unreleased_changelog.md
To better observe timer tasks, enable the metrics to be encoded into '/metrics' endpoint.
* Encode the timer task metrics
* Correct the 'seeding' task name to be lower case.
=> feat(nns): Enable timer task metrics

.github/workflows-source/schedule-daily.yml, .github/workflows/schedule-daily.yml, .github/workflows/schedule-rust-bench.yml
Reverts dfinity/ic#4159
Rust benchmark runs on dedicated machine and is excluded with monitoring workflow runs that are in the wait queue for more then 20 minutes. Having it on daily workflow would be OK if it wouldn't run on `workflow_dispatch` but then maybe Crypto team does want to run them on `workflow_dispatch`, therefore the best is if they're in it's own workflow.
=> revert: "refactor(IDX): move rust-benchmarks to daily workflow"

Cargo.lock, rs/ledger_suite/icp/ledger.did, rs/ledger_suite/icp/ledger/Cargo.toml, rs/ledger_suite/icp/ledger/ledger_canisters.bzl, rs/ledger_suite/icp/ledger/src/main.rs
I only migrate simple, non-protocol buffer query endpoints in this PR.
=> chore(ICP-Ledger): migrate non-pb query endpoints from dfn to cdk

rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/src/ledger_blocks_sync.rs
We are seeing a high volume of error messages like:
```
Error in syncing blocks: InternalError(false, Details { error_message: Some("Tip of the chain has index 21177563 but no block fou
nd at that index!"), extra_fields: {} })
```
Which is likely caused when we hit a slightly delayed IC node after getting the tip index from a more up-to-date one.
This PR introduces retries for fetching the tip block, so that it can eventually succeed getting the tip block.
It also removes logging failures to get block ranges until all retries have been attempted, cleaning the logs even further.
This was tested locally. Before the change, we were seeing the error logs a few times per minute, with the change the error and warn logs are gone after running for many minutes.
=> fix: retry fetching tip block

rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs, rs/embedders/fuzz/src/wasm_executor.rs, rs/embedders/src/compilation_cache.rs, rs/embedders/src/lib.rs, rs/embedders/tests/compilation_cache.rs, rs/execution_environment/src/hypervisor.rs, rs/types/types/src/lib.rs, rs/utils/lru_cache/src/lib.rs
Limit the number of entries in the compilation cache so that it doesn't take up too many file descriptors.
=> fix(EXC-1990): Limit compilation cache entries

rs/embedders/src/wasm_utils/validation.rs, rs/embedders/src/wasmtime_embedder/wasmtime_embedder_tests.rs, rs/execution_environment/tests/execution_test.rs
This reverts commit 227e8e3de539e128ab67ca0375fd24e291e93b28. 
Wasmtime 30 contains the fix that makes wasmtime module validation deterministic, so this hotfix can be removed and the concrete error can be returned to the user again.
=> chore: [EXC-1833] Revert "chore: Ignore wasmtime validation errors (#3338)"

rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Adapt the ICRC ledger suite golden state tests to the latest ledger version that migrates blocks from the heap to stable structures.
=> test(ICRC_Ledger): FI-1693: Adapt ICRC golden state tests to migration of blocks

rs/replicated_state/src/page_map/storage/tests.rs
We don't necessarily gain much from running hundreds of times a proptest that writes hundreds of files. Limit it to 10 cases (i.e. runs) instead of the default 256; and 10 instructions (instead of 20).
This reduces the runtime (on my devenv, YMMV) from 2+ minutes to 2 seconds.
=> chore: Reduce the size of the random_instructions proptest

rs/canister_sandbox/src/dts.rs, rs/embedders/src/wasm_executor.rs, rs/execution_environment/tests/dts.rs, rs/interfaces/src/execution_environment.rs, rs/system_api/src/lib.rs
To improve finalization rates, executions generating over one gigabyte of dirty pages were previously split into execution and memory copy slices.
The previous implementation paused the canister, but because neither instruction nor heap delta limits were reached, the canister resumed in the next inner loop of the same round.
This PR always passes a zero instruction counter to the `yield_for_dirty_memory_copy`, ensuring that the round instruction limit is reached.
The memory copy slice reaches the `MAX_HEAP_DELTA_PER_ITERATION` limit, and does not require any fixes.
This fixes RUN-878.
=> fix: EXC-1969: Fix in-round DTS for memory copy

mainnet-canister-revisions.json, rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs, rs/nervous_system/integration_tests/tests/sns_release_qualification.rs, rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs, rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils_legacy.rs, rs/nervous_system/integration_tests/tests/upgrade_existing_sns_test.rs
This PR adds a temporary step to all SNS qualification tests that normally work with mainnet SNS-W version to first upgrade it to the latest version on the master branch. This prepares for an urgent SNS-W release needed to fix the SNS deployment error caused by NNS Governance and SNS-W APIs being out of sync (namely, NNS Governance no longer sets the neurons field, while the mainnet SNS-W still requires that).
This change is also enabling us to bump the mainnet canister versions.
=> test(sns): Upgrade SNS-W before deploying SNS (and bump the canister mainnet versions)

rs/https_outcalls/client/src/metrics.rs
This PR fixes typographical errors in the https_outcalls metrics documentation.
- Corrects the misspelled word "conesusus" to "consensus" for request results.
- Fixes "Execiton" to "Execution" in the execution duration metric description.
=> chore: fix typos in http_outcalls metrics.rs file

rs/embedders/BUILD.bazel, rs/embedders/benches/compilation.rs
EXC-1983
This will allow us to benchmark changes to the compilation process to see if there is a trade off between compilation and execution times.
=> test(EXC-1983): Add a query benchmark to compilation benches

rs/consensus/src/consensus/block_maker.rs, rs/consensus/src/consensus/malicious_consensus.rs
The certified height is already part of the validation context.
=> chore: Remove unnecessary `certified_height` argument

rs/ethereum/ledger-suite-orchestrator/test_utils/src/lib.rs
This removes usages of `ic_test_utilities::load_wasm` from the `ledger_suite_orchestrator` test utils.
The `load_wasm` helper was introduced when both cargo & bazel tests were supported; now it merely adds indirection so we remove it. This also makes navigating the code & dependencies much easier as environment variables are referenced by named, instead of inferred from canister name.
=> chore(IDX): load ledger suite orchestrator wasm directly

.github/actions/bazel-upload-checksums/action.yaml, .github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml, ci/bazel-scripts/main.sh
This deduplicates the logic for finding checksums and uploading checksums as a GitHub artifacts. The implementation was duplicated (though not exactly identical) between `main.sh` and the `Build IC` build step.
=> chore(IDX): deduplicate checksum upload

ci/scripts/run-build-ic.sh
This modifies `run-build-ic.sh` to be a bit more readable:
* remove references to env vars that do not exist anymore or that were not used
* flatten if-logic
* use consistent string matching
=> chore(IDX): simplify run-build-ic.sh

ic-os/hostos/context/Dockerfile.base, ic-os/hostos/context/packages.common
Reverts dfinity/ic#4320. This is a NOOP for the actual image builds. Now that new base images have been built and published, this switches them back to the previous changes, while they are being tested on https://github.com/dfinity/ic/pull/4321.
=> revert: "feat: [NODE-1574] Upgrade components to SEV-SNP compatible versions"

ic-os/guestos/context/Dockerfile.base, ic-os/guestos/context/packages.common
There is no metapackage to track the "extra" modules that does not also include firmware. This manually adds only the extra modules, and a small mechanism to keep them in sync. We need the extra modules for `sev-guest` support.
=> feat: Remove firmware from GuestOS

Cargo.Bazel.Fuzzing.json.lock, Cargo.Bazel.Fuzzing.toml.lock, Cargo.Bazel.json.lock, Cargo.Bazel.toml.lock, Cargo.lock, Cargo.toml, bazel/external_crates.bzl, rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml, rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml, rs/ledger_suite/tests/sm-tests/src/lib.rs, rs/nns/governance/canbench/canbench_results.yml
To benefit from the performance gains in recent editions of stable-structures, we need to update.
=> chore: upgrade stable-structures

ci/scripts/run-build-ic.sh
This ensures the `ARGS` variable is set. Otherwise, if no changes are required, the variable is unset when the size is checked.
=> fix(IDX): initialize ARGS var

rs/tests/query_stats/BUILD.bazel
The P90 duratiion of the following tests is higher than the maximally allowed 5 minutes:
* `//rs/tests/query_stats:query_stats_above_threshold`: 7min 20s
* `//rs/tests/query_stats:query_stats_basic`: 6min 38s
So we mark them as `long_test` such that they're not automatically run on PRs but only when requested explicitly by tagging the PR with `CI_ALL_BAZEL_TARGETS` or when commits are pushed to `master`.
=> test(IDX): mark query_stats_above_threshold and query_stats_basic as long_tests

bazel/conf/.bazelrc.build
On CI run all system-tests up to 3 times since they're known to be the most flaky since they require non-deterministic resources like the Internet.
For docs see:
https://bazel.build/reference/command-line-reference#flag--flaky_test_attempts
=> chore(IDX): run system-tests up to 3 times on CI

rs/tests/driver/src/util.rs
We occasionally observe that the first attempt of installing a UniversalCanister in a system-test takes a long time and eventually times out after 5 minutes. A subsequent attempt usually succeeds quickly as show in the following example:
```
2025-03-14 10:21:50.735 DEBG[query_stats_above_threshold:rs/tests/driver/src/driver/test_env_api.rs:2056:0] Func="install UniversalCanister 5v3p4-iyaaa-aaaaa-qaaaa-cai [rs/tests/driver/src/util.rs:169]" is being retried for the maximum of 500s with a constant backoff of 5s
2025-03-14 10:27:00.319 DEBG[query_stats_above_threshold:rs/tests/driver/src/driver/test_env_api.rs:2078:0] Func="install UniversalCanister 5v3p4-iyaaa-aaaaa-qaaaa-cai [rs/tests/driver/src/util.rs:169]" failed on attempt 1. Error: Couldn't create canister with provisional API: The …
```
=> test(IDX): have a 30s timeout for creating the Universal and Message Canisters

rs/types/management_canister_types/BUILD.bazel
https://github.com/dfinity/ic/pull/4020 removed the actual dependency of private management types from `artifact_pool` but it missed that there were 2 mentions of `//rs/artifact_pool` in the bazel dependency whitelist. This PR removes the mentions from the whitelist completely.
=> chore: Remove artifact_pool from whitelist of private mananagement types

rs/xnet/payload_builder/src/certified_slice_pool.rs
Replace `panic` with `debug_assert` plus returning an empty slice if, after having checked that an empty slice would fit; and that the slice we have won't fit; it turns out we somehow still have an empty slice. The slice will eventually be replaced in the pool; or the payload builder will call us with a higher limit; so this cannot lead to stalling the stream.
=> refactor: Downgrade `panic` to `debug_assert` in `Payload::take_prefix`, part 2

ci/src/artifacts/upload.bzl, ci/src/artifacts/upload.sh
This moves the "skip" logic out of `upload.sh` and into `upload.bzl`. This allows us to reuse `upload.sh` wherever necessary without the script needed to figure out if it needs to run or not.
This'll allow us to move the upload out of the build and into a new CI step.
=> chore(IDX): flatten upload.sh

packages/pocket-ic/CHANGELOG.md, packages/pocket-ic/src/lib.rs
This PR fixes the functions `PocketIcBuilder::with_nns_subnet`, `PocketIcBuilder::with_sns_subnet`, `PocketIcBuilder::with_ii_subnet`, `PocketIcBuilder::with_fiduciary_subnet`, and `PocketIcBuilder::with_bitcoin_subnet` to not add a new empty subnet if a subnet of the corresponding kind has already been specified (e.g., with state loaded from a given state directory).
=> fix(PocketIC): do not add a new empty subnet if a subnet has already been specified

rs/ledger_suite/icp/archive/src/main.rs
While migrating to from dfn to cdk, I did not add `ic_cdk::setup();` at the beginning of some endpoints. There are still some endpoints that are missing the setup call, but they were not touched by the migration.
=> chore(ICP-Archive): add missing ic_cdk setup

rs/pocket_ic_server/src/main.rs, rs/pocket_ic_server/src/state_api/routes.rs
This PR fixes TTL in PocketIC for long-running requests by
- not terminating the PocketIC server while a request is pending;
- refreshing TTL *after* processing request.
=> fix(PocketIC): TTL for long-running requests

rs/boundary_node/ic_boundary/src/cache.rs, rs/boundary_node/ic_boundary/src/cache/test.rs, rs/boundary_node/ic_boundary/src/core.rs, rs/boundary_node/ic_boundary/src/metrics.rs, rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs, rs/boundary_node/ic_boundary/src/routes.rs, rs/boundary_node/ic_boundary/src/snapshot.rs
* Caching middleware will now cache the response extensions so that the metrics can log e.g. proper node id etc.
* Move caching middleware a bit up the stack (before retry)
=> chore(BOUN-1188 BOUN-963): `ic-boundary`: improve caching a bit, cleanup dead code

rs/xnet/payload_builder/src/certified_slice_pool.rs
While the check is technically safe (`Payload::count_bytes()` returns the size of the header plus the size of all messages; and `take_prefix` starts with the header size and computes a running total of message sizes), it is safer to use a `debug_assert` instead of the `panic` and to continue, cutting off the `Payload` just before the last message.
=> refactor: Downgrade `panic` to `debug_assert` in `Payload::take_prefix`

rs/nns/integration_tests/src/governance_time_warp.rs
Relaxed an assert by advancing time more (via set_time_warp).
Hard to verify whether this correctly deflakes, because even with `--runs_per_test=317` I am not able to provoke a flake (without this change). FWIW, with these changes, `--runs_per_test=317` still works.
Also, added some diagnostics. If this fix does not work, diagnostics will probably help with future deflaking efforts.
=> test(nns): Trying to deflake governance_time_warp.

ci/src/mainnet_revisions/mainnet_revisions.py
This PR enables auto-merge for the automatic PRs created for revisions made to the mainnet canister files. This is the first step in fully automating the approval process - the second step will be adding mergify to give the approval.
See test PR here where auto-merge is enabled: https://github.com/dfinity/ic/pull/4411
=> chore(IDX): enable auto-merge for mainnet revisions file

Cargo.lock, rs/registry/canister/BUILD.bazel, rs/registry/canister/Cargo.toml, rs/registry/canister/canister/canister.rs, rs/registry/canister/canister/registry.did, rs/registry/canister/proto/ic_registry_canister/pb/v1/registry.proto, rs/registry/canister/protobuf_generator/src/lib.rs, rs/registry/canister/src/gen/ic_registry_canister.pb.v1.rs, rs/registry/transport/BUILD.bazel, rs/registry/transport/Cargo.toml, rs/registry/transport/proto/ic_registry_transport/pb/v1/transport.proto, rs/registry/transport/src/gen/ic_registry_transport.pb.v1.rs, rs/registry/transport/src/lib.rs
The motivating use case is vetKeys. However, knowledge of that feature is NOT required to understand this change (and future changes that will build on this).
The important thing to understand is that we want clients to be able to fetch "large" entries. Prior to this feature, this was not possible, due to the message size limit in the ICP (2 MiB). This feature will get around that by spreading the desired data over multiple canister calls.
The "large" value required by vetKeys is `CatchUpPackageContents` entries, which have keys of the form `catch_up_package_contents_${subnet_id}`.
This just introduces the new interface, which consists of various `HighCapacity*` types (e.g. there was already `RegistryValue`, but now there is also `HighCapacityRegistryValue`). Clients can begin programming …
=> feat(registry): Large response API.

Cargo.lock, rs/nervous_system/agent/BUILD.bazel, rs/nervous_system/agent/Cargo.toml, rs/nervous_system/agent/src/lib.rs, rs/nervous_system/agent/src/state_machine_impl.rs
This PR adds a test-only, state machine-based implementation for `ic-nervous-system-agent`. This is analogous to the existing PocketIC implementation. The state machine agent will be used in a follow-up PR to port SNS Governance tests to API types.
=> test(nervous_system): Add a test-only, state machine-based implementation for `ic-nervous-system-agent`

packages/pocket-ic/CHANGELOG.md, packages/pocket-ic/src/common/rest.rs, packages/pocket-ic/src/lib.rs, rs/pocket_ic_server/src/pocket_ic.rs, rs/pocket_ic_server/tests/test.rs, rs/state_machine_tests/src/lib.rs
This PR simplifies PocketIC API for mounting existing subnet states: no subnet ID is required anymore as it can be extracted from the provided subnet state.
=> chore(PocketIC): no subnet ID required when mounting existing subnet state

rs/ic_os/vsock/vsock_lib/src/host/agent.rs
The default timeout for HostOS upgrade downloads was 30 seconds. This increases it to 120 seconds. 
If an upgrade fails, nodes loop trying to upgrade, so bumping the download timeout does not come with much drawback.
=> chore(node): Increase HostOS upgrade download timeout

Cargo.lock, Cargo.toml, rs/nervous_system/agent/BUILD.bazel, rs/nervous_system/agent/Cargo.toml, rs/nervous_system/agent/src/lib.rs, rs/nervous_system/agent/src/state_machine_impl.rs, rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs, rs/sns/governance/api_helpers/BUILD.bazel, rs/sns/governance/api_helpers/Cargo.toml, rs/sns/governance/api_helpers/src/lib.rs
This PR adds a new crate under `rs/sns/governance/api_helpers`. This crate is dedicated to helper functions defined on top of the SNS Governance API, which are extensively used by SNS integration tests.
| [Next PR](https://github.com/dfinity/ic/pull/4428) >
=> feat(sns): Add a new crate for SNS Governance API helpers

rs/execution_environment/src/ic00_permissions.rs, rs/execution_environment/src/scheduler.rs, rs/execution_environment/tests/dts.rs
The current scheduler logic permits `advance_long_running_install_code` to complete a lengthy install process and then immediately initiate a new one within `drain_subnet_queues`.
This PR uses the `can_execute_subnet_msg` function to differentiate between heavy subnet messages, which must respect the round limit, and light subnet messages, which can be executed at any time.
Fixes RUN-386
=> fix: EXC-1992: Fix same round install code and draining queues

rs/nns/governance/canister/canister.rs, rs/nns/governance/src/timer_tasks/mod.rs, rs/nns/governance/src/timer_tasks/prune_following.rs, rs/nns/governance/unreleased_changelog.md
The timer task library has functionalities to collect metrics on the tasks, so refactoring tasks to use the library helps with observability.
* Define a PruneSomeFollowingTask as a RecurringSyncTask and schedule it in `schedule_tasks`
* Change the scheduling from `cansiter.rs` to `schedule_tasks`
=> refactor(nns): Refactor prune following to use timer task

rs/sns/governance/src/governance/assorted_governance_tests.rs, rs/sns/governance/src/governance/proposal_topics_tests.rs, rs/sns/governance/src/topics.rs, rs/sns/governance/src/types.rs, rs/sns/governance/unreleased_changelog.md
This PR implements the last phase of the new SNS proposal criticality feature that shifted the source of truth from a hard coded function to the topics configuration of a given SNS.
Recently added `SetTopcisForCustomProposals` proposals enabled categorizing custom proposals under a critical topic to become critical for the first time. However, now that the initial batches are categorized, its time to make the `SetTopcisForCustomProposals` proposal critical itself, as right now it is possible to circumvent proposal criticality by changing a proposal's topic without involving the grand majority of votes.
=> feat(sns): Move `SetTopcisForCustomProposals` under the `CriticalDappOperations` topic.

rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs, rs/sns/governance/canister/governance.did, rs/sns/governance/canister/governance_test.did, rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto, rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs, rs/sns/governance/src/governance.rs, rs/sns/governance/src/pb/conversions.rs, rs/sns/governance/src/types.rs, rs/sns/governance/unreleased_changelog.md, rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto, rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
This PR adds `Neuron.topic_followees` to support the upcoming SNS topics feature.
Additionally, this PR
- Adds a forward reference to NNS1-3676 in which we plan to implement `construct_topic_followees` for neurons newly created after a swap.
- Removes the unused API type `NeuronParameters`
- Factors out the `topic_id_to_api` function to support type mappings in rs/sns/governance/src/pb/conversions.rs
- Cleans up some code docs.
| [Next PR](https://github.com/dfinity/ic/pull/4442) >
=> feat(sns): Add `Neuron.topic_followees`

ci/scripts/rust-benchmarks.sh
This is a small cleanup of the `rust-benchmarks.sh` script to make it a bit more idiomatic & readable.
=> chore(IDX): simplify rust-benchmarks.sh

Cargo.lock, rs/pocket_ic_server/BUILD.bazel, rs/pocket_ic_server/Cargo.toml, rs/pocket_ic_server/src/pocket_ic.rs, rs/pocket_ic_server/src/state_api/routes.rs, rs/pocket_ic_server/src/state_api/state.rs, rs/pocket_ic_server/tests/test.rs, rs/state_machine_tests/src/lib.rs
This PR fixes PocketIC to support mounting (multiple) generic application subnets:
- do not distinguish the canister allocation range when deriving the subnet seed (as the separation is invisible when mounting a subnet state);
- use `StateManagerImpl` to derive the subnet ID and canister ranges from a given state;
- check that canister ranges are disjoint and fail instance creation with HTTP status code 400 if they are not disjoint.
=> fix(PocketIC): support mounting generic application subnets

.github/CODEOWNERS
When the file was renamed, codeowners was not updated.
=> chore(IDX): update codeowners

rs/tests/consensus/orchestrator/cup_compatibility_test.rs
Currently, we only test against the version deployed on the NNS subnet, which is the oldest deployed replica version.
With this change, we will also test against the newest deployed replica version, i.e., the one running on the `io67a` subnet
=> test: [CON-1144] modify `cup_compatibility_test` to also test the compatibility against the version deployed on the `io67a` subnet

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
Removing steps that are not required anymore (since we don't upload artifacts to local S3).
=> chore(IDX): build-ic cleanup

rs/tests/driver/src/driver/resource.rs
In `vm_spec_from_nested_node(...)` don't specify `alternate_template: Some(VmType::Production)` since that's the default.
Schedule Hourly: https://github.com/dfinity/ic/actions/runs/14043802093
=> chore(IDX): simplify vm_spec_from_nested_node

rs/nns/governance/canister/canister.rs, rs/nns/governance/unreleased_changelog.md
Increase the probability of failure from 70% to 90% for the deprecated _pb methods
=> chore(nns): Fail the pb methods in governance with 90%

packages/pocket-ic/CHANGELOG.md, packages/pocket-ic/src/lib.rs, packages/pocket-ic/src/nonblocking.rs, rs/pocket_ic_server/tests/test.rs
This PR makes the HTTP gateway IP address configurable when using the function `PocketIc::make_live_with_params` to create an HTTP gateway for a PocketIC instance.
The const `EXPECTED_SERVER_VERSION` is made public so that clients can download a matching server version based on this constant.
=> feat(PocketIC): PocketIc::make_live_with_params takes optional IP address

mainnet-canister-revisions.json, rs/ledger_suite/icp/tests/golden_nns_state.rs
In the golden tests I also updated the ID of the archive that has the capacity increased - since the 4th archive was spawned we will increase its capacity.
=> chore(ICP-Ledger): update index and archive mainnet canister revisions

packages/pocket-ic/src/common/rest.rs, rs/pocket_ic_server/src/pocket_ic.rs, rs/pocket_ic_server/tests/test.rs
This PR checks the canister ranges of a subnet with state loaded from disk against the canister ranges of the expected subnet kind (which must be contained in them) and against the canister ranges of other subnet kinds (which must be disjoint from them).
=> chore: check subnet kind canister ranges when loading subnet state

Cargo.lock, rs/nervous_system/BUILD.bazel, rs/nns/integration_tests/BUILD.bazel, rs/nns/integration_tests/Cargo.toml, rs/nns/integration_tests/src/registry_get_chunk.rs, rs/nns/test_utils/src/state_test_helpers.rs, rs/registry/canister/BUILD.bazel, rs/registry/canister/Cargo.toml, rs/registry/canister/canister/canister.rs, rs/registry/canister/src/registry.rs, rs/registry/canister/src/storage.rs
(Still) does NOT make the `get_chunk` method do anything USEFUL yet, because there is no way to actually add chunks yet, but that will come later.
This just sets up the back end/stable memory, and makes it readable via canister calls.
This does cause a minor behavior change though: instead of panic, get_chunk actually returns. However, it's always "not found" (for now). This is hardly worth mentioning in release notes.
Closes [NNS1-3680][jira]
[jira]: https://dfinity.atlassian.net/browse/NNS1-3680
[prev]: https://github.com/dfinity/ic/pull/4451
[NNS1-3680]: https://dfinity.atlassian.net/browse/NNS1-3680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(registry): Implemented get_chunk method.

.github/actions/bazel-test-all/action.yaml
This breaks on the macOS intel job that expects the variable to be expanded.
=> fix(IDX): don't quote bazel targets

rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2025_03_17.md, rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2025_03_17.md, rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2025_03_17.md
Proposals to upgrade the ckBTC ledger suite (archive, index and ledger) to  the latest version ([ledger-suite-icrc-2025-02-27](https://github.com/dfinity/ic/releases/tag/ledger-suite-icrc-2025-02-27)).
=> chore(ckbtc): Proposals to upgrade ledger suite 

rs/sns/cli/src/health.rs, rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs, rs/sns/governance/api/src/topics.rs
This PR adds SNS topic-related info for each SNS in the output of `sns health --json`. Not adding it to the default (human-readable) output, as the data is too large.
=> feat(sns_cli): Add topics info to json output

rs/sns/audit/src/lib.rs
This PR fixes the tool `//rs/sns/audit:sns-audit` by porting it to the new API for reading the Neuron's Fund investment controller (since the old API was obsolete).
=> fix(sns_audit): Use the new API for reading the Neuron's Fund investment controller

rs/tests/driver/src/driver/bootstrap.rs
The deployment-environment is used as an input to generate the node's IP address. Current node versions sanitize this deployment-environment input to be lowercase before deriving the IP address, but older versions do not. This change only effects the IP address generated by older IC image versions when run with a `testnet` deployment-environment.
=> chore(node): update deployment-environment argument

rs/pocket_ic_server/BUILD.bazel, rs/pocket_ic_server/tests/spec_test.rs, rs/tests/research/BUILD.bazel, rs/tests/research/spec_compliance/spec_compliance.rs
In https://github.com/dfinity/ic/pull/3508 we change the name of the underlying `ic-ref-test` binary, but keep the target the same. This breaks tests that have been depending on the binary name directly.
This change uses the target path to reference the binary, instead.
=> fix: Pass ic-ref-test directly

ic-os/components/selinux/ic-node/ic-node.fc, ic-os/components/selinux/ic-node/ic-node.te
EXC-1837
Create a separate selinux domain for the compiler sandbox and remove `execmem` permissions for the replica and canister sandbox domains. These are no longer needed with the on disk compilation cache and they pose a security risk because they allow processes to execute anonymous memory.
The compiler sandbox still has `execmem` permissions because `wasmtime` internally writes the compiled code to an executable region. But this is much safer than having `execmem` on the canister sandbox because the compiler sandbox doesn't execute any untrusted code (it just compiles untrusted code).
=> chore(EXC-1837): Remove execmem permissions

rs/config/src/execution_environment.rs
The flags will be used once the current no-op implementations in rs/execution_environment/src/execution_environment.rs are replaced by a real code path.
=> feat: [EXC-1941] Introduce feature flags for canister snapshot import and export

.github/actions/bazel-test-all/action.yaml
The `diff.sh` [requires](https://sourcegraph.com/github.com/dfinity/ic/-/blob/ci/bazel-scripts/diff.sh?L16-L18) the `MERGE_BASE_SHA` and `BRANCH_HEAD_SHA` to be set. Otherwise CI won't run any bazel tests. However these env vars were removed in [#4493](https://github.com/dfinity/ic/pull/4493/files#diff-15b4f1d6b5ce255f735126a9b2abd404d43f09db12771399482afef58cdfcfcbL60). This adds them back.
=> fix(IDX): make sure MERGE_BASE_SHA and BRANCH_HEAD_SHA are set

.github/workflows-source/release-testing.yml, .github/workflows-source/schedule-daily.yml, .github/workflows/release-testing.yml, .github/workflows/schedule-daily.yml
Introducing the [wrapper script](https://github.com/dfinity/ic/pull/4493) somehow broke the ability to parse multiple lines.
=> fix(IDX): move bazel commands to one line

rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
Add debugging information to an `assert!` in a flaky ICP Rosetta system test.
=> test(ICP_Rosetta): FI-1507: Add debugging information to assert in flaky test

.github/actions/bazel/action.yaml
Our *github-stats* service relies on having `-bep` suffix.
=> fix(IDX): bep artifact name

rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs, rs/config/src/embedders.rs
EXC-1993
Increase the maximum number of canister sandboxes. This allows us to keep more sandboxes hot which will improve latency and throughput.
=> feat(EXC-1993): Increase sandbox limit

rs/execution_environment/src/canister_manager/tests.rs, rs/execution_environment/src/execution/install_code/tests.rs, rs/execution_environment/src/execution_environment/tests/compilation.rs, rs/execution_environment/src/hypervisor.rs, rs/execution_environment/tests/dts.rs, rs/execution_environment/tests/hypervisor.rs
Skip charging a canister the full compilation amount if the canister's Wasm code is expected to be in the compilation cache.
Patch taken from
https://github.com/hpeebles/ic/commit/6a21822a1fc7ba49c83b0c8780a321f95c0230a7
=> feat(EXC): Skip compilation charge when Wasm is in cache

rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/pb/conversions.rs
To support the DisburseMaturity neuron command, the disbursements need to be stored.
Add `MaturityDisbursement` into the internal data model. The neuron API type isn't changed yet, nor is the stable structures representation.
=> feat(nns): Add MaturityDisbursement to neuron internal data model

rs/nns/governance/CHANGELOG.md, rs/nns/governance/src/governance.rs, rs/nns/governance/tests/governance.rs
The changes in this PR is already deployed as part of a security hotfix: 
* https://dashboard.internetcomputer.org/proposal/135955
* https://forum.dfinity.org/t/nns-updates-2025-03-25-nns-governance-security-hotfix/42978
Compared to the [original commit](https://github.com/dfinity/ic/commit/cbebf5d2d74bb97b616a8204df43d2ddfc3560aa), this PR also adds a CHANGELOG entry (not unreleased_changelog, since it's already released)
Manage Neuron proposals have low fees (0.01 ICP) and high limit for open proposals (100K). If they can be large (~2MiB), then it's easy to fill up the wasm memory with very low cost.
When validating the manage neuron proposals (`validate_manage_neuron_proposal`), simply disallow problematic commands:
- MakeProposal can be large since they can (and are intended to) …
=> fix(nns): Prevent large manage neuron proposals

rs/nns/governance/canister/canister.rs, rs/nns/governance/unreleased_changelog.md, rs/nns/nns.bzl
NNS Governance almost use candid everywhere, except for 2 _pb methods (being deprecated) and init. We would like to switch init to candid as well.
* Support candid parsing in init
=> feat(nns): Support initializing NNS Governance by candid

rs/tests/driver/src/driver/ic.rs
Currently, "fast" subnets have notary delay set to `500ms`. Since https://github.com/dfinity/ic/pull/1508 and https://github.com/dfinity/ic/pull/2050 the default notary delay is `300ms` which means that "fast" subnets are slower than "normal" (i.e. using the default settings) subnets
=> test: make fast subnets actually fast

.github/actions/bazel/action.yaml, .github/actions/bazel/bin/bazel
Github Stats service requires exact file names: `bazel-bep.pb.gpg` and `profile.json`.
=> fix(IDX): set expected names for bep and profile

rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/storage.rs, rs/nns/governance/src/storage/neurons.rs
To support the DisburseMaturity neuron command, the disbursements need to be stored in the stable structures.
Add a new `StableBTreeMap` for maturity disbursements, similar to recent ballots.
=> feat(nns): Store maturity disbursements in a StableBTreeMap

rs/nns/governance/src/governance/tla/mod.rs, rs/nns/governance/tla/Claim_Neuron.tla, rs/nns/governance/tla/Common.tla, rs/nns/governance/tla/Common_Apalache.tla, rs/nns/governance/tla/Disburse_Neuron.tla, rs/nns/governance/tla/Disburse_To_Neuron.tla, rs/nns/governance/tla/Merge_Neurons.tla, rs/nns/governance/tla/Refresh_Neuron.tla, rs/nns/governance/tla/Spawn_Neuron.tla, rs/nns/governance/tla/Spawn_Neurons.tla, rs/nns/governance/tla/Split_Neuron.tla, rs/nns/governance/tla/Split_Neuron_Apalache.tla
This makes the TLA model track the spawning state of neurons. Previously, the model interpreted "has maturity but no stake" as equal to spawning. This was done as to avoid storing more state and thus potentially improve the scalability of model checking, but this is not a correct invariant, and it led to the model finding an issue where the cached stake would be reset when merging neurons while spawning, but this was a false positive. The model can still be checked successfully with this addition (i.e., it doesn't really blow up the model checking time).
I also took the opportunity to clean up the models by factoring some common bits out.
=> fix(nns): Track the spawning state in the TLA model

rs/config/src/embedders.rs, rs/embedders/src/wasm_executor.rs, rs/embedders/src/wasm_utils.rs, rs/embedders/src/wasm_utils/instrumentation.rs, rs/embedders/src/wasm_utils/system_api_replacements.rs, rs/embedders/src/wasmtime_embedder.rs, rs/embedders/src/wasmtime_embedder/system_api.rs, rs/embedders/tests/instrumentation.rs, rs/embedders/tests/wasmtime_embedder.rs, rs/execution_environment/src/execution/call_or_task/tests.rs, rs/execution_environment/tests/dts.rs, rs/interfaces/src/execution_environment.rs, rs/system_api/src/lib.rs, rs/system_api/src/stable_memory.rs, rs/system_api/tests/system_api.rs, rs/test_utilities/execution_environment/src/lib.rs
This PR removes the `wasm_native_stable_memory` flag as the feature has been implemented since a long time ago. This allows to clean up a lot of unused code and simplify some of the logic across embedders/execution environment/system api.
=> chore: Remove wasm_native_stable_memory feature flag

Cargo.lock, rs/sns/governance/BUILD.bazel, rs/sns/governance/Cargo.toml, rs/sns/governance/protobuf_generator/src/lib.rs, rs/sns/governance/src/following.rs, rs/sns/governance/src/following/tests.rs, rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs, rs/sns/governance/src/governance.rs, rs/sns/governance/src/lib.rs, rs/sns/governance/src/proposal.rs, rs/sns/governance/src/topics.rs, rs/sns/governance/src/types.rs
This PR adds validation for the recently added neuron `SetFollowing` command (which is still disabled). The validation is based on global topic following invariants, but does not yet take into potential account existing topic-based following that a neuron might have; that will be added in a follow-up PR.
| [Next PR](https://github.com/dfinity/ic/pull/4563) >
=> feat(sns): neuron `SetFollowing` command is validated in isolation 

ci/scripts/run-build-ic.sh
This ensures both full build and partial builds in `run-build-ic.sh` are consistent and both use `--no-release`. This does not affect builds on "protected" branches like `master` and releases.
=> fix(IDX): use --no-release for build-ic on PRs

rs/nns/governance/src/governance.rs, rs/nns/governance/unreleased_changelog.md
Now that neurons are all moved to stable memory, we should be able to increase the limit to 500K. It can be increased further after the followee index is dropped, but since it's already at 390K (close to the current limit of 400K), we should bump the limit first.
=> feat(nns): Bump neuron limit to 500K

Cargo.lock, rs/execution_environment/tests/dts.rs, rs/execution_environment/tests/execution_test.rs, rs/nns/integration_tests/src/cycles_minting_canister.rs, rs/replica_tests/tests/canister_lifecycle.rs, rs/tests/execution/compute_allocation_test.rs, rs/tests/execution/general_execution_tests/canister_lifecycle.rs, rs/tests/execution/max_number_of_canisters_test.rs, rs/tests/nns/sns/lib/src/sns_deployment.rs, rs/universal_canister/lib/BUILD.bazel, rs/universal_canister/lib/Cargo.toml, rs/universal_canister/lib/src/lib.rs, rs/universal_canister/lib/src/management.rs
Remove universal canister's dependency on internal crates to make it easier to use by non-ic repos.
=> chore: simplify rust dependencies of the universal canister

rs/crypto/benches/idkg.rs, rs/crypto/benches/ni_dkg.rs, rs/crypto/benches/tecdsa.rs, rs/crypto/benches/threshold_sig.rs, rs/crypto/benches/tschnorr.rs
Adapts the crypto benchmarks from 28 nodes to 34 nodes, because all large subnets (Fiduciary, II, SNS) now [have 34 nodes](https://dashboard.internetcomputer.org/subnets?sort=desc-upNodes).
=> chore(crypto): CRP-2636 adapt benchmarks to 34 instead 28 nodes

.github/actions/bazel-test-all/action.yaml, .github/actions/bazel/action.yaml, .github/workflows/schedule-rust-bench.yml
This inlines the `BUILDBUDDY_LINKS` value in the bazel action instead of providing it as an input. This ensure it is used everywhere and simplify the workflow definitions.
=> fix(IDX): set BUILDBUDDY_LINKS for all jobs

.github/actions/bazel-test-all/action.yaml
This makes commits on PRs labeled with `CI_ALL_BAZEL_TARGETS` act like a release by building all targets and uploading build artifacts.
=> feat(IDX): upload all artifacts with CI_ALL_BAZEL_TARGETS

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs, rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/canister/governance.did, rs/nns/governance/canister/governance_test.did, rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/benches.rs, rs/nns/governance/src/governance/tests/mod.rs, rs/nns/governance/src/heap_governance_data.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/benches.rs, rs/nns/governance/src/neuron_store/neuron_store_tests.rs, rs/nns/governance/src/pb/conversions.rs, rs/nns/governance/unreleased_changelog.md
The `USE_STABLE_MEMORY_FOLLOWING_INDEX` flag has been set to true on Feb. 3, released with the proposal 135063. In this PR, the feature flag is removed while being replaced to `true`, and because of that, the `topic_followee_index` is no longer read, and it is also cleaned up in this PR.
* `USE_STABLE_MEMORY_FOLLOWING_INDEX` is replaced with `true`, and code paths simplified (removing dead code, etc.)
* Benchmarks using `temporarily_disable_stable_memory_following_index` are removed
* Calls to `temporarily_enable_stable_memory_following_index` are removed since it's no longer necessary
* The init argument no longer has `topic_followee_index`, and the candid files are updated accordingly
* Remove `topic_followee_index` from the canister state, along with code to backup, restore, and …
=> refactor(nns): Remove topic_followee_index and USE_STABLE_MEMORY_FOLLOWING_INDEX

.vscode/settings.json, rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs, rs/sns/governance/canister/governance.did, rs/sns/governance/canister/governance_test.did, rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto, rs/sns/governance/src/follower_index.rs, rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs, rs/sns/governance/src/governance.rs, rs/sns/governance/src/lib.rs
This PR implements a dynamic index for the topic-based follower index relation. The index will be used to implement the new, topic-based following. Note that the neurons themselves store the "follows" relation which is the inverse of "is-followed-by".
This PR also fixes a small mistake in the new API (switching from `uint64` to `int32` indices). This is safe because the API corresponds to a command that has not yet been enabled in production.
=> feat(sns): Implement topic following index

rs/state_layout/src/state_layout.rs, rs/types/management_canister_types/src/lib.rs
https://github.com/dfinity/ic/pull/4431/ introduced a bug when converting `pb::CanisterSnapshotBits` to `CanisterSnapshotBits`. This PR fixes that. `//rs/ledger_suite/icrc1:icrc_ledger_suite_integration_golden_state_upgrade_downgrade_test_u256` succeeds now. 
Upgrade/downgrade test in a follow-up.
=> fix: Use default value for SnapshotSource instead of failing. 

rs/tests/driver/src/driver/resource.rs
What
===
Increase the vCPUs (and memory) of the host VM in the nested system-tests (`//rs/tests/nested:...`)  to match the number of vCPUs of its nested guest VM. So from 6 to 64.
Why
===
The nested system-tests are very flaky. By SSHing into the host VMs we noticed that their nested GuestOS VMs are often running into soft CPU lockups. See the following log from a host VM:
```
$ cat /var/log/libvirt/qemu/guestos-serial.log:
...
[ 1145.028103] watchdog: BUG: soft lockup - CPU#1 stuck for 1066s! [cpuhp/1:212] 
[ 1145.028103] Modules linked in: 
[ 1145.028103] CPU: 1 UID: 0 PID: 212 Comm: cpuhp/1 Tainted: G L 6.11.0-21-generic #21~24.04.1-Ubuntu 
[ 1145.028103] Tainted: [L]=SOFTLOCKUP 
[ 1145.028103] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 2024.02-2ubuntu0.1 10/25/2024 
[ …
```
=> test(NODE-1579): nested systests: increase resources for host VM

rs/tests/networking/canister_http_correctness_test.rs
This change adds in the context of http outcalls systems correctness tests, tests that focus on the response headers limitations. These tests are being migrated from our Haskell spec tests into Rust.
=> test(consensus): add https outcalls compliance tests for response headers

rs/sns/cli/dfx.json, rs/sns/dfx.json
Those dfx.json files are used by the dfx sns extension, and the `index.did` has been deleted in favor of `index-ng.did`. Therefore, the dfx nns extension wouldn't be able to advance the ic commit pass the point where `index.did` was deleted.
Replace `index/index.did` with `index-ng/index-ng.did`
=> chore(nns): Use the correct icrc1 index candid file

rs/tests/consensus/backup/common.rs, rs/tests/consensus/upgrade/downgrade_app_subnet_test.rs, rs/tests/consensus/upgrade/upgrade_app_subnet_test.rs, rs/tests/consensus/upgrade/upgrade_downgrade_app_subnet_test.rs
This PR enables the the VetKD keys in the upgrade / downgrade and backup tests.
=> test(CON-1472): Enable VetKD in upgrade/downgrade & backup tests

rs/execution_environment/src/lib.rs, rs/http_endpoints/xnet/src/lib.rs, rs/http_endpoints/xnet/src/tests.rs, rs/messaging/src/message_routing.rs, rs/messaging/src/message_routing/tests.rs, rs/messaging/src/scheduling/valid_set_rule.rs, rs/replica/src/setup_ic_stack.rs, rs/replica_tests/src/lib.rs
Where used a lot (such as e.g. the `RegistryClient` within `BatchProcessorImpl`), it is likely more efficient to use concrete types (via `impl trait` or generic types) instead of dynamic types.
I had an earlier version of this change that tried to replace all `dyn trait` uses in Message Routing with generics, but the resulting types became exceedingly complex; and these were mostly pointers that were used once per round (e.g. to call `process_batch()`).
=> refactor: Use generics and `impl trait` instead of `dyn trait`

.github/workflows/ci-pr-title-validation.yml
Having `pull_request_target` event allows this workflow to run on PRs from a forked repo.
=> chore(IDX): pr title validaton event

ci/src/mainnet_revisions/mainnet_revisions.py
[NODE-1578](https://dfinity.atlassian.net/browse/NODE-1578)
mainnet_revisions.py now updates the mainnet-icos-version.json hostos version and update_img_hash fields
[NODE-1578]: https://dfinity.atlassian.net/browse/NODE-1578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: extend mainnet_revisions.py to update hostos version

Cargo.lock, rs/execution_environment/BUILD.bazel, rs/execution_environment/Cargo.toml, rs/execution_environment/src/canister_manager.rs
EXC-2011
Instead of parsing the entire Wasm module to check if a canister is using 64-bit mode, we can just parse the memory section. This can speed up the check by 5x in some cases.
=> fix(EXC-2011): Speed up wasm64 check

rs/embedders/benches/compilation.rs, rs/execution_environment/benches/lib/src/common.rs, rs/execution_environment/benches/system_api/execute_query.rs, rs/execution_environment/benches/system_api/execute_update.rs, rs/execution_environment/benches/wasm_instructions/main.rs
This reduces the default runtime to speed up running the benchmarks in CI.
=> chore: EXC: Reduce number of benchmark samples

bin/run-all-fuzzers.sh
This reverts commit 539d2fb4907a1f1c7027aa1422f495a295e62a2d.
=> revert: Bump --bes_timeout flag for sandbox_fuzzing builds to 600s (#4649)

.github/workflows/schedule-rust-bench.yml
* //rs/embedders:compilation_bench runs for ~5 min, adds 28 benchmarks
* //rs/embedders:stable_memory_bench runs for ~10 min, adds 14 benchmarks
* //rs/execution_environment:execute_inspect_message_bench runs for ~2 min, adds 8 benchmarks
* //rs/execution_environment:execute_query_bench runs for ~2 min, adds 6 benchmarks
* //rs/execution_environment:execute_update_bench runs for ~23 min, adds 116 benchmarks
* //rs/execution_environment:wasm_instructions_bench runs for ~80 min, adds 1704 benchmarks
=> perf: EXC: Run more execution benchmarks periodically

rs/orchestrator/BUILD.bazel
In another PR I'm adding a log message to the orchstrator's `main.rs` and noticed that the reported crate name is wrong:
`Apr 04 11:39:55 uwt2y-k7rvs-mrmr7-dkc6f-nq3yi-snjri-al2ez-hofgy-fvbed-2ofrn-nae orchestrator[2040]: {"log_entry":{"level":"INFO","utc_time":"2025-04-04T11:39:55.869Z","message":"Shutting down orchestrator...","crate_":"ic_state_tool","module":"ic_state_tool","line":21,"node_id":"","subnet_id":""}}
`
This PR fixes it
=> fix: rename the orchestrator binary crate from `ic_state_tool` to `orchestrator`

.github/actions/bazel-test-all/action.yaml, .github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml, ci/scripts/run-build-ic.sh
This extracts the CI build config (whether to diff the targets, to run a release build, etc) into a new job so that it is centralized and so that other jobs (`bazel-test-all`, `build-ic`) can depend on it.
This also adds a job summary so that the build config can be checked easily.
=> fix(IDX): Extract CI build config

rs/ledger_suite/common/ledger_canister_core/src/ledger.rs
Return the archived ranges in order.
=> fix(Ledger): FI-1689: Return the archived ranges in order

.github/actions/bazel/bin/bazel, .github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml, bazel/conf/.bazelrc.build, bazel/conf/.bazelrc.internal
This moves most of the `:ci` Bazel config out of the .bazelrc and into the CI jobs that require it. This streamlines the config to make it more portable and ensure the options are only set where required.
=> chore(IDX): move opts out of `--config=ci`

rs/tests/nested/BUILD.bazel, rs/tests/nested/src/lib.rs
The Farm hosts in the dm1 DC run:
Ubuntu-24.04, libvirt-10.0.0 and QEMU-8.2.2 while the other (older) Farm hosts run 
Ubuntu-20.04, libvirt-6.6.0  and QEMU-5.0.0.
If the host VM in the nested system-tests is allocated to these older hosts the nested guest VM often runs into soft CPU lockups. So we temporarily require that this test is hosted in dm1 until the other Farm hosts are upgraded to Ubuntu 24.04.
=> chore(NODE-1579): fix flakiness in nested systests by only running them in dm1

rs/nns/governance/canister/canister.rs, rs/nns/governance/unreleased_changelog.md
The `_pb` method in the NNS Governance are deprecated. This PR makes them always fail.
Make the failure probability 100% for the `_pb` methods. We could simply panic. However, that will require us to remove branches of code, which might make it more difficult to rollback if needed if subsequent code is relying on the removal.
=> feat(nns): Always panic when pb methods are called

rs/embedders/benches/compilation.rs, rs/embedders/benches/embedders_bench/src/lib.rs, rs/embedders/benches/heap.rs, rs/embedders/benches/stable_memory.rs, rs/execution_environment/benches/system_api/execute_inspect_message.rs, rs/execution_environment/benches/system_api/execute_query.rs, rs/execution_environment/benches/system_api/execute_update.rs, rs/execution_environment/benches/wasm_instructions/main.rs
This PR makes all Criterion benchmark groups unique, without functional changes.
Unique groups facilitate querying results.
=> chore: EXC-2009: Make benchmark groups unique

rs/prep/src/internet_computer.rs
Add the dc entries to the initial registry
Prior to this change, the ic-prep could generate initial node operators and node providers by looking into a `meta.json` definition.
However, the NO generated out of that definition had an empty value for the DC.
Furthermore, the DC entries were missing altogether.
This change allows for extra configuration inside the meta.json
```json
"dc_A": {
"node_allowance" : 3,
"node_provider": "provider_keys/np.der",
"region": "us-west-1",
"owner": "example_owner",
"gps": [37.7749, -122.4194]
}
```
On UTOPIA setup, the ic-prep is used to generate initial config. The dre tool now shows the correct config.
```bash
dre --nns-urls http://localhost:8050 registry | jq .dcs
2025-04-08T06:50:12.373Z INFO  dre > Running version …
```
=> test: ic-prep Add the data center records to the registry

.github/workflows/slack-workflow-run.yml
Some of the tests are flaky and therefore alerts are unnecessary. Since this is run once an hour it will be retried automatically if it fails.
=> chore(IDX): remove alerts for ic version workflow

rs/tests/nested/src/lib.rs
The `//rs/tests/nested:hostos_upgrade_...` tests are currently flaky because in order to detect if the host upgraded post upgrade they just sleep for 180s. If the host did not upgrade and reboot within those 180 seconds the test would fail because the version would still equal the pre-upgrade version.
This commit fixes that by explicitly waiting for the host to reboot by first retrieving its boot ID pre upgrade and then waiting until it changes post upgrade.
Schedule Hourly: https://github.com/dfinity/ic/actions/runs/14336926419 ✅ .
=> test(IDX): explicitly check for reboot in nested upgrade tests

.github/workflows/ci-pr-title-validation.yml
We don't need to trigger workflow for triggering title validation on every commit.
=> chore(IDX): don't validate on synchronize

rs/rosetta-api/icrc1/BUILD.bazel
Add more resources for the `icrc_multitoken_rosetta_system` test, since it has been flaky, and the errors seem to indicate this could be due to not enough resources available to run the test.
=> test(Multitoken_Rosetta): FI-1699: Add more resources for icrc_multitoken_rosetta_system test

rs/crypto/benches/vetkd.rs
Adapts the vetKD benchmarks so that they don't only run for subnet sizes of `[13, 34]`, but for `[1, 4, 13, 34, 40]`, which is the same set we use for tECDSA, tSchnorr, and iDKG.
=> feat(crypto): CRP-2733 run vetKD benches for more subnet sizes

rs/registry/canister/src/registry.rs
Because there is already `prost::Message::encode_to_vec` for that.
=> refactor(registry): Get rid of `pb_encode` function.

rs/config/src/embedders.rs
Switch from best-effort calls only being enabled on application subnets to best-effort calls enabled everywhere (including system subnets and NNS).
Best-effort calls have been enabled on selected application subnets for 4+ weeks now; and on all other application subnets for 2+ weeks. Metrics don't show anything out of the ordinary (such as e.g. leaked resources) and the feedback from canister developers is also positive in terms of correct behavior. The vast majority of the underlying code (message pooling, references, including dangling ones) has been running for many months as the basis of guaranteed response calls.
In conclusion, we believe it is safe to enable best-effort calls on system subnets.
=> feat(MR): [MR-649] Enable best-effort calls everywhere

rs/nns/governance/src/storage.rs
Keeping logical grouping for memory ids might have people be tempted to define the ids non-consecutively, which can lead to bugs where memory ids are reused. Having logical grouping isn't that beneficial for defining ids, since the logical relationship between the memories can still be seen where they are used.
* Keep memory ids sorted
* Remove logical grouping
=> chore(nns): Keep memory ids sorted

rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/voting_power_snapshots.rs, rs/nns/governance/src/governance/voting_power_snapshots_tests.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/voting_power.rs
To prevent a sudden takeover of the NNS in the event of some party gaining illegitimate voting power (e.g. a bug in Governance, ICP Ledger, etc.), we aim at reverting the voting power to an earlier snapshot, so that neurons don't gain voting power immediately if a spike is detected.
There are 3 PRs to achieve the above-mentioned goal:
- (current PR) Define VotingPowerSnapshot and a collection of snapshots
- (#4405) Add a timer task to record snapshots periodically
- (#4406) Use the previous snapshot if a voting power spike is detected
* Define a VotingPowerSnapshot to represent the voting power calculated at a certain point of time
* One key decision is to also snapshot the voting power of each neuron, which then can be used to create ballots later, if (in an extremely unlikely event) a …
=> feat(nns): Define VotingPowerSnapshot and a collection of snapshots

Cargo.lock, rs/embedders/BUILD.bazel, rs/embedders/Cargo.toml, rs/embedders/tests/common/mod.rs, rs/embedders/tests/sandbox_safe_system_state.rs, rs/embedders/tests/system_api.rs, rs/embedders/tests/system_api_tracking.rs
When `//rs/system_api` got moved under `//rs/embedders` (commit 9662ae2), the integration tests in `//rs/system_api/tests` accidentally ended up under `//rs/embedders/src` and thus became inactive. Move them to `//rs/embedders/tests` and tweak the build files to revive them.
=> test: Resurrect `system_api` tests

rs/tests/cross_chain/BUILD.bazel
Test is broken since https://github.com/dfinity/ic/pull/4764. 
Previous image is not available anymore and test needs to be fixed to work with the new image.
=> chore(IDX): temporarily disable ic_xc_cketh_test

Cargo.Bazel.Fuzzing.json.lock, Cargo.Bazel.Fuzzing.toml.lock, Cargo.Bazel.json.lock, Cargo.Bazel.toml.lock, Cargo.lock, Cargo.toml, bazel/external_crates.bzl
(cherry picked from commit 2fbdb88dc8fe2918cf3e313de6eeb358f0e3b345)
=> chore: bump crossbeam-channel to 0.5.15 (#4767)

rs/ledger_suite/tests/sm-tests/src/in_memory_ledger.rs, rs/ledger_suite/tests/sm-tests/src/in_memory_ledger/tests.rs
Fix the handling of expired allowances in the `InMemoryLedger`. If the `expires_at` value of an allowance is in the past, it should be treated as an expired allowance.
=> test(Ledger): FI-1691: Correct handling of expired allowances in InMemoryLedger

Cargo.lock, rs/rosetta-api/icp/BUILD.bazel, rs/rosetta-api/icp/Cargo.toml, rs/rosetta-api/icp/src/rosetta_server.rs
One recent source of ICP Rosetta test flakiness is the fact that the file with the port number where Rosetta is listening is not written atomically. E.g., in [this test](https://github.com/dfinity/ic/blob/8db45d0ad972479dd99a80720dc98c2401dbb48a/rs/rosetta-api/icp/tests/integration_tests/src/lib.rs#L106-L107), the client tries to read the port number from the file, but panics on line 107 with a `Expected port in port file: ParseIntError { kind: Empty }` error. This is because ICP Rosetta creates the port file, and then writes to it, and the client reads the file before anything has been written to it. This PR proposes to make the port file writing atomic in [the same way that it is currently done in the ICRC Rosetta](https://github.com/dfinity/ic/blob/8db45d0ad972479dd99a80720dc98c2401dbb4 …
=> fix(ICP_Rosetta): FI-1507: Write ICP Rosetta port file atomically

Cargo.lock, hs/spec_compliance/src/IC/Test/Spec/CanisterHistory.hs, rs/config/src/execution_environment.rs, rs/execution_environment/src/canister_manager/tests.rs, rs/execution_environment/src/canister_settings.rs, rs/execution_environment/src/execution/call_or_task/tests.rs, rs/execution_environment/src/execution/response/tests.rs, rs/execution_environment/src/execution_environment/tests/canister_task.rs, rs/execution_environment/src/query_handler/query_cache/tests.rs, rs/execution_environment/tests/dts.rs, rs/execution_environment/tests/execution_test.rs, rs/execution_environment/tests/hypervisor.rs, rs/execution_environment/tests/subnet_size_test.rs, rs/ledger_suite/tests/sm-tests/src/lib.rs, rs/nns/integration_tests/src/cycles_minting_canister.rs, rs/nns/integration_tests/src/update_canister_settings.rs, rs/sns/integration_tests/BUILD.bazel, rs/sns/integration_tests/Cargo.toml, rs/sns/integration_tests/src/manage_dapp_canister_settings.rs, rs/test_utilities/execution_environment/src/lib.rs, rs/tests/execution/general_execution_tests/canister_lifecycle.rs
This reverts commit 2c64388af33d97e64254d68955807b048e7a0286. After user feedback that this breaking change affects certain workflows, the decision is to revert it and instead introduce some warnings in dfx when users try to set very low freezing threshold values.
=> chore: Revert "feat: Introduce low bound for canister's freezing threshold (#4401)"

rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Since the migration to stable structures is complete, it shall again be possible to roll back to the previous ledger version. This PR proposes to remove the parameters and functionality that allowed for failed downgrades to not fail the test - since the downgrades tested here should now always be possible, any downgrade failure should also cause the test to fail.
=> test(ICRC_Ledger): Remove migration-related checks in ICRC ledger suite golden state test

MODULE.bazel, rs/tests/cross_chain/BUILD.bazel, rs/tests/cross_chain/ic_xc_cketh_test.rs
Use foundry [v0.3.0](https://github.com/foundry-rs/foundry/pkgs/container/foundry/391862899?tag=v0.3.0) to re-enable the system test `ic_xc_cketh_test`. 
That test was disabled with #4775 due to a failed attempt to upgrade foundry to the last version in #4764 that was blocking the CI pipeline.
=> fix: re-enable `ic_xc_cketh_test`

rs/nns/governance/src/lib.rs, rs/nns/governance/src/maturity_disbursement_index.rs, rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/neuron_store_tests.rs, rs/nns/governance/src/storage.rs, rs/nns/governance/src/storage/neuron_indexes.rs
To support finalizing maturity disbursement (asynchronous, as it's 7 days after initiation), a timer task is needed to find all the neurons eligible for finalization, as well as computing the next finalization timestamp. An index from finalization timestamp to neuron ids will help avoid unnecessary full neuron scans.
* Define and implement `MaturityDisbursementIndex`
* Add it to `indexes_mut` behind feature flag so that updating neurons will cause the index to be updated
* Export `governance_maturity_disbursement_index_len` metric behind feature flag
* Validate the index map behind feature flag
All 3 places modifying existing behaviors are behind feature flag: (1) updating indexes when updating neuron (2) encoding metric for size of the index (3) validating the index btree map
=> feat(nns): Add an index for maturity disbursement based on finalization timestamp

rs/nns/governance/src/governance.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron_lock.rs, rs/nns/governance/src/neuron_lock_tests.rs
The `LedgerUpdateLock` contains a `*mut Governance` which requires `unsafe` in order to unlock, and it is only compatible with the `governance_mut()` access pattern where `unsafe` is also used for accessing the canister state. As we are moving towards accessing the canister state through `LocalKey<RefCell<Governance>>`, a new access pattern for neuron locks is needed.
* Move `LedgerUpdateLock` and the locking/unlocking mechanisms to `neuron_lock.rs`
* Implement `NeuronAsyncLock` to be compatible with `&'static LocalKey<RefCell<Governance>>`
* Implement locking and unlocking mechanisms similar to `LedgerUpdateLock`
=> feat(nns): Define NeuronAsyncLock to be compatible with safer access pattern to global state

rs/nns/governance/src/governance.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/voting_power.rs, rs/nns/governance/src/storage.rs, rs/nns/governance/src/timer_tasks/mod.rs, rs/nns/governance/src/timer_tasks/snapshot_voting_power.rs, rs/nns/governance/unreleased_changelog.md
To prevent a sudden takeover of the NNS in the event of some party gaining illegitimate voting power (e.g. a bug in Governance, ICP Ledger, etc.), we aim at disabling the early adoption of NNS proposals if the voting power has a spike, which should give the network more time to react and recover in such cases.
There are 3 PRs to achieve the above-mentioned goal:
- (#4404) Define VotingPowerSnapshot and a collection of snapshots
- (current PR) Add a timer task to record snapshots periodically
- (#4798) Use the previous snapshot if a voting power spike is detected
* Refactor the existing function `create_ballots_for_standard_proposal` to be used for snapshots too
* Define how to store the snapshots in stable storage
* Define a timer task for taking snapshots
=> feat(nns): Add a timer task to perform voting power snapshots

rs/nns/governance/canister/canister.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/neuron/types/tests.rs, rs/nns/governance/src/neuron_store/metrics/tests.rs, rs/nns/governance/src/timer_tasks/mod.rs, rs/nns/integration_tests/src/neuron_following.rs
The "Periodic Confirmation of Following/Voting Power" feature started having its full effect at the beginning of April, and no reason to recall it has emerged (knock on wood). DFINITY has looked at the practical consequences of this, and it does not seem like any interventions are needed. Therefore, now is a good time to get rid of these flags.
As with all such clean ups, it is not super important that this go in soon. If there are any objections to merging this now, then we can definitely delay.
Closes [NNS1-3601].
[NNS1-3601]: https://dfinity.atlassian.net/browse/NNS1-3601
=> chore(nns): Delete flags related to periodic confirmation of following.

rs/execution_environment/BUILD.bazel
The P90 duration of the [//rs/execution_environment:execution_environment_misc_integration_tests/dts](https://sourcegraph.com/github.com/dfinity/ic/-/blob/rs/execution_environment/tests/dts.rs) test [jumped up](https://superset.idx.dfinity.network/explore/?slice_id=108) starting in March 2024 and reached above the maximum of 5 minutes. We can't reproduce this locally so it's likely related to a load issue on CI.
To have more control over the resource usage of this test we move it to its own dedicated bazel target ` //rs/execution_environment:dts_test`. We don't change any CPU reservation or `RUST_TEST_THREADS` settings yet such that we can gather some data on the baseline durations.
=> test(IDX): move //rs/execution_environment:execution_environment_misc_integration_tests/dts to its own target

ic-os/components/hostos-scripts/monitoring/custom-metrics.sh
Output:
```
hostos_config_version{version="1.1.0"} 1
```
=> chore: [NODE-1580] export hostos config as metric

rs/execution_environment/fuzz/BUILD.bazel, rs/execution_environment/fuzz/fuzz_targets/execute_ic_wasm.rs, rs/execution_environment/fuzz/fuzz_targets/execute_system_api.rs, rs/test_utilities/execution_environment/src/lib.rs
The current fuzzers don't leverage any additional features provided by `StateMachine` framework that `ExecutionTest` doesn't offer and we have very significant difference between the two in terms of fuzzing performance.
=> chore(fuzzing): Switch to ExecutionTest framework from StateMachine

Cargo.lock, rs/ledger_suite/icrc1/ledger/BUILD.bazel, rs/ledger_suite/icrc1/ledger/Cargo.toml, rs/ledger_suite/icrc1/ledger/src/benches/mod.rs, rs/ledger_suite/icrc1/ledger/src/main.rs, rs/ledger_suite/icrc1/ledger/tests/tests.rs
Recompute the certified data in the post upgrade of the ICRC ledger.
The certified data is currently only updated during ledger init, and after a transaction. This means that, without this fix, with the ICRC-3 certificate update that fixes the non-compliant labels, the ledger will return an invalid certificate until it process its first transaction after the canister upgrade.
=> fix(ICRC_Ledger): FI-1709: Recompute ICRC ledger certified data in post upgrade

rs/rust_canisters/random_traffic_test/src/main.rs
This counter is supposed to protect against no-op heartbeats due to silent rollbacks. For checks that this be non-zero, the counter should not be included for heartbeats that didn't try to make any calls.
=> fix: Make the Heartbeat Counter on the Random Traffic Canister increment only for substantial Heartbeats.

rs/state_manager/src/lib.rs, rs/state_manager/tests/state_manager.rs
During checkpointing, we switch to the files in the new checkpoint to back data structures like pagemaps and wasm binaries. This approach should also apply to the wasm binaries of canister snapshots and this PR fixes it.
=> fix: switch to checkpoint for wasm binaries in canister snapshots

rs/canister_sandbox/BUILD.bazel, rs/canister_sandbox/Cargo.toml, rs/canister_sandbox/bin/test_controller.rs, rs/canister_sandbox/bin/test_sandbox.rs, rs/canister_sandbox/src/protocol/sbxsvc.rs, rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs, rs/canister_sandbox/src/sandbox_client_stub.rs, rs/canister_sandbox/src/sandbox_manager.rs, rs/canister_sandbox/src/sandbox_server.rs, rs/canister_sandbox/src/sandbox_service.rs
EXC-1802
There were two copies of the sandbox `OpenWasm` and `CreateExecutionState` RPC calls to handle the in-memory and on-disk compilation caches. Now that we've switched to the on-disk version we can remove the extra version.
=> chore(EXC-1802): Remove old sandbox rpc calls

rs/nns/integration_tests/src/neuron_following.rs, rs/nns/integration_tests/src/reinstall_and_upgrade.rs, rs/nns/test_utils/src/itest_helpers.rs, rs/nns/test_utils/src/state_test_helpers.rs
We are moving towards using candid as the only API interface in the NNS Governance. Currently, the NNS Governance supports initializing with either of candid or protobuf. This PR switches tests to use candid.
=> refactor(nns): Initialize NNS Governance with candid

rs/nns/governance/src/lib.rs, rs/nns/governance/unreleased_changelog.md, rs/nns/nns.bzl
The condition to turn on disburse maturity was incorrectly copied from `DISABLE_NF_FUND_PROPOSALS` (which was on at the time). This PR correctly turns it back off.
=> fix(nns): Turn off disburse maturity which was incorrectly turned on

rs/registry/canister/api/src/lib.rs, rs/registry/canister/canister/canister.rs, rs/registry/canister/canister/registry.did, rs/registry/canister/src/get_node_providers_monthly_xdr_rewards.rs, rs/registry/canister/src/mutations/node_management/common.rs, rs/registry/canister/unreleased_changelog.md
This allows the function in Registry that calculates rewards to take a particular version.
This is needed for fully testing historical data against the Registry and the new Node Rewards canister to ensure parity.
=> feat(registry): Node Rewards can target a specific version

rs/consensus/idkg/src/payload_verifier.rs
This PR fixes a an issue that was uncovered when testing to migrate the registry to the new`reshare_chain_key` endpoint.
The validation function still decodes the response and was not adapted to handle both possible decodings.
=> fix(consnesus): Fix reshare chain key validation

rs/tests/consensus/orchestrator/rotate_ecdsa_idkg_key_test.rs, rs/tests/consensus/subnet_recovery/common.rs, rs/tests/consensus/subnet_recovery/sr_nns_failover_nodes_test.rs, rs/tests/consensus/subnet_recovery/sr_nns_same_nodes_test.rs
Using only one node may hide subtle bugs, for instance in payload validation. This PR increases the subnet size of all subnets in recovery tests to at least 4 nodes.
=> test: Increase subnet size to 4 nodes in recovery tests

rs/tests/consensus/tecdsa/utils/src/lib.rs
This PR increases the number of retries when trying to acquire a chain key signature in the system tests.
Certain tests activate the chain key signatures just before trying to get a signature. At that time, the routing of the IC might not be ready yet. Currently, we retry only 5 times, with a 2 second backoff. This can lead to flackyness.
=> test(consensus): Increase number of retries of get signature in system tests

Cargo.lock, rs/ic_os/vsock/vsock_lib/BUILD.bazel, rs/ic_os/vsock/vsock_lib/Cargo.toml, rs/ic_os/vsock/vsock_lib/src/host/agent.rs
This reverts commit 943d3bf19c888185650a53075e1f5ee6157662f5 because it breaks the `//rs/tests/nested:hostos_upgrade_smoke_test`.
Schedule Hourly: https://github.com/dfinity/ic/actions/runs/14490678316 ✅ .
=> fix: revert "chore: unifying downloading logic (#4805)"

Cargo.lock, rs/nns/integration_tests/src/node_provider_remuneration_migration.rs, rs/node_rewards/canister/BUILD.bazel, rs/node_rewards/canister/Cargo.toml, rs/node_rewards/canister/api/src/monthly_rewards.rs, rs/node_rewards/canister/src/main.rs, rs/node_rewards/canister/tests/get_node_providers_monthly_xdr_rewards.rs, rs/node_rewards/canister/unreleased_changelog.md
Limit callers to Node Reward canister to only be governance
Reduce unnecessary traffic to the canister and avoid making the API publicly utilized and hard to evolve during the next phase of changes.
=> feat(node_rewards): limit caller to governance for xdr rewards

rs/drun/src/message.rs, rs/execution_environment/src/query_handler/query_cache.rs, rs/execution_environment/src/query_handler/query_context.rs, rs/execution_environment/src/query_handler/query_scheduler.rs, rs/execution_environment/tests/hypervisor.rs, rs/https_outcalls/client/src/client.rs, rs/test_utilities/execution_environment/src/lib.rs, rs/types/types/src/messages/http.rs, rs/types/types/src/messages/query.rs, rs/validator/ingress_message/tests/validate_request.rs
This PR
- renames `QuerySource::Anonymous` to `QuerySource::System` since the caller of such a query is the management canister (rather than the anonymous principal) and queries with such a source are triggered by the protocol (system) for canister http outcalls;
- introduces a function `QuerySource::user_id` that is used to avoid code duplication.
=> chore: refactor QuerySource

ic-os/components/hostos-scripts/monitoring/monitor-power.sh
Deployed to bare-metal test machine and scraped the metrics:
```
power_average_watts 143
power_instantaneous_watts 143
power_sampling_period_seconds 1
```
The issue was that when the timer runs, the output of the IPMI tool is slightly different from when it is run manually. Manually, it includes "AM"/"PM" with the time. Hence, the offset by 1 in the `awk` expression.
=> fix: update parsing of power measurements via IPMI tool

third_party/lmdb/repository.bzl
We started running into [the following error](https://github.com/dfinity/ic/actions/runs/14573057064/job/40914741275#step:4:71):
```
WARNING: Download from 
https://git.openldap.org/openldap/openldap/-/archive/55fd54dae6f90080b770dbc9dbcee5044976b7bf/openldap-55fd54dae6f90080b770dbc9dbcee5044976b7bf.zip 
failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException 
Checksum was 9f8e4f1fa8c0996043ef35db0d0d52b9cbd314572263cf2e5961912b0410fa72 
but wanted 657307ba28abbf6d926b24d568098a34de5888e165d1cb0c434ef6c9f2ec392d
```
which means the content of the URL changed and the hash has to be updated.
=> fix: correct the hash of liblmdb

rs/https_outcalls/adapter/src/rpc_server.rs
This change is a simple error message change that aims to help external developers when facing issues due to lacking IPv4 access on application subnets. A sample error is the one pasted below:
```
Call failed:
Canister: y22am-qyaaa-aaaab-qbmtq-cai
Method: get_icp_usd_exchange (update)
"Request ID": "7a5763d80514e605c16c5088b3ae773fe220c8ea54770bd34bc1bc06397b0372"
"Error code": "IC0406"
"Reject code": "4"
"Reject message": "Connecting to asdf.com failed: Failed to directly connect: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", Os { code: 101, kind: NetworkUnreachable, message: \"Network is unreachable\" }))"
```
It is a known issue that IPv4 network access is guaranteed only for system subnets. The reasons this change just adds verbosity to the error …
=> chore(consensus): add note on exclusive IPv6 guarantee on NetworkUnreachable

rs/types/types/src/canister_http.rs
This change comes in the context of migrating haskell spec tests on https_outcalls into rust.
A prior https://github.com/dfinity/ic/pull/4601 change has been made integrating these specifications as system tests. The assumption is that there is also value in adding this specifications also as unit tests.
The method validate_http_headers_and_body is used for validating both request and response headers and body, and since both request and response headers share the same validation logic, we can re-use the same test cases for both request and response headers.
=> test(consensus): add unit tests for validate_http_headers_and_body

rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
When an NNS canister does not have an upgrade arg, the proposals are prepared using empty blobs (`vec![]`). Therefore the tests should be too.
=> test(nns): Use empty blob for upgrade args in golden nns tests

rs/bitcoin/ckbtc/minter/BUILD.bazel, rs/bitcoin/ckbtc/minter/src/updates/tests.rs
XC-241: test ckBTC minter needs to call check_transaction more than once
Add a test to make sure the minter will call check_transaction again when it returns NotEnoughCycles.
=> test(ckbtc): Add a test case when check_transaction returns NotEnoughCycles

Cargo.lock, Cargo.toml
`bazel/external_crates.bzl` [specifies](https://github.com/dfinity/ic/blob/master/bazel/external_crates.bzl#L391) that the `cloudflare` crate should use revision `8b011d170d9d61eaad77bb9645371f6219285104`. However `Cargo.toml` was using a different hash. These files should match.
=> fix: match cloudflare's crate rev in Cargo.toml with external_crates.bzl

rs/execution_environment/src/query_handler/query_context.rs
This PR reduces the instruction threshold for logging canister http transform functions from 100M to 10M instructions. According to existing [metrics](https://grafana.mainnet.dfinity.network/d/execution-metrics/execution-metrics?var-heatmap_period=$__auto&from=now-24h&to=now&timezone=utc&var-datasource=PE62C54679EC3C073&var-ic=mercury&var-ic_subnet=$__all&var-instance=$__all&var-node_instance=$__all&viewPanel=panel-121), this should not result in an excessive amount of logs being produced since the majority of non-replicated queries take 5-10M instructions.
=> chore: log canister http transform taking more than 10M instructions

rs/https_outcalls/client/src/client.rs, rs/https_outcalls/client/src/lib.rs, rs/pocket_ic_server/src/pocket_ic.rs
This PR logs canister http transform function result size if it exceeds the value of `max_response_size_bytes`.
=> chore: log transform function result size if max_response_size_bytes exceeded

rs/replay/src/backup.rs, rs/replay/src/player.rs
Currently we don’t verify the state hash in a CUP if the CUP’s height is below the latest state’s height: [click](https://sourcegraph.com/github.com/dfinity/ic@23abac5891de0ebde5c49c0fe91a1aab39c6241f/-/blob/rs/replay/src/player.rs?L1197-1202).
When replaying blocks for the backup purposes, we start with a checkpoint height `h`, we execute blocks until we reach the next CUP height `h'`, and continue executing blocks until we reach the smallest height `h'' >= h'` which is explicitly finalized: [click](https://sourcegraph.com/github.com/dfinity/ic@23abac5891de0ebde5c49c0fe91a1aab39c6241f/-/blob/rs/replay/src/backup.rs?L460-468). Only then we verify the CUP: [click](https://sourcegraph.com/github.com/dfinity/ic@23abac5891de0ebde5c49c0fe91a1aab39c6241f/-/blob/rs/replay/src/player.rs?L1092-1104 …
=> fix(ic-backup): [CON-1493] Only replay blocks until a CUP height during a backup

rs/tests/ckbtc/ckbtc_minter_basics_test.rs, rs/tests/ckbtc/ckbtc_minter_batching.rs, rs/tests/ckbtc/ckbtc_minter_checker.rs, rs/tests/ckbtc/ckbtc_minter_deposit_and_withdrawal.rs, rs/tests/ckbtc/ckbtc_minter_retrieve_btc.rs, rs/tests/ckbtc/ckbtc_minter_update_balance.rs, rs/tests/ckbtc/src/lib.rs
XC-243
In ckBTC system tests, install and run the minter and bitcoin checker canisters on an application subnet so that it better matches what is in production.
=> test(ckbtc): run minter and checker on app subnet in sys tests

ic-os/bootloader/grub.cfg, ic-os/hostos/grub.cfg, ic-os/setupos/grub.cfg
[NODE-1587](https://dfinity.atlassian.net/browse/NODE-1587)
Added video=1024x768 to the kernel boot parameters to fix a regression in Linux 6.11 that causes the iDRAC console to show "no signal". This forces the framebuffer to stay within a resolution supported by iDRAC's virtual console when no physical monitor is attached.
[NODE-1587]: https://dfinity.atlassian.net/browse/NODE-1587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(node): fix iDRAC console 'no signal' regression

rs/registry/canister/BUILD.bazel
Therefore, stop telling bazel to look there.
=> refactor(registry): There is no `gen` directory in `registry/canister`.

rs/registry/canister/src/registry.rs
The legacy format has been deprecated for years; moreover, it has not been used in years (assuming my deductions from the code are correct).
The reason I'm doing this now is that this makes it easier for me to make some other changes (to support larger registry entries).
=> refactor(registry): Drop support for legacy registry upgrade format.

Cargo.lock, rs/registry/canister/chunkify/BUILD.bazel, rs/registry/canister/chunkify/Cargo.toml, rs/registry/canister/chunkify/src/lib.rs, rs/registry/canister/chunkify/src/tests.rs
These are not yet used, but will be soon within the registry canister itself (not by clients).
Closes [NNS1-3682].
[NNS1-3682]: https://dfinity.atlassian.net/browse/NNS1-3682
=> feat(registry): Added `dechunkify` and `decode_high_capacity_registry_value`.

Cargo.lock, rs/types/wasm_types/BUILD.bazel, rs/types/wasm_types/Cargo.toml, rs/types/wasm_types/src/lib.rs
This PR adds a `write` method to the `CanisterModule` type, such that this binary data can be uploaded and written in slices via the snapshot data upload endpoints. 
Using the write method may make the `CanisterModule` invalid. But this type seems to have no validity guarantees in existing code: E.g., [here](https://sourcegraph.com/github.com/dfinity/ic@mwe/module_write/-/blob/rs/execution_environment/src/canister_manager/types.rs?L213), it's composed from user-provided wasm chunks. Also, the canister module will only be compiled when put in the compilation cache, and only at that point does the replica know if the module is valid. 
When the user is done uploading slices, they may load the snapshot. At this point, the snapshot's content, including the `CanisterModule`, must be validated …
=> feat: Make CanisterModule writable for snapshot upload

rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/disburse_maturity.rs, rs/nns/governance/src/governance/disburse_maturity_tests.rs, rs/nns/governance/src/governance/ledger_helper.rs, rs/nns/governance/src/maturity_disbursement_index.rs, rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/neuron_lock.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/neuron_store_tests.rs, rs/nns/governance/src/pb/conversions.rs, rs/nns/governance/src/timer_tasks/finalize_maturity_disbursements.rs, rs/nns/governance/src/timer_tasks/mod.rs, rs/nns/integration_tests/src/governance_neurons.rs, rs/nns/test_utils/src/state_test_helpers.rs
For the DisburseMaturity feature, the initiation of the disbursement has been implemented. This PR implements the finalization of the disbursement where ICPs are minted from maturity.
* Define a timer task to finalize the maturity disbursement and scheduling for the next finalization
* Implement the finalization logic:
* Validation
* Acquire neuron lock
* Pop existing disbursement
* Mint ICP
* Error handling
Note that the timer task is behind a feature flag, and the timer task is the entry point. In other words, this PR does not change the production behavior.
=> feat(nns): Process the finalization of maturity disbursements

rs/node_rewards/canister/src/storage.rs, rs/node_rewards/canister/unreleased_changelog.md
The `StableBTreeMap::new` initializes the BTreeMap as an empty map, we'd like the map to be preserved over upgrades.
* Replace `StableBTreeMap::new` with `StableBTreeMap::init`
=> fix(node_rewards): Use StableBTreeMap::init instead of ::new

rs/nns/governance/src/governance/voting_power_snapshots.rs, rs/nns/governance/unreleased_changelog.md
The `StableBTreeMap::new` initializes the BTreeMap as an empty map, we'd like the map to be preserved over upgrades.
* Replace `StableBTreeMap::new` with `StableBTreeMap::init`
=> fix(nns): Use StableBTreeMap::init instead of ::new for voting power snapshots

rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/src/governance/benches.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron_data_validation.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/benches.rs, rs/nns/governance/src/neuron_store/metrics.rs, rs/nns/governance/src/neuron_store/metrics/tests.rs, rs/nns/governance/src/neuron_store/neuron_store_tests.rs
All neurons are migrated to stable memory ,and the feature `allow_active_neurons_in_stable_memory` has been turned on for a long time. There is no reason to turn it back off.
* Remove `allow_active_neurons_in_stable_memory`
* Remove all branches where `allow_active_neurons_in_stable_memory` is false, and simplify code afterwards
* Remove all `temporarily_enable_allow_active_neurons_in_stable_memory` calls since it does nothing.
* Remove all tests/benchmarks with `temporarily_disable_allow_active_neurons_in_stable_memory` since the condition is no longer possible.
=> refactor(nns): Clean up allow_active_neurons_in_stable_memory

rs/nns/governance/src/governance/benches.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/benches.rs, rs/nns/governance/src/neuron_store/metrics/tests.rs, rs/nns/governance/src/neuron_store/neuron_store_tests.rs
The neuron migration to stable memory is completed. We want to remove the feature flags while preserving the behavior of flag being turned on.
* Remove `migrate_active_neurons_to_stable_memory`
* Remove all branches where `migrate_active_neurons_to_stable_memory` is false, and simplify code afterwards
=> refactor(nns): Clean up migrate_active_neurons_to_stable_memory

.github/workflows-source/schedule-daily.yml, .github/workflows/schedule-daily.yml, ic-os/dev-tools/bare_metal_deployment/deploy.py
For now, the test just makes sure that the `power_average_watts` metric is available. We can add more metrics (if they are critical) in the future.
Just replace `USERNAME` and `MACHINE` and you are good to go:
```
bazel run \
//ic-os/setupos/envs/dev:launch_bare_metal -- \
--file_share_username USERNAME \
--config_path $(realpath ./ic-os/dev-tools/bare_metal_deployment/MACHINEyaml) \
--csv_filename $(realpath ./MACHINE.csv) \
--check_hostos_metrics
```
=> chore: [NODE-1591] add power metrics test

rs/nns/governance/canister/canister.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/neuron_store.rs
The neuron migration to stable memory is completed, therefore the timer task to move neurons between the 2 storage is no longer needed.
* Stop scheduling the task (remove `schedule_adjust_neurons_storage`)
* Delete dead code
=> refactor(nns): Clean up the timer task AdjustNeuronStorage

rs/registry/canister/chunkify/src/lib.rs, rs/registry/canister/chunkify/src/tests.rs
This one will be used in an imminent PR.
[prev]: https://github.com/dfinity/ic/pull/4870
=> feat(registry): Added (another) way to dechunkify a (more abstract) high-capacity object.

rs/nns/sns-wasm/tests/add_wasm.rs, rs/nns/sns-wasm/tests/common/mod.rs, rs/nns/sns-wasm/tests/deploy_new_sns.rs, rs/nns/sns-wasm/tests/get_deployed_sns_by_proposal_id.rs, rs/nns/sns-wasm/tests/update_sns_subnet_list.rs, rs/nns/sns-wasm/tests/upgrade_sns_instance.rs, rs/nns/test_utils/src/state_test_helpers.rs, rs/sns/integration_tests/src/sns_treasury.rs
This PR drops the function `reduce_state_machine_logging_unless_env_set` meant to reduce logging output in tests by setting the environment variable `RUST_LOG`.
The motivation for this change is that we want to deprecate `RUST_LOG` in StateMachine tests:
- setting environment variables in tests affects *all* tests running in the same process while `StateMachineBuilder::with_log_level` can (and should) be used to tune the log level for a *single* test;
- `RUST_LOG` can sometimes be set implicitly (e.g., in a test environment) resulting in unexpected log verbosity of StateMachine tests.
This PR has currently no effect on log output verbosity: the affected tests produce the same amount of output as validated by running
```
bazel test //rs/nns/sns-wasm:sns-wasm_integration_test …
```
=> chore: drop reduce_state_machine_logging_unless_env_set

.github/actions/bazel/action.yaml
This ensures a CSV containing execlogs is always uploaded, even if no execlogs were generated. This prevents errors in the build determinism checks that do expect a CSV to be present, even if potentially empty.
=> fix(IDX): always upload execlogs

rs/nns/integration_tests/src/registry_get_chunk.rs, rs/registry/canister/src/registry.rs, rs/registry/canister/src/storage.rs, rs/registry/canister/src/storage/tests.rs, rs/registry/transport/src/high_capacity.rs
In a recent PR, this high-capacity type was used to ENCODE changelog entries. This PR "completes that circle", so to speak.
Doing this made me realize that I made a mistake in an earlier change.
Nothing that `from_serializable_form` calls (whether direct or indirect) should chunkify. Whereas, earlier, I made `changelog_insert` do chunkification (and `changelog_insert` is indirectly called by `from_serialized_form`). This change fixes that by moving chunkification "up" the call graph to `apply_mutations` (which is not called by `from_serializable_form`, not even indirectly). This actually turns out to be the right "choke point" where chunkification should be applied.
Fortunately, the new buggy `changelog_insert` behavior (i.e. chunkification) was never enabled in release builds (feature …
=> feat(registry): During upgrade, decodes using HighCapacityRegistryAtomicMutateRequest.

Cargo.lock, rs/pocket_ic_server/BUILD.bazel, rs/pocket_ic_server/Cargo.toml, rs/pocket_ic_server/src/main.rs
This PR increases the maximum number of open files in PocketIC. The motivation for this change is to prevent errors due to too many open files when dealing with a lot of canisters.
=> chore(PocketIC): increase maximum number of open files

ic-os/components/hostos-scripts/generate-guestos-config/generate-guestos-config.service
https://dfinity.atlassian.net/browse/NODE-1592
The value of `vm_nr_of_vcpus` is set in update-config. But because the `vm_nr_of_vcpus` field was added after the last rollout, the update-config service must rerun to write the new-_new_ config version to disk. 
Without this new ordering, the update-config service runs after generate-guestos-config.service, causing generate-guestos.sh to fail as it didn’t have the default value for vm_nr_of_vcpus.
=> fix(node): HostOS upgrade failure

Cargo.lock, rs/rosetta-api/icrc1/BUILD.bazel, rs/rosetta-api/icrc1/CHANGELOG.md, rs/rosetta-api/icrc1/Cargo.toml, rs/rosetta-api/icrc1/src/common/constants.rs
This pull request updates the `ic-icrc-rosetta` project to version `1.2.1` and includes several improvements, bug fixes, and updates to maintain consistency across the codebase. Below are the most important changes:
* Updated the `ROSETTA_VERSION` to `1.2.1` in multiple files to reflect the new release:
- `BUILD.bazel` (`MACRO_DEV_DEPENDENCIES`)
- `Cargo.toml` (`version` field)
- `constants.rs` (`ROSETTA_VERSION` constant)
* Added a new section for version `1.2.1` in `CHANGELOG.md` with the following highlights:
- Added token-specific metrics for multi-token instances to distinguish between tokens ([#4790](https://github.com/dfinity/ic/pull/4790)).
- Increased the sync thread watchdog timeout from 10 to 60 seconds to handle IC instability better …
=> feat(icrc-rosetta): add icrc rosetta release 1.2.1

rs/nns/integration_tests/src/lifeline.rs, rs/nns/integration_tests/src/neuron_following.rs, rs/nns/integration_tests/src/neuron_voting.rs, rs/nns/integration_tests/src/subnet_rental_canister.rs, rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs, rs/nns/test_utils/src/state_test_helpers.rs
The previous approach of minting u64::MAX/4 ICPs within the golden NNS state tests will stop working if we are able to detect a voting power spike and use previous ballots in such an event. Therefore, the only way to pass for testing upgrades would be to vote with existing neurons.
* Create versions of `nns_cast_vote` and `manage_neuron` without panics
* Create "super powerful neuron" with a smaller (but more realistic) number of tokens
* Vote on upgrade proposals with well-known public neurons
=> test(nns): Within the golden state test, vote on proposals by impersonating well-known neurons

rs/nervous_system/agent/src/helpers/nns.rs, rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs, rs/nns/governance/api/src/pb.rs, rs/nns/governance/tests/governance.rs, rs/nns/integration_tests/src/create_service_nervous_system.rs, rs/nns/integration_tests/src/governance_neurons.rs, rs/nns/integration_tests/src/governance_time_warp.rs, rs/nns/integration_tests/src/neuron_following.rs, rs/nns/integration_tests/src/neuron_voting.rs, rs/nns/test_utils/src/state_test_helpers.rs, rs/rosetta-api/icp/src/request_handler.rs, rs/sns/cli/src/lib.rs, rs/tests/driver/src/nns.rs, rs/tests/nns/nns_token_balance_test.rs
NNS Governance API does not use protobuf anymore (in a previous [PR](https://github.com/dfinity/ic/pull/4843). Therefore, every `prost:*` can be removed from the API types file.
* Replace `prost::Message` with `Debug, Default`
* Replace `prost::OneOf` with `Debug`
* Remove `comparable::Comparable`, `compare_default` and `self_describing` since they are needed for some tests which are based on internal types.
* Remove all `#[prost(...)]` on fields
* Remove a helper function `get_all_proposal_ids` since it's not used
* Change from enum to i32 for some tests
* This might seem "inconvenient" or "less readable", but note that it correctly reflects how the API is difficult to use right now, as the meanings of those i32's are not part of the API
* `DisburseMaturityResponse::amount_disbursed_e8s` …
=> refactor(nns): Remove all prost annotations on the NNS Governance API

rs/tests/nested/BUILD.bazel, rs/tests/nested/src/lib.rs, rs/tests/system_tests.bzl
`if [ -n "RUN_SCRIPT_HOSTOS_UPDATE_IMG_TEST" ]; then` was always resolving to true. 
Fixing the bug fixes the `hostos_upgrade_from_mainnet_to_mainnet` manual target
=> fix(node): hostos_upgrade_from_mainnet_to_mainnet

rs/nns/governance/src/maturity_disbursement_index.rs, rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/neuron_data_validation.rs, rs/nns/governance/src/storage/neurons.rs
The maturity disbursement index is used to find the maturity disbursement that are ready for finalization, as well as scheduling the timer to run at the correct time. We want to make sure the index is correct, by adding validation that the index is equivalent to the primary data as much as possible.
* Implement `MaturityDisbursementIndexValidator`
* Run the validator when `is_disburse_maturity_enabled`
=> feat(nns): Validate the maturity disbursement index

rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs, rs/nns/governance/canister/governance.did, rs/nns/governance/canister/governance_test.did, rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/neuron/types/tests.rs, rs/nns/governance/src/pb/conversions.rs, rs/nns/governance/tests/governance.rs, rs/nns/integration_tests/src/governance_neurons.rs
As part of the disburse maturity functionality, after a disbursement is initiated, the user should be able to check on the disbursement in progress.
* Define the maturity_disbursement_in_progress field within the neuron on the API layer.
* Convert from internal type to the API type for the disbursement
* Update .did files
* Update the state machine test to check disbursements through get_full_neuron
=> feat(nns): Expose maturity disbursements as part of neuron

rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
There was an instance where an NNS Governance upgrade without SNS-W upgrade causing backward compatibility issue, where a field stops getting populated within the CreateServiceNervousSystem payload, while the corresponding change in SNS-W to validate this field is not released. On a high level, there is some message passing between NNS Governance and SNS-W for CSNS proposal execution, and we want to make sure the message passing is not broken if either of them is upgraded without each other.
=> test(sns): Check that NNS Governance and SNS-W can be upgraded without each other

rs/nns/governance/src/lib.rs, rs/nns/governance/unreleased_changelog.md
Enable fetching rewards from node rewards canister instead of registry.
This unblocks further changes to node provider rewards calculations.
=> feat(nns): Enable node rewards from new canister

rs/execution_environment/BUILD.bazel
The `//rs/execution_environment:dts_test` has a P90 of over ~8 minutes. See its [durations chart](https://superset.idx.dfinity.network/explore/?slice_id=112).
Note that [by default rust's libtest will use the amount of concurrency available on the hardware](https://doc.rust-lang.org/rustc/tests/index.html#--test-threads-num_threads) which in our case is 64 threads since our runners have 64 cores. One hypothesis why this test is slow is that it starts running all its 38 tests in parallel thereby hogging the CPUs who will also be doing a lot of other work of the whole `bazel test //...` invocation. 
So we try to optimise the test by both:
* reducing the number of tests executed in parallel to just 4 and by 
* increasing the number of CPUs that will be available to this test from 1 to 4.
=> test: tune the slow //rs/execution_environment:dts_test

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
This ensures the Bazel setup is working on macos -- even on PRs -- without triggering an actual build.
=> feat(IDX): run minimal macos intel build on PRs

rs/registry/canister/canister/canister.rs, rs/registry/canister/canister/registry.did, rs/registry/canister/src/mutations/do_migrate_canisters.rs, rs/registry/canister/src/mutations/mod.rs, rs/registry/canister/unreleased_changelog.md
This adds a new endpoint that does nothing, but implements the canister migrations spec
=> feat(registry): Add canister migrations endpoint with no functionality

Cargo.lock, rs/rosetta-api/icp/BUILD.bazel, rs/rosetta-api/icp/CHANGELOG.md, rs/rosetta-api/icp/Cargo.toml
This pull request updates the `ic-rosetta-api` package to version 2.1.4, introducing new features, improvements, and fixes. The most notable changes include enhancements to metrics, architectural migrations, and bug fixes to improve reliability and observability.
* Updated `ROSETTA_VERSION` and `Cargo.toml` to reflect the new version `2.1.4`. [[1]](diffhunk://#diff-7c8bbf3cd57fe84e5547fbbe9524a822dd0b2009b12e565f3d502f7e696aefdbL100-R100) [[2]](diffhunk://#diff-b6a799ae48d36b40e8c0d283cce4a7f6c0dfa04b51471ae5c23bde38ed36297aL3-R3)
* Added a detailed changelog entry for version 2.1.4:
- **Added**: Token-specific metrics and a new PocketIC Time type for testing. ([#4790](https://github.com/dfinity/ic/pull/4790), [#4864](https://github.com/dfinity/ic/pull/4864))
- **Changed**: Migrated to …
=> feat(icp-rosetta): add icp rosetta release 2.1.4

rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Skip the FuelEV SNS in the ICRC golden state test since the ledger index canister ran out of cycles and was uninstalled.
=> test(ICRC_Ledger): FI-1719: Skip FuelEV in ICRC SNS golden state test

rs/messaging/src/message_routing.rs, rs/messaging/src/state_machine.rs, rs/replicated_state/src/canister_state/queues.rs, rs/replicated_state/src/canister_state/queues/message_pool.rs, rs/replicated_state/src/canister_state/queues/tests.rs, rs/replicated_state/src/canister_state/system_state.rs, rs/replicated_state/src/lib.rs, rs/replicated_state/src/replicated_state.rs, rs/replicated_state/tests/replicated_state.rs
Add `kind` / `context` / `class` labels as appropriate to timed out and and shed message metrics, to better track where and when messages are being dropped.
=> feat: [MR-606] Break out dropped message metrics by kind / context / class

rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/neuron_store/neuron_store_tests.rs
When a neuron has maturity disbursement in progress, it should not be considered "empty" when listing neurons, since it still has some form of maturity in it.
=> feat(nns): Consider neurons with maturity disbursements as non empty

rs/nns/governance/src/governance/voting_power_snapshots.rs, rs/nns/governance/src/governance/voting_power_snapshots_tests.rs, rs/nns/governance/src/timer_tasks/snapshot_voting_power.rs
When there is a voting power spike detected in the snapshots themselves, we don't want to add new snapshots since they would make the voting power look normal after some time.
* Refactor the voting power spike detection logic into `totals_entry_with_minimum_total_potential_voting_power_if_voting_power_spiked`
* Early return on in the `SnapshotVotingPowerTask::execute` when `is_latest_snapshot_a_spike`.
=> feat(nns): Stop recording new snapshots when there is a spike

rs/execution_environment/src/metrics.rs, rs/messaging/tests/call_tree_tests.rs
Use the same `class` label values ("best-effort" and "guaranteed response") across MR and Execution metrics.
=> chore: Unify message class label values

rs/crypto/internal/crypto_lib/bls12_381/vetkd/tests/tests.rs
Adapts the integration tests of the vetKD crypto library (`ic-crypto-internal-bls12-381-vetkd`) to use
* the size of the subnet on which the vetKD produciton key will be deployed (34 nodes)
* the threshold that is used in production (high threshold: 2/3 of 34, i.e., 23)
This is to address an informational finding of an internal security review.
=> fix(crypto): use production subnet size and threshold in vetKD crypto library tests

Cargo.lock, rs/tests/consensus/tecdsa/utils/src/lib.rs, rs/tests/consensus/vetkd/BUILD.bazel, rs/tests/consensus/vetkd/Cargo.toml, rs/tests/consensus/vetkd/vetkd_key_life_cycle_test.rs
Enhances the vetKD system test so that many key properties of the vetKD API are tested that were not tested before. For example:
* Two executions of the vetKD protocol must yield the same (decrypted) vetKey for the same input/context/keyID/canister combination, even if the key derivation happens on another subnet.
* Two executions of the vetKD protocol must yield different (decrypted) vetKeys if any of input, context, keyID, canister are different.
=> feat(crypto): CRP-2777 enhance vetKD key lifecycle system test

MODULE.bazel, bazel/os_info.bzl, publish/binaries/BUILD.bazel
This adds a new repository rule that reads the OS info and exports it as `os_info`. By doing this we can be more flexible in how we provide the `remote_subdir` when uploading artifacts and are not limited to rules only, but can also use a macro. This is part of the work for extracting the upload step from the build itself.
=> chore(IDX): add os_info repository rule

rs/nns/governance/src/neuron_data_validation.rs, rs/nns/governance/src/neuron_store.rs
As heap_neurons no longer exist (migrated to stable memory), we can stop reading them in validation.
* Stop checking heap neurons for cardinalities.
* Stop iterating through heap neurons when validating neurons in batch
* Clean up `NeuronStore::heap_neurons_iter()`
=> refactor(nns): Stop validating heap neurons

rs/registry/canister/src/mutations/do_migrate_canisters.rs, rs/registry/canister/src/mutations/routing_table.rs, rs/registry/canister/unreleased_changelog.md, rs/registry/routing_table/src/lib.rs
This update adds functionality tothe migrate_canisters endpoint to update the routing table when it is called.
This functionality is still restricted to the Governance canister, so that it cannot be called outside of a testing environment.
It will eventually be available to support the canister migrations feature.
=> feat(registry): migrate_canisters endpoint updates routing table

rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/src/neuron_store/benches.rs
Registering neuron ballots are done through `NeuronStore::register_recent_neuron_ballot` and neither the heap (obsolete) and stable memory path use `with_neuron_mut`. Therefore the benchmark was not realistic.
Stop modifying recent ballots in the `with_neuron_mut` benchmarks.
=> chore(nns): Stop registering ballots in with_neuron_mut

ic-os/components/defs.bzl, ic-os/defs.bzl, toolchains/sysimage/BUILD.bazel, toolchains/sysimage/build_container_base_image.py, toolchains/sysimage/build_container_filesystem_tar.py, toolchains/sysimage/build_fat32_image.py, toolchains/sysimage/build_lvm_image.py, toolchains/sysimage/build_vfat_image.py, toolchains/sysimage/toolchain.bzl, toolchains/sysimage/utils.py
All sysimage tools now use the same format. Each is a bazel rule wrapped around a `py_binary`, with as much consistency as possible.
=> chore: Consolidate and standardize sysimage tools

toolchains/sysimage/toolchain.bzl
This fixes the following error:
```
$ bazel build //ic-os/setupos/envs/prod:disk.img --config=bes
INFO: Invocation ID: e57da46c-660c-466f-bb15-b03bfa8d18da
INFO: Streaming build results to: https://dash.idx.dfinity.network/invocation/e57da46c-660c-466f-bb15-b03bfa8d18da
ERROR: /ic/ic-os/setupos/envs/prod/BUILD.bazel:10:11: in disk_image_no_tar rule //ic-os/setupos/envs/prod:disk.img:
Traceback (most recent call last):
File "/ic/toolchains/sysimage/toolchain.bzl", line 466, column 27, in _disk_image_no_tar_impl
_run_with_icos_wrapper(
File "/ic/toolchains/sysimage/toolchain.bzl", line 15, column 20, in _run_with_icos_wrapper
ctx.actions.run(
Error in run: at index 0 of inputs, got element of type list, want File
```
=> fix: //ic-os/.../:disk.img targets

packages/ic-vetkd-utils/src/lib.rs, packages/ic-vetkd-utils/tests/tests.rs
For one this avoids confusion with the other value called context in the larger VetKey protocol, which has nothing to do with this parameter.  Calling it `identity` captures its meaning within the context of the IBE, and the doc comments are ammended to explain the connection between the `identity` parameter in IBE and the `input` parameter in VetKey derivation.
=> chore(crypto): CRP-2788 Rename IBE parameter from context to identity

rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs, rs/nns/test_utils/src/state_test_helpers.rs
* Use the same mechanism as voting through the upgrade proposals
* Add comments to explain why voting with well-known public neurons instead of minting more ICPs.
=> test(nns): Fix the golden NNS state test by voting the ManageNetworkEconomics proposal with well-known public neurons

ci/container/build-ic.sh, ic-os/guestos/envs/prod/BUILD.bazel, ic-os/hostos/envs/prod/BUILD.bazel, ic-os/setupos/envs/prod/BUILD.bazel, publish/binaries/BUILD.bazel, publish/canisters/BUILD.bazel, publish/defs.bzl
This better represents what the rule does (creates a bundle of artifacts that can then be e.g. uploaded).
=> chore(IDX): rename checksum_rule to artifact_bundle

rs/consensus/dkg/src/lib.rs, rs/consensus/dkg/src/utils.rs, rs/consensus/tests/framework/mod.rs, rs/consensus/vetkd/src/test_utils.rs, rs/registry/canister/src/invariants/crypto.rs, rs/registry/canister/src/invariants/crypto/tests.rs, rs/types/management_canister_types/src/lib.rs
VetKd does not use pre-signatures, and the corresponding config parameter is ignored. This PR adapts a registry invariant to allow chain keys that do not require pre-signatures to be configured with zero pre-signatures to create in advance.
Once this change is rolled out to the mainnet registry, we can update system tests to configure vetKD keys with zero pre-signatures.
=> feat: CRP-2618 Allow zero `pre_signatures_to_create_in_advance` in vetKD `ChainKeyConfig`

rs/tests/driver/src/driver/farm.rs
The `//rs/tests/nested:...` tests currently upload large files which sometimes cause Farm to run out of disk space. I would like to know how much is being uploaded so this logs the file size before uploading which looks like:
```
$ bazel test //rs/tests/nested:registration --config=systest
...
2025-05-08 14:36:56.779 INFO[setup:rs/tests/driver/src/driver/farm.rs:166:0] Uploading file: config_disk.img.zst of size 41060 bytes ...
...
2025-05-08 14:36:56.830 INFO[setup:rs/tests/driver/src/driver/farm.rs:166:0] Uploading file: config_disk.img.zst of size 43713 bytes ...
...
2025-05-08 14:38:58.843 INFO[setup:rs/tests/driver/src/driver/farm.rs:166:0] Uploading file: config.img.zst of size 2370645843 bytes ...
```
=> chore: log the size of the file to be uploaded to Farm

rs/http_endpoints/public/src/nns_delegation_manager.rs, rs/p2p/quic_transport/src/connection_manager.rs
This will assist with debugging flaky test. Example of logs:
```
Fetching delegation from the nns subnet. Attempts: 1.
Establishing TCP connection to rbuft-7b2ng-tiz5n-uqpqb-tdkxx-5t2d4-h7lft-nq5em-6o3ou-nw5vw-aae @ [--REDACTED--]:8080
Establishing TLS stream to rbuft-7b2ng-tiz5n-uqpqb-tdkxx-5t2d4-h7lft-nq5em-6o3ou-nw5vw-aae. Tcp stream: PollEvented { io: Some(TcpStream { addr: [--REDACTED--]:43904, peer: [--REDACTED--]:8080, fd: 31 }) }
Establishing HTTP connection to rbuft-7b2ng-tiz5n-uqpqb-tdkxx-5t2d4-h7lft-nq5em-6o3ou-nw5vw-aae. Tls stream: TlsStream { io: PollEvented { io: Some(TcpStream { addr: [--REDACTED--]:43904, peer: [--REDACTED--]:8080, fd: 31 }) }, session: ClientConnection, state: Stream }
Attempt to fetch HTTPS delegation from root subnet node with addr = …
```
=> chore: add more logs to nns delegation manager

rs/tests/consensus/replica_determinism_test.rs
The `//rs/tests/consensus:replica_determinism_test` was flaky because the malicious node could turn malicious and crash the replica just after the health check but before creating the agent. If this happened creating the agent would fail with:
```
2025-05-08 10:06:44.846 INFO[test:StdErr] Could not create agent: TransportError(reqwest::Error 
{ kind: Request, url: "http://[2602:fb2b:100:10:501e:e3ff:fefe:d2e5]:8080/api/v2/status", 
source: hyper_util::client::legacy::Error(Connect, ConnectError(
"tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) })
```
This is fixed by retrying creating the agent because the crashed replica should come back online after a while.
=> fix: flaky //rs/tests/consensus:replica_determinism_test

bazel/defs.bzl, ic-os/defs.bzl, ic-os/guestos/envs/prod/BUILD.bazel, ic-os/hostos/envs/prod/BUILD.bazel, ic-os/setupos/envs/prod/BUILD.bazel, publish/canisters/BUILD.bazel
This brings the file size checks to the BUILD files for visibility, and also reduces some of the logic in the `icos_build` macro.
This file check macro is also modified so that its gets named according to the `name` passed in.
=> chore(IDX): extract file size checks from icos_build

rs/tests/consensus/backup/common.rs, rs/tests/consensus/utils/src/upgrade.rs, rs/tests/dre/utils/steps/ensure_elected_version.rs
This refactors the consensus utils code to reflect the fact that public update-test images don't exist -- or at least should not.
=> chore(IDX): Don't expect public update-test images

.github/workflows/test-namespace-darwin.yaml
CI sometimes runs into [the following error](https://github.com/dfinity/ic/actions/runs/14966115526/job/42037281951) on the workflow: Bazel Test macOS Apple Silicon:
```
ERROR: /Users/runner/work/ic/ic/rs/nns/handlers/lifeline/impl/BUILD.bazel:35:16: CopyIdlFiles 
rs/nns/handlers/lifeline/impl/actor_idl_path failed: I/O exception during sandboxed execution: 
/private/tmp/zig-cache (No such file or directory)
```
`.github/workflows/test-namespace-darwin.yaml` doesn't actually use `.github/actions/bazel` which creates the `/tmp/zig-cache` directory. So let's create it. 
It's unclear why this failure only happens sometimes and [didn't happen](https://github.com/dfinity/ic/actions/runs/14894656219/job/41834646820) on https://github.com/dfinity/ic/pull/4848 which re-introduced the hermetic CC …
=> fix: let test-namespace-darwin use the hermetic cc toolchain

rs/registry/canister/tests/common/test_helpers.rs, rs/registry/canister/tests/create_subnet.rs, rs/registry/canister/tests/recover_subnet.rs
This PR adds unit tests to the registry canister, which cover the vetkd functionality in `create_subnet.rs` and `recover_subnet.rs`.
In particular:
- It extends `wait_for_chain_key_setup` to also support vetkeys
- Introduces `test_accepted_proposal_with_vetkd_gets_keys_from_other_subnet` test
- Introduces `test_recover_subnet_gets_vetkd_keys_when_needed` test
- Introduces `test_recover_subnet_without_vetkd_removes_it_from_signing_list` test
=> test(CRP-2632): Extend registry unit tests to include vetkd cases

ic-os/defs.bzl, ic-os/guestos/defs.bzl
Renamed `boot_args_template` to `extra_boot_args_template` for consistency.
=> chore: Update boot args key to `extra_boot_args_template`

rs/execution_environment/src/canister_manager/types.rs, rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
This PR links the Internet Computer specifications to the error: CanisterManagerError::SnapshotLimitExceeded. 
The interface spec changes are covered by [PR-5742](https://github.com/dfinity/portal/pull/5742)
=> chore: EXC-1701: Add error doc link for canister snapshot limit error.

rs/nns/governance/src/governance.rs, rs/nns/governance/src/network_economics.rs
This PR offers a minor refactoring for the `register_vote` function in the NNS, and adds a doc comment to explain the preconditions of that function.
=> chore(nns): Minor refactoring and documentation for NnsGov.register_vote

.github/workflows/schedule-rust-bench.yml, rs/ic_os/config/src/lib.rs, rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs, rs/tests/consensus/utils/src/performance.rs, rs/tests/driver/src/driver/test_env_api.rs, testnet/env/shared-config.yml
This PR finishes the long awaited transition from development clusters for kibana and elasticsearch to a production cluster in dm1.
=> chore: renaming mentions of ch1-obsdev1 into testnet

rs/execution_environment/src/execution/install.rs, rs/execution_environment/src/execution/install_code.rs, rs/execution_environment/tests/canister_logging.rs
This PR clears canister logs before instantiating the new canister when reinstalling the canister. Before the canister logs were only cleared after the canister init hook completed and thus the logs produced during the canister start and init hooks were lost. This fix is also in line with the [specification](https://internetcomputer.org/docs/references/ic-interface-spec#ic-management-canister-code-installation).
=> fix: clear canister logs before instantiating new canister during reinstall

MODULE.bazel, publish/binaries/BUILD.bazel, rs/sns/testing/BUILD.bazel
This PR adds a new Bazel target `//rs/sns/testing:sns_testing_bundle` that bundles all the files required for running sns-testing, including the binaries and canister wasms. This target's artifact is a single sns_testing_bundle.tar.gz file that should be published to the CDN (the size is around 100 MB).
=> chore(sns): Publish sns-testing bundle

ci/container/build-ic.sh, ic-os/guestos/envs/prod/BUILD.bazel, ic-os/hostos/envs/prod/BUILD.bazel, ic-os/setupos/envs/prod/BUILD.bazel, publish/binaries/BUILD.bazel, publish/canisters/BUILD.bazel, publish/defs.bzl
This adds a `prefix` option when creating artifact bundles. This will allow us to use the bundles directly when uploading artifacts to the CDN, instead of duplicating the logic of listing artifacts & computing checksums.
This also makes the necessary changes in `build-ic.sh` to support nested build artifacts as well as fixes a typo in the guestos directory name.
The implementation of `artifact_bundle` is also simplified to avoid creating symlinks from Bazel; moreover the output of `artifact_bundle` is now a _directory_ instead of a list of artifacts.
Prefixes are also added to all artifact bundles to reflect the file structure on the CDN.
=> feat(IDX): Add prefix to artifact bundles

rs/execution_environment/BUILD.bazel, rs/execution_environment/src/canister_manager.rs, rs/execution_environment/src/canister_manager/tests.rs, rs/execution_environment/src/execution_environment.rs, rs/replicated_state/src/canister_state/system_state/wasm_chunk_store.rs
This PR makes the management canister endpoint `upload_chunk` idempotent, i.e., uploading an existing chunk is a no-op (except for charging cycles).
Additionally, this PR refactors
- charging cycles to use the method `consume_cycles_for_instructions` of the cycles account manager;
- the method `insert_chunk` of the wasm chunk store to take the chunk hash as input and assume that the chunk does not exist and can be inserted.
=> fix: make upload_chunk idempotent

.github/actions/bazel-test-all/action.yaml, .github/actions/bazel/action.yaml
Addressing issue encountered [here](https://github.com/dfinity/ic/actions/runs/15015811313/job/42193404782).
This makes sure that any CI job that doesn't uses *bazel-test-all* action but uses *bazel* action doesn't encounter this issue.
=> chore(IDX): chown in bazel action

rs/state_manager/src/state_sync/chunkable.rs, rs/state_manager/tests/state_manager.rs
If we try to deliver state synced state, but the execution has already created the same height checkpoint, we still deliver state sync and load the execution checkpoint to verify as if it was a state synced checkpoint.
This change aborts state sync if the destination height is already reached by execution.
=> chore: Don't deliver ALREADY_EXISTS checkpoint in state sync

bazel/execution_log_compact_to_csv.py
It's useful to have the ability to (temporarily) exclude certain targets from the Build Determinism check so this adds a `--blacklist_pat` option to the `execution_log_compact_to_csv` tool.
=> chore(IDX): execution_log_compact_to_csv: add --blacklist_pat option

testnet/tools/nns-tools/lib/canisters.sh
Also, wait longer (1 hr intead of just 1 min).
=> feat(nns-tools): Make wait-for-canister-to-upgrade.sh also print out git commit ID.

rs/execution_environment/tests/storage_reservation.rs
This PR makes the storage reservation test more robust against changes to the universal canister (and, consequently, its default memory usage).
=> chore: make storage reservation test more robust

rs/nns/integration_tests/src/registry_get_chunk.rs, rs/registry/canister/canister/canister.rs, rs/registry/canister/chunkify/src/lib.rs, rs/registry/canister/chunkify/src/tests.rs, rs/registry/canister/src/registry.rs, rs/registry/canister/src/storage/tests.rs, rs/registry/nns_data_provider/src/certification/tests.rs, rs/registry/transport/proto/ic_registry_transport/pb/v1/transport.proto, rs/registry/transport/src/gen/ic_registry_transport.pb.v1.rs, rs/registry/transport/src/high_capacity.rs, rs/registry/transport/src/high_capacity_tests.rs, rs/registry/transport/src/lib.rs
This PR renames `timestamp_seconds` to `timestamp_nanoseconds` to reflect their actual units. It is the part of #5076 and should be merged together.
=> fix: renaming timestamps to reflect actual units

rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/src/governance/benches.rs
`ProposalData::topic` actually uses 2.5M instructions when topic is `Unspecified` as it prints the proposal. This distorts the benchmarks, especially for smaller ones. In a future PR, `ProposalData::topic` will simply use the topic stored at creation time, which makes the instructions go away. This PR prepares for that, so that the next PR doesn't introduce unnecessary benchmark updates which would make the next PR more difficult to understand.
* Add motion action in proposals added for benchmark preparation
* Update canbench_results.yml
=> perf(nns): Use a proper proposal payload in benchmarks

rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/tests/mod.rs, rs/nns/governance/tests/fake.rs, rs/nns/governance/tests/governance.rs, rs/nns/governance/unreleased_changelog.md, rs/nns/integration_tests/src/cycles_minting_canister.rs, rs/nns/integration_tests/src/cycles_minting_canister_with_exchange_rate_canister.rs, rs/nns/integration_tests/src/reinstall_and_upgrade.rs, rs/tests/driver/src/nns.rs, rs/tests/nns/nns_cycles_minting_multi_app_subnets_test.rs, rs/tests/nns/nns_cycles_minting_test.rs, rs/tests/nns/nns_dapp/nns_dapp.rs, rs/tests/testnets/large.rs, rs/tests/testnets/src_testing.rs
The exchange rate proposals are no longer needed because the rates are set by the exchange rate canister.
* Make the exchange rate proposal type obsolete
* Stop making such proposals for static testnets
* Delete the test `test_minimum_icp_xdr_conversion_rate` as it explicitly tests that the proposal
=> refactor(nns): Make ExchangeRate proposals obsolete

rs/nns/governance/api/src/types.rs, rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/canister/governance.did, rs/nns/governance/canister/governance_test.did, rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/merge_neurons.rs, rs/nns/governance/src/governance/tests/mod.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/pb/conversions.rs, rs/nns/governance/src/pb/proposal_conversions.rs, rs/nns/governance/src/test_utils.rs, rs/nns/governance/tests/governance.rs, rs/nns/governance/tests/proposals.rs, rs/nns/governance/unreleased_changelog.md
Sometimes the `Proposal::topic` might change, especially when some canisters start to be considered as protocol cansiters. In this cases, we want the proposal to retain the topic at creation.
* Define `ProposalData::topic` field
* Rename `Proposal::topic` to `Proposal::assign_topic_at_creation`
* Set `ProposalData::topic` at creation time
* Change `ProposalData::topic()` to use the `Proposal::topic`
* Change `ProposalData::is_manage_neuron` to use `ProposalData::topic`
* Delete `Proposal::is_manage_neuron` in favor of `ProposalData::is_manage_neuron`
* Update benchmark for `list_proposals`. It is very lightweight so it's affected by not calling `Proposal::topic`
=> feat(nns): Persist topic throughout proposal lifecycle

rs/registry/canister/src/mutations/node_management/do_add_node.rs, rs/registry/canister/unreleased_changelog.md
This turns on enforcement that new node registrations will have a valid node_reward_type.  This is for the sake of accurately calculating node provider rewards based on the actual nodes that are registered and their types.
=> feat(registry): enforce presence of node_reward_type

rs/registry/canister-client/src/stable_canister_client.rs, rs/registry/canister-client/src/stable_canister_client/tests.rs
An edge case was detected through code analysis where the version could be bumped but the application of deltas failed.  This could lead to a gap in Registry data.
=> fix(registry-canister-client): Only version-bump after deltas are applied.

packages/pocket-ic/CHANGELOG.md, packages/pocket-ic/tests/tests.rs, rs/pocket_ic_server/CHANGELOG.md, rs/pocket_ic_server/src/pocket_ic.rs
This PR fixes a crash when creating a canister with a specified id on a PocketIC instance created from an existing PocketIC state. The issue was caused by not adding the canister ranges of subnets in the existing PocketIC state to `PocketIc::range_gen`.
=> fix(PocketIC): canister creation with specified id on resumed instance

rs/http_endpoints/public/src/nns_delegation_manager.rs
I've checked the logs on the test net and realized the log messages are bugged:
```
Fetching delegation from nns subnet failed. Retrying again in 14 seconds...
Error received: Timed out while connecting to the nns node after {CONNECTION_TIMEOUT:?}
```
=> fix: properly log the time-out in NNS delegation manager

rs/replicated_state/src/canister_state.rs, rs/replicated_state/src/canister_state/execution_state.rs
The custom wasm section may contribute to a running canister's memory footprint, but it is not stored in a snapshot explicitly, so it should not be used in the snapshot size calculation.
=> fix: Fix snapshot size calculation

Cargo.Bazel.Fuzzing.json.lock, Cargo.Bazel.json.lock, bazel/external_crates.bzl
This lists x86-darwin as a platform supported by rules_rust. This seems to have been removed [upstream](https://github.com/bazelbuild/rules_rust/pull/3239).
=> fix(IDX): Re-enable x86-darwin builds

rs/ledger_suite/icrc1/test_utils/src/lib.rs, rs/rosetta-api/icrc1/src/common/storage/storage_client.rs
Some flakiness was observed for the `test_deriving_gaps_from_storage`. This seems to be because the `valid_blockchain_with_gaps_strategy` could generate some blockchains and corresponding block index values that actually did not contain gaps. This PR proposes to add some filters to the strategies, so that the valid blockchain that is generated is of at least length `2`, and so that the first gap occurs before the last block in the blockchain.
=> test(ICRC_Rosetta): FI-1725: Fix flaky test_deriving_gaps_from_storage test

ci/tools/repro-check
Fix:
On some machines the repro-check script was throwing an error:
```
OSError: [Errno 18] Invalid cross-device link: '/home/...<path1>/update-img.tar.zst' -> '/tmp/<path2>/update-img.tar.zst'
```
This was because on some machines `/home` and `/tmp` are on different file systems.
The fix is to create temporary directory under `base_cache_dir` with timestamp instead of `tempfile.TemporaryDirectory`
=> fix(repro-check): use temp dir in the home directory to fix cross-device linking issue

ic-os/components/monitoring/filebeat/filebeat.service
ExecCondition runs before ExecStartPre. Therefore, generate-filebeat-config.sh never has a chance to create the /run/ic-node/etc/filebeat/filebeat.yml file
Instead, we can move this conditional to the ExecStart call.
This service will be cleaner once we move all generate-*-config scripts into the main generate-ic-config script
=> fix(node): filebeat exec condition

.github/workflows-source/ci-main.yml, .github/workflows-source/release-testing.yml, .github/workflows-source/schedule-daily.yml, .github/workflows-source/schedule-hourly.yml, .github/workflows/ci-main.yml, .github/workflows/release-testing.yml, .github/workflows/schedule-daily.yml, .github/workflows/schedule-hourly.yml, .github/workflows/system-tests-k8s.yml
This removes some bind mounts for the build container that are not strictly necessary anymore.
Some, like `/var/tmp`, introduce determinism issues by storing references across builds -- though the root cause is not clear yet.
=> chore(IDX): Remove unnecessary bind mounts

rs/replay/src/player.rs, rs/replay/tests/player.rs
This piggy backs off an existing test for a similar function (to wit, `registry_get_value`).
I made `get_changes_since` be `async` instead of taking a `Runtime` (which was used to `block_on`). This is orthogonal, but it makes everything a little bit simpler, because tests do not then have to create a `Runtime`.
=> test(replay): Integration test for `get_changes_since` in replay.

rs/tests/consensus/subnet_recovery/common.rs
The DKG interval of recovery tests is currently set to 9 blocks. After enabling vetKD on NNS we need to perform 6 rounds of DKG however (local/remote DKGs for high/low/vetKD transcripts), with 4 dealings each. Since we include at most one dealing per block, some of these DKG instances are currently failing, leading to flaky or failing tests.
This PR therefore increases the DKG interval to 24. This may be reduced again after we deploy chainkeys on a different subnet other than the NNS (CON-1500).
We additionally disable vetKD on the large recovery test, which can only be re-enabled after large registry deltas are supported.
=> test: fix vetKD recovery tests by increasing DKG interval length

.github/workflows/test-namespace-darwin.yaml
Upload the pocket-ic-server artifact for Arm64-Darwin.
=> chore: Upload the pocket-ic-server artifact.

ci/tools/repro-check
This PR aligns formatting logic in python repro check script. On top of that it fixes the issue of message formatting in case of an error.
Before this fix the formatting looked like:
```bash
8d4b680b40db56e909f17fbabf26a15f66b144c46f47efb4cf8c2a0285bb8faf disk-img.tar.zst
f35e46220f30def12ab42404a84b6e42a355db08aacb6bb568b3638b722e98e9 update-img-test.tar.zst
2e88687e9f7f45b35f2aec88520ab9417eb21237b9eb5f9083fde4f607085e92 update-img.tar.zst
dbf44296c2c2067cbcef7426a292ab80b5da471f95dd02d0e16904944969f1c0 disk-img.tar.zst
96c73b9996a5ef8acaa3c4379b286cd0c676ae8cee0203c1c16fcae82c3969e2 update-img-test.tar.zst
6a2e6dfb7ec02a65755ed7fd283df64f5a717a157d666f1a09575d30332efabf update-img.tar.zst
00ab0cd45d9634eb8b8cdfc1b882b3016d781569cb685e41b446f02249d6fdd6 disk-img.tar.zst
Build complete …
```
=> fix: repro-check formatting issues

BUILD.bazel, ic-os/guestos/envs/dev/BUILD.bazel, ic-os/guestos/envs/prod/BUILD.bazel
This fixes the ic-os image upload:
* Adds the `prod` variant of the `guestos`
* Adds a suffix for `dev` images
Without those, the `prod` guestos was not uploaded, and `dev` images might override `prod` images -- although those never got uploaded.
=> fix(IDX): add missing images and upload suffix

rs/embedders/benches/embedders_bench/src/lib.rs, rs/embedders/benches/heap.rs
This PR introduces additional heap benchmark dimensions:
1. One OS page step (4 KiB)
2. Two OS pages step (8 KiB).
3. One Wasm page step (64 KiB)
4. Two Wasm pages step (128 KiB)
5. One huge page step (2 MiB)
6. Two huge pages step (4 MiB)
7. A new mixed source of pages: a combination of checkpoint and heap delta.
The 8-byte step benchmark has been removed as its behavior is effectively
the same as a page step (with potentially a few more instructions to access
the same page).
Furthermore, this PR aims to resolve all memory access corner cases
by consistently using 64-bit addresses and converting them to 32-bit
only immediately before accessing the page. This approach should address
all previous issues related to verifying if an address falls within
the working set range.
Also, the PR …
=> perf: EXC-2033: Add more heap benchmarks

rs/registry/canister/src/registry.rs, rs/registry/canister/src/storage.rs
This addresses all `TODO(NNS1-3746)`s by either adding more tests, or enhancing existing ones, now that we have chunking.
All tests ALSO pass [when I enable chunking][enabled] (by setting `IS_CHUNKIFYING_LARGE_VALUES_ENABLED` to `true`), so we should be able to simply flip the flag when the time comes.
[enabled]: https://github.com/dfinity/ic/actions/runs/15134222666?pr=5210
Since chunking is still disabled in release builds, there is technically, no behavior change here, and so `unreleased_changelog.md` does not need to be updated. However, if chunking WERE enabled, there would be a (small) behavior change: the min chunkable size has been decreased by around 100 bytes.
We never promised that the previous value is EXACTLY EXACTLY EXACTLY when chunking would start happening. Rather, we …
=> test(registry): More tests for large records/chunking.

ic-os/bootloader/grub.cfg, ic-os/hostos/grub.cfg
NODE-1603
We encountered a case where a node was supposed to be rolling back from A to B, but it instead "rolled back" from A to A. This PR resolves the syntax error causing this.
=> fix(node): grub syntax error

rs/tests/nested/BUILD.bazel
The nested system-tests are currently failing due to [this](https://github.com/dfinity/ic/pull/5089#issuecomment-2892408601). The problem is that the `head_nns` variants of the nested system-tests run during the "Bazel System Test Nightly" job which is part if "Release Testing" which means we can't make a new release. 
So we make sure the `head_nns` variants don't run on  "Bazel System Test Nightly" but on "Schedule Hourly" instead.
=> fix: don't run the head_nns variants of the nested tests during system_test_nightly

rs/execution_environment/src/canister_manager/types.rs
This PR links the Internet Computer specifications to the error: `CanisterManagerError::CanisterSnapshotNotEnoughCycles`.
The interface spec changes are covered by https://github.com/dfinity/portal/pull/5742.
=> chore: EXC-1701: Add error doc link for canister snapshot not enough cycles error.

rs/https_outcalls/adapter/src/rpc_server.rs
This is how it should've been before. The only reason it worked was that `https_only` was not really enforced. See here:
https://github.com/rustls/hyper-rustls/pull/295
=> fix: disable https in the proxy client if the http flag is true.

rs/https_outcalls/adapter/src/rpc_server.rs
This PR makes all http requests from system subnets that fail via the direct path go via the an API BN as a socks proxy.
The 50% data is looking stable, with constant QPS, very low failures, and overall performance similar to the old gateways
=> chore: ramp up the new socks proxy discovery to 100%

rs/execution_environment/src/canister_manager/tests.rs, rs/execution_environment/tests/canister_logging.rs, rs/test_utilities/execution_environment/src/wat_canister.rs
The arguments used for `stable_read` in WatCanisterBuilder were incorrect, basically missing the `dst` argument. This meant that `stable_read` actually depended on a `stable_grow` to exist before it so that it can use its return value as one of the arguments. While this may be acceptable (how can you read before growing your memory first?), it also creates the reverse dependency. If one uses a `stable_grow` only, it will leave one operand on the stack and the resulting wasm module would be invalid.
One fix (which is what this PR proposes) is to always drop the result of `stable_grow` -- in a test utility it's not particularly useful anyway, most of the time the test would expect to succeed and even if it wants to fail, this can (and should be) tested outside the Wasm module (e.g. by …
=> fix: Use correct arguments for stable_read in WatCanisterBuilder

rs/execution_environment/src/canister_manager/tests.rs, rs/execution_environment/tests/hypervisor.rs
This PR enhances a few tests with an extra check that the reserved cycles are indeed more than 0 -- it could be indirectly checked via inspecting the method that calculates them based on the input args but better to be more explicit.
=> test: Make tests that check reserved cycles more robust

Cargo.lock, rs/nervous_system/neurons_fund/BUILD.bazel, rs/nervous_system/neurons_fund/Cargo.toml, rs/nervous_system/neurons_fund/src/lib.rs, rs/nervous_system/neurons_fund/src/polynomial_matching_function_tests.rs, rs/nervous_system/proxied_canister_calls_tracker/BUILD.bazel, rs/nervous_system/proxied_canister_calls_tracker/Cargo.toml, rs/nervous_system/proxied_canister_calls_tracker/src/lib.rs, rs/nns/cmc/src/main.rs, rs/nns/governance/src/garbage_collection.rs, rs/nns/governance/src/governance/disburse_maturity.rs, rs/nns/governance/src/governance/tla/mod.rs, rs/nns/governance/src/governance/voting_power_snapshots.rs, rs/nns/governance/src/neuron_lock.rs, rs/nns/governance/src/neurons_fund.rs, rs/nns/governance/src/neurons_fund/neurons_fund_participation_tests.rs, rs/nns/governance/src/proposals/mod.rs, rs/nns/governance/src/reward/distribution.rs, rs/nns/governance/src/timer_tasks/calculate_distributable_rewards.rs, rs/nns/governance/src/timer_tasks/seeding.rs, rs/nns/governance/src/voting.rs, rs/registry/canister-client/src/stable_canister_client.rs, rs/registry/canister/src/certification.rs, rs/registry/canister/src/mutations/do_update_node_rewards_table.rs, rs/registry/canister/src/mutations/subnet.rs, rs/registry/node_provider_rewards/BUILD.bazel, rs/registry/node_provider_rewards/Cargo.toml, rs/registry/node_provider_rewards/src/logs.rs, rs/sns/audit/BUILD.bazel, rs/sns/root/src/lib.rs
Ditto for `eprintln`.
The effect of this is that logging from canisters does NOT go into a black hole.
In `tests` modules, our usual thing is to do
```
use super::*;
```
If the parent module does `use whatever::println;`, and the `tests` module calls `println`, Rust says that it does not know which version of `println` we are trying to call. To disambiguate, the `tests` module can do
```
use self::println;
```
to say that it wants the normal version of `println`. This is done in some of the `tests` modules here.
In some cases, this also required adding `ic-cdk` to `DEPENDENCIES` (ditto for `Cargo.toml`, ofc).
How I figured out which files should be changed:
```
grep -rl println! rs/nns rs/nervous_system rs/sns \
| xargs grep -L "use .*println" \
| grep -v tests \
| sort
```
Ofc, this is …
=> feat(governance): Added `use ic_cdk::println;` to files that lack it.

.github/CODEOWNERS, .github/workflows/ci-pr-only-nns-team-reminder.yml, .github/workflows/team-channels.json
The name of the [nns-team](https://github.com/orgs/dfinity/teams/nns-team) has changed to [governance-team](https://github.com/orgs/dfinity/teams/governance-team). More information can be found [here](https://dfinity.slack.com/archives/CGJND92DA/p1747828796597669?thread_ts=1747671441.856149&cid=CGJND92DA) and [here](https://dfinity.slack.com/archives/CGJND92DA/p1747740057505439).
- Update references from the old team name to the new one.
Not necessary.
=> chore: update team name to governance-team

Cargo.lock, rs/tests/cross_chain/BUILD.bazel, rs/tests/cross_chain/Cargo.toml
The `canister_client` crate is not very maintained anymore and we would like to avoid its use. The `ic-tests-cross-chain` crate still depends on it but does not actually use it.
This PR simply removes the dependency from the Cargo and Bazel files.
=> chore(cross-chain): remove unused canister_client dependency

packages/pocket-ic/src/nonblocking.rs
This PR fixes test failures such as [this](https://github.com/dfinity/ic/actions/runs/15183560437/job/42703402902?pr=5234#step:5:13075) due to `SystemTime` not being monotone.
=> fix(PocketIC): panic in SystemTime::elapsed

ic-os/components/hostos-scripts/generate-guestos-config/dev-generate-guestos-config.sh, ic-os/components/hostos-scripts/generate-guestos-config/generate-guestos-config.sh
All nodes have a vm_nr_of_vcpus field in their config object, thanks to update_config.rs
This field was added recently, and we updated update_config.rs to create the default value rather than put the default value in generate-guestos-config (or, rather than put the default value _everywhere_ in generate-guestos-config). So it is not optional for new deployments (despite what the default value in generate-guestos-config may suggest) and all nodes deployed have the value.
We can remove the 64 default value in generate-guestos-config.sh, which will make the code less confusing.
=> fix(node): Remove vm_nr_of_vcpus default value

.github/actions/bazel-test-all/action.yaml
The `--config=release` was being added to both `bazel_args` and explicitly on the command line.
=> fix(IDX): deduplicate release flag

Cargo.lock, ic-os/components/hostos-scripts/generate-guestos-config/dev-generate-guestos-config.sh, ic-os/components/hostos-scripts/generate-guestos-config/generate-guestos-config.sh, rs/ic_os/config/BUILD.bazel, rs/ic_os/config/Cargo.toml, rs/ic_os/config/src/guestos_config.rs, rs/ic_os/config/src/lib.rs, rs/ic_os/config/src/main.rs, rs/ic_os/config_types/src/lib.rs, rs/ic_os/deterministic_ips/src/lib.rs
In addition, calculate IP address from the passed config instead of taking it as a separate argument.
=> refactor: Factor out generate_guestos_config into a library function and add tests

rs/nns/governance/api/src/types.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/tests/stake_maturity.rs, rs/nns/governance/tests/fixtures/mod.rs, rs/nns/governance/tests/governance.rs
This removes more vestiges of merge_maturity code (which has been non-functional for over 1 year), in governance.
=> chore(governance): Clean up more leftovers from merge_maturity

packages/pocket-ic/src/lib.rs, packages/pocket-ic/src/nonblocking.rs, rs/pocket_ic_server/CHANGELOG.md, rs/pocket_ic_server/src/state_api/state.rs
This PR refactors PocketIC to set the (certified) time for auto-progress mode on the server instead of in the library: this way, trying to enable the auto-progress mode on a PocketIC instance with the auto-progress mode already enabled is a no-op (instead of resetting the certified time again).
This PR also fixes doc comments to not distinguish between `/api/v2` and `/api/v3` requests since more versions might be introduced in the future and the doc comments are already inconsistent (some only refer to `/api/v2`).
=> chore(PocketIC): set time on the server for auto-progress mode

.devcontainer/devcontainer.json, ci/container/container-run.sh
On `zh-spm34` and `zh1-spm22` when running `ci/container/container-run.sh` the podman option:
```
--mount type=volume,chown=true,destination=/tmp/zig-cache
```
causes:
```
Error: 'overlay' is not supported over zfs
```
and 
```
Error: chown: invalid mount option
```
So instead of using a volume to mount `/tmp/zig-cache` we bind mount `~/.cache/zig-cache` to  `/tmp/zig-cache`  in both `ci/container/container-run.sh` and `.devcontainer/devcontainer.json`.
=> chore: bind mount ~/.cache/zig-cache to /tmp/zig-cache

rs/drun/src/main.rs
Since `moc` tests are run in a controlled environment, we do exactly know which traps occur and when. So there is zero added value in observing backtraces, but they tend to diverge in various test targets (e.g. EOP vs. classical) so to avoid normalisation for golden tests, better suppress them.
=> chore(drun): eliminate backtraces when testing with `drun`

.github/workflows/tag-release.yml
Canister was removed in #5069. See [related failure](https://github.com/dfinity/ic/actions/runs/15204705042/job/42765131789). Directly use https despite "curl -L/301".
=> chore(IDX): remove wasm.wasm.gz

rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
When simulating voting with multiple neurons in the test, we should not assume the voting all succeed since they might follow each other. On the other hand, not checking the voting result is OK since we will wait for the proposal execution anyway. The only downside of not checking is that when proposal does not execute, it's slightly more difficult to debug.
=> test(nns): Stop assuming voting with well known neurons must succeed as they might follow each other

rs/sns/swap/src/swap.rs, rs/sns/swap/tests/swap.rs, rs/sns/swap/unreleased_changelog.md
This PR fixes an issue that could occur if the NNS Governance canister does not find proposals that correspond to the creation of the SNS that requests Neurons' Fund participation during finalization. Note that currently, the Neurons' Fund is disabled, and the SNSs that do not even request Neurons' Fund participation are potentially risking that their finalization halts if the NNS proposal that created that SNS cannot be found (this recently happened due to an unrelated problem in the NNS).
The solution is to avoid calling the NNS Governance's `settle_neurons_fund_participation_result` function is the SNS des not specifically request Neurons' Fund participation.
=> fix(sns): Avoid calling NNS Governance during swap finalization if Neuron's Fund participation was not requested

rs/types/wasm_types/src/errors.rs
This PR fixes user error messages to not contain `See documentation` without a link to documentation, i.e., to not end with `See documentation: `.
=> fix: do not include See documentation without doc link

Cargo.lock, rs/ledger_suite/icrc1/BUILD.bazel, rs/ledger_suite/icrc1/Cargo.toml, rs/ledger_suite/icrc1/ledger/BUILD.bazel, rs/ledger_suite/icrc1/ledger/Cargo.toml, rs/ledger_suite/icrc1/ledger/src/tests.rs, rs/ledger_suite/icrc1/tests/tests.rs, rs/ledger_suite/icrc1/tokens_u256/BUILD.bazel, rs/ledger_suite/icrc1/tokens_u256/Cargo.toml, rs/ledger_suite/icrc1/tokens_u256/tests/tests.rs, rs/ledger_suite/icrc1/tokens_u64/BUILD.bazel, rs/ledger_suite/icrc1/tokens_u64/Cargo.toml, rs/ledger_suite/icrc1/tokens_u64/tests/tests.rs
Use `test_strategy` annotations instead of the `proptest!` macro for ICRC1 ledger suite tests. Using the annotations instead of the macro allows `rustfmt` to format the code. This PR is inspired by [this earlier PR](https://github.com/dfinity/ic/pull/4163) for the `xnet/payload_builder` tests.
=> chore(ICRC_Ledger): FI-1726: Use test_strategy instead of proptest macro for ICRC1 ledger suite tests

mainnet-icos-revisions.json
Reverts dfinity/ic#5290 as it's changes break [some tests](https://github.com/dfinity/ic/actions/runs/15254144506/job/42897652573).
=> revert: "chore: Update Mainnet IC revisions file"

.github/workflows-source/schedule-hourly.yml, .github/workflows/schedule-hourly.yml
The `pipelined_compilation` creates a different config from Bazel's point of view, leading to `--check_up_to_date` assuming that the artifacts are not up to date.
=> chore(IDX): don't use pipelined build for schedule hourly

rs/rosetta-api/icp/src/rosetta_server.rs
This pull request introduces a new mechanism to ensure that the `heartbeat_fn` is only invoked after the first successful blockchain synchronization in the `start_sync_thread` function. This change improves the logic for handling synchronization and ensures that the heartbeat is not prematurely triggered.
Without this, if there's any failure during the initial sync, the watchdog thread will think the initial sync is done and only wait up to 60 seconds per cycle, leading to multiple sync thread restarts.
=> fix(icp-rosetta): fix heartbeat during initial sync

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
The macOS intel job did not have `upload-artifacts` set.
=> chore(IDX): re-enable macos intel uploads

.github/workflows/system-tests-k8s.yml
The credentials were not being set (`inputs` is not set for workflows).
=> chore(IDX): remove cloud credentials from k8s tests

rs/state_manager/src/lib.rs
The defrag_canisters_map step during checkpointing was initially intended to be a functional no-op, while improving performance. In particular, it was intended to combat the slight performance difference between a subnet that was recently upgraded, and one that has been running for a while. However, it turned out that the step never lead to the desired significant improvements.
Now that checkpointing has been optimized to the area of 1 second with asynchronous checkpointing, the defrag_canisters_map step contributes as much as 40% to the checkpointing time on some subnets, which makes it not worth it.
This PR removes the step without replacement.
=> chore: Remove defrag_canisters_map step

rs/xnet/payload_builder/src/lib.rs
During XNet payload building, shuffle the streams instead of rotating them, to provide better fairness.
=> feat: Shuffle streams in XNet payload builder

rs/tests/consensus/utils/src/upgrade.rs
We had an incident (fixed in #5305) where all of the artifacts were uploaded to the same SHA256SUMS file on our object storages. This causes the current test logic to assume and expect wrong SHA since the SHAs are sorted in an ascending order in the SHA256SUMS. 
In this logic we only download update images and this is just a stronger requirement that will prevent the explained bug from happening again. Currently this breaks our qualification system test since the node is constantly expecting a wrong SHA.
An example file that breaks the code and is fixed by this pr can be downloaded [here](http://download.proxy-global.dfinity.network:8080/ic/181968dd5f36af93590490802540caf7d2df915a/guest-os/update-img/SHA256SUMS)
=> fix: full suffix for sha matching in tests

Cargo.lock, rs/rosetta-api/icrc1/BUILD.bazel, rs/rosetta-api/icrc1/CHANGELOG.md, rs/rosetta-api/icrc1/Cargo.toml, rs/rosetta-api/icrc1/src/common/constants.rs
Release information for ICRC Rosetta 1.2.3 with the following changes:
- Fixed fee collector balance calculation for transfers using fee_collector_block_index
The balance calculation wasn't taking into account fees being sent to fee collectors defined in a different block, which led to fee collector accounts having wrong balances in the local Rosetta DB.
This release:
- Makes sure that fee collectors' balances are correctly modified in such cases
- Reconciles balances of DBs potentially affected by the bug at startup by recreating the balances table. We keep track when this fix has happened for a particular DB so we only do it once.
=> feat(icrc-rosetta): add icrc rosetta release 1.2.3

.github/CODEOWNERS
This PR adds the Cross chain team as a co-owner of the bitcoin adapter crate
=> chore(XC): Make Cross chain team co-own the bitcoin adapter

hs/spec_compliance/src/IC/Test/Spec.hs
Testing large calls in Haskell has caused flakiness recently and because the test scenarios have already been covered in Rust by this [PR](https://github.com/dfinity/ic/pull/4904), we're removing them from the Haskell test suite.
=> chore: deprecate large calls tests in Haskell

ic-os/guestos/defs.bzl, ic-os/hostos/defs.bzl, ic-os/setupos/defs.bzl
`$ bazel query 'deps("//ic-os/hostos/envs/dev")' | grep //rs/ic_os/release:config
//rs/ic_os/release:config_dev
//rs/ic_os/release:config_dev_cleaned
//rs/ic_os/release:config_dev_stripped`
Context: https://github.com/dfinity/ic/pull/5325#discussion_r2112651100
=> fix(node): remove config tool dependency for dev variants

Cargo.Bazel.Fuzzing.json.lock, Cargo.Bazel.Fuzzing.toml.lock, Cargo.Bazel.json.lock, Cargo.Bazel.toml.lock, bazel/external_crates.bzl, rs/rust_canisters/downstream_calls_test/Cargo.toml, rs/rust_canisters/random_traffic_test/Cargo.toml, rs/rust_canisters/xnet_test/Cargo.toml
Recalculating the `Cargo.Bazel.*` files by emptying them and running `bin/bazel-pin.sh --force` results in:
```
error: failed to select a version for the requirement `ic-cdk = "^0.18.0"`
version 0.18.0 is yanked
version 0.18.1 is yanked
version 0.18.2 is yanked
```
This is because [the following targets](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/dfinity/ic%24+%27ic-cdk+%3D+%220.18.0%22%27&patternType=keyword&sm=0) were still depending on `ic-cdk = "^0.18.0"`:
* `//rs/rust_canisters/downstream_calls_test`
* `//rs/rust_canisters/random_traffic_test`
* `//rs/rust_canisters/xnet_test`
This is fixed by letting those targets depend on ic-cdk--0.18.0-alpha.2.
=> chore: use ic-cdk 0.18.0-alpha.2

rs/nns/cmc/src/lib.rs, rs/nns/cmc/src/main.rs, rs/nns/cmc/unreleased_changelog.md
With this PR, the cycles minting canister uses the 128bit minting and balance API.
=> feat: [EXC-1824] Use mint_cycles128 in CMC

rs/execution_environment/tests/hypervisor.rs, rs/interfaces/src/execution_environment/errors.rs
This PR changes the error message "Canister exceeded its allowed memory allocation." for `OutOfMemory` to "Canister cannot grow its memory usage." since the error condition is not specific to "memory allocation".
=> fix: error message for OutOfMemory

.github/CODEOWNERS
This crate is used only by the execution team so moving ownership to the team explictly.
=> chore: Update code owners for lru cache

rs/orchestrator/src/registration.rs
This change would allow us to see if the `node_reward_type` is set in the `AddNodePayload`.
=> refactor(registration): unify and enhance node registration logs

rs/tests/nns/nns_dapp_test.rs
The `//rs/tests/nns:nns_dapp_test` is highly flaky (14%). When it fails it most often is because the BN returned an unexpected response when requesting an HTML page. Instead of immediately panicking we retry on a non-successful response status.
=> chore: stabilize the highly flaky nns_dapp_test

packages/pocket-ic/src/lib.rs, packages/pocket-ic/tests/tests.rs, rs/pocket_ic_server/src/pocket_ic.rs
This PR makes PocketIC return a comprehensible error if the provided subnet state directory is clearly invalid, i.e., not a directory or an empty directory.
=> chore(PocketIC): comprehensible error for clearly invalid subnet state directory

.github/workflows/update-mainnet-revisions.yaml
Because `bazel-test-all` sometimes takes longer than 1 hour to run, it keeps kicking off a new run, preventing the PR from being merged. This changes the job to run every 2 hours instead.
=> fix(IDX): run versions workflow every 2 hours

Cargo.Bazel.Fuzzing.json.lock, Cargo.Bazel.Fuzzing.toml.lock, Cargo.Bazel.json.lock, Cargo.Bazel.toml.lock, MODULE.bazel, bazel/external_crates.bzl, rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml, rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml, rs/nns/governance/canbench/canbench_results.yml
Note that canbench 0.15.0 uses the pocket-ic (client 9.0.0) [here](https://github.com/dfinity/canbench/pull/95). The `pocket-ic-mainnet-gz` is updated accordingly.
=> chore: Upgrade canbench to 0.15.0

.github/workflows/schedule-weekly.yml
In #4744, all fuzzing scripts were moved from `bin` to `bin/fuzzing`. However, the GCP key path wasn't properly adapted for it and has caused the schedule-weekly job to fail for a [while](https://github.com/dfinity/ic/actions/workflows/schedule-weekly.yml)
=> fix(fuzzing): Fix path for GCP key

rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/canister/canister.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/benches.rs, rs/nns/governance/src/governance/disburse_maturity_tests.rs, rs/nns/governance/src/governance/tests/list_neurons.rs, rs/nns/governance/src/governance/tests/list_proposals.rs, rs/nns/governance/src/governance/tests/mod.rs, rs/nns/governance/src/governance/tests/neurons_fund.rs, rs/nns/governance/src/governance/tests/node_provider_rewards.rs, rs/nns/governance/src/governance/tests/stake_maturity.rs, rs/nns/governance/src/governance_proto_builder.rs, rs/nns/governance/src/neuron_lock_tests.rs, rs/nns/governance/src/reward/distribution.rs, rs/nns/governance/src/seed_accounts/seed_accounts_tests.rs, rs/nns/governance/src/timer_tasks/calculate_distributable_rewards.rs, rs/nns/governance/src/timer_tasks/distribute_rewards.rs, rs/nns/governance/src/timer_tasks/snapshot_voting_power.rs, rs/nns/governance/src/voting.rs, rs/nns/governance/tests/degraded_mode.rs, rs/nns/governance/tests/fake.rs, rs/nns/governance/tests/fixtures/mod.rs, rs/nns/governance/tests/governance.rs, rs/nns/governance/tests/interleaving_tests.rs, rs/nns/governance/tests/monitoring.rs, rs/nns/governance/tests/proposals.rs
The overall goal is to remove `GovernanceProto::neurons` as it's always empty in production (since neurons live in stable memory). However, the very field is often used in testing, where the field contains the "initial neurons" which then get passed to `NeuronStore::new`. 
In addition, it's unnecessary to have the exact same fields on the API type as the internal type, as some of the internal types should not be initialized from the outside. By having `Governance::new` take the API type directly, we can make it possible to gradually shrink down the fields on the API Governance type, especially those that should be considered internal (e.g. `making_sns_proposal`, `spawning_neurons`).
* Inline the `api::Governance->GovernanceProto` conversion into `Governance::new`
* Fix all tests using …
=> refactor(nns): Move Governance API->Internal type conversion into Governance::new

ci/src/mainnet_revisions/mainnet_revisions.py
This will hopefully prevent regressions from getting merged to master.
=> chore(IDX): run all bazel targets on mainnet revision PRs

rs/execution_environment/src/query_handler/query_context.rs, rs/tests/networking/canister_http_correctness_test.rs
Composite queries have only been used as canister http transforms by the canister `whele-paaaa-aaaab-qbkmq-cai` ([logs](https://kibana.mainnet.dfinity.network/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-30d%2Fd,to:now))&_a=(columns:!(),filters:!(),hideChart:!f,index:ic-logs-mainnet,interval:auto,query:(language:kuery,query:'%22Running%20composite%20canister%20http%20transform%20on%20canister%22'),sort:!(!(timestamp,desc))))) which was upgraded to no longer use them and thus this PR disables them (they have never been specified as enabled by the [Interface Specification](https://internetcomputer.org/docs/references/ic-interface-spec#ic-candid)).
=> chore: disable composite query as canister http transform

ci/src/artifacts/upload.sh
This explicitly tells `rclone` to not use a config file, avoiding unnecessary warnings when `rclone` is run.
=> chore(IDX): don't use a config file for rclone

rs/tests/consensus/upgrade/BUILD.bazel
The `//rs/tests/consensus/upgrade:{upgrade,downgrade}_app_subnet_tests` are highly flaky because they timeout frequently. When looking at their Kibana logs we see that the node was in the process of rebooting to the upgraded version but then the test timed out. So giving it a bit more time will probably allow these tests to succeed. So we increase their bazel timeouts from `long` (15 minutes) to `eternal` (1 hour).
=> fix: increase timeout for the {upgrade,downgrade}_app_subnet_tests

rs/state_machine_tests/src/lib.rs
This PR adds an additional step to state machine tests that restart the state manager by flushing any asynchronous operations first.
=> fix: Flush state manager before restart

rs/nns/governance/BUILD.bazel
The `//rs/nns/governance:governance_integration_test_tests/governance` test times out in over 2% of the runs requiring folks to manually restart the job on their PRs. So this commit marks all `//rs/nns/governance:governance_integration_test_tests/...` tests as flaky such that they're automatically retried and show up on our Flakiness Dashboards. The latter will help with prioritising fixing the flakiness.
=> chore: mark  //rs/nns/governance:governance_integration_test_tests:... as flaky

rs/nns/governance/src/governance.rs, rs/nns/governance/src/neuron_store.rs, rs/nns/governance/src/storage/neurons.rs, rs/nns/governance/tests/README.md, rs/nns/governance/tests/fixtures/mod.rs, rs/nns/governance/tests/governance.rs, rs/nns/governance/tests/interleaving_tests.rs, rs/nns/governance/tests/merge_neurons.rs
The ability to assert on the entirety of the NNS Governance state was OK before, but as we have more and more data in stable storage, it becomes less feasible to do so. In particular now neurons live in the stable storage, so we won't be able assert on the neurons anyway.
* Remove (prop_)assert_changes and its invocations
* For `check_proposal_status_after_voting_and_after_expiration_new`, there is already a test `check_proposal_status_after_voting_and_after_expiration` which does the same thing except for asserting the global state changes.
=> test(nns): Remove (prop_)assert_changes

rs/pocket_ic_server/src/state_api/state.rs, rs/pocket_ic_server/tests/gateway.rs
This PR fixes PocketIC tests binding the PocketIC HTTP gateway to an invalid backend by the PocketIC server returning a platform-independent anchor ("upstream error") to be checked against in the tests.
=> fix(PocketIC): tests binding HTTP gateway to invalid backend

.github/workflows/schedule-weekly.yml
These credentials should no longer be needed as we migrated to ghcr
=> fix(fuzzing): Remove docker creds from the weekly fuzzing job

ci/scripts/rust-lint.sh
This passes `--keep-going` to `cargo clippy` causing it to check as much as possible and not fail on the first issue.
=> chore: pass `--keep-going` to `cargo clippy`

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
The comment doesn't apply anymore.
=> fix(IDX): Remove outdated reference to CI_MACOS_INTEL

.github/workflows-source/schedule-daily.yml, .github/workflows/schedule-daily.yml
All CI jobs succeeded, except for `Bazel Test NNS Nightly` which first timed out, then failed when I bumped the timeout up to 30min. However, it has also been failing on regular runs, so it's difficult to identify if this is related to it being run in dm1.
See failed run here: https://dash.dm1-idx1.dfinity.network/invocation/a1d7914e-e0ee-4657-b492-39383df7b73a
=> chore(IDX): remove zh1 pin from daily jobs

ic-os/components/networking/nftables/hostos/nftables.template
Running `bazel test --config=systest //rs/tests/nested:hostos_upgrade_smoke_test` from `dm1` was failing because the test failed to SSH to the HostOS VM because the connection was blocked by the HostOS' firewall. This commit opens up the firewall for dm1.
=> chore: allow dm1 in the HostOS firewall

rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/disburse_maturity_tests.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/neuron_data_validation.rs, rs/nns/governance/src/neuron_store/neuron_store_tests.rs, rs/nns/governance/src/storage/neuron_indexes.rs, rs/nns/governance/src/timer_tasks/mod.rs
Disburse maturity has been enabled for a while, clean up some code that's no longer needed
* Clean up the `is_disburse_maturity_enabled` flag
* Clean up a test that asserts `OldMaturityDisbursement` (from a previous version) can be successfully deserialized to the new version.
=> chore(nns): Clean up disburse maturity

rs/tests/message_routing/xnet/xnet_compatibility.rs
Due to doing two subnet upgrades during the test; and these upgrades sometimes taking multiple minutes to complete; the mean latency measured by the subnet that is running throughout can exceed the currently expected 60 seconds. Until we figure out the root cause of the slow upgrades, double the target latency.
=> fix: Bump the expected mean latency of the xnet_compatibility test

.github/actions/bazel-test-all/action.yaml, .github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
This adds the node names as annotations to the job steps. See example: https://github.com/dfinity/ic/actions/runs/15612912580?pr=5526
Please let me know if there's a better format so that we can query these later on.
=> feat(IDX): export node name to step annotation

rs/nns/governance/canister/canister.rs, rs/nns/governance/src/timer_tasks/mod.rs, rs/nns/governance/src/timer_tasks/neuron_data_validation.rs, rs/nns/governance/src/timer_tasks/unstake_maturity_of_dissolved_neurons.rs, rs/nns/governance/unreleased_changelog.md, rs/nns/integration_tests/src/governance_neurons.rs, rs/nns/test_utils/src/state_test_helpers.rs
The timer_tasks library uses canonical patterns to schedule timers, while exposing metrics about task execution. This will make it easier to monitor the tasks. In addition, with the new pattern, the `governance_mut()` unsafe accessor is avoided.
* Create new `PeriodicSyncTask` for `neuron_data_validation` and `unstake_maturity_of_dissolved_neurons`
* Remove existing scheduling in `canister.rs`
* Add a state machine test for `unstake_maturity_of_dissolved_neurons`
=> feat(nns): Use timer_tasks library for some timer tasks

.github/actions/bazel-test-all/action.yaml, third_party/jemalloc/BUILD.jemalloc.bazel
This reverts commit 0dba014c1883d02346e273bd59a4f61073f8ad08.
Because we use a different zig-cache for each bazel config, we do not expect jemalloc build failures.
=> revert: "fix(IDX): don't cache jemalloc build (#5174)"

rs/tests/nested/src/lib.rs
All Farm hosts have been upgraded to Ubuntu-24.04 which means all of them could now successfully host nested VMs. This means we no longer need to limit these tests to the `dm1` DC.
=> chore: allow running the nested system-tests on all farm hosts

rs/cross-chain/proposal-cli/src/canister/mod.rs
Follow-up on #5511 to fix the path to the built wasm artifact in the proposal-cli tool.
=> fix(XC): path to wasm for SOL RPC canister for proposal-cli

.github/actions/bazel/action.yaml, bazel/execution_log_compact_to_csv.py
The goal is to have as few non-reproducible bazel targets as possible because non-reproducible targets hurt cache utilisation and increase the risk of having non-reproducible final artifacts like guesOS images.
So we forbid all non-reproducible targets except for a few known ones which we can document and ideally link to an upstream ticket.
=> chore: require build determinism for all targets except a few exclusions

rs/nns/governance/src/governance.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/tests/fake.rs, rs/nns/integration_tests/src/node_provider_remuneration.rs
This removes the feature flag for a feature that has run successfully, and no longer needs to be gated behind a feature flag.
=> chore(nns): Cleanup USE_NODE_PROVIDER_REWARD_CANISTER flag and code

rs/nervous_system/tools/release-runscript/src/main.rs, testnet/tools/nns-tools/lib/sns_upgrades.sh
The order of SNS ledger suite canisters should be Index, Ledger, Archive. That is the intended order of upgrades for those canisters.
=> chore(governance): Fix order of SNS canisters and double quote some bash variables in release scripts

.github/actions/bazel/action.yaml
On 2025-05-15, after https://github.com/dfinity/ic/commit/1a0559dfaf00591d5e82e99ea5d59d3eb59460f3 the Schedule Rust Benchmarks [started failing](https://github.com/dfinity/ic/actions/runs/15034578789/job/42253845722#step:4:125) with:
```
ERROR: Error computing the main repository mapping: 
Error accessing registry https://bcr.bazel.build/: 
Failed to fetch registry file https://bcr.bazel.build/modules/rules_oci/2.0.0/MODULE.bazel: 
/cache/bazel/content_addressable/sha256/5d5cf1932238b009f874d5a9f214bbedf5d8cec8e5028e083f1147726876572f/tmp-b5ead0e6-c6a7-4c74-b416-919d96c41b1a 
(Permission denied)
```
This was because the owner of the `/cache` directory got recursively changed to 1001:1001 every time the jobs ran. On `fr1-spm15`, where the rust benchmarks run, 1001 maps to the `dfnadmin` …
=> fix: don't assume the current UID is 1001 to fix the schedule-rust-bench workflow

.github/workflows/slack-workflow-run.yml
This adds an alert for `Sync IC private from IC public` so we will be notified if it is broken (like it was last week).
This workflow will be triggered from `ic-private`, though because all workflows except for `Sync IC private from IC public` are disabled we should only receive alerts for this one.
If this alert fails and we start getting alerts every 10 minutes, we can always disable this `Slack Workflow Run` workflow in ic-private.
=> chore(IDX): add alerts for ic-private

Cargo.lock, packages/ic-metrics-assert/BUILD.bazel, packages/ic-metrics-assert/Cargo.toml, packages/ic-metrics-assert/src/lib.rs
(XC-296) Add a new async trait in `ic-metrics-assert` to fetch metrics via an asynchronous HTTP query.
=> feat: add trait in `ic-metrics-assert` to perform async HTTP query

rs/tests/consensus/subnet_recovery/BUILD.bazel
The mainnet version of test should now pass as well, after the registry was upgraded to support chunking with proposal [136988](https://dashboard.internetcomputer.org/proposal/136988)
=> chore: Reenable large subnet recovery test

rs/state_manager/src/lib.rs
Reverts dfinity/ic#5573
This is breaking the nightly backup test, which is trying to detect a state divergence after modifying a checkpoint file: https://github.com/dfinity/ic/actions/runs/15697333995
=> revert: "chore: [MR-600] Enable incremental manifest computation on the NNS"

packages/ic-metrics-assert/CHANGELOG.md, packages/ic-metrics-assert/README.md
(XC-296) Add release date for v0.1.0 in `ic-metrics-assert` `CHANGELOG.md`.
=> chore: add date to `ic-metrics-assert` change log

ci/container/container-run.sh
`ci/container/container-run.sh` called `podman` with the following bind mounts:
* `--mount type=bind,source="${ZIG_CACHE}",target="/tmp/zig-cache"` where `${ZIG_CACHE} = ~/.cache/zig-cache`
* `--mount type=bind,source="/tmp",target="/tmp"`
This causes an issue on `zh1-spm{22,34}` which is exemplified by the following: 
```
bas@zh1-spm22:~/d/ic/ic$ sudo rm -rf /tmp/zig-cache/
bas@zh1-spm22:~/d/ic/ic$ ci/container/container-run.sh echo
+ exec sudo podman run --pids-limit=-1 -i -t --log-driver=none --rm --privileged --network=host --cgroupns=host -w /ic -u 1017:1017 -e HOSTUSER=bas -e VERSION=ac7ff452684f84ea0cfc3fd0a27228220a368b33 --hostname=devenv-container --add-host devenv-container:127.0.0.1 --entrypoint= --init --pull=missing --mount type=bind,source=/home/bas/d/ic/ic,target=/ic …
```
=> fix: remove /tmp mount in container-run.sh to prevent shadowing

rs/tests/consensus/subnet_recovery/BUILD.bazel, rs/tests/consensus/upgrade/BUILD.bazel
These tests were temporarily disabled because of DNS resolution issues when attempting to download the upgrade images in the testing environment. It seems that this was fixed by updating related DNS records.
I [ran](https://github.com/dfinity/ic/actions/runs/15711630457) the hourly tests three times and they succeeded always.
=> test: Re-enable Consensus hourly tests

Cargo.lock, packages/icrc-ledger-types/BUILD.bazel, packages/icrc-ledger-types/Cargo.toml
Remove unused `ic-cdk` dependency from `icrc-ledger-types`.
=> chore(ICRC_Ledger): FI-1770: Remove unused ic-cdk dependency from icrc-ledger-types

Cargo.lock, rs/tests/consensus/upgrade/BUILD.bazel, rs/tests/consensus/upgrade/Cargo.toml, rs/tests/consensus/upgrade/common.rs, rs/tests/consensus/upgrade/upgrade_downgrade_app_subnet_test.rs
Downgrading a replica must always work. Prior to this PR, the downgrade test did not contain any canister snapshot, so any forwards-incompatibility in the snapshot format would not be detected. This PR fixes that gap.
=> chore: [EXC-2066] Add a snapshot to upgrade/downgrade tests.

Cargo.lock, packages/icrc-ledger-types/CHANGELOG.md, packages/icrc-ledger-types/Cargo.toml
The version includes the change to remove the unneeded dependency to `ic-cdk`.
=> chore(icrc-ledger-types): create a new version for release

bazel/hermetic_cc_toolchain.patch
This modifies our hermetic_cc_toolchain patch to have the zig-wrapper be built with `/tmp/zig-cache/config-catchall` instead of `/tmp/zig-cache`. This prevents the build using different levels of directories and ensures the cache is always nested under `/tmp/zig-cache/config-FOO`.
=> chore(IDX): use catchall subdirectory for zig wrapper build

rs/ic_os/os_tools/hostos_tool/src/main.rs
We never use it and it overlaps with help.
=> fix: Remove short argument name (-h) for hostos_config_object_path

ic-os/hostos/defs.bzl, rs/ic_os/os_tools/hostos_tool/BUILD.bazel, rs/ic_os/release/BUILD.bazel
This is a temporary solution to fix some tests until we have a better solution that automatically pulls in dev binaries into dev images.
=> fix: Deploy dev version of hostos_tool in dev HostOS

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
This changes the CI jobs for fuzzers to be built with the simple `bazel` action instead of `bazel-test-all`. The fuzzers are only being built and don't actually run `bazel test`.
This does mean that the `diff` script is not being used and the full build will "run" every time, though in case of a cached build this only involves downloading ~20 targets and the whole job takes less than 2 minutes to run.
=> chore(IDX): Use simple action for fuzzers build

bazel/hermetic_cc_toolchain.patch, rs/replay/src/player.rs
To achieve this we modify the `wait_for_state` which instead of waiting until the hash of the state at the given height is computed, we now call the [StateManager::flush_tip_channel](https://github.com/dfinity/ic/blob/9734b186d658df38dabdfaf356b5fcccae668de5/rs/state_manager/src/lib.rs#L1156-L1158) function which blocks until the most recent checkpoint is created and verified. Previously we were waiting for the hash of the _latest_ state, but if the latest state height was not a checkpoint height, the function would return early without waiting for a checkpoint to be computed (https://github.com/dfinity/ic/blob/66dc6048dd854d3215e9097802f688afc56ef4c9/rs/replay/src/player.rs#L1610-L1622). 
Sample logs:
```
(...)
Validated artifacts up to new finalized height: 291
Validated artifacts up to …
```
=> fix(ic-backup): always wait until the most recent checkpoint has been created and verified, and manifest created 

Cargo.lock, rs/ledger_suite/icrc1/index-ng/tests/tests.rs, rs/ledger_suite/icrc1/test_utils/BUILD.bazel, rs/ledger_suite/icrc1/test_utils/Cargo.toml, rs/ledger_suite/icrc1/test_utils/src/lib.rs, rs/ledger_suite/tests/sm-tests/src/in_memory_ledger.rs, rs/ledger_suite/tests/sm-tests/src/lib.rs, rs/rosetta-api/icp/BUILD.bazel, rs/rosetta-api/icp/tests/system_tests/common/system_test_environment.rs, rs/rosetta-api/icp/tests/system_tests/test_cases/account_balances.rs, rs/rosetta-api/icp/tests/system_tests/test_cases/transfers.rs, rs/rosetta-api/icrc1/src/construction_api/services.rs, rs/rosetta-api/icrc1/src/construction_api/utils.rs, rs/rosetta-api/icrc1/tests/integration_test_components/storage/storing_blockchain_data_test.rs, rs/rosetta-api/icrc1/tests/multitoken_system_tests.rs, rs/rosetta-api/icrc1/tests/system_tests.rs
Currently, the `valid_transaction_strategy` proptest helper has generated `mint`, `burn`, `transfer`, and `approve` transactions. This PR proposes to enhance it to also generate `transfer_from` transactions.
=> test(Ledgers): FI-1459: Add transfer_from to valid_transactions_strategy

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml, bazel/conf/.bazelrc.build
Similarly to #5642, this removes the `--config=macos_ci` special config used by `build` commands.
The only option set (ignoring system & fuzz tests) is already set in the top-level `build` command.
=> chore(IDX): Remove bazel macos-ci config

.github/actions/bazel/bin/bazel
Bazel profile analyzers like [EngFlow/bazel_invocation_analyzer](https://github.com/EngFlow/bazel_invocation_analyzer) work better if actions in the profile include target labels. So this enables [`--experimental_profile_include_target_label`](https://bazel.build/reference/command-line-reference#common_options-flag--experimental_profile_include_target_label).
The tool also recommends [`--noslim_profile`](https://bazel.build/reference/command-line-reference#common_options-flag--slim_profile) but that causes the `profile.json` to grow to ~948M which is a tad too excessive.
Running `bazel_invocation_analyzer` on the profile generated by this PR results in:
```
bas@devenv-bas:~/d/bazel_invocation_analyzer$ bazel run //cli -- --mode=all_data,used_data,suggestions ~/profile-1750342458.json …
```
=> chore: include target labels in bazel profiles

rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
This is a tiny error string correction in a test. Otherwise, no behavior change.
=> test(nns): Mention `node-rewards` is implied by `all` in NNS upgrade test.

.github/actions/bazel/action.yaml, .github/workflows-source/release-testing.yml, .github/workflows/release-testing.yml
This changes the `release-testing.yml` workflow to use the simpler `bazel` action, as the workflow does not require `bazel-test-all`'s bells and whistles. It also merges the system test jobs into one job, parametrized via build strategy. Finally, the jobs are changed to use the `stamped` config to ensure the actual to-be-released artifacts are used.
=> chore(IDX): Simplify release-testing workflow

rs/crypto/internal/crypto_lib/bls12_381/vetkd/benches/vetkd.rs, rs/crypto/internal/crypto_lib/bls12_381/vetkd/src/lib.rs, rs/crypto/internal/crypto_lib/bls12_381/vetkd/tests/tests.rs, rs/crypto/src/vetkd/mod.rs, rs/crypto/test_utils/vetkd/src/lib.rs
This condition cannot occur due to how our callers are implemented, but it is worth being resilient to the issue in case the vault implementation changes in the future.
=> chore(crypto): CRP-2831 Modify VetKD to be robust about duplicated node shares

rs/registry/admin/src/main.rs
We are switching from a monolithic routing table to multiple smaller registry entries. This PR changes ic-admin from reading to the old value to the new ones.
* Use `NnsDataProvider` to poll registry entries, select the keys through `get_key_family`, and read the values based on the keys.
The `ic-admin get-routing-table` yields the exact same result before and after the change.
=> feat(ic-admin): Use canister_ranges_ keys to read routing table

Cargo.lock, rs/execution_environment/Contributing.md, rs/types/management_canister_types/BUILD.bazel, rs/types/management_canister_types/Cargo.toml, rs/types/management_canister_types/tests/candid_equality.rs, rs/types/management_canister_types/tests/ic.did
This PR ports the candid equality test from [cdk-rs](https://github.com/dfinity/cdk-rs/blob/5ef8e6ab2911e1dccceaaba9839999c7bbe15568/ic-management-canister-types/tests/candid_equality.rs) to this repository. This is supposed to prevent regressions like [this](https://github.com/dfinity/ic/pull/5662). The following missing management canister APIs are left for future work: VetKD, bitcoin, snapshot upload/download.
=> test: add test for candid types of management canister types

.github/actions/bazel/action.yaml, .github/workflows-source/release-testing.yml, .github/workflows/release-testing.yml
This drops the `matrix` and merges all 3 kinds of system tests into a single job. This means the codebase doesn't have to be built 3 times and simplifies the workflow.
Originally discussed here: https://github.com/dfinity/ic/pull/5655#discussion_r2161555423
=> chore: merge release-testing system tests

.github/workflows-source/schedule-hourly.yml, .github/workflows/schedule-hourly.yml
This changes the `build-all-no-cache` job to call bazel directly, instead of calling `bazel-test-all`.
=> chore: simplify build-all-no-cache command

rs/tests/nested/BUILD.bazel, rs/tests/nested/src/lib.rs, rs/tests/nested/src/util.rs
Make the node go through an HTTP gateway when trying to submit the join request to the NNS. This reflects the mainnet behavior.
=> chore: use HTTP gateway for nested registration test

.github/workflows-source/schedule-daily.yml, .github/workflows/schedule-daily.yml, rs/tests/system_tests.bzl
This replaces the `bazel query` previously used in daily/nightly benchmarks with test tag filters.
=> chore: filter out head nns benchmarks by tag

rs/ledger_suite/icrc1/ledger/BUILD.bazel
We've seen this test timeout a couple times. Instead of marking it as flaky, increase the timeout.
=> chore(IDX): bump timeout for ledger_test

Cargo.Bazel.Fuzzing.json.lock, Cargo.Bazel.Fuzzing.toml.lock, Cargo.Bazel.json.lock, Cargo.Bazel.toml.lock, Cargo.lock, Cargo.toml, bazel/external_crates.bzl, ic-os/defs.bzl, ic-os/tests/BUILD.bazel, rs/ic_os/config/build.rs, rs/ic_os/config/golden/guestos_vm_kvm.xml, rs/ic_os/config/golden/guestos_vm_sev.xml, rs/ic_os/config/src/guest_vm_config.rs, rs/ic_os/config/templates/guestos_vm_template.xml, rs/ic_os/os_tools/hostos_tool/BUILD.bazel, rs/ic_os/os_tools/hostos_tool/Cargo.toml, rs/ic_os/os_tools/hostos_tool/src/boot_args.rs, rs/ic_os/os_tools/hostos_tool/src/guest_direct_boot.rs, rs/ic_os/os_tools/hostos_tool/src/guest_vm.rs, rs/ic_os/os_tools/hostos_tool/src/main.rs, rs/ic_os/os_tools/hostos_tool/src/mount.rs, rs/ic_os/os_tools/hostos_tool/src/systemd_notifier.rs
This PR adds support for QEMU direct boot and adds SEV config options to the VM XML config when SEV is enabled in the HostOSConfig. QEMU direct boot is enabled regardless of the config.
Since direct boot will skip the GRUB bootloader, the logic from the existing GuestOS grub.cfg was moved into the HostOS VM runner (`prepare_direct_boot` in `guest_direct_boot.rs`). The code mounts the grub and boot partitions of the guest, updates the grubenv, extracts the necessary files and kernel command line and returns these.
An interesting complication is that older GuestOS releases don't have the boot_args file and so don't support direct boot. In this case we need to fall back to booting with GRUB. In this case, we must not update the grubenv, since the GRUB bootloader will update it again and it's …
=> feat: Support SEV config and direct boot in the VM runner

rs/ic_os/os_tools/guest_vm_runner/src/main.rs, rs/ic_os/os_tools/guest_vm_runner/src/mount.rs
Make `ExtractingFilesystemMounter` act persistently, so mounting the same partition multiple times should return the same directory. This is closer to reality, since changes in a mounted filesystem should be visible when the same partition is mounted again.
=> test: Improve fake mounter with persistent mounts

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
The PATH doesn't need to be updated since all tools come from Bazel.
=> chore: don't set amd64-darwin PATH

rs/ic_os/os_tools/guest_vm_runner/BUILD.bazel
Two mistakes slipped in into the guest_vm_runner BUILD rule config, this PR fixes them.
=> fix: guest_vm_runner build rules

ic-os/defs.bzl, rs/ic_os/os_tools/guest_vm_runner/BUILD.bazel, toolchains/sysimage/build_disk_image.py, toolchains/sysimage/toolchain.bzl
The difference between this image and the regular published image is that we populate the B partitions which are otherwise empty (to reduce the file size of the target).
=> test: Introduce new IC-OS image target that can be used in tests

.github/actions/bazel-test-all/action.yaml, .github/workflows-source/release-testing.yml, .github/workflows/release-testing.yml, bazel/conf/.bazelrc.build
This extracts some CLI arguments used in `bazel-test-all` into a new configuration option, `flake_retry`. When enabled, some tests known to be flaky (those explcitly marked as such and those in `//rs/tests`) to be retried automatically.
The configuration is also applied to the release testing workflow.
=> chore: add flaky_retry bazel configuration

rs/execution_environment/src/canister_settings.rs, rs/execution_environment/src/canister_settings/tests.rs, rs/state_layout/src/state_layout/tests.rs, rs/types/management_canister_types/src/lib.rs
Modified the hash function of environment variables to return a [u8; 32] array instead of a Vec<u8> for fixed-size output.
=> chore: Environment Variables hash return value from vec to [u8, 32]

rs/rosetta-api/icp/BUILD.bazel
A [recent PR](https://github.com/dfinity/ic/pull/5592) introduced some flakiness to the `test_cases::search_transactions::test_search_transactions_by_account` test. While investigating the issue, mark the test as flaky.
=> test(ICP_Rosetta): FI-1779: Mark ICP Rosetta system tests flaky

rs/bitcoin/ckbtc/minter/src/lib.rs, rs/bitcoin/ckbtc/minter/src/main.rs, rs/bitcoin/ckbtc/minter/src/state.rs, rs/bitcoin/ckbtc/minter/tests/tests.rs
An estimated median fee of 142 millistatoshis per vbyte for Bitcoin Mainnet was used during approximatively 30min, from 2025.06.21 01:09:50 UTC until 2025.06.21 01:39:00 UTC. However, the median fee around that time should have been in the order of 2000 millistatoshis per vbyte. This extremely low fee led to several transactions not being mined and triggered the discovery of another bug fixed in #5713, which currently prevents transaction from being resubmitted.
Until we know the root cause for this low fee, this PR ensures that the estimated median fee is at least 1500 millisatoshis per vbyte (for Bitcoin Mainnet). The current median fee per vbyte in the last 6 months shows that only in rare occurrences the median fee was lower than this value, therefore incurring only a minimal …
=> fix(ckbtc): Ensure minimum fee per vbyte

rs/nervous_system/agent/src/agent_impl.rs, rs/nervous_system/agent/src/lib.rs, rs/nervous_system/agent/src/management_canister/requests.rs, rs/nervous_system/agent/src/pocketic_impl.rs, rs/nervous_system/integration_tests/tests/upgrade_sns_controlled_canister_with_large_wasm.rs
This PR adds an optional function `effective_canister_id` to `trait Request`, so that implementations can rely on the effective canister IDs to route special requests (e.g., those to the management canister) that cannot always be routed automatically.
=> chore(nervous-system-agent): Support `effective_canister_id` in `trait Request` to enable routing management canister calls

rs/sns/governance/canbench/canbench_results.yml, rs/sns/governance/src/governance.rs, rs/sns/governance/src/icrc_ledger_helper.rs, rs/sns/governance/unreleased_changelog.md
This PR fixed a problem with Candid decoding of `Nat` to `u64` that didn't correctly handle `0`.
Also, release notes are edited.
=> fix(sns): Ensure Candid decoding of `Nat` to `u64` correctly handles `0`

rs/state_manager/src/lib.rs, rs/state_manager/src/tip.rs, rs/state_manager/tests/state_manager.rs
This PR splits `reset_tip_to` and `merge` into individual metrics and renames some metrics to reflect the code changes.
=> chore: Improve checkpointing metrics

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
This adds some test targets to the arm64-darwin build to align it with the arm64-linux pocket IC CI builds.
=> chore: run pocket-ic tests on arm64-darwin

.github/workflows/ci-pr-only-nns-team-reminder.yml
=> fix(governance-tools): Escape ` in the the "Governance Unreleased Changelog Reminder" script

rs/registry/canister/src/mutations/routing_table.rs, rs/registry/canister/src/registry_lifecycle.rs
The migration code is one-off and has been run. Therefore we can clean it up.
=> chore(nns): Clean up migration code for canister ranges

rs/nns/governance/api/src/types.rs, rs/nns/governance/canister/governance.did, rs/nns/governance/canister/governance_test.did, rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron_store/metrics.rs, rs/nns/governance/src/neuron_store/metrics/tests.rs, rs/nns/governance/src/pb/conversions.rs, rs/nns/governance/tests/governance.rs, rs/nns/governance/unreleased_changelog.md
As NNS Dap switches from spawning neurons to disbursing maturity, it would be interesting to monitor its impact on the number of spawning neurons.
* Aggregate `spawning_neurons_count` when iterating through neurons in `compute_cached_metrics`
* Add `spawning_neurons_count` to both cached metrics and metrics, and pass the cached metric to metric
* Encode `governance_spawning_neurons_count` in the metrics endpoint
=> feat(nns): Add a metric for the number of spawning neurons

rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/tests/mod.rs, rs/nns/governance/src/governance/voting_power_snapshots.rs, rs/nns/governance/src/governance/voting_power_snapshots_tests.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron_store/voting_power.rs, rs/nns/governance/src/pb/conversions.rs, rs/nns/governance/src/storage.rs, rs/nns/governance/src/timer_tasks/snapshot_voting_power.rs, rs/nns/governance/unreleased_changelog.md, rs/nns/integration_tests/src/governance_proposals.rs, rs/nns/integration_tests/src/lib.rs
To prevent a sudden takeover of the NNS in the event of some party gaining illegitimate voting power (e.g. a bug in Governance, ICP Ledger, etc.), we aim at disabling the early adoption of NNS proposals if the voting power has a spike, which should give the network more time to react and recover in such cases.
There are 3 PRs to achieve the above-mentioned goal:
- (#4404) Define VotingPowerSnapshot and a collection of snapshots
- (#4405) Add a timer task to record snapshots periodically
- (current PR) Use the previous snapshot if a voting power spike is detected
=> feat(nns): Use a previous snapshot for ballots if an unusually high voting power is detected

rs/tests/ict/cmd/helpers.go
Previously, all of our testnets were placed in the `tests/testnets` directory. Since that is no longer the case, this PR adapts logic to properly discover the correct target by looking for `:<target>` in the response of:
```bash
bazel query attr(tags, 'dynamic_testnet', tests(//rs/tests/...)
```
This results in the following:
```bash
ict testnet create small --lifetime-mins 10 # Valid, will match //rs/tests/testnets:small
ict testnet create canister_http_soak_test --lifetime-mins 10 # Valid, will match //rs/tests/networking:canister_http_soak_test`
ict testnet create blahblahblah --lifetime-mins 10 # Invalid, will not match anything.
```
=> fix: properly make fully qualified target from a suffix

rs/sns/testing/BUILD.bazel
The test sometimes times out on CI with the default timeout of 5 minutes (moderate) so we bump it to 15 minutes (long).
Note: on a local Linux runner the test takes ~1mn to run which is not close to the timeout; the test might however be sensitive to machine load.
=> chore: increase sns_testing_ci timeout

rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs
https://github.com/dfinity/ic/pull/5530 introduced the `SignerCanister` allowing us to generate signature requests as part of the canister itself, instead of sending them as an ingress message.
However, responses of the `SignerCanister` are currently always interpreted as successful, even if the actual signature request failed (i.e., because the request queue was full). This is skewing the results of the benchmark (see [here](https://grafana.testnet.dfinity.network/d/crypto-benchmarks-criterion-tecdsa/tecdsa?from=now-30d&to=now&var-datasource=es-logs-ci-performance) for instance). Therefore, we temporarily revert to the `MessageCanister`.
=> fix(tests): Temporarily revert chain key performance tests back to `MessageCanister`

rs/rosetta-api/icp/BUILD.bazel, rs/rosetta-api/icp/tests/system_tests/test_cases/search_transactions.rs
Ignore the `spender` account in `transfer_from` and `burn` operations when searching for transactions by account in Rosetta. This is because the account balance of the `spender` is not affected in a `transfer_from` and `burn`, so no Rosetta operation is created for the spender. In this case, only `approve` transactions will be found when searching for the `spender` account.
=> test(ICP_Rosetta): FI-1779: Ignore spender in transfers in search_transactions_by_account

packages/pocket-ic/BUILD.bazel
We've seen the test time out on CI and we suspect the test might be sensitive to machine load. Here we bump the timeout from 5mn to 15mn. Locally, the test seems to run in under 1mn.
=> chore: bump pocket-ic test timeout

rs/nns/handlers/root/impl/BUILD.bazel, rs/nns/handlers/root/impl/Cargo.toml, rs/nns/handlers/root/impl/src/root_proposals.rs, rs/nns/handlers/root/unreleased_changelog.md
Routing table is changed from a single record in the registry to multiple sharded records. Therefore, it's no longer feasible to read a single registry value for the NNS Subnet id. Instead, call registry to look up the subnet id.
Change `Registry::get_value` call to `Registry::get_subnet_for_canister`, to get the NNS subnet id.
The test target `//rs/nns/integration_tests:integration_tests_src/root_proposals` fails if the NNS Subnet retrieved from registry is incorrect
=> feat(nns): Change root proposal to call Registry::subnet_for_canister instead of reading from routing table

rs/nns/integration_tests/src/registry_get_changes_since.rs, rs/nns/test_utils/src/registry.rs, rs/registry/canister/src/mutations/routing_table.rs, rs/registry/canister/tests/modify_canister_migrations.rs, rs/registry/canister/tests/reroute_canister_ranges.rs, rs/registry/canister/tests/roll_back_canister_migration.rs
Routing table format is being changed from a single value to sharded values. This PR sets up the sharded routing table in addition to the single routing table.
=> test(registry): Set up sharded routing table in registry tests

rs/execution_environment/tests/canister_history.rs
This PR hardens canister history tests by overriding controllers with a list containing repeated controllers and asserting that canister history is updated with a sorted and deduplicated list.
=> test: harden canister history tests by providing duplicate controllers

Cargo.lock, rs/ic_os/os_tools/guest_vm_runner/BUILD.bazel, rs/ic_os/os_tools/guest_vm_runner/Cargo.toml, rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_kvm.xml, rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_qemu.xml, rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_sev.xml, rs/ic_os/os_tools/guest_vm_runner/golden/upgrade_guestos.xml, rs/ic_os/os_tools/guest_vm_runner/src/main.rs, rs/ic_os/os_tools/guest_vm_runner/src/systemd_notifier.rs, rs/ic_os/os_tools/guest_vm_runner/templates/guestos_vm_template.xml
With the "restart" libvirt setting, the VM is restarted using the same direct boot args as it was used to start with. This is obviously wrong and breaks upgrades where changing the boot params is necessary.
This fix doesn't allow QEMU to restart the VM but rather adds support in the guest_vm_runner to recreate the VM with a brand new configuration.
=> fix: Fix the reboot behavior of GuestVM

publish/canisters/BUILD.bazel, rs/ledger_suite/icp/ledger.did, rs/ledger_suite/icp/ledger/src/main.rs, rs/ledger_suite/icp/src/lib.rs, rs/ledger_suite/icp/test_utils/src/state_machine_helpers/ledger.rs
The candid equivalent of the `tip_of_chain_pb` protocol buffer endpoint.
=> feat(ICP-Ledger): FI-1795: add candid tip_of_chain endpoint

rs/tests/consensus/tecdsa/tschnorr_message_sizes_test.rs, rs/tests/consensus/tecdsa/utils/src/lib.rs, rs/tests/driver/src/util.rs
#5853 just got merged and led to a [regression](https://github.com/dfinity/ic/actions/runs/16197096606/job/45726302061). It fixed the signer canister interface to always return a signature, or reject the call if that is not possible, as opposed to returning an `Ok`/`Err` but I had forgotten to adapt the Rust `SignerCanister` API to reflect this change. I'll use `CI_ALL_BAZEL_TARGETS` next time...
This PR fixes this. Now the API of `MessageCanister` and `SignerCanister` are similar, since `SignerCanister` no longer returns a `Result` (i.e. `forward_to` and `gen_ecdsa_sig`/`gen_schnorr_sig`/`gen_vetkd_key` have the same function signatures).
=> fix(test): fix Rust SignerCanister API

rs/registry/canister/canister/canister.rs, rs/registry/canister/canister/registry.did, rs/registry/canister/canister/registry_test.did, rs/registry/canister/src/mutations/do_create_subnet.rs, rs/registry/canister/unreleased_changelog.md
It didn't return anything before. I don't think this was intentional. This is helpful for subnet rental, because Governance wants to tell the Subnet Rental canister about the subnet that was created for a rental.
This changes a return type from being `()` (zero element tuple) to `(SomeResult)` (one elment tuple), which is pretty unusual. It is reasonable to question, "Wait, is that ok?". According to the following experiment, it is:
```
$ echo '
type Request = record {};
service : () -> {
create_subnet : (Request) -> ();
}
' > previous.did
echo '
type Request = record {};
type Result = variant {
Ok;
Err;
};
service : () -> {
create_subnet : (Request) -> (Result);
}
' > next.did
echo
echo -n "evolving from previous to next: "
if didc check next.did previous.did
then
echo OK
else
echo …
```
=> feat(registry): Make Registry.create_subnet return the ID of the new subnet.

Cargo.lock, rs/registry/canister/BUILD.bazel, rs/registry/canister/Cargo.toml, rs/registry/canister/canbench/canbench_results.yml, rs/registry/canister/src/certification.rs, rs/registry/canister/src/flags.rs, rs/registry/canister/src/invariants/routing_table.rs, rs/registry/canister/src/invariants/subnet.rs, rs/registry/canister/src/mutations/routing_table.rs, rs/registry/canister/src/mutations/routing_table_benches.rs
In order to determine the number of canister migrations we can allow as well as making sure whatever capacity we allow won't degrade unexpectedly, we add benchmarks for each of the constraints limiting the number of canister migrations we can have: (1) canister upgrade instruction limit (2) migrate canister as an update call (3) routing table lookup as query call
* Avoid performing certain operations when benchmarking
* Do not set certified data
* Do not fail invariants check when there are no system subnet
* Add a flag for deprecating the old routing table record and set it to true in benchmarks
* (main) Add benchmarks for the 3 operations mentioned above, for 100|1000|10000 canister migrations.
=> perf(registry): Benchmark for canister migration

rs/bitcoin/replica_types/src/lib.rs
Refactor the handling of type conversion to use definitions from protobuf instead of hardcoded i32.
=> refactor: better network enum conversion in ic-btc-replica-types

.devcontainer/devcontainer.json, ci/container/container-run.sh
Previously we used to mount the whole `/tmp` dir into the container image which was pretty convenient for sharing files among containers. after #5601 we stopped doing that because it conflicts with other requirements. 
This PR mounts back at least `/tmp/ict_testnets` which is used as default dir for ict log output.
=> fix: mount back ict_testnets dir into the local container

rs/execution_environment/src/canister_settings.rs, rs/execution_environment/tests/storage_reservation.rs
If the memory allocation field in canister settings is `None`, then the memory allocation does not change and thus the new memory bytes should be equal to the old memory bytes (instead of the actual memory usage which is only accurate if the canister has best-effort memory allocation).
Given how the value of `new_memory_bytes` is used, this fix does not change the current behavior of canister settings validation. But it still makes sense to fix the value to make the code more robust for future refactorings.
Justification.
- For canisters with best-effort memory allocation, this PR does not change the value of `new_memory_bytes`.
- For canisters with reserved memory allocation and memory usage not exceeding the reserved memory allocation, this PR increases the value of `new_memory_bytes` …
=> fix: new memory bytes if no change of memory allocation is requested

rs/nervous_system/agent/src/sns/root.rs, rs/sns/cli/src/upgrade_sns_controlled_canister.rs, rs/sns/init/src/lib.rs, rs/sns/integration_tests/src/root.rs, rs/sns/integration_tests/src/timers.rs, rs/sns/root/canister/canister.rs, rs/sns/root/canister/root.did, rs/sns/root/proto/ic_sns_root/pb/v1/root.proto, rs/sns/root/src/gen/ic_sns_root.pb.v1.rs, rs/sns/root/src/lib.rs, rs/sns/root/src/types.rs, rs/sns/root/unreleased_changelog.md
This PR adds a new function `Root.register_extension`, that allows registering SNS extensions. For context, the first SNS extension will be the [SNS Liquidity Pools extension](https://forum.dfinity.org/t/sns-liquidity-pools-design/50439).
=> feat(sns): add `Root.register_extension`

rs/tests/driver/src/driver/nested.rs, rs/tests/driver/src/driver/test_env_api.rs, rs/tests/driver/src/driver/universal_vm.rs
`SshSession` implementations were quite repetitive, this PR refactors the trait and removes the duplication
In addition, it also adds a new method `get_guest_ssh` which allows sending SSH commands to the GuestVM in nested tests.
=> test: Refactor SshSession trait and add Guest SSH to NestedVm

rs/consensus/idkg/src/complaints.rs, rs/consensus/idkg/src/payload_builder.rs, rs/consensus/idkg/src/payload_builder/key_transcript.rs, rs/consensus/idkg/src/payload_builder/pre_signatures.rs, rs/consensus/idkg/src/payload_builder/resharing.rs, rs/consensus/idkg/src/payload_verifier.rs, rs/consensus/idkg/src/pre_signer.rs, rs/consensus/idkg/src/signer.rs, rs/consensus/idkg/src/test_utils.rs, rs/consensus/idkg/src/utils.rs, rs/test_utilities/consensus/src/idkg.rs, rs/types/types/src/crypto.rs
This is cleaner and avoids some duplication of `algorithm_for_key_id` functions.
=> chore: Implement `From<MasterPublicKeyId>` for `AlgorithmId`

rs/nns/governance/canbench/canbench_results.yml, rs/nns/governance/src/governance/voting_power_snapshots_benches.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/unreleased_changelog.md
The voting power spike detection mechanism depends on a timer task which takes a snapshot of voting power every day. If the timer task fails silently, then the mechanism will not work correctly. Therefore we should be able to detect when the snapshots are getting stale.
Expose a metric `governance_voting_power_snapshots_time_since_latest_snapshot_seconds`
=> feat(nns): Add a staleness metric for voting power snapshots

.github/workflows/update-mainnet-revisions.yaml, Cargo.lock, WORKSPACE.bazel, bazel/mainnet-canisters.bzl, mainnet-canister-revisions.json, rs/nervous_system/tools/sync-with-released-nervous-system-wasms/BUILD.bazel, rs/nervous_system/tools/sync-with-released-nervous-system-wasms/Cargo.toml, rs/nervous_system/tools/sync-with-released-nervous-system-wasms/src/main.rs
This PR adds support for external mainnet canisters in the bazel workspace.
In more detail, this PR
- represents external mainnet canisters by their git tag in the mainnet canister json file;
- updates that git tag automatically using the existing bot for NNS canisters extended to
- crawl all git tags of the corresponding (hard-coded) external repository (e.g., `dfinity/cycles-ledger`);
- for every git tag, list all release assets;
- look for a release asset whose name has the form `{canister_name}.sha256` where `canister_name` is hard-coded (e.g., `cycles-ledger.wasm.gz`);
- if that release asset starts with the expected module hash of the external canister (as fetched from the ICP mainnet using an IC agent), then the corresponding tag is updated in the mainnet canister json file;
- uses …
=> feat: support for external mainnet canisters in the bazel workspace

rs/tests/consensus/tecdsa/BUILD.bazel, rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs
To ensure consistent performance we configure the IC nodes in the tecdsa performance tests to be only allocated to Dell Farm hosts in dm1 (of which we have 34). The rest of the VMs (for the colocated test driver and for the PrometheusVM) will be allocated to Supermicros (of which we have 9) to leave as much room as possible for IC nodes.
Running `ict test tecdsa_performance_test_colocate` indeed results in the expected VM allocation:
```
farm=# 
SELECT
vms.hostname      AS host, 
vms.display_name  AS vm, 
vms.spec->'vCPUs' AS vcpus 
FROM 
vms, 
groups 
WHERE 
vms.group_id = groups.id 
AND groups.display_name LIKE 'tecdsa_performance_test%';
host              |                               vm                                | vcpus …
```
=> chore: run IC nodes in tecdsa performance tests on Dells

packages/pocket-ic/src/lib.rs
This PR distinguishes between arm64 and x86_64 when downloading PocketIC server in the PocketIC library so that the downloaded binary works on arm64 architectures, too. This PR has been manually tested on macOS/arm64, linux/arm64, and linux/x86_64.
=> fix(PocketIC): distinguish between arm64 and x86_64 when downloading PocketIC server

rs/nns/governance/src/governance/voting_power_snapshots.rs, rs/nns/governance/src/governance/voting_power_snapshots_tests.rs, rs/nns/governance/unreleased_changelog.md
If the voting power spike detection mechanism has a false positive, we will need to remove most of the voting power snapshots so that new voting power will be considered normal. In that case, we don't want the detection mechanism to be inactive, which would be the case if we only detect spikes if the voting power snapshots are full. The "fullness" check was added to get around the check in tests, but as @andrew-lee-work pointed out, we can limit the check for tests.
In production code, do not skip the voting power spike detection when the snapshots are not full.
=> feat(nns): Keep the voting power spike detection when the snapshots are not full

rs/http_utils/src/file_downloader.rs
This change adds extra progress logging during response body streaming in `file_downloader.rs`, to help debug slow downloads in system tests involving replica version upgrades/downgrades.
A concrete use case is investigating flakiness in `//rs/tests/message_routing/xnet:xnet_compatibility`, where slow downloads still occasionally occur, even after recent DNS-related fixes. In these cases, connections are successfully established, but streaming is sluggish or stalls unpredictably. E.g., on July 9th, there was a run where one download took 345 seconds (which is 1-2 orders of magnitude over what's to be expected from normal runs):
=> feat: Extra progress logging for response body streaming in `file_downloader.rs`

rs/consensus/idkg/src/payload_builder/resharing.rs, rs/consensus/idkg/src/payload_verifier.rs, rs/consensus/src/consensus/batch_delivery.rs, rs/types/management_canister_types/src/lib.rs
This is Part 2 of the `compute_initial_i_dkg_dealings` endpoint removal, following #5866.
This PR:
- Removes `ComputeInitialIDkgDealingsResponse` and the special cases regarding it's decoding
- Removes the `ComputeInitialIDkgDealignsArgs`, which are no longer in use
- Adapts 2 tests, which were still not migrated
=> chore(CRP-2613): Remove deprecated compute_initial_i_dkg_dealings endpoint Pt. 2

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml, bin/fuzzing/run-all-fuzzers.sh
This updates the Run Fuzzers workflow to use the bazel action, which ensures build artifacts are uploaded to the Bazel cache.
This seems to have been overlooked when the job was ported from the hourly pipeline to the main workflow.
=> fix: build fuzzers with bazel action

packages/pocket-ic/BUILD.bazel, packages/pocket-ic/tests/tests.rs
This PR fixes PocketIC test flakiness when killing PocketIC server: the tests now explicitly wait until a checkpoint is written to disk before force killing the PocketIC server.
=> fix: PocketIC test flakiness when killing PocketIC server

rs/execution_environment/src/canister_manager.rs, rs/execution_environment/tests/canister_snapshots.rs, rs/replicated_state/src/canister_state/system_state.rs
This PR performs the following changes:
- consolidates cycles and memory usage checks and updates in the management canister by performing the checks in a single function returning `ValidatedCyclesAndMemoryUsage` and the updates in another single function consuming `ValidatedCyclesAndMemoryUsage` as input (to enforce at compile time that checks are always performed before updates);
- checks if cycles for instructions are available before reserving cycles to simplify the validation logic;
- adds a test that taking a snapshot of a canister that would become frozen fails.
=> chore: consolidate cycles and memory usage checks in management canister

rs/replicated_state/src/metadata_state/tests.rs
These tests occasionally time out. This could be caused by computationally expensive generation of IDKG transcripts. Reducing the number of nodes should reduce the amount of computation necessary.
=> test: Reduce the number of nodes contributing to test IDKG transcripts

rs/tests/testnets/io_perf_benchmark.rs
The host feature `HostFeature::IoPerformance` will soon be mandatory for targetting I/O performance testing hosts on Farm.
=> chore: require HostFeature::IoPerformance in the io_perf_benchmark

rs/sns/treasury_manager/src/lib.rs, rs/sns/treasury_manager/treasury_manager.did
This PR extends the `TransactionWitness` API with a new case `Pending`, a placeholder for a transaction witness used to record a transaction attempt before it is completed. This is to implement security recommendations on how to best record transactions in treasury manager implementations.
=> feat(sns_treasury_manager): API to record pending transactions

publish/canisters/BUILD.bazel
This PR enables publishing the Universal Canister Wasm to DFINITY's CDN, enabling projects outside this repo to depend on and use it in advanced testing scenarios, e.g., the emulate a broken 3rd party canister.
=> chore: Publish Universal Canister

rs/tests/consensus/subnet_recovery/BUILD.bazel, rs/tests/consensus/subnet_recovery/common.rs
A lot of the `//rs/tests/consensus/subnet_recovery:...` tests timeout after 15 minutes causing them to have high flakiness rates (some as high as 25%). So this increases the bazel timeout from `long` (900s) to `eternal` (3600s) and the timeout in the test from 15 to 30 minutes.
=> chore: increase timeouts of subnet_recovery tests to reduce flakiness

MODULE.bazel, rs/nervous_system/integration_tests/tests/sns_extension_test.rs
This PR re-enables the final balance assertion in the treasury manager integration test, which now passes due to the fix in the dependency canister being bumped.
=> test(sns): Re-enable final balance assertion in treasury manager test

rs/tests/testnets/io_perf_benchmark.rs
This PR is to leverage the newly-added `IoPerformance` feature supported by Farm https://github.com/dfinity/ic/pull/6027.
If hosts is not specified in environment variables, Farm will automatically select NUM_PERF_HOSTS available hosts.
If hosts is set, NUM_PERF_HOSTS will be ignored.
=> test: `io_perf_benchmark` can select available hosts automatically

rs/nns/cmc/src/main.rs
This is a minor fix that will help future upgrades to be seamless and easy to reason about.
=> fix(cmc): Change version to correctly reflect the State version

rs/tests/message_routing/xnet/BUILD.bazel, rs/tests/message_routing/xnet/xnet_malicious_slices.rs
The 7.6% flaky `//rs/tests/message_routing/xnet:xnet_malicious_slices` was timing out frequently in its `setup` task since it lowered the default 10 minute task timeout to 5 minutes.
So this commit:
* Removes the explicit task timeout settings and relies on the 10 minute defaults.
* Starts the PrometheusVM and IC concurrently to save time.
* Runs this tests pre-master since there's no reason to only run this nightly (it's short and doesn't consume much resources).
=> chore: deflake //rs/tests/message_routing/xnet:xnet_malicious_slices

ic-os/components/misc/guestos-recovery/guestos-recovery-engine/guestos-recovery-engine.sh, rs/tests/consensus/guestos_recovery_engine_smoke_test.rs
Fixes race condition in guestos-recovery-engine permission handling
**Problem**: The recovery engine was intermittently setting incorrect permissions 
on the `ic_registry_local_store` directory, causing the smoke test to fail with 
"Unexpected permissions: drwxr-xr-x. Expected: drwxr-s---"
**Root Cause**: The script captured only owner/group UIDs but not the full permission 
bits (including setgid). When creating the temporary directory:
1. `mkdir` created directory with default permissions (755 = drwxr-xr-x)  
2. `chown` set ownership but didn't preserve the setgid bit
3. `rsync -a` copied these incorrect permissions to the target
4. `setup-permissions` eventually fixed it, creating a timing window for test failures
**Fix**: Capture the target directory permissions before rsync, then …
=> test(node): fix guestos_recovery_engine_smoke_test permission checking

rs/sns/governance/src/governance.rs, rs/sns/governance/unreleased_changelog.md
This PR fixes a bug due to which governance cached metrics could be recomputed once every 10 seconds rather than with the intended rate of once per hour.
=> fix(sns): Ensure governance cached metrics are recomputed once per hour

rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs, rs/sns/governance/canister/governance.did, rs/sns/governance/canister/governance_test.did, rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto, rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs, rs/sns/governance/src/governance.rs, rs/sns/governance/src/governance/assorted_governance_tests.rs, rs/sns/governance/src/governance/proposal_topics_tests.rs, rs/sns/governance/src/pb/conversions.rs, rs/sns/governance/src/proposal.rs, rs/sns/governance/src/topics.rs, rs/sns/governance/src/types.rs
This PR adds the API for executing SNS extension operations, as discussed [here](https://github.com/dfinity/ic/pull/5359).
=> feat(sns): Add API for executing extension operations

rs/nervous_system/tools/release-runscript/src/main.rs
Since the icrc ledger suite has its own release process and they should be published to the SNS-WASM at a specific commit, most likely they shouldn't be released along with other NNS/SNS canisters. Print a warning when the candidates have a mix of the icrc ledger suite and other canisters.
=> feat(nns-tools): Add a warning when the release candates contain a mix of icrc ledger suite and other canisters

ic-os/components/misc/guestos-recovery/guestos-recovery-engine/guestos-recovery-engine.sh, ic-os/guestos/envs/recovery-dev/defs.bzl, rs/recovery/src/lib.rs, rs/recovery/src/steps.rs
`tar -z` actually uses gzip ([source](https://man7.org/linux/man-pages/man1/tar.1.html#:~:text=%2Dz%2C%20%2D%2Dgzip%2C%20%2D%2Dgunzip%2C%20%2D%2Dungzip%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20Filter%20the%20archive%20through%20gzip(1).)).
`tar --zstd` was the one we wanted ([source](https://man7.org/linux/man-pages/man1/tar.1.html#:~:text=%2D%2Dzstd%20Filter%20the%20archive%20through%20zstd(1).)).
=> fix(recovery): use zstd instead of gzip

rs/execution_environment/src/execution_environment.rs, rs/https_outcalls/client/src/client.rs
There are two log lines which need to be "linked" via an ID corresponding to the request.
However one of them logs the callback ID corresponding to the canister call, while the other logs the ID corresponding to the request from the management canister. (which is updated [here](https://github.com/dfinity/ic/blob/e9f4cf612cb649099c2b37f97e761b3362e39cbb/rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs#L244)).
Those IDs are pretty much always corresponding to different requests.
=> fix: Log sender reply callback instead of request ID

rs/tests/driver/src/driver/group.rs, rs/tests/driver/src/driver/vector_vm.rs
We used to create relative links, which if shared and viewed at a later time, may not show the logs at all. This change uses absolute times and produces links like the following:
```bash
https://kibana.testnet.dfinity.network/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:'2025-07-30T22:53:05.332Z',to:now))&_a=(columns:!(MESSAGE,ic_subnet,ic_node),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,field:ic,index:testnet-vector-push,key:ic,negate:!f,params:(query:small--1753915985067),type:phrase),query:(match_phrase:(ic:small--1753915985067)))),hideChart:!f,index:testnet-vector-push,interval:auto,query:(language:kuery,query:''),sort:!(!(timestamp,desc)))
```
=> chore: using absolute time to determine kibana links

Cargo.lock, rs/ic_os/dev_test_tools/setupos-disable-checks/src/main.rs, rs/ic_os/linux_kernel_command_line/BUILD.bazel, rs/ic_os/linux_kernel_command_line/Cargo.toml, rs/ic_os/linux_kernel_command_line/src/lib.rs
- Add new `get_argument` method
- Replace `TryFrom` with `FromStr` which is a more idiomatic choice for parsing
=> feat: Improvements to the linux_kernel_command_line lib

ic-os/components/init/bootstrap-ic-node/bootstrap-ic-node.sh
New ✨:
```
root@guest-52220F4D8CD8:~# ls -lah /var/lib/ic/data/
total 12K
drwxr-xr-x. 9 ic-replica nogroup                  203 Jul 30 16:31 .
drwxr-xr-x. 5 root       root                    4.0K Jul 30 16:31 ..
drwxr-s---. 2 ic-replica nonconfidential            6 Jul 30 16:31 cups
drwxr-s---. 2 ic-replica ic-consensus-pool          6 Jul 30 16:31 ic_consensus_pool
drwxr-s---. 3 ic-replica ic-registry-local-store   24 Jul 30 16:31 ic_registry_local_store
drwxr-s---. 3 ic-replica nonconfidential           25 Jul 30 16:31 ic_state
drwxr-x--x. 2 ic-replica ic-replica                 6 Jul 30 16:31 images
-r--r--r--. 1 ic-replica nogroup                  240 Jul 30 16:31 nns_public_key.pem
-r--------. 1 ic-replica nogroup                  223 Jul 30 16:31 node_operator_private_key.pem …
```
=> fix: Fixup bootstrap permissions

MODULE.bazel
This version was shipped with Ubuntu 20.04.
=> chore: Bump glibc version to 2.31

rs/tests/message_routing/xnet/xnet_compatibility.rs
Currently, this test tends to be rather flaky. A major contributing factor is the need to perform both an upgrade and a downgrade of the guestOS version, requiring potentially long downloads of the respective images. Depending on which servers the file downloads resolve to, this can result in long transatlantic transfers - this is the case for the recent peak shown in the plot below, which displays download times from recent test runs. Similar peaks have been observed in the past, and in general there is a high discrepancy between the median and worst-case download times, as can also be noted from the same plot.
Internally, individual downloads are already limited to 600 seconds, but the test requires more than that to complete both downloads, perform the upgrade and downgrade, and run …
=> chore: Increase total test timeout for `xnet_compatibility` test

ic-os/components/upgrade/grub.sh, ic-os/components/upgrade/manageboot/manageboot.sh
`manageboot.sh confirm` does not synchronise the updated `/boot/grub/grubenv` to disk in all cases. This means that if a node is killed after `manageboot.sh confirm` it will boot to the previous version. This is causing massive flakiness in all system-tests that perform upgrades (like the `//rs/tests/consensus/upgrade:...` tests).
This is fixed by calling `sync` in `write_grubenv` right after writing `/boot/grub/grubenv`.
Since we now sync there we can remove the sync in `manageboot.sh upgrade-commit`.
=> fix: ensure /boot/grub/grubenv is always synced after writing

bazel/noble.lock.json
This commit is the result of `bazel run @noble//:lock` which only fixed the indentation in `bazel/noble.lock.json`.
=> chore: update bazel/noble.lock.json

packages/pocket-ic/src/nonblocking.rs
This PR fixes the PocketIC library to not override canister upgrade options so that upgrading a Motoko EOP canister fails due to not persisting its WASM memory (instead of silently wiping its WASM memory).
=> fix(PocketIC): do not override canister upgrade options

ic-os/components/misc/guestos-recovery/guestos-recovery-engine/guestos-recovery-engine.sh
It's cleaner to have the same processing for the CUP and the local store, i.e. both calling `stat -c '%a' ...` and `chmod` afterwards, instead of `stat -c '%u' /stat -c '%g'` for local store and `chown` for the CUP
=> refactor(node): guestos-recovery-engine permission setting

rs/http_endpoints/nns_delegation_manager/src/nns_delegation_manager.rs
As @schneiderstefan pointed out, requesting paths with prefix `/subnet` (which we are) via `/api/v2/canister` url might be deprecated in the future and it's recommended to use `/api/v2/subnet` instead. See https://internetcomputer.org/docs/references/ic-interface-spec#http-read-state
=> fix: use `/api/v2/subnet/<subnet_id>/read_state` instead of `/api/v2/canister/<effective_canister_id>/read_state` when fetching nns delegation

Cargo.lock, rs/consensus/src/consensus/catchup_package_maker.rs, rs/consensus/src/consensus/validator.rs, rs/consensus/utils/BUILD.bazel, rs/consensus/utils/Cargo.toml, rs/consensus/utils/src/lib.rs, rs/crypto/test_utils/canister_threshold_sigs/src/lib.rs, rs/test_utilities/consensus/src/idkg.rs
Request contexts are now paired with the full pre-signature (instead of only the pre-signature ID). Therefore, we can now determine the registry versions referenced by ongoing signature requests via the transcripts of the paired pre-signature directly, instead of having to look up the corresponding full pre-signature in the payload.
The "oldest" such registry version continues to be included in the CUP, and affects when a node is allowed to leave the subnet. A node may only leave the subnet if it is no longer part of it according to this "oldest" registry version. This ensures that all ongoing signature requests that require the node's contribution may be finished.
=> chore: CON-1547 Use the full pre-signature to determine "oldest registry version in use"

rs/backup/BUILD.bazel
This inlines `DEPENDENCIES` and other dep bundles in `BUILD.bazel` files for the crates under `rs/backup`. This makes the dependencies of each target more explicit and helps analysis tools.
=> chore: inline dependencies in backup crates

rs/tests/nested/src/lib.rs, rs/tests/nested/src/util.rs
Return a `Result` instead of panicking, when the version is not yet found.
=> fix: [NODE-1680] Fix broken nested tests

rs/sns/governance/src/governance.rs, rs/sns/governance/tests/governance.rs, rs/sns/governance/unreleased_changelog.md
The topic follower index was updated incorrectly as the update was based on the new followees rather than the old one. This PR fixes the ordering of the operations so that the index can be updated correctly.
=> fix(sns): Fix an issue where neuron topic follower index is updated incorrectly

rs/node_rewards/canister/src/registry_querier.rs, rs/node_rewards/canister/src/registry_querier/tests.rs, rs/node_rewards/rewards_calculation/src/rewards_calculator/mod.rs, rs/node_rewards/rewards_calculation/src/rewards_calculator_results.rs
Changes:
- Fix rewardable nodes computation to not consider rewardable the day when node is removed from the registry
- Add `avg_rewards` and `avg_coefficient` to Type3 rewards
=> fix(NRC): Fix rewardable nodes computation

.github/actions/bazel/action.yaml, Cargo.Bazel.json.lock, Cargo.Bazel.toml.lock, Cargo.lock, bazel/external_crates.bzl
This upgrades the `autocfg` crate to 1.5.0 in most places* to get a fix for a reproducibility issue in the `num-traits` crate. See: https://github.com/rust-num/num-traits/pull/355#issuecomment-2982171195.
\* There are still some dependencies left on `autocfg-0.1.8` from the `rand-0.6.5`, `rand_chacha-0.1.1` and `rand_pcg-0.1.8` crates. But importantly `num-traits` will now be using `autocfg-1.5.0`.
=> chore: upgrade autocfg to 1.5.0 to fix reproducibility

Cargo.lock, packages/ic-ed25519/BUILD.bazel, packages/ic-ed25519/Cargo.toml, packages/ic-ed25519/src/lib.rs, packages/ic-ed25519/tests/tests.rs, packages/ic-secp256k1/BUILD.bazel, packages/ic-secp256k1/Cargo.toml, packages/ic-secp256k1/src/lib.rs, packages/ic-secp256k1/tests/tests.rs
This embeds the production public master keys for Ed25519 and adds a convenience function for performing fully offline key derivation.
=> feat(crypto): CRP-2810 Add support for subkey derivation to ic-ed25519 and ic-secp256k1

rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Remove the ICVC SNS from the ICRC ledger suite golden state test, since the index canister has run out of cycles and was uninstalled.
=> test(ICRC_Ledger): Remove sunset ICVC SNS from golden state test

ic-os/components/networking/nftables/hostos/nftables.template, rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_sev.xml, rs/ic_os/os_tools/guest_vm_runner/golden/upgrade_guestos.xml, rs/ic_os/os_tools/guest_vm_runner/templates/guestos_vm_template.xml
- Open outgoing SOCKS proxy connections via TCP 1080 port
- Remove locked memory from the SEV config (this is unnecessary according to Rüdiger K and was preventing the VM from starting)
=> chore: HostOS SEV improvements

rs/bitcoin/ckbtc/minter/src/lib.rs, rs/bitcoin/ckbtc/minter/tests/replay_events.rs
Prevent the ckBTC minter from signing a transaction that uses too many inputs to ensure that the transaction remains standard and has a size below the limit of 100kB. This is a stop-gap solution to prevent sending and resubmitting non-standard transactions.
=> fix(ckbtc): prevent signing transaction with too many inputs

ci/src/mainnet_revisions/mainnet_revisions.py, ic-os/dev-tools/hostos-upgrade-tests.sh, mainnet-icos-revisions.json, rs/tests/common.bzl
NODE-1684
The mainnet-icos-revisions.json hash values are all for prod images, but we now support (and use!) dev images in our tests. 
We got lucky (or unlucky) that the change to start using dev mainnet images in tests didn’t break any of our tests. This was because we don’t have any tests upgrading **_TO a mainnet version_**. Our tests only test upgrading **FROM** mainnet versions or test ICs initially deployed with mainnet versions.
If a test tried to upgrade to a mainnet version, it would fail because the node would download a _dev_ upgrade image and see it doesn’t match the expected _prod_ image hash.
I only noticed this when I was testing a node joining a testnet IC with an unassigned registry version that didn’t match the node's own.
=> test(node): Use dev hashes in mainnet-icos-revisions.json

.github/workflows/rosetta-release.yml
This sets the container options required by podman in the `Rosetta Release` workflow. Without these options, our podman wrapper will fail to start.
=> fix: use correct container options for rosetta

Cargo.lock, rs/ic_os/grub/BUILD.bazel, rs/ic_os/grub/Cargo.toml, rs/ic_os/grub/src/lib.rs, rs/ic_os/os_tools/guest_disk/BUILD.bazel, rs/ic_os/os_tools/guest_disk/Cargo.toml, rs/ic_os/os_tools/guest_disk/src/generated_key.rs, rs/registry/proto_data_provider/src/lib.rs, rs/state_manager/src/lib.rs, rs/sys/src/fs.rs, rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs, rs/tests/driver/src/driver/test_env.rs
The new noclobber variant only writes the file if it doesn't exist already. The implementation guarantees that the existence check and the write are done atomically.
=> chore: Add clobber argument to write_atomically and use it in ic_os code

PULL_REQUEST_BAZEL_TARGETS
This adds a tip on how to get a list of files matching `<PATTERN>` to the `PULL_REQUEST_BAZEL_TARGETS` file. 
It uses the same logic as the `ci/bazel-scripts/targets.py` script.
=> chore: add tip how to find matching files to PULL_REQUEST_BAZEL_TARGETS

PULL_REQUEST_BAZEL_TARGETS
This commit defines which code changes should trigger a run of the (long) rejoin_test and xnet_compatiblity tests.
=> test: Run some MR long tests sometimes

rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
=> doc(nns): Say that Topic.TOPIC_UNSPECIFIED is not applicable to Governance/SNS/Neuron's fund

ci/bazel-scripts/targets.py
Triggered by [this code review](https://github.com/dfinity/ic/pull/6329#discussion_r2284662305), it's important that targets in `PULL_REQUEST_BAZEL_TARGETS` are checked for non-emptiness after excluding all `manual` targets. That will prevent mistakes like including a non-colocated variant of a colocated test like `//rs/tests/consensus/backup:backup_manager_upgrade_test` (which is automatically tagged as `manual`) instead of it's colocated variant `//rs/tests/consensus/backup:backup_manager_upgrade_test_colocate`.
=> test: check if targets in PULL_REQUEST_BAZEL_TARGETS are non-empty after excluding all manual targets

rs/tests/boundary_nodes/BUILD.bazel, rs/tests/consensus/BUILD.bazel, rs/tests/consensus/backup/BUILD.bazel, rs/tests/consensus/subnet_recovery/BUILD.bazel, rs/tests/consensus/tecdsa/BUILD.bazel, rs/tests/consensus/upgrade/BUILD.bazel, rs/tests/financial_integrations/rosetta/BUILD.bazel, rs/tests/networking/BUILD.bazel, rs/tests/research/BUILD.bazel, rs/tests/system_tests.bzl
System-test colocation has been very stable for a long time and many system-tests and performance tests rely on it so I declare it no longer experimental by renaming the `experimental_system_test_colocation` tag to `colocate`.
=> chore: rename the experimental_system_test_colocation to colocate

rs/tests/testnets/io_perf_benchmark.rs
This saves about 43 minutes when running the io perf tests. Most of the time was spent writing zeros moving the GuestOS image onto the SSDs.
---
When GuestOS first boots, it will create a new encrypted volume with all of the remaining space on disk. We already provide the entire `hostlvm/guest` to the VM, so instead of writing/seeking through the entire 5TiB of zeroes, we only need to clear signatures and write the image to the front of the drive.
=> feat: [NODE-1686] Speed up perf tests

rs/boundary_node/ic_boundary/src/bouncer/exec.rs, rs/boundary_node/ic_boundary/src/bouncer/firewall.rs, rs/boundary_node/ic_boundary/src/bouncer/mod.rs, rs/boundary_node/ic_boundary/src/check.rs, rs/boundary_node/ic_boundary/src/core.rs, rs/boundary_node/ic_boundary/src/dns.rs, rs/boundary_node/ic_boundary/src/http/handlers.rs, rs/boundary_node/ic_boundary/src/http/middleware/process.rs, rs/boundary_node/ic_boundary/src/http/middleware/retry.rs, rs/boundary_node/ic_boundary/src/http/mod.rs, rs/boundary_node/ic_boundary/src/metrics.rs, rs/boundary_node/ic_boundary/src/persist.rs, rs/boundary_node/ic_boundary/src/rate_limiting/fetcher.rs, rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs, rs/boundary_node/ic_boundary/src/rate_limiting/mod.rs, rs/boundary_node/ic_boundary/src/routes.rs, rs/boundary_node/ic_boundary/src/snapshot.rs, rs/boundary_node/ic_boundary/src/tls_verify.rs
* Split the table into two parts:
- Canister ranges with a length of 5 and shorter (this is hardcoded for now) are expanded into a direct canister ID to subnet mapping in the hash table
- The rest will go into a sorted array and will be looked up using a binary search as before
- The lookups consult the hash table first and then do a binary search if not found
* Refactor the table itself to return `Arc<Subnet>` directly instead of `RouteSubnet` that was redundant. `RouteSubnet` was simplified and renamed to `Route`.
=> chore(BOUN-1456): ic-boundary routing table improvements

ic-os/components/hostos.bzl, ic-os/hostos/context/Dockerfile
The dev-cert is necessary for the dev HostOS to contact the mock server used in nns_recovery_test
=> test(node): include dev-cert in dev hostos

rs/tests/run-p8s.nix, rs/tests/run-p8s.sh
This commit makes sure the `rs/tests/run-p8s.sh` script works again.
=> chore: update rs/tests/run-p8s.sh and support --grafana-dashboards-dir

rs/tests/driver/src/driver/prometheus_vm.rs
When system-tests request to `download_prometheus_data_dir_if_exists()` at the end of their tests the p8s service is stopped after which its data directory is tarred. However users expect that p8s will keep running when they use `--keepalive` so this commit restart p8s right after tarring its datadir.
=> chore: in system-tests start p8s again after tarring its datadir

.github/workflows/ci-notify-slack.yml
This PR sanitizes pull request titles in Slack notifications to prevent broken messages when titles contain characters like < > &.
Adds a sanitize step before posting the message so all notifications display correctly.
=> ci: fix slack notifications by sanitizing titles with < > &

rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs
This supports dynamically enabling the download of p8s data in the `tecdsa_performance_test` by setting the `DOWNLOAD_P8S_DATA` environment variable and documents how to inspect metrics of system-tests after the test has finished.
=> chore: support dynamically downloading the p8s data and document how to use Grafana dashboards locally

rs/execution_environment/src/execution/install_code/tests.rs, rs/execution_environment/src/execution_environment/tests.rs, rs/replicated_state/src/canister_state/execution_state.rs
This PR replaces an outdated hard-coded constant 8 by `size_of::<Global>()` in the computation of execution state size. This change is consistent with the [value](https://github.com/dfinity/ic/blob/abbed6b27a69f85f3ff539ed9a214faa666e1299/rs/replicated_state/src/canister_snapshots.rs#L656) in the computation of snapshot size.
=> fix: replace outdated hard-coded constant by size_of::<Global>()

.github/workflows/slack-workflow-run.yml
This PR sets up alerts sent to `#eng-nns` for failed CI runs on automatically generated PRs updating mainnet canister versions such as this [one](https://github.com/dfinity/ic/pull/6365). This PR also fixes the workflow name to be "CI Main".
=> chore: set up slack alerts for CI failures on ic-nervous-system-wasms

rs/sns/governance/src/extensions.rs, rs/sns/governance/src/governance.rs, rs/sns/governance/src/proposal.rs
This improves the validation for the proposal submission, by using the same function that's used for validation which is more thorough and uses more context than the original validation function.
=> feat(sns): Use same validation function for proposal creation as execution

rs/config/src/embedders.rs, rs/drun/src/main.rs, rs/embedders/benches/embedders_bench/src/lib.rs, rs/embedders/fuzz/src/compile.rs, rs/embedders/fuzz/src/differential.rs, rs/embedders/fuzz/src/ic_wasm.rs, rs/embedders/fuzz/src/imports.rs, rs/embedders/fuzz/src/wasm_executor.rs, rs/embedders/fuzz/src/wasmtime.rs, rs/embedders/fuzz/src/ws2wasm.rs, rs/embedders/src/wasm_utils/validation.rs, rs/embedders/tests/instrumentation.rs, rs/embedders/tests/validation.rs, rs/embedders/tests/wasmtime_embedder.rs, rs/embedders/tests/wasmtime_random_memory_writes.rs, rs/execution_environment/benches/lib/src/common.rs, rs/execution_environment/fuzz/fuzz_targets/execute_ic_wasm.rs, rs/execution_environment/fuzz/fuzz_targets/execute_system_api.rs, rs/execution_environment/src/canister_manager/tests.rs, rs/execution_environment/tests/execution_test.rs, rs/execution_environment/tests/hypervisor.rs, rs/pocket_ic_server/src/nonmainnet_features.rs, rs/test_utilities/execution_environment/src/lib.rs
The wasm64 feature has been enabled for a long time and all tests etc already expect it to be enabled. Removing the flag as it's not needed anymore.
The bulk of changes are in tests/fuzzers to remove enabling the flag in the config.
=> chore: Remove wasm64 feature flag

rs/rosetta-api/icrc1/src/config.rs, rs/rosetta-api/icrc1/src/lib.rs, rs/rosetta-api/icrc1/src/main.rs
Makes the CLI arguments of ICRC1 Rosetta more testable and adds unit tests.
It introduces a `Config` struct, which represents the values of the CLI arguments after being parsed.
This is a prelude to adding the `--environment` preset to the CLI as we had done with ICP Rosetta.
=> test: improve testing of ICRC1 Rosetta CLI args [FI-1784]

rs/tests/networking/BUILD.bazel
`//rs/tests/networking:nns_delegation_branch_nns_version_test` is quite flaky because it runs into timeouts due to the subtest `nns_delegation_on_app_subnet_test` which can take over 10 minutes eating up the 15 minute time budget of the whole test.
=> fix: increase timeout of nns_delegation_branch_nns_version_test to reduce flakiness

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
The cargo jobs in CI Main do not trigger on `workflow_call` which means that they won't run as part of Release Testing:
* `cargo-clippy-linux`: [example non run](https://github.com/dfinity/ic/actions/runs/17034304497/job/48283183248)
* `cargo-build-release-linux`: [example non run](https://github.com/dfinity/ic/actions/runs/17034304497/job/48283183285)
It's important they do run as part of release testing since we want our release to be buildable by cargo. So this adds the `||  github.event_name == 'workflow_call'` condition to both steps.
=> fix: ensure the cargo jobs run on Release Testing

rs/embedders/src/wasmtime_embedder/system_api/routing.rs, rs/execution_environment/src/canister_manager.rs, rs/execution_environment/src/execution_environment.rs, rs/messaging/src/routing/stream_builder.rs, rs/messaging/src/routing/stream_builder/tests.rs, rs/messaging/src/routing/stream_handler.rs, rs/messaging/src/routing/stream_handler/tests.rs, rs/pocket_ic_server/src/pocket_ic.rs, rs/registry/routing_table/src/lib.rs, rs/registry/routing_table/src/tests.rs, rs/replicated_state/src/metadata_state.rs, rs/replicated_state/src/replicated_state.rs, rs/state_manager/src/manifest/split.rs
This commit removes `RoutingTable::route`, which was used to route messages to the correct subnet.
The difference to the still existing `RoutingTable::lookup_entry` was that `route` would additionally consider the case where the target is a subnet id instead of a canister id. However, previously this was implemented by scanning over all canister ranges and checking if the input occurs as the subnet id for any range. There are two issues with this, which this commit both solves:
1. As it's a linear scan, route was `O(n)`, where n is the number of ranges in the routing table. Currently `n` is small, but will grow with the upcoming canister migration feature.
2. There is a theoretical edge case of subnets with no ranges assigned to them. It was not possible to route to such a subnet.
This …
=> perf: Replace `RoutingTable::route` by `NetworkTopology::route`

publish/canisters/BUILD.bazel
Move the ICP and ICRC ledger archive canisters from the `COMPRESSED_CANISTERS` list into the regular `CANISTERS` for building and publishing canisters. Since all canisters are compressed these days, it doesn't seem necessary to have the ledger archives in the separate list, and having them in the `CANISTERS` list also means that their `.did` files are also bundled and published.
=> chore(Ledger_archives): No special COMPRESSED_CANISTERS treatment for ledger archives

rs/tests/nested/src/lib.rs
Removing version compatibility assert while we work on a more comprehensive fix for mainnet image support: https://github.com/dfinity/ic/pull/6285
=> fix(node): remove setupos/guestos mainnet version assert

packages/ic-ed25519/CHANGELOG.md, packages/ic-secp256k1/CHANGELOG.md
Add missing entries for `PublicKey::derive_mainnet_key` to the changelogs of ic-ed25519 and ic-secp256k1. It seems this was forgotten in https://github.com/dfinity/ic/pull/6173 and https://github.com/dfinity/ic/pull/6262.
=> chore(crypto): CRP-2810 add missing PublicKey::derive_mainnet_key to changelogs

rs/tests/networking/BUILD.bazel
This test is often timing out after 900s so let's increase its timeout to `eternal` (1 hour).
=> fix: increase timeout of the query_workload_long_test to reduce flakiness

rs/tests/boundary_nodes/BUILD.bazel
This test is often timing out after 900s so to reduce flakiness this increases the timeout to `eternal` which is 1 hour.
=> fix: increase timeout of the api_bn_update_workload_test to reduce flakiness

rs/canister_sandbox/src/protocol/sbxsvc.rs, rs/canister_sandbox/src/sandbox_server.rs, rs/cycles_account_manager/src/lib.rs, rs/embedders/fuzz/src/wasm_executor.rs, rs/embedders/src/wasmtime_embedder/tests.rs, rs/embedders/tests/common/mod.rs, rs/embedders/tests/system_api.rs, rs/embedders/tests/wasmtime_random_memory_writes.rs, rs/execution_environment/benches/lib/src/common.rs, rs/execution_environment/src/canister_manager/tests.rs, rs/execution_environment/src/execution/call_or_task/tests.rs, rs/execution_environment/src/execution_environment.rs, rs/execution_environment/src/query_handler.rs, rs/execution_environment/src/scheduler.rs, rs/execution_environment/src/scheduler/test_utilities.rs, rs/execution_environment/src/scheduler/tests.rs, rs/execution_environment/tests/execution_test.rs, rs/execution_environment/tests/hypervisor.rs, rs/interfaces/src/execution_environment.rs, rs/state_machine_tests/src/lib.rs, rs/test_utilities/embedders/src/lib.rs, rs/test_utilities/execution_environment/src/lib.rs
This PR refactors `SubnetAvailableMemory` by splitting its constructor `new` into a pair of constructors:
- `new_for_testing`: no scaling factor applied in tests that create `SubnetAvailableMemory` manually (only to be used in tests);
- `new_scaled`: used internally in the execution environment to apply the scaling factor `self.scheduler_cores` (renamed from `self.resource_saturation_scaling` to make the semantics of the value clearer);
removing the division operator on `SubnetAvailableMemory` (an instance of `SubnetAvailableMemory` should be created with an appropriate scaling factor and not rescaled later) and the scaling factor as an explicit field of `SubnetAvailableMemory` (since `SubnetAvailableMemory` is always scaled with the same scaling factor).
This way, we scale …
=> chore: refactor SubnetAvailableMemory

rs/artifact_pool/src/consensus_pool_cache.rs, rs/consensus/idkg/src/payload_builder/pre_signatures.rs, rs/consensus/idkg/src/test_utils.rs, rs/consensus/idkg/src/utils.rs, rs/interfaces/src/consensus_pool.rs, rs/types/types/src/consensus/idkg/common.rs
This PR adds a function to count the total number of available pre-signatures that are stored in the state at a given height, and all payloads above the state height.
The function is currently unused. In the future it will be needed to determine the number of additional pre-signature creations that we should start for each stash.
Counting the number of pre-signatures correctly additionally relies on https://github.com/dfinity/ic/pull/6308, which ensures that all blocks above the certified height are part of the `IDkgBlockReader`.
=> feat: CON-1571 Count the total number of available pre-signatures in the state and blockchain

.github/workflows-source/ci-main.yml, .github/workflows-source/schedule-daily.yml, .github/workflows/ci-main.yml, .github/workflows/schedule-daily.yml, rs/pocket_ic_server/BUILD.bazel
This PR is a follow-up to #6443 (please see that PR description for more context). Upon failures, a slack alert to #pocket-ic is sent.
=> chore(PocketIC): make external types tests run on schedule

rs/consensus/idkg/src/payload_builder/pre_signatures.rs
This PR introduces a struct that will allow us to order pre-signature stashes by their priority. Specifically, stashes with a proportionally lower fill level receive a higher priority. Ties between stashes with the same proportional fill level are broken by comparing the key IDs of the stashes instead.
This structure will allow us to determine for which stash the next pre-signature creation should be started. In the future, consensus will start the creation of new pre-signatures for the stash with the highest priority (meaning the lowest fill level) until the maximum capacity for creating more pre-signatures is reached.
=> feat: CON-1530 Introduce a way to order pre-signature stashes by their priority (lowest fill level)

rs/tests/query_stats/lib/src/aggregation.rs
In the test, we update a universal canister to contain some data. Then we query each node individually to return the data.
Occasionally, this fails, since a single node might be behind, and therefore might serve outdated data.
This PR sets the waiting time from 2 secs to 5 secs, which hopefully makes the test more robust.
=> test(consensus): Make query_stats_basic test more stable

rs/tests/financial_integrations/rosetta/BUILD.bazel, rs/tests/message_routing/xnet/BUILD.bazel
`test_timeout = "long"` is the [default](https://sourcegraph.com/github.com/dfinity/ic/-/blob/rs/tests/system_tests.bzl?L210) for system-tests so let's not set it explicitly.
=> chore: remove explicit settings of test_timeout = "long" since it's the default

rs/http_utils/BUILD.bazel
This inlines `DEPENDENCIES` and `DEV_DEPENDENCIES` in `rs/http_utils/BUILD.bazel`. This makes the dependencies of each target more explicit and helps analysis tools.
=> chore: inline dependencies in http_utils

rs/embedders/fuzz/src/compile.rs, rs/embedders/fuzz/src/ic_wasm.rs, rs/execution_environment/fuzz/fuzz_targets/execute_ic_wasm.rs, rs/execution_environment/fuzz/fuzz_targets/execute_system_api.rs
The previous [PR](https://github.com/dfinity/ic/pull/6354) that cleaned up the embedder flag for enabling memory64 missed a few things:
1. Setting up the test environment can be made easier in some execution fuzz tests as we do not need to differentiate between an embedder that allows 32-bit only or 64-bit Wasms (missed as there was no complaint about the unused bool that controlled whether the embedder enables `wasm64`).
2. While `SystemApiModule` was correctly producing both 32-bit and 64-bit Wasms with the respective imports of the system API, `ICWasmModule` and `MaybeInvalidModule` were inadvertently changed to only include the 64-bit version of the system API. Technically, this works but it's better to keep the behaviour closer to what we had before where for 32-bit Wasms we import …
=> fix: Some more cleanups in execution fuzzers

Cargo.lock, rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs, rs/tests/consensus/tecdsa/tschnorr_message_sizes_test.rs, rs/tests/consensus/tecdsa/utils/BUILD.bazel, rs/tests/consensus/tecdsa/utils/Cargo.toml, rs/tests/consensus/tecdsa/utils/src/lib.rs, rs/tests/driver/BUILD.bazel, rs/tests/driver/Cargo.toml, rs/tests/driver/src/util.rs, rs/tests/test_canisters/signer/BUILD.bazel, rs/tests/test_canisters/signer/Cargo.toml, rs/tests/test_canisters/signer/src/lib.rs, rs/tests/test_canisters/signer/src/main.rs, rs/tests/test_canisters/signer/src/signer.did
This PR uses the non-depecrated API from ic-cdk 0.18 in `ic-signer`, the signer canister. In particular, the API now supports VetKD, allowing us to remove the dependency to `ic-management-canister-types` and the manual implementation of `vetkd_derive_key`.
=> chore(test): bump signer canister to ic-cdk 0.18

rs/execution_environment/src/scheduler/scheduler_metrics.rs, rs/execution_environment/src/scheduler/threshold_signatures.rs
Under normal circumstances, consensus makes sure to never deliver any pre-signatures to execution that would exceed the maximum configured number of pre-signatures in the stash.
However, in case there is a bug in consensus, it would be bad to fill up the pre-signature stash endlessly. Therefore, this PR additionally enforces the maximum pre-signature stash size in the execution layer. Any pre-signature exceeding the maximum size will be purged, and trigger a warning + metric increase.
The same situation may occur naturally, if the maximum stash size was reduced via NNS proposal. Before this PR, the pre-signature stash would have remained at the previous configured size, until the entire stash is purged and re-generated as part of the next key rotation. Now, the stash will be trimmed to …
=> feat: CON-1559 Purge pre-signatures that exceed the maximum stash size

rs/state_manager/src/tip.rs
As we increase the state size, we need to adjust the LSMT merge strategy to be not too aggressive unless needed. I.e. we want to avoid blocking the checkpointing unless we have to do it in order to keep the limits on storage overhead and number of files.
=> feat: Soft limit for merge size [MR-695]

.github/workflows/tag-release.yml
This PR adds pocket-ic ARM binaries to the release and removes drun binaries (the Motoko team was the last user of drun, so it's safe to remove it. In a future PR we will also remove the drun code).
=> chore: add arm64 pocket-ic binaries releases

rs/boundary_node/ic_boundary/src/test_utils.rs, rs/determinism_test/src/setup.rs, rs/drun/src/lib.rs, rs/messaging/src/message_routing/tests.rs, rs/nns/integration_tests/src/registry_get_changes_since.rs, rs/nns/test_utils/src/registry.rs, rs/orchestrator/registry_replicator/src/internal_state.rs, rs/prep/src/internet_computer.rs, rs/registry/regedit/src/protobuf.rs, rs/state_machine_tests/src/lib.rs
The old routing table format is no longer read by the clients, and it's no longer validated by the registry client in the previous PR (#6034). This PR stops preparing the routing table with the "routing_table" key. This cannot be done at the same time as the previous PR because some tests run by CI uses the mainnet registry canister, so they won't pass until the previous PR gets into the mainnet.
=> chore: Stop preparing routing table in the old format outside of production

rs/bitcoin/ckbtc/minter/BUILD.bazel
The P90 duration of the `//rs/bitcoin/ckbtc/minter:ckbtc_minter_replay_events_tests` is over 13 minutes which is higher than our 5 minute maximum. So let's tag this as a `long_test` to not run it on PRs by default.
If desired this test can be triggered explicitly on certain file changes via [`PULL_REQUEST_BAZEL_TARGETS`](https://github.com/dfinity/ic/blob/master/PULL_REQUEST_BAZEL_TARGETS).
Note that this test does run when "direct" source dependencies of the test are modified. More precisely it runs whenever any of the files returned by the following are modified: 
```
bazel query 'filter("^//", kind("source file", deps(//rs/bitcoin/ckbtc/minter:ckbtc_minter_replay_events_tests, 2)))' 
```
=> chore: tag //rs/bitcoin/ckbtc/minter:ckbtc_minter_replay_events_tests as a long_test

rs/nervous_system/tools/submit-motion-proposal/src/main.rs
When submitting an update call, a request id might be returned rather than the response, and in this case the agent should poll. The `call_and_wait` method does just that.
=> feat(nns): Use call_and_wait rather than call when submitting motion proposal

rs/tests/node/BUILD.bazel
In the week starting on 2025-08-21 the 90th percentile duration of the `//rs/tests/node:...` tests was:
| test | P90 duration |
|---|---|
| //rs/tests/node:root_tests | 6m 41s |
| //rs/tests/node:ipv4_integration_test | 5m 16s |
These are all longer than our 5 minute maximum so let's move them to `long_test`.
If desired this test can be triggered explicitly on certain file changes via [`PULL_REQUEST_BAZEL_TARGETS`](https://github.com/dfinity/ic/blob/master/PULL_REQUEST_BAZEL_TARGETS).
Note that this test does run when "direct" source dependencies of the tests are modified. More precisely it runs whenever any of the files returned by the following are modified: 
```
bazel query 'filter("^//", kind("source file", deps(//rs/tests/node:root_tests, 2)))' 
```
=> chore: tag //rs/tests/node/... as long_test

rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
The test is new and we are still calibrating the limit allowed. The current decrease seems OK.
=> test(nns): Increase the diff allowed for wasm memory decrease after upgrade

rs/tests/message_routing/rejoin_test_large_state.rs, rs/tests/message_routing/rejoin_test_lib/rejoin_test_lib.rs
While taking a look at the state sync system tests, I came along this test, which seems to be similar to what I want to use for the fast state sync benchmark.
However, it seems the test was running much slower than needed.
This PR:
- Parallelizes the calls inside the `modify_canister_heap`, such that the different canisters run in parallel. This speeds up the time to fill them up from 150s to around 40s.
- Sets a shorter DKG interval, from 500 to 25. A large amount of time is spend waiting for cups
- The unit and initial notary delays are set to 200ms
=> test(MR): Speed up rejoin_large_test

rs/nervous_system/common/src/ledger.rs, rs/nns/governance/api/src/types.rs, rs/nns/governance/canister/governance.did, rs/nns/governance/canister/governance_test.did, rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/neuron_lock_tests.rs, rs/nns/governance/src/pb/conversions/mod.rs, rs/nns/governance/tests/governance.rs, rs/nns/governance/unreleased_changelog.md, rs/nns/test_utils/src/state_test_helpers.rs
Similar to SNS, add a `memo: opt nat64` field so that clients can specify a memo when splitting neurons and hence make the subaccount of the child neuron predictable.
=> feat(nns): Add memo for the split neuron command

.github/workflows-source/schedule-daily.yml, .github/workflows/schedule-daily.yml
Send a slack notification to #eng-nns whenever the nightly `nns-tests-nightly` job fails.
=> chore: send a slack notification on nns-tests-nightly failures

Cargo.lock, rs/ic_os/vsock/guest/src/main.rs, rs/ic_os/vsock/vsock_lib/BUILD.bazel, rs/ic_os/vsock/vsock_lib/Cargo.toml, rs/ic_os/vsock/vsock_lib/src/guest/mod.rs, rs/ic_os/vsock/vsock_lib/src/lib.rs
It allows for mocking vsock command invocations in tests.
=> chore: Factor out VSockClient trait

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml, ci/bazel-scripts/targets.py
Previously when a PR only modified dependencies of targets that matched the `EXCLUDED_TEST_TAGS` the `targets.py` script would return these targets but they would then subsequently be filtered out by `--test_tag_filters` which would cause bazel to error with:
```
ERROR: No test targets were found, yet testing was requested
```
This commit fixes that by excluding the targets matching  `EXCLUDED_TEST_TAGS`  inside the `targets.py` script. If a PR only modifies dependencies of targets matching `EXCLUDED_TEST_TAGS` `targets.py` will return no targets causing the bazel action to exit early and thus not invoke bazel preventing the error.
=> fix: filter for excluded tags in targets.py

rs/tests/consensus/upgrade/upgrade_downgrade_app_subnet_test.rs
Similar to https://github.com/dfinity/ic/pull/6356, which bumped the timeout of the `//rs/tests/consensus/upgrade:upgrade_downgrade_nns_subnet_test`, this bumps the timeout of the `//rs/tests/consensus/upgrade:upgrade_downgrade_app_subnet_test` since it frequently runs into a timeout as well.
=> test: bump timeout of the //rs/tests/consensus/upgrade:upgrade_downgrade_app_subnet_test

rs/tests/nns/BUILD.bazel
The 90th percentile duration of the `//rs/tests/nns:nns_dapp_test` was 6 minutes and 22 for the week starting on 2025-08-25. This is longer than our maximum of 5 minutes so this commit tags this test as `long_test` to not run it on PRs by default.
=> chore: tag //rs/tests/nns:nns_dapp_test as long_test

rs/http_endpoints/public/src/call/call_async.rs, rs/http_endpoints/public/src/call/call_sync.rs, rs/http_endpoints/public/src/metrics.rs, rs/http_endpoints/public/tests/load_shed_test.rs
Didn't want to do it in https://github.com/dfinity/ic/pull/6378 because the PR was quite big already
=> chore(canister_migration): [CON-1487] Rename some structs/constants from *CALL_V3* to *SYNC_CALL*

.github/workflows-source/schedule-daily.yml, .github/workflows/schedule-daily.yml
The `Bazel System Test Benchmarks` job of the `Schedule Daily` workflow overlaps with the `Release Testing` workflow causing some load from `Release Testing` to spill over to the `dm1` Performance DC. To prevent this we move `Schedule Daily` an hour earlier to midnight.
=> chore: schedule daily workflow an hour earlier so it doesn't overlap with Release Testing

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
Print the targets to test in `Bazel Test All` which is useful for debugging. The output will look something like:
```
bazel query --keep_going '((((kind(".*_test", //...)) except attr(tags, long_test, //...)) + attr(tags, long_test, rdeps(//..., set(.github/workflows-source/ci-main.yml .github/workflows/ci-main.yml), 2))) + set()) except attr(tags, 'manual|system_test_large|system_test_benchmark|fuzz_test|fi_tests_nightly|nns_tests_nightly|pocketic_tests_nightly', //...)'
Testing the following 974 targets:
//:python-requirements_test
//bazel:buildifier_test
//bazel:gazelle_test
//bazel/candid_integration_tests:candid_integration_tests
//bazel/inject_version_into_wasm_tests:inspect_stamped_trivial_wasm
//ic-os/components:check_unused_components_test
...
```
=> chore: print the bazel targets to test in bazel-test-all

bazel/conf/.bazelrc.build, ic-os/dev-tools/hostos-upgrade-tests.sh, ic-os/guestos/README.adoc, rs/tests/README.md, rs/tests/README_NEW.md, rs/tests/ict/cmd/testCmd.go, rs/tests/ict/cmd/testnetCreateCmd.go
The bazel `systest` config now only enables `--test_output=streamed` which is not enough to warrant a dedicated bazel config. So this commit removes the `systest` config and just sets `--test_output=streamed` where necessary.
=> chore: rm systest bazel config

ci/bazel-scripts/targets.py
Previously the bazel query printed by `targets.py` would wrap the `excluded_tags_regex` in single quotes which would conflict with the single quotes around the whole query preventing easy copy/paste/run in your terminal. So this fixes that by wrapping the  `excluded_tags_regex` in double quotes instead.
Additionally this wraps the modified files (`mfiles`) appearing in the query in double quotes as well to allow files with spaces. We could do even better by doing various kinds of escaping but this is good enough for now. 
Now the printed query looks like:
```
bazel query --keep_going '((((kind(".*_test", rdeps(//..., set("ci/bazel-scripts/targets.py")))) except attr(tags, long_test, //...)) + attr(tags, long_test, rdeps(//..., set("ci/bazel-scripts/targets.py"), 2))) + …
```
=> chore: print bazel query in targets.py with proper quotes

rs/config/src/execution_environment.rs
Enable two staging canisters on the subnet [`io67a`](https://dashboard.internetcomputer.org/network/subnets/io67a-2jmkw-zup3h-snbwi-g6a5n-rm5dn-b6png-lvdpl-nqnto-yih6l-gqe) to have access to the dogecoin adapter:
1. [`bhuiy-ciaaa-aaaad-abwea-cai`](https://dashboard.internetcomputer.org/canister/bhuiy-ciaaa-aaaad-abwea-cai) for Dogecoin mainnet
2. [`bavom-pqaaa-aaaad-abweq-cai`](https://dashboard.internetcomputer.org/canister/bavom-pqaaa-aaaad-abweq-cai) for Dogecoin testnet
=> feat(XC): enable Dogecoin for staging canisters

rs/http_endpoints/public/src/read_state/canister.rs, rs/tests/networking/read_state_test.rs
See the deprecation note in https://internetcomputer.org/docs/references/ic-interface-spec#http-read-state
Note: the paths were allowlisted in https://github.com/dfinity/ic/pull/6152 which has been deployed on mainnet for less than a month, so there shouldn't be many users of it
=> feat: [CON-1578] don't allow requesting `/canister_ranges` paths in `/api/{v2,v3}/canister/<canister_id>/read_state`

rs/tests/nested/src/lib.rs
The introduction of the end-to-end NNS recovery test (https://github.com/dfinity/ic/commit/64da0373b9b0bbfa79b99cb4b55018f6ef94d29c) is very flaky. The reason is that in the case where the DFINITY-owned node is lagging behind (which happens when it is part of the faulty nodes), it could happen that its artifact pool has a finalization height which is lower than the highest certification share height across the subnet. In that case, we ask the `ICReplay` step of the recovery to replay until the latter but it will only replay until the highest finalized block.
Indeed, the recovery tool assumes that the node we download the state from (including the consensus artifact pools) from contains all artifacts (except certifications and certification shares) up to the highest certification share …
=> fix(nns-recovery): choose DFINITY-owned node as one with highest certification share height

rs/p2p/peer_manager/src/lib.rs, rs/p2p/peer_manager/src/metrics.rs, rs/tests/consensus/adding_nodes_to_subnet_test.rs, rs/tests/consensus/tecdsa/tecdsa_add_nodes_test.rs, rs/tests/consensus/utils/src/node.rs
This PR adds two metrics:
- the registry version of the latest subnet topology relevant to P2P
- the registry version of the earliest subnet topology relevant to P2P (this is equivalent to the "oldest registry version in use" by consensus).
Additionally, we use the latter metric to improve the robustness of two system tests (`adding_nodes_to_subnet` and `tecdsa_add_nodes`): 
These tests execute proposals to add nodes to a subnet, and then assert that the added nodes make progress as part of the new subnet. Technically, this isn't enough to ensure that the new nodes indeed joined the _active_ subnet membership, and participate in consensus after a successful resharing of the old membership. The reason is that such an assertion will always pass as long as the new nodes manage to sync …
=> chore: CON-1583 Add a topology version metric and use it in some tests adding nodes

rs/nns/cmc/src/main.rs, rs/nns/cmc/unreleased_changelog.md
This removes transaction_notification and transaction_notification_pb endpoints which are no longer usable, as the corresponding functionality in the ledger has been removed in https://dashboard.internetcomputer.org/proposal/138271.
=> chore(cmc): Remove unreachable functions (ledger removed notify flow)

rs/node_rewards/canister/api/src/provider_rewards_calculation.rs, rs/node_rewards/canister/node-rewards-canister.did, rs/node_rewards/canister/proto/rewards_calculator/pb/v1/types.proto, rs/node_rewards/canister/protobuf/src/gen/rewards_calculator.pb.v1.rs, rs/node_rewards/canister/protobuf/src/lib.rs, rs/node_rewards/canister/src/canister/mod.rs, rs/node_rewards/canister/src/canister/test/get_node_providers_rewards.rs, rs/node_rewards/canister/src/main.rs, rs/node_rewards/canister/src/storage.rs, rs/node_rewards/canister/tests/get_node_providers_monthly_xdr_rewards.rs
Changes:
- Remove historical rewards storage
- Remove APIs for retrieving historical rewards as they will be recomputed whenever is needed. Gov. canister will store breadcrumbs to recompute rewards
=> fix(NPR): Discard historical rewards storage and APIs

Cargo.lock, rs/cross-chain/proposal-cli/BUILD.bazel, rs/cross-chain/proposal-cli/Cargo.toml, rs/cross-chain/proposal-cli/README.adoc, rs/cross-chain/proposal-cli/src/canister/mod.rs, rs/cross-chain/proposal-cli/src/canister/tests.rs, rs/cross-chain/proposal-cli/src/dashboard/mod.rs, rs/cross-chain/proposal-cli/src/dashboard/responses.rs, rs/cross-chain/proposal-cli/src/dashboard/tests.rs, rs/cross-chain/proposal-cli/src/forum/mod.rs, rs/cross-chain/proposal-cli/src/forum/tests.rs, rs/cross-chain/proposal-cli/src/main.rs
As part of the Voting Neuron Grants season 2 teams submitting canister upgrade proposals are required to [create a forum topic](https://forum.dfinity.org/t/nns-proposal-discussions/34492) for every proposal or group of proposals. This PR adds a new functionality to `proposal-cli` to be able to create a new forum topic given one or several proposal IDs.
=> feat(proposal-cli): create forum topic for canister upgrade proposals

.github/workflows/rosetta-release.yml
The `rules_oci` use `crane` under the hood which only understand `docker`-style credentials, so we ask `podman` to use `docker`-compatible credentials when performing `login`.
=> fix: use docker-compatible authentication file

rs/sns/governance/canister/canister.rs
This removes the migration code, since the last SNS Governance canister has been published with the migration.
See https://dashboard.internetcomputer.org/proposal/138281 where the previous change went out.
=> chore(sns): Cleanup SNS migration code

rs/nns/sns-wasm/canister/canister.rs, rs/nns/sns-wasm/src/sns_wasm.rs, rs/nns/sns-wasm/unreleased_changelog.md
The original motivation is to detect when swap finalization fails - since such event starts at the beginning of the SNS lifecycle, we cannot reasonably rely on manually updated list of SNSes. Therefore, we need a way to automatically detect new SNSes, and allow prometheus to scrape metrics from new SNS canisters.
Expose a "/sns_canisters" endpoint similar to [orbit](https://5mxvd-qaaaa-aaaal-ajbkq-cai.raw.icp0.io/metrics/sd) based on `deployed_sns_list`.
=> feat(sns-wasm): Service discovery for SNS canisters

rs/recovery/src/file_sync_helper.rs, rs/recovery/src/ssh_helper.rs, rs/recovery/src/steps.rs
The code breaks if the path to the key file or output directory have a space in them.
A concrete example is by running a system test with a space inside its name. For example, launching a system test with `.add_test(systest!(nns_recovery_test; TestConfig {}))` (which will be the format for NNS recovery tests) gives the path `…/tests/nns_recovery_test (TestConfig {})/ssh/authorized_priv_keys/admin`.
This PR properly escapes the paths (I tested using the path above, and it now works).
=> fix(recovery): escape ic-recovery filepaths

rs/nns/governance/api/src/types.rs, rs/nns/governance/canister/governance.did, rs/nns/governance/canister/governance_test.did, rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/heap_governance_data.rs, rs/nns/governance/src/pb/conversions/mod.rs
The `making_sns_proposal` was used as a lock to prevent making a OpenSnsTokenSwap proposal and a CreateServiceNervousSystem proposal at the same time. Now that the former cannot be made, this lock is useless.
Clean up all definitions and usage of `making_sns_proposal`
=> chore(nns): Clean up making_sns_proposal

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
The "Bazel Test All" job is regularly timing out on master after 2 hours. In most of these cases the "Run Bazel Commands" and "Upload to S3" steps just took too long resulting in the job to be cancelled while running the "Upload to S3" step.
Let's bump the timeout by 30 minutes.
=> fix: bump timeout of bazel-test-all from 120 to 150 minutes

rs/execution_environment/tests/storage_reservation.rs
This PR adds additional tests for storage reservation cycles, covering the scenarios of memory growth both in small steps and large steps.
=> test: more reserved cycles tests

rs/bitcoin/adapter/test_utils/src/rpc_client.rs
Occasionally bitcoind may return "Wallet already loading." for loadwallet RPC call even though all tests were run sequentially and the wallet was already unloaded in the previous test.
To avoid test failures, instead of throwing an error we wait a second for the wallet to finish loading before continue.
=> test(btc-adapter): handle wallet already loading error

packages/pocket-ic/CHANGELOG.md, packages/pocket-ic/src/lib.rs, packages/pocket-ic/src/nonblocking.rs, packages/pocket-ic/tests/icp_features.rs, packages/pocket-ic/tests/tests.rs
This PR
- makes the new function `PocketIcBuilder::with_auto_progress` consistent with the existing function `PocketIc::auto_progress` by making them both take no arguments;
- removes the deprecated function `PocketIc::make_deterministic`.
=> chore(PocketIC): clean up server API

rs/nns/cmc/CHANGELOG.md, rs/nns/cmc/unreleased_changelog.md, rs/nns/governance/CHANGELOG.md, rs/nns/governance/unreleased_changelog.md, rs/nns/sns-wasm/CHANGELOG.md, rs/nns/sns-wasm/unreleased_changelog.md, rs/registry/canister/CHANGELOG.md, rs/registry/canister/unreleased_changelog.md, rs/sns/governance/CHANGELOG.md, rs/sns/governance/unreleased_changelog.md, rs/sns/swap/CHANGELOG.md, rs/sns/swap/unreleased_changelog.md
Update CHANGELOG.md for the release on Sept. 8th, 2025.
- [138369](https://dashboard.internetcomputer.org/proposal/138369)
- [138370](https://dashboard.internetcomputer.org/proposal/138370)
- [138371](https://dashboard.internetcomputer.org/proposal/138371)
- [138372](https://dashboard.internetcomputer.org/proposal/138372)
- [138373](https://dashboard.internetcomputer.org/proposal/138373)
- [138374](https://dashboard.internetcomputer.org/proposal/138374)
=> chore(nervous-system): Update changelog for release 2025-09-09

rs/nns/governance/api/src/proposal_submission_helpers.rs, rs/nns/governance/api/src/types.rs, rs/nns/governance/canister/governance.did, rs/nns/governance/canister/governance_test.did, rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/governance.rs, rs/nns/governance/src/lib.rs, rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/pb/conversions/mod.rs, rs/nns/governance/src/pb/proposal_conversions.rs, rs/nns/governance/src/proposals/deregister_known_neuron.rs, rs/nns/governance/src/proposals/deregister_known_neuron_tests.rs, rs/nns/governance/src/proposals/mod.rs, rs/nns/governance/unreleased_changelog.md, rs/nns/integration_tests/src/known_neurons.rs, rs/nns/test_utils/src/state_test_helpers.rs
There are many known neurons that are no longer active, and currently there is no way to remove them.
Implement a deregister_known_neuron proposal type behind a feature flag.
=> feat(nns): Implement a proposal type DeregisterKnownNeuron behind feature flag

rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs, rs/embedders/src/wasmtime_embedder.rs, rs/embedders/src/wasmtime_embedder/tests.rs, rs/execution_environment/tests/hypervisor.rs, rs/interfaces/src/execution_environment.rs, rs/memory_tracker/src/lib.rs
This PR adds tracking of Wasm page metrics (dirty and accessed) in the memory tracker. This allows for better monitoring and analysis of memory usage patterns specific to Wasm pages.
=> feat: EXC-2032: Add memory tracker Wasm page metrics

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml, WORKSPACE.bazel
Fix to work around [the gold linker bug on aarch64-linux](https://github.com/dfinity/ic/actions/runs/17692688125/job/50290153280?pr=6705) which was introduced when https://github.com/dfinity/ic/pull/6705 merged https://github.com/dfinity/ic/commit/b9221277cd5e0dc9a2cd5af5ed7ddc9aff10e7a3 (chore: bumping edition to 2024):
```
= note: some arguments are omitted. use `--verbose` to show all linker arguments
= note: /usr/bin/ld.gold: internal error in update_erratum_insn, at ../../gold/aarch64.cc:1003
collect2: error: ld returned 1 exit status
```
=> fix: use lld linker on aarch64-linux to work around linker bug

.github/workflows/pocket-ic-tests-windows.yml
The GitHub action `vedantmgoyal9/setup-wsl2` has been dropped and thus this PR switches to `Vampire/setup-wsl`.
=> fix(PocketIC): use Vampire/setup-wsl

rs/p2p/quic_transport/src/connection_handle.rs, rs/p2p/quic_transport/src/lib.rs, rs/p2p/quic_transport/src/metrics.rs, rs/p2p/quic_transport/src/request_handler.rs
For each artifact to be transmitted via a connection between two peers, P2P opens a new and dedicated QUIC stream. The maximum number of concurrent QUIC streams (and therefore the maximum number of artifacts to be transferred in parallel) is controlled by the constant [MAX_CONCURRENT_BIDI_STREAMS](https://sourcegraph.com/github.com/dfinity/ic@1ad8f453823f58e9fd48e251fb7fe30b88a56c89/-/blob/rs/p2p/quic_transport/src/connection_manager.rs?L74).
This PR adds metrics for the number of concurrent incoming/outgoing QUIC streams, which will help us determine how far away we are from reaching the configured maximum. This is especially relevant for IDKG, which transmits a lot of artifacts.
=> chore(p2p): Add metrics for the number of concurrent incoming/outgoing QUIC streams

rs/crypto/benches/idkg.rs
If the benchmark is not actually being run (for example because the user on the command line requested some subset of benchmarks be executed), creating the IDKG test environment is unnecessary work.
=> perf(crypto): In IDKG benchmarks avoid needlessly creating test env

.github/CODEOWNERS
As suggested [here](https://github.com/dfinity/ic/pull/6628#pullrequestreview-3216014815), we would like consensus to be co-owners of the NNS recovery tests.
=> chore: update CODEOWNERS for NNS recovery tests

rs/crypto/benches/idkg.rs, rs/crypto/test_utils/canister_threshold_sigs/src/lib.rs, rs/crypto/tests/canister_threshold_idkg.rs
Updates the canister threshold sig utils so that `generate_key_transcript` directly creates an unmasked key transcript rather than first creating a masked one and then resharing it to unmask it.
This is possible because we now have an IDKG mode to direclty create random unmasked transcripts, but the new approach isn't used everywhere yet. There are likely a few more places where we still do the indirection via the masked random transcript.
The change will (slightly) improve the runtimes of the crypto benchmarks, as this utility is used at a few places in the benchmarks (for both tECDSA and tSchnorr: `bench_sign_share`, `bench_verify_sig_share`, `bench_combine_sig_shares`, `bench_verify_combined_sig`).
Also adjusts some integration tests and benchmarks accordingly.
=> perf(crypto): Generate unmasked key transcript directly in test utils and benchmarks

ci/src/mainnet_revisions/mainnet_revisions.py
Labelling a PR with `CI_ALL_BAZEL_TARGETS` is expensive in terms of time and number of vCPUs used. Since we have [quite a number](https://github.com/dfinity/ic/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fpr-creation-bot-dfinity-ic+label%3ACI_ALL_BAZEL_TARGETS) of automatic PRs changing the `mainnet-*-revisions.json` files which are automatically labelled with `CI_ALL_BAZEL_TARGETS` our CI metrics are worse than necessary (IMHO). 
Let's experiment with not labelling them with `CI_ALL_BAZEL_TARGETS` and see if that causes any issues. If so, we could consider adding certain long_tests to [`PULL_REQUEST_BAZEL_TARGETS`](https://github.com/dfinity/ic/blob/master/PULL_REQUEST_BAZEL_TARGETS) when `mainnet-*-revisions.json` files are changed.
Note that when `mainnet-*-revisions.json` files are …
=> chore: do not label mainnet revision PRs with CI_ALL_BAZEL_TARGETS

ic-os/bootloader/hostos_grub.cfg
NODE-1710
`hostos_grub.cfg` will be edited by node providers in the event of a manual recovery. To make it easier for node providers, the two `linux` commands have been consolidated into a single call. This way, node providers will only have one command to update a single command with the recovery boot parameters.
Unfortunately, for this change to reach mainnet, we will have to bring back the grub-upgrader component and roll out a HostOS upgrade to update the `hostos_grub.cfg`
Updated grub:
=> refactor(node): hostos_grub.cfg to contain only a single linux command

rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_server.rs, rs/crypto/internal/crypto_service_provider/src/vault/test_utils/ni_dkg/fixtures.rs, rs/crypto/node_key_validation/src/tests.rs, rs/crypto/src/sign/threshold_sig/ni_dkg/transcript/tests.rs, rs/types/types/src/crypto/threshold_sig/ni_dkg/transcripts_to_retain.rs
Previously the Rust formatting rules incorrectly assumed that any comments on a line following an item with a trailing comment should always be indented to match the trailing comment.
This is fixed in the Rust 2024 edition; now the formatter incorrectly assumes that any comments on a line following an item with a trailing comment should never be indented to match the trailing comment.
Progress.
=> chore(crypto): CRP-2928 Fix some formatting errors introduced in Rust 2024 Edition conversion

rs/bitcoin/ckbtc/minter/ckbtc_minter.did, rs/bitcoin/ckbtc/minter/src/dashboard.rs, rs/bitcoin/ckbtc/minter/src/lib.rs, rs/bitcoin/ckbtc/minter/src/main.rs, rs/bitcoin/ckbtc/minter/src/management.rs, rs/bitcoin/ckbtc/minter/src/metrics.rs, rs/bitcoin/ckbtc/minter/src/state.rs, rs/bitcoin/ckbtc/minter/src/test_fixtures.rs, rs/bitcoin/ckbtc/minter/src/updates/get_btc_address.rs, rs/bitcoin/ckbtc/minter/src/updates/get_withdrawal_account.rs, rs/bitcoin/ckbtc/minter/src/updates/retrieve_btc.rs, rs/bitcoin/ckbtc/minter/src/updates/tests.rs, rs/bitcoin/ckbtc/minter/tests/replay_events.rs, rs/bitcoin/ckbtc/minter/tests/tests.rs
Follow-up to #6264 to remove the introduced `#![allow(deprecated)]` in the code of the `ic-ckbtc-minter` canister:
1. in [`rs/bitcoin/ckbtc/minter/src/main.rs`](https://github.com/dfinity/ic/blob/3794e29f4a7b0174dd40539262a22ef48bd7d6de/rs/bitcoin/ckbtc/minter/src/main.rs#L1)
2. in [`rs/bitcoin/ckbtc/minter/src/lib.rs`](https://github.com/dfinity/ic/blob/3794e29f4a7b0174dd40539262a22ef48bd7d6de/rs/bitcoin/ckbtc/minter/src/lib.rs#L1)
3. in [`rs/bitcoin/ckbtc/minter/tests/tests.rs`](https://github.com/dfinity/ic/blob/3794e29f4a7b0174dd40539262a22ef48bd7d6de/rs/bitcoin/ckbtc/minter/tests/tests.rs#L1)
The changes in the ckBTC minter API are due to changes in the return type of `get_canister_status`, which is a debug endpoint where backwards-compatibility is not guaranteed.
=> chore(XC): remove deprecation from `ic-cdk` in `ic-ckbtc-minter`

ic-os/components/misc/guestos-recovery/guestos-recovery-upgrader/guestos-recovery-upgrader.sh, rs/tests/nested/nns_recovery/common.rs, rs/tests/nested/src/lib.rs
NODE-1713
We agreed to use full hashes for the NNS recovery rather than the short six-character hashes
=> chore(node): convert version-hash to a full hash

rs/nns/canister_ids.json, rs/nns/constants/src/lib.rs, rs/registry/canister/canister/canister.rs, rs/registry/canister/unreleased_changelog.md
The migration canister [was added to the NNS](https://dashboard.internetcomputer.org/proposal/138487), resulting in a [definitive canister ID](http://[2001:1ab9:f002:5:6801:63ff:feb7:7ad7]:8080/_/dashboard). This PR whitelists that new canister ID to call the registry canister endpoint for canister migration.
=> feat: Whitelist migration canister to call registry endpoint

rs/nns/governance/src/governance.rs, rs/nns/governance/unreleased_changelog.md, rs/nns/integration_tests/src/stop_or_start_canister.rs
The StopOrStartCanister NNS Function is replaced by Action::StopOrStartCanister which uses different topics for different canisters. The ic-admin also always use the latter. This PR makes the NNS Function obsolete.
- Add `NnsFunction::StopOrStartNnsCanister` to `check_obsolete`, suggesting `Action::StopOrStartNnsCanister`
- Update integration tests
=> chore(nns): Clean up StopOrStartCanister as an NNS Function

.github/workflows-source/ci-main.yml, .github/workflows/ci-main.yml
The `bazel-test-macos-intel` is increasingly timing out so let's increase its timeout by 50 minutes to 3 hours.
=> chore: bump timeout of bazel-test-macos-intel to 3 hours

rs/bitcoin/adapter/benches/e2e.rs
Fix bug introduced in #6760 where the benchmark `e2e` for the Bitcoin/Dogecoin adapter was left hanging due to running the gRPC server as a blocking task, although that task never finishes (on purpose).
=> fix(adapter): benchmark hanging due to server blocking thread

rs/execution_environment/src/query_handler.rs
`HttpQueryHandler` was defined earlier in the file and in between there was the implementation of `InternalHttpQueryHandler`. Moving it closer to its own implementation so the flow for the reader feels more natural and it's not broken up.
=> refactor: Move HttpQueryHandler declaration closer to its implementation

rs/state_layout/src/utils.rs, rs/state_manager/src/lib.rs, rs/state_manager/src/state_sync/chunkable.rs, rs/state_manager/tests/state_manager.rs, rs/tests/message_routing/rejoin_test_lib/rejoin_test_lib.rs
In state sync, unchanged files from previous checkpoints or caches should be copied into the scratchpad as efficiently as possible. Currently, this still uses reflink, while LSMT-based checkpointing already uses hardlink for read-only files. 
We should extend the same approach to state sync. Hardlinking is faster at scale (e.g., 100k canisters) and preserves OS page cache, while reflinking creates new inodes and discards OS page cache. To enable this safely, all hardlinked files must remain read-only to protect checkpoint integrity.
Experiments show that hardlink reduces duration of copying 200k files from 28s to 5s.
=> feat: [MR-494] Use hardlink to copy files in state sync

rs/recovery/src/lib.rs
#6901 added a new folder to `/var/lib/ic/data` that is not necessary for recoveries. This PR makes `ic-recovery` ignore it when downloading a node's state.
=> fix(ic-recovery): ignore `ic_adapter` when downloading state

rs/protobuf/def/state/queues/v1/queues.proto, rs/protobuf/src/gen/state/state.queues.v1.rs, rs/protobuf/src/gen/types/state.queues.v1.rs, rs/types/types/src/messages.rs, rs/types/types/src/messages/inter_canister.rs, rs/types/types/src/messages/inter_canister/tests.rs
Introduce the new `Refund` message type; and the `StreamMessage` enum, which will replace `RequestOrResponse` in streams.
=> feat: [MR-719] Introduce `Refund` and `StreamMessage`

rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/api/ni_dkg_errors.rs, rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/groth20_bls12_381/encryption.rs
Enhances the DecryptError::InvalidChunk to include the debug representation of the underlying error. Currently the underlying error is swallowed, but this is useful for debugging.
=> chore(crypto): include underlying error in DecryptError::InvalidChunk

rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2025_09_19.md, rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2025_09_19.md, rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2025_09_19.md
([XC-475](https://dfinity.atlassian.net/browse/XC-475)) Proposals to upgrade the ckBTC ledger suite to [ledger-suite-icrc-2025-09-01](https://github.com/dfinity/ic/releases/tag/ledger-suite-icrc-2025-09-01).
[XC-475]: 475
[XC-475]: https://dfinity.atlassian.net/browse/XC-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XC-475]: https://dfinity.atlassian.net/browse/XC-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(ckbtc): upgrade ledger suite

rs/ethereum/cketh/mainnet/orchestrator_upgrade_2025_09_19.md
([XC-475](https://dfinity.atlassian.net/browse/XC-475)) Proposals to upgrade the ckETH/ckERC20 ledger suite to [ledger-suite-icrc-2025-09-01](https://github.com/dfinity/ic/releases/tag/ledger-suite-icrc-2025-09-01).
[XC-475]: 475
[XC-475]: https://dfinity.atlassian.net/browse/XC-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XC-475]: https://dfinity.atlassian.net/browse/XC-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(cketh/ckerc20): upgrade ledger suite

Cargo.lock, packages/pocket-ic/src/common/rest.rs, packages/pocket-ic/tests/icp_features.rs, rs/pocket_ic_server/BUILD.bazel, rs/pocket_ic_server/Cargo.toml, rs/pocket_ic_server/src/external_canister_types.rs, rs/pocket_ic_server/src/pocket_ic.rs
This PR initializes the cycles account of the anonymous principal with `2^127` cycles if the `cycles_token` feature is requested during PocketIC instance creation. This flow has only been enabled on the cycles ledger recently and thus it is added to PocketIC now.
=> chore(PocketIC): top up anonymous account on cycles ledger

PULL_REQUEST_BAZEL_TARGETS
Since https://github.com/dfinity/ic/pull/6900 changed the `mainnet-icos-revisions.json` file and broke the following upgrade tests:
* `//rs/tests/consensus/backup:backup_manager_downgrade_test_colocate`
* `//rs/tests/consensus/backup:backup_manager_upgrade_test_colocate`
* `//rs/tests/consensus/upgrade:upgrade_downgrade_app_subnet_test_colocate`
It makes sense to run these tests whenever `mainnet-icos-revisions.json` changes to prevent future failures like this.
=> chore: trigger upgrade tests on mainnet-icos-revisions.json changes

rs/ic_os/dev_test_tools/setupos-image-config/src/bin/inject.rs, rs/ic_os/device/src/device_mapping.rs, rs/ic_os/os_tools/guest_vm_runner/src/guest_direct_boot.rs, rs/ic_os/os_tools/guest_vm_runner/src/main.rs, rs/ic_os/sev/src/host/mod.rs, rs/ic_os/vsock/vsock_lib/src/host/hsm.rs
When there is a problem with one of these files, we get better logs if the name contains some information.
=> chore: Add prefix to named temp files in production

.github/workflows/schedule-weekly.yml
This moves weekly secrets to an environment so they can only be accessed on the master branch.
=> feat(IDX): move weekly secrets to env

ic-os/dev-tools/bare_metal_deployment/deploy.py
If wait_func is triggered (when there's no IP address in the BMC info), the test fails. Remove this code path.
=> fix: deploy.py wait_func path and guestos_ipv6_address optionality

rs/tests/networking/BUILD.bazel, rs/tests/networking/state_sync_performance.rs
The state sync performance test has been problems getting stuck on `await_status_is_healthy`.
It seemed to work occasionally, but often, it would get stuck, doing the actual request to the `status` endpoint.
Looking at the logs, sometimes the request was actually made, while other times it was not being made, and the request was not timing out after 6 seconds.
I replaced the call with it's async version and now it seems to work. I do not fully understand the previous behaviour, as I thought, calling `block_on` while already being in an async block should be handled gracefully.
This PR does not reactivate the test yet, as I would like to get a better understanding first.
=> fix(networking): Fix state sync performance test

rs/embedders/src/wasmtime_embedder/system_api/routing.rs, rs/embedders/src/wasmtime_embedder/system_api/sandbox_safe_system_state.rs, rs/execution_environment/src/canister_manager.rs, rs/execution_environment/src/canister_manager/types.rs, rs/execution_environment/src/execution_environment.rs, rs/execution_environment/src/execution_environment/tests.rs, rs/execution_environment/src/execution_environment_metrics.rs, rs/execution_environment/src/ic00_permissions.rs, rs/execution_environment/src/scheduler.rs, rs/execution_environment/tests/dts.rs, rs/execution_environment/tests/execution_test.rs, rs/test_utilities/execution_environment/src/lib.rs, rs/types/management_canister_types/src/lib.rs, rs/types/management_canister_types/tests/candid_equality.rs, rs/types/management_canister_types/tests/ic.did, rs/types/types/src/messages/ingress_messages.rs, rs/types/types/src/messages/inter_canister.rs
Add a management canister endpoint `canister_metadata` ([spec](https://github.com/dfinity/portal/pull/6069))
=> feat: Add a canister_metadata management canister method

rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/tests/mod.rs, rs/nns/governance/unreleased_changelog.md
If a known neuron does not vote on a proposal, this fact should be recorded (`vote = Vote::Unspecified`), and the only way to know that they did not vote is to check the ballots after the voting window. One way is to check the ballots right before they are cleared.
- Record the votes by known neurons right before the ballots are cleared.
=> feat(nns): Record known neuron votes before clearing ballots

rs/ledger_suite/icp/ledger/src/main.rs
For canister `update` endpoints that are exported using `#[export_name]`, the entry point must encase its code in `in_executor_context` as described in [the `cdk-rs` documentation](https://github.com/dfinity/cdk-rs/blob/main/ic-cdk/V18_GUIDE.md#custom-exports-advanced).
=> fix(ICP_Ledger): FI-1872: Add in_executor_context for ICP ledger notify endpoints

rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/BUILD.bazel, rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/icrc3_test_ledger.did, rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/src/main.rs, rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/tests/tests.rs
When disabled, icrc3 is not listed as part of the supported standards when calling `icrc1_supported_standards`.
=> test(ICRC-Ledger): FI-1874: endpoint that disables icrc3 in the test ledger

packages/icrc-ledger-types/CHANGELOG.md, packages/icrc-ledger-types/src/icrc1/account.rs
Add a `try_from_subaccount_to_principal` function that returns an error rather than panicking if the `Subaccount` cannot be converted to a `Principal`.
=> fix(icrc-ledger-types): FI-1866: Add try_from_subaccount_to_principal

rs/execution_environment/tests/canister_snapshots.rs, rs/execution_environment/tests/hypervisor.rs, rs/replicated_state/src/replicated_state.rs, rs/replicated_state/tests/replicated_state.rs
This PR fixes subnet memory taken for canisters with memory allocation: so far their contribution to the `execution` field in `MemoryTaken` was the sum of their memory allocation, canister history, wasm chunk store, and canister snapshots memory usage. However, this leads to accounting for canister history, wasm chunk store, and canister snapshots memory usage twice - once in the memory allocation and one more time separately. This PR fixes that by taking the maximum of the canister memory usage (execution, canister history, wasm chunk store, and canister snapshots memory usage) and memory allocation.
This PR also adds a regression test:
- fill a subnet with canisters having 100 GiB of memory allocation each;
- make the memory allocation of the last canister best-effort;
- grow their …
=> fix: subnet memory taken for canisters with memory allocation

ic-os/components/guestos/init/setup-lvs/setup-lvs.sh, ic-os/components/upgrade/shared-resources/setup-shared-resources/setup-shared-backup.sh
This reverts commit 3d50e3e4346ce38e7146edb94b4fc866ef9047b5 since it causes all system-tests that kill and restart IC nodes to fail.
=> fix: revert "chore: Resize backup LV to 500GB (#6926)"

rs/types/management_canister_types/src/http.rs, rs/types/management_canister_types/src/lib.rs, rs/types/management_canister_types/src/provisional.rs, rs/types/management_canister_types/tests/ic.did
This PR unifies Candid declarations in doc comments for management canister Rust types.
No functional changes, only doc comments.
Changes:
- removes extra parenthesis `(record {...})` with `record {...}`
- consistently uses ` ```text ` in blocks
=> chore: unify management canister doc comments for Rust types

rs/nns/governance/src/governance.rs, rs/nns/governance/src/governance/merge_neurons.rs, rs/nns/governance/src/governance/tests/mod.rs, rs/nns/governance/src/neuron/types.rs, rs/nns/governance/src/neuron/types/tests.rs, rs/nns/governance/tests/governance.rs, rs/nns/governance/unreleased_changelog.md
As we add more and more data into KnownNeuronData (especially links), it becomes more likely that they will make list_neurons exceeds the message size limit (arguable, it was already the case before recent changes).
For list_neurons, not include known_neuron_data in "neuron info" or "full neuron"
=> feat(nns): Stop exposing KnownNeuronData in list_neurons

rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto, rs/nns/governance/src/garbage_collection.rs, rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs, rs/nns/governance/src/heap_governance_data.rs, rs/nns/governance/tests/governance.rs
Since the known neuron voting history involves proposal ids, and the known neurons have committed topics, the topics of the proposals need to be persisted even though we garbage collect proposals for now. Otherwise there will be no way of computing the voting statistics from the voting history, without relying on offline data.
* Add a `topic_of_garbage_collected_proposals` field
* Insert `(proposal_id, topic)` into the map for a garbage collected proposal
=> feat(nns): Archive topics of garbage collected proposals

rs/nns/governance/canister/governance_test.did, rs/sns/governance/canister/governance_test.did
https://github.com/dfinity/ic/pull/6947 removed `governance_test.did` files and generated them with bazel instead. However these files are included in rust code (`include_str!("governance_test.did")`) which means that `cargo clippy` will [fail](https://github.com/dfinity/ic/actions/runs/18238768918/job/51941823743#step:5:2903) on it.
The reason the `cargo clippy` job [succeeded](https://github.com/dfinity/ic/actions/runs/18230285300/job/51912091777) on the PR was that the `cargo clippy` step only runs if `.rs` files have been modified which the PR didn't touch.
To fix the `cargo clippy` job we commit empty `governance_test.did` files.
=> fix: add empty governance_test.did files to make cargo clippy succeed

rs/http_endpoints/nns_delegation_manager/src/nns_delegation_manager.rs
This commit shortens the interval for subnets to refresh their delegation from the NNS from 10 minutes to 5 minutes.
The upcoming canister migration feature is quite sensitive to outdated NNS delegations, as responses to ingress calls to a recently migrated canister are only valid if the delegation reflects the updated routing table.
Canister migrations take at least 5 minutes anyway to protect from replay attacks. It therefore makes sense to also set the delegation update interval to 5 minutes. At the same time, updating delegations is not so costly that we cannot do it every 5 minutes.
=> chore: Shorten NNS delegation refresh interval

rs/execution_environment/src/canister_manager.rs, rs/execution_environment/src/canister_manager/tests.rs, rs/execution_environment/src/canister_manager/types.rs, rs/execution_environment/src/execution/install_code.rs, rs/execution_environment/src/execution/install_code/tests.rs, rs/execution_environment/src/execution_environment.rs, rs/execution_environment/src/execution_environment/tests.rs, rs/execution_environment/src/scheduler.rs, rs/execution_environment/tests/canister_history.rs, rs/execution_environment/tests/hypervisor.rs, rs/interfaces/src/execution_environment.rs, rs/replicated_state/src/canister_state.rs, rs/replicated_state/src/canister_state/system_state.rs
This PR performs the following changes:
- updates subnet available memory after uninstalling code;
- updates subnet available memory after updating canister history;
- adds a new test checking that subnet available memory matches canister memory usage.
=> fix: update subnet available memory after unstalling code and updating canister history

rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto, rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs, rs/replicated_state/src/canister_state/system_state/call_context_manager/proto.rs
This PR makes sure that replicas can [deal with the future](https://github.com/dfinity/ic/pull/7072). 
That is, decode an enum variant from a protobuf file with a future version. See above link for details. 
**Reviewers**: Please review the above PR before approving this one, in case it needs some changes that feed back into this one.
=> feat: [EXC-1848] Enrich `CallOrigin` with method name 1/2

.github/workflows/ci-main.yml
This moves the `python-ci-tests` to run on `ubuntu-latest` instead of self-hosted runners. Apparently it runs without issues.
=> feat(IDX): use gh hosted runner for python tests

rs/nns/cmc/src/main.rs, rs/nns/handlers/lifeline/impl/BUILD.bazel, rs/nns/handlers/root/impl/canister/canister.rs, rs/nns/handlers/root/impl/canister/root.did, rs/nns/integration_tests/src/cycles_minting_canister.rs
There are a few places (root/cmc) not using the ic_cdk_macros without a good reason.
* Use `ic_cdk_macros::query(hidden = true)` for `total_cycles_minted`
* Switch `total_cycles_minted` to return candid rather than protobuf. Note that the current value on the mainnet is at 70% of u64::MAX, so the u64 doesn't make sense anyway. This is a breaking change, but the method has never been exposed (not in .did)
* Use `#[init]` for root
=> refactor(cmc/root): Fix a few places where ic_cdk_macros are not used

.github/workflows/ci-pr-only.yml
In preparation for open-sourcing the IC we are replacing self-hosted runners with gh hosted runners.
=> chore(IDX): replace dependencies-check runner

.github/workflows/ci-main.yml
These two CI jobs are basically identical, just executing different commands, so we combine them into one, so that we can make updates to them more easily.
It also introduces the label `CI_RUN_CARGO_JOBS` in case we want to run the job without making any cargo file changes on our PR.
In the next PR I will move these jobs to gh-hosted runners.
=> refactor(IDX): combine CI cargo jobs

packages/pocket-ic/src/nonblocking.rs, packages/pocket-ic/tests/tests.rs, rs/pocket_ic_server/src/state_api/state.rs
This PR stops all HTTP gateways for a PocketIC instance before deleting that PocketIC instance.
The motivation for this fix is that such HTTP gateways won't work anyway once the PocketIC instance is deleted and thus we could release their resources (e.g., ports).
This PR has been tested by the existing (hardened) test `with_http_gateway_config_and_cleanup_works` since the Rust library is also updated to not explicitly stop an HTTP gateway for a PocketIC instance before deleting the instance (and thus the test ensures that the HTTP gateway is stopped as part of PocketIC instance deletion implemented by this PR).
=> fix(PocketIC): stop HTTP gateways before deleting PocketIC instance

rs/test_utilities/execution_environment/src/lib.rs
This PR refactors the `ExecutionTestBuilder` to hold a `SubnetConfig` so that certain options can be overwritten in tests instead of passing explicitly the options.
One benefit of this is that we don't need to keep adding fields in `ExecutionTestBuilder` as more configuration options are added. We only need to expose a setter to overwrite the config value (similar to existing ones).
Another benefit is that it helps in a further refactoring of using `setup_execution` to create the execution services needed for tests instead of manually doing that to reduce code duplication. `setup_execution` requires a `subnet_config` to be passed so that it creates the services with the right options, so having it already in the `ExecutionTestBuilder` streamlines things (otherwise one would need to …
=> refactor: Use SubnetConfig in ExecutionTestBuilder to group configuration options in tests

packages/pocket-ic/tests/icp_features.rs
The broken test was compensating for the discrepancy in balance calculation between the ledger and index.
https://github.com/dfinity/ic/pull/6508 fixed this discrepancy so both index and ledger have the same balances. Since this PR is not on mainnet yet, we temporarily have to compare against both correct balance (for testing with master) and incorrect (for testing with mainnet).
=> test(pocket-ic): test index and ledger with the same balance

rs/recovery/src/steps.rs, rs/replay/src/cmd.rs, rs/replay/src/lib.rs
The NNS recovery system tests sometimes failed because nodes would take forever to load the NiDKG transcripts from the recovery CUP. The problem was that the latter set the `registry_store_uri` field, which [means](https://github.com/dfinity/ic/blob/a44bcc6d2867d6cbb9e035353d9a0cf5a171c52c/rs/consensus/dkg/src/payload_builder.rs#L516-L520) we were overwriting the registry version of these transcripts with a newer one, effectively corrupting them. As the comment in the link above suggests, this field is used in NNS recovery on *failover* nodes, but the `cmd_get_recovery_cup` function is called only in NNS recovery on *same* nodes. This PR thus unsets this field there.
The bug did not happen very often because [this check](https://github.com/dfinity/ic/blob/fa37988f9a26f6dfa05b1953362c7b0719 …
=> fix(nns-recovery): fix `registry_store_uri` parameter in NNS recovery on same nodes
